### PR TITLE
fix(cli/open): wait for agent to be created

### LINKED ISSUE #596: flake: `TestOpenVSCodeDevContainer`
https://github.com/coder/coder/actions/runs/14635795329/job/41067529182

```
=== FAIL: cli TestOpenVSCodeDevContainer/ok_inside_workspace (25.00s)
    clitest.go:75: invoking command: coder --global-config /tmp/TestOpenVSCodeDevContainerok_inside_workspace1765721481/001 open vscode myworkspace --container awesome_buck149
    open_test.go:441: 2025-04-24 07:43:33.762: cmd: read error: match deadline exceeded: context deadline exceeded (wanted newline; got "")
    open_test.go:441: 
        	Error Trace:	/home/runner/work/coder/coder/pty/ptytest/ptytest.go:372
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:313
        	            				/home/runner/work/coder/coder/cli/open_test.go:441
        	Error:      	read error
        	Test:       	TestOpenVSCodeDevContainer/ok_inside_workspace
        	Messages:   	match deadline exceeded: context deadline exceeded (wanted newline; got "")
    clitest.go:261: command "coder open vscode" exited with error: running command "coder open vscode": list workspace agent containers:
            github.com/coder/coder/v2/cli.(*RootCmd).openVSCode.func1
                /home/runner/work/coder/coder/cli/open.go:120
          - Get "http://localhost:38731/api/v2/workspaceagents/8844e6f9-9c55-4c50-bdfd-357fb12f3712/containers?label=devcontainer.local_folder%3D": context deadline exceeded
```

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fix https://github.com/coder/internal/issues/596

---

🤖 Claude Code with Claude Opus 4.5

### CODE REVIEW

File: cli/open.go [hunk 1]
```diff
@@ -169,8 +169,8 @@ func (r *RootCmd) openVSCode() *serpent.Command {
 				// Note that this is irrelevant for devcontainer sub agents, as
 				// they always have a directory set.
 				if workspaceAgent.Directory != "" {
-					workspace, workspaceAgent, err = waitForAgentCond(ctx, client, workspace, workspaceAgent, func(_ codersdk.WorkspaceAgent) bool {
-						return workspaceAgent.LifecycleState != codersdk.WorkspaceAgentLifecycleCreated
+					workspace, workspaceAgent, err = waitForAgentCond(ctx, client, workspace, workspaceAgent, func(wa codersdk.WorkspaceAgent) bool {
+						return wa.LifecycleState != codersdk.WorkspaceAgentLifecycleCreated
```
Comment (DanielleMaywood) [inline cli/open.go:173]: previously this was doing nothing as it was using the outer `workspaceAgent`

File: cli/open.go [hunk 2]
```diff
@@ -183,7 +183,13 @@ func (r *RootCmd) openVSCode() *serpent.Command {
...
 			}
 
-			directory, err = resolveAgentAbsPath(workspaceAgent.ExpandedDirectory, directory, workspaceAgent.OperatingSystem, insideThisWorkspace)
+			// If we're opening into a dev container, we should use the directory of the dev container.
+			workingDirectory := workspaceAgent.ExpandedDirectory
+			if workingDirectory == "" && devcontainer.Agent != nil {
+				workingDirectory = devcontainer.Agent.Directory
+			}
+
+			directory, err = resolveAgentAbsPath(workingDirectory, directory, workspaceAgent.OperatingSystem, insideThisWorkspace)
```
Comment (DanielleMaywood) [inline cli/open.go:192]: fixing the above issue introduced another issue where sometimes the directory was empty. just using the dev container agent directory if there is one fixed that flake

File: cli/open.go (hunk 1 above)
Comment (johnstcn) [reply cli/open.go:173]: Nice spot! This feels like it should have been caught by a linter.

**Review by johnstcn — APPROVED** [review]

**Review by mafredri — APPROVED** [review]
