### PR TITLE
fix: suppress license expiry warning if a new license covers the gap

### LINKED ISSUE #19498: Upcoming license expiry generates license warnings, even if a newer license exists
If you have a license that's expiring soon, a license warning is generated telling you to contact sales for a renewal.

When you get a new license from sales and load it into Coder, you're expected to leave the old license active without deleting it until the new license kicks in.

During this phase with two licenses added, the older license continues to generate a license warning, even though the newer license will take it's place once we reach the start date of the new license.

We should not generate this warning in this case. I think for now, the simplest solution would be to suppress those warnings if a license would become active before it expires.

### PR DESCRIPTION
**Pull request by deansheather**
Previously, if you had a new license that would start before the current one fully expired, you would get a warning. Now, the license validity periods are merged together, and a warning is only generated based on the end of the current contiguous period of license coverage.

If you have used AI to produce some or all of this PR, please ensure you have read our [AI Contribution guidelines](https://coder.com/docs/about/contributing/AI_CONTRIBUTING) before submitting.

Closes #19498

### CODE REVIEW

**Review by Emyrk — APPROVED** [review]
This makes no changes to the entitlements, just the license expiration warning :+1:

File: enterprise/coderd/license/license_test.go [hunk 1]
```diff
@@ -180,6 +180,109 @@ func TestEntitlements(t *testing.T) {
...
+		require.Len(t, entitlements.Warnings, 0) // suppressed
+	})
+
+	t.Run("Expiration warning not suppressed if new license has gap", func(t *testing.T) {
+		t.Parallel()
+		db, _ := dbtestutil.NewDB(t)
+
+		// Insert the expiring license
+		graceDate := dbtime.Now().AddDate(0, 0, 1)
+		db.InsertLicense(context.Background(), database.InsertLicenseParams{
```
Comment (deansheather) [inline enterprise/coderd/license/license_test.go]: Unchecked error
