### PR TITLE
fix(cli): proactively use active template version when require_active_version is set

### LINKED ISSUE #22030: bug: coder start does not respect template's require_active_version setting
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When a template has `Require workspaces automatically update when started` enabled (`require_active_version = true`), running `coder start` from the CLI (or via the VS Code extension, which calls `coder start` under the hood) starts the workspace with the old template version instead of updating to the active template version.

The web UI and server-side autostart correctly enforce the update, but the CLI does not.

**Impact:**
This also affects the VS Code Coder extension (tested with v1.12.2), which calls `coder start --yes` to start workspaces. Organizations relying on `require_active_version` to enforce template updates on start will find that the policy is not enforced when workspaces are started via the CLI or VS Code extension.

### Relevant Log Output

```shell
N/A
```

### Expected Behavior

`coder start` should update the workspace to the active template version before starting, matching the behavior of the web UI and server-side autostart.

### Steps to Reproduce

1. Create a template with `Require workspaces automatically update when started enabled`
2. Create a workspace from the template
3. Push a new version to the template
4. Stop the workspace
5. Run `coder start <owner>/<workspace>` from the CLI
6. Observe that the workspace starts with the old template version

### Environment

- Host OS:
- Coder version: 2.25.6, 2.26.6, 2.28.6, and 2.29.6 - Tests were performed on these versions but this issue predates these versions.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by f0ssel**
Fixes #22030

## Problem

When a template has `require_active_version = true` and a workspace is outdated, the web UI always shows "Update and start" as the **only** button (for all users including admins), but `coder start` starts with the old version. For admins, this silently succeeds on the stale version. For non-admins, it goes through a clunky 403→retry path. This also affects the VS Code extension, which calls `coder start --yes` under the hood.

## Root Cause

`buildWorkspaceStartRequest()` in `cli/start.go` checks `workspace.AutomaticUpdates == "always"` but ignores `workspace.TemplateRequireActiveVersion`. The server-side autostart already ORs both settings together:

```go
// coderd/autobuild/lifecycle_executor.go
func useActiveVersion(opts, ws) bool {
    return opts.RequireActiveVersion || ws.AutomaticUpdates == "always"
}
```

The CLI was missing the `RequireActiveVersion` check.

## Fix

Add `workspace.TemplateRequireActiveVersion` to the existing OR condition:

```go
// Before:
if workspace.AutomaticUpdates == codersdk.AutomaticUpdatesAlways || action == WorkspaceUpdate {

// After:
if workspace.AutomaticUpdates == codersdk.AutomaticUpdatesAlways || workspace.TemplateRequireActiveVersion || action == WorkspaceUpdate {
```

Now `coder start` and `coder restart` proactively use the active template version when `require_active_version` is set, matching the web UI and server autostart behavior. The 403→retry fallback remains as a safety net but is no longer the primary path for any user.

## Testing

Updated `enterprise/cli/start_test.go` — all user types (owner, template admin, ACL admin, group ACL admin, member) now expect the active version when `require_active_version` is set, and verify the 403→retry message does NOT appear.

### CODE REVIEW

File: enterprise/coderd/workspaces_test.go [hunk 1]
```diff
@@ -251,6 +251,47 @@ func TestCreateWorkspace(t *testing.T) {
...
+			},
+		})
+		memberClient, _ := coderdtest.CreateAnotherUser(t, ownerClient, user.OrganizationID)
+
+		version := coderdtest.CreateTemplateVersion(t, ownerClient, user.OrganizationID, nil)
+		coderdtest.AwaitTemplateVersionJobCompleted(t, ownerClient, version.ID)
+		template := coderdtest.CreateTemplate(t, ownerClient, user.OrganizationID, version.ID, func(ctr *codersdk.CreateTemplateRequest) {
+			ctr.RequireActiveVersion = true
+		})
+		require.True(t, template.RequireActiveVersion)
```
Comment (johnstcn) [inline enterprise/coderd/workspaces_test.go]: suggestion: use `dbgen.Template` / `dbgen.TemplateVersion` which will allow you to set `RequireActiveVersion` directly.

File: enterprise/coderd/workspaces_test.go [hunk 2]
```diff
@@ -251,6 +251,47 @@ func TestCreateWorkspace(t *testing.T) {
...
+		ws, err := memberClient.CreateUserWorkspace(ctx, codersdk.Me, codersdk.CreateWorkspaceRequest{
+			TemplateID: template.ID,
+			Name:       "test-ws",
+		})
+		require.NoError(t, err)
+		coderdtest.AwaitWorkspaceBuildJobCompleted(t, memberClient, ws.LatestBuild.ID)
+
+		ws, err = memberClient.Workspace(ctx, ws.ID)
+		require.NoError(t, err)
+		require.Equal(t, codersdk.AutomaticUpdatesAlways, ws.AutomaticUpdates)
```
Comment (johnstcn) [inline enterprise/coderd/workspaces_test.go]: Also ensure that the template version of the workspace is the active version ID of the template.

File: enterprise/coderd/templates_test.go [hunk 3]
```diff
@@ -727,6 +727,65 @@ func TestTemplates(t *testing.T) {
...
+		// Create workspaces with automatic_updates = "never" (the
+		// default).
+		ws1 := coderdtest.CreateWorkspace(t, memberClient, template.ID, func(cwr *codersdk.CreateWorkspaceRequest) {
+			cwr.AutomaticUpdates = codersdk.AutomaticUpdatesNever
+		})
+		coderdtest.AwaitWorkspaceBuildJobCompleted(t, memberClient, ws1.LatestBuild.ID)
+		ws2 := coderdtest.CreateWorkspace(t, memberClient, template.ID, func(cwr *codersdk.CreateWorkspaceRequest) {
+			cwr.AutomaticUpdates = codersdk.AutomaticUpdatesNever
+		})
+		coderdtest.AwaitWorkspaceBuildJobCompleted(t, memberClient, ws2.LatestBuild.ID)
```
Comment (johnstcn) [inline enterprise/coderd/templates_test.go]: What does testing with two workspaces accomplish here?

File: enterprise/coderd/templates_test.go [hunk 4]
```diff
@@ -727,6 +727,65 @@ func TestTemplates(t *testing.T) {
...
+		// Both workspaces should now have automatic_updates =
+		// "always".
+		ws1, err = memberClient.Workspace(ctx, ws1.ID)
+		require.NoError(t, err)
+		require.Equal(t, codersdk.AutomaticUpdatesAlways, ws1.AutomaticUpdates)
+
+		ws2, err = memberClient.Workspace(ctx, ws2.ID)
+		require.NoError(t, err)
+		require.Equal(t, codersdk.AutomaticUpdatesAlways, ws2.AutomaticUpdates)
+	})
```
Comment (johnstcn) [inline enterprise/coderd/templates_test.go]: Might also be useful to stop the workspace and attempt to start it again without updating. The result should be that the template is on the active version.

**Review by johnstcn — APPROVED** [review]
Changes look good to me.

**Comment by geokat** [comment]
Do we need a DB migration to make sure already existing workspaces are fixed too? Otherwise they won't be fixed until the admin re-toggles the setting for the template?

File: coderd/workspaces.go [hunk 5]
```diff
@@ -633,6 +633,15 @@ func createWorkspace(
 		}
 	}
 
+	// When the template requires the active version and the caller
+	// did not explicitly request a specific update policy, default
+	// to "always" so the DB value matches the enforced behavior.
+	// We only override the implicit default to avoid overriding an
+	// explicit choice by an admin creating on behalf of a user.
```
Comment (geokat) [inline coderd/workspaces.go]: It seems this will only hold until the user restarts the workspace from the webUI?
The webUI treats the template setting as the source of truth, unlike the CLI.
So we are back to square one with the inconsistency in this use case, unless I'm missing something.

EDIT: After digging more, I realized my test non-admin user had the `Admin` role in the template's ACL. 
Starting via CLI without that role caused the workspace to update to  the latest version. So the inconsistency only affects users who have update permission on the template.

File: coderd/templates.go [hunk 6]
```diff
@@ -865,6 +865,20 @@ func (api *API) patchTemplateMeta(rw http.ResponseWriter, r *http.Request) {
...
+		// "always" so the database value matches the enforced
+		// behavior.
+		if req.RequireActiveVersion && !template.RequireActiveVersion {
+			err = tx.UpdateWorkspaceAutomaticUpdatesByTemplateID(ctx, database.UpdateWorkspaceAutomaticUpdatesByTemplateIDParams{
+				TemplateID:       template.ID,
+				AutomaticUpdates: database.AutomaticUpdatesAlways,
+			})
+			if err != nil {
+				return xerrors.Errorf("update workspace automatic updates: %w", err)
+			}
```
Comment (sreya) [inline coderd/templates.go]: The only issue with doing this is that you lose the state of the workspace-scoped setting. So if someone toggles the template-scoped requiring automatic updates then you lose whatever setting the user set on the workspace. If someone toggles this off then all the workspaces will still be set to `true` right?

**Review by sreya — COMMENTED** [review]
@f0ssel could you explain where the bug manifested here? Were we not checking at build time that the version the user was trying to pass was the latest version if required by the template?

**Comment by f0ssel** [comment]
@sreya I think so, but I'm going to look more into the workspace scoped `require_active_version` because that feature is unfamiliar to me so I'm trying to understand what the original intent really was.

File: coderd/templates.go (hunk 6 above)
Comment (f0ssel) [reply coderd/templates.go]: Yes this would be a force on, manual opt out

Comment (Emyrk) [reply coderd/templates.go]: Ideally we keep the user's previously selected value. But at the same time, if toggling it in the template changes the user's value, I don't think that is a huge deal.

Right now when the template takes control, the user has a disabled field in the UI. So they can't change it, even if they wanted to change their user chosen fallback.

If someone is toggling the template setting and annoying users, we could revisit 🤷

**Comment by f0ssel** [comment]
@sreya @johnstcn @geokat @Emyrk Thanks for the reviews, I think changing the workspace API value to satisfy https://github.com/coder/coder/issues/22031 may not be the ideal path forward, so I think matching the UI in consistent behavior would be a safer first step. I've updated the PR to reflect that change instead.

**Review by johnstcn — APPROVED** [review]
This is a better solution (making the CLI behaviour match the UI).

**Comment by geokat** [comment]
We may still not be addressing the user's issue. Based on the [issue](https://github.com/coder/coder/issues/22030) description and the conversation with @uzair-coder07, it seems the user is running `coder start` as a template admin (Owner) and expects it to behave the same way as the "Start" button in the frontend.

I think the misunderstanding is that the "Start" button behaves like [`coder update`](https://coder.com/docs/reference/cli/update) when the workspace version is not current, and the user expects `coder start` to behave exactly the same way.

**Comment by f0ssel** [comment]
Thanks for the context @geokat , I see that the UI doesn't give the option to start with the old version at all, so by having this option it's acting as a footgun. We can suggest using update, or maybe we can have start behave differently. Do you have a suggested UX change that could help align these?

**Comment by geokat** [comment]
> I see that the UI doesn't give the option to start with the old version at all,

AFAICS template admins can pick an older version via meatball -> Change version, but it still requires changing the current version (even to an old one) before it takes effect. So the option is there, but it's hidden and not easy to use (you have to change to another version and then back to the one you want).

In general, I think having similar flows across frontends is the way to go. For example, the "Start" button in the webui could be a split button (depending on whether the user is a template admin) that starts on the current version by default but also allows updating (or the other way around).

I'm not sure about the best CLI UX... Maybe deprecate `coder update` and add an `--update` option (could be true by default) to `coder start`? :thinking:  

EDIT: Maybe we could also add `--template-version=<ver>` to `coder start` for even more parity with the webui.

**Comment by sreya** [comment]
I'm confused at this point what we're solving can we distill it down a bit. I thought the bug was the backend isn't enforcing requiring active version for relevant workspaces but seems like it does? If so then the CLI behavior must only be observable for admins right? I'm _pretty_ sure if you don't specify a specific template version then the backend should just pick the active one (if `require_active_version=true`) or reuses the last build if `require_active_version=false`. Shouldn't we just update the CLI to omit the build number on start and then it's all hunky dory?
