### PR TITLE
fix: display SVG emojis in the picker

### LINKED ISSUE #16263: Some custom emojis aren't displaying
Version: [`v2.18.4 6125358`](https://github.com/coder/coder/commit/6125358569071babaf36a7d4ff976429387df8da)

When using the emoji picker, some of the custom emojis aren't displaying.

https://github.com/user-attachments/assets/7c74b115-d1ed-4f24-9103-489f9ff9728f

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/16263

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
Tested manually, and it works 👍

File: site/src/components/IconField/EmojiPicker.tsx [hunk 1]
```diff
@@ -26,6 +31,22 @@ type EmojiPickerProps = Omit<
 >;
 
 const EmojiPicker: FC<EmojiPickerProps> = (props) => {
+	/**
+	 * Workaround for a bug in the emoji-mart library where custom emoji images render improperly.
+	 * Setting the image width to 100% ensures they display correctly.
+	 *
+	 * Reference: https://github.com/missive/emoji-mart/pull/806
```
Comment (mtojek) [inline site/src/components/IconField/EmojiPicker.tsx:38]: Perhaps link the original issue too: https://github.com/missive/emoji-mart/issues/805
