### PR TITLE
fix(coderd): workspaceapps: update last_used_at when workspace app reports stats

### LINKED ISSUE #11509: bug: workspace.last_used_at not updated when accessing coder_app
I just noticed now on my workspace `vvuurrkk`  <http://dev.coder.com|dev.coder.com> that `last_used_at` is set to 5 days ago. I have been using this workspace consistently over the last few days.

This behaviour can also be observed with a newly created workspace:

https://dev.coder.com/api/v2/workspaces/86c99fd0-35ef-4443-ba0d-304885699478

Initial start:
```
"created_at": "2024-01-09T10:10:18.925754Z",
"updated_at": "2024-01-09T10:10:18.925754Z",
"last_used_at": "2024-01-09T10:10:18.925756Z",
```

After stop / start: 
```
"created_at": "2024-01-09T10:10:18.925754Z",
"updated_at": "2024-01-09T10:10:18.925754Z",
"last_used_at": "2024-01-09T10:10:18.925756Z",
```

After opening code-server:
```
"created_at": "2024-01-09T10:10:18.925754Z",
"updated_at": "2024-01-09T10:10:18.925754Z",
"last_used_at": "2024-01-09T10:10:18.925756Z",
```

After opening web terminal (edit: just didn't leave it open long enough):
```
"last_used_at": "2024-01-09T10:10:18.925756Z",
```

After `coder ssh <workspace>`:

```
"last_used_at": "2024-01-09T10:19:46.010417Z",
```

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/11509

- Adds a new query `BatchUpdateLastUsedAt`
- Adds calls to `BatchUpdateLastUsedAt` in app stats handler upon flush
- Passes a stats flush chan to apptest setup scaffolding

This is not the 'correct' solution, but it puts a decent enough bandage on the problem until we figure out a more unified solution to this issue of updating the "Last Used At" field of workspaces based on certain events. I'll be opening a follow-up PR for this.

Now when the workspace apps stats collector flushes a batch of stats, we bump `LastUsedAt` for all affected workspaces.

Note: I'm just updating `LastUsedAt` to the same value for all workspaces. I don't know if there's a good way to insert a whole bunch of distinct values for a number of rows in a single transaction, and I want to keep this to a single query if possible.

I've verified that this works experimentally but this is the sort of thing that should be ossified in tests. I'm currently putting this into `TestWorkspaceApps` as it seems to be the place where all the testing of proxying flows happens.

Also note: the tests are sadly a bit racy; I've done what I can for the moment but I may need to spend some follow-up time refactoring.

### CODE REVIEW

File: coderd/workspaceapps/apptest/apptest.go [hunk 1]
```diff
@@ -195,6 +202,8 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
 			require.NoError(t, err)
 			defer resp.Body.Close()
 			require.Equal(t, http.StatusNotFound, resp.StatusCode)
+			// TODO(cian): A blocked request should not count as workspace usage.
+			// assertWorkspaceLastUsedAtNotUpdated(t, appDetails.AppClient(t), appDetails)
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:206]: review: leaving this here to address in a follow-up. As this is now tied to stats collection, we bump whenever there are app usage stats for a workspace.

File: coderd/workspaceapps/apptest/apptest.go [hunk 2]
```diff
@@ -209,6 +218,8 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
 			require.NoError(t, err)
 			defer resp.Body.Close()
 			require.Equal(t, http.StatusTemporaryRedirect, resp.StatusCode)
+			// TODO(cian): The initial redirect should not count as workspace usage.
+			// assertWorkspaceLastUsedAtNotUpdated(t, appDetails.AppClient(t), appDetails)
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:222]: review: follow-up

File: coderd/workspaceapps/apptest/apptest.go [hunk 3]
```diff
@@ -226,6 +237,8 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
 			loc, err := resp.Location()
 			require.NoError(t, err)
 			require.Equal(t, proxyTestAppQuery, loc.RawQuery)
+			// TODO(cian): The initial redirect should not count as workspace usage.
+			// assertWorkspaceLastUsedAtNotUpdated(t, appDetails.AppClient(t), appDetails)
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:241]: review: follow-up

File: coderd/workspaceapps/apptest/apptest.go [hunk 4]
```diff
@@ -331,6 +346,8 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
 			body, err := io.ReadAll(resp.Body)
 			require.NoError(t, err)
 			require.Contains(t, string(body), "must be accessed with the full username, not @me")
+			// TODO(cian): A blocked request should not count as workspace usage.
+			// assertWorkspaceLastUsedAtNotUpdated(t, appDetails.AppClient(t), appDetails)
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:350]: review: follow-up

File: coderd/workspaceapps/apptest/apptest.go [hunk 5]
```diff
@@ -375,6 +396,7 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
 			// TODO(@deansheather): This should be 400. There's a todo in the
 			// resolve request code to fix this.
 			require.Equal(t, http.StatusInternalServerError, resp.StatusCode)
+			assertWorkspaceLastUsedAtUpdated(t, appDetails)
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:399]: review: I'm counting this as a successful and valid attempt to access a workspace.

File: coderd/workspaceapps/apptest/apptest.go [hunk 6]
```diff
@@ -1549,3 +1564,31 @@ func testReconnectingPTY(ctx context.Context, t *testing.T, client *codersdk.Cli
...
+func assertWorkspaceLastUsedAtNotUpdated(t testing.TB, details *Details) {
+	t.Helper()
+
+	<-time.After(testutil.IntervalMedium) // Wait for Bicopy to finish.
+	details.FlushStats()
+	<-time.After(testutil.IntervalMedium) // Wait for stats to fully flush.
+	ws, err := details.SDKClient.Workspace(context.Background(), details.Workspace.ID)
+	require.NoError(t, err)
+	require.Equal(t, ws.LastUsedAt, details.Workspace.LastUsedAt, "workspace LastUsedAt updated when it should not have been")
+}
```
Comment (johnstcn) [inline coderd/workspaceapps/apptest/apptest.go:1594]: review: this is where all the race gremlins live:
- Bicopy does not appear to exit immediately so if we flush stats immediately we may not get a finished session.
- Even though a completed flush _should_ mean that LastUsedAt has been bumped, I've observed some wiggle room (especially when wsproxy is involved).

File: enterprise/wsproxy/wsproxy_test.go [hunk 7]
```diff
@@ -442,6 +442,13 @@ func TestWorkspaceProxyWorkspaceApps(t *testing.T) {
 			"*",
 		}
 
+		proxyFlushCh := make(chan chan<- struct{})
+		flushStats := func() {
+			proxyFlushDone := make(chan struct{})
+			proxyFlushCh <- proxyFlushDone
+			<-proxyFlushDone
+		}
```
Comment (johnstcn) [inline enterprise/wsproxy/wsproxy_test.go:450]: review: there should be no need to flush the stats on the primary here, as the proxy sends its stats directly to the primary endpoint which is wired up directly to the Reporter, which just inserts immediately.

File: coderd/httpapi/websocket.go [hunk 8]
```diff
@@ -4,8 +4,9 @@ import (
 	"context"
 	"time"
 
-	"cdr.dev/slog"
 	"nhooyr.io/websocket"
+
+	"cdr.dev/slog"
```
Comment (mtojek) [inline coderd/httpapi/websocket.go:9]: nit: is it expected or is the linter impaired?

File: coderd/workspaceapps/stats.go [hunk 9]
```diff
@@ -117,11 +118,21 @@ func (r *StatsDBReporter) Report(ctx context.Context, stats []StatsReport) error
...
-			}
+		if len(batch.UserID) == 0 {
+			return nil
+		}
+
+		if err := tx.InsertWorkspaceAppStats(ctx, batch); err != nil {
+			return err
+		}
+
+		// TODO: There should be a better way to do this.
```
Comment (mtojek) [inline coderd/workspaceapps/stats.go:129]: nit: You may want to more context for readers explaining why do you think it is inefficient.

**Review by mtojek — APPROVED** [review]
I left few nit-picks, and I'm looking forward to follow-ups!

File: coderd/httpapi/websocket.go (hunk 8 above)
Comment (johnstcn) [reply coderd/httpapi/websocket.go:9]: Might be my linter.

File: enterprise/coderd/coderdenttest/proxytest.go [hunk 10]
```diff
@@ -37,6 +37,9 @@ type ProxyOptions struct {
 
 	// ProxyURL is optional
 	ProxyURL *url.URL
+
+	// Flush is optional
+	Flush chan chan<- struct{}
```
Comment (mafredri) [inline enterprise/coderd/coderdenttest/proxytest.go:42]: Naming could match workspace apps here, i.e. `FlushStats`.

File: enterprise/wsproxy/wsproxy_test.go (hunk 7 above)
Comment (mafredri) [reply enterprise/wsproxy/wsproxy_test.go:450]: Correct me if I'm wrong, but without a flush, we can't ensure that `Report()` is being called (i.e. flushing the in-memory stats to coderd via post), right? So I think it may be needed here too, depending on what we're looking to achieve.

File: enterprise/wsproxy/wsproxy_test.go [hunk 11]
```diff
@@ -442,6 +442,13 @@ func TestWorkspaceProxyWorkspaceApps(t *testing.T) {
 			"*",
 		}
 
+		proxyFlushCh := make(chan chan<- struct{})
```
Comment (mafredri) [inline enterprise/wsproxy/wsproxy_test.go:445]: Naming these stats specific might keep things more clear.

File: coderd/workspaceapps_test.go [hunk 12]
```diff
@@ -262,6 +262,13 @@ func TestWorkspaceApps(t *testing.T) {
 			opts.AppHost = ""
 		}
 
+		statsFlushCh := make(chan chan<- struct{})
+		opts.StatsCollectorOptions.Flush = statsFlushCh
+		flushStats := func() {
+			flushDone := make(chan struct{})
+			statsFlushCh <- flushDone
+			<-flushDone
+		}
```
Comment (mafredri) [inline coderd/workspaceapps_test.go:271]: I see you removed the channel buffering from both channels, any particular reason? I suppose it can work without them, but I try to avoid those so there's no risk of deadlocks. 😄

File: coderd/workspaceapps/apptest/apptest.go (hunk 6 above)
Comment (mafredri) [reply coderd/workspaceapps/apptest/apptest.go:1594]: Why don't we try looping the flush until we either time out or have the stats we're looking for? Might make sense to have `FlushStats` take a context too, just to be sure.

File: coderd/workspaceapps/apptest/apptest.go [hunk 13]
```diff
@@ -1549,3 +1564,31 @@ func testReconnectingPTY(ctx context.Context, t *testing.T, client *codersdk.Cli
...
 	require.ErrorIs(t, tr.ReadUntil(ctx, nil), io.EOF)
 }
+
+// Accessing an app should update the workspace's LastUsedAt.
+// NOTE: Despite our efforts with the flush channel, this is inherently racy.
+func assertWorkspaceLastUsedAtUpdated(t testing.TB, details *Details) {
+	t.Helper()
+
+	<-time.After(testutil.IntervalMedium) // Wait for Bicopy to finish.
+	details.FlushStats()
```
Comment (mafredri) [inline coderd/workspaceapps/apptest/apptest.go:1574]: Same here, looping flush seems better than waiting an arbitrary time?

File: coderd/workspaceapps/stats.go [hunk 14]
```diff
@@ -117,11 +118,25 @@ func (r *StatsDBReporter) Report(ctx context.Context, stats []StatsReport) error
...
-			err := tx.InsertWorkspaceAppStats(ctx, batch)
-			if err != nil {
-				return err
-			}
+		if len(batch.UserID) == 0 {
+			return nil
+		}
+
+		if err := tx.InsertWorkspaceAppStats(ctx, batch); err != nil {
+			return err
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply coderd/workspaceapps/stats.go:126]: Inserting app stats is just doing a big insert into a single table (which IIRC is unlogged), so if we run into issues doing that my gut tells me that any further database queries might not be successful. Might not hurt to try, but I'm not sure how much the extra complexity would be worth it. Bear in mind that we will end up just trying to do this again in another 30 seconds!

File: enterprise/wsproxy/wsproxy_test.go (hunk 7 above)
Comment (johnstcn) [reply enterprise/wsproxy/wsproxy_test.go:450]: From my reading, any POSTS to `/app-stats` go straight to `api.WorkspaceAppsStatsCollectorOptions.Reporter`, and the wsproxy app stats reporter just hits that endpoint on flush.

File: coderd/workspaceapps/apptest/apptest.go (hunk 13 above)
Comment (johnstcn) [reply coderd/workspaceapps/apptest/apptest.go:1574]: A loop-flush here would probably just execute after the first iteration.

File: coderd/workspaceapps_test.go (hunk 12 above)
Comment (johnstcn) [reply coderd/workspaceapps_test.go:271]: I'll put back the buffers; I was messing around with a few different things.

**Comment by johnstcn** [comment]
Filed https://github.com/coder/coder/issues/11643 for following up on unexpected stats inserts.
