### PR TITLE
fix: report failed CompletedJob

### LINKED ISSUE #8048: workspace stuck on "cleaning up" when app slug is duplicate on template push
You have to look in the server logs to see this.

```sh
2023-06-15 13:35:04.899 [erro]  send CompletedJob  job_id=ad76c145-d07f-4403-812b-4d3ee0eca6dd ...
    error= insert resource: duplicate app slug, must be unique per template: "vnc"
           	storj.io/drpc/drpcwire.UnmarshalError:26
           	storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
           	storj.io/drpc/drpcmanager.(*Manager).manageReader:247
```

Are there other validation errors that are not surfaced on `cleaning up`? Are we able to guarantee that this step doesn't hang moving forward?

## Current behavior

The template push hangs and the user does not know that the problem is.

## Expected behavior

Any server logs that cause provisioning to fail/hang should be exposed to the user in `coder templates push` or in the templates UI

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/8048

This PR improves provisioner job handling by reporting failed `CompletedJob`. Currently, the CLI hangs as the provisioner job fails silently. Once the change is merged, CLI will fail with:

```
2023-07-05 10:48:26.924+02:00 Use context instead. This attribute will be removed in the next major release.
=== ✔ Detecting ephemeral resources [691ms]
==> ⧗ Cleaning Up
=== ✘ Cleaning Up [23ms]
=== ✘ Cleaning Up [35ms]
running command "coder templates push": internal provisionerserver error
``` 

Additionally, this PR modifies the `ConvertState` logic to detect duplicate `coder_metadata` resources.

### CODE REVIEW

File: provisionerd/runner/runner.go [hunk 1]
```diff
@@ -232,6 +232,10 @@ func (r *Runner) Run() {
 		err := r.sender.CompleteJob(ctx, r.completedJob)
 		if err != nil {
 			r.logger.Error(ctx, "sending CompletedJob failed", slog.Error(err))
+			err = r.sender.FailJob(ctx, r.failedJobf("internal provisionerserver error"))
+			if err != nil {
+				r.logger.Error(ctx, "sending FailJob failed (while CompletedJob)", slog.Error(err))
```
Comment (johnstcn) [inline provisionerd/runner/runner.go:237]: The message here is difficult to parse, and yet even trickier to word in an informative yet succinct way.

"Failed to mark the job we previously failed to mark as completed as failed" just doesn't have the same ring to it.

If we fail to both 
a) mark the job as completed, and
b) fail to mark the completed job as failed

then isn't it likely that we are in an unrecoverable state?

**Review by johnstcn — APPROVED** [review]
Change looks good to me, although the PR title could possibly be reworded as "detect duplicate metadata resources" as this is the bigger change here.

File: provisioner/terraform/resources.go [hunk 2]
```diff
@@ -385,6 +385,7 @@ func ConvertState(modules []*tfjson.StateModule, rawGraph string) (*State, error
 	resourceIcon := map[string]string{}
 	resourceCost := map[string]int32{}
 
+	metadataTargetLabels := map[string]struct{}{}
```
Comment (mafredri) [inline provisioner/terraform/resources.go:388]: Commentary: Here I think a `map[string]bool` would be ideal, simplifies the check below where we can simply do `if metadataTargetLabels[targetLabel]`. The space savings from using `struct{}` should be negligible.

No change required, just an observation.

File: provisioner/terraform/resources_test.go [hunk 3]
```diff
@@ -636,6 +636,28 @@ func TestAppSlugValidation(t *testing.T) {
...
 }
 
+func TestMetadataResourceDuplicate(t *testing.T) {
+	t.Parallel()
+
+	// nolint:dogsled
+	_, filename, _, _ := runtime.Caller(0)
+
+	// Load the multiple-apps state file and edit it.
+	dir := filepath.Join(filepath.Dir(filename), "testdata", "resource-metadata-duplicate")
```
Comment (mafredri) [inline provisioner/terraform/resources_test.go:646]: Suggestion: There's no need to check the `runtime.Caller` here, current working directory is always relative to the test, therefore we can simply do `filepath.Join("testdata, "...")`.

**Review by mafredri — APPROVED** [review]
@johnstcn had some good comments, only found some crumbs left over 😂

File: provisioner/terraform/resources_test.go (hunk 3 above)
Comment (mtojek) [reply provisioner/terraform/resources_test.go]: Gotcha 👍

File: provisioner/terraform/resources.go (hunk 2 above)
Comment (mtojek) [reply provisioner/terraform/resources.go]: Fixed

File: provisionerd/runner/runner.go (hunk 1 above)
Comment (johnstcn) [reply provisionerd/runner/runner.go:237]: Per discussion: we can't bail out here because we need to close the loop. I don't have a better concrete suggestion for the log message, so resolving.

**Review by kylecarbs — APPROVED** [review]
