### PR TITLE
fix: write new ttl to audit log

### LINKED ISSUE #5183: Schedule and Audit Log: editing and enabling Auto-Stop log incorrectly
Given auto-stop is enabled, when I edit the duration and submit, then the audit log says I set it to 0 even though I set it to a non-zero number.

Given auto-stop is disabled, when I enable it, then the audit log has an entry with no diff. 

I think what's going on is that the audit log entry for anything to do with auto-stop always shows it being set to 0. So disabling it appears to work because 0 is correct, enabling it has no diff because it was 0 before, and editing it has an incorrect diff to 0.

### PR DESCRIPTION
**Pull request by presleyp**
Fixes #5183 

Due to a scoping bug, the ttl from the database was not being written to the audit log; the 0-initialized variable was being written instead. This fixes the behavior so that ttl changes are correctly logged.

### CODE REVIEW

File: coderd/workspaces.go [hunk 1]
```diff
@@ -672,10 +672,11 @@ func (api *API) putWorkspaceTTL(rw http.ResponseWriter, r *http.Request) {
 	var dbTTL sql.NullInt64
 
 	err := api.Database.InTx(func(s database.Store) error {
+		var validityErr error
```
Comment (presleyp) [inline coderd/workspaces.go:675]: Let me know if there's a better way to handle this - still getting the hang of Go!

Comment (f0ssel) [reply coderd/workspaces.go:675]: I think you can simplify this change to something like this:
```
		dbTTL, txErr := validWorkspaceTTLMillis(req.TTLMillis, 0)
		if txErr != nil {
			return codersdk.ValidationError{
				Field: "ttl_ms", 
				Detail: txErr .Error(),
			}
		}
		txErr = s.UpdateWorkspaceTTL(ctx, database.UpdateWorkspaceTTLParams{
			ID:  workspace.ID,
			Ttl: dbTTL,
		})
		if txErr != nil {
			return xerrors.Errorf("update workspace time until shutdown: %w", txErr )
		}
```

Comment (f0ssel) [reply coderd/workspaces.go:675]: I believe you'll need to change the `UpdateWorkspaceTTL` error as well to avoid this same problem.

**Review by f0ssel — APPROVED** [review]
