### PR TITLE
fix(site): respect meta user appearance preference as theme fallback

### LINKED ISSUE #20050: Light Theme setting not respected until Appearance page opened
Version: [`v2.25.1 3bf6a00`](https://github.com/coder/coder/commit/3bf6a008763e2dd1e8829c75d91a0c36c49007c0)

When first opening Coder, I always am in dark mode, despite my settings having light mode set. Once I then go into settings > appearance, it changes automatically on loading that page to light mode. Can this be fixed to be correct from login?

### PR DESCRIPTION
**Pull request by jeremyruppel**
Use the server-rendered meta tag value as an intermediate fallback for theme preference, between the JS-fetched value and the default theme. This ensures the correct theme is applied before the API response loads.

Fixes #20050

### CODE REVIEW

File: site/src/contexts/ThemeProvider.tsx [hunk 1]
```diff
@@ -58,8 +58,11 @@ export const ThemeProvider: FC<PropsWithChildren> = ({ children }) => {
...
 	// We might not be logged in yet, or the `theme_preference` could be an empty string.
+	// Prefer JS-fetched value, fall back to server-rendered meta tag, then default.
 	const themePreference =
-		appearanceSettingsQuery.data?.theme_preference || DEFAULT_THEME;
+		appearanceSettingsQuery.data?.theme_preference ||
+		metadata.userAppearance?.value?.theme_preference ||
+		DEFAULT_THEME;
 	// The janky casting here is find because of the much more type safe fallback
 	// We need to support `themePreference` being wrong anyway because the database
 	// value could be anything, like an empty string.
```
Comment (jeremyruppel) [inline site/src/contexts/ThemeProvider.tsx:68]: While I'm in here, should we do something like quickly validate the theme key from the meta tag and API?

Comment (aslilac) [reply site/src/contexts/ThemeProvider.tsx:68]: nah, there's not really any point. it's either a valid theme and we render the UI with it or it's invalid and we still need to render the UI. fall back to a default and move on. 🤷‍♀️

tho if you wanted to fix the typo here I wouldn't mind. "is find because" should've been "is fine because".

**Review by aslilac — APPROVED** [review]

File: site/src/contexts/ThemeProvider.tsx (hunk 1 above)
Comment (jeremyruppel) [reply site/src/contexts/ThemeProvider.tsx:68]: Typo fixed!
