### PR TITLE
fix: show error message for incompatible parameters

### LINKED ISSUE #148: Display error message on workspace parameters page if a required mutable parameter without a value is present
It should not be possible to update a workspace if a new template version adds a required immutable parameter without a default. Need to warn users of this situation.

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves coder/preview#148

If there are any immutable params with diagnostics on the workspace parameters page, display this error dialog.

Screenshot 2025-06-13 at 18 06 36

### CODE REVIEW

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx [hunk 1]
```diff
@@ -596,11 +596,18 @@ export const CreateWorkspacePageViewExperimental: FC<
 									const currentParameterValueIndex =
 										form.values.rich_parameter_values?.findIndex(
 											(p) => p.name === parameter.name,
-										) ?? -1;
```
Comment (Emyrk) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx:599]: This feels like it could be a bad default :thinking:

**Review by Emyrk — APPROVED** [review]
:+1:

**Comment by Kira-Pilot** [comment]
Need a docs update so this is clear to new users.

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx (hunk 1 above)
Comment (jaaydenh) [reply site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx:599]: yup, I removed this to check undefined instead
