### PR TITLE
fix: don't allow sharing admins to change own role

### LINKED ISSUE #1280: A shared workspace user with Admin permission can change their own role to Use
Based on the test cases discussed here, https://www.notion.so/coderhq/Shared-Workspaces-v1-Test-Cases-2e9d579be59280d99c2ec6271277aa62

It was decided that an shared workspace Admin should not be able to change their own role.

### PR DESCRIPTION
**Pull request by jaaydenh**
resolve coder/internal#1280

### CODE REVIEW

File: coderd/workspaces_test.go [hunk 1]
```diff
@@ -5190,6 +5190,74 @@ func TestUpdateWorkspaceACL(t *testing.T) {
...
+				sharedAdminUser.ID.String(): codersdk.WorkspaceRoleUse,
+			},
+		})
+		require.Error(t, err)
+		cerr, ok := codersdk.AsError(err)
+		require.True(t, ok)
+		require.Equal(t, http.StatusBadRequest, cerr.StatusCode())
+		require.Contains(t, cerr.Message, "You cannot change your own workspace sharing role")
+
+		// The workspace owner should also not be able to change their own role.
```
Comment (geokat) [inline coderd/workspaces_test.go:5241]: :+1:

**Review by geokat — APPROVED** [review]
LGTM!

**Comment by geokat** [comment]
We now have an interesting loophole: ws owners can't share with themselves, but if they admin-share with someone, that someone will be able to share with the ws owner (and the ws owner won't be able to remove the share) :)

File: coderd/workspaces.go [hunk 2]
```diff
@@ -2353,6 +2353,14 @@ func (api *API) patchWorkspaceACL(rw http.ResponseWriter, r *http.Request) {
...
 	}
 
+	apiKey := httpmw.APIKey(r)
+	if _, ok := req.UserRoles[apiKey.UserID.String()]; ok {
+		httpapi.Write(ctx, rw, http.StatusBadRequest, codersdk.Response{
+			Message: "You cannot change your own workspace sharing role.",
+		})
+		return
+	}
+
```
Comment (geokat) [inline coderd/workspaces.go:2363]: I wonder if we should add a check to close the loophole?
```suggestion
	if _, ok := req.UserRoles[workspace.OwnerID.String()]; ok {
		httpapi.Write(ctx, rw, http.StatusBadRequest, codersdk.Response{
			Message: "You cannot change the workspace owner's sharing role.",
		})
		return
	}
```

**Comment by jaaydenh** [comment]
If another admin shares the workspace with the workspace owner does it even matter? I'm assuming the ws owner will always be the owner and the share is irrelevant?

**Comment by geokat** [comment]
> If another admin shares the workspace with the workspace owner does it even matter? I'm assuming the ws owner will always be the owner and the share is irrelevant?

Yes, the share will be irrelevant for all practical reasons.

File: coderd/workspaces.go (hunk 2 above)
Comment (jaaydenh) [reply coderd/workspaces.go:2363]: Is this necessary since, changing the workspace owner's role would have no effect?

Comment (geokat) [reply coderd/workspaces.go:2363]: Not strictly necessary. But without this, workspace owners can be added to the ACL by users they shared with:

- Alice shares with Bob using `admin` role
- Bob shares "back" with Alice (just for funzies :))
- Alice is stuck with her name in the ACL list that she can't remove (due to this PR). 

It won't affect the actual access permissions, but the workspace ACL (and the related UI) will be in a state that the ws owner can't change
