### PR TITLE
fix(site): hide "Show parent apps" when no running or starting devcontainers

### LINKED ISSUE #19199: bug: "Show parent apps" button visible but does not do anything
# Problem

Given a workspace where a devcontainer has been found, the site will show the "Show parent apps" button, but clicking it does not result in any noticeable behavior.

# Possible Solution

Hide the button when there are no running devcontainers.

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fixes https://github.com/coder/coder/issues/19199

We now hide the "Show parent apps" button when there are no running or starting devcontainers.

### CODE REVIEW

File: site/src/modules/resources/AgentRow.tsx [hunk 1]
```diff
@@ -137,17 +137,16 @@ export const AgentRow: FC<AgentRowProps> = ({
...
-		) !== undefined &&
-		!showParentApps
-	) {
+		) !== undefined;
+
+	// We only want to hide the parent apps by default when there are dev
+	// containers that are either starting or running. If they are all in
+	// the stopped state, it doesn't make sense to hide the parent apps.
+	let shouldDisplayAppsSection = shouldDisplayAgentApps;
+	if (devcontainers && anyRunningOrStartingDevcontainers && !showParentApps) {
```
Comment (mafredri) [inline site/src/modules/resources/AgentRow.tsx]:
```suggestion
	if (anyRunningOrStartingDevcontainers && !showParentApps) {
```
Simplification

**Review by mafredri — APPROVED** [review]
Looks good to me 👍🏻. Would be nice to see a test case that verifies/enforces the behavior though.

**Comment by DanielleMaywood** [comment]
I've added a storybook but I've noticed it doesn't actually show the devcontainer, and after running storybook in my workspace the existing `Devcontainer` story doesn't show any either. I think the change that introduced `useAgentContainers` may have broken the prior story.

I've tried fixing this myself, and with the aid of Claude Opus 4.1, but I've not had any luck. I believe the main issue is our component is handling both data fetching and rendering, whereas with other parts of the codebase we follow the pattern: `FooBar` paired with a `FooBarView`.

@aslilac Do you think we should follow the same approach here?

**Comment by aslilac** [comment]
that's one approach, but you can also just mock the query response by setting the `queries` parameter on the story. for example: https://github.com/coder/coder/blob/0e108f1953dbe21c0da91be7cb938ca1d397f0b8/site/src/modules/resources/AgentDevcontainerCard.stories.tsx#L37
