### PR TITLE
fix: set codersdk.Task current_state during task initialization

### LINKED ISSUE #1063: task status is empty when workspace is starting or startup script is running
Image

When workspace is starting, agent is connecting, and/or startup script is running can we show a unique message in the status field? This should both be a UI and API thing so someone can get this via the tasks API, not workspaces API

### PR DESCRIPTION
**Pull request by ssncferreira**
## Problem

With the new tasks data model, a task starts with an `initializing` status. However, the API returns `current_state: null` to represent the agent state, causing the frontend to display "No message available". This PR updates `codersdk.Task` to return a `current_state` when the task is initializing with meaningful messages about what's happening during task initialization.

**Previous message**

Screenshot 2025-11-07 at 09 06 13

**New message**

Screenshot 2025-11-12 at 11 00 15

## Changes

- Populate `current_state` with descriptive initialization messages when task status is `initializing` and no valid app status exists for the current build
- **dbfake**: Fix `WorkspaceBuild` builder to properly handle pending/running jobs by linking tasks without requiring agent/app resources

**Note:** UI Storybook changes to reflect these new messages will be addressed in a follow-up PR.

Closes: https://github.com/coder/internal/issues/1063

### CODE REVIEW

File: coderd/aitasks.go [hunk 1]
```diff
@@ -302,6 +302,35 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
 		}
 	}
 
+	// If no valid agent state was found for the current build and the task is initializing,
+	// provide a descriptive initialization message.
+	if currentState == nil && codersdk.TaskStatus(dbTask.Status) == codersdk.TaskStatusInitializing {
```
Comment (johnstcn) [inline coderd/aitasks.go]: suggestion: extract this to its own function

File: coderd/aitasks.go [hunk 2]
```diff
@@ -302,6 +302,35 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
...
+		message := "Initializing workspace"
+
+		switch {
+		case ws.LatestBuild.Status == codersdk.WorkspaceStatusPending:
+			message = "Workspace build is pending"
```
Comment (johnstcn) [inline coderd/aitasks.go]: We could reduce some duplication here

```suggestion
			message = fmt.Sprintf("Workspace is %s", ws.LatestBuild.Status)
```

File: coderd/aitasks.go [hunk 3]
```diff
@@ -302,6 +302,35 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
...
+		case ws.LatestBuild.Status == codersdk.WorkspaceStatusStarting:
+			message = "Starting workspace"
+		case taskAgentLifecycle != nil:
+			switch *taskAgentLifecycle {
+			case codersdk.WorkspaceAgentLifecycleCreated:
+				message = "Agent is connecting"
```
Comment (johnstcn) [inline coderd/aitasks.go:365]: We could also probably generate this using the workspace agent lifecycle status?

File: coderd/aitasks_test.go [hunk 4]
```diff
@@ -240,14 +240,142 @@ func TestTasks(t *testing.T) {
...
+		// and replaced by the agent initialization status.
 		updated, err = exp.TaskByID(ctx, task.ID)
 		require.NoError(t, err)
-		assert.Nil(t, updated.CurrentState, "current state should be nil")
+		assert.NotEqual(t, previousCurrentState, updated.CurrentState)
+		assert.Equal(t, codersdk.TaskStateWorking, updated.CurrentState.State)
+		assert.NotEqual(t, "all done", updated.CurrentState.Message)
+	})
+
+	t.Run("InitializingAgentState", func(t *testing.T) {
```
Comment (johnstcn) [inline coderd/aitasks_test.go]: extracting the function will mean we can test it on its own and only need to test a couple cases here

File: coderd/aitasks.go [hunk 5]
```diff
@@ -302,6 +302,35 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
...
+			case codersdk.WorkspaceAgentLifecycleStarting:
+				message = "Agent is starting"
+			default:
+				message = "Initializing workspace agent"
+			}
```
Comment (mafredri) [inline coderd/aitasks.go:380]: Should we take into account the coder app status as well?

File: coderd/aitasks_test.go [hunk 6]
```diff
@@ -240,14 +240,142 @@ func TestTasks(t *testing.T) {
...
+						Prompt: "test agent connecting",
+					}, &proto.App{
+						Id:   uuid.NewString(),
+						Slug: "ccw",
+					}).Do()
+
+					require.True(t, wb.Task.WorkspaceAgentID.Valid)
+					require.NotEqual(t, uuid.Nil, wb.Task.WorkspaceAgentID.UUID)
+
+					// nolint:gocritic // System restricted operation to update agent lifecycle to "created"
```
Comment (mafredri) [inline coderd/aitasks_test.go]: I think this is no longer needed in tests. Make sure to run `golangci-lint cache clean` (name might differ, didn't check) before attempting.

**Review by mafredri — COMMENTED** [review]
It would be pretty cool if we could add these messages to the app status at the time they happen (attached with a timestamp), that way they could be viewed in history/timeline of the task as well. That's a much larger refactor though and this is fine for now, nice clean implementation. 👍🏻

File: coderd/aitasks_test.go (hunk 4 above)
Comment (ssncferreira) [reply coderd/aitasks_test.go]: My initial idea was to unit test `taskFromDBTaskAndWorkspace`, however, the packages are different (`coderd` and `coderd_test`). The only way to unit test the extracted function would be to either make it public or create a separate test file with `package coderd`, but that goes against the current approach for other test files in this directory 😕  Unless I'm missing something really basic 😅

File: coderd/aitasks.go (hunk 5 above)
Comment (ssncferreira) [reply coderd/aitasks.go:380]: Do you mean `LatestAppStatus`? I thought about adding different messages based on the app status state, for example, if `LatestAppStatus.State == idle`, the message could be "Agent is idle", or for `completed`/`failed` states, we could provide more detailed information to users. Or were you thinking of something else?

Comment (mafredri) [reply coderd/aitasks.go:380]: I was thinking about `WorkspaceAppHealth`, specifically `WorkspaceAppHealthInitializing`. If disabled we can ignore it.

I'm not sure if we need to enrich `LatestAppStatus` if there already exists an entry 🤔. I imagine users could want to tweak that via having the agent give some context via the mcp report tool.

**Comment by ssncferreira** [comment]
> It would be pretty cool if we could add these messages to the app status at the time they happen (attached with a timestamp), that way they could be viewed in history/timeline of the task as well. That's a much larger refactor though and this is fine for now, nice clean implementation. 👍🏻

That would be nice, but it would require more changes. The way I see it, we have 2 stages of initialization here:
1. Provisioning stage: when the workspace is still pending or starting and the agent doesn't even exist yet
2. Agent initializing: when the agent is connecting/starting

For phase 1, we cannot insert a `workspace_app_status` because at this stage we don't have an agent or app yet, meaning that `agent_id` and `app_id` would be null, which is not supported by the database schema.

For phase 2, we *could* insert workspace app statuses by having the agent call `PatchAppStatus` whenever it transitions to `Created` or `Starting` lifecycle states. This would give us a proper timeline/history for the agent initialization phases, which would be a nice addition.

The implementation in this PR is simpler and works for both phases, but now that I think about it, I'm not sure if it's hackier compared to properly reporting statuses...We could report statuses for phase 2 (agent initialization) and keep the current implementation for phase 1 (provisioning). 
@mafredri Would that be a better approach, or should we keep it as is for now and refactor later if needed?

**Comment by mafredri** [comment]
@ssncferreira let's keep it like this for now, it's trivial enough of a change to redo later 👍🏻. Perhaps we can open up a new ticket to track the improvement.

Good point about phase 1, although I think it applies strictly to the pending phase and perhaps slightly past it. Once the workspace is starting the agent and apps should be created meaning we could update the status in the same place in the provisionerdserver where we perform update on the `task_workspace_apps` table.

I could see two ways for phase 2, first is as you propose, have the agent do it explicitly. The second is to do it behind the scenes inside coderd on agent lifecycle change (but perhaps that's too much spooky action at a distance?).

File: coderd/aitasks.go (hunk 3 above)
Comment (ssncferreira) [reply coderd/aitasks.go:365]: The enum value for `WorkspaceAgentLifecycleCreated` is `"created"`, which doesn't translate well to the message.

File: coderd/aitasks.go (hunk 1 above)
Comment (ssncferreira) [reply coderd/aitasks.go]: Addressed in https://github.com/coder/coder/pull/20692/commits/f07e3d8a32bd1895fc91f2591dc8a349f48dddc0

File: coderd/aitasks.go (hunk 2 above)
Comment (ssncferreira) [reply coderd/aitasks.go]: Addressed in: https://github.com/coder/coder/pull/20692/commits/f07e3d8a32bd1895fc91f2591dc8a349f48dddc0

File: coderd/aitasks_test.go (hunk 6 above)
Comment (ssncferreira) [reply coderd/aitasks_test.go]: Addressed in https://github.com/coder/coder/pull/20692/commits/f07e3d8a32bd1895fc91f2591dc8a349f48dddc0

File: coderd/aitasks.go (hunk 5 above)
Comment (ssncferreira) [reply coderd/aitasks.go:380]: > I was thinking about WorkspaceAppHealth, specifically WorkspaceAppHealthInitializing. If disabled we can ignore it.

Ah, I see. So this would be the case where the agent is ready but the app is still initializing, correct? Do you think it makes sense to get into that level of detail? We have different possible AppHealth statuses:
```
WorkspaceAppHealthDisabled     WorkspaceAppHealth = "disabled"
WorkspaceAppHealthInitializing WorkspaceAppHealth = "initializing"
WorkspaceAppHealthHealthy      WorkspaceAppHealth = "healthy"
WorkspaceAppHealthUnhealthy    WorkspaceAppHealth = "unhealthy"
```
I'm guessing only the `initializing` here would make sense, because the others would probably affect the overall task status, correct?

**Comment by ssncferreira** [comment]
> @ssncferreira let's keep it like this for now, it's trivial enough of a change to redo later 👍🏻. Perhaps we can open up a new ticket to track the improvement.
> 
> Good point about phase 1, although I think it applies strictly to the pending phase and perhaps slightly past it. Once the workspace is starting the agent and apps should be created meaning we could update the status in the same place in the provisionerdserver where we perform update on the `task_workspace_apps` table.
> 
> I could see two ways for phase 2, first is as you propose, have the agent do it explicitly. The second is to do it behind the scenes inside coderd on agent lifecycle change (but perhaps that's too much spooky action at a distance?).

Created issue https://github.com/coder/coder/issues/20749 to track this for future improvements 👍

File: coderd/aitasks.go (hunk 5 above)
Comment (mafredri) [reply coderd/aitasks.go:380]: > So this would be the case where the agent is ready but the app is still initializing, correct?

Yep! 👍🏻

> Do you think it makes sense to get into that level of detail?

It would better reflect how we determine the tasks status in the `tasks_with_status` view.

> I'm guessing only the `initializing` here would make sense, because the others would probably affect the overall task status, correct?

Correct. 👍🏻

We could consider `unhealthy` as well, but that would open a can of worms I'd prefer to avoid for now (messages for agent health, workspace build failure, etc).

File: coderd/aitasks_test.go (hunk 4 above)
Comment (mafredri) [reply coderd/aitasks_test.go]: If you want to test an unexported function, you can create `aitasks_internal_test.go` with `package coderd` and test it there.

Comment (ssncferreira) [reply coderd/aitasks_test.go]: > If you want to test an unexported function, you can create `aitasks_internal_test.go` with `package coderd` and test it there.

Completely forgot about the pattern with `_internal_` files 🤦‍♀️  Addressed in: https://github.com/coder/coder/pull/20692/commits/b1cb7fee56d395c12b508f43858cbcd3ec403e3b

File: coderd/aitasks.go (hunk 5 above)
Comment (ssncferreira) [reply coderd/aitasks.go:380]: Addressed in https://github.com/coder/coder/pull/20692/commits/b1cb7fee56d395c12b508f43858cbcd3ec403e3b

File: coderd/aitasks.go [hunk 7]
```diff
@@ -330,6 +329,71 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
...
+				State:     codersdk.TaskState(ws.LatestAppStatus.State),
+				Message:   ws.LatestAppStatus.Message,
+				URI:       ws.LatestAppStatus.URI,
+			}
+		}
+	}
+
+	// If no valid agent state was found for the current build and the task is initializing,
+	// provide a descriptive initialization message.
+	if currentState == nil && codersdk.TaskStatus(dbTask.Status) == codersdk.TaskStatusInitializing {
```
Comment (DanielleMaywood) [inline coderd/aitasks.go]:
```suggestion
	if currentState == nil && dbTask.Status == database.TaskStatusInitializing {
```

**Review by DanielleMaywood — APPROVED** [review]
looks good to me with one minor nit

File: coderd/aitasks.go (hunk 7 above)
Comment (ssncferreira) [reply coderd/aitasks.go]: Good catch 👀 Addressed in https://github.com/coder/coder/pull/20692/commits/979e3707e71da1fe43f810df6184e804f5ba9b8d

File: coderd/aitasks.go [hunk 8]
```diff
@@ -330,6 +324,71 @@ func taskFromDBTaskAndWorkspace(dbTask database.Task, ws codersdk.Workspace) cod
...
+			case *taskAgentLifecycle == codersdk.WorkspaceAgentLifecycleReady:
+				if taskAppHealth != nil && *taskAppHealth == codersdk.WorkspaceAppHealthInitializing {
+					message = "App is initializing"
+				} else {
+					// In case the workspace app is not initializing,
+					// the overall task status should be updated accordingly
+					message = "Initializing workspace applications"
+				}
+			default:
+				message = "Initializing workspace agent"
```
Comment (mafredri) [inline coderd/aitasks.go:379]: I think this should never happen, but the fallback is fine, should we log something if this happens?

**Review by mafredri — APPROVED** [review]

File: coderd/aitasks.go (hunk 8 above)
Comment (ssncferreira) [reply coderd/aitasks.go:379]: Yeah, this should never happen, similarly to the `"Initializing workspace applications"` path. I think adding a comment here is enough for now. Addressed in https://github.com/coder/coder/pull/20692/commits/677339d94352f0357db53a58719519e28507d601
