### PR TITLE
fix: Wrap TableCell with Link for native browser routing

### LINKED ISSUE #2525: Bug: new tab click idioms don't work on workspace, workspaces, and templates page page
When I `<middle>`-click, `<ctrl>`-click, or `<cmd>`-click on one of these rows, I should get the destination page in a new tab
image

Currently `<middle>`-click does nothing and `<ctrl>`-click acts as a normal click.  I haven't tested `<cmd>`-click, but I assume it's the same.

### PR DESCRIPTION
**Pull request by kylecarbs**
Tables were previously using an onClick handler which replicated some
Link behavior, but not natively through the browser.

Fixes #2525.

### CODE REVIEW

File: site/src/components/TableCellLink/TableCellLink.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+      >
+        {props.children}
+      </Link>
+    </TableCell>
+  )
+}
+
+const useStyles = makeStyles((theme) => ({
+  cell: {
+    padding: "0 !important",
```
Comment (Kira-Pilot) [inline site/src/components/TableCellLink/TableCellLink.tsx:31]: Why do we need `!important` in these styles?

**Review by jsjoeio — APPROVED** [review]

File: site/src/components/TableCellLink/TableCellLink.tsx (hunk 1 above)
Comment (kylecarbs) [reply site/src/components/TableCellLink/TableCellLink.tsx:31]: Unfortunately the MUI styles will override, and that can't work for the padding (because this needs to fill the entire cell).

**Review by AbhineetJain — COMMENTED** [review]
How about making a `TableRowLink` instead? 🤔 Do we have independent usages for a `TableCellLink`?

File: site/src/theme/overrides.ts [hunk 2]
```diff
@@ -61,10 +61,10 @@ export const getOverrides = (palette: PaletteOptions) => {
         background: palette.background?.paper,
         borderBottom: `1px solid ${palette.divider}`,
         padding: 8,
-        "&:first-child": {
+        "&:not(:only-child):first-child, &:not(:only-child):first-child > a": {
```
[the remark this answers is not in the document]
Comment (kylecarbs) [reply site/src/theme/overrides.ts:64]: True I shall add

**Review by Kira-Pilot — APPROVED** [review]

**Comment by kylecarbs** [comment]
@AbhineetJain it's not possible to wrap an entire row, only particular cells. I wish!

File: site/src/components/TableCellLink/TableCellLink.tsx [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+  },
+  link: {
+    display: "block",
+    width: "100%",
+    border: "none",
+    background: "none",
+    paddingTop: theme.spacing(2),
+    paddingBottom: theme.spacing(2),
+    textDecoration: "none !important",
```
[the remark this answers is not in the document]
Comment (jsjoeio) [reply site/src/components/TableCellLink/TableCellLink.tsx:40]: Could we get more specific with a selector?

File: site/src/components/TableCellLink/TableCellLink.tsx (hunk 1 above)
Comment (Kira-Pilot) [reply site/src/components/TableCellLink/TableCellLink.tsx:31]: Got it. I wonder if we could use specificity in class naming to get around this. Not a blocker for this PR.

Comment (kylecarbs) [reply site/src/components/TableCellLink/TableCellLink.tsx:31]: I shall try!

Comment (kylecarbs) [reply site/src/components/TableCellLink/TableCellLink.tsx:31]: I shall try!
