### PR TITLE
fix: display the correct response for coder list

### LINKED ISSUE #16312: CLI: coder list -o json returns no value but a json is expected
The expected returning value should be (on stdout):
`{"workspaces":[],"count":0}`

End user runs:
coder list -o json

Sees:
`No workspaces found! Create one:   coder create <name>`

(This is printed to stderr)

This would match the API function and is a valid json.

### PR DESCRIPTION
**Pull request by evgeniy-scherbina**
Closes https://github.com/coder/coder/issues/16312

We intend to modify the behavior of the CLI handler based on the specified output format. However, the output format is currently only accessible within the `OutputFormatter` structure. Therefore, I propose extending `OutputFormatter` by introducing a public `FormatID` method, which will allow us to retrieve the format identifier and use it to customize the behavior of the CLI handler accordingly.

An alternative approach would be to make the implementation more generic. Instead of defining a `FormatID` method, we could introduce an `IsMachineReadableFormat() bool` method. This method would indicate whether the output format is machine-readable, allowing us to adjust the CLI handler's behavior accordingly.

### CODE REVIEW

**Comment by evgeniy-scherbina** [comment]
I have read the CLA Document and I hereby sign the CLA

File: cli/list.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func (r *RootCmd) list() *serpent.Command {
 				return err
 			}
 
-			if len(res) == 0 {
+			if len(res) == 0 && formatter.FormatID() != cliui.JSONFormat().ID() {
 				pretty.Fprintf(inv.Stderr, cliui.DefaultStyles.Prompt, "No workspaces found! Create one:\n")
 				_, _ = fmt.Fprintln(inv.Stderr)
 				_, _ = fmt.Fprintln(inv.Stderr, "  "+pretty.Sprint(cliui.DefaultStyles.Code, "coder create <name>"))
```
Comment (Emyrk) [inline cli/list.go:118]: Unfortunate we print anything outside the formatter. Since this code is not going to get more formatters anytime soon, this works for me :+1: 

---

There might be value in some formatter wrapping like we do here: https://github.com/coder/coder/blob/a12f553130a56ec2add6f7b7786b38a642844770/cli/cliui/output.go#L217-L217

Something to switch the formatter based on the output or something :thinking:

File: cli/cliui/output.go [hunk 2]
```diff
@@ -83,6 +83,10 @@ func (f *OutputFormatter) Format(ctx context.Context, data any) (string, error)
 	return "", xerrors.Errorf("unknown output format %q", f.formatID)
 }
 
+func (f *OutputFormatter) FormatID() string {
+	return f.formatID
+}
```
Comment (Emyrk) [inline cli/cliui/output.go:88]: Took me a second to realize this `formatID` is updated here:

https://github.com/coder/coder/blob/a12f553130a56ec2add6f7b7786b38a642844770/cli/cliui/output.go#L64-L70

Just throw a comment to make the behavior clear.

```suggestion
// FormatID will return the ID of the format selected by `--output`.
// If no flag is present, it returns the 'default' formatter.
func (f *OutputFormatter) FormatID() string {
	return f.formatID
}
```

**Review by Emyrk — APPROVED** [review]
Minor nit to add a comment :+1:

File: cli/cliui/output.go (hunk 2 above)
Comment (evgeniy-scherbina) [reply cli/cliui/output.go:90]: I added a comment.
