### PR TITLE
fix: pass in time parameter to prevent flakes

### LINKED ISSUE #10600: flake: Test_parseInsightsStartAndEndTime
```
=== FAIL: coderd Test_parseInsightsInterval_week/9_days_(7_+_2)_are_not_acceptable (0.00s)
    insights_internal_test.go:239: Status:  400
    insights_internal_test.go:240: Body:  {
        	"message": "Query parameter has invalid value.",
        	"validations": [
        		{
        			"field": "end_time",
        			"detail": "Query param \"end_time\" must have the clock set to 00:00:00"
        		}
        	]
        }
        
    insights_internal_test.go:242: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:242
        	Error:      	Should be true
        	Test:       	Test_parseInsightsInterval_week/9_days_(7_+_2)_are_not_acceptable
        	Messages:   	start_time and end_time must be valid

=== FAIL: coderd Test_parseInsightsInterval_week/6_days_are_acceptable (0.00s)
    insights_internal_test.go:239: Status:  400
    insights_internal_test.go:240: Body:  {
        	"message": "Query parameter has invalid value.",
        	"validations": [
        		{
        			"field": "end_time",
        			"detail": "Query param \"end_time\" must have the clock set to 00:00:00"
        		}
        	]
        }
        
    insights_internal_test.go:242: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:242
        	Error:      	Should be true
        	Test:       	Test_parseInsightsInterval_week/6_days_are_acceptable
        	Messages:   	start_time and end_time must be valid

=== FAIL: coderd Test_parseInsightsInterval_week (0.00s)
    insights_internal_test.go:162: now: 2023-11-08 23:59:56.781794 +0000 UTC m=+7.293516543
    insights_internal_test.go:166: today: 2023-11-08 00:00:00 +1100 AEDT
    insights_internal_test.go:169: thisHour: 2023-11-08 23:00:00 +1100 AEDT
    insights_internal_test.go:171: twoHoursAgo: 2023-11-08 21:00:00 +1100 AEDT
    insights_internal_test.go:173: thirteenDaysAgo: 2023-10-26 00:00:00 +1100 AEDT
    insights_internal_test.go:176: sixDaysAgo: 2023-11-02 00:00:00 +1100 AEDT
    insights_internal_test.go:178: nineDaysAgo: 2023-10-30 00:00:00 +1100 AEDT

=== FAIL: coderd Test_parseInsightsStartAndEndTime/Today (0.00s)
    insights_internal_test.go:138: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:138
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	Test_parseInsightsStartAndEndTime/Today
    insights_internal_test.go:140: Status:  [400](https://github.com/coder/coder/actions/runs/6805426561/job/18504925666#step:5:401)
    insights_internal_test.go:141: Body:  {
        	"message": "Query parameter has invalid value.",
        	"validations": [
        		{
        			"field": "end_time",
        			"detail": "Query param \"end_time\" must have the clock set to 00:00:00"
        		}
        	]
        }
        
    insights_internal_test.go:146: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:146
        	Error:      	Max difference between 2023-11-08 00:00:00 +0000 UTC and 0001-01-01 00:00:00 +0000 UTC allowed is 0s, but difference was 2562047h47m16.854775807s
        	Test:       	Test_parseInsightsStartAndEndTime/Today
    insights_internal_test.go:147: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:147
        	Error:      	Should be true
        	Test:       	Test_parseInsightsStartAndEndTime/Today
    insights_internal_test.go:148: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:148
        	Error:      	Max difference between 2023-11-08 23:00:00 +0000 UTC and 0001-01-01 00:00:00 +0000 UTC allowed is 0s, but difference was 2562047h47m16.854775807s
        	Test:       	Test_parseInsightsStartAndEndTime/Today
    insights_internal_test.go:149: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/insights_internal_test.go:149
        	Error:      	Should be true
        	Test:       	Test_parseInsightsStartAndEndTime/Today

=== FAIL: coderd Test_parseInsightsStartAndEndTime (0.00s)
```

Seen [here](https://github.com/coder/coder/actions/runs/6805426561/job/18504925666)

### PR DESCRIPTION
**Pull request by f0ssel**
Closes https://github.com/coder/coder/issues/10600

I'm trying to understand why these tests flake sometimes, like here: https://github.com/coder/coder/actions/runs/6805426561/job/18504925666#step:5:428

Here's what I have so far:
- The tests failed very close to midnight: `insights_internal_test.go:162: now: 2023-11-08 23:59:56.781794 +0000 UTC m=+7.293516543`
  - I noticed the monotonic clock reading, ~~and upon further reading about it I think it's reasonable to strip this when dealing with parsed times since we want our operations to match the presentation time.~~ Nvm, time.Parse already has this stripped so that won't do anything...
  - ~~Some tests fail with time not being an even hour, which I believe could be caused by a difference in wall vs monotonic clock.~~ We now think this is because we create a new `time.Now()` inside the function, and with processing lag this can be significant enough to change the time returned.  
- I've added more logging around `Location` and other times in the tests, as well as more verbose error responses so we know what times it thinks it got. My hunch is that all of these tests fail when it runs on a CI machine that has different time settings than we are used to running in. 

With the logs we hopefully have a better shot next time this happens. 

Update:
- After speaking with @mafredri we now pass the `now` time into the function. This is so if we are processing the test very slowly (like in CI) the drift can cause flakes when on a time barrier (end of hour, end of day, etc).

### CODE REVIEW

File: coderd/insights.go [hunk 1]
```diff
@@ -550,6 +550,9 @@ func parseInsightsStartAndEndTime(ctx context.Context, rw http.ResponseWriter, s
 		{"end_time", endTimeString, &endTime},
 	} {
 		t, err := time.Parse(insightsTimeLayout, qp.value)
+		// strip monotonic clock reading
+		// so presentation time and arithmetic operations are consistent
+		t = t.Round(0)
```
Comment (mafredri) [inline coderd/insights.go]: I don't think we need to strip the monotonic clock here since we're parsing a string. Monotonic clock should only be present when `time.Now()` is used. 🤔

Comment (f0ssel) [reply coderd/insights.go]: Yeah I just learned that after making this :P

**Review by kylecarbs — APPROVED** [review]
