### PR TITLE
fix(chatd): prevent chat re-acquisition during server shutdown

### LINKED ISSUE #1371: flake: TestCloseDuringShutdownContextCanceledShouldRetryOnNewReplica
CI Run: https://github.com/coder/coder/actions/runs/22557048431 (job: test-go-pg (ubuntu-latest))
Commit: d033487fffe82c718c2c937d58ec62dbb3551eb1 (author: blinkagent[bot])

Failure:
- Test: TestCloseDuringShutdownContextCanceledShouldRetryOnNewReplica
- Error: Condition never satisfied
- Location: coderd/chatd/chatd_test.go:1011
- Observed logs:
  - "chat-processor: chat canceled during shutdown; returning to pending"
  - "chat-processor: failed to acquire chat  error=\"context canceled\""
  - Test expectation for pending state never became true within testutil.WaitMedium.

Root cause classification: Flaky test (timing-sensitive eventual consistency after shutdown).

Assignment analysis:
- Checked recent changes to the test file: `git log --oneline --follow coderd/chatd/chatd_test.go`.
- Commit 2abe55549c82d7f1bd8e0b7eb6550081bc5e67ec added TestCloseDuringShutdownContextCanceledShouldRetryOnNewReplica and its helper wiring in coderd/chatd/chatd_test.go.
- Assigning to the most recent functional owner of the test: kylecarbs.

Related issues search (coder/internal):
- "TestCloseDuringShutdownContextCanceledShouldRetryOnNewReplica"
- "CloseDuringShutdown"
- "chatd_test.go" "context canceled"
- "failed to acquire chat"
No existing issues found.

Reproduction: Not deterministic; occurs intermittently in CI during shutdown retry flow.

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes https://github.com/coder/internal/issues/1371

## Problem

`TestCloseDuringShutdownContextCanceledShouldRetryOnNewReplica` flakes intermittently in CI. The observed failure is that the chat never reaches `pending` status after `serverA.Close()`.

## Root cause

Race between context cancellation and the mock OpenAI server's stream completion marker.

When `Close()` cancels the server context, the in-flight HTTP streaming request is canceled. The mock server's handler detects this via `req.Context().Done()` and closes its chunks channel. The mock's `writeChatCompletionsStreaming` then writes `data: [DONE]` — the SSE completion marker. On a loopback connection, this marker can reach the client **before** the client's HTTP transport honors the context cancellation.

When this happens:
1. The client sees a successful stream completion (not an error)
2. `chatloop.Run` returns `nil`
3. `processChat` falls through without error → status stays `waiting` (the default)
4. The test expects `pending` → **flake**

## Fix

Skip writing the `[DONE]` marker when the request context is already canceled, in both `writeChatCompletionsStreaming` and `writeResponsesAPIStreaming`.

### CODE REVIEW

File: coderd/chatd/chattest/openai.go [hunk 1]
```diff
@@ -332,6 +339,13 @@ func (s *openAIServer) writeResponsesAPIStreaming(w http.ResponseWriter, chunks
 		}
 	}
 
+	// Don't write [DONE] if the request was canceled — the client
+	// already disconnected and writing a completion marker could
+	// race with the client's context cancellation, making the
+	// stream appear to have completed successfully.
+	if r.Context().Err() != nil {
+		return
+	}
```
Comment (johnstcn) [inline coderd/chatd/chattest/openai.go]: Let's instead select over `chunks` and `r.Context().Done()`.

File: coderd/chatd/chattest/openai.go [hunk 2]
```diff
@@ -231,7 +231,20 @@ func (s *openAIServer) writeChatCompletionsStreaming(w http.ResponseWriter, chun
 		return
 	}
 
-	for chunk := range chunks {
+	for {
+		var chunk OpenAIChunk
+		var ok bool
+		select {
+		case <-r.Context().Done():
```
Comment (johnstcn) [inline coderd/chatd/chattest/openai.go:238]: might be worth dropping a log here

File: coderd/chatd/chattest/openai.go [hunk 3]
```diff
@@ -212,13 +212,13 @@ func (s *openAIServer) writeResponsesAPIResponse(w http.ResponseWriter, req *Ope
...
-		s.writeResponsesAPIStreaming(w, resp.StreamingChunks)
+		s.writeResponsesAPIStreaming(w, req.Request, resp.StreamingChunks)
 	default:
 		s.writeResponsesAPINonStreaming(w, resp.Response)
 	}
 }
 
-func (s *openAIServer) writeChatCompletionsStreaming(w http.ResponseWriter, chunks <-chan OpenAIChunk) {
+func (s *openAIServer) writeChatCompletionsStreaming(w http.ResponseWriter, r *http.Request, chunks <-chan OpenAIChunk) {
 	_ = s // receiver unused but kept for consistency
```
Comment (johnstcn) [inline coderd/chatd/chattest/openai.go]: nit, out-of-scope: just remove the receiver if you're not using it

**Review by johnstcn — APPROVED** [review]
I don't have any further blocking comments. It would be nice to modify the test that originally triggered this flake so that it detects the issue consistently, but I'm not going to block merging based on that.

File: coderd/chatd/chattest/openai.go (hunk 2 above)
Comment (johnstcn) [reply coderd/chatd/chattest/openai.go:238]: I should have been more specific: a `slog.Debug` or something from `cdr.dev/slog`.
