### PR TITLE
fix: force task to be created with latest version

### LINKED ISSUE #19744: bug: tasks: new tasks created with outdated template version
> ...if you launch a new Task after updating the supporting template, the new version of the template isn't automatically used?  You need to go to the supporting workspace, and then update/restart.
Seems like the Task UI maybe caching a template version?

Reproducible on 2.25.1

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fixes https://github.com/coder/coder/issues/19744

### CODE REVIEW

File: site/src/pages/TasksPage/TaskPrompt.tsx [hunk 1]
```diff
@@ -432,3 +433,21 @@ function sortByDefault(a: Preset, b: Preset) {
 	// Otherwise, sort alphabetically by name
 	return a.Name.localeCompare(b.Name);
 }
+
+// TODO: Enforce task creation to always use the latest active template version.
```
Comment (mtojek) [inline site/src/pages/TasksPage/TaskPrompt.tsx:432]: nit: this is rather FIXME than TODO :P

File: site/src/pages/TasksPage/TasksPage.stories.tsx [hunk 2]
```diff
@@ -261,6 +266,17 @@ export const CreateTaskSuccessfully: Story = {
 			await userEvent.click(submitButton);
 		});
 
+		await step("Uses latest template version", () => {
+			expect(API.experimental.createTask).toHaveBeenCalledWith(
```
Comment (mtojek) [inline site/src/pages/TasksPage/TasksPage.stories.tsx:271]: Correct me if I'm wrong, but since this is a story not a unit test, you shouldn't assert API calls on that level?

Can we convert it to jest test instead?

File: site/src/pages/TasksPage/TaskPrompt.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/TasksPage/TaskPrompt.tsx:432]: Is `FIXME` a valid thing? 👀

File: site/src/pages/TasksPage/TasksPage.stories.tsx (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/pages/TasksPage/TasksPage.stories.tsx:271]: We’re using Storybook as our main testing tool. At some point, Jest will only be used for testing functions or other non-component-related code. Kayla did an awesome L&L yesterday about the FE state—I’m just trying to grab the link to share here.

Comment (mtojek) [reply site/src/pages/TasksPage/TasksPage.stories.tsx:271]: Ok, TIL!

File: site/src/pages/TasksPage/TaskPrompt.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/pages/TasksPage/TaskPrompt.tsx:432]: Yeah, we have a lot of fixmes in our codebase :) 

PS. nit-pick!

**Review by mtojek — APPROVED** [review]
