### PR TITLE
fix(site): fix build logs scrolling on safari

### LINKED ISSUE #9687: Workspace build log scrolling doesn't work in Safari
If I open a build log in Safari, I'm unable to scroll it. Works fine in Brave.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/9687

### CODE REVIEW

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx [hunk 1]
```diff
@@ -57,6 +57,34 @@ export const WorkspaceBuildPageView: FC<WorkspaceBuildPageViewProps> = ({
...
+		resizeObserver.observe(document.body);
+
+		return () => {
+			resizeObserver.disconnect();
+		};
+	}, []);
+
 	if (!build) {
 		return <Loader />;
 	}
```
Comment (Parkreiner) [inline site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx:90]: I think we have an edge case here that could break the effect logic:
1. Component mounts with no build
2. We set up the ref and effect to run after the first render
3. The first render completes, but because there's no build, we return out a loader and don't attach the ref to anything
4. The layout effect runs and whiffs
5. We re-render at some point with a build, but because the layout effect dependency array is empty, nothing in it re-runs
6. The only way to get the size mutations to apply at this point is if the browser resizes, but if the user never resizes anything, we're stuck with the same issue as before

Wondering if might be best to make a new component boundary and move this state there. That way, the state only mounts when we're guaranteed to have a build

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx [hunk 2]
```diff
@@ -144,7 +172,10 @@ export const WorkspaceBuildPageView: FC<WorkspaceBuildPageViewProps> = ({
 					))}
 				</Sidebar>
 
-				<div css={{ height: "100%", overflowY: "auto", width: "100%" }}>
+				<div
+					ref={contentRef}
+					css={{ height: "100%", overflowY: "auto", width: "100%" }}
```
[the remark this answers is not in the document]
Comment (Parkreiner) [reply site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx:177]: I think I'd do something like this:
```tsx
const [contentHeight, setContentHeight] = useState<string>()
const contentRef = useRef<HTMLDivElement>(null);
useLayoutEffect(() => {
  // It's been a while since I've had to do this, but dispatching a state update from the
  // resize callback might actually be too slow, and you might get a UI flicker still. You 
  // might need to dispatch the state update AND mutate the DOM node directly when the
  // effect first mounts
}, [])

css={{ height: contentHeight || "100%" }}
```

**Review by buenos-nachos — COMMENTED** [review]
The overall approach makes sense to me – my worry is that I don't think the code is set up 100% correctly, and it won't address all problems that could pop up

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx [hunk 3]
```diff
@@ -212,6 +219,7 @@ const ScrollArea: FC<HTMLProps<HTMLDivElement>> = () => {
 	// Issue: https://github.com/coder/coder/issues/9687
 	// Reference: https://stackoverflow.com/questions/43381836/height100-works-in-chrome-but-not-in-safari
 	const contentRef = useRef<HTMLDivElement>(null);
+	const [height, setHeight] = useState<CSSProperties["width"]>("100%");
```
Comment (Parkreiner) [inline site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx:222]: Tiny thing, but could we set the type to be based on `CSSProperties["height"]>`?

**Review by buenos-nachos — APPROVED** [review]
Looks good! Thanks for bearing with me

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx (hunk 3 above)
Comment (BrunoQuaresma) [reply site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx:222]: lol yes, idk why I used width 🤦
