### PR TITLE
fix(site): show apps with disabled health status on workspaces list

### LINKED ISSUE #20319: Workspace list page filters apps by health, ignoring order attribute
## Problem

On the workspaces list page, `coder_app` resources with lower `order` values may not appear even though they should be displayed first. This is because the workspace list filters apps by health status and ignores the `order` attribute entirely.

## Current Behavior

The `WorkspaceApps` component in `/site/src/pages/WorkspacesPage/WorkspacesTable.tsx` filters apps with:

```typescript
const userApps = agent.apps
  .filter((app) => app.health === "healthy" && !app.hidden)
  .slice(0, remainingSlots);
```

This means:
1. Only apps with `health === "healthy"` are shown
2. Apps without health checks (health === "disabled") are excluded
3. The `order` attribute has no effect on which apps are displayed

## Expected Behavior

Apps should be:
1. Sorted by the `order` attribute
2. Then filtered/sliced to fit available slots
3. Health status could optionally affect visual presentation but shouldn't completely hide apps

## Reproduction

Create a template with two `coder_app` resources:

```hcl
resource "coder_app" "app1" {
  agent_id     = coder_agent.main.id
  slug         = "app1"
  display_name = "Lower Priority App"
  url          = "http://localhost:8080"
  order        = 10
  
  healthcheck {
    url       = "http://localhost:8080/health"
    interval  = 5
    threshold = 1
  }
}

resource "coder_app" "app2" {
  agent_id     = coder_agent.main.id
  slug         = "app2"
  display_name = "Higher Priority App"
  url          = "http://localhost:9090"
  order        = 1  # Lower order = higher priority
  # No healthcheck - health will be "disabled"
}
```

Result: Only `app1` appears on the workspaces list page, even though `app2` has a lower `order` value.

## Workaround

Add a healthcheck to all apps, even if it's a dummy endpoint:

```hcl
healthcheck {
  url       = "http://localhost:9090"  # any non-5XX response works
  interval  = 5
  threshold = 1
}
```

## Suggested Fix

Options to consider:

1. **Sort by order before filtering**: Respect the `order` attribute when selecting which apps to display
2. **Show apps with disabled health checks**: Don't filter out apps that simply don't have health checks configured
3. **Visual indicators instead of hiding**: Show unhealthy apps with a visual indicator rather than hiding them completely

## Related Code

- `/site/src/pages/WorkspacesPage/WorkspacesTable.tsx` (lines 656-658)
- The filtering logic in the `WorkspaceApps` component

### PR DESCRIPTION
**Pull request by EhabY**
Apps without health checks configured (`health === "disabled"`) were hidden from the workspaces list quick-access row. The filter only showed apps with `health === "healthy"`, excluding functional apps that simply don't have health monitoring configured.

Updated the filter to include both `healthy` and `disabled` apps while still excluding `unhealthy` and `initializing` apps.

Fixed #20319

### CODE REVIEW

**Review by johnstcn — APPROVED** [review]

**Comment by matifali** [comment]
Does this also handle external apps like vscode desktop and Cursor?

**Review by DanielleMaywood — CHANGES_REQUESTED** [review]
We shouldn't be writing new jest tests. We should use either Storybook for visual tests or Vitest for behavioral tests

**Comment by EhabY** [comment]
> We shouldn't be writing new jest tests. We should use either Storybook for visual tests or Vitest for behavioral tests

I'll convert this to use Vitest (the whole file) but this requires copying the `jest.setup.ts` into `vitestConfig.ts` to make the tests work.

File: site/test/vitestSetup.ts [hunk 1]
```diff
@@ -8,3 +15,72 @@ import { Blob as NativeBlob } from "node:buffer";
 // introduction of the `ArrayBufferLife` type and the related generic parameters
 // changes.
 globalThis.Blob = NativeBlob;
+
```
Comment (EhabY) [inline site/test/vitestSetup.ts]: Not all of these mocks are needed (like the `contexts/useProxyLatency`) but  I decided to copy the content of `jest.setup.ts` as is (but replacing `global`/`window` with `globalThis`)

Comment (DanielleMaywood) [reply site/test/vitestSetup.ts]: I'm not sure I'm the best person to review this part of the change so I'll tag in @aslilac for review

**Comment by EhabY** [comment]
> Does this also handle external apps like vscode desktop and Cursor?

Yes, this should handle all non-built-in apps

File: site/test/vitestSetup.ts (hunk 1 above)
Comment (aslilac) [reply site/test/vitestSetup.ts]: I would much rather take a targeted approach to bringing mocks over to vitest. these kinds of things live forever. no one is going to come through here later and figure out what's needed and what's not. I think we need to be judicious about keeping this file as minimal as possible, because any cruft is just immediately debt we will never clean up.

**Review by aslilac — COMMENTED** [review]
can we please pare down the additions to vitestSetup.ts to the essential minimum? a lot of this (like the global cleanups) are debt that ideally we wouldn't carry over

File: site/test/vitestSetup.ts (hunk 1 above)
Comment (EhabY) [reply site/test/vitestSetup.ts]: Fair enough, I've only kept a minimal amount of mocks to make the tests work and added some comments. Should we be more systemic there somehow by separating the mocks?

File: site/src/pages/WorkspacesPage/WorkspacesPage.test.tsx [hunk 2]
```diff
@@ -15,15 +17,21 @@ import { server } from "testHelpers/server";
...
-import type { Workspace, WorkspacesResponse } from "api/typesGenerated";
+import type {
+	Workspace,
+	WorkspaceApp,
+	WorkspaceAppHealth,
+	WorkspacesResponse,
+} from "api/typesGenerated";
 import { HttpResponse, http } from "msw";
 import * as CreateDayString from "utils/createDayString";
+import { vi } from "vitest";
```
Comment (aslilac) [inline site/src/pages/WorkspacesPage/WorkspacesPage.test.tsx]:
```suggestion
```

we have globals enabled, this shouldn't be necessary

File: site/test/vitestSetup.ts (hunk 1 above)
Comment (aslilac) [reply site/test/vitestSetup.ts]: yeah, probably. we could treat vitestSetup.ts as an entry point that just imports other files like blob.ts, etc. I think that significantly increases the odds of being able to clean up things as necessary down the line.

File: site/src/pages/WorkspacesPage/WorkspacesPage.test.tsx (hunk 2 above)
Comment (EhabY) [reply site/src/pages/WorkspacesPage/WorkspacesPage.test.tsx]: Removed!

File: site/test/vitestSetup.ts (hunk 1 above)
Comment (EhabY) [reply site/test/vitestSetup.ts]: I've split it into chunks:

- setup/polyfills.ts: Blob, ResizeObserver polyfills
- setup/domStubs.ts: Radix UI pointer capture stubs
- setup/mocks.ts: useProxyLatency mock
- setup/msw.ts: MSW server lifecycle

**Review by aslilac — APPROVED** [review]

**Review by DanielleMaywood — APPROVED** [review]
