### PR TITLE
fix!: support empty or default fields when updating templates

### LINKED ISSUE #19036: bug: Templates PATCH request issue
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I'm trying to update the default_ttl_ms of the templates in coder throuch PATCH request using /api/v2/templates/{template_id}. The value for default_ttl_ms is updating as expected; however, I noticed that the icon is being removed from the template.

### Relevant Log Output

```shell

```

### Expected Behavior

_No response_

### Steps to Reproduce

1. Make sure atleast one template has an icon. Make a GET call to /api/v2/templates view all the templates metadata. there should be a value for the icon field 
2. Make a patch request  using /api/v2/templates/{template_id} with the body {
"default_ttl_ms": XXXX}
3. make a GET all again to view the template metadata and see the icon field empty. 

### Environment

- Host OS:
- Coder version: V2

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rafrdz**
Breaking change: Field types in `codersdk.UpdateTemplateMeta` for `Icon`, `Description`, and `DisplayName` moved to `*string`

## Summary

In this pull request we're updating the `UpdateTemplateMeta` struct to allow `DisplayName`, `Description`, and `Icon` to be set as empty `""` or default to the value from the template if not provided in an update call.

Fixes https://github.com/coder/coder/issues/19036

### The bug

The reported bug occurred when clients were attempting to update a metadata field in a template via an edit call. When the request was decoded into an `UpdateTemplateMeta` struct the default values for fields in the struct were used to update the template even if they weren't provided. This led to fields like `Icon` being set to `""` (the default value).

### Changes

To allow for specific fields to be set to `""` these fields were updated to be `*string` as opposed to `string`. This allows for clients to set these fields as `""` in an update request or they will default to the template value if they are not provided in the update request (will be `nil`).

Added tests to confirm empty and nil values and updated other tests that use these fields.

### CODE REVIEW

**Comment by rafrdz** [comment]
I have read the CLA Document and I hereby sign the CLA

File: coderd/templates_test.go [hunk 1]
```diff
@@ -1618,6 +1618,69 @@ func TestPatchTemplateMeta(t *testing.T) {
...
+				updated, err := client.UpdateTemplateMeta(ctx, template.ID, tc.req)
+				require.NoError(t, err)
+				assert.Equal(t, tc.expected.description, updated.Description)
+				assert.Equal(t, tc.expected.icon, updated.Icon)
+				assert.Equal(t, tc.expected.defaultTTLMillis, updated.DefaultTTLMillis)
+
+				// Restore template after each test case
+				_, err = client.UpdateTemplateMeta(ctx, template.ID, restoreReq)
+				require.NoError(t, err)
+			})
```
Comment (Emyrk) [inline coderd/templates_test.go]: Just make sure the `restore` always runs, even if the original context is cancelled, the original update errors, or anything else crazy happens.
```suggestion
			t.Run(tc.name, func(t *testing.T) {
				defer func() {
					ctx := testutil.Context(t, testutil.WaitShort)
					// Restore template after each test case
					_, err := client.UpdateTemplateMeta(ctx, template.ID, restoreReq)
					require.NoError(t, err)
				}()
				
				ctx := testutil.Context(t, testutil.WaitLong)
				updated, err := client.UpdateTemplateMeta(ctx, template.ID, tc.req)
				require.NoError(t, err)
				assert.Equal(t, tc.expected.description, updated.Description)
				assert.Equal(t, tc.expected.icon, updated.Icon)
				assert.Equal(t, tc.expected.defaultTTLMillis, updated.DefaultTTLMillis)
			})
```

File: coderd/templates_test.go [hunk 2]
```diff
@@ -1618,6 +1618,69 @@ func TestPatchTemplateMeta(t *testing.T) {
...
+			{name: "Nil description defaults to template description", req: codersdk.UpdateTemplateMeta{Description: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
+			{name: "Nil icon defaults to template icon", req: codersdk.UpdateTemplateMeta{Icon: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
+		}
+
+		// It is unfortunate we need to sleep, but the test can fail if the
+		// updatedAt is too close together.
+		time.Sleep(time.Millisecond * 5)
+
+		for _, tc := range tests {
+			t.Run(tc.name, func(t *testing.T) {
```
Comment (Emyrk) [inline coderd/templates_test.go:1704]: You will have to add a nolint
```suggestion
			//nolint:tparallel,paralleltest
			t.Run(tc.name, func(t *testing.T) {
```

File: coderd/templates_test.go [hunk 3]
```diff
@@ -1618,6 +1618,69 @@ func TestPatchTemplateMeta(t *testing.T) {
...
+			{name: "Only update default_ttl_ms", req: codersdk.UpdateTemplateMeta{DefaultTTLMillis: 99 * time.Hour.Milliseconds()}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 99 * time.Hour.Milliseconds()}},
+			{name: "Clear description", req: codersdk.UpdateTemplateMeta{Description: ptr.Ref("")}, expected: expected{description: "", icon: template.Icon, defaultTTLMillis: 0}},
+			{name: "Clear icon", req: codersdk.UpdateTemplateMeta{Icon: ptr.Ref("")}, expected: expected{description: template.Description, icon: "", defaultTTLMillis: 0}},
+			{name: "Nil description defaults to template description", req: codersdk.UpdateTemplateMeta{Description: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
+			{name: "Nil icon defaults to template icon", req: codersdk.UpdateTemplateMeta{Icon: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
+		}
+
+		// It is unfortunate we need to sleep, but the test can fail if the
+		// updatedAt is too close together.
+		time.Sleep(time.Millisecond * 5)
```
Comment (Emyrk) [inline coderd/templates_test.go]: What is the failure here? Ideally we can remove this.

Just a note, we have `testutil.IntervalFast` for standard intervals.

File: coderd/templates_test.go [hunk 4]
```diff
@@ -1618,6 +1618,69 @@ func TestPatchTemplateMeta(t *testing.T) {
...
+			req      codersdk.UpdateTemplateMeta
+			expected expected
+		}
+
+		tests := []testCase{
+			{name: "Only update default_ttl_ms", req: codersdk.UpdateTemplateMeta{DefaultTTLMillis: 99 * time.Hour.Milliseconds()}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 99 * time.Hour.Milliseconds()}},
+			{name: "Clear description", req: codersdk.UpdateTemplateMeta{Description: ptr.Ref("")}, expected: expected{description: "", icon: template.Icon, defaultTTLMillis: 0}},
+			{name: "Clear icon", req: codersdk.UpdateTemplateMeta{Icon: ptr.Ref("")}, expected: expected{description: template.Description, icon: "", defaultTTLMillis: 0}},
+			{name: "Nil description defaults to template description", req: codersdk.UpdateTemplateMeta{Description: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
+			{name: "Nil icon defaults to template icon", req: codersdk.UpdateTemplateMeta{Icon: nil}, expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 0}},
```
Comment (Emyrk) [inline coderd/templates_test.go]: I know it is more LoC, but it would be easier to read if we break this out into multi lines:

```golang
			{
				name:     "Only update default_ttl_ms",
				req:      codersdk.UpdateTemplateMeta{DefaultTTLMillis: 99 * time.Hour.Milliseconds()},
				expected: expected{description: template.Description, icon: template.Icon, defaultTTLMillis: 99 * time.Hour.Milliseconds()},
			},
```

File: coderd/templates_test.go [hunk 5]
```diff
@@ -1618,6 +1618,69 @@ func TestPatchTemplateMeta(t *testing.T) {
...
+
+		client := coderdtest.New(t, nil)
+		user := coderdtest.CreateFirstUser(t, client)
+		version := coderdtest.CreateTemplateVersion(t, client, user.OrganizationID, nil)
+
+		description := "test-description"
+		icon := "/icon/icon.png"
+		defaultTTLMillis := 10 * time.Hour.Milliseconds()
+
+		template := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID, func(ctr *codersdk.CreateTemplateRequest) {
```
Comment (Emyrk) [inline coderd/templates_test.go]: _The 2 hardest problems in software is naming and caching... and off by 1 errors_

`template` as a name here does not indicate this template is the expected/reference/original. Can we name it something more indicative of it's function in this test?

```suggestion
		reference := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID, func(ctr *codersdk.CreateTemplateRequest) {
```

Comment (Emyrk) [inline coderd/templates_test.go]: A bit overkill, but since `template.Description` is the reference for the test cases.

```suggestion
		template := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID, func(ctr *codersdk.CreateTemplateRequest) {
		require.Equal(t, description, template.Description)
		require.Equal(t, icon, template.Icon)
```

File: coderd/templates_test.go (hunk 3 above)
Comment (rafrdz) [reply coderd/templates_test.go]: Result of copy/paste on my part when setting up the test. Read more into it and removed this. Thanks for the info!

**Comment by Emyrk** [comment]
Can we add a `!` to the title? -> `fix!`

This is a breaking change for the `codersdk`, so we should mark this commit as such.

**Review by Emyrk — APPROVED** [review]
LG :+1: 

Just throw the `!` in the commit title, `fix!:`. Add to the description the breaking change is the field types in `codersdk.UpdateTemplateMeta` for `icon`, `description`, and `displayname` moved to `*string`

Interestingly, the typescript types are unchanged because `omitempty` was included. So the typscript was already correct :heart: 

```typescript
	readonly display_name?: string;
	readonly description?: string;
	readonly icon?: string;
```
