### PR TITLE
fix: add missing focus state styling to buttons and checkboxes

### LINKED ISSUE #9855: A11y: Not all checkboxes have visible focus state
This is more of an issue for users navigating the site with a keyboard (Tab or Shift+Tab). At the very least, it affects all the checkboxes in the Workspaces view.

https://github.com/coder/coder/assets/28937484/ab5cc056-33e1-4ac7-820c-993f3fe1354f

When a checkbox has focus, there is no visual indicator. So, you can use your keyboard for most of the interactive elements, but the moment focus shifts to the checkbox, it's not clear where you are, or what pressing Space/Enter will do.

Should hopefully be a straightforward fix. Only obvious pitfall to me is that you have to make sure focus styling is defined before hover styling or active styling in the CSS cascade

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #9855 and adds a couple of other changes, too.

## Changes made
- Adds visual focus state to all checkboxes
-  Adds visual focus state to all switches
- Adds visual focus state to all icon buttons

Screenshot 2023-11-09 at 2 58 28 PM
Screenshot 2023-11-09 at 2 58 46 PM
Screenshot 2023-11-09 at 2 58 16 PM

There might be some other components that need similar updates, but this should help keyboard navigation in the site a lot.

### CODE REVIEW

File: site/src/theme/theme.ts [hunk 1]
```diff
@@ -427,15 +427,40 @@ dark = createTheme(dark, {
...
+           * tables). Tried every combination of selector possible (including
+           * lots of !important), and the main issue seems to be that the
+           * styling just never gets processed for it to get injected into the
+           * CSSOM.
+           *
+           * Had to settle for adding styling to the span itself (which does
+           * make the styling more obvious, even if there's not much room for
+           * customization).
+           */
+          "&.Mui-focusVisible": {
```
Comment (Parkreiner) [inline site/src/theme/theme.ts:446]: This is the reason why this PR went from taking five minutes to three hours.

**Comment by matifali** [comment]
That's super nice. Will improve the accessibility for sure.
