### PR TITLE
fix: fix duplicated agent logs

### LINKED ISSUE #16355: bug: ui: workspace build logs duplicated during build process
# Problem

Coder version 2.18.5

When building a template that uses an external log source (e.g. `envbuilder`), we can observe the following:

- During build process, logs increment normally to `$LAST_LOG_ID` up until the build completes.
- When build process complete, logs increment to a multiple of `$LAST_LOG_ID`, giving the mistaken impression that the build is occurring multiple times. It appears as a large "dump" of logs all at once in the UI.

Image

- If you hit the workspace agent build logs endpoint directly (`http://$CODER/api/v2/workspaceagents/$AGENT_ID/logs`), the correct number of logs is shown, with no duplicate entries.

First log ID:
Image

Last log ID:
Image

- After a refresh of the page, the build logs drawer shows the correct number of logs:

Image

- It appears that the UI is performing multiple WS requests for the build logs and simply appending them to the log panel:

Image

Image

Image

# Steps to reproduce:

- Either use `docker-compose` or `lima` to set up a fresh Coder instance
- Import the Devcontainers (Docker) template and use the defaults.
- Create a new workspace and select one of the pre-defined options (reproduced using home-assistant repo)
  - Important: before starting the build, open the DevTools, switch to "Network", and filter "all requests" by "logs".
- Wait for build to complete **without** refreshing the UI, and observe the last number in the build logs.

# Proposed Solution

Each log entry has a unique identifier (`id`) that can be used to de-duplicate in the logs pane.
If it's not possible to avoid the multiple requests, maybe this could be used to de-duplicate?

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/16355

### CODE REVIEW

File: site/src/modules/resources/AgentRow.tsx [hunk 1]
```diff
@@ -160,7 +155,13 @@ export const AgentRow: FC<AgentRowProps> = ({
 		select: (res) => res.containers.filter((c) => c.status === "running"),
 		// TODO: Implement a websocket connection to get updates on containers
 		// without having to poll.
-		refetchInterval: 10_000,
+		refetchInterval: (data) => {
+			if (!data) {
+				return false;
+			}
+
+			return data.length > 0 ? 10_000 : false;
```
Comment (johnstcn) [inline site/src/modules/resources/AgentRow.tsx:163]: So returning `false` here will pause refetch? What if we return `0` instead?

Comment (BrunoQuaresma) [reply site/src/modules/resources/AgentRow.tsx:163]: Yeap, false will pause the refetch. Not sure if 0 would work. From the docs:

```
refetchInterval: number | false | ((query: Query) => number | false | undefined)
Optional
If set to a number, all queries will continuously refetch at this frequency in milliseconds
If set to a function, the function will be executed with the query to compute a frequency
```

Comment (BrunoQuaresma) [reply site/src/modules/resources/AgentRow.tsx:163]: Maybe I was to naive about this. I tried to fix that because I was getting A LOT of 403 errors because of the refetch interval logic. 

So, IMO we can just:
- Do not "hide" the 403 error.
- If there is any error, stop pulling.

Does it sound right? I think I will remove the fix from this PR since it is out of the scope and open a new one.

Comment (Parkreiner) [reply site/src/modules/resources/AgentRow.tsx]: Yeah, the RQ docs weren't clear on this, so I just checked the source code. You have to follow the logic from this method a little bit, but [it does have protections to make sure that if you accidentally pass in a value of `0`, it will basically treat that as there not being an interval defined](https://github.com/TanStack/query/blob/2be8cca104443ecb26c02941c5c3717d4e517722/packages/query-core/src/queryObserver.ts#L369)

File: site/src/api/api.ts [hunk 2]
```diff
@@ -221,11 +221,11 @@ export const watchBuildLogsByTemplateVersionId = (
 
 export const watchWorkspaceAgentLogs = (
 	agentId: string,
-	{ after, onMessage, onDone, onError }: WatchWorkspaceAgentLogsOptions,
+	params?: WatchWorkspaceAgentLogsParams,
 ) => {
 	const searchParams = new URLSearchParams({
 		follow: "true",
-		after: after.toString(),
+		after: params?.after ? params?.after.toString() : "",
```
Comment (Parkreiner) [inline site/src/api/api.ts:228]: Could we make this `params?.after.toString() ?? ""`?

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx [hunk 3]
```diff
@@ -50,12 +51,12 @@ const renderWorkspacePage = async (
...
-	jest
-		.spyOn(apiModule, "watchWorkspaceAgentLogs")
-		.mockImplementation((_, options) => {
-			options.onDone?.();
-			return new WebSocket("");
-		});
+	jest.spyOn(apiModule, "watchWorkspaceAgentLogs").mockImplementation(
+		() =>
+			new OneWayWebSocket({
+				apiRoute: "",
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/WorkspacePage.test.tsx:57]: Does it make sense to pass in an empty string for the API route? I don't know if we've updated the class since I merged it in originally, but I remember that it was originally made so that you couldn't update the URL after instantiation

A socket like this would always be useless, right?

File: site/src/modules/resources/useAgentLogs.ts [hunk 4]
```diff
@@ -0,0 +1,49 @@
+import { watchWorkspaceAgentLogs } from "api/api";
+import type { WorkspaceAgent, WorkspaceAgentLog } from "api/typesGenerated";
+import { displayError } from "components/GlobalSnackbar/utils";
+import { useEffect, useState } from "react";
+
+export function useAgentLogs(
+	agent: WorkspaceAgent,
+	enabled: boolean,
+): readonly WorkspaceAgentLog[] | undefined {
+	const [logs, setLogs] = useState<WorkspaceAgentLog[]>();
```
Comment (Parkreiner) [inline site/src/modules/resources/useAgentLogs.ts:10]: What do you think of making the hook so that it always returns an array, and if we don't have logs, we return an empty array?

I feel like that might help clean up some of the render logic long-term, but I also don't know if we need to differentiate between logs not existing because we haven't gotten anything back from the server yet, versus logs not existing because the server explicitly told us that it doesn't have anything

Comment (Parkreiner) [reply site/src/modules/resources/useAgentLogs.ts:10]: It'd also simplify line 29's state update logic

**Review by buenos-nachos — COMMENTED** [review]
Nothing jumped out to me with the logic, but obviously the stories a little wrong now. Happy to re-review once those get fixed up

File: site/src/modules/resources/useAgentLogs.ts (hunk 4 above)
Comment (BrunoQuaresma) [reply site/src/modules/resources/useAgentLogs.ts:10]: For now, I don't think it would be a problem. I like the idea 👍

**Review by johnstcn — COMMENTED** [review]
LGTM and tested in my dogfood env, but deferring to @Parkreiner for approval on the TS side.

**Review by buenos-nachos — APPROVED** [review]
I'm okay with this, too

**Review by mafredri — APPROVED** [review]
LGTM!
