### PR TITLE
fix: refresh entitlements after creating first user

### LINKED ISSUE #6080: A refresh the coder server is needed after creating the first user to see Enterprise features
When you set up a new Coder deployment, you have to refresh the page to see the enterprise features.

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/6080

This PR extends `postFirstUser` API operation to refresh entitlements after generating the trial license and creating the first user. Without this change, entitlements are refreshed after 10 minutes interval.

How to test:

1. Start coder:
```
rm -rf ./.coderv2 # need a fresh database
./scripts/develop.sh # the script will create the first user and generate the trial license
```

2. See entitlements: http://localhost:3000/api/v2/entitlements . Trial should be active.

### CODE REVIEW

File: coderd/users_test.go [hunk 1]
```diff
@@ -94,7 +100,8 @@ func TestFirstUser(t *testing.T) {
 		}
 		_, err := client.CreateFirstUser(ctx, req)
 		require.NoError(t, err)
-		<-called
+		<-trialGenerated
+		<-entitlementsRefreshed
```
Comment (johnstcn) [inline coderd/users_test.go:104]: suggest using `testutil.RequireRecvCtx` to avoid the test hanging indefinitely.

**Review by johnstcn — APPROVED** [review]

File: coderd/users_test.go (hunk 1 above)
Comment (mtojek) [reply coderd/users_test.go]: Fixed 👍
