### PR TITLE
fix(agent/agentcontainers): handle race between docker ps and docker inspect

### LINKED ISSUE #586: flake: TestExpRpty/Container
Seen on `main`: https://github.com/coder/coder/actions/runs/14495685123/job/40662749622#step:7:289

```console
        	Error Trace:	/home/runner/work/coder/coder/cli/exp_rpty_test.go:125
        	            				/home/runner/work/coder/coder/cli/ssh_test.go:2149
        	            				/opt/hostedtoolcache/go/1.24.1/x64/src/runtime/asm_amd64.s:1700
        	Error:      	Received unexpected error:
        	            	running command "coder exp rpty": GET http://localhost:34079/api/v2/workspaceagents/0188aabd-8ced-4876-895f-f1b6b754143f/containers: unexpected status code 500: Internal error fetching containers.
        	            		Error: GET http://[fd7a:115c:a1e0:4876:895f:f1b6:b754:143f]:4/api/v0/containers: unexpected status code 500: Could not get containers.
        	            		Error: get containers: run docker inspect: exit status 1: Error: No such object: c7dcabdb3ebfae7bf90b69131d1c52e4b9c27c919594fbb903c086f61b55b375: exit status 1
```

As per [blame](https://github.com/coder/coder/blame/feb1a3dc02d260941e751f0033f69b9dff2fe464/cli/exp_rpty_test.go#L83) assiging to @johnstcn

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/internal/issues/586#event-17291038671

### CODE REVIEW

File: agent/agentcontainers/containers_dockercli.go [hunk 1]
```diff
@@ -241,6 +228,19 @@ func run(ctx context.Context, execer agentexec.Execer, cmd string, args ...strin
...
+}
+
+var _ Lister = &DockerCLILister{}
+
+func NewDocker(execer agentexec.Execer, opts ...func(*DockerCLILister)) Lister {
+	return &DockerCLILister{
+		execer: agentexec.DefaultExecer,
+	}
+}
+
```
Comment (johnstcn) [inline agent/agentcontainers/containers_dockercli.go:243]: review: just moved down a bit closer to the method definitions

File: agent/agentcontainers/devcontainercli_test.go [hunk 2]
```diff
@@ -229,6 +230,12 @@ func TestDockerDevcontainerCLI(t *testing.T) {
 	if os.Getenv("CODER_TEST_USE_DOCKER") != "1" {
 		t.Skip("skipping Docker test; set CODER_TEST_USE_DOCKER=1 to run")
 	}
+	if runtime.GOOS != "linux" {
+		t.Skip("Skipping on non-Linux OS")
+	}
+	if _, err := exec.LookPath("devcontainer"); err != nil {
+		t.Fatal("this test requires the devcontainer CLI: npm install -g @devcontainers/cli")
+	}
```
Comment (johnstcn) [inline agent/agentcontainers/devcontainercli_test.go:238]: review: I didn't look too closely into what was actually going on here, but I suspect it's related to path differences between the host and the Docker VM on MacOS/Windows.

File: agent/agentcontainers/containers_dockercli.go [hunk 3]
```diff
@@ -310,19 +310,24 @@ func (dcl *DockerCLILister) List(ctx context.Context) (codersdk.WorkspaceAgentLi
...
 	stdout = bytes.TrimSpace(stdoutBuf.Bytes())
 	stderr = bytes.TrimSpace(stderrBuf.Bytes())
 	if err != nil {
-		return stdout, stderr, err
+		if bytes.Contains(stderr, []byte("No such object:")) {
+			// This can happen if a container is deleted between the time we check for its existence and the time we inspect it.
+			retErr = nil
+		} else {
+			retErr = err
+		}
```
Comment (mafredri) [inline agent/agentcontainers/containers_dockercli.go:327]: Can we just return early instead of indirection of `retErr`? This code path seems error-prone to me with the second err var.

File: agent/agentcontainers/devcontainercli_test.go (hunk 2 above)
Comment (mafredri) [reply agent/agentcontainers/devcontainercli_test.go:238]: I've run this on macOS as well, so IMO we could allow that, but agree that we need to verify the devcontainer CLI here, good add 👍🏻

**Comment by johnstcn** [comment]
> I've run this on macOS as well, so IMO we could allow that

Interesting, so "works on my machine" 🤔 I tried to figure out what the root cause was on my end, but the error returned by `devcontainer-cli` is not terribly useful:

```
          	Error Trace:	/Users/cian/src/coder/coder/agent/agentcontainers/devcontainercli_test.go:256
            	Error:      	Received unexpected error:
            	            	exit status 1
            	            	devcontainer up failed: error (description: An error occurred setting up the container., message: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/tmp/nix-shell.56XzZC/TestDockerDevcontainerCLIContainerLifecycle1281021640/001,target=/workspaces/001,consistency=cached -l devcontainer.local_folder=/tmp/nix-shell.56XzZC/TestDockerDevcontainerCLIContainerLifecycle1281021640/001 -l devcontainer.config_file=/tmp/nix-shell.56XzZC/TestDockerDevcontainerCLIContainerLifecycle1281021640/001/.devcontainer/devcontainer.json -e TEST_CONTAINER=true --label com.coder.test=devcontainercli --entrypoint /bin/sh -l devcontainer.metadata=[{"containerEnv":{"TEST_CONTAINER":"true"}}] alpine:latest -c echo Container started
```

**Comment by mafredri** [comment]
@johnstcn interesting, here's me on macOS:

```
❯ CODER_TEST_USE_DOCKER=1 go test ./agent/agentcontainers -count=1
ok      github.com/coder/coder/v2/agent/agentcontainers 4.978s
```

Perhaps it's a Nix issue?

**Review by mafredri — APPROVED** [review]

**Comment by mafredri** [comment]
> It happens outside the nix environment as well, strangely enough 🤷

Then it's probably a matter of your Docker configuration, you might have to add `/tmp` to allowed paths.
