### PR TITLE
fix: detect and retry reverse port forward on used port

### LINKED ISSUE #10799: flake: TestAgent_TCPRemoteForwarding
```
   agent_test.go:785: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/agent/agent_test.go:785
        	            				/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/asm_amd64.s:1598
        	Error:      	Not equal: 
        	            	expected: "test"
        	            	actual  : "SSH-"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-test
        	            	+SSH-
        	Test:       	TestAgent_TCPRemoteForwarding
```

https://github.com/coder/coder/runs/18851340826

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #10799

The flake happens when we try to remote forward, but the port we've chosen is not free.  In the flaked example, it's actually the SSH listener that occupies the port we try to remote forward, leading to confusing reads (c.f. the linked issue).

This fix simplies the tests considerably by using the Go ssh client, rather than shelling out to OpenSSH.  This avoids using a pseudoterminal, avoids the need for starting any local OS listeners to communicate the forwarding (go SSH just returns in-process listeners), and avoids an OS listener to wire OpenSSH up to the agentConn.

With the simplied logic, we can immediately tell if a remote forward on a random port fails, so we can do this in a loop until success or timeout.

I've also simplified and fixed up the other forwarding tests. Since we set up forwarding in-process with Go ssh, we can remove a lot of the `require.Eventually` logic.

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10844** <a href="https://app.graphite.dev/github/pr/coder/coder/10844?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/10844?utm_source=stack-comment).

File: agent/agent_test.go [hunk 1]
```diff
@@ -2580,3 +2364,47 @@ func (s *syncWriter) Write(p []byte) (int, error) {
...
+// instead of opening a listener and closing it to find a port that is likely to be free, since
+// sometimes the OS reallocates the port very quickly.
+func pickRandomPort() uint16 {
+	const (
+		// Overlap of windows, linux in https://en.wikipedia.org/wiki/Ephemeral_port
+		min = 49152
+		max = 60999
+	)
+	n := max - min
+	x := rand.Intn(n)
```
Comment (deansheather) [inline agent/agent_test.go:2378]:
```suggestion
	x := rand.Intn(n) //nolint:gosec
```

**Review by deansheather — APPROVED** [review]

**Review by johnstcn — APPROVED** [review]

**Comment by spikecurtis** [comment]
### Merge activity

* **Nov 27, 12:42 AM**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/10844).
