### PR TITLE
fix: strip timezone information from a date in dau response

### LINKED ISSUE #11943: Active user count on deployment page has date off by one day
The graph of daily active users on the "Deployment" page always shows a date one day earlier than the current day for the latest data point (which appears to reflect the number for the current day). I don't think this is a time zone issue, since displaying the date in an inaccurate timezone would lead to an error in the opposite direction, but it might be something internal where the system attempts to compensate for timezones and overcorrects.

Possibly related: #7275

### PR DESCRIPTION
**Pull request by Emyrk**
Timezone information is lost, so do not forward it to the client.

See issue for debugging details

Closes https://github.com/coder/coder/issues/11943

### CODE REVIEW

File: codersdk/deployment.go [hunk 1]
```diff
@@ -2184,14 +2186,22 @@ func (d DAURequest) asRequestOption() RequestOption {
...
-	// Convert to hours
-	return offsetSec / 60 / 60
+	_, offsetSec := now.In(loc).Zone()
+	// Convert to hours and flip the sign
+	return -1 * offsetSec / 60 / 60
+}
+
+func TimezoneOffsetHour(loc *time.Location) int {
+	return TimezoneOffsetHourWithTime(time.Now(), loc)
 }
```
Comment (Emyrk) [inline codersdk/deployment.go:2205]: This value was flipped from the javascript implementation. Given this value comes from the browser, I made it match the javascript. I fixed all the tests to be deterministic so we can keep them on.

**Review by johnstcn — APPROVED** [review]
