### PR TITLE
fix: remove deprecation warnings when option unset

### LINKED ISSUE #6531: Warnings on server startup for unset vars
If you run `coder server` with no flags you still get warnings for deprecated values:

```
WARN: Address is deprecated, please use HTTP Address and TLS Address instead.
WARN: Redirect HTTP to HTTPS is deprecated, please use Redirect to Access URL instead.
```

Seems related to the bigcli transition.

### PR DESCRIPTION
**Pull request by ammario**
Resolves #6531

### CODE REVIEW

File: cli/server.go [hunk 1]
```diff
@@ -257,6 +257,10 @@ flags, and YAML configuration. The precedence is as follows:
 					continue
 				}
 
+				if opt.Value.String() == opt.Default {
+					continue
+				}
```
Comment (deansheather) [inline cli/server.go:262]: Could you add a field to bigcli types similar to what cobra had for `.Changed()`?

**Review by deansheather — APPROVED** [review]
