### PR TITLE
fix: Avoid use of r.Context() after r.Hijack()

### LINKED ISSUE #1508: Bug: Goroutine leak in `coderd.(*api).workspaceAgentTurn`
There seems to be a goroutine leak in `coderd.(*api).workspaceAgentTurn`.

This could be seen as two bugs:

1. Goroutine leak
2. Use of `(*http.Request).Context()` after `Hijack` in more than one place

## Steps to Reproduce

0. Enable pprof for coder server
1. `coder ssh dev`
3. `ctlr+d`
4. Goto 1
5. Check pprof (`go tool pprof -http=:8080 http://localhost:6060/debug/pprof/goroutine`)

The leak is in part due to reliance on the `http.Request` context and use of websockets. The underlying websocket library calls `(*http.Request).Hijack` which disables context propagation.

This happens here: https://github.com/coder/coder/blob/668a6712e62a839a193544e431552744520b05df/coderd/workspaceagents.go#L304

And the following contexts will not cancel until the http handler completes:
https://github.com/coder/coder/blob/668a6712e62a839a193544e431552744520b05df/coderd/workspaceagents.go#L316

https://github.com/coder/coder/blob/668a6712e62a839a193544e431552744520b05df/coderd/workspaceagents.go#L320

We must avoid using `r.Context()` after hijack, unless we are using it with the expectation that the http handler will exit (at which point the context will complete).

I'm unfamiliar with the [`pion/turn`](https://github.com/pion/turn) package, but another factor could be wrt how it handles connection closure, perhaps it does not propagate as we expect since we're not calling `wsConn.Close()` due to context reliance?

---

Similar reliance on request context after hijack is done elsewhere, we should rethink all of them. Example:

https://github.com/coder/coder/blob/668a6712e62a839a193544e431552744520b05df/coderd/workspaceagents.go#L155

### PR DESCRIPTION
**Pull request by mafredri**
This PR changes how we initialize `websocket.NetConn`s so that we have a context that emits connection closure.

Fixes #1508

- fix: Fix goroutine leak by propagating websocket closure
- fix: Use of r.Context() in workspaceAgentDial
- fix: Use of rw and r.Context() in workspaceAgentListen
- fix: Use of r.Context() in workspaceAgentPTY

This is version 2. Initially I implemented `io.EOF` closure propagation in `coderd/turnconn.Conn`, while I do think it may be a good idea, it's not necessary to fix #1508. I implemented it this way so that the fix can be utilized in the other handlers as well.

### CODE REVIEW

File: coderd/workspaceagents.go [hunk 1]
```diff
@@ -370,12 +376,12 @@ func (api *API) workspaceAgentPTY(rw http.ResponseWriter, r *http.Request) {
 		})
 		return
 	}
-	defer func() {
-		_ = conn.Close(websocket.StatusNormalClosure, "ended")
```
Comment (mafredri) [inline coderd/workspaceagents.go:374]: Is this `"ended"` message important?

Calling `wsNetConn.Close()` bellow will simply close it with `(StatusNormalClosure, "")`.

File: coderd/workspaceagents.go [hunk 2]
```diff
@@ -370,12 +376,12 @@ func (api *API) workspaceAgentPTY(rw http.ResponseWriter, r *http.Request) {
...
-	}()
+
 	// Accept text connections, because it's more developer friendly.
```
Comment (mafredri) [inline coderd/workspaceagents.go:380]: This comment seems to have been out of date, should it be removed?

File: coderd/workspaceagents.go [hunk 3]
```diff
@@ -143,29 +147,31 @@ func (api *API) workspaceAgentListen(rw http.ResponseWriter, r *http.Request) {
...
 
 	workspaceAgent := httpmw.WorkspaceAgent(r)
-	conn, err := websocket.Accept(rw, r, &websocket.AcceptOptions{
-		CompressionMode: websocket.CompressionDisabled,
-	})
+
+	resource, err := api.Database.GetWorkspaceResourceByID(r.Context(), workspaceAgent.ResourceID)
 	if err != nil {
 		httpapi.Write(rw, http.StatusBadRequest, httpapi.Response{
 			Message: fmt.Sprintf("accept websocket: %s", err),
```
Comment (deansheather) [inline coderd/workspaceagents.go:154]: error message is incorrect now

**Review by deansheather — APPROVED** [review]

File: coderd/workspaceagents.go (hunk 3 above)
Comment (mafredri) [reply coderd/workspaceagents.go:154]: Good catch, it was invalid before (due to use of `rw` after Hijack), didn't think to read the message.. 😂

File: coderd/workspaceagents.go [hunk 4]
```diff
@@ -501,3 +509,44 @@ func convertWorkspaceAgent(dbAgent database.WorkspaceAgent, agentUpdateFrequency
...
+// wsNetConn wraps net.Conn created by websocket.NetConn(). Cancel func
+// is called if io.EOF is encountered.
+type wsNetConn struct {
+	cancel context.CancelFunc
+	net.Conn
+}
+
+func (c *wsNetConn) Read(b []byte) (n int, err error) {
+	n, err = c.Conn.Read(b)
+	if errors.Is(err, io.EOF) {
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/workspaceagents.go:522]: Hmm, good point. I only ran into `io.EOF` in testing but taking a deeper dive into the code would indicate that it's not so predictable. Do you think there are any valid errors from `Read`/`Write` we'd need to consider or should we just cancel on any error? I'll try to dig a bit deeper to figure out what errors we may see.

[the remark this answers is not in the document]
Comment (deansheather) [reply coderd/workspaceagents.go:522]: For now we might as well just cancel on any error just to be safe, there isn't any case I can think of where we happily accept websocket errors and continue on

**Review by johnstcn — APPROVED** [review]
