### PR TITLE
Audit build outcomes/kira pilot

### LINKED ISSUE #4724: audit: resource creation failure should result in an audit log entry
~If someone attempts to create a workspace or template or whatever [other resource](https://coder.com/docs/coder-oss/latest/admin/audit-logs) and that creation fails, we should create an audit log for it.~

~At the time of ticket creation, we do not yet audit log login/logout, but we should consider this resource when completing this ticket. Related ticket #4431~

The real issue is workspace build outcomes are not currently logged. We log the request (this almost always comes back as a 201), but do not follow up with the outcome. For an example, take a look at the comment below regarding workspace deletion.

We should continue to log workspace build requests with language that indicates the outcome isn't guaranteed, like:

"Admin requested the deletion of workspace test".

Then we should follow up with an audit log for the outcome, e.g. "Workspace test successfully deleted". 

We should also log workspace build failures. Perhaps these failures (for start, stop, or delete) should all create the same audit log - we don't need a separate implementation for each.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #4724
Previously, all `workspace_build` audit logs showed 201 status codes - regardless of success or failure. This was because we were logging the initiation of the request - but not the outcome. 

We are now logging the outcome (and have stopped logging the initiation for now). If a build fails, the audit log will reflect that failure (status code `500`). If it is successful, the audit log will reflect that success (status code `200`).  The tradeoff is that there may be a delay in log generation as we have to wait for the build to finish. There are no diffs for `workspace_build` audit logs. I will add links to build logs in a fast follow to this PR so users can investigate failures.

Kapture 2022-11-21 at 12 07 42

### CODE REVIEW

File: coderd/audit.go [hunk 1]
```diff
@@ -189,6 +190,11 @@ func convertAuditLog(dblog database.GetAuditLogsOffsetRow) codersdk.AuditLog {
 	_ = json.Unmarshal(dblog.Diff, &diff)
 
 	var user *codersdk.User
+	var agent string
+
+	if dblog.UserAgent.Valid {
+		agent = dblog.UserAgent.String
+	}
```
Comment (coadler) [inline coderd/audit.go:197]: I don't think this should be necessary. You can access `dblog.UserAgent.String` safely without checking if it's valid, it'll just be an empty string, so both outcomes are essentially the same.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 2]
```diff
@@ -967,6 +1035,19 @@ func convertWorkspaceTransition(transition database.WorkspaceTransition) (sdkpro
 	}
 }
 
+func determineAuditAction(transition database.WorkspaceTransition) database.AuditAction {
```
Comment (coadler) [inline coderd/provisionerdserver/provisionerdserver.go:1038]: I think `auditActionFromTransition` would make this more clearer.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 3]
```diff
@@ -656,6 +696,34 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
+			}
+
+			audit.BuildAudit(ctx, &audit.BuildAuditParams[database.WorkspaceBuild]{
+				Audit:            *auditor,
+				Log:              server.Logger,
+				UserID:           job.InitiatorID,
+				JobID:            job.ID,
+				Action:           auditAction,
+				New:              workspaceBuild,
+				Status:           200,
```
Comment (coadler) [inline coderd/provisionerdserver/provisionerdserver.go:722]:
```suggestion
				Status:           http.StatusOK,
```

File: coderd/provisionerdserver/provisionerdserver.go [hunk 4]
```diff
@@ -656,6 +696,34 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
+
+			// We pass the workspace name to the Auditor so that it
+			// can form a friendly string for the user.
+			workspaceResourceInfo := map[string]string{
+				"workspaceName": workspace.Name,
+			}
+
+			wriBytes, err := json.Marshal(workspaceResourceInfo)
+			if err != nil {
+				server.Logger.Error(ctx, "could not marshal workspace name", slog.Error(err))
```
Comment (coadler) [inline coderd/provisionerdserver/provisionerdserver.go:712]:
```suggestion
				server.Logger.Error(ctx, "marshal resource info", slog.Error(err))
```

File: coderd/provisionerdserver/provisionerdserver.go [hunk 5]
```diff
@@ -656,6 +696,34 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
+			}
```
Comment (coadler) [inline coderd/provisionerdserver/provisionerdserver.go:713]: I would have an else here to set `wriBytes` to `[]byte("{}")`, otherwise auditing it could fail.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 6]
```diff
@@ -596,11 +635,12 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
 			return nil, xerrors.Errorf("get workspace build: %w", err)
 		}
 
+		workspace, getWorkspaceError := server.Database.GetWorkspaceByID(ctx, workspaceBuild.WorkspaceID)
```
Comment (coadler) [inline coderd/provisionerdserver/provisionerdserver.go:638]: I think this `GetWorkspaceByID` needs to stay in the transaction, otherwise it's unsafe to update it. You could make it assign to a variable outside of the function to access the info!

**Review by coadler — APPROVED** [review]

**Review by presleyp — APPROVED** [review]
Frontend ✅

File: coderd/provisionerdserver/provisionerdserver.go (hunk 5 above)
Comment (Kira-Pilot) [reply coderd/provisionerdserver/provisionerdserver.go:713]: @coadler does [this check](https://github.com/coder/coder/pull/5143/files#diff-cc84da01e587fa9b8971d66c92f68321bad61d76a161a36926ccfe6d57277048R191) in the audit function itself not cover that scenario?

Comment (coadler) [reply coderd/provisionerdserver/provisionerdserver.go:713]: Yeah it does! Didn't catch that
