### PR TITLE
fix: match term color

### LINKED ISSUE #3305: Web terminal is not matching the current site theme
Screen Shot 2022-07-29 at 16 00 30

I'm not sure how hard it is to make the theme match the current site colors, or if we could choose an existing one that is more "purple-ish" or "blue-ish".

### PR DESCRIPTION
**Pull request by f0ssel**
Fixes https://github.com/coder/coder/issues/3305 color mismatch
chrome_ZoOFRFc72Z

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 1]
```diff
@@ -75,9 +76,7 @@ const TerminalPage: FC<
       fontFamily: MONOSPACE_FONT_FAMILY,
       fontSize: 16,
       theme: {
-        // This is a slight off-black.
-        // It's really easy on the eyes!
-        background: "#1F1F1F",
+        background: colors.gray[16],
```
Comment (presleyp) [inline site/src/pages/TerminalPage/TerminalPage.tsx:79]: This is fine but `palette.background.default` is `gray[15]` so it might work as well. If the darker one looks better though, no problem.
