### PR TITLE
fix(agent): ensure SSH server shutdown with process groups

### LINKED ISSUE #17108: investigate why `run_on_stop` doesn't work consistently
while working on https://github.com/coder/coder/pull/16660, I was unable to get a shutdown script to ever run. that's bad!

we should figure out why agents aren't runnning shutdown scripts and fix it.

when we do, we should move the `make clean` of the aforementioned pr into a shutdown script.

### PR DESCRIPTION
**Pull request by mafredri**
After closer inspection of logs mentioned in #17108, it looks like the "connecting to coderd" loop was a red herring and the final log line from `(*agentssh.Server).Close` is missing.

PTY's already create a process group, so they seem to have been unaffected. But non-PTY SSH sessions were able to prevent SSH server close from completing when child processes were left running. For good measure, I added a timeout mechanism just so we don't ever block on SSH server shutdown longer than 10s.

This can be verified on current `main` by starting a workspace that has a shutdown script, and running the following command:

```
ssh coder.testa "/bin/bash -c 'trap \"sleep 6000\" SIGTERM; sleep 6000'"
```

The stopping the workspace. Shutdown scripts won't run. With this change, they do.

Fixes #17108

### CODE REVIEW

File: agent/agentssh/exec_other.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
+//go:build !windows
```
Comment (mafredri) [inline agent/agentssh/exec_other.go:1]: Review: These are copy-pasta from agentscripts package.

File: agent/agentssh/exec_windows.go [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+	"cdr.dev/slog"
+)
+
+func cmdSysProcAttr() *syscall.SysProcAttr {
+	return &syscall.SysProcAttr{}
+}
+
+func cmdCancel(ctx context.Context, logger slog.Logger, cmd *exec.Cmd) func() error {
+	return func() error {
+		logger.Debug(ctx, "cmdCancel: sending interrupt to process", slog.F("pid", cmd.Process.Pid))
```
Comment (johnstcn) [inline agent/agentssh/exec_windows.go:18]: 📋🍝 suggestion: check that `cmd.Process != nil` as it could have exited.

File: agent/agentssh/exec_other.go [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+func cmdSysProcAttr() *syscall.SysProcAttr {
+	return &syscall.SysProcAttr{
+		Setsid: true,
+	}
+}
+
+func cmdCancel(ctx context.Context, logger slog.Logger, cmd *exec.Cmd) func() error {
+	return func() error {
+		logger.Debug(ctx, "cmdCancel: sending SIGHUP to process and children", slog.F("pid", cmd.Process.Pid))
```
Comment (johnstcn) [inline agent/agentssh/exec_other.go:21]: 📋🍝 suggestion: check that `cmd.Process != nil` or capture the pid outside of the returned function.

File: agent/agentssh/agentssh.go [hunk 4]
```diff
@@ -1082,15 +1103,36 @@ func (s *Server) Close() error {
 	s.closing = nil
 	s.mu.Unlock()
 
+	s.logger.Debug(ctx, "closing server done")
+
 	return err
 }
 
-// Shutdown gracefully closes all active SSH connections and stops
+// Shutdown ~~gracefully~~ closes all active SSH connections and stops
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1111]:
```suggestion
// Shutdown forcefully closes all active SSH connections and stops
```

File: agent/agentssh/agentssh.go [hunk 5]
```diff
@@ -1054,24 +1070,29 @@ func (s *Server) Close() error {
 	}
 	s.closing = make(chan struct{})
 
+	s.logger.Debug(ctx, "closing server")
+
+	// Stop accepting new connections.
+	s.logger.Debug(ctx, "closing all active listeners")
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1076]: suggestion: log the number of active listeners

File: agent/agentssh/agentssh.go [hunk 6]
```diff
@@ -1054,24 +1070,29 @@ func (s *Server) Close() error {
...
+	for l := range s.listeners {
+		_ = l.Close()
+	}
+
 	// Close all active sessions to gracefully
 	// terminate client connections.
+	s.logger.Debug(ctx, "closing all active sessions")
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1083]: suggestion: log the number of active sessions

File: agent/agentssh/agentssh.go [hunk 7]
```diff
@@ -1054,24 +1070,29 @@ func (s *Server) Close() error {
...
 		// want to send an exit status to the client (via Exit()).
 		// Typically OpenSSH clients will return 255 as the exit status.
 		_ = ss.Close()
 	}
-
-	// Close all active listeners and connections.
-	for l := range s.listeners {
-		_ = l.Close()
-	}
+	s.logger.Debug(ctx, "closing all active connections")
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1090]: suggestion: log the number of active conns

File: agent/agent.go [hunk 8]
```diff
@@ -1773,15 +1773,20 @@ func (a *agent) Close() error {
 	a.setLifecycle(codersdk.WorkspaceAgentLifecycleShuttingDown)
 
 	// Attempt to gracefully shut down all active SSH connections and
-	// stop accepting new ones.
-	err := a.sshServer.Shutdown(a.hardCtx)
+	// stop accepting new ones. If all processes have not exited after
+	// 10 seconds, we just log it and move on as it's more important
+	// to run the shutdown scripts.
+	sshShutdownCtx, sshShutdownCancel := context.WithTimeout(a.hardCtx, 10*time.Second)
```
Comment (johnstcn) [inline agent/agent.go:1779]: I can foresee someone wanting to adjust this timeout. Maybe add a CLI option for it?

File: agent/agentssh/agentssh.go [hunk 9]
```diff
@@ -1044,6 +1055,11 @@ func (s *Server) trackSession(ss ssh.Session, add bool) (ok bool) {
 // Close the server and all active connections. Server can be re-used
 // after Close is done.
 func (s *Server) Close() error {
+	return s.close(context.Background())
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1058]: Do we need this extra method with the context argument? I don't see it used elsewhere.

File: agent/agentssh/agentssh.go [hunk 10]
```diff
@@ -1082,15 +1103,36 @@ func (s *Server) Close() error {
 	s.closing = nil
 	s.mu.Unlock()
 
+	s.logger.Debug(ctx, "closing server done")
```
Comment (johnstcn) [inline agent/agentssh/agentssh.go:1106]: suggestion: log elapsed time for closing

File: agent/agent.go (hunk 8 above)
Comment (mafredri) [reply agent/agent.go:1779]: I think that if we do get requests to make this configurable, it will help drive the implementation. I'm not certain this approach is the end-goal we want and I would like to avoid exposing functionality that may limit future implementations.

When we start solving #6175, changing this behavior may be relevant.

I'll go ahead and reduce this to 5 seconds as well as the default docker grace timeout is 10s I believe.

The original motivation behind closing SSH before running shutdown scripts is to ensure that commands doing work exit before potentially doing backups of state or something along those lines. I think giving those commands a grace of 5 seconds is plenty in most cases.

File: agent/agentssh/agentssh.go (hunk 9 above)
Comment (mafredri) [reply agent/agentssh/agentssh.go:1058]: Originally I intended to use `s.close` in `Shutdown` too, but I oopsied that change. I'll revert this though since ctx is only used for logger and we don't even utilize that feature often.

File: agent/agentssh/agentssh.go (hunk 4 above)
Comment (mafredri) [reply agent/agentssh/agentssh.go:1111]: I'd like to avoid manifesting the current implementation as the final intent. I can change the wording but I don't want to make it seem like Shutdown is supposed to be forceful.

Comment (johnstcn) [reply agent/agentssh/agentssh.go:1111]: Fair!

File: agent/agentssh/exec_other.go (hunk 3 above)
Comment (mafredri) [reply agent/agentssh/exec_other.go:21]: Checking nil isn't useful here as it's used in `cmd.Cancel = cmdCancel(...)` meaning this will only get triggered if a cmd is started. Capturing the pid outside also happens _before_ the cmd is started to `cmd.Process` will be nil at that point.

**Review by johnstcn — APPROVED** [review]
