### PR TITLE
fix: show error when creating a new group fails

### LINKED ISSUE #10928: creating group with same name as existing group does not return error
similar behavior to this issue: https://github.com/coder/coder/issues/10268

when clicking `Submit`, nothing occurs. the correct `409` is returned in the browser console, however, saying `Group with name "DataScience" already exists.`

### PR DESCRIPTION
**Pull request by aslilac**
Screenshot 2024-01-10 at 2 56 16 PM

Closes #10928

- show errors on new group page
- add a storybook case to prevent regression
- improve the errors reported from the backend

### CODE REVIEW

File: site/src/pages/GroupsPage/CreateGroupPageView.tsx [hunk 1]
```diff
@@ -36,15 +40,18 @@ export const CreateGroupPageView: FC<CreateGroupPageViewProps> = ({
...
-  const getFieldHelpers = getFormHelpers<CreateGroupRequest>(form, formErrors);
+  const getFieldHelpers = getFormHelpers<CreateGroupRequest>(form, error);
   const onCancel = () => navigate("/groups");
 
   return (
     <Margins>
       <FullPageForm title="Create group">
         <form onSubmit={form.handleSubmit}>
           <Stack spacing={2.5}>
+            {Boolean(error) && <ErrorAlert error={error} />}
```
Comment (BrunoQuaresma) [inline site/src/pages/GroupsPage/CreateGroupPageView.tsx:53]: I think showing an alert + inline field errors is too much 🤔

**Review by BrunoQuaresma — APPROVED** [review]
Just a minor comment
