### PR TITLE
fix(site): filter build timeline events by agent ID

### LINKED ISSUE #18002: bug: Workspace build timeline shows the same data for both agents in a multi-agent workspace
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Given a workspace with two resources (`docker_container`) and two agents, one for each resource. When viewing the workspace build timeline there are two issues:

1. Both agents are show in the build timeline
2. Both agents show the exact same data (connection time, script execution time, etc). This can't be correct since the second agent does not have a single script.

Image

### Expected Behavior

1. Build timeline should be filtered on the selected resource (left sidebar)
2. Agent specific connection and script timings should be shown

### Steps to Reproduce

1. Create a template with two agents and two `docker_container` resources, add one script to one agent to separate them from each other
2. Create workspace
3. Observe build timeline

### Environment

- Coder version: v2.22.0-devel+361ac82f1

### Additional Context

The issue occurs consistently

### PR DESCRIPTION
**Pull request by mafredri**
When a workspace has multiple agents (e.g., main + devcontainer), the
build timeline was showing all events duplicated under each agent
instead of filtering by the agent they belong to.

Added agentId to the Stage type and filter timings by workspace_agent_id
so each agent section only shows its own events.

Fixes #18002

---

_Generated with [`mux`](https://github.com/coder/mux) • Model: `anthropic:claude-opus-4-5` • Cost: ~`$11.48`~ `$21.48`_

### CODE REVIEW

File: site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx [hunk 1]
```diff
@@ -52,21 +52,6 @@ export const WorkspaceTimings: FC<WorkspaceTimingsProps> = ({
...
-	const uniqScriptTimings = uniqBy(
-		sortBy(agentScriptTimings, (t) => new Date(t.started_at).getTime() * -1),
-		(t) => t.display_name,
-	);
-	const timings = [
-		...provisionerTimings,
-		...uniqScriptTimings,
-		...agentConnectionTimings,
-	].sort((a, b) => {
-		return new Date(a.started_at).getTime() - new Date(b.started_at).getTime();
```
Comment (mafredri) [inline site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx:67]: Review: The `mergeTimeRanges` function already does this.

File: site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx [hunk 2]
```diff
@@ -196,8 +198,12 @@ export const WorkspaceTimings: FC<WorkspaceTimingsProps> = ({
 
 								{view.stage.name === "start" && (
 									<ScriptsChart
-										timings={agentScriptTimings
-											.filter((t) => t.stage === view.stage.name)
+										timings={uniqScriptTimings
```
Comment (mafredri) [inline site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx:204]: Review: This seemed like a bug? We discard duplicates in the top view, but not in the detailed view.

File: site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx [hunk 3]
```diff
@@ -79,21 +64,37 @@ export const WorkspaceTimings: FC<WorkspaceTimingsProps> = ({
...
-	const agentStageLabels = Array.from(
-		new Set(
-			agentConnectionTimings.map((t) => `agent (${t.workspace_agent_name})`),
+	// This is a workaround to deal with the BE returning multiple timings for a
+	// single agent script when it should return only one. Reference:
+	// https://github.com/coder/coder/issues/15413#issuecomment-2493663571
+	const uniqScriptTimings = sortBy(
+		uniqBy(
+			sortBy(agentScriptTimings, (t) => new Date(t.started_at).getTime() * -1),
+			(t) => `${t.workspace_agent_id}:${t.display_name}`,
```
Comment (mafredri) [inline site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx:73]: Review: Moved this closer to where it's used. Previously this could filter out another agents script that has the same display name, so the uniqueness condition was changed. Also note that sort condition was changed from Date (which loses precision) to the ISO 8601 timestamp string as they sort correctly lexicographically.

However, since the existing `DuplicatedScriptTiming` test was added with limited understanding of the problem, it's unclear whether this unique filtering is even needed anymore.

Note: Since we now use this below, we reverse the sort.

File: site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx [hunk 4]
```diff
@@ -270,6 +279,6 @@ const styles = {
 		borderTop: `1px solid ${theme.palette.divider}`,
 		display: "flex",
 		flexDirection: "column",
-		height: 420,
+		height: "var(--collapse-body-height, 420px)",
```
Comment (DanielleMaywood) [inline site/src/modules/workspaces/WorkspaceTiming/WorkspaceTimings.tsx]: nit(non-blocking): would be nice to upgrade these styles to tailwind as they're being touched but not going to block on this

**Review by DanielleMaywood — APPROVED** [review]

**Review by DanielleMaywood — CHANGES_REQUESTED** [review]
Looks like tailwind-ifying has added some extra height on the agent timeline component

Image

**Comment by mafredri** [comment]
@DanielleMaywood unless we accept the changed header size, I'm thinking we'll revert the Tailwind changes. Not sure how it should be fixed/changed.

**Comment by mafredri** [comment]
FWIW, I attempted to Tailwindify, but reproducing the original got too complex so I'm cutting it as I don't have more time to work on this.

**Review by DanielleMaywood — APPROVED** [review]
