### PR TITLE
fix: Improve `coder server` shutdown procedure

### LINKED ISSUE #3245: Refactor `coder server` shutdown procedure and allow `TestServer` tests to pass `goleaks` detection
Currently there are multiple ways in which the Coder server can exit and not all of them go through the same shutdown procedure. There are also cases where an error in one of the steps results skipping some of the shutdown steps.

There are also certain services started where context propagation is not guaranteed to trigger, depending on which error shut down the server.

We should standardize the server shutdown procedure and ensure that all `TestServer` cases pass `goleaks`.

### PR DESCRIPTION
**Pull request by mafredri**
This commit improves the `coder server` shutdown procedure so that all
triggers for shutdown do so in a graceful way without skipping any
steps.

We also improve cancellation and shutdown of services by ensuring
resources are cleaned up at the end.

Notable changes:
- We wrap `cmd.Context()` to allow us to control cancellation better
- We attempt graceful shutdown of the http server (`server.Shutdown`)
  because it's less abrupt (compared to `shutdownConns`)
- All exit paths share the same shutdown procedure (except for early
  exit)
- `provisionerd`s are now shutdown concurrently instead of one at a
  time, the also now get a new context for shutdown because
  `cmd.Context()` may be cancelled
- Resources created by `newProvisionerDaemon` are cleaned up
- Lifecycle `Executor` exits its goroutine on context cancellation

Fixes #3245

Combined with https://github.com/hashicorp/hc-install/pull/68, this PR
allows `goleaks` test to pass for `cli` `TestServer` tests.

### CODE REVIEW

File: cli/server.go [hunk 1]
```diff
@@ -111,26 +112,34 @@ func server() *cobra.Command {
...
 
+			// Main command context for managing cancellation
+			// of running services.
+			ctx, cancel := context.WithCancel(cmd.Context())
+			defer cancel()
+
+			// Clean up idle connections at the end, e.g.
+			// embedded-postgres can leave an idle connection
+			// which is caught by goleaks.
+			defer http.DefaultClient.CloseIdleConnections()
```
Comment (johnstcn) [inline cli/server.go:123]: 👀 TIL!

File: cli/server.go [hunk 2]
```diff
@@ -189,25 +200,25 @@ func server() *cobra.Command {
 			}
 
 			var (
-				ctxTunnel, closeTunnel = context.WithCancel(cmd.Context())
-				devTunnel              = (*devtunnel.Tunnel)(nil)
-				devTunnelErrChan       = make(<-chan error, 1)
+				ctxTunnel, closeTunnel = context.WithCancel(ctx)
+				devTunnel              *devtunnel.Tunnel
+				devTunnelErr           <-chan error
```
Comment (johnstcn) [inline cli/server.go:205]: Why are we moving to an un-buffered channel here?

Comment (mafredri) [reply cli/server.go:205]: This is just so that the channel is accessible outside the `if`, the actual channel is returned by `devtunnel.New()`.

I thought it was weird that we're allocating a channel here since the `nil` channel blocks forever which is ideal, and informs the reader of our intent.

**Review by johnstcn — APPROVED** [review]

File: cli/server.go [hunk 3]
```diff
@@ -425,75 +453,117 @@ func server() *cobra.Command {
...
 			options.Telemetry.Close()
-			cmd.Println("Waiting for WebSocket connections to close...")
-			shutdownConns()
-			coderAPI.Close()
-			return nil
+
+			// Trigger context cancellation for any remaining services.
+			cancel()
+
+			return exitErr
```
Comment (mafredri) [inline cli/server.go:566]: We'll always be returning an error now. There's really no way to cleanly shut down the server (e.g. click shut down in WebUI), so this makes sense. And interrupt for instance usually returns non-zero exit code.

The only downside is that we will print `context cancelled` and `see --help` at the end. I kind of want us to have a cobra post-exec for cli that does `os.Exit(n)` is the context is cancelled. Thoughts?

**Review by kylecarbs — APPROVED** [review]
I did a brief review, but on mobile so hard to confirm! Changes look good to me.
