### PR TITLE
fix: disallow deselecting dynamic dropdown value

### LINKED ISSUE #22102: bug: do not allow de-selecting options in parameter dropdown
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am using dynamic parameters. If using a dropdown input type, it is possible to un-select a value such that there is no selection.

The UI then gives a message targeted at template maintainers which will surely be confusing to template users:

> Value must be a valid option. The value is empty, did you forget to set it with a default or from user input?

Uhm, actually, yes I did set a default. Thanks for asking!

https://github.com/user-attachments/assets/5530eca0-8b4c-441a-8291-c5008d02b1e7

### Relevant Log Output

```shell

```

### Expected Behavior

Same as radio buttons - it should be impossible to get into this state.

Barring that - don't show a message intended for template maintainers.

### Steps to Reproduce

Use `form_type    = "dropdown"`, go to UI, click on the selected option (which de-selects it).

### Environment

- Coder version: 2.28.8

### Additional Context

The issue occurs consistently

### PR DESCRIPTION
**Pull request by code-asher**
This was accomplished by switching from the comboxbox (which has deselection logic) to a select (which does not).

As a side effect, the dropdowns are wider now, which seems to match better with other inputs anyway.  And, it seems it uses the `combobox` role instead of `button` which also seems to make more sense anyway?  (Also, funny that the thing called combox is not using combobox.)  Lastly, they lose some bolding.

Closes #22102

### CODE REVIEW

File: site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx [hunk 1]
```diff
@@ -335,41 +334,25 @@ const ParameterField: FC<ParameterFieldProps> = ({
...
-				(opt) => opt.value.value === value,
-			);
 			return (
-				<Combobox
+				<Select
 					value={value}
 					onValueChange={(newValue) => onChange(newValue ?? "")}
+					disabled={disabled}
 				>
-					<ComboboxTrigger asChild>
```
Comment (code-asher) [inline site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx:346]: The only thing I am not sure about is that the issue shows a dropdown with a search.  As far as I can see, we currently do not have a search on dynamic dropdown parameters (which is why I opted to just use `Select`). 

Was the removal of search an unintentional change?  If so, might need to switch back to combobox for the search and just make the deselection behavior configurable instead.

Comment (aslilac) [reply site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx:346]: hmm, yeah do any of the stories show a search field? if not then this seems fine

**Review by aslilac — APPROVED** [review]

File: site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx (hunk 1 above)
Comment (code-asher) [reply site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx:346]: Nope, none of the stories currently show a search field, so this change has parity with the status quo at least.
