### PR TITLE
fix: strip CORS headers from applications

### LINKED ISSUE #8010: Handle case where application sends conflicting CORS headers
It seems if an application sends its own headers they actually get appended (I mistakenly thought they would get overwritten but I think this was confusion from back when I was testing a different method of setting the headers rather than using the middleware).

This is an issue with the allowed origin header because although from what I can tell this is technically valid most browsers refuse to work when you set this header multiple times even if they have the same value.

We can either strip the headers from the application or remove ours in favor of the application's but since applications cannot handle OPTIONS anyway to be consistent I think we should prefer ours.  This was actually the original plan anyway but I (foolishly) abandoned it because we were using the middleware.  Hopefully there is a way to do this and still use the middleware though.

We will also need to update the documentation.

### PR DESCRIPTION
**Pull request by code-asher**
This is a followup to https://github.com/coder/coder/pull/7688

The problem is that if applications send their own CORS headers the headers get doubled up (not overwritten) and browsers do not like multiple values for the allowed origin even though it appears the spec allows for it.

We could prefer the application's headers instead of ours but since we control OPTIONS I think preferring ours will by the more consistent experience across the board and also aligns with the original RFC.

Closes https://github.com/coder/coder/issues/8010.

### CODE REVIEW

File: coderd/workspaceapps/apptest/apptest.go [hunk 1]
```diff
@@ -1260,4 +1260,61 @@ func Run(t *testing.T, appHostIsPrimary bool, factory DeploymentFactory) {
...
+		var deduped []string
+		var addedOrigin bool
+		for _, value := range resp.Header.Values("Vary") {
+			if value != "Origin" || !addedOrigin {
+				if value == "Origin" {
+					addedOrigin = true
+				}
+				deduped = append(deduped, value)
+			}
+		}
```
Comment (code-asher) [inline coderd/workspaceapps/apptest/apptest.go:1316]: I must be going mad, I have no idea how the response headers could change in perfect opposition to what I pass into the `require.Equal` for the expected value.

Examples of it swapping:
https://github.com/coder/coder/actions/runs/5284785388/jobs/9562577501
https://github.com/coder/coder/actions/runs/5284691553/jobs/9562383538

And all I did was add `"Origin", ` to the check.

**Review by bpmct — COMMENTED** [review]
Do we need to change this section in our docs? 

> Applications can set their own headers which will override the defaults but this will only apply to non-preflight requests. Preflight requests through the dashboard are never sent to applications and thus cannot be modified by them. Read more about the difference between simple requests and requests that trigger preflights [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).

**Comment by code-asher** [comment]
> Do we need to change this section in our docs?
> 
> > Applications can set their own headers which will override the defaults but this will only apply to non-preflight requests. Preflight requests through the dashboard are never sent to applications and thus cannot be modified by them. Read more about the difference between simple requests and requests that trigger preflights [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).

Yup, this PR also makes changes to this section.  Let me know if you have any thoughts on the wording!  https://github.com/coder/coder/pull/8057/files#diff-fee7817d909d710ad6c6a59e4a5fc65ea0b7608949e74c45e3465b1f51e5cc99R127-R132

**Review by Emyrk — APPROVED** [review]
LGTM :+1:

File: coderd/workspaceapps/apptest/apptest.go (hunk 1 above)
Comment (code-asher) [reply coderd/workspaceapps/apptest/apptest.go:1316]: Oddly it was two `Origin` strings, same capitalization.  It seems so bizarre that the headers returned could change based on how I change completely unrelated code, so bizarre that I feel I must be doing something dunderheaded.

File: coderd/workspaceapps/proxy.go [hunk 2]
```diff
@@ -541,6 +542,26 @@ func (s *Server) proxyWorkspaceApp(rw http.ResponseWriter, r *http.Request, appT
...
+		forbiddenVary := []string{
+			httpmw.OriginHeader,
+			httpmw.AccessControlRequestMethodsHeader,
+			httpmw.AccessControlRequestHeadersHeader,
+		}
+		for _, value := range varies {
+			if !slice.ContainsCompare(forbiddenVary, value, strings.EqualFold) {
+				r.Header.Add(httpmw.VaryHeader, value)
+			}
+		}
```
[the remark this answers is not in the document]
Comment (code-asher) [reply coderd/workspaceapps/proxy.go:561]: I figure an application might `Vary` based on headers other than CORS-related headers, so I am adding back the ones that are not related to CORS.  So if you have `Vary: Access-Control-Request-Methods` and `Vary: X-Foobar` the former gets removed while the latter gets axed.

**Comment by bpmct** [comment]
> > Do we need to change this section in our docs?
> > > Applications can set their own headers which will override the defaults but this will only apply to non-preflight requests. Preflight requests through the dashboard are never sent to applications and thus cannot be modified by them. Read more about the difference between simple requests and requests that trigger preflights [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).
> 
> Yup, this PR also makes changes to this section. Let me know if you have any thoughts on the wording! https://github.com/coder/coder/pull/8057/files#diff-fee7817d909d710ad6c6a59e4a5fc65ea0b7608949e74c45e3465b1f51e5cc99R127-R132

Somehow I totally missed the docs changes when I initially reviewed. All LGTM.
