### PR TITLE
fix(coderd): use stable sorting for insights and improve test coverage

### LINKED ISSUE #9213: Improve tests for template insights
As a follow-up to #9138, we want to improve test coverage of template insights. This means we'll also need manually generate/insert agent statistics which are a basis for some of the data.

Test cases should include:

- Multiple templates
- Multiple users
- 1-2 apps in 1-2 templates
- Controlled app usage data, e.g. user X used template Y / app Z between V and W
- Controlled agent usage data (agent stats)

What to test:

- Template ID filtering conditions (none, 1, 2, etc.)
- Requests in different timezones
- Resulting numbers must match what's expected from crafted input data

### PR DESCRIPTION
**Pull request by mafredri**
This PR introduces a new test suite for insights and makes it easy to add new test scenarios which can then be compared against golden file changes.

A few bugfixes found by the test suite are included as well.

Fixes #9213

### CODE REVIEW

**Comment by mafredri** [comment]
I think this ready now, I might add some more test further down the line but I'd like to start with optimizations next.

File: coderd/insights_test.go [hunk 1]
```diff
@@ -570,6 +580,810 @@ func TestTemplateInsights(t *testing.T) {
...
+				appUsage: []appUsage{
+					// TODO(mafredri): This doesn't behave correctly right now
+					// and will add more usage to the app. This could be
+					// considered both correct and incorrect behavior.
+					// { // One hour of usage, but same user and same template app, only count once.
+					// 	app:       users[0].workspaces[1].apps[0],
+					// 	startedAt: frozenWeekAgo,
+					// 	endedAt:   frozenWeekAgo.Add(time.Hour),
+					// 	requests:  1,
+					// },
```
Comment (mafredri) [inline coderd/insights_test.go:1135]: This is something I will fix later on, I wanted to keep query logic changes minimal for now.

Essentially this boils down to:
- User A has two workspaces in template X
- User A opens code-server in both workspaces
- User A closes both code-servers ater an hour
- We should only show 1h of code-server usage in template X

Currently we show two hours. Motivation for this is that a user can't effectively use multiple code-servers simultaneously. Imagine if this was 10 workspaces, the user would have to have very many skill points in parallel thinking and perhaps get a few extra keyboards and grow some extra limbs to produce 10h of usage. 😄

File: coderd/insights_test.go [hunk 2]
```diff
@@ -570,6 +580,810 @@ func TestTemplateInsights(t *testing.T) {
...
+							require.NoError(t, err, "want no error getting workspace")
+
+							workspace.agentID = ws.LatestBuild.Resources[0].Agents[0].ID
+						})
+					})
+				}
+			}
+
+			// Create the template version and template.
+			version := coderdtest.CreateTemplateVersion(t, client, firstUser.OrganizationID, &echo.Responses{
```
Comment (mtojek) [inline coderd/insights_test.go:829]: nit: maybe we should depend on `dbgen` as much as possible to shorten the test execution and prevent potential flakes

File: coderd/insights_test.go [hunk 3]
```diff
@@ -570,6 +580,810 @@ func TestTemplateInsights(t *testing.T) {
...
+				},
+			},
+		}
+	}
+	type testRequest struct {
+		name        string
+		makeRequest func([]*testTemplate) codersdk.TemplateInsightsRequest
+		ignoreTimes bool
+	}
+	tests := []struct {
```
Comment (mtojek) [inline coderd/insights_test.go:1203]: Do you think that we can convert-to-table/remove some other insights tests?

**Review by mtojek — APPROVED** [review]
Better test coverage is always welcome!

**Review by johnstcn — APPROVED** [review]

File: coderd/database/dbfake/dbfake.go [hunk 4]
```diff
@@ -2480,6 +2489,8 @@ func (q *FakeQuerier) GetTemplateParameterInsights(ctx context.Context, arg data
 		}
 	}
 
+	// NOTE(mafredri): Add sorting if we decide on how to handle PostgreSQL collations.
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/database/dbfake/dbfake.go:2492]: It will depend on the systems locale. Essentially if e.g. if `LC_ALL=C` or `LC_ALL=en_US.UTF-8` is set when calling `initdb`, it will produce different results.

File: coderd/insights.go [hunk 5]
```diff
@@ -377,6 +380,32 @@ func convertTemplateInsightsApps(usage database.GetTemplateInsightsRow, appUsage
 		},
 	}
 
+	// Use a stable sort, similarly to how we would sort in the query, note that
+	// we don't sort in the query because order varies depending on the table
+	// collation.
+	//
+	// ORDER BY access_method, slug_or_port, display_name, icon, is_app
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/insights.go:387]: For a stable sort it's preferred to sort all columns, otherwise data could flip-flop.

File: coderd/testdata/insights/parameters_two_days_ago,_no_data.json.golden [hunk 6]
```diff
@@ -0,0 +1,44 @@
+{
+  "report": {
+    "start_time": "0001-01-01T00:00:00Z",
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/testdata/insights/parameters_two_days_ago,_no_data.json.golden:3]: This is only for the test and to ensure the golden file isn't updated every day.

File: coderd/insights_test.go (hunk 2 above)
Comment (mafredri) [reply coderd/insights_test.go:829]: I evaluated doing that, but we didn't have any methods for generating template/workspace build parameters. Perhaps it could be a future improvement?

File: coderd/insights_test.go (hunk 3 above)
Comment (mafredri) [reply coderd/insights_test.go:1203]: I think we can delete at least one or two. But depending on if we rely primarily on dbgen here or not, we might want to keep some "whole tests" around.

File: coderd/testdata/insights/parameters_two_days_ago,_no_data.json.golden (hunk 6 above)
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/testdata/insights/parameters_two_days_ago,_no_data.json.golden:3]: Yes, I was rather thinking about the case when somebody forgets to set this field, and a unit test could potentially catch it.

File: coderd/insights_test.go (hunk 2 above)
Comment (mtojek) [reply coderd/insights_test.go:829]: 👍

File: coderd/insights_test.go [hunk 7]
```diff
@@ -570,6 +580,810 @@ func TestTemplateInsights(t *testing.T) {
...
+						},
+					},
+					{
+						name:     "workspace2",
+						template: templates[1],
+						buildParameters: []buildParameter{
+							{templateParameter: templates[0].parameters[0], value: "ABC"},
+							{templateParameter: templates[0].parameters[1], value: "123"},
+							{templateParameter: templates[0].parameters[2], value: "BBB"},
+							{templateParameter: templates[0].parameters[3], value: "option2"},
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/insights_test.go:1025]: Never mind, I see now that the wrong template parameter is being referenced here.

[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/insights_test.go:1025]: defuse now :D

File: coderd/insights_test.go (hunk 3 above)
Comment (mafredri) [reply coderd/insights_test.go:892]: I deleted one test `TestTemplateInsights`, its test cases are now covered by the golden files and then some.
