### PR TITLE
fix: use flag to enable Prometheus

### LINKED ISSUE #10601: expose Prometheus metrics for external provisioners/proxies
right now, we expose Prometheus metrics on the `2112` port of the Coder server. we should extend this support to external provisioners and workspace proxies, as such metrics include data relevant to both workspace builds and API requests.

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/10601

This PR adds an extra flag to disable Prometheus endpoint by default (bug). Additionally, I added some docs mentioning Prometheus configuration for provisionerd and wsproxy.

### CODE REVIEW

File: cli/clitest/clitest.go [hunk 1]
```diff
@@ -155,6 +159,13 @@ func Start(t *testing.T, inv *clibase.Invocation) {
 	go func() {
 		defer close(closeCh)
 		err := waiter.Wait()
+
+		if errExpected {
+			assert.Error(t, err)
+			assert.False(t, errors.Is(err, context.Canceled), "error was expected, but context was canceled")
+			return
+		}
```
Comment (johnstcn) [inline cli/clitest/clitest.go:167]: From the function signature, I'd expect this to take a func() that lets you pass in any assertions you want?

Not a blocker, but would make this very flexible and useful.

**Review by johnstcn — APPROVED** [review]

File: cli/clitest/clitest.go (hunk 1 above)
Comment (mtojek) [reply cli/clitest/clitest.go:167]: Something like `assertCallback func(t)`?

Comment (johnstcn) [reply cli/clitest/clitest.go:167]: Yeah something like that!
