### PR TITLE
fix(coderd): humanize duration on notifications

### LINKED ISSUE #14325: Humanize the duration time in the dormant notification email
image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Close #14325 

I added tests for the Humanize function, but we might want to consider adding snapshot tests for the notifications in the near future.

Since these tests would require a database (as the templates are stored there), it can be challenging to update the golden files locally with our current test setup. I’m wondering if we should start considering the use of an embedded database for some tests. 🤔

### CODE REVIEW

File: coderd/util/time/duration.go [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+	"fmt"
+	"time"
+)
+
+type Unit struct {
+	value int
+	unit  string
+}
+
+func Humanize(d time.Duration) string {
```
Comment (dannykopping) [inline coderd/util/time/duration.go:13]: Did you consider using https://pkg.go.dev/github.com/dustin/go-humanize#RelTime? We already use this library.

Comment (BrunoQuaresma) [reply coderd/util/time/duration.go:13]: Yes, but I was unsure if we wanted to have this humanized like this much or wanted something more descriptive like "X days, Y hours, and W minutes" or "around X days". Since it is a time operation I think the first could be best but I like both options honestly. What do you think?

Comment (dannykopping) [reply coderd/util/time/duration.go:13]: Instead of answering you directly, let me answer with another question:
As a user, do you care that your workspace is going to be deleted in "23 hours 59 minutes and 42 seconds" or "around 1 day"? Is the precision of the former case useful in some way?

Comment (BrunoQuaresma) [reply coderd/util/time/duration.go:13]: Good question, not really 😓 . Going to fix that.

File: coderd/util/time/duration.go [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+import (
+	"time"
+
+	"github.com/dustin/go-humanize"
+)
+
+func Humanize(d time.Duration) string {
+	endTime := time.Now().Add(d)
+	return humanize.Time(endTime)
```
Comment (dannykopping) [inline coderd/util/time/duration.go:11]: Given this is only used in two places, I'm not convinced we need any indirection in front of `humanize.Time`; we should just use it directly.

If we were using this very broadly, I could see some value is hiding this behind our own interface so we could swap out the underlying implementation, but I don't think we're there yet.

**Review by dannykopping — COMMENTED** [review]
Almost there, please address CI issues.

File: coderd/util/time/duration.go (hunk 2 above)
Comment (kylecarbs) [reply coderd/util/time/duration.go:11]: Happy you noticed this to reduce abstraction!

Comment (BrunoQuaresma) [reply coderd/util/time/duration.go:11]: 100%, I was just too lazy to remove the first abstraction I added. My bad 🙏

File: coderd/autobuild/lifecycle_executor.go [hunk 3]
```diff
@@ -323,14 +324,15 @@ func (e *Executor) runOnce(t time.Time) Stats {
 					}
 				}
 				if shouldNotifyDormancy {
+					dormantTime := time.Now().Add(time.Duration(tmpl.TimeTilDormant))
```
Comment (dannykopping) [inline coderd/autobuild/lifecycle_executor.go:327]: One thing to check: is the dormancy value in the database in UTC? If so, the timezone of the control plane might make things weird and we may want to add a `.UTC()` call in here too or use `dbtime.Now()`

File: coderd/notifications/notifications_test.go [hunk 4]
```diff
@@ -691,7 +691,7 @@ func TestNotificationTemplatesCanRender(t *testing.T) {
 					"reason":         "breached the template's threshold for inactivity",
 					"initiator":      "autobuild",
 					"dormancyHours":  "24",
-					"timeTilDormant": "24h",
+					"timeTilDormant": "24 hours",
```
Comment (dannykopping) [inline coderd/notifications/notifications_test.go:694]: A test which includes not such a round number would also be helpful for illustrative purposes.

**Review by dannykopping — APPROVED** [review]
Couple minor thoughts but LGTM!

File: coderd/autobuild/lifecycle_executor.go (hunk 3 above)
Comment (BrunoQuaresma) [reply coderd/autobuild/lifecycle_executor.go:327]: Good to know

File: coderd/notifications/notifications_test.go (hunk 4 above)
Comment (BrunoQuaresma) [reply coderd/notifications/notifications_test.go:694]: Added
