### PR TITLE
fix: refactor agent resource monitoring API to avoid excessive calls to DB

### LINKED ISSUE #728: bug: GetWorkspaceByAgentID is called over a million times a day on dogfood
https://console.cloud.google.com/sql/instances/dogfood-v2/insights;database=coder;start=2025-06-12T05:55:18.232Z;end=2025-06-19T05:55:18.232Z;trace=ac9bc1c4b501d64bb6ad790ae5a8633a;span=c6909b51da0c6db3;query_hash=3814061901782322789;sort_by=TOTAL_EXEC_TIME?inv=1&invt=Ab0giQ&project=coder-dogfood-v2

### PR DESCRIPTION
**Pull request by cstyan**
This should resolve https://github.com/coder/internal/issues/728 by refactoring the ResourceMonitorAPI struct to only require querying the resource monitor once for memory and once for volumes, then using the stored monitors on the API struct from that point on. This should eliminate the vast majority of calls to `GetWorkspaceByAgentID` and `FetchVolumesResourceMonitorsUpdatedAfter`/`FetchMemoryResourceMonitorsUpdatedAfter` (millions of calls per week).

Tests passed, and I ran an instance of coder via a workspace with a template that added resource monitoring every 10s. Note that this is the default docker container, so there are other sources of `GetWorkspaceByAgentID` db queries. Note that this workspace was running for ~15 minutes at the time I gathered this data.

Over 30s for the `ResourceMonitor` calls:
```
coder@callum-coder-2:~/coder$ curl localhost:19090/metrics | grep ResourceMonitor | grep count
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0coderd_db_query_latencies_seconds_count{query="FetchMemoryResourceMonitorsByAgentID"} 2
coderd_db_query_latencies_seconds_count{query="FetchMemoryResourceMonitorsUpdatedAfter"} 2
100  288k    0  288k    0     0  58.3M      0 --:--:-- --:--:-- --:--:-- 70.4M
coderd_db_query_latencies_seconds_count{query="FetchVolumesResourceMonitorsByAgentID"} 2
coderd_db_query_latencies_seconds_count{query="FetchVolumesResourceMonitorsUpdatedAfter"} 2
coderd_db_query_latencies_seconds_count{query="UpdateMemoryResourceMonitor"} 155
coderd_db_query_latencies_seconds_count{query="UpdateVolumeResourceMonitor"} 155
coder@callum-coder-2:~/coder$ curl localhost:19090/metrics | grep ResourceMonitor | grep count
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0coderd_db_query_latencies_seconds_count{query="FetchMemoryResourceMonitorsByAgentID"} 2
coderd_db_query_latencies_seconds_count{query="FetchMemoryResourceMonitorsUpdatedAfter"} 2
100  288k    0  288k    0     0  34.7M      0 --:--:-- --:--:-- --:--:-- 40.2M
coderd_db_query_latencies_seconds_count{query="FetchVolumesResourceMonitorsByAgentID"} 2
coderd_db_query_latencies_seconds_count{query="FetchVolumesResourceMonitorsUpdatedAfter"} 2
coderd_db_query_latencies_seconds_count{query="UpdateMemoryResourceMonitor"} 158
coderd_db_query_latencies_seconds_count{query="UpdateVolumeResourceMonitor"} 158
```

And over 1m for the `GetWorkspaceAgentByID` calls, the majority are from the workspace metadata stats updates:
```
coder@callum-coder-2:~/coder$ curl localhost:19090/metrics | grep GetWorkspaceByAgentID | grep count
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  284k    0  284k    0     0  42.4M      0 --:--:-- --:--:-- --:--:-- 46.3M
coderd_db_query_latencies_seconds_count{query="GetWorkspaceByAgentID"} 876
coder@callum-coder-2:~/coder$ curl localhost:19090/metrics | grep GetWorkspaceByAgentID | grep count
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  284k    0  284k    0     0  75.4M      0 --:--:-- --:--:-- --:--:-- 92.7M
coderd_db_query_latencies_seconds_count{query="GetWorkspaceByAgentID"} 918
```

### CODE REVIEW

File: coderd/agentapi/resources_monitoring.go [hunk 1]
```diff
@@ -33,42 +34,81 @@ type ResourcesMonitoringAPI struct {
...
+	var volumeErr error
+	a.volOnce.Do(func() {
+		volumeErr = a.fetchVolumeMonitors(ctx)
+	})
+	if volumeErr != nil {
+		return nil, volumeErr
 	}
 
+	a.monitorsLock.RLock()
+	defer a.monitorsLock.RUnlock()
```
Comment (spikecurtis) [inline coderd/agentapi/resources_monitoring.go]: I think we could simplify this locking by just moving it to `PushResourcesMonitoringUsage` and enforcing that calls to this function are not concurrent. It's meant to be sequential, and that's how the agent uses it.

File: coderd/agentapi/resources_monitoring.go [hunk 2]
```diff
@@ -33,42 +34,81 @@ type ResourcesMonitoringAPI struct {
...
-		return nil, xerrors.Errorf("failed to fetch memory resource monitor: %w", memoryErr)
+// fetchMemoryMonitor fetches the memory monitor from the database and caches it.
+// Returns an error if the fetch fails (except for sql.ErrNoRows which is expected).
+func (a *ResourcesMonitoringAPI) fetchMemoryMonitor(ctx context.Context) error {
+	memMon, err := a.Database.FetchMemoryResourceMonitorsByAgentID(ctx, a.AgentID)
+	if err != nil && !errors.Is(err, sql.ErrNoRows) {
+		return xerrors.Errorf("fetch memory resource monitor: %w", err)
+	}
+	if err == nil {
+		a.memoryMonitor = &memMon
```
Comment (spikecurtis) [inline coderd/agentapi/resources_monitoring.go]: why is this field a pointer if the fetch doesn't return a pointer? Seems ok as a value which can save allocation and GC.

File: coderd/agentapi/resources_monitoring.go [hunk 3]
```diff
@@ -33,42 +34,81 @@ type ResourcesMonitoringAPI struct {
...
+	}
+	a.volumeMonitors = volMons
+	return nil
+}
+
+func (a *ResourcesMonitoringAPI) GetResourcesMonitoringConfiguration(ctx context.Context, _ *proto.GetResourcesMonitoringConfigurationRequest) (*proto.GetResourcesMonitoringConfigurationResponse, error) {
+	// Load memory monitor once
+	var memoryErr error
+	a.memOnce.Do(func() {
+		memoryErr = a.fetchMemoryMonitor(ctx)
```
Comment (spikecurtis) [inline coderd/agentapi/resources_monitoring.go]: This doesn't really work, because you're passing a closure to `Do()` that includes the `memErr`, which is a local variable in this function. So, only the first call to this once can possibly capture the error. Every subsequent call will get `memErr` unchanged, even if there was an error.

What needs to happen here depends on the error handling strategy.

One option would be to fetch the initial value of these monitors at the time the `*ResourceMonitoringAPI` itself is instantiated (that is, when the agent connects to the RPC service). If we fail to fetch the monitors, we error out the connection and assume the agent will reconnect. That's simple, and probably OK, given that we expect DB errors to be rare.

It has the nominal drawback that it tears the whole connection down, when the agent could just retry the RPCs for resource monitoring, but at present the agent doesn't do that. If anything fails on the agentapi, it tends to just tear everything down and start again. So, being more sophisticated like hitting the db when we get RPC calls, and allowing retries for errors would be an improvement that our only client doesn't take advantage of.

File: coderd/agentapi/resources_monitoring.go (hunk 2 above)
Comment (cstyan) [reply coderd/agentapi/resources_monitoring.go]: I was using the `nil` check as a way to check for existence/proper instantiation, but we can alternatively use `CreatedAt.IsZero` to check.

File: coderd/agentapi/resources_monitoring.go (hunk 3 above)
Comment (cstyan) [reply coderd/agentapi/resources_monitoring.go]: Yep, that's just a miss on my part during some refactoring of the sync `Do` functions. I was trying to avoid the refactor that would be required to return an error and have the client retry properly while also not exiting completely for a transient failure. With your added context though it sounds like we're fine with the teardown/early exit as it's what we're already doing everywhere else for similar paths in the agent code. 

We can explore the refactor later if we decide it would be useful 👍

File: coderd/agentapi/resources_monitoring.go [hunk 4]
```diff
@@ -33,42 +34,60 @@ type ResourcesMonitoringAPI struct {
...
-		return nil, xerrors.Errorf("failed to fetch volume resource monitors: %w", err)
+		return xerrors.Errorf("fetch volume resource monitors: %w", err)
 	}
+	// 0 length is valid, indicating none configured, since the volume monitors in the DB can be many.
+	a.volumeMonitors = volMons
+
+	return nil
+}
 
+func (a *ResourcesMonitoringAPI) GetResourcesMonitoringConfiguration(_ context.Context, _ *proto.GetResourcesMonitoringConfigurationRequest) (*proto.GetResourcesMonitoringConfigurationResponse, error) {
```
Comment (cstyan) [inline coderd/agentapi/resources_monitoring.go:69]: both parameters here are unused now, but we're implementing the interface based on the grpc defitions, I'm not sure if updating those/the API is a breaking change that we need to stage in some way or if we can just update them now in this PR?

Comment (spikecurtis) [reply coderd/agentapi/resources_monitoring.go:69]: The grpc API will always take a context.

As for the request object, we want to include it to make it easier to add parameters in future in a back-compatible way. So, just leave as is.

Comment (cstyan) [reply coderd/agentapi/resources_monitoring.go:69]: > As for the request object, we want to include it to make it easier to add parameters in future in a back-compatible way. So, just leave as is.

👍 makes sense.

File: coderd/agentapi/resources_monitoring.go [hunk 5]
```diff
@@ -89,18 +112,7 @@ func (a *ResourcesMonitoringAPI) PushResourcesMonitoringUsage(ctx context.Contex
...
-		// do not want to treat it as an error.
-		if errors.Is(err, sql.ErrNoRows) {
-			return nil
-		}
-
-		return xerrors.Errorf("fetch memory resource monitor: %w", err)
-	}
-
-	if !monitor.Enabled {
+	if !a.memoryMonitor.Enabled || a.memoryMonitor.CreatedAt.IsZero() {
```
Comment (spikecurtis) [inline coderd/agentapi/resources_monitoring.go]: The zero value of `a.memoryMonitor.Enabled` is false, so I think the first check is sufficient here.

**Review by spikecurtis — APPROVED** [review]
A small suggestion inline, but I don't need to review again.

File: coderd/agentapi/resources_monitoring.go (hunk 5 above)
Comment (cstyan) [reply coderd/agentapi/resources_monitoring.go]: 👍 yep, it should be sufficient to have just one (either check works here), will change this back to just checking `Enabled`. 

I'd added `CreatedAt.IsZero()` here since we had to change `if memoryErr != nil {` in `GetResourcesMonitoringConfiguration` and there we need to use `CreateAt.IsZero` to indicate "no configuration".
