### PR TITLE
test: don't drop error on blank IP address in report

### LINKED ISSUE #1286: flake: TestSSH/RemoteForward (agent reportConnection logs ERROR on empty RemoteAddr)
CI run: https://github.com/coder/coder/actions/runs/21224353181
Failing job: https://github.com/coder/coder/actions/runs/21224353181/job/61067344480 (test-go-pg (ubuntu-latest), Linux)
Commit: e78d89620b306fefc864b3b31f930f4ccfb3877e (Matt Vollmer) https://github.com/coder/coder/commit/e78d89620b306fefc864b3b31f930f4ccfb3877e

Failure:
- Test: `cli TestSSH/RemoteForward`
- Symptom in logs:
  - `agent: split host and port for connection report failed  ip=""  error="missing port in address"`
  - Immediately followed by: `*** slogtest: log detected at level ERROR; TEST FAILURE ***`
  - The ssh remote forward then ends early and the test polls `http://localhost:8222/` with `connection refused`.

Relevant log excerpt (from job logs):
- `agent.ssh-server: reverse port forward  bind_host=127.0.0.1  bind_port=8222`
- `agent: split host and port for connection report failed  ip=""  error="missing port in address"`
- `*** slogtest: log detected at level ERROR; TEST FAILURE ***`

Suspected root cause:
- `agent.(*agent).reportConnection` calls `net.SplitHostPort(ip)` unconditionally. When `ip` is empty (because `session.RemoteAddr()` can be nil and we pass `remoteAddrString := ""`), SplitHostPort errors and we log at ERROR.
- Tests using `slogtest` treat any ERROR-level log as a test failure, so this becomes a flake when RemoteAddr is nil.

Code pointers:
- `agent/agent.go` around `reportConnection`:
  - https://github.com/coder/coder/blob/e78d89620b306fefc864b3b31f930f4ccfb3877e/agent/agent.go#L886
- `agent/agentssh/agentssh.go` passes empty string when `session.RemoteAddr() == nil`:
  - https://github.com/coder/coder/blob/e78d89620b306fefc864b3b31f930f4ccfb3877e/agent/agentssh/agentssh.go#L396
- Test:
  - `cli/ssh_test.go` subtest `RemoteForward`.

Suggested fix:
- In `reportConnection`, treat empty / non-host:port values as best-effort and do *not* log at ERROR.
  - e.g. `if ip != "" { host, _, err := net.SplitHostPort(ip); if err == nil { ip = host } }`
  - or log at Debug/Warn at most.

Assignment notes:
- Latest meaningful changes in `agent/agent.go` include Spike Curtis; `agentssh` remote addr nil-handling also previously touched by Spike.

Repro idea:
- `go test ./cli -run '^TestSSH$/RemoteForward$' -count=100`

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes https://github.com/coder/internal/issues/1286

We can get blank IP address from the net connection if the client has already disconnected, as was the case in this flake. Fix is to only log error if we get something non-empty we can't parse.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#21642** <a href="https://app.graphite.com/github/pr/coder/coder/21642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/coder/21642?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: agent/agent.go [hunk 1]
```diff
@@ -882,12 +882,16 @@ const (
 )
 
 func (a *agent) reportConnection(id uuid.UUID, connectionType proto.Connection_Type, ip string) (disconnected func(code int, reason string)) {
-	// Remove the port from the IP because ports are not supported in coderd.
-	if host, _, err := net.SplitHostPort(ip); err != nil {
-		a.logger.Error(a.hardCtx, "split host and port for connection report failed", slog.F("ip", ip), slog.Error(err))
-	} else {
-		// Best effort.
-		ip = host
+	// a blank IP can unfortunately happen if the connection is broken in a data race before we get to introspect it. We
```
Comment (mafredri) [inline agent/agent.go]:
```suggestion
	// A blank IP can unfortunately happen if the connection is broken in a data race before we get to introspect it. We
```

**Review by mafredri — APPROVED** [review]
Approving, but do we want to consider assigning `ip = host` if `ip == ""`? Granted, I'm unsure if host will be defined here either.

**Comment by spikecurtis** [comment]
> Approving, but do we want to consider assigning `ip = host` if `ip == ""`? Granted, I'm unsure if host will be defined here either.

`host` is only used to set `ip`, so if `ip` is empty there is nothing to be done.
