### PR TITLE
fix(site): Don't hide/show errors between failures

### LINKED ISSUE #5822: Workspace page flashes errors when API key expires
https://user-images.githubusercontent.com/6332295/214111403-bddbf3ac-1c71-41fd-891f-5a4ecc647f41.mov

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix #5822 

Reason: The error, for getting info, only should be cleared when it is successful. Doing that before, hides and shows the error between requests.

### CODE REVIEW

File: site/src/xServices/workspace/workspaceXService.ts [hunk 1]
```diff
@@ -291,7 +291,7 @@ export const workspaceMachine = createMachine(
               error: {
                 entry: "assignRefreshWorkspaceWarning",
                 after: {
-                  "1000": {
+                  "2000": {
```
Comment (BrunoQuaresma) [inline site/src/xServices/workspace/workspaceXService.ts:294]: I also increased the time between retries to not spam the server

**Review by Kira-Pilot — APPROVED** [review]
