### PR TITLE
fix: filter "add group member" by organization

### LINKED ISSUE #13915: Solidify permissions and licensing checks in the UI for Org feature set
Orgs is an enterprise feature. We should ensure it is effectively and coherently gated prior to releasing as an experiment.

**Requirements**
- [x] experiment name should be appropriate and documented
- [x] add small notice if experiment is enabled but user does not have premium license
- [x] make sure org features cannot be accessed and orgs cannot be created without a premium license
- [x] change site-wide permissions to be org-scoped where necessary in line with [this PR](https://github.com/coder/coder/pull/14009)
- [x] ensure that the UI doesn't error for single-org deployment after we've added all these new org features
- [x] add Jest tests for above cases
- [x] Organization sidebar settings should be conditional based on actor's capabilities. 
  - [x] "Organization Settings" should change to "Organization Summary" if the user cannot `organization.<org_id>.update`
  - [x] See [comment below](https://github.com/coder/coder/issues/13915#issuecomment-2271486254) for conditional _ideas_
- [x] Docs link for orgs/premium license
- [x] Update middleware error to say premium instead of enterprise
- [x] Show summary if not entitled

**Known issues**

- [x] groups page user dropdown shows all users on the site, not just members of the organizatinon. When adding a user to the group if they are not in the org, you get an error "User must be a member of organization "rabbit-group""

### PR DESCRIPTION
**Pull request by code-asher**
This is accomplished by using the members endpoint instead of the users endpoint, and to that end the UserAutocomplete component has been reworked to support either endpoint as separate components with a shared base.

This only affects the group page under organizations, the original one (which shows when the multi-org experiment is disabled) remains unaffected.  The org group page dropdown should now only show users belonging to the organization instead of all the users in the deployment.

Closes https://github.com/coder/coder/issues/13915

### CODE REVIEW

File: site/src/components/UserAutocomplete/UserAutocomplete.tsx [hunk 1]
```diff
@@ -16,45 +17,99 @@ import {
...
+		/>
+	);
+};
+
+export type MemberAutocompleteProps =
+	CommonAutocompleteProps<OrganizationMemberWithUserData> & {
+		organizationId: string;
+	};
+
+export const MemberAutocomplete: FC<MemberAutocompleteProps> = ({
```
Comment (code-asher) [inline site/src/components/UserAutocomplete/UserAutocomplete.tsx:67]: Is this colocation bad?  I originally was going to create separate directories for the user and member autocompletes but then I was not sure what to do with `InnerAutocomplete` because I do not really want that to be exported.  Maybe this is a case where just duplicating the code is better, but my sense is that we would rather not have drift here between the two components.

Third option is to export `InnerAutocomplete` as `UserAutocomplete` and the caller is responsible for passing in the data instead of providing components that do it.

Comment (BrunoQuaresma) [reply site/src/components/UserAutocomplete/UserAutocomplete.tsx:66]: I think it’s fine for now to keep it under UserAutocomplete. You made some good points. 👍

**Review by BrunoQuaresma — APPROVED** [review]
The code looks good to me and works as expected, but I’m missing an integration test to make this behavior more intentional and to prevent us from accidentally removing or replacing it in the future.

**Comment by code-asher** [comment]
Fair, let me add one on the group page.

**Comment by code-asher** [comment]
@BrunoQuaresma I added a Storybook testing the integration but do you know if there is a way to mock errors with react-query?  I see we use `setQueryData()` to mock the data but it does not look like there is a way to mock errors.  Right now I have it just actually making the query, which of course then fails with a 404, that way I can test the errors in Storybook, but it feels kinda bad to do it that way.

**Comment by code-asher** [comment]
I figured out a way to do it, but let me know if there is a better way

**Comment by BrunoQuaresma** [comment]
@code-asher it looks good enough for me 🚢 it
