### PR TITLE
fix: Remove audit warning if unlicensed

### LINKED ISSUE #4383: License issue warning after update to 0.9.4 (audit logging is enabled)
## Description
I updated my coder setup to version 0.9.4 and now when I view the dashboard I see a huge license violation warning because the audit feature is enabled.
image
I did not enabled this feature nor would I know how after a license. 

## Desired solution
The warning should not appear when  the feature is not actively configured or used.

## My coder env settings:
```
      CODER_PG_CONNECTION_URL: "postgresql://{{ coder__postgres_user }}:{{ coder__postgres_password }}@postgres/{{ coder__postgres_db }}?sslmode=disable"
      CODER_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "{{ coder__url_with_proto }}"
      CODER_WILDCARD_ACCESS_URL: "{{ coder__wildcard_url }}"
      CODER_PROMETHEUS_ENABLE: "true"
      CODER_PROMETHEUS_ADDRESS: "0.0.0.0:7090"
      CODER_TAILSCALE: true
```

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4383.

### CODE REVIEW

File: enterprise/coderd/coderd.go [hunk 1]
```diff
@@ -267,7 +267,9 @@ func (api *API) serveEntitlements(rw http.ResponseWriter, r *http.Request) {
 		Entitlement: entitlements.auditLogs,
 		Enabled:     api.AuditLogging,
 	}
-	if api.AuditLogging {
+	// Audit logging is disabled by default, do we want to
```
Comment (deansheather) [inline enterprise/coderd/coderd.go:270]:
```suggestion
	// Audit logging is enabled by default, do we want to
```

**Review by deansheather — APPROVED** [review]
if you're triple sure this doesn't give every unlicensed deployment audit logging for free then LGTM 👍

**Review by f0ssel — APPROVED** [review]
Makes sense, it wasn't clear to me in the code that audit logging was on by default.
