### PR TITLE
fix: Fix keyboard focus styles on buttons

### LINKED ISSUE #4262: bug(UI): Tab selection does not work on delete workspace dialogue.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix #4262

### CODE REVIEW

File: site/src/theme/overrides.ts [hunk 1]
```diff
@@ -36,6 +36,10 @@ export const getOverrides = ({ palette, breakpoints }: Theme): Overrides => {
         textTransform: "none",
         letterSpacing: "none",
         border: `1px solid ${palette.divider}`,
+
+        "&:focus-visible": {
+          outline: `2px solid ${palette.primary.dark}`,
```
Comment (BrunoQuaresma) [inline site/src/theme/overrides.ts:41]: Matches the text input styles for focus

**Review by presleyp — APPROVED** [review]
