### PR TITLE
fix(coderd): add blocking GetProvisionerJobByIDWithLock for workspace build cancellation

### LINKED ISSUE #885: flake: `TestPatchCancelWorkspaceBuild/User_is_allowed_to_cancel`
```
     workspacebuilds_test.go:583: 
        	Error Trace:	/home/runner/work/coder/coder/coderd/workspacebuilds_test.go:583
        	Error:      	Received unexpected error:
        	            	PATCH http://localhost:45217/api/v2/workspacebuilds/27da28ac-2d02-4429-b1ba-809a634cbccc/cancel?expect_status=: unexpected status code 500: Internal error fetching provisioner job.
        	            		Error: sql: no rows in result set
        	Test:       	TestPatchCancelWorkspaceBuild/User_is_allowed_to_cancel
```
https://github.com/coder/coder/actions/runs/16927754056/job/47966820758

### PR DESCRIPTION
**Pull request by kacpersaw**
Closes https://github.com/coder/internal/issues/885

Adds a new database method GetProvisionerJobByIDWithLock that uses FOR UPDATE without SKIP LOCKED to fix workspace build cancellation returning 500 errors when jobs are locked.

### CODE REVIEW

File: coderd/database/queries/provisionerjobs.sql [hunk 1]
```diff
@@ -55,6 +55,15 @@ WHERE
 FOR UPDATE
 SKIP LOCKED;
 
+-- name: GetProvisionerJobByIDWithLock :one
```
Comment (deansheather) [inline coderd/database/queries/provisionerjobs.sql:58]: Probs should add a comment here explaining the difference

**Review by deansheather — APPROVED** [review]
