### PR TITLE
fix: update workspace button should properly update the workspace

### LINKED ISSUE #4098: Workspace with `Outdated` status does not update the first time you click `update`
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

You have to click `update` a second time for the workspace to update.

image

### PR DESCRIPTION
**Pull request by Kira-Pilot**
Resolves #4098

We didn't have the latest template on our machine context so we weren't sending down the correct `template.active_version_id` when posting a new build.

### CODE REVIEW

**Review by BrunoQuaresma — APPROVED** [review]
LGTM. Just a minor question, during the refreshTemplate state, does the UI show a loader? So the user knows the workspace is updating?

**Comment by BrunoQuaresma** [comment]
Also, something that could be done is to encapsulate those states so it is easier to know they are related like:

```
updatingWorkspace: {
    initial: "refreshingTemplate",
    states: {
        refreshingTemplate: {...},
        startingWithLatest: {...},
    }
}
```

File: site/src/xServices/workspace/workspaceXService.ts [hunk 1]
```diff
@@ -271,6 +271,20 @@ export const workspaceMachine = createMachine(
                   },
                 },
               },
+              refreshTemplate: {
```
Comment (kylecarbs) [inline site/src/xServices/workspace/workspaceXService.ts:274]: Should this be `refreshTemplateAndStart` instead? It could be a bit misleading since it doesn't _just_ refresh.

**Review by kylecarbs — APPROVED** [review]

**Comment by Kira-Pilot** [comment]
> LGTM. Just a minor question, during the refreshTemplate state, does the UI show a loader? So the user knows the workspace is updating?

It does now!

File: site/src/xServices/workspace/workspaceXService.ts (hunk 1 above)
Comment (kylecarbs) [reply site/src/xServices/workspace/workspaceXService.ts]: Ahh, yup I think that'd make sense!
