### PR TITLE
fix(cli/cliui): skip startup script logs when Wait=false

### LINKED ISSUE #13580: Startup script error message is obnoxious on SSH
My workspace personalize script often fails in a way that doesn't invalidate my development environment. Unfortunately, all `ssh` operations are met with a giant multi-page dump like this:

```
& rsync /tmp/sail coder.c0:/tmp/
👋 Your workspace is outdated! Update it here: https://dev.coder.com/@ammar/c0

==> ⧗ Running workspace agent startup scripts
2024-06-14 14:16:30.318-05:00 Startup Script: + trap 'touch /tmp/.coder-startup-script.done' EXIT
2024-06-14 14:16:30.318-05:00 Startup Script: + sudo service docker start
2024-06-14 14:16:30.366-05:00 Coder Login: Logging into Coder...
2024-06-14 14:16:30.366-05:00 Coder Login: 
2024-06-14 14:16:30.410-05:00 File Browser: Installing filebrowser 
2024-06-14 14:16:30.410-05:00 File Browser: 
2024-06-14 14:16:30.455-05:00 Git Clone: /home/coder/coder already exists and isn't empty, skipping clone!
2024-06-14 14:16:30.499-05:00 File Browser: Downloading File Browser for linux/amd64...
2024-06-14 14:16:30.542-05:00 code-server: Installing code-server!
2024-06-14 14:16:30.586-05:00 Personalize: ~ ~/coder
2024-06-14 14:16:30.586-05:00 Personalize: Hit:1 https://download.docker.com/linux/ubuntu jammy InRelease
...
```

upon failure. It's extremely annoying and unhelpful. Instead, we should just show a single warning line that suggests running a different command to see the full error.

### PR DESCRIPTION
**Pull request by mafredri**
When users pass `--wait=no` or set `CODER_SSH_WAIT=no`, startup logs are no longer dumped to stderr. The stage indicator is still shown, just not the log content.

This addresses the issue where SSH operations like rsync and scp would dump hundreds of lines of startup logs, breaking scriptability.

Depends on #21104

Fixes #13580

---

Examples of output when using no wait:

Early attach:

```
❯ CODER_SSH_WAIT=no ssh foo.coder
=== ✔ Starting workspace [3583ms]
==> ⧗ Cleaning Up
=== ✔ Cleaning Up [19ms]
==> ⧗ Waiting for the workspace agent to connect
=== ✔ Waiting for the workspace agent to connect [955ms]
==> ⧗ Running workspace agent startup scripts (non-blocking)
Notice: The startup scripts are still running and your workspace may be incomplete.
For more information and troubleshooting, see https://coder.com/docs/@v2.29.0/admin/templates/troubleshooting#your-workspace-may-be-incomplete and https://coder.com/docs/admin/templates/troubleshooting
coder@foo:~/coder$
```

During startup:

```
❯ CODER_SSH_WAIT=no ssh foo.coder
==> ⧗ Running workspace agent startup scripts (non-blocking)
Notice: The startup scripts are still running and your workspace may be incomplete.
For more information and troubleshooting, see https://coder.com/docs/@v2.29.0/admin/templates/troubleshooting#your-workspace-may-be-incomplete and https://coder.com/docs/admin/templates/troubleshooting
coder@foo:~/coder$
```

After startup (still shows warning, but no logs):

```
❯ CODER_SSH_WAIT=no ssh foo.coder
==> ⧗ Running workspace agent startup scripts (non-blocking)
=== ✘ Running workspace agent startup scripts (non-blocking) [18303ms]
Warning: A startup script exited with an error and your workspace may be incomplete.
For more information and troubleshooting, see https://coder.com/docs/@v2.29.0/admin/templates/troubleshooting#startup-script-exited-with-an-error and https://coder.com/docs/admin/templates/troubleshooting
coder@foo:~/coder$
```

### CODE REVIEW

**Comment by bpmct** [comment]
## 📚 Documentation Check

### ✨ No Changes Needed

This PR is an internal refactoring that improves code organization without changing user-facing behavior. The changes:

- Extract agent waiting logic into a dedicated `agentWaiter` struct with clearer state transitions
- Rename `showStartupLogs` → `waitedForConnection` for clarity
- Add helper methods (`pollWhile`, `waitForConnection`, `handleConnected`, `waitForReconnection`, `streamLogs`) to organize the state machine
- Improve code comments and maintainability

**User-facing behavior remains unchanged:**
- The `--wait` flag behavior is identical (already documented in [docs/reference/cli/ssh.md](https://github.com/coder/coder/blob/main/docs/reference/cli/ssh.md#--wait))
- Agent connection flow and messaging unchanged
- Startup script handling unchanged
- The troubleshooting message mentioning `--wait=no` is preserved

The existing documentation in `docs/reference/cli/ssh.md` and `docs/admin/templates/troubleshooting.md` already covers the `--wait` flag functionality and remains accurate.

---
*This comment was generated by an AI Agent through [Coder Tasks](https://coder.com/docs/ai-coder/tasks)*

File: cli/cliui/agent.go [hunk 1]
```diff
@@ -222,19 +222,25 @@ func (aw *agentWaiter) handleConnected(ctx context.Context, agent codersdk.Works
...
+	// dumping a wall of logs on users who explicitly pass --wait=no. The stage
+	// indicator is still shown, just not the log content. See issue #13580.
+	if aw.opts.Wait {
+		var err error
+		agent, err = aw.streamLogs(ctx, agent, follow, fetchedAgent)
 		if err != nil {
 			return err
 		}
+
+		// If we were following, wait until startup completes.
```
Comment (mtojek) [inline cli/cliui/agent.go:221]: nit: "we" means who? browser API or CLI?

File: cli/cliui/agent.go [hunk 2]
```diff
@@ -222,19 +222,25 @@ func (aw *agentWaiter) handleConnected(ctx context.Context, agent codersdk.Works
...
+		if follow {
+			agent, err = aw.pollWhile(ctx, agent, func(agent codersdk.WorkspaceAgent) bool {
+				return agent.LifecycleState.Starting()
+			})
+			if err != nil {
+				return err
```
Comment (mtojek) [inline cli/cliui/agent.go:227]: since we will call `pollWhite` in a few places, should wrap these errors?

File: cli/cliui/agent.go [hunk 3]
```diff
@@ -222,19 +222,25 @@ func (aw *agentWaiter) handleConnected(ctx context.Context, agent codersdk.Works
...
+	// indicator is still shown, just not the log content. See issue #13580.
+	if aw.opts.Wait {
+		var err error
+		agent, err = aw.streamLogs(ctx, agent, follow, fetchedAgent)
 		if err != nil {
 			return err
 		}
+
+		// If we were following, wait until startup completes.
+		if follow {
```
Comment (mtojek) [inline cli/cliui/agent.go:222]: nit: `if !follow { return }` ?

File: cli/cliui/agent.go [hunk 4]
```diff
@@ -222,19 +222,25 @@ func (aw *agentWaiter) handleConnected(ctx context.Context, agent codersdk.Works
...
-
-	// If we were following, wait until startup completes.
-	if follow {
-		agent, err = aw.pollWhile(ctx, agent, func(agent codersdk.WorkspaceAgent) bool {
-			return agent.LifecycleState.Starting()
-		})
+	// In non-blocking mode (Wait=false), we don't stream logs. This prevents
+	// dumping a wall of logs on users who explicitly pass --wait=no. The stage
+	// indicator is still shown, just not the log content. See issue #13580.
+	if aw.opts.Wait {
```
Comment (mtojek) [inline cli/cliui/agent.go:214]: nit: `if !wait { return }` ?

File: cli/cliui/agent_test.go [hunk 5]
```diff
@@ -268,6 +268,87 @@ func TestAgent(t *testing.T) {
 				"For more information and troubleshooting, see",
 			},
 		},
+		{
+			// Verify that in non-blocking mode (Wait=false), startup script
```
Comment (mtojek) [inline cli/cliui/agent_test.go:272]: should we add a test for `streamLogs` timeouting?

File: cli/cliui/agent.go (hunk 1 above)
Comment (mafredri) [reply cli/cliui/agent.go:221]: It's referring to the code it's talking about, i.e. the CLI implementation. The previous function (streamLogs) is called with `follow` which is what we're referring to.

File: cli/cliui/agent.go (hunk 3 above)
Comment (mafredri) [reply cli/cliui/agent.go:222]: This would prevent us from hitting the code-path below outputting failure or completion status.

File: cli/cliui/agent.go (hunk 4 above)
Comment (mafredri) [reply cli/cliui/agent.go:214]: Same as for `!follow`, we wouldn't hit the code-paths below and it would change the output examples listed in PR description.

File: cli/cliui/agent_test.go (hunk 5 above)
Comment (mafredri) [reply cli/cliui/agent_test.go:272]: Do you mean context cancellation during log streaming?

Comment (mafredri) [reply cli/cliui/agent_test.go:272]: If I got this right: https://github.com/coder/coder/pull/21125

Comment (mtojek) [reply cli/cliui/agent_test.go:272]: yup, thanks!

**Review by mtojek — APPROVED** [review]
