### PR TITLE
fix: fix Listen/Unlisten race on Pubsub

### LINKED ISSUE #15312: Listen/Unlisten race in Pubsub
spotted while reviewing #15303

In the [Pubsub](https://github.com/coder/coder/blob/b1298a3c1ec1ea9ea05df105bc66c69f4c7976a1/coderd/database/pubsub/pubsub.go#L234C1-L295C2), we can't hold the `qMu` lock while calling `Listen` or `Unlisten` on the `pgListener`, because this lock is also held while delivering notifications. This was the source of a Pubsub deadlock (#11950) that we fixed in #12518.  However, that fix leaves us with a new race condition that goes like this:

We have a single subscriber to some event, and they cancel their subscription.  Concurrently, we get a new Subscribe call for the same event. Since we don't hold a lock while calling `Listen` and `Unlisten`, these could happen in any order. If `Unlisten` is called last, the new subscriber won't get any events.

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #15312

When we need to `Unlisten()` for an event, instead of immediately removing the event from the `p.queues`, we store a channel to signal any goroutines trying to Subscribe to the same event when we are done. On `Subscribe`, if the channel is present, wait for it before calling `Listen` to ensure the ordering is correct.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#15315** <a href="https://app.graphite.dev/github/pr/coder/coder/15315?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: coderd/database/pubsub/pubsub.go [hunk 1]
```diff
@@ -258,32 +312,40 @@ func (p *PGPubsub) subscribeQueue(event string, newQ *msgQueue) (cancel func(),
...
+		// as above, we must not hold the lock while calling into pgListener
+		if unlistening != nil {
 			uErr := p.pgListener.Unlisten(event)
+			close(unlistening)
+			// we can now delete the queueSet if it is empty.
+			func() {
+				p.qMu.Lock()
+				defer p.qMu.Unlock()
+				qSet, ok := p.queues[event]
+				if ok && len(qSet.m) == 0 {
```
Comment (mafredri) [inline coderd/database/pubsub/pubsub.go:343]: If we wanted to be really careful here we could check that the channel on qSet is still ours. It'll work without the check though, just the delete could (very) theoretically be done by another routine, which would still only be a semantic difference.

File: coderd/database/pubsub/pubsub.go [hunk 2]
```diff
@@ -188,6 +187,19 @@ func (l pqListenerShim) NotifyChan() <-chan *pq.Notification {
 	return l.Notify
 }
 
+type queueSet struct {
+	m map[*msgQueue]struct{}
```
Comment (mafredri) [inline coderd/database/pubsub/pubsub.go:191]: Suggestion: m => q/queues. I feel this would explain better what one is looking at when viewing the code.

**Review by mafredri — APPROVED** [review]
Solid fix! I think down the line this code could be/become hard to reason about as others look at it or make changes, but I don't have a better idea currently that doesn't have potential performance implications.

**Comment by spikecurtis** [comment]
Yeah, I'm not feeling like it's a great design, but I also couldn't come up with anything better.

2 designs I rejected:

1. I considered having the `p.queues` be the source of truth with a background goroutine reconciling the `Listen`/`Unlisten`, sort of like we do elsewhere in the product, but the problem is that when you `Subscribe`, you don't want to return until you know the pubsub is listening. So, that kind of eventually consistent model won't work.

2. We could go back to how things were and hold the `p.qMu` while calling `Listen`/`Unlisten`. We'd need to ensure that we keep reading from the notification channel, even if the `p.qMu` is locked. One way to do that is by creating an unbounded FIFO queue of notifications, so we could keep reading from the channel, even if we can't immediately process the notifications due to the lock. An unbounded queue sounds dangerous though.

**Comment by mafredri** [comment]
Yeah, I think you were right to reject those options, what you ended up is still better.

My idea was to have a single goroutine responsible for coordinating sub/unsub, basically anything queues related. We'd still have to solve for not doing blocking operations synchronously, thought.

Could look something like this:

```go
func (p *PGPubsub) listenLoop() {
	var queues map[string]... // p.queues no longer needs locking
	for {
		r := <-p.listen
		switch req.(type) {
		case listen:
			if _, ok := queues[r.event]; !ok {
				// ~go p.pqListener.Listen()
			}
			r.err <- err
		case unlisten:
			// like listen, but unlisten
		case receive:
			// enqueue notif
	}
}

func (p *PGPubsub) subscribeQueue(event string, newQ *msgQueue) (cancel func(), err error) {
	errc := make(chan error, 1)
	p.listen <- listen{"event", newQ, errc}
	_ = <-errc
	return func() {
		p.listen <- unlisten{"event", newQ, errc}
	}
}
```
