### PR TITLE
fix(site): do not render invalid task status URI, fix GitHub new links

### LINKED ISSUE #20429: tasks: random empty link when still starting up
https://github.com/user-attachments/assets/a7ef404b-30d8-43cd-8948-6025c53a0b20

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #20429

### CODE REVIEW

File: site/src/pages/TaskPage/TaskStatusLink.tsx [hunk 1]
```diff
@@ -30,15 +30,21 @@ export const TaskStatusLink: FC<TaskStatusLinkProps> = ({ uri }) => {
 					switch (type) {
 						case "pull":
 							icon = <GitPullRequestArrowIcon />;
-							label = number
-								? `${org}/${repo}#${number}`
-								: `${org}/${repo} pull request`;
+							label =
+								number === "new"
```
Comment (mafredri) [inline site/src/pages/TaskPage/TaskStatusLink.tsx:34]: Drive-by fix: Handle new. I personally ran into this where open a new PR was called `coder/coder#new`, very confusing.

**Review by DanielleMaywood — APPROVED** [review]

**Review by ssncferreira — APPROVED** [review]
LGTM 🚗
