### PR TITLE
Remove tfexec, allow TF_ environment vars and log them

### LINKED ISSUE #1359: Manually set terraform env variable prevents template creation
## OS Information

- OS: Linux
- `coder --version`: Coder v0.5.5-devel+2d3dc43 Tue May 10 07:44:09 UTC 2022

## Steps to Reproduce

1. Set a terraform environment variable: `export TF_LOG=1`
2. Run `coder server`
3. Create first template: `coder templates create docker-local -d ~/src/cdr/coder/examples/docker-local`

There should be no issue creating the template, or detailed hints on how to fix the problem (e.g. coder server is running with these environment variables set, please restart it without).

## Actual

Template creation fails:

```console
> Create and upload "~/src/cdr/coder/examples/docker-local"? (yes/no) yes
✔ Queued [139ms]
✔ Setting up [6ms]
✔ Parse parameters [17ms]
✘ Detecting persistent resources [420ms]
template import provision for start: recv import provision: set terraform env: manual setting of env var "TF_LOG" detected
```

## Notes

Considering [this comment](https://github.com/coder/coder/issues/1198#issuecomment-1120645349) I wanted to see if I can get more information out of terraform (a naive approach). I think it's fine the value can't be changed but I would have expected this value to either propagate to terraform or for the server to either inform of a way to fix it or filter out the variable.

We could for instance filter out some incompatible `TF_` env vars here, potentially logging the exclusion as a warning:
https://github.com/coder/coder/blob/2d3dc436a81d2fe6fa8af7d4958b7a1f51f56caa/provisioner/terraform/provision.go#L93-L111

## AC

Replace the terraform exec command with directly executing terraform
Test for the steps to repro this bug to validate this case is covered
Expose in the logs that the env vars are set

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #1359 

Couple of notes:

I've refactored our use of `terraform` and in the process made some changes that I believe bring us in line with what we are actually doing:

 * Dropped calls to `terraform state pull` because I don't believe we are supporting remote terraform state; instead it is stored in Coder
 * commands are directly passed the `Context` that gets cancelled when we read a `Cancel` message off the stream.

### CODE REVIEW

File: provisioner/terraform/executor.go [hunk 1]
```diff
@@ -0,0 +1,338 @@
...
+	if state.Values != nil {
+		resources, err = ConvertResources(state.Values.RootModule, rawGraph)
+		if err != nil {
+			return nil, err
+		}
+	}
+	return resources, nil
+}
+
+func (e executor) getState(ctx context.Context) (*tfjson.State, error) {
```
Comment (kylecarbs) [inline provisioner/terraform/executor.go:255]: This should have the `get` prefix removed to stay consistent with other similar funcs.

File: provisionersdk/logger.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+import (
+	"bufio"
+	"io"
+
+	"github.com/coder/coder/provisionersdk/proto"
+)
+
+type Logger interface {
+	Log(l *proto.Log) error
+}
```
Comment (kylecarbs) [inline provisionersdk/logger.go:12]: Is this interface primarily to merge the `Provision` and `Parse` log streams? I think abstracting this makes it confusing to follow the code, and just to save ~30 lines of code.

File: provisioner/terraform/executor.go [hunk 3]
```diff
@@ -0,0 +1,338 @@
...
+	// Required for "terraform init" to find "git" to
+	// clone Terraform modules.
+	env := os.Environ()
+	// Only Linux reliably works with the Terraform plugin
+	// cache directory. It's unknown why this is.
+	if e.cachePath != "" && runtime.GOOS == "linux" {
+		env = append(env, "TF_PLUGIN_CACHE_DIR="+e.cachePath)
+	}
+	return env
+}
```
Comment (kylecarbs) [inline provisioner/terraform/executor.go:40]: We seem to use this in every call. Instead of piping it through the execution functions, we could have a single `command` function that returns a command initialized with the `binaryPath`, `args`, and this env already applied.

File: provisioner/terraform/executor.go [hunk 4]
```diff
@@ -0,0 +1,338 @@
...
+	if !v.GreaterThanOrEqual(minimumTerraformVersion) {
+		return xerrors.Errorf(
+			"terraform version %q is too old. required >= %q",
+			v.String(),
+			minimumTerraformVersion.String())
+	}
+	return nil
+}
+
+func (e executor) getVersion(ctx context.Context) (*version.Version, error) {
```
Comment (kylecarbs) [inline provisioner/terraform/executor.go:101]: `get` could be removed here too for consistency with other functions.

File: provisioner/terraform/provision.go [hunk 5]
```diff
@@ -298,141 +136,60 @@ func (t *terraform) Provision(stream proto.DRPCProvisioner_ProvisionStream) erro
...
-		return proto.LogLevel_WARN, nil
-	case "error":
-		return proto.LogLevel_ERROR, nil
-	default:
-		return proto.LogLevel(0), xerrors.Errorf("invalid log level %q", logLevel)
+func logTerraformEnvVars(logger provisionersdk.Logger) error {
+	env := os.Environ()
+	for _, e := range env {
+		if strings.HasPrefix(e, "TF_") {
+			err := logger.Log(&proto.Log{Level: proto.LogLevel_WARN, Output: "terraform environment variable: " + e})
```
Comment (kylecarbs) [inline provisioner/terraform/provision.go:188]: Terraform variables can be applied with [environment variables](https://www.terraform.io/cli/config/environment-variables#tf_var_name), which means logs would leak secrets. We could `SplitN` by `=` to print the keys instead.

File: provisioner/terraform/provision_test.go [hunk 6]
```diff
@@ -22,24 +22,7 @@ import (
...
-		}
-	}
-}
-
-provider "coder" {
-}
-	`
-	t.Log(provider)
-
+func testProvisioner(t *testing.T) (context.Context, proto.DRPCProvisionerClient) {
```
Comment (kylecarbs) [inline provisioner/terraform/provision_test.go:25]: I might call this `setupProvisioner` instead. This could give a false impression that this is a test.

File: provisionersdk/logger.go [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+
+func LogWriter(logger Logger, level proto.LogLevel) (io.WriteCloser, <-chan any) {
+	r, w := io.Pipe()
+	done := make(chan any)
+	go readAndLog(logger, r, done, level)
+	return w, done
+}
+
+func readAndLog(logger Logger, r io.Reader, done chan<- any, level proto.LogLevel) {
```
Comment (kylecarbs) [inline provisionersdk/logger.go:61]: From my read over the code, this channel is only used for testing, but I'm not sure why it's required because we already ensure the output.

File: provisionersdk/logger_test.go [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+	mStream := new(mocks.ParseStream)
+	defer mStream.AssertExpectations(t)
+
+	l := &proto.Log{Level: proto.LogLevel_ERROR, Output: "an error"}
+	mStream.On("Send", mock.MatchedBy(withLog(l))).Return(nil)
+
+	uut := provisionersdk.NewParseLogger(mStream)
+	err := uut.Log(l)
+	require.NoError(t, err)
+}
```
Comment (kylecarbs) [inline provisionersdk/logger_test.go:72]: It seems this log abstraction tests that: a provisioner logger sends a provision log type, and a parse logger sends a parse log type. I feel like this is a lot of code to do that. Would this be caught by many other tests in the codebase?

**Review by kylecarbs — CHANGES_REQUESTED** [review]

File: provisionersdk/logger.go (hunk 2 above)
Comment (spikecurtis) [reply provisionersdk/logger.go:12]: Yeah, the idea is to be able to write generic logging code, like `LogWriter()` that work on either kind of stream.  This is something I found really useful when I prototyped my docker-compose provisioner, so I think it's really useful to have generic logging routines.

File: provisioner/terraform/executor.go (hunk 3 above)
Comment (spikecurtis) [reply provisioner/terraform/executor.go:40]: `plan()` and `apply()` have their own environment that include parameters from end users and the coder terraform provider stuff, so not every call has the same environment in the code I'm refactoring.  I _could_ unify things, but that ends up having to either initialize the `executor` with the parameters, or pass the parameters instead of `env` on every call.  Right now the `executor` only asks for the environment on `plan()` and `apply()` and uses this basic env for every other call.

File: provisionersdk/logger.go (hunk 7 above)
Comment (spikecurtis) [reply provisionersdk/logger.go:61]: The channel is used in product code, e.g. in `executor.go:141`.  The purpose is to allow the code that calls logging routines to ensure that the logging is finished before moving on to other things.  Without this, you could end up with out-of-order logs, or worse, a log response after a complete response.

File: provisionersdk/logger_test.go (hunk 8 above)
Comment (spikecurtis) [reply provisionersdk/logger_test.go:72]: Well, the compiler actually ensures that the types match up.  This tests that a call to Log results in a call to Send and that the fields match up.  Pretty basic, I know, but it's a baseline for the test below for `LogWriter()`.

These small, basic, unit tests are important right by the code they test.  It might be the case that other tests in the codebase actually cover this function, but it breaks encapsulation to depend on that for test coverage; changes elsewhere shouldn't cause us to leave this code exposed.

Comment (kylecarbs) [reply provisionersdk/logger_test.go:72]: I don't disagree, but the decomposition of this comes at a relatively high cost of maintainability. Adding ~400 lines for logging seems like a *lot* right now (I'm including mock code and tests in that count), considering what we gain from it.

I'm not convinced this abstraction reduces complexity for an implementor and seems premature when we only have a single provisioner emitting logs or using this abstraction. It's hard for me to understand as a contributor the purpose of this abstraction when it's only used in a single place.

File: provisioner/terraform/executor.go (hunk 3 above)
Comment (kylecarbs) [reply provisioner/terraform/executor.go:40]: Makes sense!

File: provisionersdk/logger_test.go (hunk 8 above)
Comment (spikecurtis) [reply provisionersdk/logger_test.go:72]: lines of code is a poor metric for complexity in the first place, and counting autogenerated mocks and test code in your count is counterproductive because it penalizes code that is thoroughly tested versus code that is not.

This abstraction _increases maintainability_ because it separates concerns and keeps logging boilerplate out of the provisioner functions which bloat those functions and makes them harder to read.

Comment (kylecarbs) [reply provisionersdk/logger_test.go:72]: There is _some basis_ of lines of code to complexity in solving a problem. It's not strong, but if the difference is a significant factor it can be a warning of complexity. This code is ~45 lines of code in `main` (https://github.com/coder/coder/blob/main/provisioner/terraform/provision.go#L150-L195).

There are no tests in the Terraform provider that guarantee logs are sent, so I'd be in favor of moving the testing to there for now and abstracting this once we add providers. I agree with the separation of concerns, but adding an interface that's only been implemented a single time certainly adds cognitive overhead when navigating the codebase.

There are presently no parse logs sent from the Terraform provider, so half of the purpose for this abstraction isn't actually used (apart from tests) at all. It increases maintainability assuming there are many provisioners, but we only have one.

Comment (kylecarbs) [reply provisionersdk/logger_test.go:72]: I'm happy to get others' perspectives on this too, it's very possible I'm being too pedantic. I care a lot about all of the code having a clear purpose for its structure, hence my hesitation to abstract before multiple usages pop up.

File: provisionersdk/logger.go [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+
+func (p parseLogger) Log(l *proto.Log) error {
+	return p.stream.Send(&proto.Parse_Response{
+		Type: &proto.Parse_Response_Log{
+			Log: l,
+		},
+	})
+}
+
+func LogWriter(logger Logger, level proto.LogLevel) (io.WriteCloser, <-chan any) {
```
Comment (mafredri) [inline provisionersdk/logger.go:54]: This function seems very specific to how we are running terraform and moves some of the granularity out of terraform, whilst creating a dependency provisionersdk. Some thoughts:

- We're assuming log messages will be newline delimited (scanner)
- We cannot control log level on a per-log line basis (may be relevant for future provisioners)
- This function creates an `io.Pipe` but never closes r or w, closing w is implicitly up to the caller (the done channel makes it a bit less clear we're supposed to close)
- In acutal uses, we're relying on `exec.Command` to close w (i.e. there's a lot of implicitness going on)

File: provisionersdk/logger_test.go (hunk 8 above)
Comment (mafredri) [reply provisionersdk/logger_test.go:72]: I already touched on this a bit in another comment. But I kind of agree with Kyle here, at least some of the abstractions. I'm fine with the `Logger` interface (I'm not sure how we'd do it otherwise), but I think the other logic could be moved into the terraform package. It's usually best to wait for 2+ (more the merrier) use-cases before creating an abstraction, that way it's easier to reason about what the common functionality should be.

And there's no need to be afraid to copy-paste code between packages until enough use-cases surface! As saying GOes:

> [A little copying is better than a little dependency.](https://go-proverbs.github.io)

**Review by mafredri — COMMENTED** [review]
I haven't looked much at the terraform package before, so I haven't 100% reviewed all changes, but added my comments and thoughts nonetheless.

File: provisioner/terraform/provision.go [hunk 10]
```diff
@@ -298,141 +136,87 @@ func (t *terraform) Provision(stream proto.DRPCProvisioner_ProvisionStream) erro
...
+		if strings.HasPrefix(e, "TF_") {
+			parts := strings.SplitN(e, "=", 2)
+			if len(parts) != 2 {
+				panic("os.Environ() returned vars not in key=value form")
+			}
+			if !tfEnvSafeToPrint[parts[0]] {
+				parts[1] = "<value redacted>"
+			}
+			err := logger.Log(&proto.Log{
+				Level:  proto.LogLevel_WARN,
```
[the remark this answers is not in the document]
Comment (spikecurtis) [reply provisioner/terraform/provision.go:213]: passing terraform environment variables could alter behavior in ways we have not predicted, so that's why I picked WARN.

File: provisioner/terraform/executor.go [hunk 11]
```diff
@@ -0,0 +1,338 @@
...
+		var log terraformProvisionLog
+		err := decoder.Decode(&log)
+		if err != nil {
+			return
+		}
+		logLevel := convertTerraformLogLevel(log.Level, logger)
+
+		err = logger.Log(&proto.Log{Level: logLevel, Output: log.Message})
+		if err != nil {
+			// Not much we can do.  We can't log because logging is itself breaking!
```
[the remark this answers is not in the document]
Comment (spikecurtis) [reply provisioner/terraform/executor.go:326]: I did think about that, but then you end up with two "loggers" and that's just real confusing.

**Comment by spikecurtis** [comment]
I've dropped parse support and moved the logging stuff into the terraform package.  One consequence of this is that the unit tests end up being in the `terraform` package instead of `terraform_test` because none of the logging code is exported.  I don't personally mind a mix of internal and external tests of a package, but something to be aware of.

**Review by kylecarbs — APPROVED** [review]

File: provisioner/terraform/executor_test.go [hunk 12]
```diff
@@ -0,0 +1,63 @@
+// nolint:testpackage
```
[the remark this answers is not in the document]
Comment (spikecurtis) [reply provisioner/terraform/executor_test.go:1]: as in `executor_internal_test.go` or something else?

[the remark this answers is not in the document]
Comment (kylecarbs) [reply provisioner/terraform/executor_test.go:1]: Yup, exactly
