### PR TITLE
fix: force lowercase DNS hostnames for VPN

### LINKED ISSUE #54: DNS doesn't work for workspaces with uppercase letters in their names
My workspaces:

Image

Problem:

Image

No problem:

Image

Is there a workaround that doesn't involve renaming the workspace?

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes https://github.com/coder/coder-desktop-macos/issues/54

I've also double checked that agents with hyphens & underscores play nice once programmed, as do workspaces with hyphens:

```
$ ping6 main_agent-1.main-workspace.admin.coder
PING6(56=40+8+8 bytes) fd60:627a:a42b:4e91:88c0:da4a:df4f:b54e --> fd60:627a:a42b:46d4:8b55:e549:e498:e6f5
```
also fine in Firefox & Safari, though I'm a little surprised underscores work.

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#16613** <a href="https://app.graphite.dev/github/pr/coder/coder/16613?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/16613?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: tailnet/controllers.go [hunk 1]
```diff
@@ -883,23 +883,30 @@ type Workspace struct {
 }
 
 // updateDNSNames updates the DNS names for all agents in the workspace.
+// DNS hosts must be all lowercase, or the resolver won't be able to find them.
+// Usernames are globally unique & case-insensitive.
+// Workspace names are unique per-user & case-insensitive.
+// Agent names are unique per-workspace & case-insensitive.
```
Comment (ethanndickson) [inline tailnet/controllers.go:889]: Just discovered this isn't true - agent names are case-sensitive. You can have two agents whose name only differs in capitalization.

**Review by ThomasK33 — APPROVED** [review]

**Review by deansheather — APPROVED** [review]

**Comment by ethanndickson** [comment]
### Merge activity

* **Feb 19, 8:51 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/coder/16613).
