### PR TITLE
fix: use terminal emulator that keeps state in ReconnectingPTY tests

### LINKED ISSUE #9764: flake: TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY/SignedTokenQueryParameter
```
    pty.go:36: got: runner@ubuntu:~$ echo testtest                                                  
    pty.go:36: got: runner@ubuntu:~$                                                                
    pty.go:36: got: runner@ubuntu:~$                                                                
    apptest.go:1432: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/apptest/apptest.go:1432
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/apptest/apptest.go:99
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY/SignedTokenQueryParameter
        	Messages:   	find echo output
```

https://github.com/coder/coder/actions/runs/6222769921/job/16887365393?pr=9717

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #9764 

I think what's happening is that terminal control sequences are relative to the current cursor position, so by creating a new terminal emulator each time we matched, we were getting incorrect terminal state.  This PR refactors so that you create one terminal emulator per reader, then match multiple times against the same emulator as you read more data.

### CODE REVIEW

File: agent/agent_test.go [hunk 1]
```diff
@@ -1696,19 +1699,20 @@ func TestAgent_ReconnectingPTY(t *testing.T) {
...
 			// Try a non-shell command.  It should output then immediately exit.
 			netConn4, err := conn.ReconnectingPTY(ctx, uuid.New(), 80, 80, "echo test")
 			require.NoError(t, err)
 			defer netConn4.Close()
 
-			require.NoError(t, testutil.ReadUntil(ctx, t, netConn4, matchEchoOutput), "find echo output")
-			require.ErrorIs(t, testutil.ReadUntil(ctx, t, netConn3, nil), io.EOF)
+			tr4 := testutil.NewTerminalReader(t, netConn4)
+			require.NoError(t, tr4.ReadUntil(ctx, matchEchoOutput), "find echo output")
+			require.ErrorIs(t, tr4.ReadUntil(ctx, nil), io.EOF)
```
Comment (spikecurtis) [inline agent/agent_test.go:1715]: note: original was netConn3 but I think that's copypasta

File: testutil/pty.go [hunk 2]
```diff
@@ -9,46 +9,74 @@ import (
...
+		}
+		for i := len(lines) - 1; i >= 0; i-- {
+			if strings.TrimSpace(lines[i]) != "" {
+				lines = lines[:i+1]
+				break
 			}
 		}
+		gotTrimmed := strings.Join(lines, "\n")
+		tr.t.Logf("Terminal contents:\n%s", gotTrimmed)
+		if retErr != nil {
```
Comment (code-asher) [inline testutil/pty.go:63]: Should we skip logging the bytes on expected errors too?  The only one we expect is EOF when `matcher` is `nil`, I think.

**Review by code-asher — APPROVED** [review]
Makes sense!

File: testutil/pty.go (hunk 2 above)
Comment (spikecurtis) [reply testutil/pty.go:63]: I guess we could skip if matcher is nil and EOF...
