### PR TITLE
fix: Move state pull output to stdout

### LINKED ISSUE #1645: `coder state pull` emits to stderr instead of stdout
This means you can't do `coder state pull | less`. Instead you have to do `coder state pull 2>&1 | less`, which is surprising.

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #1645.

### CODE REVIEW

**Review by mafredri — APPROVED** [review]
Oh, I did not realize `cmd.Print` goes to stderr, LGTM!

File: cli/state.go [hunk 1]
```diff
@@ -50,7 +51,7 @@ func statePull() *cobra.Command {
 			}
 
 			if len(args) < 2 {
-				cmd.Println(string(state))
+				fmt.Fprintln(cmd.OutOrStdout(), string(state))
```
Comment (AbhineetJain) [inline cli/state.go:54]: Linting can be fixed with:
```suggestion
				_, _ = fmt.Fprintln(cmd.OutOrStdout(), string(state))
```

Comment (kylecarbs) [reply cli/state.go]: tyty
