### PR TITLE
chore: fix race in cron close behavior (TestAgent_WriteVSCodeConfigs)

### LINKED ISSUE #11226: flake: TestAgent_WriteVSCodeConfigs
https://github.com/coder/coder/runs/19666833200

Test times out after 10 minutes due to a deadlock in shutting down the agent

```
goroutine 2555 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc0006ae1b0?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc0006ae1a8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sync/waitgroup.go:116 +0xa5
github.com/coder/coder/v2/agent/agentscripts.(*Runner).Close(0xc0006ae100)
	/home/runner/actions-runner/_work/coder/coder/agent/agentscripts/agentscripts.go:320 +0x19e
github.com/coder/coder/v2/agent.(*agent).Close(0xc004a0b200)
	/home/runner/actions-runner/_work/coder/coder/agent/agent.go:1498 +0x439
github.com/coder/coder/v2/agent_test.TestAgent_WriteVSCodeConfigs(0xc005b456c0)
	/home/runner/actions-runner/_work/coder/coder/agent/agent_test.go:1870 +0x160a
testing.tRunner(0xc005b456c0, 0x27ceba0)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
```

### PR DESCRIPTION
**Pull request by Emyrk**
Closes https://github.com/coder/coder/issues/11226

# Problem

The problem is `cmdCloseWait` never closes, so there is an open agent go routine that will not close. In the unit test in Question, **`cron.Run()` is the only routine started**. So I figured it is likely the routine left open. You can exercise the test locally with `go test -run TestAgent_WriteVSCodeConfigs --timeout=8s -count=20`. Or I wrote a new test that always exercises what I think the bug is.

# What is happening

The cron package we are using allows `Run()` to be called after `Close()`. This essentially allows restarting the cron daemon, which is interesting.

`Run()` is called on a go routine. So in our unit tests, it is possible the `Close()` gets called first, then `Run()` is called. There exists a time period between these 2 lines of code:

https://github.com/coder/coder/blob/9b343c49578400cb6c60aa5e92ee0825e9575f91/agent/agentscripts/agentscripts.go#L330-L331

If `Run()` is called between there, the `cmdCloseWait` will never terminate.

# A fix

If the `cronCtx` is cancelled, we just never call `cron.Run()`. The ctx is always cancelled before the stop, so this should be _pretty good_. Ideally we implement this inside the cron package and hook on their `running` flag. However this should suffice.

### CODE REVIEW

File: agent/agentscripts/agentscripts_test.go [hunk 1]
```diff
@@ -53,6 +53,15 @@ func TestTimeout(t *testing.T) {
...
 
+// TestCronClose exists because cron.Run() can happen after cron.Close().
+// If this happens, there used to be a deadlock.
+func TestCronClose(t *testing.T) {
+	t.Parallel()
+	runner := agentscripts.New(agentscripts.Options{})
+	runner.StartCron()
+	require.NoError(t, runner.Close(), "close runner")
+}
+
```
Comment (Emyrk) [inline agent/agentscripts/agentscripts_test.go:64]: Hard to know for sure if this was the bug... I was able to reproduce this way, still feels like it might be more rare intertwined into some setup code that has more chances for the order to be "correct".

**Review by johnstcn — APPROVED** [review]
I like the use of TDD to pin this one down!
