### PR TITLE
fix: remove pty match for TestSSH/RemoteForward

### LINKED ISSUE #10578: flake: TestSSH/RemoteForward: match deadline exceeded
Seen here: https://github.com/coder/coder/actions/runs/6797725835/job/18480442576

```
ssh_test.go:431: 2023-11-08 11:45:26.687: cmd: read error: match deadline exceeded: context deadline exceeded (wanted "i-am-ready"; got " for the workspace agent to connect\r\n=== ✔ Waiting for the workspace agent to connect [871ms]\r\n==> ⧗ Running workspace agent startup scripts (non-blocking)\r\nNotice: The startup scripts are still running and your workspace may be incomplete.\r\nFor more information and troubleshooting, see https://coder.com/docs/v2/latest/templates#your-workspace-may-be-incomplete and https://coder.com/docs/coder-oss/latest/templates#troubleshooting-templates\r\n\r\r\nThe default interactive shell is now zsh.\r\r\nTo update your account to use zsh, please run `chsh -s /bin/zsh`.\r\r\nFor more details, please visit [https://support.apple.com/kb/HT208050.\r\r\n\x1b[?1034hMac-1699410560950:~](https://support.apple.com/kb/HT208050./r/r/n/x1b[?1034hMac-1699410560950:~) runner$ ")
    ssh_test.go:431: 
        	Error Trace:	/Users/runner/work/coder/coder/pty/ptytest/ptytest.go:347
        	            				/Users/runner/work/coder/coder/pty/ptytest/ptytest.go:177
        	            				/Users/runner/work/coder/coder/pty/ptytest/ptytest.go:153
        	            				/Users/runner/work/coder/coder/cli/ssh_test.go:431
        	Error:      	read error
        	Test:       	TestSSH/RemoteForward
        	Messages:   	match deadline exceeded: context deadline exceeded (wanted "i-am-ready"; got " for the workspace agent to connect\r\n=== ✔ Waiting for the workspace agent to connect [871ms]\r\n==> ⧗ Running workspace agent startup scripts (non-blocking)\r\nNotice: The startup scripts are still running and your workspace may be incomplete.\r\nFor more information and troubleshooting, see https://coder.com/docs/v2/latest/templates#your-workspace-may-be-incomplete and https://coder.com/docs/coder-oss/latest/templates#troubleshooting-templates\r\n\r\r\nThe default interactive shell is now zsh.\r\r\nTo update your account to use zsh, please run `chsh -s /bin/zsh`.\r\r\nFor more details, please visit https://support.apple.com/kb/HT208050.\r\r\n\x1b[?1034hMac-1699410560950:~ runner$ ")
    t.go:84: 2023-11-08 11:45:26.687 [info]  agent: shutting down agent
    t.go:84: 2023-11-08 11:45:26.687 [debu]  agent: set lifecycle state  current={"state":"shutting_down","changed_at":"2023-11-08T11:45:26.687872Z"}  last={"state":"ready","changed_at":"2023-11-08T11:45:11.501833Z"}
    t.go:84: 2023-11-08 11:45:26.687 [debu]  agent: set lifecycle state  current={"state":"off","changed_at":"2023-11-08T11:45:26.687903Z"}  last={"state":"shutting_down","changed_at":"2023-11-08T11:45:26.687872Z"}
    t.go:84: 2023-11-08 11:45:26.688 [debu]  agent: reporting lifecycle state  payload={"state":"shutting_down","changed_at":"2023-11-08T11:45:26.687872Z"}
    t.go:84: 2023-11-08 11:45:26.688 [debu]  agent: sdk request  method=POST  url=http://localhost:51251/api/v2/workspaceagents/me/report-lifecycle  body=""
    t.go:84: 2023-11-08 11:45:26.689 [debu]  GET  host=localhost:51251  path=/api/v2/workspaces/d4771ebe-0dd7-467b-a5b1-4ffd09eb1760/watch  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2023-11-08T11:45:11.591067Z"  took=15.097969875s  status_code=200  latency_ms=15097  request_id=3e1ee465-ff8a-45a0-bcc8-b3de5e7ea6f1
    t.go:84: 2023-11-08 11:45:26.689 [debu]  GET  host=localhost:51251  path=/api/v2/derp-map  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2023-11-08T11:45:11.50906Z"  took=15.180166458s  status_code=101  latency_ms=15180  request_id=d01e8f1c-a04a-45d6-9c8a-c5932cfae443
    t.go:84: 2023-11-08 11:45:26.689 [debu]  unable to read client update, connection may be closed  client_id=98[720](https://github.com/coder/coder/actions/runs/6797725835/job/18480442576#step:5:721)b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=568227c8-b43c-4982-91c5-e755cba6c283 ...
        error= read json:
                   github.com/coder/coder/v2/tailnet.(*coordinator).handleNextClientMessage
                       /Users/runner/work/coder/coder/tailnet/coordinator.go:359
                 - failed to get reader: failed to read frame header: EOF
    t.go:84: 2023-11-08 11:45:26.689 [debu]  deleted client node  client_id=98720b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=00000000-0000-0000-0000-000000000000
    t.go:84: 2023-11-08 11:45:26.689 [debu]  deleted client connectionSocket from map  client_id=98720b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=00000000-0000-0000-0000-000000000000  agent_id=568227c8-b43c-4982-91c5-e755cba6c283
    t.go:84: 2023-11-08 11:45:26.689 [debu]  deleted last client connectionSocket from map  client_id=98720b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=00000000-0000-0000-0000-000000000000  agent_id=568227c8-b43c-4982-91c5-e755cba6c283
    t.go:84: 2023-11-08 11:45:26.689 [debu]  deleted client agents  client_id=98720b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=00000000-0000-0000-0000-000000000000
    t.go:84: 2023-11-08 11:45:26.689 [debu]  GET  host=localhost:51251  path=/api/v2/workspaceagents/568227c8-b43c-4982-91c5-e755cba6c283/coordinate  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2023-11-08T11:45:11.511759Z"  took=15.177919583s  status_code=101  latency_ms=15177  request_id=b1f4f996-fa17-45d4-b71d-e0677a4861b8
    t.go:84: 2023-11-08 11:45:26.689 [debu]  done sending updates  client_id=98720b96-66c0-4eb7-80e0-0e4e859cc177  agent_id=568227c8-b43c-4982-91c5-e755cba6c283
    t.go:84: 2023-11-08 11:45:26.689 [info]  agent.ssh-server: ssh connection complete  remote_addr=[fd7a:115c:a1e0:4361:8602:2c85:3cbb:7631]:40393  local_addr=[fd7a:115c:a1e0:49d6:b259:b7ac:b1b2:48f4]:1  error=EOF
    t.go:84: 2023-11-08 11:45:26.690 [debu]  agent.ssh-server: copy output done  bytes=219  error=<nil>
    t.go:84: 2023-11-08 11:45:26.690 [info]  agent.ssh-server: ssh session returned  remote_addr=[fd7a:115c:a1e0:4361:8602:2c85:3cbb:7631]:40393  local_addr=[fd7a:115c:a1e0:49d6:b259:b7ac:b1b2:48f4]:1  error="signal: killed"
    ssh_test.go:421: 
        	Error Trace:	/Users/runner/work/coder/coder/cli/ssh_test.go:421
        	            				/Users/runner/work/coder/coder/cli/ssh_test.go:773
        	            				/Users/runner/hostedtoolcache/go/1.20.10/arm64/src/runtime/asm_arm64.s:1172
        	Error:      	Received unexpected error:
        	            	running command "coder ssh": SSH connection ended unexpectedly:
        	            	    github.com/coder/coder/v2/cli.(*RootCmd).ssh.func1
        	            	        /Users/runner/work/coder/coder/cli/ssh.go:383
        	Test:       	TestSSH/RemoteForward
        	Messages:   	ssh command failed
```

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #10578

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10789** <a href="https://app.graphite.dev/github/pr/coder/coder/10789?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/10789?utm_source=stack-comment).

File: cli/ssh_test.go [hunk 1]
```diff
@@ -644,32 +646,36 @@ func TestSSH(t *testing.T) {
...
-		// Download the test page
-		pty.WriteLine("curl localhost:8222")
-		pty.ExpectMatch("hello world")
+		require.Eventually(t, func() bool {
+			req, err := http.NewRequestWithContext(ctx, http.MethodGet, "http://localhost:8222/", nil)
+			if !assert.NoError(t, err) {
+				// true exits the loop.
+				return true
+			}
+			resp, err := http.DefaultClient.Do(req)
```
Comment (mafredri) [inline cli/ssh_test.go:665]: I wonder if this may leave idle connections after it (triggering leak detection). If it does though, perhaps we just need to handle it in test main so we can keep using the default client.

**Review by mafredri — APPROVED** [review]

File: cli/ssh_test.go [hunk 2]
```diff
@@ -644,32 +646,36 @@ func TestSSH(t *testing.T) {
...
+			if err != nil {
+				t.Logf("HTTP GET http://localhost:8222/ %s", err)
+				return false
+			}
+			defer resp.Body.Close()
+			body, err := io.ReadAll(resp.Body)
+			assert.NoError(t, err)
+			assert.EqualValues(t, "hello world", body)
+			return true
+		}, testutil.WaitLong, testutil.IntervalFast)
```
Comment (mtojek) [inline cli/ssh_test.go:675]: The previous matcher waited for `i-am-ready` echoed by the startup script. It means that the agent didn't start yet, and `localhost:8222` is not available. I'm curious where is the trick in the new implementation. Is it a matter of `testutil.WaitLong`?

Comment (spikecurtis) [reply cli/ssh_test.go:675]: Yeah, before we waited for `i-am-ready` and then connected.

Here, we just (re)try connecting in a loop until success or a timeout.

File: cli/ssh_test.go (hunk 1 above)
Comment (spikecurtis) [reply cli/ssh_test.go:665]: I haven't seen any.  I think idle connections are cleaned up promptly.

File: cli/ssh_test.go (hunk 2 above)
Comment (mtojek) [reply cli/ssh_test.go:675]: Isn't it the same root cause? The agent is still not ready to connect. Are you just trying to reduce complexity and remove extra conditions?

**Comment by spikecurtis** [comment]
### Merge activity

* **Nov 20, 11:50 AM**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/10789).

File: cli/ssh_test.go (hunk 2 above)
Comment (spikecurtis) [reply cli/ssh_test.go:675]: Before we used PTY/expect to wait until we thought the agent was connected and SSH remote forward was up, then we connected and verified the output.  The root cause of the flake is that we didn't always get the startup script log because of the way the `ssh` command works.  It detects that a startup script is running, then asks to follow logs, but the log may have already been dispatched and we miss it, causing the expect to hang.

In the new implementation we do away with PTY/expect entirely, and thus dodge the root cause from before.  To deal with the fact that we no longer get an explicit signal that the remote forward is up, we just retry it multiple times until it comes up.

Comment (mtojek) [reply cli/ssh_test.go:675]: > The root cause of the flake is that we didn't always get the startup script log because of the way the ssh command works.

Ok, that's the part I wasn't aware of. Thanks!
