### PR TITLE
fix: filter workspace_build resource on start/stop action

### LINKED ISSUE #4796: audit: allow filtering by workspace build start/stop
In #4625, we added the ability to audit on workspace build stop/start. Currently, we have no filters for this addition - you cannot query by workspace_build.

We should add this ability so users can see just stopped workspace builds or just started workspace builds.

As part of this effort, an example should be added to the dropdown so that users know how to filter, as well as to the audit log docs.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #4796 

Screen Shot 2023-01-20 at 9 54 53 AM
Screen Shot 2023-01-20 at 9 55 05 AM

### CODE REVIEW

File: site/src/pages/AuditPage/AuditPageView.tsx [hunk 1]
```diff
@@ -35,9 +35,11 @@ const presetFilters = [
     name: "Created workspaces",
   },
   { query: "resource_type:template action:create", name: "Added templates" },
-  { query: "resource_type:user action:create", name: "Added users" },
-  { query: "resource_type:template action:delete", name: "Deleted templates" },
   { query: "resource_type:user action:delete", name: "Deleted users" },
```
Comment (Kira-Pilot) [inline site/src/pages/AuditPage/AuditPageView.tsx:38]: These were fairly redundant so I've removed them.

**Review by BrunoQuaresma — APPROVED** [review]
Both, FE and BE look good to me

**Review by coadler — APPROVED** [review]
