### PR TITLE
fix: do not warn on valid known experiments

### LINKED ISSUE #18024: bug: valid experiments are showing as invalid on `/deployment/overview`
The Coder dashboard is displaying valid experiments as invalid.
`workspace-prebuilds` and `agentic-chat` are valid experiments.

Image

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/18024

* drive-by: renames `handleExperimentsSafe` to `handleExperimentsAvailable` to better match semantics
* defines list of `codersdk.ExperimentsKnown` and updates `ReadExperiments` to log on invalid experiments
* typescript-ignores `codersdk.Experiments` so apitypings generates a valid enum list of possible values of experiment
* updates OverviewPageView to distinguish between known 'hidden' experiments and unknown 'invalid' experiments

### CODE REVIEW

File: site/src/api/queries/experiments.ts [hunk 1]
```diff
@@ -19,3 +19,7 @@ export const availableExperiments = () => {
 		queryFn: async () => API.getAvailableExperiments(),
 	};
 };
+
+export const isKnownExperiment = (experiment: string): boolean => {
+	return Experiments.includes(experiment as Experiment);
+};
```
Comment (johnstcn) [inline site/src/api/queries/experiments.ts:25]: Alternatively, we could have the FE return the list of known experiments, but it seems silly to do this when we can just use the auto-generated type.

File: site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.tsx [hunk 2]
```diff
@@ -22,8 +22,8 @@ import { UserEngagementChart } from "./UserEngagementChart";
 type OverviewPageViewProps = {
 	deploymentOptions: SerpentOption[];
 	dailyActiveUsers: DAUsResponse | undefined;
-	readonly invalidExperiments: Experiments | string[];
-	readonly safeExperiments: Experiments | string[];
+	readonly invalidExperiments: readonly string[];
```
Comment (johnstcn) [inline site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.tsx:25]: review: this has to be a string because it might not be an Experiment

File: site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.stories.tsx [hunk 3]
```diff
@@ -118,7 +118,7 @@ export const invalidExperimentsEnabled: Story = {
 				hidden: false,
 			},
 		],
-		safeExperiments: ["shared-ports"],
+		safeExperiments: ["example"],
```
Comment (johnstcn) [inline site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.stories.tsx:121]: review: using the "example" experiment enum here instead

File: coderd/coderd.go [hunk 4]
```diff
@@ -972,7 +972,7 @@ func New(options *Options) *API {
 		})
 		r.Route("/experiments", func(r chi.Router) {
 			r.Use(apiKeyMiddleware)
-			r.Get("/available", handleExperimentsSafe)
+			r.Get("/available", handleExperimentsAvailable)
```
Comment (Emyrk) [inline coderd/coderd.go:975]: Kinda unfortunate we have `/available` that returns only the safe experiments. Ideally there would be a `/available` and `/safe`. Or just have `/available` return a `map[string]bool` where the `bool` is `true` for safe or something.

File: coderd/coderd.go [hunk 5]
```diff
@@ -1895,7 +1895,9 @@ func ReadExperiments(log slog.Logger, raw []string) codersdk.Experiments {
 			exps = append(exps, codersdk.ExperimentsSafe...)
 		default:
 			ex := codersdk.Experiment(strings.ToLower(v))
-			if !slice.Contains(codersdk.ExperimentsSafe, ex) {
+			if !slice.Contains(codersdk.ExperimentsKnown, ex) {
+				log.Warn(context.Background(), "ignoring unknown experiment", slog.F("experiment", ex))
+			} else if !slice.Contains(codersdk.ExperimentsSafe, ex) {
```
Comment (Emyrk) [inline coderd/coderd.go:1900]: :+1:.

**Review by Emyrk — APPROVED** [review]
The nomenclature around `available` and `safe` feels inconsistent in the api and usage. But that is not introduced in this PR.

File: site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.stories.tsx (hunk 3 above)
Comment (Emyrk) [reply site/src/pages/DeploymentSettingsPage/OverviewPage/OverviewPageView.stories.tsx:121]: Makes sense to me. Using a consistent experiment that we don't need to keep changing.

I wonder if `example` is the best name, but I do not have a better suggestion.

`ExperimentPlaceholder`, `ExperimentDummy`, idk.

File: coderd/coderd.go (hunk 4 above)
Comment (johnstcn) [reply coderd/coderd.go:975]: Yeah I considered also returning all available experiments here but elected to keep the scope of this PR small.
