### PR TITLE
fix: remove hold WaitGroup in TestConcurrentFetch

### LINKED ISSUE #950: flake: data race in TestConcurrentFetch
```
=== Failed
=== FAIL: coderd/files TestCancelledConcurrentFetch (0.00s)
==================
WARNING: DATA RACE
Write at 0x00c000c26158 by goroutine 61:
  runtime.racewrite()
      <autogenerated>:1 +0x1e
  github.com/coder/coder/v2/coderd/files_test.TestConcurrentFetch.func2()
      /home/runner/work/coder/coder/coderd/files/cache_test.go:115 +0x104

Previous read at 0x00c000c26158 by goroutine 30:
  runtime.raceread()
      <autogenerated>:1 +0x1e
  github.com/coder/coder/v2/coderd/files_test.TestConcurrentFetch()
      /home/runner/work/coder/coder/coderd/files/cache_test.go:109 +0x712
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1851 +0x44

Goroutine 61 (running) created at:
  github.com/coder/coder/v2/coderd/files_test.TestConcurrentFetch()
      /home/runner/work/coder/coder/coderd/files/cache_test.go:112 +0x6db
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1851 +0x44

Goroutine 30 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.6/x64/src/testing/testing.go:2142 +0xeea
  main.main()
      _testmain.go:59 +0x164
==================
    testing.go:1490: race detected during execution of test

=== FAIL: coderd/files TestConcurrentFetch (0.00s)
    testing.go:1490: race detected during execution of test
```

Seen here: https://github.com/coder/coder/actions/runs/17296221039/job/49094997590

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes: https://github.com/coder/internal/issues/950

Pretty sure the intention of the `hold` wait group is to try to get the two goroutines that the test starts running at the same time. But, that should be the case for two goroutines started anyway.

The use of `hold` doesn't actually guarantee concurrent execution of `Acquire`, just that both goroutines get as far as `Done()` --- the go scheduler could run them serially without incident.

So I've chosen to just remove the use of `hold` to simplify.

But, for posterity, the data race was due to incrementing by 1 in the loop along with the goroutine that calls Done. You could increment by 1 and then back down to 0 before the second iteration of the loop starts. This then causes a data race with calling `Wait()` in the first goroutine and `Add()` in the second iteration. c.f. https://pkg.go.dev/sync#WaitGroup.Add

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#19617** <a href="https://app.graphite.dev/github/pr/coder/coder/19617?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/19617?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: coderd/files/cache_test.go [hunk 1]
```diff
@@ -100,21 +100,15 @@ func TestConcurrentFetch(t *testing.T) {
...
-		hold.Add(1)
 		// TODO: wg.Go in Go 1.25
-		wg.Add(1)
 		go func() {
 			defer wg.Done()
-			hold.Done()
-			hold.Wait()
 			_, err := cache.Acquire(ctx, dbM, fileID)
-			require.NoError(t, err)
+			assert.NoError(t, err)
```
Comment (aslilac) [inline coderd/files/cache_test.go:111]: looking at the docs for this, I suppose the change is so that the `require` variant doesn't try to terminate test execution from a goroutine, instead letting it run to completion?

just checking so I know for the future

**Review by aslilac — APPROVED** [review]
thanks for waiting for me to get back from vacation for the review 😄

File: coderd/files/cache_test.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/files/cache_test.go:111]: Yeah, `require` calls `t.FailNow()` which is only allowed from the main test goroutine. Calling it from some other goroutine will, IIRC, panic and cause the rest of the tests to get marked as `unknown` status. Just generally makes it harder to read the test output and figure out the cause of the failure.

So the rule is `assert` anywhere other than the main test goroutine.
