### PR TITLE
fix: fix goroutine leak in log streaming over websocket

### LINKED ISSUE #14881: Coder pods running out of memory
We've noticed over the past several months the coder pods gradually run out of memory over time.  Typically around 30 day mark but can't really say for sure.  Here is our memory allocation for a 5 replica set in k8s.

```
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 4000m
        memory: 8Gi
```

and here is a datadog screenshot of the memory usage around 30 day mark

Screenshot 2024-09-23 at 7 15 33 PM

Coder V2.13.4
We don't keep the k8s logs so not able to share those.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #14881

Our handlers for streaming logs don't read from the websocket. We don't allow the client to send us any data, but the websocket library we use requires reading from the websocket to properly handle pings and closing. Not doing so can [can cause the websocket to hang on write](https://github.com/coder/websocket/issues/405), leaking go routines which were noticed in #14881.

This fixes the issue, and in process refactors our log streaming to a encoder/decoder package which provides generic types for sending JSON over websocket.

I'd also like for us to upgrade to the latest https://github.com/coder/websocket but we should also upgrade our tailscale fork before doing so to avoid including two copies of the websocket library.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#15709** <a href="https://app.graphite.dev/github/pr/coder/coder/15709?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/15709?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: coderd/workspaceagents.go [hunk 1]
```diff
@@ -396,11 +397,9 @@ func (api *API) workspaceAgentLogs(rw http.ResponseWriter, r *http.Request) {
 	}
 	go httpapi.Heartbeat(ctx, conn)
 
-	ctx, wsNetConn := codersdk.WebsocketNetConn(ctx, conn, websocket.MessageText)
-	defer wsNetConn.Close() // Also closes conn.
+	encoder := wsjson.NewEncoder[[]codersdk.WorkspaceAgentLog](conn, websocket.MessageText)
+	defer encoder.Close(websocket.StatusGoingAway)
```
Comment (mafredri) [inline coderd/workspaceagents.go:401]: Why do we use going away instead of normal closure? It's kind of an error state and a divergence from before (i.e. status from calling `wsNetConn.Close()`).

File: coderd/workspaceagents.go [hunk 2]
```diff
@@ -767,7 +758,7 @@ func (api *API) derpMapUpdates(rw http.ResponseWriter, r *http.Request) {
 			err := ws.Ping(ctx)
 			cancel()
 			if err != nil {
-				_ = nconn.Close()
+				_ = ws.Close(websocket.StatusGoingAway, "ping failed")
```
Comment (mafredri) [inline coderd/workspaceagents.go:761]: 👍🏻

File: codersdk/wsjson/decoder.go [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+}
+
+// Chan starts the decoder reading from the websocket and returns a channel for reading the
+// resulting values. The chan T is closed if the underlying websocket is closed, or we encounter an
+// error. We also close the underlying websocket if we encounter an error reading or decoding.
+func (d *Decoder[T]) Chan() <-chan T {
+	if d.chanCalled.Load() {
+		panic("chan called more than once")
+	}
+	d.chanCalled.Store(true)
```
Comment (mafredri) [inline codersdk/wsjson/decoder.go:29]: Let's use compare and swap to avoid race.

File: codersdk/wsjson/decoder.go [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+	values := make(chan T)
```
Comment (mafredri) [inline codersdk/wsjson/decoder.go:30]:
```suggestion
	values := make(chan T, 1)
```
Suggestion: Performance, allow us to start reading the next message instead of waiting for the current one to be grabbed first.

File: codersdk/wsjson/decoder.go [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+	go func() {
+		defer close(values)
+		defer d.conn.Close(websocket.StatusGoingAway, "")
+		for {
+			typ, b, err := d.conn.Read(context.Background())
```
Comment (mafredri) [inline codersdk/wsjson/decoder.go:35]:
```suggestion
			typ, b, err := d.conn.Read(d.ctx.Done())
```
Suggestion: Optional, I guess the assumption is that calling close will release this which is fine. Perhaps add comment if not using `d.ctx`?

File: codersdk/wsjson/decoder.go [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+				return
+			}
+		}
+	}()
+	return values
+}
+
+// nolint: revive // complains that Encoder has the same function name
+func (d *Decoder[T]) Close() error {
+	err := d.conn.Close(websocket.StatusGoingAway, "")
```
Comment (mafredri) [inline codersdk/wsjson/decoder.go:64]: Same as previously, why not use normal closure? Also, why not take status like encoder for consistency?

**Review by mafredri — APPROVED** [review]
Small suggestions but otherwise LGTM 👍🏻

File: coderd/workspaceagents.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/workspaceagents.go:401]: I chose GoingAway because one likely reason for the server closing the connection is that it's shutting down.  We could also be closing because there is a new build and this agent is no longer current.

If we actually used status codes for anything we'd want to send different codes in these cases, but we don't.  I can change it to match the old `wsNetConn` for consistency.

File: codersdk/wsjson/decoder.go (hunk 6 above)
Comment (spikecurtis) [reply codersdk/wsjson/decoder.go:64]: I've switched to StatusNormalClosure.

Here I don't want to take the websocket status like Encoder because it's useful for the Decoder to implement `io.Closer` to more easily fit into existing code.

**Comment by spikecurtis** [comment]
### Merge activity

* **Dec 3, 1:12 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/15709).
