### PR TITLE
fix: fix loading states and permissions checks in organization settings

### LINKED ISSUE #331: Auditor experience w/ groups has a spinning sidebar
https://github.com/coder/coder/issues/16379

### LINKED ISSUE #346: Orgs sidebar shows loading indicator for User Admin
related to coder/internal#331

If a user is missing the User Admins permission but otherwise has access to an org, they can navigate to an orgs page directly and see the main content. But the Orgs sidebar will forever be stuck in a loading state

Image

### LINKED ISSUE #347: User without organization permission sees loading spinners instead of error message
When attempting to access an org that the user not has permissions (`/organizations/{orgName}`), loading indicators are displayed instead of an error message

Image

### LINKED ISSUE #348: Pre-org User Admin, Template Admin, and Auditor roles are not able to access expected orgs features
Need to confirm the correct permissions for the pre-org native roles User Admin, Template Admin, and Auditor.

When a user is configured as both a User Admin, Template Admin, and Auditor, the Organizations option does not appear in the Admin Settings dropdown, but they can still navigate directly to organization pages without any restrictions.

Verify that that users with the non-org User Admin, Template Admin, and Auditor roles separately or any combination of these combined should have the expected orgs permissions.

### LINKED ISSUE #349: Orgs selector dropdown can show zero items
This happens when the user has access to only 1 organization and does not have permissions to create an organization

The org selector should be displayed in a disabled state when no items in the dropdown would appear.

Figma: https://www.figma.com/design/OR75XeUI0Z3ksqt1mHsNQw?node-id=637-4129&m=dev#1118640418

Image

### LINKED ISSUE #350: Organization User Admin and template admin does not have access to organizations pages
1. A user with only the Organization User Admin does not have access to any of the pages for that org.
2. They do not see the Organizations menu item in the Admin Settings dropdown

### LINKED ISSUE #16379: Site-wide auditors see a spinning sidebar when visiting `Groups`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

https://github.com/user-attachments/assets/0c80fb56-8b59-41c5-ace5-784cb3019075

### Relevant Log Output

```shell

```

### Expected Behavior

A sidebar, or no sidebar. 

### Steps to Reproduce

1. Log in as an Auditor into a deployment with Premium license and multi-org
2. Navigate to `Admin settings->Deployment->Groups` 
3. Notice the sidebar is spinning

### Environment

On dev.coder.com

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aslilac**
Closes coder/internal#331
Closes coder/internal#346
Closes coder/internal#347
Closes coder/internal#348
Closes coder/internal#349
Closes coder/internal#350
Closes #16379

- Move several organizations permissions queries into one query fetched by the `OrganizationSettingsLayout` component

- Update permissions checks for whether the organizations settings should be accessible by a user

We used to just check if the user could edit any organization. The problem with that, is that by "organization" we meant the organization table, which just holds metadata, and didn't take into account the ability to edit members, groups, roles, or any other resource. We now check if the user can edit any of these resources individually in any organization.

- Fix a bunch of loading states, and spinners

There are a ton of places where if data was missing we just assumed it was loading. A lot of these have been cleaned up.

- Remove unused code, lots of general hygiene improvements.

Remove the unused `OrganizationSummaryPage`, move the /organizations redirect logic into its own component instead of leaving it in the settings page (which is no longer even the default)

- Update individual page permission checks, and make sure editing is checked separately from viewing

More pages are now viewable if the user has permission to view the information on them, even if they can't edit them.

### CODE REVIEW

**Comment by jaaydenh** [comment]
When testing the permissions for each Role, how do you know what the permissions should be for each user other than looking at the backend code? Having documentation of the permissions as they relate to all orgs features for all roles will be helpful for reviewing this PR especially any tests, for future testing and for documentation for users

For all roles including:
Owner, User Admin, Template Admins, Auditor, Organization Admin, Organization User Admin, Organization Template Admin, Organization Auditor

**Comment by aslilac** [comment]
I don't think it really makes sense to focus on "roles", because custom roles exist. I just focused on "what permissions make sense for enabling x". a "create/new thing" button should only show up for people with the proper permissions to create a that type of thing.

File: site/src/contexts/auth/RequirePermission.tsx [hunk 1]
```diff
@@ -14,7 +14,8 @@ export const RequirePermission: FC<RequirePermissionProps> = ({
 	isFeatureVisible,
 }) => {
 	if (!isFeatureVisible) {
-		return <Navigate to="/workspaces" />;
+		// return <Navigate to="/workspaces" />;
+		return <h1>oh fuck</h1>;
```
Comment (jaaydenh) [inline site/src/contexts/auth/RequirePermission.tsx:18]: 🥇

File: site/src/pages/OrganizationSettingsPage/OrganizationRedirect.tsx [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+		organizationPermissionsByOrganizationId: organizationPermissions,
+	} = useOrganizationSettings();
+
+	// Redirect /organizations => /organizations/some-organization-name
+	// If they can edit the default org, we should redirect to the default.
+	// If they cannot edit the default, we should redirect to the first org that
+	// they can edit.
+	const editableOrg = [...organizations]
+		.sort((a, b) => (b.is_default ? 1 : 0) - (a.is_default ? 1 : 0))
+		.find((org) => canEditOrganization(organizationPermissions[org.id]));
```
Comment (jaaydenh) [inline site/src/pages/OrganizationSettingsPage/OrganizationRedirect.tsx:19]: Its interesting how retrieving orgs with view permissions happens through useOrganizationSettings but knowing which orgs you can edit it done separately through canEditOrganization. Would you say that you avoided putting editableOrganizations inside OrganizationSettingsContext because they are not used as often and not necessary to place there?

File: site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx [hunk 3]
```diff
@@ -1,81 +1,31 @@
...
-			.sort((a, b) => (b.is_default ? 1 : 0) - (a.is_default ? 1 : 0))
-			.find((org) => canEditOrganization(permissions[org.id]));
-		if (editableOrg) {
-			return <Navigate to={`/organizations/${editableOrg.name}`} replace />;
-		}
-		return <EmptyState message="No organizations found" />;
-	}
-
-	if (!organization) {
+	if (!organization || !organizationPermissions?.editSettings) {
```
Comment (jaaydenh) [inline site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx:25]: Wouldn't it be clearer to tell users that don't have permissions to edit settings that they don't have the required permissions instead of "Organization not found"?

File: site/src/pages/OrganizationSettingsPage/CustomRolesPage/CreateEditRolePage.tsx [hunk 4]
```diff
@@ -37,9 +34,8 @@ export const CreateEditRolePage: FC = () => {
 		organizationRoles(organizationName),
 	);
 	const role = roleData?.find((role) => role.name === roleName);
-	const permissions = permissionsQuery.data;
 
-	if (isLoading || !permissions) {
+	if (isLoading || !organizationPermissions) {
```
Comment (jaaydenh) [inline site/src/pages/OrganizationSettingsPage/CustomRolesPage/CreateEditRolePage.tsx:38]: Why not tell users explicitly that they don't have permissions. This could be confusing for users who thought they did have the correct permissions. They are likely to think something is broken and file a bug or submit a support request if they just see the loader.

File: site/src/pages/OrganizationSettingsPage/OrganizationRedirect.tsx (hunk 2 above)
Comment (aslilac) [reply site/src/pages/OrganizationSettingsPage/OrganizationRedirect.tsx:19]: yeah, I think in general we don't want to be checking if the "organization" is editable, we just want to check if you have the permissions to view/edit the more specific thing that you're currently looking at. this component is a bit of a special case because it's trying to decide what organization to redirect you from, and I think the idea of "picking one you can edit" is still pretty nice here.

File: site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx (hunk 3 above)
Comment (aslilac) [reply site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx:25]: this is a case where I'd love if the `RequirePermission` component was something for display rather than a redirect, but this PR is already huge and I didn't wanna drag that work into it. I do agree that actually showing a permission error would be better tho. can I create a follow-up issue to tackle that later?

File: site/src/pages/OrganizationSettingsPage/CustomRolesPage/CreateEditRolePage.tsx (hunk 4 above)
Comment (aslilac) [reply site/src/pages/OrganizationSettingsPage/CustomRolesPage/CreateEditRolePage.tsx:38]: this isn't a specific permission check, this is "we failed to load the permissions for this org, which probably means it doesn't exist"

File: site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx (hunk 3 above)
Comment (jaaydenh) [reply site/src/pages/OrganizationSettingsPage/OrganizationSettingsPage.tsx:25]: ok lets have a separate issue

**Comment by jaaydenh** [comment]
@aslilac Its currently possible to access the default org without an enterprise or premium license. It feels like this should not be possible or there should be a full page error message. This could be a separate issue though

Screenshot 2025-02-18 at 20 55 13

**Comment by jaaydenh** [comment]
On the provisioners page an Organization user admin sees the error "Error loading the provisioner jobs" but the organization admin sees the provisioners loaded correctly. Should Organization user admins have access to this page?

Screenshot 2025-02-18 at 21 13 44

**Comment by jaaydenh** [comment]
user with sitewide auditor role is seeing the error message below for an org they are not a member of. Seems like either they should not get this error or they should not have access orgs they are not a member of.

Screenshot 2025-02-18 at 21 17 27

**Comment by aslilac** [comment]
> A user with site wide user admin, template admin and auditor is able to successfully access an org they are not a member of without any errors. This does not seem correct.

it is correct though, that's how site wide permissions are implemented

**Comment by jaaydenh** [comment]
> > A user with site wide user admin, template admin and auditor is able to successfully access an org they are not a member of without any errors. This does not seem correct.
> 
> it is correct though, that's how site wide permissions are implemented

The part that feels incorrect is that a user is only able access an org they are not a member if they have all 3 permissions combined (site wide user admin, template admin and auditor) if they have just 1 or 2 of them then they do not have acccess.

**Comment by aslilac** [comment]
after looking at the code, the new provisioners page has some deeper rooted permissions issues that probably need to be dealt with separately.

**Comment by aslilac** [comment]
> The part that feels incorrect is that a user is only able access an org they are not a member if they have all 3 permissions combined (site wide user admin, template admin and auditor) if they have just 1 or 2 of them then they do not have access. It feels like that should only be for an owner role. Behavior that only happens for combinations of roles feels confusing.

I think the real issue here is that I gave site auditors `organizations.read` to fix another issue, but site user admin and site template admin both need it as well. All of the site wide roles now have that permission, which equals them out.

**Comment by jaaydenh** [comment]
Why would a site wide template admin have access to custom roles but not idp sync? Whereas a user admin has access to both? I would expect the template admin does not need access to custom roles.

**Comment by jaaydenh** [comment]
For a site wide template admin I am still seeing this error message for an org they are not a member of. I am expecting them to have access to members in the same way they do for an org they are a member of.

Screenshot 2025-02-19 at 16 51 30

**Comment by jaaydenh** [comment]
It may help to update the roles popover with information about access to provisioners, custom roles and idp sync and to be clear about ability to manage users and groups. FYI, its because of the text here that I dont think site wide template admins or auditors should be able to access members or groups in organizations.

Screenshot 2025-02-19 at 16 57 43

**Comment by aslilac** [comment]
@jaaydenh this PR is already enormous and fixes a ton of bugs. I appreciate that you want to find more bugs, but this code needs to be merged. this PR is almost two weeks old, if you have a problem with any of the changes I have already made then we can talk about those, but any further fixes need to be follow ups. I'm not gonna keep adding more and more bug fixes in one PR forever. 😅

**Comment by jaaydenh** [comment]
@aslilac Totally fine moving more fixes to another PR. I was imaging the goal of this PR was to correct the frontend permissions for all the built-in site wide and organizations roles.

**Review by jaaydenh — APPROVED** [review]
Approving this to lock in the all the fixes so far. I will create additional issues for the other bugs that are out of scope.
