### PR TITLE
fix: stop extending API key access if OIDC refresh is available

### LINKED ISSUE #17070: bug: api key not refreshed when api key expired but oauth2 access token not
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

We have [a system](https://github.com/coder/coder/blob/a05c8fe03285ef231162cff04af241d3f25d4611/coderd/httpmw/apikey.go#L261-L261) that refreshes expired api keys backed by oauth2 if a refresh token is available.

However, in the case when the api key is expired but the oauth2 access token isn’t, the refresh logic is not triggered, and the api key `ExpiresAt` field is not updated.

Relavant check: 
https://github.com/coder/coder/blob/bbe7dacd354e023d9f9df060adb99c1b25c346c4/coderd/httpmw/apikey.go#L261

Early exit if `ExpiresAt` is not updated.
https://github.com/coder/coder/blob/bbe7dacd354e023d9f9df060adb99c1b25c346c4/coderd/httpmw/apikey.go#L319-L324

### Relevant Log Output

```shell

```

### Expected Behavior

I'd expect the `ExpiresAt` field to be updated when a valid OAuth2 access token is available.

### Steps to Reproduce

The way I triggered it is I manually updated the `ExpiresAt` field on an api key to the current time via a SQL query and then refreshed the Coder web UI.

### Environment

- Host OS: Linux
- Coder version: 2.20.2

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #17070

Cleans up our handling of APIKey expiration and OIDC to keep them separate concepts. For an OIDC-login APIKey, both the APIKey and OIDC link must be valid to login. If the OIDC link is expired and we have a refresh token, we will attempt to refresh.

OIDC refreshes do not have any effect on APIKey expiry.

https://github.com/coder/coder/issues/17070#issuecomment-2886183613 explains why this is the correct behavior.

### CODE REVIEW

File: coderd/httpmw/apikey.go [hunk 1]
```diff
@@ -292,37 +306,51 @@ func ExtractAPIKey(rw http.ResponseWriter, r *http.Request, cfg ExtractAPIKeyCon
...
+					Detail:  fmt.Sprintf("update user_link: %s.", err.Error()),
+				})
+			}
 		}
 	}
 
-	// Checking if the key is expired.
-	// NOTE: The `RequireAuth` React component depends on this `Detail` to detect when
-	// the users token has expired. If you change the text here, make sure to update it
-	// in site/src/components/RequireAuth/RequireAuth.tsx as well.
```
Comment (spikecurtis) [inline coderd/httpmw/apikey.go:318]: Note that `RequireAuth.tsx` was modified to not have this string match dependency in https://github.com/coder/coder/pull/9442

File: coderd/httpmw/apikey.go [hunk 2]
```diff
@@ -292,37 +306,51 @@ func ExtractAPIKey(rw http.ResponseWriter, r *http.Request, cfg ExtractAPIKeyCon
 				})
 			}
 
-			// If it is, let's refresh it from the provided config
+			if link.OAuthRefreshToken == "" {
+				return optionalWrite(http.StatusUnauthorized, codersdk.Response{
+					Message: SignedOutErrorMessage,
+					Detail:  fmt.Sprintf("%s session expired at %q.", friendlyName, link.OAuthExpiry.String()),
```
Comment (mafredri) [inline coderd/httpmw/apikey.go:312]: Suggestion: Including an instruction in the detail for how to resolve would be helpful for the user.

File: coderd/httpmw/apikey.go [hunk 3]
```diff
@@ -238,6 +238,17 @@ func ExtractAPIKey(rw http.ResponseWriter, r *http.Request, cfg ExtractAPIKeyCon
 		// Tracks if the API key has properties updated
 		changed = false
 	)
+
+	if key.ExpiresAt.Before(now) {
+		return optionalWrite(http.StatusUnauthorized, codersdk.Response{
+			Message: SignedOutErrorMessage,
+			Detail:  fmt.Sprintf("API key expired at %q.", key.ExpiresAt.String()),
+		})
+	}
```
Comment (mafredri) [inline coderd/httpmw/apikey.go:247]: Suggestion: Extract `now` assignment and move above the `var` declaration to relevant code-paths closer to each other.

File: coderd/httpmw/apikey.go [hunk 4]
```diff
@@ -258,7 +269,7 @@ func ExtractAPIKey(rw http.ResponseWriter, r *http.Request, cfg ExtractAPIKeyCon
 			})
 		}
 		// Check if the OAuth token is expired
-		if link.OAuthExpiry.Before(now) && !link.OAuthExpiry.IsZero() && link.OAuthRefreshToken != "" {
+		if !link.OAuthExpiry.IsZero() && link.OAuthExpiry.Before(now) {
```
Comment (mafredri) [inline coderd/httpmw/apikey.go:272]: Pondering: Not new behavior, but there doesn't seem to be any buffer between expiry and renewal (e.g. now - 10s), could this lead to bad user experiences where we approve the token and it expires right after?

**Review by mafredri — COMMENTED** [review]
Two small suggestions but the change makes sense to me. I can approve if need be but I'd feel better if @Emyrk also took a look, so deferring approval for now.

File: coderd/httpmw/apikey.go (hunk 3 above)
Comment (Emyrk) [reply coderd/httpmw/apikey.go:247]: Make sense to move this up

File: coderd/httpmw/apikey.go (hunk 4 above)
Comment (Emyrk) [reply coderd/httpmw/apikey.go:272]: It should be ok, because refresh tokens are still valid when the oauth code expires. So we do not need to be preemptive here

File: coderd/httpmw/apikey.go (hunk 2 above)
Comment (Emyrk) [reply coderd/httpmw/apikey.go:312]: I think the best you can do it log in again.

Which the frontend should redirect you to the login page.

File: coderd/httpmw/apikey_test.go [hunk 5]
```diff
@@ -508,6 +508,99 @@ func TestAPIKey(t *testing.T) {
...
+			r  = httptest.NewRequest("GET", "/", nil)
+			rw = httptest.NewRecorder()
+		)
+		r.Header.Set(codersdk.SessionTokenHeader, token)
+
+		oauthToken := &oauth2.Token{
+			AccessToken:  "wow",
+			RefreshToken: "moo",
+			Expiry:       dbtime.Now().AddDate(0, 0, 1),
+		}
```
Comment (Emyrk) [inline coderd/httpmw/apikey_test.go:537]:
```suggestion
		// Include a valid oauth token for refreshing. If this token is invalid,
		// it is difficult to tell an auth failure from a expired api key, or 
		// an expired oauth key.
		oauthToken := &oauth2.Token{
			AccessToken:  "wow",
			RefreshToken: "moo",
			Expiry:       dbtime.Now().AddDate(0, 0, 1),
		}
```

File: coderd/coderdtest/oidctest/idp.go [hunk 6]
```diff
@@ -794,6 +794,7 @@ func (f *FakeIDP) newToken(t testing.TB, email string, expires time.Time) string
 func (f *FakeIDP) newRefreshTokens(email string) string {
 	refreshToken := uuid.NewString()
 	f.refreshTokens.Store(refreshToken, email)
+	f.logger.Info(context.Background(), "new refresh token", slog.F("email", email), slog.F("token", refreshToken))
```
Comment (Emyrk) [inline coderd/coderdtest/oidctest/idp.go:797]: I'm guessing this was for debugging some other tests?

The tests written did not require the oidctest.

Regardless, I don't mind more logs in this code

**Review by Emyrk — APPROVED** [review]
This all makes sense to me :+1:

File: coderd/coderdtest/oidctest/idp.go (hunk 6 above)
Comment (spikecurtis) [reply coderd/coderdtest/oidctest/idp.go:797]: Yeah, this test was failing on an early revision of the change. I added the logs to diagnose, and left them in because they seemed useful.

**Comment by spikecurtis** [comment]
### Merge activity

* **May 19, 4:05 AM EDT**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/17878).

File: coderd/coderdtest/oidctest/idp.go (hunk 6 above)
Comment (Emyrk) [reply coderd/coderdtest/oidctest/idp.go:797]: :+1:
