### PR TITLE
fix: rate limit by user instead of IP for authenticated requests

### LINKED ISSUE #20857: bug: rate limit by user is broken
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

c.f. https://github.com/coder/dogfood/issues/216

~I'm marking this s1~ (@Kira-Pilot downgraded to S2) on the grounds that customers could be hitting the same issue as we are in dogfood ^^.

I modified some CI tests to set a rate limit, then put a break point in this code in `ratelimit.go`

```
			// Prioritize by user, but fallback to IP.
			apiKey, ok := r.Context().Value(apiKeyContextKey{}).(database.APIKey)
			if !ok {
				return httprate.KeyByIP(r)
			}
```

`ok` never ends up true.

The problem is that the rate limit middleware is set _before_ the middleware that extracts the API key, so the key is never available in the request context the rate limiter uses.

This has knock-on consequences that our `X-Coder-Bypass-Ratelimit` header for scale testing is always ignored.

### Relevant Log Output

```shell

```

### Expected Behavior

Rate limits are enforced per user, even if requests come from different IP addresses.

### Steps to Reproduce

Login, send requests.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kacpersaw**
## Problem

Rate limiting by user is broken (#20857). The rate limit middleware runs before API key extraction, so user ID is never in the request context. This causes:
- Rate limiting falls back to IP address for all requests
- `X-Coder-Bypass-Ratelimit` header for Owners is ignored (can't verify role without identity)

## Solution

Adds `PrecheckAPIKey`, a **root-level middleware** that fully validates the API key on every request (expiry, OIDC refresh, DB updates, role lookup) and stores the result in context. Added **once** at the root router — not duplicated per route group.

### Architecture

```
Request → Root middleware stack:
  → ExtractRealIP, Logger, ...
  → PrecheckAPIKey(...)              ← validates key, stores result, never rejects
  → HandleSubdomain(apiRateLimiter)  ← workspace apps now also benefit
  → CORS, CSRF

→ /api/v2 or /api/experimental:
  → apiRateLimiter                   ← reads prechecked result from context
  → route handlers:
    → ExtractAPIKeyMW                ← reuses prechecked data, adds route-specific logic
    → handler
```

### Key design decisions

| Decision | Rationale |
|---|---|
| **Full validation, not lightweight** | Spike's review: "the whole idea of a 'lightweight' extraction that skips security checks is fundamentally flawed." Only fully validated keys are used for rate limiting — expired/invalid keys fall back to IP. |
| **Structured error results** | `ValidateAPIKeyError` has a `Hard` flag that maps to `write` vs `optionalWrite`. Hard errors (5xx, OAuth refresh failures) surface even on optional-auth routes. Soft errors (missing/expired token) are swallowed on optional routes. |
| **Added once at the root** | Spike's review: "Why can't we add it once at the root?" Root placement means workspace app rate limiters also benefit. |
| **Skip prechecked when `SessionTokenFunc != nil`** | `workspaceapps/db.go` uses a custom `SessionTokenFunc` that extracts from `issueReq.SessionToken`. The prechecked result may have validated a different token. Falls back to `ValidateAPIKey` with the custom func. |
| **User status check stays in `ExtractAPIKey`** | Dormant activation is route-specific — `ValidateAPIKey` stores status but doesn't enforce it. |
| **Audience validation stays in `ExtractAPIKey`** | Depends on `cfg.AccessURL` and request path, uses `optionalWrite(403)` which depends on route config. |

### Changes

- **`coderd/httpmw/apikey.go`**:
  - New `ValidateAPIKey` function — extracted core validation logic, returns structured errors instead of writing HTTP responses
  - New `PrecheckAPIKey` middleware — calls `ValidateAPIKey`, stores result in `apiKeyPrecheckedContextKey`, never rejects
  - New types: `ValidateAPIKeyConfig`, `ValidateAPIKeyResult`, `ValidateAPIKeyError`, `APIKeyPrechecked`
  - Refactored `ExtractAPIKey` — consumes prechecked result from context (skipping redundant validation), falls back to `ValidateAPIKey` when no precheck available
  - Removed `ExtractAPIKeyForRateLimit` and `preExtractedAPIKey`
- **`coderd/httpmw/ratelimit.go`**: Rate limiter checks `apiKeyPrecheckedContextKey` first, then `apiKeyContextKey` fallback (for unit tests / workspace apps), then IP
- **`coderd/coderd.go`**: Added `PrecheckAPIKey` once at root `r.Use(...)` block, removed `ExtractAPIKeyForRateLimit` from `/api/v2` and `/api/experimental`
- **`coderd/coderd_test.go`**: `TestRateLimitByUser` regression test with `BypassOwner` subtest

Fixes #20857

### CODE REVIEW

File: coderd/coderd.go [hunk 1]
```diff
@@ -1054,6 +1054,11 @@ func New(options *Options) *API {
 
 		r.NotFound(func(rw http.ResponseWriter, _ *http.Request) { httpapi.RouteNotFound(rw) })
 		r.Use(
+			// Lightweight identification so the rate limiter can
+			// key by user ID instead of falling back to IP.
+			// No validation or side effects — that still happens
+			// in apiKeyMiddleware deeper in the route tree.
+			httpmw.ExtractAPIKeyForRateLimit(options.Database),
```
Comment (spikecurtis) [inline coderd/coderd.go]: I'm not a fan of adding this ad-hoc in multiple places. Why can't we add it once at the root?

File: coderd/httpmw/apikey.go [hunk 2]
```diff
@@ -149,6 +162,56 @@ func ExtractAPIKeyMW(cfg ExtractAPIKeyConfig) func(http.Handler) http.Handler {
...
+				next.ServeHTTP(rw, r)
+				return
+			}
+
+			pe := preExtractedAPIKey{key: *key}
+
+			// Fetch roles for bypass-header check. This is the
+			// same call ExtractAPIKey makes, so it will be skipped
+			// later when ExtractAPIKey sees the pre-extracted data.
+			subject, userStatus, err := UserRBACSubject(ctx, db, key.UserID, key.ScopeSet())
```
Comment (spikecurtis) [inline coderd/httpmw/apikey.go]: If we fail to fully validate the API key, but still use it for rate limiting, then a stolen key can be used to violate rate limits forever. In particular, if you get a hold of an expired owner key, then you can DoS the system.

Rate limits are a security feature, so this whole idea of a "lightweight" extraction that skips security checks is fundamentally flawed. We should extract and validate the API key on _every request_ if present, and store the results in the context. Then later middlewares can decide the consequences of missing or invalid keys (might be different, depending on the route, so it should be possible to distinguish missing from invalid).

**Review by spikecurtis — DISMISSED** [review]

File: coderd/httpmw/apikey.go [hunk 3]
```diff
@@ -149,157 +200,126 @@ func ExtractAPIKeyMW(cfg ExtractAPIKeyConfig) func(http.Handler) http.Handler {
...
+			// No token or invalid token — soft error.
+			return nil, &ValidateAPIKeyError{
+				Code:     http.StatusUnauthorized,
+				Response: resp,
+			}
+		}
+	}
+	if key == nil {
+		return nil, nil
 	}
```
Comment (jdomeracki-coder) [inline coderd/httpmw/apikey.go]: It seems that this condition can never be met ie. when `APIKeyFromRequest()` returns `ok == true` then value of `key` can't be `nil` 🤔 

This seems to contradict this comment:
https://github.com/coder/coder/pull/22049/changes#diff-309476c9621e252572e816ecc90fca9285c5712839587ef85c4656636b83aa43R75-R80

**Review by jdomeracki-coder — CHANGES_REQUESTED** [review]
Overall looks sound to me except the one comment left

**Review by jdomeracki-coder — APPROVED** [review]
Looks good to me from security point of view

File: coderd/httpmw/apikey.go [hunk 4]
```diff
@@ -312,43 +324,55 @@ func ExtractAPIKey(rw http.ResponseWriter, r *http.Request, cfg ExtractAPIKeyCon
...
-				return optionalWrite(http.StatusUnauthorized, codersdk.Response{
-					Message: SignedOutErrorMessage,
-					Detail:  fmt.Sprintf("%s session expired at %q. Try signing in again.", friendlyName, link.OAuthExpiry.String()),
-				})
+				return nil, &ValidateAPIKeyError{
+					Code: http.StatusUnauthorized,
+					Response: codersdk.Response{
+						Message: SignedOutErrorMessage,
+						Detail:  fmt.Sprintf("%s session expired at %q. Try signing in again.", friendlyName, link.OAuthExpiry.String()),
+					},
```
Comment (johnstcn) [inline coderd/httpmw/apikey.go:358]: Why is this a "soft" error but below is "hard"?

File: coderd/httpmw/apikey.go [hunk 5]
```diff
@@ -149,157 +199,119 @@ func ExtractAPIKeyMW(cfg ExtractAPIKeyConfig) func(http.Handler) http.Handler {
...
-				Message: SignedOutErrorMessage,
-				Detail:  "You must re-authenticate with the login provider.",
-			})
+			return nil, &ValidateAPIKeyError{
+				Code: http.StatusUnauthorized,
+				Response: codersdk.Response{
+					Message: SignedOutErrorMessage,
+					Detail:  "You must re-authenticate with the login provider.",
+				},
+			}
```
Comment (johnstcn) [inline coderd/httpmw/apikey.go:291]: Should this be a "hard" error?

Comment (kacpersaw) [reply coderd/httpmw/apikey.go:291]: No, missing UserLink means the OAuth identity link was deleted, equivalent to "session expired." On optional-auth routes this should be swallowed so the request proceeds unauthenticated. Matches the original optionalWrite here. The DB error right below (line 293) is correctly hard.

File: coderd/httpmw/apikey.go (hunk 4 above)
Comment (kacpersaw) [reply coderd/httpmw/apikey.go:358]: No refresh token = session expired naturally → soft, swallowed on optional routes. Refresh token exists but refresh failed = active failure (provider rejected it) → hard, always surfaced. Matches original optionalWrite vs write.

Comment (johnstcn) [reply coderd/httpmw/apikey.go:358]: Gotcha. Might be good to add a comment explaining that.

File: coderd/coderd_test.go [hunk 6]
```diff
@@ -416,3 +416,66 @@ func TestDERPMetrics(t *testing.T) {
...
+	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
+		ownerClient.URL.String()+"/api/v2/buildinfo", nil)
+	require.NoError(t, err)
+	req.Header.Set(codersdk.SessionTokenHeader, ownerClient.SessionToken())
+
+	resp, err := ownerClient.HTTPClient.Do(req)
+	require.NoError(t, err)
+	resp.Body.Close()
+	require.Equal(t, http.StatusTooManyRequests, resp.StatusCode,
+		"request should be rate limited")
```
Comment (johnstcn) [inline coderd/coderd_test.go]: suggest breaking this out into its own parallel sub-test

File: coderd/coderd_test.go [hunk 7]
```diff
@@ -416,3 +416,66 @@ func TestDERPMetrics(t *testing.T) {
...
+// This is a regression test for https://github.com/coder/coder/issues/20857
+func TestRateLimitByUser(t *testing.T) {
+	t.Parallel()
+
+	const rateLimit = 5
+
+	ownerClient := coderdtest.New(t, &coderdtest.Options{
+		APIRateLimit: rateLimit,
+	})
+	_ = coderdtest.CreateFirstUser(t, ownerClient)
```
Comment (johnstcn) [inline coderd/coderd_test.go]: We should also test with a member user and validate the behaviour (I don't think regular users can/should bypass the rate limit check?)

**Review by johnstcn — APPROVED** [review]
