### PR TITLE
fix(site): Do not show template params if there is no param to be shown

### LINKED ISSUE #7254: UI shows blank "Template params" section
i have the following terraform variable set to `sensitive`, meaning it shouldn't show in the UI. if there are no variables to be shown, the `Template params` section should be removed entirely.

```
provider "coder" {
  feature_use_managed_variables = false
}

variable "use_kubeconfig" {
  sensitive   = true
}
```

Screenshot 2023-04-23 at 6 29 52 PM

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix #7254

### CODE REVIEW

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx [hunk 1]
```diff
@@ -135,6 +135,10 @@ export const CreateWorkspacePageView: FC<
     })
 
   const isLoading = props.loadingTemplateSchema || props.loadingTemplates
+  // We only want to show schema that have redisplay_value equals true
+  const schemaToBeDisplayed = props.templateSchema?.filter(
+    (schema) => schema.redisplay_value,
+  )
```
Comment (Kira-Pilot) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx:141]: The linked bug ticket mentions that terraform values set to `sensitive` shouldn't appear in the UI. Does the `sensitive` key map to `redisplay_value` or is this something we have to check for separately?

**Review by Kira-Pilot — APPROVED** [review]
