### PR TITLE
fix: display build timings when all timings are loaded

### LINKED ISSUE #15273: Build timings: I have to refresh the page to see startup script timing
https://github.com/user-attachments/assets/cdae3b10-bb87-43be-97e1-2dd48dea535f

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
- [Refetch timings until script timings are present](https://github.com/coder/coder/commit/2181bec72b5334e5e15dc575d2234860be02920b)
- [Stay on loading state when agent script timings are empty](https://github.com/coder/coder/commit/b16fad165c8733c60150b0dfce5df73ab2669e36)

Fix https://github.com/coder/coder/issues/15273

### CODE REVIEW

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx [hunk 1]
```diff
@@ -157,13 +157,28 @@ export const WorkspaceReadyPage: FC<WorkspaceReadyPageProps> = ({
...
+		// Sometimes, the timings can be fetched before the agent script timings are
+		// done or saved in the database so we need to conditionally refetch the
+		// timings. To refetch the timings, I found the best way was to compare the
+		// expected amount of script timings with the current amount of script
+		// timings returned in the response.
+		refetchInterval: (data) => {
+			const expectedScriptTimingsCount = workspace.latest_build.resources
+				.flatMap((r) => r.agents)
+				.flatMap((a) => a?.scripts)
+				.filter((s) => s !== undefined).length;
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:176]: Tiny nit, but I want to say this can be cleaned up as:
```ts
const expectedScriptTimingsCount = workspace.latest_build.resources
  .flatMap((r) => r.agents)
  .flatMap((a) => a?.scripts ?? []).length;
```

File: site/src/api/queries/workspaceBuilds.ts [hunk 2]
```diff
@@ -58,17 +58,9 @@ export const infiniteWorkspaceBuilds = (
...
-	workspaceBuildId: string,
-	readyAgentsCount: number,
-) => {
+export const workspaceBuildTimings = (workspaceBuildId: string) => {
 	return {
-		queryKey: [
-			"workspaceBuilds",
-			workspaceBuildId,
-			"timings",
-			{ readyAgentsCount },
```
Comment (Parkreiner) [inline site/src/api/queries/workspaceBuilds.ts:70]: What was the `readyAgentCount` value doing before? I see that we were only using it for the query key, and now it's gone

**Review by buenos-nachos — APPROVED** [review]
Looks good! Had one question to make sure I'm properly understanding something, but it's tiny and shouldn't cause any problems

File: site/src/api/queries/workspaceBuilds.ts (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/api/queries/workspaceBuilds.ts:70]: It was to refetch the query when a new agent was marked as ready but it was very buggy and a bad decision on my end. The current refetch logic makes more sense and it is easier to follow.
