### PR TITLE
fix: flaky install.sh upgrade on OSX (zsh killed)

### LINKED ISSUE #2086: Coder gets zsh killed on macOS (not M1) after curl installing 0.6.2 AMD64 build
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.2

## Steps to Reproduce

curl -L https://coder.com/install.sh | sh

then run coder

## Expected

the list of coder commands

## Actual

markmilligan@mtmcoder ~ % coder
zsh: killed     coder

## Logs

After coder is installed:

`Installing v0.6.2 of the amd64 release from GitHub.

+ Reusing ~/.cache/coder/coder_0.6.2_darwin_amd64.zip
+ mkdir -p /usr/local
+ sudo mkdir -p /usr/local/bin
Password:
+ sudo unzip -d ~/.cache/coder -o ~/.cache/coder/coder_0.6.2_darwin_amd64.zip
Archive:  /Users/markmilligan/.cache/coder/coder_0.6.2_darwin_amd64.zip
  inflating: /Users/markmilligan/.cache/coder/LICENSE  
  inflating: /Users/markmilligan/.cache/coder/README.md  
  inflating: /Users/markmilligan/.cache/coder/coder  
+ sudo cp ~/.cache/coder/coder /usr/local/bin/coder
	Standalone release has been installed into /usr/local/bin/coder

Run Coder (temporary):
  coder server --dev

Or run a production deployment with PostgreSQL:
    CODER_PG_CONNECTION_URL="postgres://<username>@<host>/<database>?password=<password>" \
        coder server`

which coder

`markmilligan@mtmcoder ~ % which coder
/usr/local/bin/coder`

## Notes

I'm blocked

### PR DESCRIPTION
**Pull request by bpmct**
Fixes #2086. This likely has something to do with how MacOS trusts binaries

## To test

@misskniss @mark-theshark - would appreciate if you could confirm this fixes it

Broken:
```sh
# see the current version
coder --version
# install a different version of Coder (n+1 or n-1)
curl -L https://raw.githubusercontent.com/coder/coder/main/install.sh | sh -s -- --version=0.6.6
# run the binary
coder version
# [1]    48010 killed     coder
```

Fixed:
```sh
# see the current version
coder --version
# install a different version of Coder (n+1 or n-1)
curl -L https://raw.githubusercontent.com/coder/coder/bpmct/install-fixes/install.sh | sh -s -- --version=0.6.6
# run the binary
coder
# Coder v0.6.6+cbde8e8 Mon Jun 13 14:16:26 UTC 2022
# https://github.com/coder/coder/commit/cbde8e8b91097412b2ae0daa72d1b698b61584bc!
```

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -85,7 +85,8 @@ echo_latest_version() {
 
 echo_standalone_postinstall() {
 	cath <<EOF
-	Standalone release has been installed into $STANDALONE_INSTALL_PREFIX/bin/$STANDALONE_BINARY_NAME
+
+Standalone release has been installed into $STANDALONE_INSTALL_PREFIX/bin/$STANDALONE_BINARY_NAME
```
Comment (bpmct) [inline install.sh:89]: did a lil bit of formatting here

File: install.sh [hunk 2]
```diff
@@ -391,7 +392,16 @@ install_standalone() {
...
 	fi
 
-	"$sh_c" cp "$CACHE_DIR/coder" "$STANDALONE_INSTALL_PREFIX/bin/$STANDALONE_BINARY_NAME"
+	COPY_LOCATION="$STANDALONE_INSTALL_PREFIX/bin/$STANDALONE_BINARY_NAME"
+
+	# Remove the file if it already exists to
+	# avoid https://github.com/coder/coder/issues/2086
+	if [ -f "$COPY_LOCATION" ]; then
+    	"$sh_c" rm $COPY_LOCATION
+	fi
```
Comment (bpmct) [inline install.sh:401]: mv would also work here instead of cp.

https://developer.apple.com/forums/thread/130313?answerId=410704022#410704022

**Review by misskniss — APPROVED** [review]
That fixed it for me. Thanks @bpmct !
