### PR TITLE
fix: ensure wsproxy `MultiAgent` is closed when websocket dies

### LINKED ISSUE #11401: workspace proxy fails to proxy; error "ensure agent: subscribe agent"
(TODO: write a better issue title)

After https://github.com/coder/coder/pull/11366 was merged, I observed 502 errors when attempting to open vscode-web on my workspace:

```
Failed to proxy request to application: acquire agent conn: ensure agent: subscribe agent: write message: failed to write msg: WebSocket closed: failed to read frame header: EOF
```

and alternately, upon refresh:

```
Failed to proxy request to application: acquire agent conn: ensure agent: subscribe agent: write message: failed to write msg: failed to acquire lock: context canceled

```

Screenshot 2024-01-04 at 09 30 08

I observed this behaviour with:
- https://paris.fly.dev.coder.com (fly.io)
- https://sydney.fly.dev.coder.com (fly.io)

But not with:
- https://europe.dev.coder.com (GCP)
- https://sydney.dev.coder.com (GCP)
- https://brazil.dev.coder.com (GCP)
- https://sao-paulo.fly.dev.coder.com (fly.io)
- direct

After restarting paris.fly.dev.coder.com, the issue was apparently resolved.

Current theory is that there is a bug in the retry logic.

This appears to be supported by the following timeline of events:

- 2024-01-04T05:33:34.9677772Z 'paris-coder' fly.io wsproxy restarted
- 2024-01-04T05:34:08.0138014Z 'sydney-coder' fly.io wsproxy restarted
- 2024-01-04T05:34:17.3245364Z deployment.apps/coder restarted
- 2024-01-04T05:34:25.7908454Z 'sydney' GCP wsproxy restarted
- 2024-01-04T05:34:29.7072117Z 'sao-paulo-coder' fly.io wsproxy restarted
- 2024-01-04T05:34:33.5160577Z deployment "coder" successfully rolled out
- 2024-01-04T05:34:44.6466916Z 'europe' GCP wsproxy restarted
- 2024-01-04T05:35:02.7787815Z 'brazil' GCP wsproxy restarted

The Paris and Sydney wsproxies would have been connected to coderd at the time of the rollout restart happening; the restart would have interrupted the persistent websocket connection for those wsproxies while the others most likely were connected to the new coderd replicas.

Curiously, the workspace proxy healthcheck reported no issues:

```
curl https://sydney.fly.dev.coder.com/healthz-report
{"errors":null,"warnings":null}

```

The logs on the Paris fly.io wsproxy had already rotated, but we observed the following in the Sydney fly.io wsproxy's log output:

```
2024-01-04T05:34:06Z app[918577d4bd5538] syd [info]Started HTTP listener at http://0.0.0.0:3000
2024-01-04T05:34:06Z app[918577d4bd5538] syd [info]View the Web UI: https://sydney.fly.dev.coder.com
2024-01-04T05:34:08Z app[918577d4bd5538] syd [info]==> Logs will stream in below (press ctrl+c to gracefully exit):
2024-01-04T05:34:35Z app[918577d4bd5538] syd [info]2024-01-04 05:34:35.000 [warn]  net.workspace-proxy.servertailnet: broadcast server node to agents ...
2024-01-04T05:34:35Z app[918577d4bd5538] syd [info]    error= write message:
2024-01-04T05:34:35Z app[918577d4bd5538] syd [info]               github.com/coder/coder/v2/enterprise/wsproxy/wsproxysdk.(*remoteMultiAgentHandler).writeJSON
2024-01-04T05:34:35Z app[918577d4bd5538] syd [info]                   /home/runner/actions-runner/_work/coder/coder/enterprise/wsproxy/wsproxysdk/wsproxysdk.go:524
2024-01-04T05:34:35Z app[918577d4bd5538] syd [info]             - failed to write msg: WebSocket closed: failed to read frame header: EOF
```

### PR DESCRIPTION
**Pull request by coadler**
The `SingleTailnet` behavior only checked to see if the `MultiAgent` was
closed, but the websocket error was not being propogated into the
`MultiAgent`, causing it to never be swapped for a new working one.

Fixes https://github.com/coder/coder/issues/11401

Before:
```
Coder Workspace Proxy v0.0.0-devel+85ff030 - Your Self-Hosted Remote Development Platform
Started HTTP listener at http://0.0.0.0:3001

View the Web UI: http://127.0.0.1:3001

==> Logs will stream in below (press ctrl+c to gracefully exit):
2024-01-04 20:11:56.376 [warn]  net.workspace-proxy.servertailnet: broadcast server node to agents ...
    error= write message:
               github.com/coder/coder/v2/enterprise/wsproxy/wsproxysdk.(*remoteMultiAgentHandler).writeJSON
                   /home/coder/coder/enterprise/wsproxy/wsproxysdk/wsproxysdk.go:524
             - failed to write msg: WebSocket closed: failed to read frame header: EOF
```

After:
```
Coder Workspace Proxy v0.0.0-devel+12f1878 - Your Self-Hosted Remote Development Platform
Started HTTP listener at http://0.0.0.0:3001

View the Web UI: http://127.0.0.1:3001

==> Logs will stream in below (press ctrl+c to gracefully exit):
2024-01-04 20:26:38.545 [warn]  net.workspace-proxy.servertailnet: multiagent closed, reinitializing
2024-01-04 20:26:38.546 [erro]  net.workspace-proxy.servertailnet: reinit multi agent ...
    error= dial coordinate websocket:
               github.com/coder/coder/v2/enterprise/wsproxy/wsproxysdk.(*Client).DialCoordinator
                   /home/coder/coder/enterprise/wsproxy/wsproxysdk/wsproxysdk.go:454
             - failed to WebSocket dial: failed to send handshake request: Get "http://127.0.0.1:3000/api/v2/workspaceproxies/me/coordinate": dial tcp 127.0.0.1:3000: connect: connection refused
2024-01-04 20:26:38.587 [erro]  net.workspace-proxy.servertailnet: reinit multi agent ...
    error= dial coordinate websocket:
               github.com/coder/coder/v2/enterprise/wsproxy/wsproxysdk.(*Client).DialCoordinator
                   /home/coder/coder/enterprise/wsproxy/wsproxysdk/wsproxysdk.go:454
             - failed to WebSocket dial: failed to send handshake request: Get "http://127.0.0.1:3000/api/v2/workspaceproxies/me/coordinate": dial tcp 127.0.0.1:3000: connect: connection refusedhandshake request: Get "http://127.0.0.1:3000/api/v2/workspaceproxies/me/coordinate": dial tcp 127.0.0.1:3000: connect: connection refused
2024-01-04 20:26:40.446 [info]  net.workspace-proxy.servertailnet: successfully reinitialized multiagent  agents=0  took=1.900892615s
```

### CODE REVIEW

**Comment by coadler** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #11414** <a href="https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=stack-comment).

File: enterprise/wsproxy/wsproxysdk/wsproxysdk.go [hunk 1]
```diff
@@ -472,6 +472,11 @@ func (c *Client) DialCoordinator(ctx context.Context) (agpl.MultiAgentConn, erro
 		OnRemove:          func(agpl.Queue) { conn.Close(websocket.StatusGoingAway, "closed") },
 	}).Init()
 
+	go func() {
+		<-ctx.Done()
```
Comment (spikecurtis) [inline enterprise/wsproxy/wsproxysdk/wsproxysdk.go:476]: If I'm understanding this correctly, we're depending on the fact that the reader goroutine below cancels the context on a failed read.

I think we should _also_ tear down the multi-agent on a failed write of subscription messages. It's unlikely that we'd have a failure that leaves the connection half-open (e.g. for reads but not writes), but such things are possible and you don't want the proxy limping on unable to subscribe to new agents.

File: coderd/httpapi/websocket.go [hunk 2]
```diff
@@ -26,10 +26,10 @@ func Heartbeat(ctx context.Context, conn *websocket.Conn) {
...
-// Heartbeat loops to ping a WebSocket to keep it alive. It kills the connection
-// on ping failure.
+// Heartbeat loops to ping a WebSocket to keep it alive. It calls `exit` on ping
+// failure.
 func HeartbeatClose(ctx context.Context, exit func(), conn *websocket.Conn) {
-	ticker := time.NewTicker(30 * time.Second)
+	ticker := time.NewTicker(15 * time.Second)
 	defer ticker.Stop()
 
 	for {
```
Comment (spikecurtis) [inline coderd/httpapi/websocket.go:35]: <i class='graphite__hidden'>[Re: lines 43 to 43]<br/><br/></i>

Drop an INFO log here<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/coder/coder/11414?utm_source=unchanged-line-comment">Graphite</a>.</span>

**Review by spikecurtis — CHANGES_REQUESTED** [review]
Good work tracking down the bug!

I don't see any new tests though that will catch and prevent a regression, so please add

**Review by spikecurtis — APPROVED** [review]
