### PR TITLE
fix: handle urls with multiple slashes

### LINKED ISSUE #9877: Using double forward slash in URL returns HTML instead of performing an API request
The issue can be demonstrated easily:

```
~
❯ curl https://dev.coder.com/api/v2/buildinfo
{"external_url":"https://github.com/coder/coder/commit/6f0e2a79683d30c2974fbe9cda5802f0b7c47d44","version":"v2.1.5-devel+6f0e2a796","dashboard_url":"https://dev.coder.com","workspace_proxy":false}
```
vs
```
~
❯ curl https://dev.coder.com//api/v2/buildinfo
<!doctype html>

<!--
    ▄█▀    ▀█▄
     ▄▄ ▀▀▀  █▌   ██▀▀█▄          ▐█
 ▄▄██▀▀█▄▄▄  ██  ██      █▀▀█ ▐█▀▀██ ▄█▀▀█ █▀▀
█▌   ▄▌   ▐█ █▌  ▀█▄▄▄█▌ █  █ ▐█  ██ ██▀▀  █
     ██████▀▄█    ▀▀▀▀   ▀▀▀▀  ▀▀▀▀▀  ▀▀▀▀ ▀
  -->

<head>
```

This could probably be considered a non-bug, but I'm reporting it as a bug. It's not an uncommon scenario when concatenating URLs (ran into this in #9852) that we could handle. Perhaps we can sanitize all (or at least most) `//` to `/`?

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/9877

This PR introduces another middleware to rewrite URLs when multiple slashes are used.

Testing:

```
curl http://localhost:8080//api///v2/buildinfo
curl http://localhost:8080/api//v2/buildinfo
curl http://localhost:3000//api/////v2
curl http://localhost:3000/api//v2
```

### CODE REVIEW

File: coderd/coderd.go [hunk 1]
```diff
@@ -1731,3 +1732,29 @@ func ReadExperiments(log slog.Logger, raw []string) codersdk.Experiments {
...
+		var path string
+		rctx := chi.RouteContext(r.Context())
+		if rctx != nil && rctx.RoutePath != "" {
+			path = rctx.RoutePath
+		} else {
+			path = r.URL.Path
+		}
+
+		// Normalize multiple slashes to a single slash
+		newPath := multipleSlashesRe.ReplaceAllString(path, "/")
```
Comment (johnstcn) [inline coderd/coderd.go:1749]: nit, non-blocking: I wonder what the cost of a regex replace is versus iterating over the string once?

**Review by johnstcn — APPROVED** [review]
LGTM, but I'd like to get an OK from @mafredri as well. Multiple slashes is _technically_ valid in the case of `/api/v2/something/$FOO/bar` if `$FOO` can be an empty string. I don't see us needing this in the future, but I'm also no soothsayer.

File: coderd/coderd.go [hunk 2]
```diff
@@ -1731,3 +1732,29 @@ func ReadExperiments(log slog.Logger, raw []string) codersdk.Experiments {
...
+
+		// Apply the cleaned path
+		if rctx != nil {
+			rctx.RoutePath = newPath
+		}
+		r.URL.Path = newPath
```
Comment (mafredri) [inline coderd/coderd.go:1755]: In some cases we may overwrite RoutePath with Path, and vice-versa. Depending on which is missing. Is there any risk with this approach?

Looking at existing middleware, they seem to take a conditional approach for the assignment of both values: https://github.com/go-chi/chi/blob/e846b8304c769c4f1a51c9de06bebfaa4576bd88/middleware/strip.go#L24-L28

**Review by mafredri — APPROVED** [review]

**Comment by mafredri** [comment]
> Multiple slashes is _technically_ valid in the case of `/api/v2/something/$FOO/bar` if `$FOO` can be an empty string. I don't see us needing this in the future, but I'm also no soothsayer.

This is a good point @johnstcn, I strongly hope we will never end up there as it's a use-case that's better not being supported IMO 😄

File: coderd/coderd.go (hunk 2 above)
Comment (mtojek) [reply coderd/coderd.go]: I don't think it is a great deal, but let's keep it consistent :) Thanks for raising this

File: coderd/coderd.go (hunk 1 above)
Comment (mtojek) [reply coderd/coderd.go:1749]: I had that thought to fiddle with chars, but blindly assumed that regexp is safer and easier for devs to comprehend. Thanks for the comment anyway!
