### PR TITLE
fix: fix MetricsAggregator check for metric sameness

### LINKED ISSUE #11451: Prometheus metrics endpoint returns 500 instead of metrics
Our instances stopped to respond to metric requests:
```
❯ curl http://coder-service2.xxx:2112/
An error has occurred while serving metrics:

132 error(s) occurred:
* collected metric "agent_sessions_errors_total" { label:{name:"agent_name"  value:"main"}  label:{name:"error_type"  value:"output_io_copy"}  label:{name:"magic_type"  value:"ssh"}  label:{name:"pty"  value:"yes"}  label:{name:"template_name"  value:"debian-like-buildenv"}  label:{name:"username"  value:"xxx"}  label:{name:"workspace_name"  value:"muts"}  counter:{value:11}} was collected before with the same name and label values
* collected metric "agent_sessions_total" { label:{name:"agent_name"  value:"main"}  label:{name:"magic_type"  value:"ssh"}  label:{name:"pty"  value:"no"}  label:{name:"template_name"  value:"debian-like-buildenv"}  label:{name:"username"  value:"xxx"}  label:{name:"workspace_name"  value:"muts"}  counter:{value:6}} was collected before with the same name and label values
* collected metric "agent_sessions_total" { label:{name:"agent_name"  value:"main"}  label:{name:"magic_type"  value:"ssh"}  label:{name:"pty"  value:"yes"}  label:{name:"template_name"  value:"debian-like-buildenv"}  label:{name:"username"  value:"xxx"}  label:{name:"workspace_name"  value:"muts"}  counter:{value:18}} was collected before with the same name and label values
[...]
```

It seem to have happened with the upgrade to 2.6.0.

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #11451

A refactor of the Agent API passes metrics as protobufs, which include pointers to label name/value pairs.  The aggregator tested for sameness by doing a shallow compare of label values, which for different stats reports would compare unequal because the pointers would be different.

This fix does a deep compare.

While testing I also noted that we neglect to compare template names. This is unlikely to have caused any issue in practice, since the combination of username/workspace is unique, but in the context of comparing metric labels we should do the comparison.

If a user creates a workspace, deletes it, then recreates from a different template, we could in principle have reported incorrect stats for the old template.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* `main`
  * **#11508** <a href="https://app.graphite.dev/github/pr/coder/coder/11508?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: coderd/prometheusmetrics/aggregator_test.go [hunk 1]
```diff
@@ -111,6 +126,7 @@ func TestUpdateMetrics_MetricsDoNotExpire(t *testing.T) {
 
 func verifyCollectedMetrics(t *testing.T, expected []*agentproto.Stats_Metric, actual []prometheus.Metric) bool {
 	if len(expected) != len(actual) {
+		t.Logf("expected %d metrics, got %d", len(expected), len(actual))
```
Comment (mtojek) [inline coderd/prometheusmetrics/aggregator_test.go:129]: nit: won't `t.Logf` be spamming in build logs too much?

File: coderd/prometheusmetrics/aggregator.go [hunk 2]
```diff
@@ -68,7 +67,32 @@ type annotatedMetric struct {
...
+		am.templateName == req.templateName &&
+		am.Name == m.Name &&
+		labelsEqual(am.Labels, m.Labels)
+}
+
+func labelsEqual(a, b []*agentproto.Stats_Metric_Label) bool {
+	if len(a) != len(b) {
+		return false
+	}
+	am := make(map[string]string)
```
Comment (mtojek) [inline coderd/prometheusmetrics/aggregator.go:82]: nit: `am := make(map[string]string, len(a))`

File: coderd/prometheusmetrics/aggregator.go [hunk 3]
```diff
@@ -68,7 +67,32 @@ type annotatedMetric struct {
...
+		am[l.GetName()] = l.GetValue()
+	}
+	for _, l := range b {
+		v, ok := am[l.GetName()]
+		if !ok {
+			return false
+		}
+		if v != l.GetValue() {
+			return false
+		}
```
Comment (mtojek) [inline coderd/prometheusmetrics/aggregator.go:93]: nit: alternatively, unless empty values for labels are appropriate.

```
if v := am[l.GetName()]; v != l.GetValue() {
    return false
}
```

File: coderd/prometheusmetrics/aggregator.go [hunk 4]
```diff
@@ -68,7 +67,32 @@ type annotatedMetric struct {
...
+		am.Name == m.Name &&
+		labelsEqual(am.Labels, m.Labels)
+}
+
+func labelsEqual(a, b []*agentproto.Stats_Metric_Label) bool {
+	if len(a) != len(b) {
+		return false
+	}
+	am := make(map[string]string)
+	for _, l := range a {
```
Comment (mtojek) [inline coderd/prometheusmetrics/aggregator.go:83]: nit: this is personal, but I used to misread `l`, `I`, `1`, and `|`. Maybe `lbl`?

**Review by mtojek — APPROVED** [review]
Left a few nit-picks

File: coderd/prometheusmetrics/aggregator_test.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/prometheusmetrics/aggregator_test.go:129]: In local testing I never hit it when the test passed.

Comment (mtojek) [reply coderd/prometheusmetrics/aggregator_test.go:129]: yeah, I'm thinking about the failure scenario

File: coderd/prometheusmetrics/aggregator.go (hunk 4 above)
Comment (spikecurtis) [reply coderd/prometheusmetrics/aggregator.go:83]: Sounds like time to pick a different font 😝 !

File: coderd/prometheusmetrics/aggregator.go (hunk 3 above)
Comment (spikecurtis) [reply coderd/prometheusmetrics/aggregator.go:93]: Just looked this up, and Prometheus treats empty label values as equivalent to not existing. To handle that case I'd need to rework the initial check on length.

File: coderd/prometheusmetrics/aggregator_test.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/prometheusmetrics/aggregator_test.go:129]: if it's failing, then I want to know, spam be damned

**Comment by spikecurtis** [comment]
### Merge activity

* **Jan 9, 6:21 AM**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/11508).

**Review by Emyrk — COMMENTED** [review]
Good find

File: coderd/prometheusmetrics/aggregator_test.go (hunk 1 above)
Comment (Emyrk) [reply coderd/prometheusmetrics/aggregator_test.go:129]: Maybe unrelated but Zerolog has an easy "sampler" you can use for this kind of stuff: https://github.com/rs/zerolog?tab=readme-ov-file#log-sampling

Makes it easy to throw into some active loops while still controlling the spam.

Comment (mtojek) [reply coderd/prometheusmetrics/aggregator_test.go:129]: TIL 👍
