### PR TITLE
fix: reduce excessive logging when database is unreachable

### LINKED ISSUE #17045: bug: Excessive log generation when PostgreSQL database is offline
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When the Coder PostgreSQL database becomes unavailable, the Coder instance/pod generates an excessive amount of logs - approximately 500,000 lines per minute. The logs repeatedly show connection attempts and failures without any throttling or backoff mechanism.

The Example log pattern that repeats continuously shows up at least 40 lines every 1/100th of a second

Connection attempts continue at full speed with no reduction in frequency, generating approximately 500,000 log lines per minute, which could:

- Fill up disk space rapidly
- Make log analysis difficult
- Potentially impact system performance

- Log files can grow to unmanageable sizes
- Difficulty diagnosing other issues due to log flooding
- Potential disk space exhaustion

### Relevant Log Output

```shell
2025-03-21 17:16:24.504 [info]  coderd.pgcoord: closed incoming coordinate call while unhealthy  coordinator_id=62a74eaa-8477-451e-a81b-1bf4247b23bc  peer_id=e0fe7b54-8f5b-4568-be73-f43586e8b3f3
2025-03-21 17:16:24.504 [info]  coderd.servertailnet: obtained tailnet API v2+ client
2025-03-21 17:16:24.504 [info]  coderd.servertailnet: tailnet API v2+ connection lost
```

### Expected Behavior

When the DB is 'offline', the Tailnet process should have a mechanism where it can be 'silent' if the DB is unavailable or somewhat muted, to avoid running out of disk-space or memory depending on the storage.

The system should implement an exponential backoff or throttling mechanism to reduce log verbosity when the database is unavailable. Connection attempts should decrease in frequency over time.

**Possible Solution**
Implement a tapering retry mechanism in the database connection logic:

- Add exponential backoff for connection retries
- Reduce logging verbosity after initial connection failures
- Log only state changes (e.g., "database still unavailable after X attempts")

**Related Issues**
Similar to [Issue #11799](https://github.com/coder/coder/issues/11799)

### Steps to Reproduce

1. Have a running Coder deployment
2. tail the log, kubectl logs -f
3. Stop your PostgreSQL Service

### Environment

- Host OS: Irrelevant
- Coder version: 2.19.1+

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dannykopping**
Fixes #17045

### CODE REVIEW

File: coderd/coderd.go [hunk 1]
```diff
@@ -679,6 +679,10 @@ func New(options *Options) *API {
 		DERPFn:   api.DERPMap,
 		Logger:   options.Logger,
 		ClientID: uuid.New(),
+		DatabaseHealthcheckFn: func(ctx context.Context) error {
```
Comment (dannykopping) [inline coderd/coderd.go:682]: Self-review: I didn't want to pull the whole store into the dialer, so opted for this approach.

File: coderd/tailnet_test.go [hunk 2]
```diff
@@ -389,9 +426,36 @@ type agentWithID struct {
 	agent.Agent
 }
 
-func setupServerTailnetAgent(t *testing.T, agentNum int, opts ...tailnettest.DERPAndStunOption) ([]agentWithID, *coderd.ServerTailnet) {
```
Comment (dannykopping) [inline coderd/tailnet_test.go:392]: Self-review: had to refactor this a bit to allow existing options to be passed in or a healthcheck func. It's a bit janky but it keeps the scope of changes tight; open to other ideas.

File: codersdk/database.go [hunk 3]
```diff
@@ -0,0 +1,7 @@
+package codersdk
+
+import "errors"
+
+const DatabaseNotReachable = "database not reachable"
+
+var ErrDatabaseNotReachable = errors.New(DatabaseNotReachable)
```
Comment (dannykopping) [inline codersdk/database.go:7]: Self-review: not using anywhere yet, since we can't pass _actual_ sentinel errors around in this case, but for other use-cases it will be useful. Happy to remove, though.

File: provisionerd/provisionerd.go [hunk 4]
```diff
@@ -299,7 +300,10 @@ func (p *Server) acquireLoop() {
 			p.opts.Logger.Debug(ctx, "shut down before client (re) connected")
 			return
 		}
-		p.acquireAndRunOne(client)
+		err := p.acquireAndRunOne(client)
+		if err != nil && ctx.Err() == nil { // Only log if context is not done.
+			p.opts.Logger.Debug(ctx, "retrying to acquire job", slog.F("retry_in_ms", retrier.Delay.Milliseconds()), slog.Error(err))
```
Comment (dannykopping) [inline provisionerd/provisionerd.go:305]: Self-review: `acquireAndRunOne` already logs its own warning - specifically the `provisionerd was unable to acquire job` one is logged when the db is unreachable - so `Debug` is what felt most appropriate to me.

File: coderd/tailnet.go [hunk 5]
```diff
@@ -537,13 +539,20 @@ func NewMultiAgentController(ctx context.Context, logger slog.Logger, tracer tra
...
+	DatabaseHealthcheckFn func(ctx context.Context) error
 }
 
-func (a *InmemTailnetDialer) Dial(_ context.Context, _ tailnet.ResumeTokenController) (tailnet.ControlProtocolClients, error) {
+func (a *InmemTailnetDialer) Dial(ctx context.Context, _ tailnet.ResumeTokenController) (tailnet.ControlProtocolClients, error) {
+	if a.DatabaseHealthcheckFn != nil {
+		if err := a.DatabaseHealthcheckFn(ctx); err != nil {
+			return tailnet.ControlProtocolClients{}, xerrors.Errorf("%s: %w", codersdk.DatabaseNotReachable, err)
+		}
+	}
```
Comment (johnstcn) [inline coderd/tailnet.go:554]: I think we need to debounce this. I'm not sure how often we're going to be dialing but my gut tells me that if we call the healthcheck on each ping _synchronously_, we're going to be

1) adding latency to the dialer,
2) adding unwanted load to the database

File: tailnet/controllers.go [hunk 6]
```diff
@@ -1381,6 +1382,14 @@ func (c *Controller) Run(ctx context.Context) {
 				if xerrors.Is(err, context.Canceled) || xerrors.Is(err, context.DeadlineExceeded) {
 					return
 				}
+
+				// If the database is unreachable by the control plane, there's not much we can do, so we'll just retry later.
+				if strings.Contains(err.Error(), codersdk.DatabaseNotReachable) {
```
[the remark this answers is not in the document]
Comment (dannykopping) [reply tailnet/controllers.go:1387]: Alas no; it's not an actual error which is plumbed through. I'm going to try a different approach though because I agree this is smelly.

File: provisionerd/provisionerd.go [hunk 7]
```diff
@@ -290,7 +291,7 @@ func (p *Server) acquireLoop() {
 	defer p.wg.Done()
 	defer func() { close(p.acquireDoneCh) }()
 	ctx := p.closeContext
-	for {
+	for retrier := retry.New(10*time.Millisecond, 1*time.Second); retrier.Wait(ctx); {
```
Comment (dannykopping) [inline provisionerd/provisionerd.go:294]: NOTE: This is causing some flakiness currently, because jobs are timing out waiting for provisioners, now that we're introducing some backoff.

Looking into it...

File: tailnet/controllers.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (dannykopping) [reply tailnet/controllers.go]: Fixed in 4b0fd6a6c68642a9ae49408a40154ef6c4b8471b
This has the disadvantage of losing the original error details, but in this case it seems justified because we really only care about `codersdk.ErrDatabaseNotReachable` and need to conditionalize on that.

File: coderd/coderd.go (hunk 1 above)
Comment (dannykopping) [reply coderd/coderd.go:682]: Good idea 👍 will address.

File: coderd/tailnet_test.go [hunk 8]
```diff
@@ -365,6 +365,43 @@ func TestServerTailnet_ReverseProxy(t *testing.T) {
...
+		conn, release, err := serverTailnet.AgentConn(ctx, a.id)
+		t.Cleanup(release)
+		require.NoError(t, err)
+		assert.True(t, conn.AwaitReachable(ctx))
+	})
+
+	// If the healthcheck fails, we have no insight into this at this level.
+	// The dial against the control plane is retried, so we wait for the context to timeout as an indication that the
+	// healthcheck is performing as expected.
+	t.Run("Failing", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (dannykopping) [reply coderd/tailnet_test.go:390]: This felt wrong to me; thanks for pointing this out; it was a bit undercooked.

File: provisionerd/provisionerd.go [hunk 9]
```diff
@@ -299,7 +300,10 @@ func (p *Server) acquireLoop() {
 			p.opts.Logger.Debug(ctx, "shut down before client (re) connected")
 			return
 		}
-		p.acquireAndRunOne(client)
+		err := p.acquireAndRunOne(client)
+		if err != nil && ctx.Err() == nil { // Only log if context is not done.
+			p.opts.Logger.Debug(ctx, "retrying to acquire job", slog.F("retry_in_ms", retrier.Delay.Milliseconds()), slog.Error(err))
+		}
```
[the remark this answers is not in the document]
Comment (dannykopping) [reply provisionerd/provisionerd.go:313]: As I noticed myself when tests started flaking 🤦 already fixed in f92e85281333bb958e8500839c87069cdc8dbe7a

File: coderd/coderd.go [hunk 10]
```diff
@@ -675,10 +675,11 @@ func New(options *Options) *API {
...
 	dialer := &InmemTailnetDialer{
-		CoordPtr: &api.TailnetCoordinator,
-		DERPFn:   api.DERPMap,
-		Logger:   options.Logger,
-		ClientID: uuid.New(),
+		CoordPtr:            &api.TailnetCoordinator,
+		DERPFn:              api.DERPMap,
+		Logger:              options.Logger,
+		ClientID:            uuid.New(),
+		DatabaseHealthCheck: api.Database,
```
Comment (johnstcn) [inline coderd/coderd.go:682]: Nice :-)

File: coderd/tailnet.go [hunk 11]
```diff
@@ -534,16 +536,28 @@ func NewMultiAgentController(ctx context.Context, logger slog.Logger, tracer tra
...
+	// DatabaseHealthCheck is used to validate that the store is reachable.
+	DatabaseHealthCheck Pinger
 }
 
-func (a *InmemTailnetDialer) Dial(_ context.Context, _ tailnet.ResumeTokenController) (tailnet.ControlProtocolClients, error) {
+func (a *InmemTailnetDialer) Dial(ctx context.Context, _ tailnet.ResumeTokenController) (tailnet.ControlProtocolClients, error) {
+	if a.DatabaseHealthCheck != nil {
+		if _, err := a.DatabaseHealthCheck.Ping(ctx); err != nil {
+			return tailnet.ControlProtocolClients{}, xerrors.Errorf("%w: %v", codersdk.ErrDatabaseNotReachable, err)
+		}
```
Comment (johnstcn) [inline coderd/tailnet.go:558]: Would it make sense to return this error in the `Pinger`?

File: coderd/tailnet_test.go [hunk 12]
```diff
@@ -365,6 +368,44 @@ func TestServerTailnet_ReverseProxy(t *testing.T) {
...
+	dialer := &coderd.InmemTailnetDialer{
+		CoordPtr:            &coordPtr,
+		Logger:              logger,
+		ClientID:            uuid.UUID{5},
+		DatabaseHealthCheck: fch,
+	}
+	_, err := dialer.Dial(ctx, nil)
+
+	// Then: the error returned reflects the database has failed its healthcheck.
+	require.ErrorIs(t, err, codersdk.ErrDatabaseNotReachable)
```
Comment (spikecurtis) [inline coderd/tailnet_test.go:399]: 👍

**Review by spikecurtis — APPROVED** [review]

**Review by johnstcn — APPROVED** [review]

File: coderd/tailnet.go (hunk 11 above)
Comment (dannykopping) [reply coderd/tailnet.go:558]: It could, but I'd rather use this approach since it's more explicit.
