### PR TITLE
fix: agent disconnects from coordinator

### LINKED ISSUE #7428: tailnet coordinator periodically disconnects clients & agents
Agent disconnects started increasing substantially with #7345 

coordinator-agent

Logs: https://app.datadoghq.com/logs?query=%40caller%3A%2Fhome%2Frunner%2Fwork%2Fcoder%2Fcoder%2Ftailnet%2Fcoordinator.go%5C%3A%2A%20%40msg%3A%28%22unable%20to%20read%20agent%20update%3B%20closed%20conn%3F%22%20OR%20%22unable%20to%20read%20client%20update%3B%20closed%20conn%3F%22%20OR%20%22could%20not%20write%20nodes%20to%20connection%22%29&agg_q=%40fields.error%2C%40fields.error&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice&index=%2A&messageDisplay=inline&sort_m=%2C&sort_t=%2C&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=toplist&x_missing=true%2Ctrue&from_ts=1682961720000&to_ts=1683220920000&live=false

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #7428

### CODE REVIEW

File: tailnet/coordinator_test.go [hunk 1]
```diff
@@ -108,16 +116,28 @@ func TestCoordinator(t *testing.T) {
...
+		case <-ctx.Done():
+			t.Fatal("timed out")
+		}
 		sendClientNode(&tailnet.Node{})
 		clientNodes := <-agentNodeChan
 		require.Len(t, clientNodes, 1)
 
+		// wait longer than the internal wait timeout.
+		// this tests for regression of https://github.com/coder/coder/issues/7428
+		time.Sleep(tailnet.WriteTimeout * 3 / 2)
```
Comment (mafredri) [inline tailnet/coordinator_test.go:131]: Perhaps we should shorten the write timeout for tests so that we don't add a long delay? Even though we're running tests concurrently, if we have a lot of these it'll end up impacting test times.

**Review by mafredri — APPROVED** [review]

File: tailnet/coordinator.go [hunk 2]
```diff
@@ -238,6 +242,23 @@ func (t *TrackedConn) SendUpdates() {
...
+			// nhooyr.io/websocket has a bugged implementation of deadlines on a websocket net.Conn.  What they are
+			// *supposed* to do is set a deadline for any subsequent writes to complete, otherwise the call to Write()
+			// fails.  What nhooyr.io/websocket does is set a timer, after which it expires the websocket write context.
+			// If this timer fires, then the next write will fail *even if we set a new write deadline*.  So, after
+			// our successful write, it is important that we reset the deadline before it fires.
+			//
+			// SetWriteDeadline(0) is *supposed* to cancel the deadline, but again, nhooyr.io/websocket is bugged, and
+			// interprets 0 as the Golang time epoch, midnight on Jan 1, year 1, some two thousand years in the past.
+			// So, we set the write deadline an absurd amount of time in the future: 100 years.
+			err = t.conn.SetWriteDeadline(time.Now().Add(time.Hour * 24 * 365 * 100))
```
[the remark this answers is not in the document]
Comment (spikecurtis) [reply tailnet/coordinator.go:255]: I could have sworn that I followed references and didn't see the `t.IsZero()` check.  I guess I could have been looking at a really old version, or just losing my mind.

I'll fix to write 0.

File: tailnet/coordinator_test.go (hunk 1 above)
Comment (spikecurtis) [reply tailnet/coordinator_test.go:131]: I mean, I could.  

I could make the write timeout an option, and plumb it through.  However, when we run these tests in parallel, it can slow them down quite a bit, so I wouldn't want to set the timer too short, lest we get a flaky test under load. Maybe 1 second?  500 ms?

The current sleep is 7.5s, and I'd be able to shave it down to maybe 750ms, which doesn't really feel worth the trouble to me.

Comment (mafredri) [reply tailnet/coordinator_test.go:131]: To avoid plumbing, how about something like:

```go
var WriteTimeout = func() time.Duration {
	if inTest() {
		return 1 * time.Second
	}
	return 5 * time.Second
}()
```
?

Maybe that'd be `testutil.InTest()` or just an inline check in this package. I think that'd be fine for now, at some point we may want a better way to know all places where we may be modifying behavior for tests.

Perhaps not ideal since this would affect all tests. I'll this up to you.

**Review by coadler — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]
