### PR TITLE
fix(site): update `useAgentLogs` to make it more testable and add more tests

### LINKED ISSUE #644: flake: useAgentLogs
```
 FAIL src/modules/resources/useAgentLogs.test.ts
  ● useAgentLogs › clear logs when disabled to avoid duplicates

    expect(received).toHaveLength(expected)

    Expected length: 3
    Received length: 6
    Received array:  [{"created_at": "2025-05-16T03:52:06.102Z", "id": 0, "level": "info", "output": "Log 0", "source_id": ""}, {"created_at": "2025-05-16T03:52:06.102Z", "id": 1, "level": "info", "output": "Log 1", "source_id": ""}, {"created_at": "2025-05-16T03:52:06.102Z", "id": 2, "level": "info", "output": "Log 2", "source_id": ""}, {"created_at": "2025-05-16T03:52:06.102Z", "id": 0, "level": "info", "output": "Log 0", "source_id": ""}, {"created_at": "2025-05-16T03:52:06.102Z", "id": 1, "level": "info", "output": "Log 1", "source_id": ""}, {"created_at": "2025-05-16T03:52:06.102Z", "id": 2, "level": "info", "output": "Log 2", "source_id": ""}]

      40 | 		await server.connected;
      41 | 		server.send(JSON.stringify(generateLogs(3)));
    > 42 | 		expect(result.current).toHaveLength(3);
         | 		                       ^
      43 | 	});
      44 | });
      45 |

      at Object.toHaveLength (src/modules/resources/useAgentLogs.test.ts:42:26)
```

seen here: https://github.com/coder/coder/actions/runs/15060230530/job/42333911889

### PR DESCRIPTION
**Pull request by buenos-nachos**
Take 2
Closes https://github.com/coder/internal/issues/644

## Changes made
- Updated how `useAgentLogs` was defined to make it easier to inject specific data dependencies (basically making the hook more unit-testable)
- Simplified the hook API to limit the amount of scope of data it needs to work
- Added more test cases, and re-enabled the one test case we had previously disabled
- Extracted our mock websocket code into a separate file, and added more methods to it
- Updated all runtime code to accommodate new changes

### CODE REVIEW

File: site/src/hooks/useEmbeddedMetadata.ts [hunk 1]
```diff
@@ -229,13 +229,12 @@ export function makeUseEmbeddedMetadata(
...
 		);
 
-		// biome-ignore lint/correctness/useExhaustiveDependencies(manager.clearMetadataByKey): baked into containing hook
 		const stableMetadataResult = useMemo<UseEmbeddedMetadataResult>(() => {
 			return {
 				metadata,
 				clearMetadataByKey: manager.clearMetadataByKey,
 			};
-		}, [metadata]);
+		}, [manager, metadata]);
```
Comment (buenos-nachos) [inline site/src/hooks/useEmbeddedMetadata.ts:237]: A case where realistically, the value of `manager` won't ever change, but it technically can, since function parameters are reassignable. So better to add it to the dependencies for correctness

File: site/src/modules/resources/AgentRow.tsx [hunk 2]
```diff
@@ -76,24 +77,24 @@ export const AgentRow: FC<AgentRowProps> = ({
 		["starting", "start_timeout"].includes(agent.lifecycle_state) &&
 			hasStartupFeatures,
 	);
-	const agentLogs = useAgentLogs(agent, showLogs);
+	const agentLogs = useAgentLogs(agent.id, showLogs);
 	const logListRef = useRef<List>(null);
 	const logListDivRef = useRef<HTMLDivElement>(null);
-	const startupLogs = useMemo(() => {
-		const allLogs = agentLogs || [];
```
Comment (buenos-nachos) [inline site/src/modules/resources/AgentRow.tsx:86]: `agentLogs` is no longer nullable, so a bunch of logic can be removed

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 3]
```diff
@@ -1,60 +1,147 @@
 import { renderHook, waitFor } from "@testing-library/react";
```
Comment (buenos-nachos) [inline site/src/modules/resources/useAgentLogs.test.ts]: Enough changed with the test file that it honestly might not even be worth looking at the old version of the code

File: site/src/testHelpers/websockets.ts [hunk 4]
```diff
@@ -0,0 +1,140 @@
+import type { WebSocketEventType } from "utils/OneWayWebSocket";
+
+export type MockWebSocketPublisher = Readonly<{
+	publishMessage: (event: MessageEvent<string>) => void;
+	publishError: (event: Event) => void;
+	publishClose: (event: CloseEvent) => void;
+	publishOpen: (event: Event) => void;
+	readonly isConnectionOpen: boolean;
```
Comment (buenos-nachos) [inline site/src/testHelpers/websockets.ts]: Setup is 99% the same from the old file, just with the addition of this getter method

**Review by aslilac — COMMENTED** [review]
I think this mock WebSocket implementation needs some tests of its own, and is probably worth its own PR as well. @jaaydenh has been working on a similar refactor of some other tests that I think uses a copy of this WebSocket mock. It'd be nice to sync on that so that we don't duplicate effort, and _then_ we can get everyones tests reviewed. 😄

**Comment by buenos-nachos** [comment]
@aslilac Yeah, totally fair. I'll check with Jaayden

File: site/src/modules/resources/AgentRow.tsx [hunk 5]
```diff
@@ -76,24 +77,24 @@ export const AgentRow: FC<AgentRowProps> = ({
...
+			return agentLogs;
+		}
+		return [
+			...agentLogs,
+			{
 				id: -1,
 				level: "error",
 				output:
 					"Startup logs exceeded the max size of 1MB, and will not continue to be written to the database! Logs will continue to be written to the /tmp/coder-startup-script.log file in the workspace.",
 				created_at: new Date().toISOString(),
```
Comment (aslilac) [inline site/src/modules/resources/AgentRow.tsx]: we're leaking in here. I feel like this should be...
```suggestion
				created_at: agentLogs.at(-1).created_at,
```
since that's probably more "correct" and deterministic

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 6]
```diff
@@ -1,60 +1,195 @@
...
+import {
+	type CreateUseAgentLogsOptions,
+	createUseAgentLogs,
+} from "./useAgentLogs";
+
+const millisecondsInOneMinute = 60_000;
+
+function generateMockLogs(
+	logCount: number,
+	baseDate = new Date(),
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
	baseDate = new Date("Thu, 07 Aug 2025 21:38:12 GMT"),
```

as an example, how about just right now

File: site/src/modules/resources/AgentRow.tsx [hunk 7]
```diff
@@ -76,24 +77,24 @@ export const AgentRow: FC<AgentRowProps> = ({
...
-		const logs = [...allLogs];
-		if (agent.logs_overflowed) {
-			logs.push({
+	const startupLogs = useMemo<readonly WorkspaceAgentLog[]>(() => {
+		if (!agent.logs_overflowed) {
+			return agentLogs;
+		}
+		return [
+			...agentLogs,
+			{
```
Comment (aslilac) [inline site/src/modules/resources/AgentRow.tsx]: also I know it was already like this, but is shoving a log entry on the end really the best way to do this?

this `startupLogs` value eventually gets passed to `AgentLogs` below. what if we just passed `agentLogs` in unmodified and added an `overflowed` prop that shows the warning?

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 8]
```diff
@@ -1,60 +1,195 @@
...
+		const logs = generateMockLogs(10, new Date("september 9, 1999"));
+		const reversed = logs.toReversed();
+
+		for (const log of reversed) {
+			act(() => {
+				serverResult.current?.publishMessage(
+					new MessageEvent("message", { data: JSON.stringify([log]) }),
+				);
+			});
+		}
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
		await act(async () => {
			for (const log of reversed) {
				serverResult.current?.publishMessage(
					new MessageEvent("message", { data: JSON.stringify([log]) }),
				);
			}
		});
```

I'm still trying to build up an intuition for `act`, but I noticed while looking at the docs that they now promote calling it with an `async` function and `await`ing so I'm wondering if this patch makes sense.

reference: https://react.dev/reference/react/act

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 9]
```diff
@@ -1,60 +1,195 @@
...
+		const { serverResult, rerender } = mountHook({
+			initialAgentId: MockWorkspaceAgent.id,
+			// Start off disabled so that we can check that the callback is
+			// never called when there is no connection
+			enabled: false,
+			onError,
+		});
+
+		const errorEvent = new Event("error");
+		act(() => serverResult.current?.publishError(errorEvent));
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
		await act(() => serverResult.current?.publishError(errorEvent));
```

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 10]
```diff
@@ -1,60 +1,195 @@
...
+		expect(onError).not.toHaveBeenCalled();
+
+		rerender({ agentId: MockWorkspaceAgent.id, enabled: true });
+		act(() => serverResult.current?.publishError(errorEvent));
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
		await act(() => serverResult.current?.publishError(errorEvent));
```

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 11]
```diff
@@ -1,60 +1,195 @@
...
+		expect(onError).toHaveBeenCalledTimes(1);
+	});
+
+	it("Clears logs when hook becomes disabled (protection to avoid duplicate logs when hook goes back to being re-enabled)", async () => {
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
	// This is a protection to avoid duplicate logs when the hook is re-enabled
	it("Clears logs when hook becomes disabled", async () => {
```

File: site/src/modules/resources/useAgentLogs.ts [hunk 12]
```diff
@@ -1,47 +1,91 @@
-import { watchWorkspaceAgentLogs } from "api/api";
-import type { WorkspaceAgent, WorkspaceAgentLog } from "api/typesGenerated";
+import {
+	type WatchWorkspaceAgentLogsParams,
+	watchWorkspaceAgentLogs,
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.ts]: I wonder if rather than all of this factory stuff we could just mock `watchWorkspaceAgentLogs`. I think that might make it easier to get the `publisher` value too, but can't say for sure.

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 13]
```diff
@@ -1,60 +1,195 @@
...
+		const { hookResult, serverResult, rerender } = mountHook({
+			initialAgentId: MockWorkspaceAgent.id,
+		});
+
+		// Send initial logs so that we have something to clear out later
+		const initialLogs = generateMockLogs(3, new Date("april 5, 1997"));
+		const initialEvent = new MessageEvent("message", {
+			data: JSON.stringify(initialLogs),
+		});
+		act(() => serverResult.current?.publishMessage(initialEvent));
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
		await act(async () => serverResult.current?.publishMessage(initialEvent));
```

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 14]
```diff
@@ -1,60 +1,195 @@
...
+			rerender({ agentId: MockWorkspaceAgent.id, enabled: false });
+			await waitFor(() => expect(hookResult.current).toHaveLength(0));
+
+			// Re-enable the hook and send new logs
+			rerender({ agentId: MockWorkspaceAgent.id, enabled: true });
+			const newLogs = generateMockLogs(3, new Date(md));
+			const newEvent = new MessageEvent("message", {
+				data: JSON.stringify(newLogs),
+			});
+			act(() => serverResult.current?.publishMessage(newEvent));
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts]:
```suggestion
			await act(async () => serverResult.current?.publishMessage(newEvent));
```

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx [hunk 15]
```diff
@@ -308,12 +308,7 @@ type AgentLogsContentProps = {
 };
 
 const AgentLogsContent: FC<AgentLogsContentProps> = ({ agent }) => {
-	const logs = useAgentLogs(agent, true);
-
-	if (!logs) {
-		return <Loader />;
-	}
-
+	const logs = useAgentLogs(agent.id, true);
```
Comment (aslilac) [inline site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx]: another "I know it was already like this" moment but nondescript booleans like this are dreadful. I'd love to see this argument go from `boolean` to `{ enabled: boolean = true }` (similar to what react-query does, default to on, optimized for the happy path)

**Review by aslilac — COMMENTED** [review]
I'd love to have a story for the `logs_overflowed` state

(sorry if this is asking a lot, I just keep seeing things that'd be nice to clean up everywhere)

File: site/src/modules/resources/useAgentLogs.test.ts [hunk 16]
```diff
@@ -1,60 +1,195 @@
...
+
+	// Note: the `current` property is only "halfway" readonly; the value is
+	// readonly, but the key is still mutable
+	hookResult: { current: readonly WorkspaceAgentLog[] };
+}>;
+
+function mountHook(options: MountHookOptions): MountHookResult {
+	const { initialAgentId, enabled = true, onError = jest.fn() } = options;
+
+	const serverResult: ServerResult = { current: undefined };
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.test.ts:57]: if we stick with this we could just use `createRef` and `React.RefObject<MockWebSocketServer>` instead of making our own type here

Comment (buenos-nachos) [reply site/src/modules/resources/useAgentLogs.test.ts:57]: Those are not the same. `createRef` is for interfacing with class components, and creates a mutable object that's still part of React's data flow

This setup is ejecting a value created during React's lifecycle into an outside function. React has absolutely no idea that this exists, but it's how a lot of React testing tools work under the hood. I get the aversion to having more bespoke types, but switching to the built-in type would be lying about it actually is

**Comment by buenos-nachos** [comment]
@aslilac I think I have this pretty close to done:
- The whole hook setup was changed to remove the curried function for `useAgentLogs`, and the tests have been swapped to `jest.spyOn`
- The actual components have been updated to be aware of an `overflowed` property for `AgentLogs`, and there's a story in place to show the state

The only thing I'm not super clear on is how to style the overflowed UI. I really think that the overflow styling should be represented as a tooltip. The actual message is super short, so we want to constrain the width pretty aggressively for good typography, and a tooltip naturally lends itself well to those constraints without affecting the layout of the main container

The only thing is, beyond feeling like it should be a tooltip, I feel pretty lost. I tried going through Storybook, but their search is so bad that it made it hard to see if we have any components that have the "alert tooltip" behavior already. Do you know of any existing components that fit the bill?

File: site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx [hunk 17]
```diff
@@ -308,24 +307,20 @@ type AgentLogsContentProps = {
...
-	const logs = useAgentLogs(agent, true);
-
-	if (!logs) {
-		return <Loader />;
-	}
-
+	const logs = useAgentLogs({ agentId: agent.id });
 	return (
 		<AgentLogs
+			overflowed={false}
```
Comment (aslilac) [inline site/src/pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx]: is this actually correct? it seems like an overflow would be just as possible here

File: site/src/modules/resources/AgentRow.tsx [hunk 18]
```diff
@@ -312,7 +295,8 @@ export const AgentRow: FC<AgentRowProps> = ({
 									width={width}
 									css={styles.startupLogs}
 									onScroll={handleLogScroll}
-									logs={startupLogs.map((l) => ({
+									overflowed={true}
```
Comment (aslilac) [inline site/src/modules/resources/AgentRow.tsx]: shouldn't this be 
```suggestion
									overflowed={agent.logs_overflowed}
```
?

File: site/src/hooks/useEmbeddedMetadata.ts (hunk 1 above)
Comment (aslilac) [reply site/src/hooks/useEmbeddedMetadata.ts:237]: the extra dep is way nicer than the excessively long `biome-ignore` comment. good tradeoff.

**Review by aslilac — COMMENTED** [review]
I don't think the `overflowed` prop is being set correctly, but otherwise this is looking like a huge improvement.

File: site/src/components/Badge/Badge.stories.tsx [hunk 19]
```diff
@@ -21,6 +21,24 @@ export const Warning: Story = {
...
+	args: {
+		variant: "info",
+	},
+};
+
+export const Green: Story = {
+	args: {
+		variant: "green",
+	},
+};
```
Comment (buenos-nachos) [inline site/src/components/Badge/Badge.stories.tsx:40]: Some of our styling for the `Badge` component was jacked, and we just never caught it because we never made stories for the variants

File: site/src/components/Latency/Latency.tsx [hunk 20]
```diff
@@ -34,18 +33,17 @@ export const Latency: FC<LatencyProps> = ({
...
 			<Tooltip title={notAvailableText}>
-				<>
-					<span css={{ ...visuallyHidden }}>{notAvailableText}</span>
-
-					<CircleHelpIcon className="ml-auto size-icon-sm" style={{ color }} />
-				</>
+				<span className="ml-auto">
+					<span className="sr-only">{notAvailableText}</span>
+					<CircleHelpIcon className="size-icon-sm" style={{ color }} />
+				</span>
```
Comment (buenos-nachos) [inline site/src/components/Latency/Latency.tsx]: Biome kept hitting me with a linter violation that this fragment was useless, even though it's needed for the MUI types. The fix script also refused to run. Figured splitting things up like this was a decent compromise

File: site/src/components/Latency/Latency.tsx [hunk 21]
```diff
@@ -34,18 +33,17 @@ export const Latency: FC<LatencyProps> = ({
 		const notAvailableText = "Latency not available";
 		return (
 			<Tooltip title={notAvailableText}>
-				<>
-					<span css={{ ...visuallyHidden }}>{notAvailableText}</span>
-
-					<CircleHelpIcon className="ml-auto size-icon-sm" style={{ color }} />
-				</>
+				<span className="ml-auto">
```
Comment (aslilac) [inline site/src/components/Latency/Latency.tsx]: why does it need `margin-left: auto`?

File: site/src/modules/resources/AgentLogs/AgentLogs.tsx [hunk 22]
```diff
@@ -1,178 +1,189 @@
...
-					let icon: JSX.Element;
-					// If no icon is specified, we show a deterministic
-					// colored circle to identify unique scripts.
-					if (logSource.icon) {
-						icon = (
-							<img
-								src={logSource.icon}
-								alt=""
-								width={14}
-								height={14}
```
Comment (aslilac) [inline site/src/modules/resources/AgentLogs/AgentLogs.tsx:63]: why remove these?

File: site/src/modules/resources/useAgentLogs.ts [hunk 23]
```diff
@@ -1,47 +1,73 @@
...
-				"Unable to watch the agent logs",
+				"Unable to watch agent logs",
 				"Please try refreshing the browser",
 			);
 			socket.close();
 		});
 
-		return () => {
-			socket.close();
-		};
```
Comment (aslilac) [inline site/src/modules/resources/useAgentLogs.ts]: can we revert this? it's clearer that the longer form doesn't return anything meaningful, whereas the second version returns whatever `close()` returns.

Comment (buenos-nachos) [reply site/src/modules/resources/useAgentLogs.ts]: I prefer the changed version aesthetically (and the type signature for useEffect ensures that there won't ever be any problems), but I just reverted it

File: site/src/modules/resources/AgentLogs/AgentLogs.tsx (hunk 22 above)
Comment (buenos-nachos) [reply site/src/modules/resources/AgentLogs/AgentLogs.tsx:63]: They're not removed – they got turned into the `size-3.5` class. This is a native HTML element – `width` and `height` aren't special props, so we can afford to just turn them into normal Tailwind

File: site/src/components/Latency/Latency.tsx (hunk 21 above)
Comment (buenos-nachos) [reply site/src/components/Latency/Latency.tsx]: I had it because the previous icon had it. Let me see if it's safe to remove

Comment (buenos-nachos) [reply site/src/components/Latency/Latency.tsx]: Okay, it wasn't a drop-in replacement, but I updated the component and where it was used, and added an extra story. The margin values never should've been baked into the component, but now it's fully gone

The component itself is still a bit janky, but (1) this PR has already ballooned in scope from just trying to fix a simple flake, and (2) I'm legitimately running out of time to squeeze a bunch of stuff in before vacation. It's already midnight – I'm not done for today yet

I fully understand if you still have problems with the component, but what we have now should still be an improvement. We can take care of the rest of the problems in a separate PR

**Review by aslilac — APPROVED** [review]
