### PR TITLE
fix(site): Fix login flow

### LINKED ISSUE #6224: bug: incorrect login attempt via built-in auth takes user back to login screen
running `0.17.3`. while attempting to login via built-in auth, i incorrectly entered my username/password. i was redirected to this screen:

image

this did not tell me that my login attempt was unsuccessful. i then clicked back into `Email and password`, where it showed me the unsuccessful message:

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/6224

https://user-images.githubusercontent.com/3165839/220407831-b6924eff-ed10-4559-9a24-8ec9213416ed.mov

### CODE REVIEW

File: site/src/components/SignInForm/SignInForm.tsx [hunk 1]
```diff
@@ -110,12 +98,16 @@ export const SignInForm: FC<React.PropsWithChildren<SignInFormProps>> = ({
         {loginPageTranslation.t("signInTo")}{" "}
         <strong>{commonTranslation.t("coder")}</strong>
       </h1>
+      <Maybe condition={error !== undefined}>
+        <div className={styles.error}>
+          <AlertBanner severity="error" error={error} />
+        </div>
+      </Maybe>
```
Comment (Kira-Pilot) [inline site/src/components/SignInForm/SignInForm.tsx:105]: 👍 good simplification

File: site/src/hooks/usePermissions.ts [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
+  const { data } = authState.context
 
-  if (!permissions) {
-    throw new Error("Permissions are not loaded yet.")
+  if (isAuthenticated(data)) {
+    return data.permissions
   }
 
-  return permissions
+  throw new Error("User is not authenticated.")
```
Comment (Kira-Pilot) [inline site/src/hooks/usePermissions.ts:12]: A lot of these hooks look very similar. Perhaps down the road (not in this PR) we could consolidate them into 1 hook that takes an arg.

**Review by Kira-Pilot — APPROVED** [review]
Great cleanup and appreciate the video!
