### PR TITLE
Filter query: has-agent connecting, connected, disconnected, timeout

### LINKED ISSUE #4679: Surface agent status in workspaces page
As a Coder admin looking for failed workspaces, I can currently use `status:failed` (https://coder.example.com/workspaces?filter=status%3Afailed) to detect and troubleshoot users' broken workspaces.

However, it is not as easy to find workspaces that appear to be "running," yet an agent is stuck in "connecting" or "disconnected." Can we make this query-able from the "workspaces" page? For example: `status: running has-agent:disconnected`

## Related

- #4678

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/4679

This PR transforms the logic from [workspace agent](https://github.com/coder/coder/blob/main/coderd/workspaceagents.go#L724-L750) into a database query. It isn't straightforward as it needs to project data from workspace resources and workspace agents, then map `has-agent` conditions (connecting, timeout, disconnected, connected) onto db fields.

Notice: `has-agent:` filter only works for workspaces in the `start` transition.

An alternative approach, which isn't a spaghetti db query, would assume a query filter/[mapping](https://github.com/coder/coder/blob/main/coderd/workspaceagents.go#L724-L750) applied in the application layer, on received workspaces query results from DB.

### CODE REVIEW

File: coderd/database/queries/workspaces.sql [hunk 1]
```diff
@@ -161,6 +178,30 @@ WHERE
...
+					latest_build.first_connected_at IS NULL AND (latest_build.created_at + latest_build.connection_timeout_seconds * INTERVAL '1 second' < NOW())
+				WHEN @has_agent = 'connecting' THEN
+			    	latest_build.first_connected_at IS NULL
+				WHEN @has_agent = 'disconnected' THEN
+					(
+						latest_build.disconnected_at IS NOT NULL AND
+						latest_build.disconnected_at > latest_build.last_connected_at
+					) OR (
+						latest_build.last_connected_at IS NOT NULL AND
+						latest_build.last_connected_at + 6 * INTERVAL '1 second' < NOW() -- FIXME agentInactiveDisconnectTimeout = 6
```
Comment (coadler) [inline coderd/database/queries/workspaces.sql:197]: I think you could just do `INTERVAL '6 seconds'` instead. Also, is this continually updated?

File: coderd/workspaces_test.go [hunk 2]
```diff
@@ -824,6 +824,151 @@ func TestWorkspaceFilterManual(t *testing.T) {
...
+		ctx, cancel := context.WithTimeout(context.Background(), testutil.WaitMedium)
+		defer cancel()
+
+		testutil.Eventually(ctx, t, func(ctx context.Context) (done bool) {
+			workspaces, err := client.Workspaces(ctx, codersdk.WorkspaceFilter{
+				FilterQuery: fmt.Sprintf("has-agent:%s", "timeout"),
+			})
+			if !assert.NoError(t, err) {
+				return false
+			}
```
Comment (coadler) [inline coderd/workspaces_test.go:968]: I don't think this works as expected. Even if it returns false, the whole test would fail. I think you could just use `require.NoError` instead

File: coderd/database/queries/workspaces.sql [hunk 3]
```diff
@@ -44,22 +44,39 @@ FROM
 	workspaces
 LEFT JOIN LATERAL (
 	SELECT
+	    build_number,
+	    workspace_builds.job_id,
```
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: I adjusted the entire .sql file.

File: coderd/workspaces_test.go (hunk 2 above)
Comment (mtojek) [reply coderd/workspaces_test.go]: Fixed.

File: coderd/database/queries/workspaces.sql (hunk 1 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql:197]: The interval should be passed from [agentInactiveDisconnectTimeout](https://github.com/coder/coder/blob/2b6c229e4e2e94776500fe366b538afb6c24c199/coderd/coderd.go#L78) for every `Workspaces()`, at least for ones using `HasAgent`.

I set it temporarily to [6 seconds](https://github.com/coder/coder/blob/2b6c229e4e2e94776500fe366b538afb6c24c199/coderd/coderd.go#L118-L123) to show the overall PR idea. I can improve it now, but I'm not convinced as it introduces a strict dependency on Coder configuration.

Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: All FIXMEs are implemented now.

File: coderd/database/databasefake/databasefake.go [hunk 4]
```diff
@@ -871,6 +871,54 @@ func (q *fakeQuerier) GetAuthorizedWorkspaces(ctx context.Context, arg database.
...
+				case "connecting":
+					hasAgentMatched = !wa.FirstConnectedAt.Valid
+				case "disconnected":
+					hasAgentMatched = (wa.DisconnectedAt.Valid && wa.DisconnectedAt.Time.After(wa.LastConnectedAt.Time)) ||
+						(wa.LastConnectedAt.Valid && wa.LastConnectedAt.Time.Add(time.Duration(arg.AgentInactiveDisconnectTimeout)*time.Second).Before(database.Now()))
+				case "timeout":
+					hasAgentMatched = !wa.FirstConnectedAt.Valid &&
+						wa.CreatedAt.Add(time.Duration(wa.ConnectionTimeoutSeconds)*time.Second).Before(database.Now())
+				}
+				break // only 1 agent is expected
```
Comment (mafredri) [inline coderd/database/databasefake/databasefake.go:914]: This comment confused me a bit at first, but then I noticed that we'll always only check one agent here. Should this be something like this instead?

```suggestion
				if hasAgentMatched {
					break // only 1 agent is required to match
				}
```

File: coderd/database/queries/workspaces.sql [hunk 5]
```diff
@@ -161,17 +178,41 @@ WHERE
...
+					latest_build.first_connected_at IS NULL AND (latest_build.created_at + latest_build.connection_timeout_seconds * INTERVAL '1 second' < NOW())
+				WHEN @has_agent = 'connecting' THEN
+					latest_build.first_connected_at IS NULL
+				WHEN @has_agent = 'disconnected' THEN
+					(
+						latest_build.disconnected_at IS NOT NULL AND
+						latest_build.disconnected_at > latest_build.last_connected_at
+					) OR (
+						latest_build.last_connected_at IS NOT NULL AND
+						latest_build.last_connected_at + INTERVAL '1 second' * @agent_inactive_disconnect_timeout :: bigint < NOW()
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:197]: Suggestion: Rename to `@agent_inactive_disconnect_timeout_seconds` to make the intent clear in the generated code.

File: coderd/database/queries/workspaces.sql [hunk 6]
```diff
@@ -44,22 +44,39 @@ FROM
...
 		provisioner_jobs.updated_at,
 		provisioner_jobs.canceled_at,
 		provisioner_jobs.completed_at,
-		provisioner_jobs.error
+		provisioner_jobs.error,
+		workspace_agents.created_at,
+		workspace_agents.disconnected_at,
+		workspace_agents.first_connected_at,
+		workspace_agents.last_connected_at,
+		workspace_agents.connection_timeout_seconds
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:59]: Suggestion: renaming these, e.g. like `workspace_agents.created_at AS agent_created_at` would make the rest of the query more clear. I was a bit confused at first when reading `latest_build.created_at`, etc.

Alternatively: These could also precompute the agent states, like `(first_connect IS NULL AND ...) AS agent_timeout`

File: coderd/database/queries/workspaces.sql [hunk 7]
```diff
@@ -161,17 +178,41 @@ WHERE
...
+				WHEN @has_agent = 'disconnected' THEN
+					(
+						latest_build.disconnected_at IS NOT NULL AND
+						latest_build.disconnected_at > latest_build.last_connected_at
+					) OR (
+						latest_build.last_connected_at IS NOT NULL AND
+						latest_build.last_connected_at + INTERVAL '1 second' * @agent_inactive_disconnect_timeout :: bigint < NOW()
+					)
+				WHEN @has_agent = 'connected' THEN
+					latest_build.last_connected_at IS NOT NULL
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:200]: Should this case also verify that the state isn't actually `disconnected` either via timeout or `disonnected_at`?

File: coderd/database/queries/workspaces.sql [hunk 8]
```diff
@@ -161,17 +178,41 @@ WHERE
...
+	-- Filter by agent status
+	-- has-agent: is only applicable for workspaces in "start" transition. Stopped and deleted workspaces don't have agents.
+	AND CASE
+		WHEN @has_agent :: text != '' THEN
+			latest_build.transition = 'start'::workspace_transition
+			AND CASE
+				WHEN @has_agent = 'timeout' THEN
+					latest_build.first_connected_at IS NULL AND (latest_build.created_at + latest_build.connection_timeout_seconds * INTERVAL '1 second' < NOW())
+				WHEN @has_agent = 'connecting' THEN
+					latest_build.first_connected_at IS NULL
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:190]: This could also return true for an agent that has timed out?

File: coderd/database/queries/workspaces.sql (hunk 5 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: Good call, fixed.

File: coderd/database/queries/workspaces.sql (hunk 6 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: Done

File: coderd/database/databasefake/databasefake.go (hunk 4 above)
Comment (mafredri) [reply coderd/database/databasefake/databasefake.go:914]: I guess my question is, what happens when there are multiple agent, and with different statuses? Let's say we want workspaces with timed out agents. We could have one workspace with two agents where the first is connected and the second is timed out. In this case, I'd expect this workspace to show up in the search result but we'd only be checking the first one, i.e. connected.

File: coderd/database/queries/workspaces.sql (hunk 8 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: I guess that this is also possible. I included the extra condition.

File: coderd/database/queries/workspaces.sql (hunk 7 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: I extended the condition.

Frankly speaking,, I'm thinking about refactoring that part of the code and creating an extra "runtime" column for `agent status`. I'm not quite sure if it's possible to use SQL clauses to reflect this [logic](https://github.com/coder/coder/blob/main/coderd/workspaceagents.go#L724-L750). I really wouldn't like to create functions...

File: coderd/database/databasefake/databasefake.go (hunk 4 above)
Comment (mtojek) [reply coderd/database/databasefake/databasefake.go:904]: Let me refer to the SQL implementation. This is the order:

```
	ORDER BY
		build_number DESC,
		agent_last_connected_at ASC,
		agent_first_connected_at ASC
	LIMIT
		1
```

So, in practice, the statement will only consider that last build and look for the last connected agent. To break this assumption we would need a build job will multiple agents. Please correct me if I'm wrong, as this is the core part of this PR :)

File: coderd/database/queries/workspaces.sql (hunk 7 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: I guess that you can take a look at the CASE logic implementation one more time as I've rewritten it to look similar to the Go code.

File: coderd/database/queries/workspaces.sql (hunk 8 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: See above.

File: coderd/database/databasefake/databasefake.go (hunk 4 above)
Comment (mafredri) [reply coderd/database/databasefake/databasefake.go:904]: Ah right. So IMO it makes sense we're looking at the latest build, but we should probably consider all agents belonging to that build in the query. 🤔 It'd be strange if only the last agent affected it.

Comment (mtojek) [reply coderd/database/databasefake/databasefake.go:904]: Ok, I will try to improve the code. I admit that currently, it looks only at the last build and the most up-to-date agent.

File: coderd/database/queries/workspaces.sql (hunk 7 above)
Comment (Emyrk) [reply coderd/database/queries/workspaces.sql]: @mtojek I think the case logic is exactly what you want. But you would have to add that case logic to all reads. So either remove all `GetWorkspaceAgentsByXXX` and make 1 with a filter (like workspaces/template/etc). Or you could also make a `view`. I looked into this before with sqlc in an issue here:

https://github.com/coder/coder/issues/2201

Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: Hey @Emyrk, thanks for jumping in!

I had a chat about this issue with @mafredri to try `WITH` expression first. I guess that I can transform it into a `VIEW` if there are performance/clean-sql concerns. Otherwise, I am happy to do this in a follow-up.

File: coderd/database/databasefake/databasefake.go (hunk 4 above)
Comment (mtojek) [reply coderd/database/databasefake/databasefake.go]: Refactored.

File: coderd/database/queries/workspaces.sql (hunk 7 above)
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: @Emyrk @mafredri After further research I noticed a possible blocker for a view. The CASE logic 
 requires `agent_inactive_disconnect_timeout_seconds`, which is a coderd option, and it's currently provided via query.

Unless we can change it to a static value, then I suppose we can't use views here.

**Review by mafredri — COMMENTED** [review]
A few more thoughts on the query structure, but really liking how it turned out so far. 👍🏻

File: coderd/database/databasefake/databasefake.go [hunk 9]
```diff
@@ -909,6 +947,38 @@ func (q *fakeQuerier) GetAuthorizedWorkspaces(ctx context.Context, arg database.
...
+		status = "disconnected"
+	case dbAgent.LastConnectedAt.Valid:
+		// The agent should be assumed connected if it's under inactivity timeouts
+		// and last connected at has been properly set.
+		status = "connected"
+	default:
+		panic("unknown agent status: " + status)
+	}
+	return status
+}
```
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/databasefake/databasefake.go:980]: I guess that the biggest pain point is `agent_inactive_disconnect_timeout_seconds` which I mentioned [here](https://github.com/coder/coder/pull/5145#discussion_r1031089389). No matter where we put the logic, there is always a dependency on the config option.

File: coderd/database/queries/workspaces.sql (hunk 7 above)
Comment (mafredri) [reply coderd/database/queries/workspaces.sql]: That's a good point @mtojek, it definitely hampers the use case. Ideally this value would come from either the terraform provider or be stored in the database by some other means, at which point it can be part of the query.

I don't find it unthinkable that we would serialize certain coder server runtime properties in the database, either as a temp table or one that is (re)written on startup. The inactivity seconds could then be stored there and joined.

File: coderd/database/databasefake/databasefake.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/databasefake/databasefake.go:982]: Comment added.

File: coderd/database/queries/workspaces.sql [hunk 10]
```diff
@@ -38,12 +38,55 @@ WHERE
 	);
 
 -- name: GetWorkspaces :many
+WITH workspace_builds_agents AS (
```
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/queries/workspaces.sql:41]: This is a good suggestion, but won't it be a problem that `latest_build` goes over all workspaces? 

```sql
SELECT
	workspaces.*, COUNT(*) OVER () as count
FROM
	workspaces
LEFT JOIN LATERAL (
	SELECT

...

	WHERE
		workspace_builds.workspace_id = workspaces.id
...
) latest_build ON TRUE
```

I presume that we will need `latest_builds` (plural) for every workspace, but I'm not sure if it isn't the same complexity.

File: coderd/database/queries/workspaces.sql [hunk 11]
```diff
@@ -38,12 +38,55 @@ WHERE
...
+		workspace_resources
+	ON
+		workspace_resources.job_id = provisioner_jobs.id
+	LEFT JOIN
+		workspace_agents
+	ON
+		workspace_agents.resource_id = workspace_resources.id
+	WHERE
+		workspace_builds.transition = 'start'::workspace_transition AND
+		workspace_agents.id IS NOT NULL
```
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: My bad, fixed.

File: coderd/database/queries/workspaces.sql (hunk 10 above)
[the remark this answers is not in the document]
Comment (mtojek) [reply coderd/database/queries/workspaces.sql]: Ok, I investigated a few concepts we talked about offline with @mafredri:

1. Replace `latest_build` with `workspace_latest_builds` CTE.

Unfortunately, I wasn't able to select only the last build per workspace.

2. Replace `workspace_build_agent` CTE with `JOIN LATERAL`.

Workspaces with multiple agents will return multiple records, which is unexpected.

3. Place the CASE logic in the [WHERE clause](https://github.com/coder/coder/pull/5145/commits/d74b072b9fa12c89f8417cb4801011c2226367ab)

It looks like the conditional logic will fire only if `has-agent` is specified and it shouldn't affect other `GetWorkspaces` queries.

Let me know your thoughts.

File: coderd/database/queries/workspaces.sql [hunk 12]
```diff
@@ -161,17 +162,63 @@ WHERE
...
+				FROM
+					workspace_builds
+				JOIN
+					provisioner_jobs
+				ON
+					provisioner_jobs.id = workspace_builds.job_id
+				JOIN
+					workspace_resources
+				ON
+					workspace_resources.job_id = provisioner_jobs.id
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:180]: I haven't tested if this works, but I would suggest this final change:

```suggestion
				FROM
					latest_build
				JOIN
					workspace_resources
				ON
					workspace_resources.job_id = provisioner_job_id
```

You'll need to add `provisioner_jobs.id AS provisioner_job_id ` to the select for `latest_build` though.

This should be more performant than re-joining these tables here. (It also eliminates the need for the `build_number` check in `WHERE`.)

Comment (mtojek) [reply coderd/database/queries/workspaces.sql:180]: I'm afraid that it would work if `latest_build` is CTE. Otherwise, it's: `relation "latest_build" does not exist`.

**Review by mafredri — APPROVED** [review]
Looks great, nice job on the query! 👍🏻
