### PR TITLE
fix: change resource icon colors in the delete modal based on the set theme

### LINKED ISSUE #16191: [bug] Icon color doesn't update with the color theme
Image

All icons should use our color tokens so they are automatically updated with the theme. In this case, it should be "content-secondary".

cc @BrunoQuaresma as it relates to https://github.com/coder/coder/issues/15613?issue=coder%7Ccoder%7C14780

### PR DESCRIPTION
**Pull request by brettkolodny**
Closes #16191 

I've gone and solved this in a potentially strange way, and I feel like there is a better/more obvious way.

Screenshot 2025-02-12 at 6 50 49 PM

Screenshot 2025-02-12 at 6 51 42 PM

### CODE REVIEW

File: site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx [hunk 1]
```diff
@@ -247,7 +247,16 @@ const Resources: FC<StageProps> = ({ workspaces }) => {
 			>
 				{Object.entries(resources).map(([type, summary]) => (
 					<Stack key={type} direction="row" alignItems="center" spacing={1}>
-						<img alt="" src={summary.icon} css={styles.summaryIcon} />
+						<div
+							aria-hidden={true}
+							className="bg-content-primary"
+							style={{
```
Comment (jaaydenh) [inline site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx:253]: one of the long-term goals is to completely remove emotion css from the project. Adding new non-tailwind styles does not move things in that direction.

Comment (jaaydenh) [reply site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx:253]: Actually, I looked at this more carefully and this solution doesn't depend on emotion. It feels like overall that dynamically loading icons with an img tag is not the best solution but that is not relevant or in scope for this bug fix which does fix the bug.

**Review by jaaydenh — APPROVED** [review]
Nice fix given the constraints the of the problem.

File: site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx (hunk 1 above)
Comment (brettkolodny) [reply site/src/pages/WorkspacesPage/BatchDeleteConfirmation.tsx]: Yeah, this solution didn't feel great when I did it but I couldn't figure out something better. But Kayla just told me about this `ExternalImage` component that seems to do the trick!

**Review by aslilac — APPROVED** [review]
perfect 💅
