### PR TITLE
fix: ui: workspace bumpers now honour template max_ttl

### LINKED ISSUE #2764: Workspace schedule bumpers are broken
## Problem
Bumpers in the workspace schedule are broken

## Steps to reproduce
1. Press a + or - button and observe error

Screen Shot 2022-06-30 at 2 41 58 PM

Screen Shot 2022-06-30 at 2 42 41 PM

## Definition of Done
A user should be able to modify the shutdown using the bumpers + or -
---

Perhaps it is following the template policy correctly, but the error makes it appear broken.

### PR DESCRIPTION
**Pull request by johnstcn**
- chore: WorkspacePage: invert workspace schedule bumper logic for readibility
- fix: ui: workspace bumpers now honour template max_ttl
- chore: refactor workspace schedule bumper logic mostly into `util/schedule.ts` and unit test separately

Verification Steps:
- Create and start a workspace from a template that has a max_ttl of less than 24 hours and has autostop enabled.
- Repeatedly click the ➕ icon by the schedule -> it should not allow extending the workspace deadline past template max_ttl
- Repeatedly click the ➖  icon by the schedule -> it should not allow decreasing the workspace deadline before now plus 30 minutes

Fixes https://github.com/coder/coder/issues/2764.

### CODE REVIEW

File: site/src/components/WorkspaceScheduleButton/WorkspaceScheduleButton.tsx [hunk 1]
```diff
@@ -40,27 +40,21 @@ export const shouldDisplayPlusMinus = (workspace: Workspace): boolean => {
...
-export const deadlineMinusDisabled = (workspace: Workspace, now: dayjs.Dayjs): boolean => {
-  const delta = dayjs(workspace.latest_build.deadline).diff(now)
-  return delta <= 30 * 60 * 1000 // 30 minutes
-}
-
-export const deadlinePlusDisabled = (workspace: Workspace, now: dayjs.Dayjs): boolean => {
-  const delta = dayjs(workspace.latest_build.deadline).diff(now)
-  return delta >= 24 * 60 * 60 * 1000 // 24 hours
-}
-
```
Comment (johnstcn) [inline site/src/components/WorkspaceScheduleButton/WorkspaceScheduleButton.tsx:52]: review: moved to `util/workspace.ts`

File: site/src/pages/WorkspacePage/WorkspacePage.tsx [hunk 2]
```diff
@@ -63,12 +65,16 @@ export const WorkspacePage: React.FC = () => {
...
       <div className={styles.error}>
         {getWorkspaceError && <ErrorSummary error={getWorkspaceError} />}
+        {refreshTemplateError && <ErrorSummary error={refreshTemplateError} />}
         {checkPermissionsError && <ErrorSummary error={checkPermissionsError} />}
       </div>
     )
   } else if (!workspace) {
     return <FullScreenLoader />
+  } else if (!template) {
+    return <div className={styles.error}>Loading template</div>
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:75]: That's fair. Although I'd really like to be able to add information to `FullScreenLoader` on what's currently happening (e.g. Reticulating Splines)

[the remark this answers is not in the document]
Comment (presleyp) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:75]: We could add a prop to `FullScreenLoader` that can take that info?

[the remark this answers is not in the document]
Comment (johnstcn) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:75]: That sounds like a good idea. I'll open a separate issue for that.

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx [hunk 3]
```diff
@@ -181,6 +183,7 @@ describe("Workspace Page", () => {
 
   describe("Resources", () => {
     it("shows the status of each agent in each resource", async () => {
+      const getTemplateMock = jest.spyOn(api, "getTemplate").mockResolvedValueOnce(MockTemplate)
```
Comment (presleyp) [inline site/src/pages/WorkspacePage/WorkspacePage.test.tsx:186]: It's generally better to test things that are apparent to the user than internals like whether a function was called, but sometimes it's necessary. Is this one of the cases where testing user-apparent effects is too hard?

File: site/src/pages/WorkspacePage/WorkspacePage.tsx [hunk 4]
```diff
@@ -85,7 +91,7 @@ export const WorkspacePage: React.FC = () => {
               bannerSend({
                 type: "UPDATE_DEADLINE",
                 workspaceId: workspace.id,
-                newDeadline: dayjs(workspace.latest_build.deadline).utc().add(4, "hours"),
+                newDeadline: dayjs.min(deadline.add(4, "hours"), maxDeadline(workspace, template)),
```
Comment (presleyp) [inline site/src/pages/WorkspacePage/WorkspacePage.tsx:94]: You don't have to change this here, but I'm wondering if we want to try to push logic like this into XState. Instead of one `UPDATE_DEADLINE` event, we could have multiple events that do calculations within them. The idea would be to try to get more logic out of components. Maybe a topic for Frontend Variety.

File: site/src/util/workspace.ts [hunk 5]
```diff
@@ -1,10 +1,14 @@
 import { Theme } from "@material-ui/core/styles"
 import dayjs from "dayjs"
+import duration from "dayjs/plugin/duration"
```
Comment (presleyp) [inline site/src/util/workspace.ts:3]: Love that you put util functions in their own spot and tested them! I noticed when I was working on the schedule form that there are a lot of different places for schedule-related util functions. Any thoughts on that? I don't want to make you figure it all out in this PR but I might at least call this util file something about the schedule instead of just the workspace.

File: site/src/pages/WorkspacePage/WorkspacePage.tsx (hunk 4 above)
Comment (johnstcn) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:94]: Yeah, I was wondering that but didn't want to over-complicate the machine. :-)

File: site/src/util/workspace.ts (hunk 5 above)
Comment (johnstcn) [reply site/src/util/workspace.ts:3]: IMO I think it makes sense to keep it in the workspace util file, as workspaces and schedules are tightly coupled. If we eventually move schedules into more of a separate entity of their own, then maybe I could see it making more sense.

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx (hunk 3 above)
Comment (johnstcn) [reply site/src/pages/WorkspacePage/WorkspacePage.test.tsx:186]: I'm not sure  -- I'll try seeing if I can make some assertions about child components here.

Comment (johnstcn) [reply site/src/pages/WorkspacePage/WorkspacePage.test.tsx:186]: Actually, it seems like testing properties of child components is considered somewhat of an anti-pattern. I'll factor some more stuff out to a util file and test it separately.

**Review by presleyp — APPROVED** [review]
Great work! The loading state is the only thing I feel strongly about.
