### PR TITLE
fix: apply autofocus to workspace button search

### LINKED ISSUE #14816: The dropdown from "Create Workspace..." doesn't auto-focus the search field
As a user, it would be nice to be able to start search/typing immediately after clicking "Create Workspace...", however, the field is not focused.

image

Browser: Safari
Deployment: dev.coder.com

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/14816

When user clicks on the "New workspace" button, the focus will automatically switch to the text field.

Screenshot 2025-03-13 at 13 40 46

### CODE REVIEW

File: site/src/components/SearchField/SearchField.tsx [hunk 1]
```diff
@@ -6,19 +6,28 @@ import InputAdornment from "@mui/material/InputAdornment";
 import TextField, { type TextFieldProps } from "@mui/material/TextField";
 import Tooltip from "@mui/material/Tooltip";
 import visuallyHidden from "@mui/utils/visuallyHidden";
-import type { FC } from "react";
+import { type FC, useEffect, useRef } from "react";
 
 export type SearchFieldProps = Omit<TextFieldProps, "onChange"> & {
 	onChange: (query: string) => void;
+	autoFocused?: boolean;
```
Comment (mafredri) [inline site/src/components/SearchField/SearchField.tsx:13]: Suggestion: `autoFocus` (action) vs `autoFocused` (past)

**Review by mafredri — APPROVED** [review]
LGTM, thanks for fixing this!

File: site/src/components/SearchField/SearchField.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/components/SearchField/SearchField.tsx]: renamed to `autoFocus` 👍 thanks for suggestion!
