### PR TITLE
fix: improve log on provisioner daemon started with pk

### LINKED ISSUE #15126: Correct log line when using tagged --key provisioner
Right now we log a line with the tags we are using for the provisioner, and when using `--key` it says it's "untagged" which isn't true. 

```
2024-11-06 21:29:27.404 [info]  starting provisioner daemon  tags={}  name=coder-provisioner-67d54c74dc-qds64

```

The issue is that the key authentication does not have permission to describe the key and get the tags, and since we don't get any from the cli args, it logs that there's no tags. 

Options I see:
1. Add permissions to provisioner keys to get tag information
2. Remove log line altogether if it's not critical information

Spun out from https://github.com/coder/coder/issues/15047

### PR DESCRIPTION
**Pull request by defelmnq**
Resolve #15126 

This PR aims to fetch the provisioned key details when starting a provisioned daemon - for now in order to access the tags associated to the provisioned key and display them accordingly in the starting logs.

We do not want to change any other logic inside this PR as it was already working as expected.

### CODE REVIEW

**Comment by johnstcn** [comment]
> cc @johnstcn I tried to think about how to test this one but am not sure to find something that makes sense.

Take a look at the existing tests in `enterprise/cli/provisionerdaemonstart_test.go`: in particular, tests that leverage `ptytest.New(inv)` to assert the stdin/stdout of the command that's being invoked.

**Comment by defelmnq** [comment]
Yeah indeed @johnstcn that's why I kept it as a draft until the other one is merged - was more to be able to validate CI & ensure its all ready.

About the tests tips thanks, currently checking.

File: enterprise/cli/provisionerdaemonstart.go [hunk 1]
```diff
@@ -104,6 +104,22 @@ func (r *RootCmd) provisionerDaemonStart() *serpent.Command {
...
+
+			if provisionerKey != "" {
+				pkDetails, err := client.GetProvisionerKey(ctx, provisionerKey)
+				if err != nil {
+					return xerrors.New("unable to get provisioner key details")
+				}
+
+				for k, v := range pkDetails.Tags {
+					displayedTags[k] = v
+				}
```
Comment (johnstcn) [inline enterprise/cli/provisionerdaemonstart.go:120]: I think we can overwrite `displayedTags` here entirely. If using a provisioner key, none of the tags specified via `tags` can be used. (In fact, I don't think you're even _allowed_ specify both `--key` and `--tag`)

Comment (defelmnq) [reply enterprise/cli/provisionerdaemonstart.go]: I preferred to keep two different variables as otherwise it would require some other logic changes.

The tag variable is used to call the `/provisionerdaemon/serve` endpoint below, and using the same variable would mean changes here too, which I feel like we dont want. 

wdyt ?

File: enterprise/cli/provisionerdaemonstart_test.go [hunk 2]
```diff
@@ -294,6 +294,51 @@ func TestProvisionerDaemon_ProvisionerKey(t *testing.T) {
 		require.Equal(t, proto.CurrentVersion.String(), daemons[0].APIVersion)
 	})
 
+	t.Run("OKWithTags", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (defelmnq) [reply enterprise/cli/provisionerdaemonstart_test.go:297]: We could add a test to validate what happen in case of the `client.GetProvisionerKey` failing - I've just done it. 

Otherwise the logic should not be impacted and the endpoint itself seems pretty much well tested.

File: enterprise/cli/provisionerdaemonstart.go [hunk 3]
```diff
@@ -104,6 +104,23 @@ func (r *RootCmd) provisionerDaemonStart() *serpent.Command {
...
+				displayedTags[key] = val
+			}
+
+			if provisionerKey != "" {
+				pkDetails, err := client.GetProvisionerKey(ctx, provisionerKey)
+				if err != nil {
+					return xerrors.New("unable to get provisioner key details")
+				}
+
+				displayedTags = make(map[string]string, len(pkDetails.Tags))
```
Comment (dannykopping) [inline enterprise/cli/provisionerdaemonstart.go:118]: What is your intention here? To clear out the map if the provisioner key is set?

File: enterprise/cli/provisionerdaemonstart_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (dannykopping) [reply enterprise/cli/provisionerdaemonstart_test.go:297]: I'm not really understanding the point of `NoProvisionerKeyFound`. The purpose of this PR is to add changes to tags which are logged, but AFAICS you're not looking at the outputted logs? Does the provisioner fail to start in this case?

[the remark this answers is not in the document]
Comment (defelmnq) [reply enterprise/cli/provisionerdaemonstart_test.go:297]: Yeah that's exactly it - I am open to the behavior we want to apply here but globally if we can not contact the backend / retrieve the key , I returned and error and did not continued to start the provisioner.

We can instead just output an error and continue as if nothing happened - but the log will be the same as of now (without the tags)

[the remark this answers is not in the document]
Comment (dannykopping) [reply enterprise/cli/provisionerdaemonstart_test.go:297]: Cool, no need to change the behaviour - I was just confirming what the intent was for this test.

File: enterprise/cli/provisionerdaemonstart.go (hunk 3 above)
Comment (defelmnq) [reply enterprise/cli/provisionerdaemonstart.go:118]: So globally, either we have no key and some tags (line 107 to 110) - either we have no key (line 112) and want to fill the displayedTags with the ones fetched in `pkDetails`.

That's why at first I was using the same map without allocating it , as we can't really be sure about the size before knowing in which case we'll enter 
anyway, we want the map to be declared in the whole function to be used below.

Comment (dannykopping) [reply enterprise/cli/provisionerdaemonstart.go:118]: Seems like you should add an `else` block which populates `displayedTags` if the provision key is nil?

I don't think what you have is a big deal performance-wise since maps can never shrink, so if the `make` call on L107 has a length of 4 and the call on L118 has a length of 2, it'll keep the originally-allocated memory.
Preallocation is not strictly necessary but it's a good practice. In this case if there's a chance we'll allocate twice then there's not much of a saving since that's what preallocation is trying to prevent.

**Review by dannykopping — APPROVED** [review]
LGTM

File: enterprise/cli/provisionerdaemonstart.go (hunk 1 above)
Comment (johnstcn) [reply enterprise/cli/provisionerdaemonstart.go:121]: For the sake of correctness, I'd like to make this change.
Otherwise this may confuse future readers of the code.
However, let's do it as a separate follow-up PR.

**Review by johnstcn — APPROVED** [review]

File: enterprise/cli/provisionerdaemonstart.go (hunk 3 above)
Comment (defelmnq) [reply enterprise/cli/provisionerdaemonstart.go]: tried to improve it from your feedback, was it what you had in mind ? 🙏
