### PR TITLE
fix: ensure deleting workspace creates audit log

### LINKED ISSUE #4316: audit: I deleted a workspace but the audit logs did not record it.
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

Conversely, when I create a workspace, it is logged.  Updating a workspace is not logged too.

Precise, accurate audit logging is critical for security and compliance teams within enterprises.

I am basing the expected actions from the Coder docs
https://coder.com/docs/coder-oss/latest/admin/audit-logs#filtering-logs

API key creation is not logged too - I did `coder login` which to my knowledge is the only way to create a token, and an audit log entry is not created.

Unlike v1, there is no CLI command to create and delete tokens.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
partially fixes #4316 

We weren't create Audit Log entries when deleting a workspace.

Now we are:
Screen Shot 2022-10-13 at 1 56 19 PM

### CODE REVIEW

File: coderd/workspacebuilds.go [hunk 1]
```diff
@@ -277,6 +280,22 @@ func (api *API) postWorkspaceBuilds(rw http.ResponseWriter, r *http.Request) {
...
+				Log:     api.Logger,
+				Request: r,
+				Action:  database.AuditActionDelete,
+			})
+		)
+
+		defer commitAudit()
+		aReq.Old = workspace
+	}
+
```
Comment (Kira-Pilot) [inline coderd/workspacebuilds.go:296]: @coadler I'd love to write a test asserting log creation as we discussed, but I am having some difficulty.

In `coderd/workspacebuilds_test.go` in the `TestWorkspaceBuildStatus` test, I attempted to add:

````
require.Len(t, auditor.AuditLogs, 4)
assert.Equal(t, database.AuditActionDelete, auditor.AuditLogs[3].Action)
````

at the very end of the test, after successful deletion by the client; however, `auditor.AuditLogs` is always an empty list. Any idea why?

Comment (coadler) [reply coderd/workspacebuilds.go:296]: Could you push that code up too? I'll try and take a look!

Comment (Kira-Pilot) [reply coderd/workspacebuilds.go:296]: @coadler pushed! Thanks!

File: coderd/workspacebuilds_test.go [hunk 2]
```diff
@@ -541,6 +542,7 @@ func TestWorkspaceBuildStatus(t *testing.T) {
 	closeDaemon.Close()
 	template := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID)
 	workspace := coderdtest.CreateWorkspace(t, client, user.OrganizationID, template.ID)
+	auditor := audit.NewMock()
```
Comment (coadler) [inline coderd/workspacebuilds_test.go:545]: This auditor needs to be added to the `&coderdtest.Options` struct above!

Comment (Kira-Pilot) [reply coderd/workspacebuilds_test.go]: That worked; thank you!

**Review by coadler — APPROVED** [review]
