### PR TITLE
fix(coderd/workspaceapps): prevent race in workspace app audit session updates

### LINKED ISSUE #520: flake: `Test_ResolveRequest`
https://github.com/coder/coder/actions/runs/13925238657/job/38968087846?pr=16984

```
db_test.go:1176: app app-owner
    audit.go:101: audit log 1: expected Ip {2001:db8:eb00:95d7:8a04:cb58:82f:d5d2 ffffffffffffffffffffffffffffffff}, got {2001:db8:5022:2959:9e53:ad3e:9b05:9a21 ffffffffffffffffffffffffffffffff}
    audit.go:101: audit log 2: expected Ip {2001:db8:eb00:95d7:8a04:cb58:82f:d5d2 ffffffffffffffffffffffffffffffff}, got {2001:db8:5022:2959:9e53:ad3e:9b05:9a21 ffffffffffffffffffffffffffffffff}
    db_test.go:1176: app app-authed
    db_test.go:1211: 
        	Error Trace:	C:/a/coder/coder/coderd/workspaceapps/db_test.go:1211
        	Error:      	"[{efd2d949-d5a4-48e3-b5b9-[803](https://github.com/coder/coder/actions/runs/13925238657/job/38968087846?pr=16984#step:7:804)dc8d4630c 2025-03-18 14:14:09.299881 +0000 UTC 43f3ae24-5dc6-484a-8356-dc01a0e9a306 1dda8818-7d97-4beb-abb3-edd6b302d6d5 {{2001:db8:2207:a3db:5118:7a7f:3042:3bcb ffffffffffffffffffffffffffffffff} true} { false} workspace_app ded5ebba-a586-4de1-b2f9-fa414e89ee2b app-authed open [123 125] 200 [123 34 119 111 114 107 115 112 97 99 101 95 110 97 109 101 34 58 34 101 97 103 101 114 45 99 97 114 118 101 114 52 45 54 72 116 34 44 34 98 117 105 108 100 95 110 117 109 98 101 114 34 58 34 34 44 34 98 117 105 108 100 95 114 101 97 115 111 110 34 58 34 34 44 34 119 111 114 107 115 112 97 99 101 95 111 119 110 101 114 34 58 34 116 101 115 116 117 115 101 114 34 44 34 119 111 114 107 115 112 97 99 101 95 105 100 34 58 34 99 49 56 57 48 51 51 50 45 100 54 49 49 45 52 51 51 48 45 57 50 55 53 45 50 102 102 55 53 52 55 98 49 99 101 99 34 125] 00e3867d-0eb5-40c3-bc69-e3e496bfd856 } {230466a5-8b40-4f01-8baa-f0afd92b2363 2025-03-18 14:14:09.299881 +0000 UTC 43f3ae24-5dc6-484a-8356-dc01a0e9a306 1dda8818-7d97-4beb-abb3-edd6b302d6d5 {{2001:db8:2207:a3db:5118:7a7f:3042:3bcb ffffffffffffffffffffffffffffffff} true} { false} workspace_app ded5ebba-a586-4de1-b2f9-fa414e89ee2b app-authed open [123 125] 200 [123 34 119 111 114 107 115 112 97 99 101 95 110 97 109 101 34 58 34 101 97 103 101 114 45 99 97 114 118 101 114 52 45 54 72 116 34 44 34 98 117 105 108 100 95 110 117 109 98 101 114 34 58 34 34 44 34 98 117 105 108 100 95 114 101 97 115 111 110 34 58 34 34 44 34 119 111 114 107 115 112 97 99 101 95 111 119 110 101 114 34 58 34 116 101 115 116 117 115 101 114 34 44 34 119 111 114 107 115 112 97 99 101 95 105 100 34 58 34 99 49 56 57 48 51 51 50 45 100 54 49 49 45 52 51 51 48 45 57 50 55 53 45 50 102 102 55 53 52 55 98 49 99 101 99 34 125] 110410df-b0e7-4c7d-a615-e2a6b654d144 }]" should have 1 item(s), but has 2
        	Test:       	Test_ResolveRequest/AuditLogging
        	Messages:   	single audit log, previous session active

=== FAIL: coderd/workspaceapps Test_ResolveRequest (1.00s)
```

### PR DESCRIPTION
**Pull request by mafredri**
Fixes coder/internal#520

### CODE REVIEW

File: coderd/workspaceapps/db.go [hunk 1]
```diff
@@ -447,16 +447,20 @@ func (p *DBTokenProvider) auditInitRequest(ctx context.Context, w http.ResponseW
 			slog.F("status_code", statusCode),
 		)
 
-		var startedAt time.Time
+		var (
+			refreshID       = uuid.New()
+			upsertRefreshID uuid.UUID
+		)
```
Comment (johnstcn) [inline coderd/workspaceapps/db.go:453]: I feel this is potentially error-prone.
Apparently you can use `(xmax = 0) AS inserted` to know if we did an insert instead of an update ([link](https://stackoverflow.com/questions/39058213/differentiate-inserted-and-updated-rows-in-upsert-using-system-columns)). Would this be a better option?

Comment (mafredri) [reply coderd/workspaceapps/db.go:453]: Which error risk did you identify?

The `xmax` behavior can be used to differentiate _inserts_ and _updates_, but there are two types of _updates_ in this case which it doesn't help with. Btw, `xmax` behavior is something of an implementation detail, not sure I'd want to depend on it in production code.

File: coderd/database/migrations/000302_fix_app_audit_session_race.up.sql [hunk 2]
```diff
@@ -0,0 +1,5 @@
+-- Add column with default to fix existing rows.
+ALTER TABLE workspace_app_audit_sessions
+	ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/database/migrations/000302_fix_app_audit_session_race.up.sql:3]: TIL, looks interesting.

File: coderd/database/migrations/000302_fix_app_audit_session_race.up.sql [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+ALTER TABLE workspace_app_audit_sessions
+	ALTER COLUMN id DROP DEFAULT;
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/database/migrations/000302_fix_app_audit_session_race.up.sql:5]: You probably saw it in my other PR 😄

File: coderd/workspaceapps/db.go (hunk 1 above)
Comment (johnstcn) [reply coderd/workspaceapps/db.go:453]: It requires you to know beforehand that the ID you put in is not necessarily the ID you get out and that you may want to check that what you put in is what you get out. So more of a potential sharp edge for the unwary.

Comment (mafredri) [reply coderd/workspaceapps/db.go]: Thanks for explaining the problem, made this a simple fix a00d197.

**Review by johnstcn — APPROVED** [review]
