### PR TITLE
fix: missing FE ttl constraint validation

### LINKED ISSUE #1908: Bug: Workspace Schedule UI: submitting long TTL for workspace in UI caused error to update and workspace to hang and become unusable
- Browser (if applicable):  Chrome, in Windows

## Steps to Reproduce

- Set TTL to 100000000000  (after filling in the other fields with acceptable defaults)
- Hit submit
- UI hangs and never updates and becomes unusable

## Expected

 
If the TTL is truly invalid, I should receive an error message preventing the submit and telling me what the values are. Even better if the UI has input validation or at least some help text. 

## Actual

 
UI hangs forever

## Screenshot
image

### PR DESCRIPTION
**Pull request by greyscaled**
Resolves: https://github.com/coder/coder/issues/1908

### CODE REVIEW

File: site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx [hunk 1]
```diff
@@ -172,6 +172,7 @@ export const WorkspaceSchedulePage: React.FC = () => {
             autoStart: formValuesToAutoStartRequest(values),
             ttl: formValuesToTTLRequest(values),
           })
+          return Promise.resolve()
```
Comment (vapurrmaid) [inline site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx:175]: **Review**:

Useful whenever you're returning a synchronous `onSubmit`:

https://formik.org/docs/api/formik#onsubmit-values-values-formikbag-formikbag--void--promiseany

It looks a little janky (I know), but is absolutely necessary to avoid infini-spinning submit button if submissions fails the first time.

Comment (presleyp) [reply site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx:175]: I was avoiding using formik's `isSubmitting` (for instance, to determine whether to disable things), but are you saying that formik internally uses it so we still need this workaround?

**Review by johnstcn — APPROVED** [review]
BE ✔️

File: site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx (hunk 1 above)
Comment (presleyp) [reply site/src/pages/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx:175]: Yeah, I see it as letting XState be in charge of knowing what state we're in instead of Formik.

**Review by presleyp — APPROVED** [review]

**Review by Kira-Pilot — APPROVED** [review]
