### PR TITLE
fix(coderd/database/dbfake): prevent cross-test job stealing in WorkspaceBuildBuilder

### LINKED ISSUE #1367: flake: TestTasks/Send/SendToNonActiveStates/Pending
## CI Failure Details

**CI Run Link:** https://github.com/coder/coder/actions/runs/22382456151

**Failed Job:** `test-go-pg (macos-latest)`

**Commit Info:**
- SHA: `6c16794173806a7b28e987c7ccc2391110282e70`
- Author: Garrett Delfosse
- Date: 2026-02-25

## Failure Signature

```
=== FAIL: coderd TestTasks/Send/SendToNonActiveStates/Pending (0.21s)
    aitasks_test.go:898:
        Error:       "Task is initializing." does not contain "pending"
        Test:        TestTasks/Send/SendToNonActiveStates/Pending
```

## Error Analysis

The Pending subtest expects the API error message to include `pending`, but the response returned `Task is initializing.` This suggests the task status transitioned from pending → initializing before the assertion, so the response text no longer matches the expected pending message.

## Root Cause Hypothesis

*Likely flaky/timing-dependent.* The task created in `database.TaskStatusPending` appears to transition to `initializing` quickly (possibly when the provisioner daemon picks up the job), causing the response message to change to `Task is initializing.` between creation and the `TaskSend` call.

## Assignment Analysis

Git history for the failing block (no per-line blame available):
- `git log --oneline --follow coderd/aitasks_test.go`
- Commit `2549fc71faeb13f21d5efbb83c11108ee95e0468` (Mathias Fredriksson) introduced the `SendToNonActiveStates` subtests and the related error messaging logic.

Assigning to **@mafredri** as the most recent meaningful modifier of this test block and the task status handling.

## Related Issues

- #1320 (flake: TestTasks) — closed; different failure signature but same test family.

## Reproduction Hints

```
go test ./coderd -run 'TestTasks/Send/SendToNonActiveStates/Pending' -count=50
```

## Notes

No race detector warnings, panics, or OOM indicators observed in the job logs.

### PR DESCRIPTION
**Pull request by mafredri**
Previously, WorkspaceBuildBuilder.doInTX() inserted provisioner jobs
with empty tags and used a loop in AcquireProvisionerJob that could
match other tests' pending jobs when parallel tests share a database.

Add a unique tag (jobID -> "true") to each provisioner job at insert
time, then use that tag in AcquireProvisionerJob to target only the
correct job. This follows the same pattern used in dbgen.ProvisionerJob.

Closes coder/internal#1367

### CODE REVIEW

File: coderd/database/dbfake/dbfake.go [hunk 1]
```diff
@@ -395,30 +401,24 @@ func (b WorkspaceBuildBuilder) doInTX() WorkspaceResponse {
...
+			StartedAt: sql.NullTime{
+				Time:  startedAt,
+				Valid: true,
+			},
+			WorkerID: uuid.NullUUID{
+				UUID:  uuid.New(),
+				Valid: true,
+			},
+			Types:           []database.ProvisionerType{database.ProvisionerTypeEcho},
+			ProvisionerTags: must(json.Marshal(tags)),
```
Comment (ssncferreira) [inline coderd/database/dbfake/dbfake.go:417]: Any issue with dropping the `{"scope": "organization"}` provisioner tag?

**Review by ssncferreira — APPROVED** [review]
LGTM! Super clean 🥇

File: coderd/database/dbfake/dbfake.go (hunk 1 above)
Comment (mafredri) [reply coderd/database/dbfake/dbfake.go:417]: Good catch, I don't foresee it causing an issue but we should add it back for completeness 👍🏻
