### PR TITLE
fix: agentcontainers: fix flake when ctx cancelled while running docker inspect

### LINKED ISSUE #738: flake: TestSSH_Container/OK
```
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: successfully reported lifecycle state  payload="lifecycle:{state:OFF changed_at:{seconds:1750761858 nanos:195016000}}"
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: reported final lifecycle state
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: coordinator RPC disconnected
    t.go:106: 2025-06-24 10:44:18.197 [info]  agent.net.tailnet: closing tailnet Conn
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent.net.tailnet: closing configMaps configLoop
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent.net.tailnet: closing nodeUpdater updateLoop
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: swallowing context canceled  name="report lifecycle"
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: swallowing context canceled  name="report connections"
    t.go:106: 2025-06-24 10:44:18.197 [info]  coderd.agentrpc.yamux.stdlib: [ERR] yamux: Failed to read header: failed to get reader: failed to read frame header: EOF  owner=myuser  workspace_name=myworkspace  agent_name=dev  request_id=7e77b036-3a62-4a4a-b800-a4eb0afacf2b
    t.go:106: 2025-06-24 10:44:18.197 [info]  agent.stdlib: [ERR] yamux: Failed to read header: failed to get reader: context canceled
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: log sender send loop exiting
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: swallowing context canceled  name="send logs"
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent: got stats callback
    t.go:106: 2025-06-24 10:44:18.197 [debu]  coderd: agent connection monitor is closing connection  workspace_id=6e124ce3-a93c-44bc-a447-16995a4424b6  agent_id=6fd44077-26ce-4c2f-8272-69e9d141fbbc  request_id=7e77b036-3a62-4a4a-b800-a4eb0afacf2b  reason=canceled
    t.go:106: 2025-06-24 10:44:18.197 [debu]  agent.net.tailnet: closed netstack
    t.go:115: 2025-06-24 10:44:18.197 [erro]  agent.containers: updater loop ticker failed ...
        error= list containers failed:
                   github.com/coder/coder/v2/agent/agentcontainers.(*API).updateContainers
                       /home/coder/repos/coder/agent/agentcontainers/api.go:471
                 - run docker inspect: signal: killed: :
                   github.com/coder/coder/v2/agent/agentcontainers.(*dockerCLI).List
                       /home/coder/repos/coder/agent/agentcontainers/containers_dockercli.go:293
                 - signal: killed
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
```

seen locally by @spikecurtis

### PR DESCRIPTION
**Pull request by johnstcn**
Should fix https://github.com/coder/internal/issues/738

### CODE REVIEW

File: agent/agentcontainers/containers_dockercli.go [hunk 1]
```diff
@@ -311,21 +311,31 @@ func (dcli *dockerCLI) List(ctx context.Context) (codersdk.WorkspaceAgentListCon
...
+		var stdoutBuf, stderrBuf bytes.Buffer
+		cmd := execer.CommandContext(ctx, "docker", append([]string{"inspect"}, ids...)...)
+		cmd.Stdout = &stdoutBuf
+		cmd.Stderr = &stderrBuf
+		err = cmd.Run()
+		stdout = bytes.TrimSpace(stdoutBuf.Bytes())
+		stderr = bytes.TrimSpace(stderrBuf.Bytes())
+		if err != nil {
+			if ctx.Err() != nil {
+				// If the context was canceled, we don't want to return an error.
```
Comment (johnstcn) [inline agent/agentcontainers/containers_dockercli.go]:
```suggestion
				// If the context was canceled, we want to return that error instead.
```

File: agent/agentcontainers/containers_dockercli.go [hunk 2]
```diff
@@ -311,21 +311,31 @@ func (dcli *dockerCLI) List(ctx context.Context) (codersdk.WorkspaceAgentListCon
...
-	cmd.Stderr = &stderrBuf
-	err = cmd.Run()
-	stdout = bytes.TrimSpace(stdoutBuf.Bytes())
-	stderr = bytes.TrimSpace(stderrBuf.Bytes())
-	if err != nil {
-		if bytes.Contains(stderr, []byte("No such object:")) {
-			// This can happen if a container is deleted between the time we check for its existence and the time we inspect it.
-			return stdout, stderr, nil
+	select {
+	case <-ctx.Done():
```
Comment (mafredri) [inline agent/agentcontainers/containers_dockercli.go]: This could be simplified to just `if ctx.Err() != nil`.

File: agent/agentcontainers/api.go [hunk 3]
```diff
@@ -378,7 +378,11 @@ func (api *API) updaterLoop() {
 	// and anyone looking to interact with the API.
 	api.logger.Debug(api.ctx, "performing initial containers update")
 	if err := api.updateContainers(api.ctx); err != nil {
-		api.logger.Error(api.ctx, "initial containers update failed", slog.Error(err))
+		if errors.Is(err, context.Canceled) {
```
Comment (spikecurtis) [inline agent/agentcontainers/api.go:381]: Note that `context.Canceled` doesn't, by default, trigger test failure. Still, nice to not pollute the error stream.

**Review by mafredri — APPROVED** [review]
Other than the simplification suggestion, LGTM 👍🏻

**Review by spikecurtis — APPROVED** [review]
