### PR TITLE
fix(coderd/prometheusmetrics)!: filter deleted wsbuilds to reduce db load

### LINKED ISSUE #717: bug: GetLatestWorkspaceBuilds creates lots of DB load
In our dogfood deployment over 5 days in early June:

Avg Execution Time: 349.5ms
Num Times Called: 25805
Avg Rows: 4677

https://www.notion.so/coderhq/GetLatestWorkspaceBuilds-209d579be5928025a686ec5a4a2defd2?source=copy_link

### PR DESCRIPTION
**Pull request by mafredri**
This change removes the `GetLatestWorkspaceBuilds` query which includes
all workspaces for all time (including deleted). This allows us to also
stop using `GetProvisionerJobsByIDs` for said builds as the job status
is included in `GetWorkspaces` called separately.

**BREAKING CHANGE**: The `coderd_api_workspace_latest_build` Prometheus
metric no longer includes builds belonging to deleted workspaces, as
such, this metric will show fewer statuses.

Fixes coder/internal#717

### CODE REVIEW

File: coderd/prometheusmetrics/prometheusmetrics_test.go [hunk 1]
```diff
@@ -323,6 +349,33 @@ func TestWorkspaceLatestBuildStatuses(t *testing.T) {
...
+			insertFailed(t, db, u, org)
+			insertSuccess(t, db, u, org)
+			insertRunning(t, db, u, org)
+
+			// Verify that deleted workspaces/builds are NOT counted in metrics.
+			n, err := cryptorand.Intn(5)
+			require.NoError(t, err)
+			for range 1 + n {
+				insertDeleted(t, db, u, org)
+			}
```
Comment (mafredri) [inline coderd/prometheusmetrics/prometheusmetrics_test.go:369]: Review: This fails in the old implementation, but I thought it best to formalize the assumption. Considering the old implementation did not test for this, it seems like validation for the new approach.

**Comment by spikecurtis** [comment]
Soft deleted workspaces have been around forever, as has this metric. I wonder if @kylecarbs can reach back that far in his memory and recall whether it was a deliberate decision to incluce builds from deleted workspaces in the `coderd_api_workspace_latest_build_total` metric, or just an oversight.

The description of the metric talks about "current" number of workspace builds by status, which makes me think it was just an oversight. Since we track the latest build per workspace, not just all builds, the metric isn't useful for tracking an overall rate of succeeding / failing builds. My take is that the most obvious interpretation is that it's for non-deleted workspaces and this change is fine.

**Comment by mafredri** [comment]
That is the conclusion I also came to when I read the descriptions, which is why I went with this approach.

If need be, we can include deleted builds with a specialized query that selects the least amount of data needed. Previously we selected all data only to use a single column which is why optimizations were not possible.

**Review by johnstcn — APPROVED** [review]
This change makes sense to me.

**Review by dannykopping — APPROVED** [review]
Seems reasonable 👍 

Please ensure the semantics of this change are documented in the release notes for the next release.
We could clarify the definition of this metric too, which may help operators:

https://coder.com/docs/admin/integrations/prometheus#available-metrics

Currently it's quite brief: "The latest workspace builds with a status."

File: coderd/database/dbauthz/dbauthz.go [hunk 2]
```diff
@@ -2157,17 +2157,6 @@ func (q *querier) GetLatestWorkspaceBuildByWorkspaceID(ctx context.Context, work
...
-	// This function is a system function until we implement a join for workspace builds.
-	// This is because we need to query for all related workspaces to the returned builds.
-	// This is a very inefficient method of fetching the latest workspace builds.
-	// We should just join the rbac properties.
-	if err := q.authorizeContext(ctx, policy.ActionRead, rbac.ResourceSystem); err != nil {
-		return nil, err
-	}
-	return q.db.GetLatestWorkspaceBuilds(ctx)
-}
-
```
Comment (Emyrk) [inline coderd/database/dbauthz/dbauthz.go:2191]: Less queries! :heart:

**Comment by mafredri** [comment]
I've updated the PR to be a "breaking" change as well as describe the changed behavior. I've also updated the helps for the metrics to mention that it's for non-deleted workspaces.
