### PR TITLE
fix: allow users with workspace:create for any owner to list users

### LINKED ISSUE #18203: Custom roles cannot create workspaces on behalf of members in UI via the list
This was discovered by creating this role and attempting to create a workspace on behalf on a member in the UI. I was unable to do it at all, but @Emyrk said it would work if you manually paste username...

Regardless, we should fix this UX:

Image
Image

### PR DESCRIPTION
**Pull request by f0ssel**
## Summary

Custom roles that can create workspaces on behalf of other users need to be able to list users to populate the owner dropdown in the workspace creation UI. Previously, this required a separate `user:read` permission, causing the dropdown to fail for custom roles.

## Changes

- Modified `GetUsers` in `dbauthz` to check if the user can create workspaces for any owner (`workspace:create` with `owner_id: *`)
- If the user has this permission, they can list all users without needing explicit `user:read` permission
- Added tests to verify the new behavior

## Testing

- Updated mock tests to assert the new authorization check
- Added integration tests for both positive and negative cases

Fixes #18203

### CODE REVIEW

**Review by Emyrk — COMMENTED** [review]
Add this test to `roles_test.go` to have a test for which built in roles can do this.


```golang
{
	Name: "CreateWorkspaceForMembers",
	// When creating the WithID won't be set, but it does not change the result.
	Actions:  []policy.Action{policy.ActionCreate},
	Resource: rbac.ResourceWorkspace.InOrg(orgID).WithOwner(policy.WildcardSymbol),
	AuthorizeMap: map[bool][]hasAuthSubjects{
		true:  {owner, orgAdmin},
		false: {setOtherOrg, orgUserAdmin, orgAuditor, memberMe, userAdmin, templateAdmin, orgTemplateAdmin},
	},
},
```

File: coderd/workspaces.go [hunk 1]
```diff
@@ -2951,3 +2951,48 @@ func convertToWorkspaceRole(actions []policy.Action) codersdk.WorkspaceRole {
...
+	for _, user := range users {
+		minimalUsers = append(minimalUsers, codersdk.MinimalUser{
+			ID:        user.ID,
+			Username:  user.Username,
+			Name:      user.Name,
+			AvatarURL: user.AvatarURL,
+		})
+	}
+
+	httpapi.Write(ctx, rw, http.StatusOK, minimalUsers)
```
Comment (Emyrk) [inline coderd/workspaces.go:2997]: This is a good idea 👍

File: coderd/workspaces_test.go [hunk 2]
```diff
@@ -5620,6 +5620,53 @@ func TestWorkspaceSharingDisabled(t *testing.T) {
 	})
 }
 
+func TestWorkspaceAvailableUsers(t *testing.T) {
+	t.Parallel()
+
+	t.Run("OwnerCanListUsers", func(t *testing.T) {
+		t.Parallel()
+		client := coderdtest.New(t, &coderdtest.Options{IncludeProvisionerDaemon: true})
+		owner := coderdtest.CreateFirstUser(t, client)
```
Comment (Emyrk) [inline coderd/workspaces_test.go:5629]: Maybe use an org admin instead. Owners can do everything anyway

**Review by Emyrk — APPROVED** [review]
Small nit on the test, and 1 suggested test
