### PR TITLE
fix: add version information to default docs links

### LINKED ISSUE #13369: Link to versioned docs in the product
We have "learn more" documentation links in the product to explain features or debug known issues. These URLs always point to the latest version of the docs, regardless of your deployment/CLI version. 

We should have these take users to docs matching their version of Coder using the URL scheme `coder.com/docs/@<version-tag>/*`.

This will prevent showing mismatched documentation.

### PR DESCRIPTION
**Pull request by bcpeinhardt**
This PR adds version information to the default docs links. If the user set's the docs link themselves it won't mess with it.
It also moves a helper function for getting embedded build info into utils and adds a little cache.

fixes #13369

### CODE REVIEW

File: site/src/utils/docs.ts [hunk 1]
```diff
@@ -1,4 +1,11 @@
-const DEFAULT_DOCS_URL = "https://coder.com/docs";
+import { getStaticBuildInfo } from "./buildInfo";
+
+function defaultDocsUrl(): string {
+  const docsUrl = "https://coder.com/docs";
+  // If we can get the specific version, we want to include that in default docs URL.
+  const version = getStaticBuildInfo()?.version.split("-")[0];
```
Comment (aslilac) [inline site/src/utils/docs.ts:6]:
```suggestion
  let version = getStaticBuildInfo()?.version;
  const i = version?.indexOf("-") ?? -1;
  if (version.index >= 0) {
    version = version.slice(0, i);
  }
```

idk, this feels slightly clearer to me and avoid allocating an extra array, but I'll leave it up to you if you want to accept this suggestion or not

**Review by aslilac — APPROVED** [review]
nice!

File: site/src/utils/docs.ts (hunk 1 above)
Comment (bcpeinhardt) [reply site/src/utils/docs.ts:6]: Yeah I agree this is better :)

Comment (bcpeinhardt) [reply site/src/utils/docs.ts]: Uh oh compiler error, fixing haha

Comment (aslilac) [reply site/src/utils/docs.ts]: oh, what was I even thinking 🤪 clearly should've been `i` instead of `version.index`

**Comment by aslilac** [comment]
thanks for the fix!
