### PR TITLE
fix: stop printing warnings on external provisioner daemon command

### LINKED ISSUE #11307: spurious warning when starting external provisioner with PSK
When you start an external provisioner using a PSK the CLI drops a warning

```
check entitlement warnings error: get user me: GET http://coder.example.com/api/v2/users/me: unexpected status code 401: You are signed out or your session has expired. Please sign in again to continue.: Try logging in using 'coder login <url>'.

        Error: Cookie "coder_session_token" or query parameter must be provided.
```

This happens because the PSK auth doesn't work for the entitlement warnings or other startup checks.

We should just ignore these checks when starting an external provisioner daemon as they are meant for humans not a daemon.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #11307

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #11309** <a href="https://app.graphite.dev/github/pr/coder/coder/11309?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11309?utm_source=stack-comment).

File: enterprise/cli/provisionerdaemons_test.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ func TestProvisionerDaemon_PSK(t *testing.T) {
 	ctx, cancel := context.WithTimeout(inv.Context(), testutil.WaitLong)
 	defer cancel()
 	clitest.Start(t, inv)
-	pty.ExpectMatchContext(ctx, "starting provisioner daemon")
+	pty.ExpectNoMatchBefore(ctx, "check entitlement", "starting provisioner daemon")
```
Comment (johnstcn) [inline enterprise/cli/provisionerdaemons_test.go:39]: TIL that this exists

**Review by johnstcn — APPROVED** [review]

**Comment by spikecurtis** [comment]
### Merge activity

* **Dec 21, 7:55 AM**: @@spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/11309).
