### PR TITLE
fix: Templates table columns width

### LINKED ISSUE #3639: Uneven line wrapping for template descriptions
Screenshot from 2022-08-23 14-40-39

Unexpected line wrappings for the first template **used by** column takes a single line but, for the 2nd template, it takes two lines.
Also, If I have space on my screen, why the titles are wrapped? **Created by** is taking two lines.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fixes #3639 

Before fix:
image

After fix:
Screen Shot 2022-08-29 at 13 08 13

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

File: site/src/pages/TemplatesPage/TemplatesPageView.tsx [hunk 1]
```diff
@@ -115,10 +115,10 @@ export const TemplatesPageView: FC<React.PropsWithChildren<TemplatesPageViewProp
         <Table>
           <TableHead>
             <TableRow>
-              <TableCell>{Language.nameLabel}</TableCell>
-              <TableCell>{Language.usedByLabel}</TableCell>
-              <TableCell>{Language.lastUpdatedLabel}</TableCell>
-              <TableCell>{Language.createdByLabel}</TableCell>
+              <TableCell width="50%">{Language.nameLabel}</TableCell>
+              <TableCell width="16%">{Language.usedByLabel}</TableCell>
```
Comment (presleyp) [inline site/src/pages/TemplatesPage/TemplatesPageView.tsx:119]: It looks great, but I wonder if there's a better way than hard-coding a percentage.

Comment (presleyp) [reply site/src/pages/TemplatesPage/TemplatesPageView.tsx:119]: The MUI docs didn't give me any good ideas (you can set a cell to "small" but the problem was they were too small, even though the default is "medium", so that wouldn't help), so I think this is fine as long as it looks good in different screen sizes!

**Review by presleyp — APPROVED** [review]
