### PR TITLE
fix(site): Prompting user for missing variables

### LINKED ISSUE #6941: rich parameters: not prompting me for missing variables
I introduced a new template version that includes a new parameter and I'm not seeing the pop-up prompt to enter the missing parameter when I update my workspace.

https://user-images.githubusercontent.com/22407953/229251628-8890f7c9-64e7-426a-8982-db29a8fec11d.mov

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix #6941

### CODE REVIEW

File: site/src/api/api.ts [hunk 1]
```diff
@@ -1017,12 +1019,22 @@ const getMissingParameters = (
...
+    // don't need to ask them if they are not required.
+    const isMutableAndRequired = p.mutable && p.required
+    // Is immutable, so we can check if it is its first time on the build
+    const isImmutable = !p.mutable
+
+    if (isLegacy || isMutableAndRequired || isImmutable) {
+      requiredParameters.push(p)
+      return
+    }
+  })
```
Comment (BrunoQuaresma) [inline site/src/api/api.ts:1037]: @mtojek @bpmct is this logic correct? I must admit that asking or not for missing parameters is pretty challenging to understand for me 😅

Comment (mtojek) [reply site/src/api/api.ts:1037]: Let me try it locally...

**Review by mtojek — APPROVED** [review]
