### PR TITLE
fix: use `os.Pipe` implementation for Windows CLI tests to reduce flakiness

### LINKED ISSUE #1277: flake: TestRename (windows) - PTY read/write handle invalid
CI run: https://github.com/coder/coder/actions/runs/21133032582
Commit: d176714f90f2c4dffa4c182722f6b16deface38a (Cian Johnston)
Job: test-go-pg (windows-2022)

## What failed
Go test failures in the `cli` package:
- `TestRename`

Key log excerpts:
```
clitest.go:283: command "coder rename" exited with error: running command "coder rename": read |0: The handle is invalid.
...
ptytest.go:430 ... Error: write |1: The parameter is incorrect.
Test: TestRename
Messages: write line failed
```

## Why this looks flaky
This is Windows-only and the failure is in PTY I/O (`read |0: The handle is invalid`, `write |1: The parameter is incorrect`), consistent with intermittent PTY/handle lifecycle issues.

## Suspected root cause
PTY test harness appears to lose/close the underlying handle unexpectedly while the test is still interacting with the CLI prompt.

Files involved from stack trace:
- `cli/rename_test.go`
- `cli/clitest/clitest.go`
- `pty/ptytest/ptytest.go` (failure at/near `ptytest.go:430`)

## Ownership / assignment rationale
Most recent substantive change to `pty/ptytest/ptytest.go` is:
- 259dee2ea899 ("fix: move contexts to appropriate locations") by Danny Kopping

`cli/rename_test.go` hasn’t had a Windows-specific PTY change recently; this failure signature points to the PTY test harness.

Assigning to: @dannykopping

### PR DESCRIPTION
**Pull request by dannykopping**
On Windows, `pty.New()` was creating a `ConPTY` (`PseudoConsole`) even when no process would be attached. `ConPTY` requires a real process to function correctly - without one, the pipe handles become invalid intermittently, causing flaky test failures like `read |0: The handle is invalid.`
                                                                                                                                                                                                                                                                                       
This affected tests using the `ptytest.New()` + `Attach()` pattern for in-process CLI testing.                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                       
The fix splits Windows PTY creation into two paths:                                                                                                                                                                                                                                    
- `newPty()` now returns a simple pipe-based PTY for the `Attach()` use case                                                                                                                                                                                                               
- `newConPty()` creates a real `ConPTY`, called by `Start()` when a process will be attached
                                                                                                                                                                                                                                                                                       
AFAICT this will result in no change in behaviour outside of tests.

Fixes coder/internal#1277   

_Disclaimer: investigated and implemented by Claude Opus 4.5, reviewed by me._

### CODE REVIEW

File: pty/pty_windows.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ var (
 )
 
 // See: https://docs.microsoft.com/en-us/windows/console/creating-a-pseudoconsole-session
-func newPty(opt ...Option) (*ptyWindows, error) {
+func newPty(opt ...Option) (PTY, error) {
```
Comment (johnstcn) [inline pty/pty_windows.go:25]: It's not immediately obvious new that `newPty` returns a type that should **only be used in tests**.

File: pty/pty_windows.go [hunk 2]
```diff
@@ -83,6 +101,93 @@ func newPty(opt ...Option) (*ptyWindows, error) {
...
+	// The pipe for "output" - what would be stdout for a process.
+	// CLI writes to outputWriter, test reads from outputReader.
+	outputReader *os.File
+	outputWriter *os.File
+
+	closeMutex sync.Mutex
+	closed     bool
+}
+
+func newPipePty() (*pipePty, error) {
```
Comment (johnstcn) [inline pty/pty_windows.go]: Since `pipePty` is only meant to be used in tests, `newPipePty` should probably have a `*testing.T` argument. I would also argue in favour of moving this to the `ptytest` package.

**Review by johnstcn — COMMENTED** [review]
I'm in favour of the spirit of the change, but the new implementation is not sufficiently clear about its intended purpose IMO.

File: pty/pty_windows.go (hunk 1 above)
Comment (dannykopping) [reply pty/pty_windows.go:25]: Addressed in 939ab2798.

File: pty/pty_windows.go (hunk 2 above)
Comment (dannykopping) [reply pty/pty_windows.go]: Addressed in 939ab2798; I think this is probably clear enough? WDYT?

Edit: on second thought, I'll look into the feasibility of moving it to `ptytest`; it'll fit better there.

Comment (dannykopping) [reply pty/pty_windows.go]: @johnstcn is 354d3ef44 to your liking?

File: pty/pty_windows.go [hunk 3]
```diff
@@ -37,6 +37,21 @@ func newPty(opt ...Option) (*ptyWindows, error) {
 		return nil, xerrors.Errorf("pty not supported")
 	}
 
+	// On Windows, pty.New() without Start() is only used by ptytest.New() for
+	// in-process CLI testing. ConPTY requires an attached process to function
+	// correctly, so ptytest has its own pipe-based implementation. Production
+	// code should use pty.Start() which creates a ConPTY with process attached.
+	return nil, xerrors.Errorf("pty without process not supported on Windows; use ptytest.New() for tests")
+}
```
Comment (johnstcn) [inline pty/pty_windows.go:45]: Shouldn't this just return `newConPty(opt)`?

Comment (dannykopping) [reply pty/pty_windows.go:45]: I don't think so; the API is a bit odd to me TBH.
`pty.New` is only used by tests it seems, so therefore we should discourage a parallel use-case alongside `Start()`.

Comment (johnstcn) [reply pty/pty_windows.go:45]: Ah, that's definitely confusing. I don't think you need to address that in this PR, but we should probably make this abundantly obvious somehow.

**Review by johnstcn — APPROVED** [review]
LGTM 👍
