### PR TITLE
fix(site): Fix terminal elements size

### LINKED ISSUE #7507: "startup script is still running" cuts off bottom of terminal
Screenshot 2023-05-11 at 7 38 40 PM

when using vim, you have to scroll to see the bottom

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix #7507

Screen Shot 2023-05-15 at 09 25 44

### CODE REVIEW

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 1]
```diff
@@ -313,34 +314,40 @@ const TerminalPage: FC<
...
+        {shouldDisplayStartupWarning && (
+          <div className={styles.alert} role="alert">
+            <WarningIcon className={styles.alertIcon} />
+            <div>
+              <div className={styles.alertTitle}>
+                Startup script is still running
+              </div>
+              <div className={styles.alertMessage}>
+                You can continue using this terminal, but something may be
+                missing or not fully set up.
```
Comment (Kira-Pilot) [inline site/src/pages/TerminalPage/TerminalPage.tsx:327]: Is there a more specific error message we can give the user at this point, or no? E.g. "You can continue to use this terminal, but cluster configuration has not yet completed and some functionality may be missing."

**Review by Kira-Pilot — APPROVED** [review]

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 1 above)
Comment (bpmct) [reply site/src/pages/TerminalPage/TerminalPage.tsx:327]: It's difficult to predict what the exact behavior would be, because the startup script is defined by the template admin and in some cases, the user as well. For example, the startup script may be responsible for installing packages, cloning repositories, or setting a default shell. It's best to look at the startup logs (on the workspace page) to see what is still hanging.

Comment (bpmct) [reply site/src/pages/TerminalPage/TerminalPage.tsx:327]: In cases where it is still running, it could be as simple as "your shell is bash, not zsh until you refresh" or more important to a workflow such as "the repo hasn't even been cloned yet so you can't start your work"

Comment (Kira-Pilot) [reply site/src/pages/TerminalPage/TerminalPage.tsx:327]: Gotcha! Maybe we could prompt the user to look at the startup logs to get a better sense of what's going on.
