### PR TITLE
fix: accumulate agentstats until reported and fix insights DAU offset

### LINKED ISSUE #259: flake: `TestDeploymentInsights` timeout
Seen here: https://github.com/coder/coder/actions/runs/12245804266/job/34234808558?pr=15771

Wall of text, but this seems to be a pattern:

```
   t.go:106: 2024-12-11 05:15:06.568 [debu]  agentrpc: read stats report  owner=testuser  workspace_name=magical-wiles5-gMh  agent_name=example  request_id=59e7ebb5-fdc9-4508-bee8-a0b071ec3235  interval=100ms  workspace_id=0d11109a-8e32-4a3c-9280-38f9f1518cfa  payload="stats:{connection_median_latency_ms:0.368 session_count_ssh:1 metrics:{name:\"derp_home_change\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_errors\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_matches\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_mismatches\" type:COUNTER} metrics:{name:\"issue_869_workaround\" type:COUNTER} metrics:{name:\"magicdns_packet_in\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_key\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_parse\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_peer\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_recv_bpf_ipv4\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bpf_ipv6\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_callmemaybe\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_recv_callmemaybe_bad_disco\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_callmemaybe_bad_node\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_recv_derp_peer_gone_unknown\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_derp_peer_not_here\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_ping\" type:COUNTER value:163} metrics:{name:\"magicsock_disco_recv_pong\" type:COUNTER value:161} metrics:{name:\"magicsock_disco_recv_udp\" type:COUNTER value:322} metrics:{name:\"magicsock_disco_send_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_send_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_disco_sent_callmemaybe\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_sent_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_sent_ping\" type:COUNTER value:169} metrics:{name:\"magicsock_disco_sent_pong\" type:COUNTER value:163} metrics:{name:\"magicsock_disco_sent_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_netmap_num_peers\" type:GAUGE} metrics:{name:\"magicsock_num_derp_conns\" type:GAUGE value:1} metrics:{name:\"magicsock_rebind_calls\" type:COUNTER} metrics:{name:\"magicsock_recv_data_derp\" type:COUNTER value:79} metrics:{name:\"magicsock_recv_data_ipv4\" type:COUNTER value:358} metrics:{name:\"magicsock_recv_data_ipv6\" type:COUNTER} metrics:{name:\"magicsock_restun_calls\" type:COUNTER value:186} metrics:{name:\"magicsock_send_data\" type:COUNTER value:438} metrics:{name:\"magicsock_send_data_network_down\" type:COUNTER} metrics:{name:\"magicsock_send_derp\" type:COUNTER value:90} metrics:{name:\"magicsock_send_derp_error\" type:COUNTER} metrics:{name:\"magicsock_send_derp_error_chan\" type:COUNTER value:3} metrics:{name:\"magicsock_send_derp_error_closed\" type:COUNTER} metrics:{name:\"magicsock_send_derp_error_queue\" type:COUNTER} metrics:{name:\"magicsock_send_derp_queued\" type:COUNTER value:90} metrics:{name:\"magicsock_send_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_send_udp_error\" type:COUNTER} metrics:{name:\"magicsock_update_endpoints\" type:COUNTER value:194} metrics:{name:\"netcheck_https_measure\" type:COUNTER value:60} metrics:{name:\"netcheck_report\" type:COUNTER value:66} metrics:{name:\"netcheck_report_error\" type:COUNTER} metrics:{name:\"netcheck_report_full\" type:COUNTER value:38} metrics:{name:\"netcheck_stun_recv_ipv4\" type:COUNTER value:152} metrics:{name:\"netcheck_stun_recv_ipv6\" type:COUNTER} metrics:{name:\"netcheck_stun_send_ipv4\" type:COUNTER value:126} metrics:{name:\"netcheck_stun_send_ipv6\" type:COUNTER} metrics:{name:\"packet_reflect_to_os\" type:COUNTER} metrics:{name:\"portmap_pcp_address_mismatch\" type:COUNTER} metrics:{name:\"portmap_pcp_not_authorized\" type:COUNTER} metrics:{name:\"portmap_pcp_ok\" type:COUNTER} metrics:{name:\"portmap_pcp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_pcp_unhandled_response_code\" type:COUNTER} metrics:{name:\"portmap_pmp_network_failure\" type:COUNTER} metrics:{name:\"portmap_pmp_not_authorized\" type:COUNTER} metrics:{name:\"portmap_pmp_ok\" type:COUNTER} metrics:{name:\"portmap_pmp_out_of_resources\" type:COUNTER} metrics:{name:\"portmap_pmp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_pmp_unhandled_opcode\" type:COUNTER} metrics:{name:\"portmap_pmp_unhandled_response_code\" type:COUNTER} metrics:{name:\"portmap_pxp_response\" type:COUNTER} metrics:{name:\"portmap_upnp_ok\" type:COUNTER} metrics:{name:\"portmap_upnp_parse_err\" type:COUNTER} metrics:{name:\"portmap_upnp_response\" type:COUNTER} metrics:{name:\"portmap_upnp_response_alternate_port\" type:COUNTER} metrics:{name:\"portmap_upnp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_upnp_updated_meta\" type:COUNTER} metrics:{name:\"wgengine_major_changes\" type:COUNTER} metrics:{name:\"wgengine_minor_changes\" type:COUNTER} metrics:{name:\"agent_reconnecting_pty_connections_total\" type:COUNTER} metrics:{name:\"agent_sessions_total\" type:COUNTER value:1 labels:{name:\"magic_type\" value:\"ssh\"} labels:{name:\"pty\" value:\"no\"}} metrics:{name:\"agent_ssh_server_failed_connections_total\" type:COUNTER} metrics:{name:\"agent_ssh_server_sftp_connections_total\" type:COUNTER} metrics:{name:\"agent_ssh_server_sftp_server_errors_total\" type:COUNTER} metrics:{name:\"coderd_agentstats_currently_reachable_peers\" type:GAUGE labels:{name:\"connection_type\" value:\"derp\"}} metrics:{name:\"coderd_agentstats_currently_reachable_peers\" type:GAUGE value:1 labels:{name:\"connection_type\" value:\"p2p\"}} metrics:{name:\"coderd_agentstats_startup_script_seconds\" type:GAUGE value:3.33e-07 labels:{name:\"success\" value:\"true\"}}}"
    t.go:106: 2024-12-11 05:15:06.568 [debu]  agentrpc: drpc server error  owner=testuser  workspace_name=magical-wiles5-gMh  agent_name=example  request_id=59e7ebb5-fdc9-4508-bee8-a0b071ec3235 ...
        error= context canceled
               	storj.io/drpc/drpcserver.(*Server).handleRPC:128
               	storj.io/drpc/drpcserver.(*Server).ServeOne:66
               	storj.io/drpc/drpcserver.(*Server).Serve.func2:114
               	storj.io/drpc/drpcctx.(*Tracker).track:35
    t.go:106: 2024-12-11 05:15:06.600 [debu]  dbrollup: rolling up data
```

Not sure who to assign this to, so assigned @mafredri since you're mostly the insights owner - but feel free to reallocate if this is in error.

### LINKED ISSUE #15824: flake: `TestDeploymentInsights` timeout
Seen here: https://github.com/coder/coder/actions/runs/12245804266/job/34234808558?pr=15771

Wall of text, but this seems to be a pattern:

```
   t.go:106: 2024-12-11 05:15:06.568 [debu]  agentrpc: read stats report  owner=testuser  workspace_name=magical-wiles5-gMh  agent_name=example  request_id=59e7ebb5-fdc9-4508-bee8-a0b071ec3235  interval=100ms  workspace_id=0d11109a-8e32-4a3c-9280-38f9f1518cfa  payload="stats:{connection_median_latency_ms:0.368 session_count_ssh:1 metrics:{name:\"derp_home_change\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_errors\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_matches\" type:COUNTER} metrics:{name:\"dnsfallback_recursive_mismatches\" type:COUNTER} metrics:{name:\"issue_869_workaround\" type:COUNTER} metrics:{name:\"magicdns_packet_in\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_key\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_parse\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bad_peer\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_recv_bpf_ipv4\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_bpf_ipv6\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_callmemaybe\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_recv_callmemaybe_bad_disco\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_callmemaybe_bad_node\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_recv_derp_peer_gone_unknown\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_derp_peer_not_here\" type:COUNTER} metrics:{name:\"magicsock_disco_recv_ping\" type:COUNTER value:163} metrics:{name:\"magicsock_disco_recv_pong\" type:COUNTER value:161} metrics:{name:\"magicsock_disco_recv_udp\" type:COUNTER value:322} metrics:{name:\"magicsock_disco_send_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_send_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_disco_sent_callmemaybe\" type:COUNTER value:11} metrics:{name:\"magicsock_disco_sent_derp\" type:COUNTER value:13} metrics:{name:\"magicsock_disco_sent_ping\" type:COUNTER value:169} metrics:{name:\"magicsock_disco_sent_pong\" type:COUNTER value:163} metrics:{name:\"magicsock_disco_sent_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_netmap_num_peers\" type:GAUGE} metrics:{name:\"magicsock_num_derp_conns\" type:GAUGE value:1} metrics:{name:\"magicsock_rebind_calls\" type:COUNTER} metrics:{name:\"magicsock_recv_data_derp\" type:COUNTER value:79} metrics:{name:\"magicsock_recv_data_ipv4\" type:COUNTER value:358} metrics:{name:\"magicsock_recv_data_ipv6\" type:COUNTER} metrics:{name:\"magicsock_restun_calls\" type:COUNTER value:186} metrics:{name:\"magicsock_send_data\" type:COUNTER value:438} metrics:{name:\"magicsock_send_data_network_down\" type:COUNTER} metrics:{name:\"magicsock_send_derp\" type:COUNTER value:90} metrics:{name:\"magicsock_send_derp_error\" type:COUNTER} metrics:{name:\"magicsock_send_derp_error_chan\" type:COUNTER value:3} metrics:{name:\"magicsock_send_derp_error_closed\" type:COUNTER} metrics:{name:\"magicsock_send_derp_error_queue\" type:COUNTER} metrics:{name:\"magicsock_send_derp_queued\" type:COUNTER value:90} metrics:{name:\"magicsock_send_udp\" type:COUNTER value:330} metrics:{name:\"magicsock_send_udp_error\" type:COUNTER} metrics:{name:\"magicsock_update_endpoints\" type:COUNTER value:194} metrics:{name:\"netcheck_https_measure\" type:COUNTER value:60} metrics:{name:\"netcheck_report\" type:COUNTER value:66} metrics:{name:\"netcheck_report_error\" type:COUNTER} metrics:{name:\"netcheck_report_full\" type:COUNTER value:38} metrics:{name:\"netcheck_stun_recv_ipv4\" type:COUNTER value:152} metrics:{name:\"netcheck_stun_recv_ipv6\" type:COUNTER} metrics:{name:\"netcheck_stun_send_ipv4\" type:COUNTER value:126} metrics:{name:\"netcheck_stun_send_ipv6\" type:COUNTER} metrics:{name:\"packet_reflect_to_os\" type:COUNTER} metrics:{name:\"portmap_pcp_address_mismatch\" type:COUNTER} metrics:{name:\"portmap_pcp_not_authorized\" type:COUNTER} metrics:{name:\"portmap_pcp_ok\" type:COUNTER} metrics:{name:\"portmap_pcp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_pcp_unhandled_response_code\" type:COUNTER} metrics:{name:\"portmap_pmp_network_failure\" type:COUNTER} metrics:{name:\"portmap_pmp_not_authorized\" type:COUNTER} metrics:{name:\"portmap_pmp_ok\" type:COUNTER} metrics:{name:\"portmap_pmp_out_of_resources\" type:COUNTER} metrics:{name:\"portmap_pmp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_pmp_unhandled_opcode\" type:COUNTER} metrics:{name:\"portmap_pmp_unhandled_response_code\" type:COUNTER} metrics:{name:\"portmap_pxp_response\" type:COUNTER} metrics:{name:\"portmap_upnp_ok\" type:COUNTER} metrics:{name:\"portmap_upnp_parse_err\" type:COUNTER} metrics:{name:\"portmap_upnp_response\" type:COUNTER} metrics:{name:\"portmap_upnp_response_alternate_port\" type:COUNTER} metrics:{name:\"portmap_upnp_sent\" type:COUNTER value:66} metrics:{name:\"portmap_upnp_updated_meta\" type:COUNTER} metrics:{name:\"wgengine_major_changes\" type:COUNTER} metrics:{name:\"wgengine_minor_changes\" type:COUNTER} metrics:{name:\"agent_reconnecting_pty_connections_total\" type:COUNTER} metrics:{name:\"agent_sessions_total\" type:COUNTER value:1 labels:{name:\"magic_type\" value:\"ssh\"} labels:{name:\"pty\" value:\"no\"}} metrics:{name:\"agent_ssh_server_failed_connections_total\" type:COUNTER} metrics:{name:\"agent_ssh_server_sftp_connections_total\" type:COUNTER} metrics:{name:\"agent_ssh_server_sftp_server_errors_total\" type:COUNTER} metrics:{name:\"coderd_agentstats_currently_reachable_peers\" type:GAUGE labels:{name:\"connection_type\" value:\"derp\"}} metrics:{name:\"coderd_agentstats_currently_reachable_peers\" type:GAUGE value:1 labels:{name:\"connection_type\" value:\"p2p\"}} metrics:{name:\"coderd_agentstats_startup_script_seconds\" type:GAUGE value:3.33e-07 labels:{name:\"success\" value:\"true\"}}}"
    t.go:106: 2024-12-11 05:15:06.568 [debu]  agentrpc: drpc server error  owner=testuser  workspace_name=magical-wiles5-gMh  agent_name=example  request_id=59e7ebb5-fdc9-4508-bee8-a0b071ec3235 ...
        error= context canceled
               	storj.io/drpc/drpcserver.(*Server).handleRPC:128
               	storj.io/drpc/drpcserver.(*Server).ServeOne:66
               	storj.io/drpc/drpcserver.(*Server).Serve.func2:114
               	storj.io/drpc/drpcctx.(*Tracker).track:35
    t.go:106: 2024-12-11 05:15:06.600 [debu]  dbrollup: rolling up data
```

Not sure who to assign this to, so assigned @mafredri since you're mostly the insights owner - but feel free to reallocate if this is in error.

### PR DESCRIPTION
**Pull request by mafredri**
This PR addresses a flake in `TestDeploymentInsights` caused by missing agent network stats. It also fixes the assumption that we should discard and not accumulate agent network stats if we can't keep up. Without accumulation we risk losing data.

Fixes coder/internal#259

### CODE REVIEW

File: coderd/insights.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func (api *API) returnDAUsInternal(rw http.ResponseWriter, r *http.Request, temp
 	}
 	for _, row := range rows {
 		resp.Entries = append(resp.Entries, codersdk.DAUEntry{
-			Date:   row.StartTime.Format(time.DateOnly),
+			Date:   row.StartTime.In(loc).Format(time.DateOnly),
```
Comment (mafredri) [inline coderd/insights.go:92]: Review: Drive-by fix, the date was off-by-one depending on timezone.

File: agent/stats.go [hunk 2]
```diff
@@ -54,8 +55,18 @@ func (s *statsReporter) callback(_, _ time.Time, virtual, _ map[netlogtype.Conne
...
+		if s.networkStats == nil && virtual != nil {
+			s.networkStats = make(map[netlogtype.Connection]netlogtype.Counts)
+		}
+		for k, v := range virtual {
+			s.networkStats[k] = s.networkStats[k].Add(v)
+		}
+	} else {
+		s.networkStats = maps.Clone(virtual)
+		s.unreported = true
+	}
```
Comment (mafredri) [inline agent/stats.go:69]: Review: If the callback was called multiple times before reporting, we lost data as each update is a snapshot since the last.

This can happen if:
1. The interval is short (tests)
2. Report takes a long time

File: coderd/insights_test.go [hunk 3]
```diff
@@ -48,16 +48,26 @@ func TestDeploymentInsights(t *testing.T) {
 	db, ps := dbtestutil.NewDB(t, dbtestutil.WithDumpOnFailure())
 	logger := testutil.Logger(t)
 	rollupEvents := make(chan dbrollup.Event)
+	statsInterval := 500 * time.Millisecond
+	batcher, closeBatcher, err := workspacestats.NewBatcher(context.Background(),
+		workspacestats.BatcherWithLogger(logger.Named("batcher").Leveled(slog.LevelDebug)),
+		workspacestats.BatcherWithStore(db),
+		workspacestats.BatcherWithBatchSize(1),
+		workspacestats.BatcherWithInterval(statsInterval),
```
Comment (mafredri) [inline coderd/insights_test.go:56]: Review: Manually controlling size and interval to speed up the test.

File: coderd/insights_test.go [hunk 4]
```diff
@@ -76,7 +86,7 @@ func TestDeploymentInsights(t *testing.T) {
 	workspace := coderdtest.CreateWorkspace(t, client, template.ID)
 	coderdtest.AwaitWorkspaceBuildJobCompleted(t, client, workspace.LatestBuild.ID)
 
-	ctx := testutil.Context(t, testutil.WaitLong)
+	ctx := testutil.Context(t, testutil.WaitSuperLong)
```
Comment (mafredri) [inline coderd/insights_test.go:89]: In race mode, propagating the agent connection stats can take a while.

File: agent/stats.go [hunk 5]
```diff
@@ -54,8 +55,18 @@ func (s *statsReporter) callback(_, _ time.Time, virtual, _ map[netlogtype.Conne
 	s.L.Lock()
 	defer s.L.Unlock()
 	s.logger.Debug(context.Background(), "got stats callback")
-	s.networkStats = &virtual
-	s.unreported = true
+	// Accumulate stats until they've been reported.
+	if s.unreported {
+		if s.networkStats == nil && virtual != nil {
+			s.networkStats = make(map[netlogtype.Connection]netlogtype.Counts)
```
Comment (dannykopping) [inline agent/stats.go:61]: Nit: let's save some allocations.

```suggestion
			s.networkStats = make(map[netlogtype.Connection]netlogtype.Counts, len(virtual))
```

File: agent/stats.go (hunk 2 above)
Comment (dannykopping) [reply agent/stats.go:69]: Great catch!

File: coderd/insights_test.go (hunk 3 above)
Comment (dannykopping) [reply coderd/insights_test.go:56]: Maybe this would be better as an inline comment?

File: coderd/insights_test.go [hunk 6]
```diff
@@ -108,6 +118,13 @@ func TestDeploymentInsights(t *testing.T) {
 	err = sess.Start("cat")
 	require.NoError(t, err)
 
+	select {
+	case <-ctx.Done():
+		require.Fail(t, "timed out waiting for initial rollup event")
```
Comment (dannykopping) [inline coderd/insights_test.go:123]:
```suggestion
		require.Failf(t, "timed out waiting for initial rollup event: %s", ctx.Err())
```

**Review by dannykopping — APPROVED** [review]
LGTM

File: agent/stats.go (hunk 5 above)
Comment (mafredri) [reply agent/stats.go]: I've never actually benchmarked how much a difference a size hint gives for maps, especially ones that don't have a lot of data. Is there a significant difference?

Your suggestion made me realize this had a better fix 😄.

**Review by dannykopping — APPROVED** [review]
LGTM
