### PR TITLE
fix: move contexts to appropriate locations

### LINKED ISSUE #1173: flake: `TestExpRpty/Container`
```
    ptytest.go:167: 2025-12-04 09:41:17.924: cmd: read error: match deadline exceeded: context deadline exceeded (wanted " #"; got "")
    ptytest.go:167: 
        	Error Trace:	/home/runner/work/coder/coder/pty/ptytest/ptytest.go:372
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:196
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:167
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:162
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:149
        	            				/home/runner/work/coder/coder/cli/exp_rpty_test.go:136
        	Error:      	read error
        	Test:       	TestExpRpty/Container
        	Messages:   	match deadline exceeded: context deadline exceeded (wanted " #"; got "")
```

Seen in https://github.com/coder/coder/actions/runs/19924364267/job/57120337027

### LINKED ISSUE #1174: flake: `TestSSH_Container/OK`
```
    clitest.go:86: invoking command: coder --global-config /tmp/TestSSH_ContainerOK3829723581/003 ssh myworkspace -c 2ceefe1796756e37719399b44933e17840da640e4a12fdd7b611a5b16ceb3e91
    t.go:109: 2025-12-04 09:40:59.088 [erro]  cli: command exit  error="Get \"http://127.0.0.1:38281/api/v2/users/me/workspace/myworkspace?include_deleted=false\": context deadline exceeded"
    ssh_test.go:2092: 
        	Error Trace:	/home/runner/work/coder/coder/cli/ssh_test.go:2092
        	            				/home/runner/work/coder/coder/cli/ssh_test.go:2421
        	            				/opt/hostedtoolcache/go/1.24.10/x64/src/runtime/asm_amd64.s:1700
        	Error:      	Received unexpected error:
        	            	running command "coder ssh": Get "http://127.0.0.1:38281/api/v2/users/me/workspace/myworkspace?include_deleted=false": context deadline exceeded
        	Test:       	TestSSH_Container/OK
...
    ptytest.go:167: 2025-12-04 09:41:14.086: cmd: read error: match deadline exceeded: context deadline exceeded (wanted " #"; got "")
    ptytest.go:167: 
        	Error Trace:	/home/runner/work/coder/coder/pty/ptytest/ptytest.go:372
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:196
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:167
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:162
        	            				/home/runner/work/coder/coder/pty/ptytest/ptytest.go:149
        	            				/home/runner/work/coder/coder/cli/ssh_test.go:2095
        	Error:      	read error
        	Test:       	TestSSH_Container/OK
        	Messages:   	match deadline exceeded: context deadline exceeded (wanted " #"; got "")
```

Seen in https://github.com/coder/coder/actions/runs/19924364267/job/57120336964

### PR DESCRIPTION
**Pull request by dannykopping**
Closes https://github.com/coder/internal/issues/1173
Closes https://github.com/coder/internal/issues/1174

Currently these two tests are flaky because the contexts were created before a potentially long-running process. By the time the context was actually used, it may have timed out - leading to confusion.

Additionally, the `ExpectMatch` calls were not using the test context - but rather a background context. I've marked that func as deprecated because we should always tie these to the test context.

Special thanks to @mafredri for the brain probe 🧠

### CODE REVIEW

File: pty/ptytest/ptytest.go [hunk 1]
```diff
@@ -145,6 +145,8 @@ type outExpecter struct {
 	runeReader *bufio.Reader
 }
 
+// Deprecated: use ExpectMatchContext instead.
+// This uses a background context, so will not respect the test's context.
```
Comment (mafredri) [inline pty/ptytest/ptytest.go:149]: ❤️

**Review by mafredri — APPROVED** [review]
