### PR TITLE
fix: ensure listen websocket isn't opened for non-latest agents

### LINKED ISSUE #2004: Bug: Ensure agent websockets from outdated builds are rejected before websocket is opened
Exponential backoff is only enabled if the websocket fails to open. If
the websocket is opened but immediately killed, the agent will try to
immediately reconnect. This is desireable in cases where coderd is being
replaced or network conditions cause the connection to die, but not for
permanent errors

### PR DESCRIPTION
**Pull request by coadler**
Exponential backoff is only enabled for if the websocket fails to open.
If the websocket is opened but immediately killed, the agent will try to
immediately reconnect. This is desireable in cases where coderd is being
replaced or network conditions cause the connection to die.

### CODE REVIEW

File: coderd/workspaceagents.go [hunk 1]
```diff
@@ -143,16 +143,49 @@ func (api *API) workspaceAgentListen(rw http.ResponseWriter, r *http.Request) {
...
+		}
+		if build.ID != latestBuild.ID {
+			return xerrors.New("build is outdated")
+		}
+		return nil
+	}
+
+	err = ensureLatestBuild()
+	if err != nil {
+		api.Logger.Debug(r.Context(), "agent connected from non-latest built",
```
Comment (kylecarbs) [inline coderd/workspaceagents.go:176]: We might say `tried to connect` instead, because it didn't actually connect.

**Review by kylecarbs — APPROVED** [review]
