### PR TITLE
fix: resolve overflow on `<TemplateInsightsPage />` `Parameters usage`

### LINKED ISSUE #19954: bug: overflow in Template insights UI
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Template insights for some coder parameter overflow the table width

Image

### Relevant Log Output

```shell
N/A
```

### Expected Behavior

Long lines should nicely overlap

### Steps to Reproduce

Go to a Template Insights tab for any template that has a long text for the `coder_parameter` value of type string. 

### Environment

- Coder version: [v2.26.0-devel+b712e975d](https://github.com/coder/coder/commit/b712e975d56412d6acc820267b678c6db1f3c0a4)

### Additional Context

The issue occurs consistently, The issue happens on multiple deployments, I have tested this on the latest version

### PR DESCRIPTION
**Pull request by jakehwll**
Closes #19954 

This pull-request ensures content doesn't overflow the screen when looking at `Parameters usage` in `<TemplateInsightsPage />`. 

| Old | New |
| --- | --- | 
| TEMPLATE_ANALYTICS_OLD | TEMPLATE_ANALYTICS_NEW |

### CODE REVIEW

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx [hunk 1]
```diff
@@ -505,29 +510,38 @@ const TemplateParametersUsagePanel: FC<TemplateParametersUsagePanelProps> = ({
...
-											<div>Count</div>
-										</TooltipTrigger>
-										<TooltipContent>
-											The number of workspaces using this value
-										</TooltipContent>
-									</Tooltip>
-								</ParameterUsageRow>
+							<div
+								className="flex-1 text-sm grid grid-cols-[1fr_auto] gap-x-4 items-baseline"
+								style={{ flexGrow: 2 }}
```
Comment (DanielleMaywood) [inline site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx]:
```suggestion
								className="flex-1 grow-2 text-sm grid grid-cols-[1fr_auto] gap-x-4 items-baseline"
```

**Review by DanielleMaywood — APPROVED** [review]

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx (hunk 1 above)
Comment (jakehwll) [reply site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx]: Damnit, I checked the imports for `@mui/` but didn't look for`css={}`...

You win this time 🤭
