### PR TITLE
fix(site): show error on duplicate template rename attempt

### LINKED ISSUE #15311: 500 Error on Duplicate Template Name Change, No UI Error Displayed
When selecting a template from the template list, opening "Settings," and attempting to change the name to one that already exists, the API returns a 500 error with the following message. However, there is no error displayed in the UI, making it difficult to understand the issue.

```json
{
    "message": "An internal server error occurred.",
    "detail": "execute transaction: update template metadata: pq: duplicate key value violates unique constraint \"templates_organization_id_name_idx\""
}
```

This text was translated from Japanese to English using ChatGPT, so there may be minor contextual inaccuracies. Thank you for your understanding.

### PR DESCRIPTION
**Pull request by ethanndickson**
Fixes #15311.

image

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#15348** <a href="https://app.graphite.dev/github/pr/coder/coder/15348?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ethanndickson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: coderd/templates.go [hunk 1]
```diff
@@ -841,7 +841,17 @@ func (api *API) patchTemplateMeta(rw http.ResponseWriter, r *http.Request) {
 		return nil
 	}, nil)
 	if err != nil {
-		httpapi.InternalServerError(rw, err)
+		if database.IsUniqueViolation(err) {
+			httpapi.Write(ctx, rw, http.StatusConflict, codersdk.Response{
+				Message: fmt.Sprintf("Template %q already exists.", req.Name),
```
Comment (ethanndickson) [inline coderd/templates.go:846]: Definitely out of scope of this PR, but it might be good to have some centralised mapping of database violations to human readable error messages.

**Comment by BrunoQuaresma** [comment]
@ethanndickson the PR looks good but I'm missing tests for FE and BE

File: coderd/templates_test.go [hunk 2]
```diff
@@ -612,6 +613,32 @@ func TestPatchTemplateMeta(t *testing.T) {
 		assert.Equal(t, database.AuditActionWrite, auditor.AuditLogs()[4].Action)
 	})
 
+	t.Run("AlreadyExists", func(t *testing.T) {
+		t.Parallel()
+
+		if !dbtestutil.WillUsePostgres() {
+			t.Skip("This test requires Postgres constraints")
+		}
```
Comment (ethanndickson) [inline coderd/templates_test.go:621]: `dbmem` is getting removed in the near future, where this'll get removed too.

**Review by BrunoQuaresma — APPROVED** [review]
Awesome, ty!
