### PR TITLE
fix: locate Terraform entrypoint file

### LINKED ISSUE #16360: Wrong `main.tf` file can be auto-selected when opening template in built-in web editor
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When a user goes to open a template from within our built-in template editor, it tries to auto-select the `main.tf` file, as that will likely be there the majority of the code will live. This works fine for simpler templates.

The problem is that, when you have multiple `main.tf` files (e.g., one at the root directory, and another in a sub-directory), the auto-selection logic seems to try to select the first `main.tf` file it can find. As subdirectories are listed first in the editor, that means that the less relevant, secondary `main.tf` file will always be selected, and the user has to click the correct one.

### Relevant Log Output
N/A

### Expected Behavior

When a user opens a template in the built-in editor, the auto-selection logic will favor the `main.tf` file at the root directory (if it exists). All other `main.tf` files will not be eligible for auto-selection, so if the root file is missing, the main text area will start off empty.

### Steps to Reproduce

1. Create a template with two `main.tf` files. One should go in the root directory, and the other should go in a subdirectory
2. Open the template in the built-in web editor
3. See that the subdirectory's `main.tf` file is selected, even if it barely has any bearing on the overall template functionality

Note for Dogfood: this already applies to the current Coder on Coder template 

### Environment

- Host OS: Dogfood
- Coder version: v2.18.5

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/16360

This PR updates the template version editor code to accurately identify the Terraform entrypoint file.

### CODE REVIEW

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx [hunk 1]
```diff
@@ -357,10 +357,33 @@ const publishVersion = async (options: {
...
+	traverse(fileTree, (_, filename, path) => {
+		if (skip) {
+			return;
+		}
+
+		if (filename === defaultMainTerraformFile) {
+			initialFile = path;
+			skip = true;
+			return;
+		}
```
Comment (johnstcn) [inline site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:385]: What is the order in which `traverse()` will traverse the nodes of `fileTree`? Are child paths sorted prior to being added to the frontier? In other words, if you have both `a/main.tf` and `z/main.tf`, which will get chosen? I know you have a test above, but is the output dependant on the ordering of the nodes? Is it just "first found wins"?

Comment (mtojek) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:385]: Let me expand `traverse()` with sorting capabilities.

Comment (mtojek) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:385]: Done

Comment (johnstcn) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:385]: nice 👍

**Review by johnstcn — APPROVED** [review]

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx [hunk 2]
```diff
@@ -90,7 +90,7 @@ export const TemplateVersionEditorPage: FC = () => {
 	// File navigation
 	// It can be undefined when a selected file is deleted
 	const activePath: string | undefined =
-		searchParams.get("path") ?? findInitialFile(fileTree ?? {});
+		searchParams.get("path") ?? findEntrypointFile(fileTree ?? {});
```
Comment (Parkreiner) [inline site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:93]: Do you know what happens if `searchParams.get` returns an empty string or a string that isn't a valid filename? That would short-circuit the nullish expression and prevent `findEntrypointFile` from ever being called, and as far as I can tell, that value would be fed directly into the editor

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx [hunk 3]
```diff
@@ -357,10 +357,33 @@ const publishVersion = async (options: {
...
 
-const findInitialFile = (fileTree: FileTree): string | undefined => {
+const defaultMainTerraformFile = "main.tf";
+
+// findEntrypointFile function locates the entrypoint file to open in the Editor.
+// It browses the filetree following these steps:
+// 1. If "main.tf" exists in root, return it.
+// 2. Traverse through sub-directories.
+// 3. If "main.tf" exists in a sub-directory, skip further browsing, and return the path.
+// 4. If "main.tf" was not found, return the last reviewed "".tf" file.
```
Comment (Parkreiner) [inline site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:367]: With the sorting in place now, I feel like it would've helped to clarify what "last reviewed" means, especially to help make it clear that the tests are actually deterministic

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx (hunk 2 above)
Comment (mtojek) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:93]: nice catch! let me look into this 👍

Comment (mtojek) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx:93]: https://github.com/coder/coder/pull/16757
