### PR TITLE
fix(site): Fix missing parameters detection on update workspace

### LINKED ISSUE #6734: rich parameters: can't migrate to the template with coder_parameters
Hi,

Screenshot 2023-03-22 at 17 19 19

This popup has been introduced to allow users to pass their own values for new required parameters. Unfortunately, it doesn't play well with migration flow. The migration flow assumes that if there is no workspace build parameters, but there is a legacy variable property present, coder [backend will try](https://github.com/coder/coder/blob/main/coderd/workspacebuilds.go#L505-L516) to pull matching values from legacy parameters.

I guess that one of the options would be skipping rich parameters with extra property (`legacy_variable_name`)?

@bpmct @BrunoQuaresma

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes #6734

### CODE REVIEW

File: site/src/api/api.ts [hunk 1]
```diff
@@ -977,7 +977,10 @@ const getMissingParameters = (
 ) => {
   const missingParameters: TypesGen.TemplateVersionParameter[] = []
   const requiredParameters = templateParameters.filter(
-    (p) => p.required && p.mutable,
+    // It is required
+    // and it can be changed
+    // and it is not from a legacy variable
+    (p) => p.required && p.mutable && p.legacy_variable_name === undefined,
```
Comment (BrunoQuaresma) [inline site/src/api/api.ts:983]: Is this correct @mtojek ?

Comment (mtojek) [reply site/src/api/api.ts:983]: It definitely solved my case :) Thank you

**Review by mtojek — APPROVED** [review]

**Comment by mtojek** [comment]
I hope that you don't mind, Bruno, if I merge this change.
