### PR TITLE
fix(site): use hard reload after login to reload metadata

### LINKED ISSUE #20050: Light Theme setting not respected until Appearance page opened
Version: [`v2.25.1 3bf6a00`](https://github.com/coder/coder/commit/3bf6a008763e2dd1e8829c75d91a0c36c49007c0)

When first opening Coder, I always am in dark mode, despite my settings having light mode set. Once I then go into settings > appearance, it changes automatically on loading that page to light mode. Can this be fixed to be correct from login?

### PR DESCRIPTION
**Pull request by jeremyruppel**
After password login, `navigate('/')` performed a client-side SPA navigation, leaving the pre-authentication `<meta>` tags (including `userAppearance`) empty in the DOM. The `ThemeProvider` read empty metadata and fell through to `DEFAULT_THEME` until the API query resolved, causing a visible flash of the wrong theme. A page refresh fixed it because the server re-rendered HTML with the session cookie present.

Replace `navigate('/')` with `window.location.href` so the server re-renders HTML with all metadata tags populated (`userAppearance`, `user`, `permissions`, etc.) via the new session cookie. This matches the pattern already used for API route redirects on the same page. Also uses `redirectTo` instead of hardcoded "/" so the redirect query parameter is respected for password login.

Fixes https://github.com/coder/coder/issues/20050

> [!NOTE]
> Generated by Coder Agents

<details><summary>Decision log</summary>

- Chose `window.location.href` over invalidating React Query caches because a hard reload is the only way to get fresh server-rendered meta tags. The API query approach still has a flash between mount and response.
- Sanitized redirect URL with `redirectUrl.pathname` (same as existing `<Navigate>` path) to prevent open redirects via absolute URLs.
- Removed unused `useNavigate` import.

</details>

### CODE REVIEW

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 1]
```diff
@@ -87,7 +86,13 @@ const LoginPage: FC = () => {
...
 				onSignIn={async ({ email, password }) => {
 					await signIn(email, password);
-					navigate("/");
+					// Use a hard reload instead of React Router navigation
+					// so the server re-renders the HTML with all metadata
+					// tags populated (userAppearance, user, permissions,
+					// etc.) using the new session cookie.
+					window.location.href = redirectUrl
+						? redirectUrl.pathname
+						: redirectTo;
```
Comment (EhabY) [inline site/src/pages/LoginPage/LoginPage.tsx]: I think we need to sanitize the URL here because otherwise it could be exploited by a malicious actor with a redirect query. This should be something like:

```ts
const sanitizedUrl = new URL(redirectTo, window.location.origin);
window.location.href = sanitizedUrl.pathname + sanitizedUrl.search;
``` 

Taken from L59-L60 ^

Also the redirectUrl queries are dropped here (the example above maintains them)

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 2]
```diff
@@ -87,7 +86,13 @@ const LoginPage: FC = () => {
 				isSigningIn={isSigningIn}
 				onSignIn={async ({ email, password }) => {
 					await signIn(email, password);
-					navigate("/");
```
Comment (EhabY) [inline site/src/pages/LoginPage/LoginPage.tsx:90]: Was this a bug that  it ignored the `redirectTo` query?

File: site/src/pages/LoginPage/LoginPage.test.tsx [hunk 3]
```diff
@@ -121,6 +121,82 @@ describe("LoginPage", () => {
...
+		// HTML with fresh metadata (userAppearance, etc.).
+		await waitFor(() => {
+			expect(locationHrefSpy).toHaveBeenCalledWith("/");
+		});
+
+		// Cleanup
+		Object.defineProperty(window, "location", {
+			configurable: true,
+			value: originalLocation,
+		});
```
Comment (EhabY) [inline site/src/pages/LoginPage/LoginPage.test.tsx:197]: If the test throws (or fails) then this won't happen. Can we do this in a `finally` or maybe even a `afterEach`?

File: site/src/pages/LoginPage/LoginPage.tsx (hunk 2 above)
Comment (jeremyruppel) [reply site/src/pages/LoginPage/LoginPage.tsx:90]: the bug is that we get the user's theme two ways: from the meta tags and from the API, and there is a user flow where we have neither, and so this is why the default theme was being applied.

when the user is logged out, we render the page with empty meta tags

```html
<meta property="userAppearance" content="">
```

if you're signed in, that meta tag is populated with your appearance settings, so we know your theme at page load time. additionally, if you navigate to the appearance settings page, we call the API and update your theme that way too. the issue is, when the user is logged out (so, empty meta tag) and they log in, we do a _client side nav_ which doesn't hit the server, so we don't reload the meta tags, and since we don't call the API until you visit the appearance settings page, this leaves the user with the hardcoded default (dark)

https://github.com/coder/coder/pull/24219 simply makes the default be the user's system pref, which I think is better than defaulting to dark always, but this is the real fix

File: site/src/pages/LoginPage/LoginPage.test.tsx (hunk 3 above)
Comment (jeremyruppel) [reply site/src/pages/LoginPage/LoginPage.test.tsx:197]: good call!

**Comment by aslilac** [comment]
I don't think a hard reload is the elegant solution here. it seems like this means something is broken about the embedded metadata query system that it flickers like that.

**Comment by jeremyruppel** [comment]
> I don't think a hard reload is the elegant solution here. it seems like this means something is broken about the embedded metadata query system that it flickers like that.

maybe (probably) I misunderstand our metadata manager, but after login, doesn't that mean we'd need API calls for each bit of metadata missing from the pre-login page? that seems less elegant to me than just hard navigating and getting all new page state, and more error-prone

File: site/src/utils/redirect.ts [hunk 4]
```diff
@@ -21,3 +21,11 @@ export const retrieveRedirect = (search: string): string => {
 	const redirect = searchParams.get("redirect");
 	return redirect ? redirect : defaultRedirect;
 };
+
+/**
+ * Ensures the redirect is not an open redirect, aka it's relative
+ */
+export const sanitizeRedirect = (redirectTo: string) => {
+	const sanitizedUrl = new URL(redirectTo, window.location.origin);
```
Comment (EhabY) [inline site/src/utils/redirect.ts:29]: Maybe add a test where `redirectTo` causes `new URL` to throw. I think that could happen but I could be mistaken here...

File: site/src/pages/LoginPage/LoginPage.tsx (hunk 2 above)
Comment (EhabY) [reply site/src/pages/LoginPage/LoginPage.tsx:90]: I meant that we navigate to `/` even though the `redirectTo` could be set. But yeah the client side nav seems to be the main issue here, can we not load those meta tag dynamically actually so to not force a reload?

File: site/src/utils/redirect.ts (hunk 4 above)
Comment (aslilac) [inline site/src/utils/redirect.ts]:
```suggestion
	const sanitizedUrl = new URL(redirectTo, location.origin);
```

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 5]
```diff
@@ -87,7 +85,11 @@ const LoginPage: FC = () => {
...
+					// Use a hard reload instead of React Router navigation
+					// so the server re-renders the HTML with all metadata
+					// tags populated (userAppearance, user, permissions,
+					// etc.) using the new session cookie.
+					window.location.href = sanitizeRedirect(redirectTo);
```
Comment (aslilac) [inline site/src/pages/LoginPage/LoginPage.tsx]:
```suggestion
					location.href = sanitizeRedirect(redirectTo);
```

**Review by aslilac — APPROVED** [review]
ok, I've come around to the idea.

just a code style thing: we don't usually use `window.` to access globals, just reach for them directly
