### PR TITLE
test: add mocked terraform installation files

### LINKED ISSUE #72: test flake: TestInstall reaches out over the internet
seen here: https://github.com/coder/coder/actions/runs/10249700468/job/28353691793?pr=14153

```
=== Failed
=== FAIL: provisioner/terraform TestInstall (25.52s)
    install_test.go:44: 
        	Error Trace:	/home/runner/work/coder/coder/provisioner/terraform/install_test.go:44
        	            				/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/asm_amd64.s:1695
        	Error:      	Received unexpected error:
        	            	install:
        	            	    github.com/coder/coder/v2/provisioner/terraform.Install
        	            	        /home/runner/work/coder/coder/provisioner/terraform/install.go:73
        	            	  - Get "https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_SHA256SUMS.72D7468F.sig": net/http: TLS handshake timeout
        	Test:       	TestInstall
    install_test.go:57: 
        	Error Trace:	/home/runner/work/coder/coder/provisioner/terraform/install_test.go:57
        	            				/home/runner/work/coder/coder/provisioner/terraform/install_test.go:86
        	Error:      	Not equal: 
        	            	expected: "/tmp/TestInstall1283833058/001/terraform"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-/tmp/TestInstall1283833058/001/terraform
        	            	+
        	Test:       	TestInstall
        	Messages:   	installs returned different paths
```

### PR DESCRIPTION
**Pull request by pawbana**
Adds mocked terraform installation files and uses them in provisioner/terraform.TestInstall
Fixes: https://github.com/coder/internal/issues/72

### CODE REVIEW

File: provisioner/terraform/install_test.go [hunk 1]
```diff
@@ -73,13 +117,11 @@ func TestInstall(t *testing.T) {
 	modTime1 := checkBinModTime()
 
 	// Since we're using the same version the install should be idempotent.
-	install(terraform.TerraformVersion)
+	install(version1)
 	modTime2 := checkBinModTime()
 	require.Equal(t, modTime1, modTime2)
 
 	// Ensure a new install happens when version changes
-	version2 := version.Must(version.NewVersion("1.2.0"))
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go:81]: why was this check removed?

File: provisioner/terraform/testdata/fake-terraform-installer/setup_fakes.sh [hunk 2]
```diff
@@ -0,0 +1,102 @@
+#!/bin/bash
+
```
Comment (hugodutka) [inline provisioner/terraform/testdata/fake-terraform-installer/setup_fakes.sh]: I'd rather we used go for this logic. This script should be a function in `install_test.go`.

File: provisioner/terraform/testdata/fake-terraform-installer/setup_fakes.sh [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+done
+
+## Prepare zips
+go mod init fake-terraform
+
+echo "LICENSE" >./LICENSE.txt
+for ver in "${versions[@]}"; do
+	go build -ldflags "-X main.version=${ver}" -o terraform
+	zip terraform_"${ver}"_linux_amd64.zip terraform LICENSE.txt
+	mv terraform_"${ver}"_linux_amd64.zip ./"${ver}"
```
Comment (hugodutka) [inline provisioner/terraform/testdata/fake-terraform-installer/setup_fakes.sh]: Instead of building a new binary, you can just write a mock bash script to disk and make it executable.

**Review by hugodutka — CHANGES_REQUESTED** [review]
I like the idea to mock the terraform server. When you're refactoring code, please avoid process exec for moving, zipping, and making files executable. We run these tests on multiple OSes, and stuff will be less prone to break if you stick to the go stdlib.

File: provisioner/terraform/install_test.go (hunk 1 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go:81]: it was just moved to line 84

File: provisioner/terraform/install_test.go [hunk 4]
```diff
@@ -20,6 +25,141 @@ import (
...
+//
+//	${tmpDir}/index.json
+//	${tmpDir}/${version}/index.json
+//	${tmpDir}/${version}/terraform_${version}_linux_amd64.zip
+//	  -> zip contains 'terraform' binary and sometimes 'LICENSE.txt'
+func createFakeTerraformInstallationFiles(t *testing.T) string {
+	tmpDir := t.TempDir()
+	mainV1 := strings.ReplaceAll(mainIndexJSONVersionTemplate, "${ver}", version1.String())
+	mainV2 := strings.ReplaceAll(mainIndexJSONVersionTemplate, "${ver}", version2.String())
+	mainIndex := mainIndexJSONPrefix + mainV1 + ",\n" + mainV2 + "\n" + mainIndexJSONSufix
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go]: manually constructing a json is janky. it'd be nicer to marshall a go object instead:

```go
x := map[string]any {
	"prev_version": 3,
	"hello": map[string]any {
		"world": 4,
	},
}

marshalled, err := json.Marshal(x)
if err != nil {
	return "", err
}
```

File: provisioner/terraform/install_test.go [hunk 5]
```diff
@@ -20,6 +25,141 @@ import (
...
+	require.NoError(t, err)
+	require.NotZero(t, bc)
+
+	require.NoError(t, zip1Writer.Close())
+	require.NoError(t, zip2Writer.Close())
+
+	return tmpDir
+}
+
+// starts fake http server serving fake terraform installation files
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go]: nit: the server isn't fake

```suggestion
// starts an http server serving fake terraform installation files
```

File: provisioner/terraform/install_test.go [hunk 6]
```diff
@@ -20,6 +25,141 @@ import (
...
+
+	mux := http.NewServeMux()
+	fs := http.FileServer(http.Dir(tmpDir))
+	mux.Handle("/terraform/", http.StripPrefix("/terraform", fs))
+
+	server := http.Server{
+		ReadHeaderTimeout: time.Second,
+		Handler:           mux,
+	}
+	go server.Serve(listener)
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go]: instead of using `defer` in TestInstall, you can schedule cleanup right here

```suggestion
	go server.Serve(listener)
	t.Cleanup(func() {
		if err := srv.Close(); err != nil {
			t.Errorf("failed to close server: %v", err)
		}
	})
```

**Review by hugodutka — APPROVED** [review]
looking good
