### PR TITLE
fix(provisioner/terraform/tfparse): skip evaluation of unrelated parameters

### LINKED ISSUE #16021: coder_parameter regression: cannot use lists and functions anymore
The following parameter definition was valid with older coder versions but is valid anymore with coder 2.18.1 by `coder templates push`

```
data "coder_parameter" "param_name" {
  name         = "param_name"
  type         = "list(string)"
  default      = jsonencode(["1", "2", "3", "4"])
  description  = "List of ..."
  mutable      = true
}
```
Fails with:
```
evaluate default values of workspace tags: load parameter defaults: failed to evaluate coder_parameter "param_name" default value "jsonencode([\"1\", \"2\", \"3\", \"4\"])": variables.tf:121,18-102: Function calls not allowed; Functions may not be called here.
```

Even if I remove the jsonencode, it still fails with:
```
evaluate default values of workspace tags: load parameter defaults: failed to marshal coder_parameter "param_name" default value "[\"1\", \"2\", \"3\", \"4\"]" as string: only primitive types are supported - bool, number, and string
```

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/16021

`tfparse` had been enforcing the "no functions, no locals" rule for _all_ `coder_parameter` default values, where we only want to enforce this for ones referenced by `coder_workspace_tags`.

* Improves tfparse test coverage to include more parameter types and values
* Adds tests with unrelated parameters that should be ignored by tfparse
* Modifies tfparse to only attempt evaluation of variables/parameters referenced by coder_workspace_tags

### CODE REVIEW

File: provisioner/terraform/tfparse/tfparse_test.go [hunk 1]
```diff
@@ -422,6 +446,99 @@ func Test_WorkspaceTagDefaultsFromFile(t *testing.T) {
...
+					}`,
+			},
+			expectTags: map[string]string{
+				"stringvar":   "a",
+				"numvar":      "1",
+				"boolvar":     "true",
+				"stringparam": "a",
+				"numparam":    "1",
+				"boolparam":   "true",
+				"listparam":   `["a", "b"]`,
```
Comment (johnstcn) [inline provisioner/terraform/tfparse/tfparse_test.go:504]: review: this ends up being allowed due to the `default` of `coder_parameter` being a string.

File: provisioner/terraform/tfparse/tfparse_test.go [hunk 2]
```diff
@@ -422,6 +446,99 @@ func Test_WorkspaceTagDefaultsFromFile(t *testing.T) {
...
+						default = ["a"]
+					}
+					data "coder_workspace_tags" "tags" {
+						tags = {
+							listvar = var.listvar
+						}
+					}`,
+			},
+			expectTags:  nil,
+			expectError: `can't convert variable default value to string: unsupported type []interface {}`,
```
Comment (johnstcn) [inline provisioner/terraform/tfparse/tfparse_test.go:523]: review: this is also not allowed by the provider:

```
│   on main.tf line 38, in data "coder_workspace_tags" "tags":
│   38:   tags = {
│   39:     "listvar" = ["a"]
│   40:   }
│
│ Inappropriate value for attribute "tags": element "listvar": string required.
```

File: provisioner/terraform/tfparse/tfparse_test.go [hunk 3]
```diff
@@ -422,6 +446,99 @@ func Test_WorkspaceTagDefaultsFromFile(t *testing.T) {
...
+						default = {"a": "b"}
+					}
+					data "coder_workspace_tags" "tags" {
+						tags = {
+							mapvar = var.mapvar
+						}
+					}`,
+			},
+			expectTags:  nil,
+			expectError: `can't convert variable default value to string: unsupported type map[string]interface {}`,
```
Comment (johnstcn) [inline provisioner/terraform/tfparse/tfparse_test.go:540]: review: also not allowed by the provider:

```
│   on main.tf line 38, in data "coder_workspace_tags" "tags":
│   38:   tags = {
│   39:     "mapvar" = {a = "b"}
│   40:   }
│
│ Inappropriate value for attribute "tags": element "mapvar": string required.
```

File: provisioner/terraform/tfparse/tfparse.go [hunk 4]
```diff
@@ -290,6 +305,18 @@ func (p *Parser) CoderParameterDefaults(ctx context.Context, varsDefaults map[st
 			continue
 		}
 
+		var found bool
+		needle := strings.Join([]string{"data", dataResource.Type, dataResource.Name}, ".")
```
Comment (johnstcn) [inline provisioner/terraform/tfparse/tfparse.go:309]: As far as I can tell, there is no way to break a variable reference over multiple lines e.g.

```
data.\
coder_parameter.\
foo.\
value
```

**Review by mtojek — APPROVED** [review]
I approve this change although I'm concerned about the overall parsing logic. With another patch it will become harder to debug or touch internals in the future.

**Comment by johnstcn** [comment]
Smoke-tested on personal deployment with example from linked issue.

https://github.com/user-attachments/assets/35bd3cba-7544-4ceb-934d-42263fbaea1a

Note that issue described in https://github.com/coder/coder/issues/16022 is still present if that parameter is referenced in `coder_workspace_tags`.

File: provisioner/terraform/tfparse/tfparse.go [hunk 5]
```diff
@@ -247,28 +251,39 @@ func WriteArchive(bs []byte, mimetype string, path string) error {
...
-	// variables.
+	// required variables.
 	m := make(map[string]string)
 	for _, v := range p.module.Variables {
 		if v == nil {
 			continue
 		}
+		var found bool
+		for _, tv := range tags {
+			if strings.Contains(tv, v.Name) {
```
Comment (johnstcn) [inline provisioner/terraform/tfparse/tfparse.go:266]:
```suggestion
			if strings.Contains(tv, "var."+v.Name) {
```

Comment (Emyrk) [inline provisioner/terraform/tfparse/tfparse.go:266]: won't a `strings.Contains` also contain variable names that are subsets?

Like `var.Foo` will match both `Foo` and `var.FooBar`

**Review by SasSwart — APPROVED** [review]

File: provisioner/terraform/tfparse/tfparse.go (hunk 5 above)
Comment (Emyrk) [reply provisioner/terraform/tfparse/tfparse.go:266]: Here is a test case:
```golang
			{
				name: "overlapping var name",
				files: map[string]string{
					`main.tf`: `
						// This file is the same as the above, except for this comment.
						variable "a" {
							type = string
							default = "1"
						}
						variable "ab" {
						 description = "This is a variable of type string"
						 type        = string
						 default     = jsonencode(["a", "b"])
						}
						data "coder_workspace_tags" "tags" {
							tags = {
								"foo": "bar",
								"a": var.a,
							}
						}`,
				},
				reqTags:  map[string]string{"foo": "noclobber"},
				wantTags: map[string]string{"owner": "", "scope": "organization", "foo": "bar", "a": "1"},
			},
```

Comment (johnstcn) [reply provisioner/terraform/tfparse/tfparse.go:266]: Gotcha, we may then need to do some more "intelligent" parsing.
I hesitate to reach for a regexp.... but `\b` may be exactly what we need here

Comment (Emyrk) [reply provisioner/terraform/tfparse/tfparse.go:266]: Is the reason you do a contains because it could be an expression like `foo(var.name)`?

Comment (Emyrk) [reply provisioner/terraform/tfparse/tfparse.go:266]: Is there any way to parse the expression and get the actual tokens? Or we only have `string` in the HCL?

Comment (johnstcn) [reply provisioner/terraform/tfparse/tfparse.go:266]: Yep. I'm looking into HCL traversals now as they might allow us to do this cleanly.

Comment (johnstcn) [reply provisioner/terraform/tfparse/tfparse.go]: OK, I've modified the implementation to instead:
- Gather the set of variables referenced by the tags up-front,
- Only evaluate the default value(s) for `coder_parameters` referenced by those tags.
- As default values of coder_parameters can reference other variables, to avoid needing to perform a graph traversal of all the dependencies here I've elected to simply continue passing in all the variable default values. We don't immediately enforce default values for all variables.
- To avoid unrelated variables with default values of complex types being rejected, I added some 'last-ditch' support for JSON-encoding them.
