### PR TITLE
fix(provisioner): handle multiple agents, apps, scripts and envs

### LINKED ISSUE #12949: coder_app: When adding multiple coder_agents gets duplicated coder_app
If we have multiple coder_agent and then add a coder_app for one of the agents we have it repeated across all agents. It's not respecting the `agent_id`.

```
terraform {
  required_version = ">= 1.0"
  required_providers {
    coder = {
      source  = "coder/coder"
      version = ">=0.20.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">=5.44"
    }
    hashicorptls = {
      source  = "hashicorp/tls"
      version = ">=4.0.5"
    }
    hashicorpnull = {
      source  = "hashicorp/null"
      version = ">=3.2.2"
    }
  }
}

provider "coder" {
}

data "coder_workspace" "me" {
}

 resource "coder_agent" "master" {
   arch               = "amd64"
   auth               = "aws-instance-identity"
   os                 = "linux"
 }

resource "coder_agent" "ad" {
  arch = "amd64"
  auth = "aws-instance-identity"
  os   = "windows"
}

locals {
  agent_master = coder_agent.master.init_script
  agent_ad = coder_agent.ad.init_script
}

resource "coder_app" "s2-studio" {
  agent_id     = coder_agent.master.id
  slug         = "s2-studio"
  display_name = "SingleStore Studio"
  icon         = "https://www.singlestore.com/favicon-32x32.png" # "${data.coder_workspace.me.access_url}/icon/code.svg"
  url          = "http://localhost:13337"
  share        = "owner"
  subdomain    = false
  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 5
    threshold = 6
  }
}

resource "aws_instance" "master" {
  count                  = 1
  ami                    = ""
  instance_type          = "m6a.xlarge"
  vpc_security_group_ids = [""]
  subnet_id              = ""
  user_data              = local.agent_master
}

resource "aws_instance" "ad" {
  count                  = 1
  ami                    = ""
  instance_type          = "m6a.xlarge"
  vpc_security_group_ids = [""]
  subnet_id              = ""
  user_data              = local.agent_ad
}
```

On the above example I am expecting that the `coder_app.s2-studio` to be present only in the `coder_agent.master`, but that is not the case:

image

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/12949

This PR adjusts provisioner logic to properly handle apps, scripts, and envs assigned to different agent. Without this PR every app/script/env is assigned to every agent. Unfortunately, there isn't an easy way to achieve it, and we need to snoop the dependency information from the graph.

Note: I added a couple of .tf tests, which blew up the PR size. The code change itself is relatively small.

### CODE REVIEW

File: provisioner/terraform/resources.go [hunk 1]
```diff
@@ -748,6 +750,30 @@ func convertAddressToLabel(address string) string {
 	return cut
 }
 
+func dependsOnAgent(graph *gographviz.Graph, agent *proto.Agent, appAgentID string, resource *tfjson.StateResource) bool {
+	// Plan: we need to find if there is edge between the agent and the resource.
+	if agent.Id == "" && appAgentID == "" {
+		appNodeSuffix := fmt.Sprintf(`] %s.%s (expand)"`, resource.Type, resource.Name)
+		agentNodeSuffix := fmt.Sprintf(`] coder_agent.%s (expand)"`, agent.Name)
```
Comment (johnstcn) [inline provisioner/terraform/resources.go:757]: It's unfortunate that we need to match this :(

File: provisioner/terraform/resources.go [hunk 2]
```diff
@@ -748,6 +750,30 @@ func convertAddressToLabel(address string) string {
...
+				for _, edge := range edges {
+					if strings.HasSuffix(edge.Src, appNodeSuffix) &&
+						strings.HasSuffix(edge.Dst, agentNodeSuffix) {
+						return true
+					}
+				}
+			}
+		}
+		return false
+	}
```
Comment (johnstcn) [inline provisioner/terraform/resources.go:771]: My main concern is that we are traversing this graph multiple times in a tight loop.
Could we instead traverse the graph once, build a shallow map of `agent -> resource`, and use that to determine the agent-resource dependency?

Comment (mtojek) [reply provisioner/terraform/resources.go:771]: The main reason I'm hesitant to do this, it would be another cache/state used only to prevent this problem. Considering we have 1 agent on average, 2 in total, it may not introduce a heavy performance impact.

Anyway, if you think this is a must-do, I will improve the loop 👍  I admit, I focused mostly on fixing the problem.

Comment (johnstcn) [reply provisioner/terraform/resources.go:771]: That's fair. Let's make it work correctly first, and then see about benchmarking / speeding it up.

**Review by johnstcn — APPROVED** [review]
