### PR TITLE
fix: stop SSHKeysPage from flaking

### LINKED ISSUE #10481: flake: SSHKeyPage.test.tsx has too many element matches
Had this happen earlier today, but for some reason, I can't find the logs in the actions that ran. Not sure if re-running the test caused the logs to get wiped.

Either way, there's an issue that sometimes triggers on `SSHKeyPage.test.tsx`. [Here's a failing run](https://github.com/coder/coder/actions/runs/6589196703/job/17903112550)

Here's what looks like the most important part:
> Found multiple elements with the text: Error regenerating SSH key

From looking at the rest of the tests, it looks like there's a conflict between the error surfaced in the main part of the UI, and the little toast/snackbar UI we have for more global messages. Two things come to mind here:
1. Update the test to be more specific and always grab the correct element
2. Look into why the global snackbar only sometimes gets dismissed

Hoping to look into this either Thursday or Friday this week.

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #10481
This fix updates `SSHKeys.tsx` to prevent its tests from flaking.

## Changes made
- Refactored `<GlobalSnackbar>` and `useCustomEvent` to simplify snackbar logic
- Updated `SSHKeys.tsx` to process mutation errors solely through the snackbar, and not also the local UI
- Updated Storybook to remove UI error logic, and updated the test to make selectors more semantics-based

### CODE REVIEW

File: site/src/components/GlobalSnackbar/GlobalSnackbar.tsx [hunk 1]
```diff
@@ -29,54 +28,10 @@ export const GlobalSnackbar: FC = () => {
...
-    (event) => {
-      setNotification(event.detail);
-      setOpen(true);
-    },
-    [],
-  );
-
-  useCustomEvent(SnackbarEventType, handleNotification);
-
-  const renderAdditionalMessage = (msg: AdditionalMessage, idx: number) => {
```
Comment (Parkreiner) [inline site/src/components/GlobalSnackbar/GlobalSnackbar.tsx:42]: This got removed in favor of making it a separate component at the bottom of the file

File: site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.test.tsx [hunk 2]
```diff
@@ -4,6 +4,21 @@ import { renderWithAuth } from "testHelpers/renderHelpers";
...
+ * v4 had a way to set custom loggers, but they're removed in v5. Only other
+ * option is changing the env directly, which feels super dicey
+ */
+beforeAll(() => {
+  jest.spyOn(console, "error").mockImplementation(() => {});
+});
+
+afterAll(() => {
+  jest.clearAllMocks();
+});
```
Comment (Parkreiner) [inline site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.test.tsx:20]: Not sure if it makes sense to turn this logic into a test utility function

**Review by aslilac — APPROVED** [review]
