### PR TITLE
fix(site): show accurate message and warning color for startup script failures in agent row

### LINKED ISSUE #23652: Agent row shows misleading "Error starting the agent" message and red border for startup script failures
## Description

When a startup script fails (`lifecycle_state: "start_error"`), the agent row in the workspace page shows incorrect messaging and styling:

1. **Wrong message**: The hover tooltip on the warning icon shows "Error starting the agent" / "Something went wrong during the agent startup." This is misleading — the agent IS started and functional (SSH works, terminal works). Only the startup script exited with a non-zero code.
2. **Wrong color**: The agent row border is red (`border-border-destructive`) instead of orange/warning. A startup script failure is a warning-level issue, not a destructive error.

Image

## Expected behavior

* **Message** should say "Startup script failed" / "A startup script exited with an error. Check the agent logs for details." — matching the workspace-level alerts fixed in [#22843](<https://github.com/coder/coder/issues/22843>) and [#23591](<https://github.com/coder/coder/issues/23591>).
* **Border color** should be `border-border-warning` (orange) instead of `border-border-destructive` (red), consistent with `start_timeout` which already uses `border-border-warning`.

## Location in code

* `site/src/modules/resources/AgentStatus.tsx` — `StartErrorLifecycle` component renders the tooltip
* `site/src/modules/resources/AgentRow.tsx` — maps `start_error` to `"border-border-destructive"`

## Context

Follow-up to [#22843](<https://github.com/coder/coder/issues/22843>) and [#23591](<https://github.com/coder/coder/issues/23591>) which fixed the workspace-level alerts and hover popover to show accurate messages. The agent-row-level tooltip was not addressed in those PRs.

Refs [ENG-739](https://linear.app/codercom/issue/ENG-739/workspace-is-unhealthy-message-is-not-clear-as-to-root-cause-does-not)

### PR DESCRIPTION
**Pull request by matifali**
The agent row tooltip showed "Error starting the agent" / "Something went wrong during the agent startup" with a red border when a startup script fails. This is misleading — the agent is started and functional, only the startup script exited with a non-zero code.

Extracts shared message constants (`agentLifecycleMessages`, `agentStatusMessages`) from `health.ts` so both the workspace-level health classification and the per-agent-row tooltips reference the same single source of truth. No more duplicated wording that can drift.

Changes:
- **`health.ts`**: Exports `agentLifecycleMessages` and `agentStatusMessages` maps; `getAgentHealthIssue` now references them instead of inline strings.
- **`AgentStatus.tsx`**: All lifecycle/status tooltip components (`StartErrorLifecycle`, `StartTimeoutLifecycle`, `ShutdownTimeoutLifecycle`, `ShutdownErrorLifecycle`, `TimeoutStatus`) now import and render from the shared message constants. `StartErrorLifecycle` icon changed from red (`errorWarning`) to orange (`timeoutWarning`).
- **`AgentRow.tsx`**: `start_error` border changed from `border-border-destructive` (red) to `border-border-warning` (orange).

Closes #23652
Refs #21389

> 🤖 This PR was created with the help of Coder Agents, and has been reviewed by my human.  🧑‍💻

### CODE REVIEW

File: site/src/modules/workspaces/health.ts [hunk 1]
```diff
@@ -1,5 +1,55 @@
 import type { Workspace, WorkspaceAgentStatus } from "#/api/typesGenerated";
 
+interface AgentMessage {
+	title: string;
+	detail: string;
+}
```
Comment (DanielleMaywood) [inline site/src/modules/workspaces/health.ts]: Is this type actually used anywhere?

File: site/src/modules/workspaces/health.ts [hunk 2]
```diff
@@ -1,5 +1,55 @@
...
+		title: "Shutdown script failed",
+		detail:
+			"A shutdown script exited with an error. Check the agent logs for details.",
+	},
+	shutdown_timeout: {
+		title: "Agent is taking longer than expected to stop",
+		detail:
+			"A shutdown script has exceeded the expected time. Check the agent logs for details.",
+	},
+} as const satisfies Record<string, AgentMessage>;
```
Comment (DanielleMaywood) [inline site/src/modules/workspaces/health.ts]: We can drop `satisfies Record<string, AgentMessage>`

File: site/src/modules/workspaces/health.ts [hunk 3]
```diff
@@ -1,5 +1,55 @@
...
+		title: "Agent is taking longer than expected to connect",
+		detail:
+			"Continue to wait and check the log output for errors. If agents do not connect, try restarting the workspace.",
+	},
+	disconnected: {
+		title: "Workspace agent has disconnected",
+		detail:
+			"Check the log output for errors. If agents do not reconnect, try restarting the workspace.",
+	},
+} as const satisfies Record<string, AgentMessage>;
```
Comment (DanielleMaywood) [inline site/src/modules/workspaces/health.ts]: We can drop `satisfies Record<string, AgentMessage>`

File: site/src/modules/resources/AgentStatus.tsx [hunk 4]
```diff
@@ -399,14 +356,14 @@ const styles = {
...
 		width: 14,
 		height: 14,
 		position: "relative",
 	}),
 
-	errorWarning: (theme) => ({
+	errorIcon: (theme) => ({
 		color: theme.palette.error.main,
 		width: 14,
 		height: 14,
```
Comment (DanielleMaywood) [inline site/src/modules/resources/AgentStatus.tsx]: Typically when making changes to the frontend, if we touch the MUI styles at all the preference is migrate over to tailwind styling

File: site/src/modules/resources/AgentStatus.tsx [hunk 5]
```diff
@@ -66,54 +115,23 @@ interface DevcontainerStatusProps {
...
-					>
-						Troubleshoot
-					</Link>
-					.
-				</HelpTooltipText>
-			</HelpTooltipContent>
-		</HelpTooltip>
-	);
-};
+const StartErrorLifecycle: FC<AgentStatusProps> = ({ agent }) => (
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.tsx:133]: **P3** `StartErrorLifecycle` (and `ShutdownErrorLifecycle` below) relies on the default `variant="warning"` to get the yellow icon, where the old code explicitly used `styles.errorWarning` (red). The downgrade is intentional per the PR rationale, but compare with `DevcontainerStartError` at line 306, which explicitly passes `variant="error"`. *(Bisky P2, Hisoka P2, Mafuuu P2)*

> Hisoka: "The inconsistency in explicitness makes the yellow-vs-red decision look accidental rather than deliberate. Adding `variant="warning"` explicitly to `StartErrorLifecycle` and `ShutdownErrorLifecycle` would cost nothing and make the intent unmistakable."

Passing `variant="warning"` explicitly would make it clear this is a conscious choice, not a forgotten prop.

> 🤖

File: site/src/modules/workspaces/health.ts [hunk 6]
```diff
@@ -1,5 +1,55 @@
...
+		detail:
+			"A startup script has exceeded the expected time. Check the agent logs for details.",
+	},
+	shutdown_error: {
+		title: "Shutdown script failed",
+		detail:
+			"A shutdown script exited with an error. Check the agent logs for details.",
+	},
+	shutdown_timeout: {
+		title: "Agent is taking longer than expected to stop",
```
Comment (mafredri) [inline site/src/modules/workspaces/health.ts]: **P3** `shutdown_timeout.title` uses agent-level framing while the other three entries use script-level framing. *(Mafuuu P3, Robin P3, Nami Obs)*

> Mafuuu: "The other three entries attribute the issue to the script: 'Startup script failed', 'Startup script is taking longer than expected', 'Shutdown script failed'. `shutdown_timeout.title` says 'Agent is taking longer than expected to stop', attributing the issue to the agent. The detail field correctly points to the script."

Something like "Shutdown script is taking longer than expected" would match the `start_timeout` pattern. The old tooltip had the same framing, but since you're canonicalizing these, it's a good time to fix it.

> 🤖

File: site/src/modules/resources/AgentStatus.tsx [hunk 7]
```diff
@@ -324,31 +297,15 @@ const SubAgentStatus: FC<SubAgentStatusProps> = ({ agent }) => {
...
-					.
-				</HelpTooltipText>
-			</HelpTooltipContent>
-		</HelpTooltip>
-	);
-};
+const DevcontainerStartError: FC<AgentStatusProps> = ({ agent }) => (
+	<AgentWarningTooltip
+		ariaLabel="Start error"
+		title="Error starting the devcontainer agent"
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.tsx:311]: **Nit** `DevcontainerStartError` is the only tooltip consumer that hardcodes its title and detail instead of pulling from the shared constants. *(Robin P3, Bisky Obs, Nami Obs, Leorio Nit, Mafuuu Obs)*

> Robin: "Every other lifecycle/status tooltip in the file now imports from `agentScriptMessages` or `agentConnectionMessages`. If the intent is a single source of truth, this is a gap."

Devcontainer errors are a different domain so this might be intentional. Could add a `devcontainer_start_error` entry to `agentScriptMessages` (or a separate `agentDevcontainerMessages` map) if you want full coverage.

> 🤖

File: site/src/modules/resources/AgentStatus.tsx [hunk 8]
```diff
@@ -66,54 +115,23 @@ interface DevcontainerStatusProps {
...
 
-const StartTimeoutLifecycle: FC<AgentStatusProps> = ({ agent }) => {
-	return (
-		<HelpTooltip>
-			<HelpTooltipTrigger asChild role="status" aria-label="Agent timeout">
-				<TriangleAlertIcon css={styles.timeoutWarning} />
-			</HelpTooltipTrigger>
+const StartTimeoutLifecycle: FC<AgentStatusProps> = ({ agent }) => (
+	<AgentWarningTooltip
+		ariaLabel="Agent timeout"
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.tsx]: **Nit** `ariaLabel="Agent timeout"` here and `ariaLabel="Timeout"` on `TimeoutStatus` (line 252) are indistinguishable to screen readers, but they describe different things: a startup script taking too long vs the agent process failing to connect. *(Leorio)*

> Leorio: "Someone using assistive tech can't distinguish between 'the agent process timed out connecting' and 'a startup script is slow' from the aria-label alone."

Consider `ariaLabel="Startup script timeout"` here to match the visible text.

> 🤖

File: site/src/modules/resources/AgentStatus.tsx [hunk 9]
```diff
@@ -19,13 +19,62 @@ import {
...
+			<HelpTooltipTrigger asChild role="status" aria-label={ariaLabel}>
+				<TriangleAlertIcon
+					css={variant === "warning" ? styles.warningIcon : styles.errorIcon}
+				/>
+			</HelpTooltipTrigger>
+			<HelpTooltipContent>
+				<HelpTooltipTitle>{title}</HelpTooltipTitle>
+				<HelpTooltipText>
+					{detail}
+					{troubleshootingURL && (
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.tsx:70]: **Nit** The old tooltips rendered a trailing period after the Troubleshoot link (`Troubleshoot</Link>.`). The new component drops it. Minor, since the detail text already ends with a period, but six tooltips changed at once. *(Bisky P3, Nami P3)*

> 🤖

**Review by mafredri — COMMENTED** [review]
Good refactor. Collapsing six near-identical tooltip components into `AgentWarningTooltip` with shared message constants is a real improvement, and the conditional troubleshooting link quietly fixes a latent bug with empty hrefs. The `as const satisfies` pattern is well-chosen.

2 P3 findings, 3 nits across 5 inline comments. Also worth noting: `TaskStartupWarningButton.tsx` (lines 97, 106) has its own hardcoded copies of the startup script error/timeout messages that this PR doesn't touch. The wording already drifts from the new constants ("startup script has exited with an error" vs "Startup script failed"). Not blocking, but it limits the single-source-of-truth benefit if left as-is.

PS. The PR description references `agentLifecycleMessages` and `agentStatusMessages`, but the actual exports are `agentScriptMessages` and `agentConnectionMessages`.

> 🤖 This review was generated with the help of Coder Agents.

File: site/src/modules/workspaces/health.ts (hunk 1 above)
Comment (matifali) [reply site/src/modules/workspaces/health.ts]: Done — removed `AgentMessage` interface and the `satisfies` constraints. `as const` already provides type safety.

File: site/src/modules/workspaces/health.ts (hunk 2 above)
Comment (matifali) [reply site/src/modules/workspaces/health.ts]: Done — dropped both `satisfies` constraints along with the `AgentMessage` interface.

File: site/src/modules/workspaces/health.ts (hunk 3 above)
Comment (matifali) [reply site/src/modules/workspaces/health.ts]: Done.

File: site/src/modules/resources/AgentStatus.tsx (hunk 4 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx]: Good point — migrating these to Tailwind is a good follow-up but would be a bigger change touching all the status dot styles too. Keeping it out of scope for this PR.

File: site/src/modules/resources/AgentStatus.tsx (hunk 5 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:133]: Done — both `StartErrorLifecycle` and `ShutdownErrorLifecycle` now pass `variant="warning"` explicitly.

File: site/src/modules/workspaces/health.ts (hunk 6 above)
Comment (matifali) [reply site/src/modules/workspaces/health.ts]: Done — now "Shutdown script is taking longer than expected", matching the `start_timeout` pattern.

File: site/src/modules/resources/AgentStatus.tsx (hunk 7 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:311]: Intentionally leaving this as-is. Devcontainer errors are a different domain — they are about the container runtime failing, not user startup/shutdown scripts. Adding it to the shared constants would conflate the two. If devcontainer messaging needs its own source of truth later, a separate `agentDevcontainerMessages` map would be the right approach.

File: site/src/modules/resources/AgentStatus.tsx (hunk 8 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx]: Done — changed to "Startup script timeout" here and "Shutdown script timeout" / "Shutdown script failed" for the shutdown equivalents.

File: site/src/modules/resources/AgentStatus.tsx (hunk 9 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:70]: Intentional — the detail text already ends with proper punctuation ("...for details."), so adding another period after the Troubleshoot link would read oddly: "...for details. Troubleshoot." The link works as a standalone call-to-action without trailing punctuation.

File: site/src/modules/resources/AgentStatus.tsx (hunk 4 above)
Comment (DanielleMaywood) [reply site/src/modules/resources/AgentStatus.tsx]: as said prior, the point is to do it when we touch it, so i think we should do it now

Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx]: Ok will do with help from an agent. Thanks for calling it out.

Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx]: Done — migrated the icon styles to Tailwind. `AgentWarningTooltip` now uses `className="relative size-3.5 text-content-warning"` / `text-content-destructive"` instead of the Emotion `warningIcon`/`errorIcon` styles. Removed both unused Emotion style entries.

File: site/src/modules/workspaces/health.ts [hunk 10]
```diff
@@ -1,5 +1,50 @@
 import type { Workspace, WorkspaceAgentStatus } from "#/api/typesGenerated";
 
+/**
+ * Canonical messages for startup and shutdown script issues.
+ * Used by both the workspace-level health classification and the
```
Comment (mafredri) [inline site/src/modules/workspaces/health.ts]: **P3** JSDoc says "both the workspace-level health classification and the per-agent-row tooltips" but the shutdown constants are only consumed by the tooltips. *(Mafuuu P2, Nami Obs)*

> Mafuuu: "I grep'd for `shutdown_error` and `shutdown_timeout` usage: both constants are consumed only by `AgentStatus.tsx`. In `getAgentHealthIssue`, the `hasShutdownState` branch groups all shutdown states together with its own inline text. A developer reading the JSDoc would believe editing these constants updates both surfaces. It doesn't."

The start-related entries are shared with both surfaces, so the doc isn't wrong, just overpromising. Could scope it: "Used by the per-agent-row tooltips; start-related entries are also shared with the workspace-level health classification."

> 🤖

File: site/src/modules/resources/AgentStatus.tsx [hunk 11]
```diff
@@ -66,54 +119,24 @@ interface DevcontainerStatusProps {
 	agent?: WorkspaceAgent;
 }
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.tsx:123]: **P3** The PR's core value is message consistency between the health banner and per-agent tooltips. `health.test.ts` proves the banner side (23 tests, hardcoded expected strings). Nothing proves the tooltip side. *(Bisky P2)*

> Bisky: "If `StartErrorLifecycle` accidentally reads from `agentScriptMessages.start_timeout` instead of `start_error`, no test catches it. You dressed up one side of the consistency guarantee and left the other bare."

Adding `play` functions to the lifecycle stories would close this. Hover the icon, assert the tooltip title matches the expected constant. Five minutes per story, and the aria-label assertion alone would catch a mismapping.

> 🤖

**Review by mafredri — COMMENTED** [review]
Thanks for fixing the variant explicitness, the shutdown_timeout title, and the aria-labels. All three verified correct in the new commit.

F3 (DevcontainerStartError) and F5 (trailing period) contested with solid reasoning, no pushback from us.

Fresh panel found 2 new P3s across 2 inline comments. `TaskStartupWarningButton.tsx` still has its own copies of the startup messages (round 1 F6, no response yet).

> 🤖 This review was generated with the help of Coder Agents.

File: site/src/modules/workspaces/health.ts (hunk 10 above)
Comment (matifali) [reply site/src/modules/workspaces/health.ts]: Good catch — updated the JSDoc to: "Used by the per-agent-row tooltips in AgentStatus; the start-related entries are also shared with the workspace-level health classification in getAgentHealthIssue."

File: site/src/modules/resources/AgentStatus.tsx (hunk 11 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:123]: Done — added `AgentStatus.stories.tsx` with `play` functions for all 5 tooltip states. Each story clicks the icon and asserts the tooltip title matches the shared constant (`agentScriptMessages.start_error.title`, etc.). A mismapping like `start_timeout` instead of `start_error` would fail the assertion.

**Comment by matifali** [comment]
Re: `TaskStartupWarningButton.tsx` — looked at it. The messages there are sentence fragments embedded in a structured tooltip with multiple inline doc links: "A workspace **startup script has exited with an error**. We recommend **debugging the startup script** because **your workspace may be incomplete**." These serve a different grammatical role than our standalone title/detail constants and can't be swapped in without breaking the sentence structure. Different UI context (Task page button tooltip vs agent row status tooltip), different message pattern. Not in scope for this PR.

> 🤖 This response was generated by Coder Agents.

**Review by mafredri — COMMENTED** [review]
Thanks for addressing both findings and the Tailwind migration. All verified:

- JSDoc now accurately scopes which constants are shared with which surface.
- `AgentStatus.stories.tsx` with `play` functions for all 5 tooltip states closes the testing gap. The assertions import the shared constants directly, so a mismapping would fail the story.
- Tailwind migration of icon styles uses established `text-content-warning`/`text-content-destructive` classes, consistent with the rest of the codebase.

F6 (TaskStartupWarningButton) contested with a clear explanation: different grammatical role, different UI context. Agreed, not in scope.

LGTM.

> 🤖 This review was generated with the help of Coder Agents.

File: site/src/modules/resources/AgentStatus.stories.tsx [hunk 12]
```diff
@@ -0,0 +1,146 @@
...
+			lifecycle_state: "start_error",
+		},
+	},
+	play: async () => {
+		const icon = screen.getByRole("status", {
+			name: "Startup script failed",
+		});
+		await userEvent.hover(icon);
+		await waitFor(() =>
+			expect(screen.getByRole("tooltip")).toHaveTextContent(
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.stories.tsx]: **P3** Play functions assert only the tooltip title. The detail text and troubleshooting link are unasserted. *(Bisky P2, Nami Obs)*

> Bisky: "If someone deleted the `detail` prop from a call site, or broke the `{troubleshootingURL && ...}` conditional in `AgentWarningTooltip`, every story still passes. The detail text and the 'Troubleshoot' link are the actionable parts of these tooltips, and nothing asserts they render."

The title check already catches the mismapping scenario from R2-F2, so this is an enhancement rather than a gap. Adding `toHaveTextContent(agentScriptMessages.X.detail)` and a `getByRole("link", { name: "Troubleshoot" })` assertion would make the coverage complete.

> 🤖

File: site/src/modules/resources/AgentStatus.stories.tsx [hunk 13]
```diff
@@ -0,0 +1,146 @@
...
+	args: {
+		agent: {
+			...MockWorkspaceAgent,
+			status: "connected",
+			lifecycle_state: "ready",
+		},
+	},
+};
+
+export const StartupScriptFailed: Story = {
```
Comment (mafredri) [inline site/src/modules/resources/AgentStatus.stories.tsx:57]: **Nit** No story exercises the empty troubleshooting URL branch. `MockWorkspaceAgent` always has a URL, so the `{troubleshootingURL && ...}` conditional only ever takes the truthy path. *(Bisky P3, Nami Obs)*

A variant with `troubleshooting_url: ""` and `expect(screen.queryByRole("link", { name: "Troubleshoot" })).not.toBeInTheDocument()` would pin the falsy path.

> 🤖

**Review by mafredri — COMMENTED** [review]
All round 2 findings verified resolved. Stories are a solid addition, JSDoc is accurate, Tailwind migration is clean.

Fresh panel found 1 P3 and 1 nit in the new stories, plus an observation on the error/timeout visual consolidation.

PS. Mafuuu suggests keeping the yellow border but retaining the red icon for `*_error` states, so operators can still distinguish "crashed" from "slow" without hovering. Worth considering if fast triage matters, but the current approach is coherent with the PR's rationale.

> 🤖 This review was generated with the help of Coder Agents.

**Comment by matifali** [comment]
Can I get a ✅ ?

File: site/src/modules/resources/AgentStatus.stories.tsx (hunk 12 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.stories.tsx]: Done — play functions now assert title, detail, and troubleshoot link. Extracted a shared `expectTooltip` helper that checks all three. Also added `StartupScriptFailedNoTroubleshootURL` story that covers the falsy branch with `troubleshooting_url: ""`.

File: site/src/modules/resources/AgentStatus.stories.tsx (hunk 13 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.stories.tsx:57]: Done — added `StartupScriptFailedNoTroubleshootURL` story with `troubleshooting_url: ""` that asserts `queryByRole("link", { name: "Troubleshoot" })` is not in the document.

**Comment by matifali** [comment]
Done — rebased onto latest main and updated the `baseUrl` import in `AgentStatus.stories.tsx` to use the `#/` style (`#/testHelpers/entities`). `health.test.ts` was already correct after the rebase.

> 🤖 This response was generated by Coder Agents.

File: site/src/modules/resources/AgentStatus.tsx [hunk 14]
```diff
@@ -19,13 +19,66 @@ import {
...
+}) => {
+	return (
+		<HelpTooltip>
+			<HelpTooltipTrigger asChild role="status" aria-label={ariaLabel}>
+				<TriangleAlertIcon
+					className={`relative size-3.5 ${
+						variant === "warning"
+							? "text-content-warning"
+							: "text-content-destructive"
+					}`}
```
Comment (jakehwll) [inline site/src/modules/resources/AgentStatus.tsx]: nit: legibility

```suggestion
					className={cn(
							"relative size-3.5",
							variant === "warning"
								? "text-content-warning"
								: "text-content-destructive"
						)}
```

Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx]: Done — switched to `cn()` for the className.

**Comment by jakehwll** [comment]
image

Did we intend to update the design to orange here also?

**Comment by DanielleMaywood** [comment]
> image
> Did we intend to update the design to orange here also?

@jakehwll unselect the diff setting

**Comment by matifali** [comment]
Are there more blockers here? If not I would like this to get in before the code release today. Thanks. 
But yes please ensure it meets the quality you expect.

File: site/src/modules/resources/AgentStatus.tsx [hunk 15]
```diff
@@ -19,13 +19,68 @@ import {
...
+	troubleshootingURL?: string;
+	variant?: "warning" | "error";
+}
+
+/**
+ * Shared tooltip for agent warning/error states. Renders an alert
+ * icon with a help tooltip showing the title, detail, and an
+ * optional troubleshooting link.
+ */
+const AgentWarningTooltip: FC<AgentWarningTooltipProps> = ({
```
Comment (johnstcn) [inline site/src/modules/resources/AgentStatus.tsx:47]: nit, non-blocking: this can be a "warning" or "error". There's an argument to be made for naming this `AgentTooltip`. Definitely not a blocker though and feel free to ignore.

**Review by johnstcn — APPROVED** [review]
I don't see any blocking issues. 👍 I got an agent to place a second pair of eyes on it as well.

File: site/src/modules/resources/AgentStatus.tsx (hunk 15 above)
Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:47]: I think it's worth addressing. Let me look into it.

Comment (matifali) [reply site/src/modules/resources/AgentStatus.tsx:47]: Will address in a follow up.
