### PR TITLE
fix: fix dormancy notifications

### LINKED ISSUE #25: reword the dormant template notification
From https://github.com/coder/coder/pull/13868#discussion_r1690118628

The wording is a little weird here. Can we change it and add a link to the dormancy docs:

I don't think we need to include the initiator, just improve the reasons (see end of message).

> Hi `{user-name}`, your workspace `{ws-name}` has been marked [dormant](https://coder.com/docs/templates/schedule#dormancy-threshold-enterprise) because of `{reason}`.

Append if dormancy cleanup is enabled and `dormancy_hours` < 24:
> Dormant workspaces are [automatically deleted](https://coder.com/docs/templates/schedule#dormancy-auto-deletion-enterprise) after `{dormancy_hours}` hours of inactivity.

Append if dormancy cleanup is enabled, and `dormancy_hours` > 24:
> Dormant workspaces are [automatically deleted](https://coder.com/docs/templates/schedule#dormancy-auto-deletion-enterprise) after `{dormancy_hours // 24}` days of inactivity.

> To prevent deletion, use your workspace with the link below.

---

The reasons also fit into differing grammatic context:
- Lifecycle executor: "breached the template's threshold for inactivity"
- API: "requested by user"
- Template: "template updated to new dormancy policy"

If we use these, they'd fit the above messages better.
- Lifcycle: "prolonged inactivity, exceeding the dormancy threshold"
- API: "a user request"
- Template: "an update to the template's dormancy"

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
- Fix and update dormancy templates. Closes https://github.com/coder/team-coconut/issues/25 and https://github.com/coder/team-coconut/issues/23
- Added tests to check if template bodies are valid and ok to render

### CODE REVIEW

File: coderd/notifications/notifications_test.go [hunk 1]
```diff
@@ -603,6 +604,99 @@ func TestNotifierPaused(t *testing.T) {
...
+		tc := tc
+
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+
+			_, _, sql := dbtestutil.NewDBWithSQLDB(t)
+
+			var bodyTmpl string
+			err := sql.
+				QueryRow("SELECT body_template FROM notification_templates WHERE id = $1 LIMIT 1", tc.id).
```
Comment (BrunoQuaresma) [inline coderd/notifications/notifications_test.go:690]: I've inlined this query because it's only used for tests now. I don't think the overhead of adding a new SQLC query would be justifiable. I actually tried that, and I encountered a few accounting errors because the query wasn't being used in the non-test codebase.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 2]
```diff
@@ -1101,13 +1101,11 @@ func (s *server) notifyWorkspaceBuildFailed(ctx context.Context, workspace datab
 		return // failed workspace build initiated by a user should not notify
 	}
 	reason = string(build.Reason)
-	initiator := "autobuild"
 
 	if _, err := s.NotificationsEnqueuer.Enqueue(ctx, workspace.OwnerID, notifications.TemplateWorkspaceAutobuildFailed,
 		map[string]string{
-			"name":      workspace.Name,
-			"initiator": initiator,
```
Comment (BrunoQuaresma) [inline coderd/provisionerdserver/provisionerdserver.go:1109]: I found out that `TemplateWorkspaceAutobuildFailed` was not using the initiator label in the template body so I just removed it.

**Comment by BrunoQuaresma** [comment]
Unfortunately, those tests don't prevent wrong labels from being used or required labels from being missed. To make that happen, the notifications tests would have to use the database. I think it would be valid but not in the scope for this PR.

File: coderd/autobuild/lifecycle_executor.go [hunk 3]
```diff
@@ -325,14 +320,24 @@ func (e *Executor) runOnce(t time.Time) Stats {
...
+				if shouldNotifyDormancy {
+					_, err = e.notificationsEnqueuer.Enqueue(
 						e.ctx,
-						e.notificationsEnqueuer,
-						*dormantNotification,
+						ws.OwnerID,
+						notifications.TemplateWorkspaceDormant,
+						map[string]string{
+							"name":           ws.Name,
+							"reason":         "prolonged inactivity, exceeding the dormancy threshold",
```
Comment (dannykopping) [inline coderd/autobuild/lifecycle_executor.go:330]: Shortened this. WDYT?

```suggestion
							"reason":         "inactivity exceeded the dormancy threshold",
```

File: coderd/autobuild/lifecycle_executor.go [hunk 4]
```diff
@@ -325,14 +320,24 @@ func (e *Executor) runOnce(t time.Time) Stats {
...
+							"timeTilFormant": time.Duration(tmpl.TimeTilDormant).String(),
```
Comment (dannykopping) [inline coderd/autobuild/lifecycle_executor.go:331]:
```suggestion
							"timeTilDormant": time.Duration(tmpl.TimeTilDormant).String(),
```

File: coderd/autobuild/lifecycle_executor.go [hunk 5]
```diff
@@ -325,14 +320,24 @@ func (e *Executor) runOnce(t time.Time) Stats {
...
+						},
+						"api",
```
Comment (dannykopping) [inline coderd/autobuild/lifecycle_executor.go:333]: API is too vague to be useful.

```suggestion
						"lifecycle_executor",
```

File: coderd/workspaces.go [hunk 6]
```diff
@@ -953,25 +953,43 @@ func (api *API) putWorkspaceDormant(rw http.ResponseWriter, r *http.Request) {
...
-					Workspace: workspace,
-					Initiator: initiator.Username,
-					Reason:    "requested by user",
-					CreatedBy: "api",
+				workspace.OwnerID,
+				notifications.TemplateWorkspaceDormant,
+				map[string]string{
+					"name":           workspace.Name,
+					"reason":         "a " + initiator.Username + " request",
+					"timeTilFormant": time.Duration(tmpl.TimeTilDormant).String(),
```
Comment (dannykopping) [inline coderd/workspaces.go:986]:
```suggestion
					"timeTilDormant": time.Duration(tmpl.TimeTilDormant).String(),
```

File: coderd/database/migrations/000232_update_dormancy_notification_template.down.sql [hunk 7]
```diff
@@ -0,0 +1,11 @@
+UPDATE notification_templates
+SET
+    body_template = E'Hi {{.UserName}}\n\n' || E'Your workspace **{{.Labels.name}}** has been marked as **dormant**.\n' || E'The specified reason was "**{{.Labels.reason}} (initiated by: {{ .Labels.initiator }})**\n\n' || E'Dormancy refers to a workspace being unused for a defined length of time, and after it exceeds {{.Labels.dormancyHours}} hours of dormancy might be deleted.\n' || E'To activate your workspace again, simply use it as normal.'
```
Comment (dannykopping) [inline coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:3]: Neither `initiator` nor `dormancyHours` labels are present, AFAICS.
Please test these notifications before submitting your PR.

File: coderd/database/migrations/000232_update_dormancy_notification_template.down.sql [hunk 8]
```diff
@@ -0,0 +1,11 @@
...
+WHERE
+    id = '0ea69165-ec14-4314-91f1-69566ac3c5a0';
+
+UPDATE notification_templates
+SET
+    body_template = E'Hi {{.UserName}}\n\n' || E'Your workspace **{{.Labels.name}}** has been marked for **deletion** after {{.Labels.dormancyHours}} hours of dormancy.\n' || E'The specified reason was "**{{.Labels.reason}}**\n\n' || E'Dormancy refers to a workspace being unused for a defined length of time, and after it exceeds {{.Labels.dormancyHours}} hours of dormancy it will be deleted.\n' || E'To prevent your workspace from being deleted, simply use it as normal.'
```
Comment (dannykopping) [inline coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:9]: Ditto.

File: coderd/database/migrations/000232_update_dormancy_notification_template.up.sql [hunk 9]
```diff
@@ -0,0 +1,16 @@
...
+		E'Your workspace **{{.Labels.name}}** has been marked as [**dormant**](https://coder.com/docs/templates/schedule#dormancy-threshold-enterprise) because of {{.Labels.reason}}.\n' ||
+		E'Dormant workspaces are [automatically deleted](https://coder.com/docs/templates/schedule#dormancy-auto-deletion-enterprise) after {{.Labels.timeTilDormant}} of inactivity.\n' ||
+		E'To prevent deletion, use your workspace with the link below.'
+WHERE
+	id = '0ea69165-ec14-4314-91f1-69566ac3c5a0';
+
+UPDATE notification_templates
+SET
+	body_template = E'Hi {{.UserName}}\n\n' ||
+		E'Your workspace **{{.Labels.name}}** has been marked for **deletion** after {{.Labels.timeTilDormant}} of [dormancy](https://coder.com/docs/templates/schedule#dormancy-auto-deletion-enterprise) because of {{.Labels.reason}}.\n' ||
```
Comment (dannykopping) [inline coderd/database/migrations/000232_update_dormancy_notification_template.up.sql:13]: I'm not sure how this notification was tested before submitting your PR because this label was misnamed.

File: coderd/notifications/notifications_test.go [hunk 10]
```diff
@@ -603,6 +604,99 @@ func TestNotifierPaused(t *testing.T) {
...
+				Scan(&bodyTmpl)
+			require.NoError(t, err, "failed to query body template for template:", tc.id)
+
+			_, err = render.GoTemplate(bodyTmpl, tc.payload, nil)
```
Comment (dannykopping) [inline coderd/notifications/notifications_test.go:694]: What about the title template?

**Review by dannykopping — CHANGES_REQUESTED** [review]
We need a bit more attention to detail here please.
I think we should look into your idea of golden files for these email templates; we're missing too many mistakes without them. Could you add an issue for that?

File: coderd/database/migrations/000232_update_dormancy_notification_template.down.sql (hunk 7 above)
Comment (BrunoQuaresma) [reply coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:3]: This is a "rollback" migration, so it should use the previous values from the applied migration. Maybe you got confused, thinking this was the "up" migration?

Comment (dannykopping) [reply coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:3]: I didn't notice that, you're correct - however I'm not really seeing the point of reverting back to the previous template?

File: coderd/database/migrations/000232_update_dormancy_notification_template.up.sql (hunk 9 above)
Comment (BrunoQuaresma) [reply coderd/database/migrations/000232_update_dormancy_notification_template.up.sql:13]: I was testing it only using the tests, but I can see how flaky it is. I'm starting to wonder if we should test the notifications using the database, so we can catch any mismatches between the template body and provided labels.

This is kind of related to my comment [here](https://github.com/coder/coder/pull/14029#issuecomment-2253287566).

Comment (dannykopping) [reply coderd/database/migrations/000232_update_dormancy_notification_template.up.sql:13]: Agreed, but let's not make it a condition of this PR.
I think we're aligned given what I requested in https://github.com/coder/coder/pull/14029#pullrequestreview-2204224750.

File: coderd/database/migrations/000232_update_dormancy_notification_template.down.sql (hunk 7 above)
Comment (BrunoQuaresma) [reply coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:3]: Me neither, but I suspect it could create some issues while changing branches or navigating commits since the previous code might not expect the new labels, for example. So, I decided to be extra safe.

Comment (dannykopping) [reply coderd/database/migrations/000232_update_dormancy_notification_template.down.sql:3]: I don't think we want to go out-of-sync with the code calling these templates, so let's clear out the down migration here

**Comment by BrunoQuaresma** [comment]
Issue created for tests: https://github.com/coder/team-coconut/issues/32

File: coderd/notifications/notifications_test.go [hunk 11]
```diff
@@ -603,6 +604,105 @@ func TestNotifierPaused(t *testing.T) {
...
+			var (
+				titleTmpl string
+				bodyTmpl  string
+			)
+			err := sql.
+				QueryRow("SELECT title_template, body_template FROM notification_templates WHERE id = $1 LIMIT 1", tc.id).
+				Scan(&titleTmpl, &bodyTmpl)
+			require.NoError(t, err, "failed to query body template for template:", tc.id)
+
+			_, err = render.GoTemplate(titleTmpl, tc.payload, nil)
```
Comment (dannykopping) [inline coderd/notifications/notifications_test.go:697]: I think you should probably also test that these templates aren't empty, just to be safe.

**Review by dannykopping — APPROVED** [review]
Almost there!
I don't need to re-review once you've address the one remaining comment
Thanks @BrunoQuaresma
