### PR TITLE
fix: support additional http headers on agent

### LINKED ISSUE #14462: CODER_HEADER not sent in requests for Coder Agent
Related: https://github.com/coder/coder/issues/6520 , https://github.com/coder/coder/issues/14412

While trying to get the Coder Agent to bypass an identity-aware proxy, it appears that the `coder agent` command does not respect the CODER_HEADER or CODER_HEADER_COMMAND environment variables or command line parameters. I wrote a small script to use for CODER_HEADER_COMMAND that outputs a log entry to the systemd journal, and it is clear that it is never triggered by Coder in the process of attempting to connect to the far end coderd.

They are respected by the other commands I tested, e.g. `coder login`, `coder list`, etc. all work well.

Please let me know if there's some additional debug output I can grab. 

Maybe the work in https://github.com/coder/coder/pull/6521/files is insufficient and missed being applied to agents completely somehow?

### PR DESCRIPTION
**Pull request by ethanndickson**
Fixes #14462.

Currently, the `agent` subcommand does not consume `CODER_HEADER/--header` or `CODER_HEADER_COMMAND/--header-command`. 

This PR adds `CODER_AGENT_HEADER/--agent-header` and `CODER_AGENT_HEADER_COMMAND/--agent-header-command` instead of consuming the global ones. 
This was done as other options for agent authentication differentiate themselves by using an agent prefix (token, url, token_file), to avoid unintentionally populating the options on an agent using a client configuration.

#11901 will likely supersede this, long-term.

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#14464** <a href="https://app.graphite.dev/github/pr/coder/coder/14464?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ethanndickson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: cli/agent.go [hunk 1]
```diff
@@ -361,6 +371,18 @@ func (r *RootCmd) workspaceAgent() *serpent.Command {
...
+			Env:         "CODER_AGENT_HEADER_COMMAND",
+			Value:       serpent.StringOf(&agentHeaderCommand),
+			Description: "An external command that outputs additional HTTP headers added to all requests. The command must output each header as `key=value` on its own line.",
+		},
+		{
+			Flag:        "agent-header",
+			Env:         "CODER_AGENT_HEADER",
+			Value:       serpent.StringArrayOf(&agentHeader),
+			Description: "Additional HTTP headers added to all requests. Provide as " + `key=value` + ". Can be specified multiple times.",
+		},
```
Comment (deansheather) [inline cli/agent.go:385]: Can these just go on the agent subcommand?

**Review by deansheather — APPROVED** [review]

File: cli/agent.go (hunk 1 above)
Comment (deansheather) [reply cli/agent.go:385]: NVM I'm dumb
