### PR TITLE
fix: agent panics on closed network

### LINKED ISSUE #5293: flaky: TestAgent tailnet.(*Conn).Close() panics
Spotted in:
https://github.com/coder/coder/actions/runs/3617075588/jobs/6095609319
https://github.com/coder/coder/actions/runs/3605941257/jobs/6076793161
~https://github.com/coder/coder/actions/runs/3601341028/jobs/6067023763~ a different root cause
https://github.com/coder/coder/actions/runs/3621911592/jobs/6105957495

In most cases, the test fails after a few seconds. I'm going to dig deeper as it seems to be a common root cause.

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/5293

This PR adds a simple condition, `network != nil`, to prevent the agent from panicking.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -262,7 +262,9 @@ func (a *agent) createTailnet(ctx context.Context, derpMap *tailcfg.DERPMap) (ne
 		return nil, xerrors.Errorf("create tailnet: %w", err)
 	}
 	defer func() {
-		if err != nil {
+		// Apparently, it's possible to shut down network via agent.Close().
+		// The condition `network != nil` prevents panic in tests.
+		if err != nil && network != nil {
```
Comment (mafredri) [inline agent/agent.go:267]: This one is actually a bit sneaky. This doesn't capture the original intent. We should probably rename either the return variable or the variable in `network, err =`. We want to do close on the function local network which is always non-nil here, not on the return variable which is nil if `return nil, err`.

Comment (mtojek) [reply agent/agent.go:267]: > We want to do close on the function local network which is always non-nil here, not on the return variable which is nil if return nil, err.

Looking at the source of `createTailnet`, it doesn't seem to be possible to have a nilled network, unless ...

`a.network = network` is set in 2 places: [first](https://github.com/coder/coder/blob/main/agent/agent.go#L218) and [second](https://github.com/coder/coder/blob/061635c36d6d73f27421e361a01e0976ecd8477e/agent/agent.go#L269). In the first, it's guarded with a mutex. 

It seems natural to reduce one `a.network = network`? I guess that's the only option to have a `network = nil`.

Comment (mtojek) [reply agent/agent.go]: Ok, we had an offline chat with Mathias and came up with a bit different solution.

File: agent/agent.go [hunk 2]
```diff
@@ -266,7 +266,6 @@ func (a *agent) createTailnet(ctx context.Context, derpMap *tailcfg.DERPMap) (ne
 			network.Close()
 		}
 	}()
-	a.network = network
```
Comment (mafredri) [inline agent/agent.go:269]: Let's be mindful about this one if we notice anything weird with the stats agent. Some stats message may be discarded until `a.network` is reassigned. But maybe this won't matter?

**Review by mafredri — APPROVED** [review]
LGTM!

File: agent/agent.go (hunk 2 above)
Comment (mtojek) [reply agent/agent.go:269]: Yes, I will keep an eye on this one.
