### PR TITLE
fix: extract checkbox label from dynamic parameter styling prop

### LINKED ISSUE #17474: parameters: how can/should we support a different checkbox value from the title
IMO, this looks clunky with the display name being displayed twice
Image

```hcl
data "coder_parameter" "ai" {
  name        = "ai"
  display_name = "Use AI?"
  description = "Do you want to use AI for this workspace?"
  type        = "bool"
  form_type   = "checkbox"
  default = false
  order       = 0
}
```

Maybe we support more text via `styling`? One idea:
Image

```hcl
data "coder_parameter" "ai" {
  name        = "ai"
  display_name = "Use AI?"
  description = "Do you want to use AI for this workspace?"
  type        = "bool"
  form_type   = "checkbox"
  default = false
  order       = 0
  styling = jsonencode({
    label = "Enable AI functionality for this template"
  })
}
```

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves #17474 

A label will only be shown next to the checkbox If there is a value for `label` in the styling prop for the dynamic parameter

Screenshot 2025-05-01 at 21 35 32

### CODE REVIEW

**Review by aslilac — COMMENTED** [review]
we need to fix whatever the type of `parameter.styling` is here. even if it's just `Record<string, string>`, that's better than one off type assertions littered all over the place.

**Comment by jaaydenh** [comment]
@aslilac improved the handling of parameter styling

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx [hunk 1]
```diff
@@ -470,6 +471,7 @@ export const CreateWorkspacePageViewExperimental: FC<
 
 							<div className="flex flex-col gap-9">
 								{parameters.map((parameter, index) => {
+									const styling = parameter.styling as ParameterStyling;
```
Comment (aslilac) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx:474]: yeah but this is still an inline cast. whatever the type of `parameter` is here should have a `styling: ParameterStyling;` member.

Comment (jaaydenh) [reply site/src/pages/CreateWorkspacePage/CreateWorkspacePageViewExperimental.tsx]: Updated the styling type in coder/preview

**Review by aslilac — APPROVED** [review]
