### PR TITLE
fix: Return deleted users when fetching workspace builds

### LINKED ISSUE #4359: Coder fails to retrieve workspaces
Using release v0.9.2

This only affects some users.
It started happening after enabling github login, but affects both local and github users.

`{2022-10-04 08:43:40.244 [WARN]  (coderd)        <./coderd/httpmw/logger.go:54>  Logger.func1.1  GET  
{"host": "coder.somewhere.com", "path": "/api/v2/workspaces", "proto": "HTTP/1.1", "remote_addr": "10.111.112.219:59792", "took": "54.363056ms", "status_code": 500, "latency_ms": 54, "response_body": "{\"message\":\"Internal error fetching workspace resources.\",\"detail\":\"convert workspace builds: converting workspace build: build initiator not found for workspace: \\\"test\\\"\"}\n", "request_id": "48a31c5b-d685-4ab0-b77d-fe6b82923d2e"}
`

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4359.

### CODE REVIEW

File: coderd/database/queries/users.sql [hunk 1]
```diff
@@ -9,7 +9,10 @@ LIMIT
 	1;
 
 -- name: GetUsersByIDs :many
-SELECT * FROM users WHERE id = ANY(@ids :: uuid [ ]) AND deleted = @deleted;
+-- This should check for deleted, because it's frequently used
```
Comment (deansheather) [inline coderd/database/queries/users.sql:12]: you mean shouldn't?

**Review by deansheather — APPROVED** [review]

File: coderd/database/queries/users.sql (hunk 1 above)
Comment (kylecarbs) [reply coderd/database/queries/users.sql:12]: Yup, ty
