### PR TITLE
fix: Use "virtual_machine_id" for instance identity with Azure

### LINKED ISSUE #3315: azure-instance-identity authentication uses different instance_id than provisioner
when using the `azurerm` terraform provider, the coder provisioner returns an `instance_id` like

/subscriptions/05e8b285-4ce1-46a3-b4c9-f51ba67d6acc/resourceGroups/coder-spike-spikeaz-resources/providers/Microsoft.Compute/virtualMachines/coder-spike-spikeaz-vm

However the Coder Agent, using the Azure metadata service, calls Coder Server with `vmId` like: 90c8eeb0-597a-4df8-8ab6-dc25521d0989

This is rejected by Coder Server.

```
2022-07-29 17:58:40.865 [WARN]	<./cli/agent.go:152>	workspaceAgent.func1	authenticate workspace	{"method": "azure-instance-identity", "error": "POST https://fccac451dc692c5a665d211025e3015e.pit-1.try.coder.app/api/v2/workspaceagents/azure-instance-identity: unexpected status code 404: Instance with id \"90c8eeb0-597a-4df8-8ab6-dc25521d0989\" not found."}
```

### PR DESCRIPTION
**Pull request by kylecarbs**
This was using the wrong property, causing automatic auth to break.

Fixes #3315.

### CODE REVIEW

File: provisioner/terraform/resources.go [hunk 1]
```diff
@@ -310,8 +310,8 @@ func applyAutomaticInstanceID(resource *tfjson.StateResource, agents []*proto.Ag
 	key, isValid := map[string]string{
 		"google_compute_instance":         "instance_id",
 		"aws_instance":                    "id",
-		"azurerm_linux_virtual_machine":   "id",
-		"azurerm_windows_virtual_machine": "id",
+		"azurerm_linux_virtual_machine":   "virtual_machine_id",
+		"azurerm_windows_virtual_machine": "virtual_machine_id",
```
Comment (spikecurtis) [inline provisioner/terraform/resources.go:314]: I'm actually using `azurerm_virtual_machine` in the example template because `azurerm_linux_virtual_machine` doesn't support attaching the data disk before booting, meaning I can't format it in cloud-init

**Review by spikecurtis — APPROVED** [review]

File: provisioner/terraform/resources.go (hunk 1 above)
Comment (kylecarbs) [reply provisioner/terraform/resources.go:314]: Ahh, I'll add that as a resource as well.

Comment (kylecarbs) [reply provisioner/terraform/resources.go:314]: Spike and I discussed, and it doesn't seem that the deprecated `azurerm_virtual_machine` resource exposes the machine ID.
