### PR TITLE
test: add golden files to enterprise cli

### LINKED ISSUE #6766: cli: generate golden files in the enterprise package
This was a problem before the clibase merge, but we aren't verifying diffs for enterprise commands, posing great regression risk.

### PR DESCRIPTION
**Pull request by Emyrk**
Fixes https://github.com/coder/coder/issues/6766

### CODE REVIEW

File: cli/clitest/golden.go [hunk 1]
```diff
@@ -0,0 +1,236 @@
...
+			Cmd:  []string{"users", "list", "--output", "json"},
+		},
+	}
+}
+
+// TestCommandHelp will test the help output of the given commands
+// using golden files.
+//
+//nolint:tparallel,paralleltest
+func TestCommandHelp(t *testing.T, cmds []*clibase.Cmd, cases []CommandHelpCase) {
```
Comment (Emyrk) [inline cli/clitest/golden.go:70]: Just moved this function so it can be reused.

**Comment by ammario** [comment]
Big thank you!

File: enterprise/cli/testdata/coder_groups_list_--help.golden [hunk 2]
```diff
@@ -0,0 +1,77 @@
+Usage: coder [global-flags] <subcommand>
```
Comment (mafredri) [inline enterprise/cli/testdata/coder_groups_list_--help.golden:1]: Something seems wrong here, this is the output for `coder --help`, not `coder groups list --help` (see others as well).

**Review by mafredri — COMMENTED** [review]
A bunch of the golden files seem to be for the wrong command 🤔

File: enterprise/cli/testdata/coder_groups_list_--help.golden (hunk 2 above)
Comment (Emyrk) [reply enterprise/cli/testdata/coder_groups_list_--help.golden:1]: Yea, something is up. Working on it

Comment (Emyrk) [reply enterprise/cli/testdata/coder_groups_list_--help.golden:1]: The issue was I was not making a fresh `*clibase.Cmd` each time, and their was a step of the test that mutates the cmds.

So now I am using a fresh cmd for each test.

Comment (Emyrk) [reply enterprise/cli/testdata/coder_groups_list_--help.golden]: Fixed

**Review by mafredri — APPROVED** [review]

File: enterprise/cli/testdata/coder_wsproxy_--help.golden [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+Aliases: wsproxy
+
+[1mSubcommands[0m
+    create              Create a workspace proxy
+    delete              Delete a workspace proxy
+    edit                Edit a workspace proxy
+    ls                  List all workspace proxies
+    regenerate-token    Regenerate a workspace proxy authentication token. This
+                        will invalidate the existing authentication token.
+    server              Start a workspace proxy server
```
[the remark this answers is not in the document]
Comment (Emyrk) [reply enterprise/cli/testdata/coder_wsproxy_--help.golden:14]: Only for now since the command is hidden: https://github.com/coder/coder/blob/3033a468197b7ccfedf3149340740c12836e4fa0/enterprise/cli/workspaceproxy.go#L21-L21

It's still in experimental. I manually generated the wsproxy though because I know some people are trying it out.

[the remark this answers is not in the document]
Comment (Emyrk) [reply enterprise/cli/testdata/coder_wsproxy_--help.golden:14]: I'll drop the manual one and let it generate when we pull it out of experimental.
