### PR TITLE
fix: don't use adduser and addgroup for docker images

### LINKED ISSUE #3337: Add arm64 and armv7 Docker images
Support for these was removed in #3336 due to an "exec format error". This occurs when building non-amd64 images on an amd64 machine without a virtual machine emulating the instruction set. These builds worked fine when there were no execs in the Dockerfile. With the addition of `adduser`, this became broken.

Some ideas:
- Remove the exec in favor of copying a file
- Use QEMU for non-amd64 architectures

### PR DESCRIPTION
**Pull request by deansheather**
Adds back armv7 and arm64 images. Changes the Dockerfile to avoid using `RUN` and adds comments explaining that `RUN` should never be used.

Uses a `docker cp` to copy the `/etc/passwd` and `/etc/group` files out of the base image (which works on multi-arch using `docker create`), adds the `coder` user/group lines and then copies them back in during the real image build.

Fixes #3337

### CODE REVIEW

File: scripts/build_docker.sh [hunk 1]
```diff
@@ -95,14 +95,27 @@ ln -P Dockerfile "$temp_dir/"
...
+# using the RUN directive in the Dockerfile because you can't use RUN if you're
+# building the image for a different architecture than the host.
+docker pull --platform "$arch" alpine:latest
+
+temp_container_id="$(docker create --platform "$arch" alpine:latest)"
+docker cp "$temp_container_id":/etc/group ./group
+docker cp "$temp_container_id":/etc/passwd ./passwd
+docker rm "$temp_container_id"
+
+echo "coder:x:1000:coder" >> ./group
```
Comment (kylecarbs) [inline scripts/build_docker.sh:111]: Should we just run the proper commands in the container here instead then copy the files? Seems like it could be simpler.

Comment (deansheather) [reply scripts/build_docker.sh:111]: You can't run commands in the container because it's a different architecture. All of the binaries like `sh`, `echo`, `useradd`, `groupadd` etc. are for whatever architecture the image is.

Comment (deansheather) [reply scripts/build_docker.sh:111]: We could just check in the /etc/passwd and /etc/group files to the repo, but then they won't update if alpine changes anything, so I opted for this instead.

Comment (kylecarbs) [reply scripts/build_docker.sh:111]: Oh I mean you can run them in this container instead of doing the echo

Comment (kylecarbs) [reply scripts/build_docker.sh:111]: e.g. `docker exec $temp_container_id adduser`

Comment (deansheather) [reply scripts/build_docker.sh:111]: That won't work since the container is for a different architecture. Docker lets you create containers for different architectures but they won't start because of exec format errors. I'm taking advantage of that here to copy the files out of the image for the correct arch.

Comment (kylecarbs) [reply scripts/build_docker.sh:111]: I 🤦🤦🤦🤦🤦🤦🤦🤦 so hard when I realized how wrong I was.

**Review by kylecarbs — APPROVED** [review]
TY for fixing this so quickly 🥳🥳🥳

**Review by Emyrk — APPROVED** [review]
Cool way around this
