### PR TITLE
fix(site): correctly interpret timezone based on offset in `formatOffset`

### LINKED ISSUE #10784: bug: can't load daily insights
Steps to reproduce
1. Go to insights.
2. Select "Daily"
3. Select a random day range, for example: Nov 1- Nov 20.
4. Result

Screenshot 2023-11-20 at 10 36 04

I guess that it depends on the user location, but for me backend complains about the future timestamp.

Screenshot 2023-11-20 at 10 47 18

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #10784

### CODE REVIEW

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx [hunk 1]
```diff
@@ -791,14 +791,14 @@ function toISOLocal(d: Date, offset: number) {
...
+  // A negative offset means the this is a positive timezone, e.g. GMT+2 = -120.
+  const isPositiveTimezone = offset <= 0;
   const absoluteOffset = Math.abs(offset);
   const hours = Math.floor(absoluteOffset / 60);
   const minutes = Math.abs(offset) % 60;
-  const formattedHours = `${isPositive ? "+" : "-"}${String(hours).padStart(
-    2,
-    "0",
-  )}`;
+  const formattedHours = `${isPositiveTimezone ? "-" : "+"}${String(
```
Comment (mafredri) [inline site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx:799]:
```suggestion
  const formattedHours = `${isPositiveTimezone ? "+" : "-"}${String(
```

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx [hunk 2]
```diff
@@ -791,14 +791,14 @@ function toISOLocal(d: Date, offset: number) {
 }
 
 function formatOffset(offset: number): string {
-  const isPositive = offset >= 0;
+  // A negative offset means the this is a positive timezone, e.g. GMT+2 = -120.
```
Comment (mafredri) [inline site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx:794]:
```suggestion
  // A negative offset means that this is a positive timezone, e.g. GMT+2 = -120.
```
