### PR TITLE
fix(coderd/database): avoid clobbering workspace build state

### LINKED ISSUE #9823: EnterpriseTemplateScheduleStore removes provisioner state from builds
```
	// Update the workspace build.
	err = db.UpdateWorkspaceBuildByID(ctx, database.UpdateWorkspaceBuildByIDParams{
		ID:          build.ID,
		UpdatedAt:   now,
		Deadline:    autostop.Deadline,
		MaxDeadline: autostop.MaxDeadline,
	})
	if err != nil {
		return xerrors.Errorf("update workspace build %q: %w", build.ID, err)
	}
```

https://github.com/coder/coder/blob/e9077f3bd2f0f6bb3a6518cc2d4d5e5bde055831/enterprise/coderd/schedule/template.go#L282

Symptoms
-----------

We are seeing multiple instances of workspace `start` builds with no ProvisionerState after the build completes.  Then, when the user stops their workspace, terraform gets no state, takes no cleanup action, and completes the stop.  Finally, when the user starts their workspace again, they get errors from the underlying infrastructure saying resources already exist.

In our dogfood, this looks like

```
Error: Unable to create container: Error response from daemon: Conflict. The container name "/coder-matifali-coder" is already in use by container "494d08c32846558f4475d58d32341184f46115b32e8215fc02a3808626296f29". You have to remove (or rename) that container to be able to reuse that name.
on main.tf line 329, in resource "docker_container" "workspace":
  329: resource "docker_container" "workspace" {
```

The previous stop will also anomalously report no resources to change or destroy, e.g.

```
Terraform 1.1.9
coder_agent.dev: Plan to create
coder_app.code-server: Plan to create
coder_app.gateway: Plan to create
coder_app.filebrowser: Plan to create
docker_volume.home_volume: Plan to create
docker_image.dogfood: Plan to create
Plan: 6 to add, 0 to change, 0 to destroy.
```

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/9823.

- Decomposes `UpdateWorkspaceBuildByID` into `UpdateWorkspaceBuildProvisionerStateByID` and `UpdateWorkspaceBuildDeadlineByID`.
- Replaces existing invocations of `UpdateWorkspaceBuildByID` with the newer queries where applicable.
- Modifies `GetActiveWorkspaceBuildsByTemplateID` to not return incomplete workspace builds.

### CODE REVIEW

**Review by deansheather — APPROVED** [review]

File: coderd/database/dbauthz/dbauthz_test.go [hunk 1]
```diff
@@ -1232,14 +1232,13 @@ func (s *MethodTestSuite) TestWorkspace() {
...
 		build := dbgen.WorkspaceBuild(s.T(), db, database.WorkspaceBuild{WorkspaceID: ws.ID, JobID: uuid.New()})
-		check.Args(database.UpdateWorkspaceBuildByIDParams{
-			ID:               build.ID,
-			UpdatedAt:        build.UpdatedAt,
-			Deadline:         build.Deadline,
-			ProvisionerState: []byte{},
+		check.Args(database.UpdateWorkspaceBuildDeadlineByIDParams{
+			ID:        build.ID,
+			UpdatedAt: build.UpdatedAt,
+			Deadline:  build.Deadline,
```
Comment (mafredri) [inline coderd/database/dbauthz/dbauthz_test.go:1241]: This is a test, but in theory this clobbers max deadline? Should we do some testing about that?

**Review by mafredri — APPROVED** [review]

File: coderd/database/dbauthz/dbauthz_test.go (hunk 1 above)
Comment (johnstcn) [reply coderd/database/dbauthz/dbauthz_test.go:1241]: In theory, yes - but I want to keep the scope of this limited to provisioner jobs.
We can think about https://github.com/coder/coder/issues/9822 separately.

**Review by mtojek — APPROVED** [review]
👍 once the linter is happy
