### PR TITLE
fix: parse username/workspace correctly on coder state pull --build

### LINKED ISSUE #10884: `coder state pull --build <num>` errors with "Route not found'
Coder version: 2.3.0

I'm trying to inspect a previous state of a workspace because a user is reporting an issue where the home volume size parameter was reset to the default value and they say that did not change that.

I can run `$ coder state pull theuser/wsname`, but adding the `--build <num>` flag always fails with "Route not found.", eg.:

```
$ coder state pull theuser/wsname -b 64
Route not found.
```

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #10884

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10973** <a href="https://app.graphite.dev/github/pr/coder/coder/10973?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/10973?utm_source=stack-comment).

File: cli/state.go [hunk 1]
```diff
@@ -46,7 +46,11 @@ func (r *RootCmd) statePull() *clibase.Cmd {
 				}
 				build = workspace.LatestBuild
 			} else {
-				build, err = client.WorkspaceBuildByUsernameAndWorkspaceNameAndBuildNumber(inv.Context(), codersdk.Me, inv.Args[0], strconv.FormatInt(buildNumber, 10))
+				owner, workspace, err := splitNamedWorkspace(inv.Args[0])
+				if err != nil {
+					return err
+				}
+				build, err = client.WorkspaceBuildByUsernameAndWorkspaceNameAndBuildNumber(inv.Context(), owner, workspace, strconv.FormatInt(buildNumber, 10))
```
Comment (johnstcn) [inline cli/state.go:53]: Non-blocking:

I wonder if it would make sense to introduce something like

```
type WorkspaceName string
type WorkspaceOwner string
```

and make `splitNamedWorkspace` return those types?

File: cli/state_test.go [hunk 2]
```diff
@@ -2,46 +2,40 @@ package cli_test
...
-		template := coderdtest.CreateTemplate(t, client, owner.OrganizationID, version.ID)
-		// Need to create workspace as templateAdmin to ensure we can read state.
-		workspace := coderdtest.CreateWorkspace(t, templateAdmin, owner.OrganizationID, template.ID)
-		coderdtest.AwaitWorkspaceBuildJobCompleted(t, client, workspace.LatestBuild.ID)
+		r := dbfake.WorkspaceBuild(t, store, database.Workspace{
+			OrganizationID: owner.OrganizationID,
+			OwnerID:        taUser.ID,
+		}).
+			Seed(database.WorkspaceBuild{ProvisionerState: wantState}).
+			Do()
```
Comment (johnstcn) [inline cli/state_test.go:36]: :+1:

File: cli/state_test.go [hunk 3]
```diff
@@ -51,32 +45,46 @@ func TestStatePull(t *testing.T) {
...
+		inv, root := clitest.New(t, "state", "pull", r.Workspace.Name)
 		var gotState bytes.Buffer
 		inv.Stdout = &gotState
 		clitest.SetupConfig(t, templateAdmin, root)
 		err := inv.Run()
 		require.NoError(t, err)
 		require.Equal(t, wantState, bytes.TrimSpace(gotState.Bytes()))
 	})
+	t.Run("OtherUserBuild", func(t *testing.T) {
```
Comment (johnstcn) [inline cli/state_test.go:66]: :+1: :+1:

**Review by johnstcn — APPROVED** [review]
