### PR TITLE
fix(coderd): add audit log on creating a new session key

### LINKED ISSUE #19671: CreateAPIKey method invocations should generate audit logs
### Summary
[CreateAPIKey](https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/apikey.go#L423) method invocations should generate audit events.

### Current Behavior
When user runs `coder login` the CLI API Key gets created via [CreateAPIKey](https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/apikey.go#L423)
https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/cli/login.go#L371-L387

The corresponding method invocation lacks explicit [audit.InitRequest](https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/audit/request.go#L350) function call which is required to generate audit log events
https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/userauth.go#L534-L539

As a result all events of this type are missing from the audit logs.

### Proposed Changes
All invocations of the [CreateAPIKey](https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/apikey.go#L423) method should include the [audit.InitRequest](https://github.com/coder/coder/blob/06cbb2890f453cd522bb2158a6549afa3419c276/coderd/audit/request.go#L350) function call.

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/19671
(re-?)Adds an audit log entry when an API key is created via `coder login`.

NOTE: This does _not_ backfill audit logs.

Screenshot 2025-09-02 at 14 16 24

### CODE REVIEW

**Review by deansheather — APPROVED** [review]

File: coderd/apikey.go [hunk 1]
```diff
@@ -131,8 +131,19 @@ func (api *API) postToken(rw http.ResponseWriter, r *http.Request) {
...
-	user := httpmw.UserParam(r)
+	var (
+		ctx               = r.Context()
+		user              = httpmw.UserParam(r)
+		auditor           = api.Auditor.Load()
+		aReq, commitAudit = audit.InitRequest[database.APIKey](rw, &audit.RequestParams{
+			Audit:   *auditor,
+			Log:     api.Logger,
+			Request: r,
+			Action:  database.AuditActionCreate,
```
Comment (jdomeracki-coder) [inline coderd/apikey.go:142]: Won't be visible in the UI if [filter](https://coder.com/docs/admin/security/audit-logs#how-to-filter-audit-logs) will specify `action:login`

Comment (johnstcn) [reply coderd/apikey.go:142]: Correct, typically that gets logged when users authenticate via the Web UI.
