### PR TITLE
fix(UI): workspace restart button stops build before starting a new one

### LINKED ISSUE #6241: Feat. provide a restart button
# Description

For our UseCase (partly ephemeral workspace) it is totally okay to restart a workspace. Currently we have to press stop first and then start the workspace again. It would be nice if one can restart a workspace via a butten in the drop-down menu.

image

### PR DESCRIPTION
**Pull request by Kira-Pilot**
Resolves https://github.com/coder/coder/issues/6241 and replaces the reverted #7268.

I've added a test to ensure the restart button hook is called appropriately but React Query makes it difficult to test side effects so I'm effectively mocking the `stopWorkspace` api call and not the `startWorkspace` api call. I will take a second look at this during a quieter day, but for the time being, smoke testing would be appreciated!

### CODE REVIEW

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx [hunk 1]
```diff
@@ -120,9 +132,11 @@ export const WorkspaceReadyPage = ({
           ),
         }}
         isUpdating={workspaceState.matches("ready.build.requestingUpdate")}
+        isRestarting={isRestarting}
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:135]: @BrunoQuaresma one of the workspace props is `failedBuildLogs`. Looks like this is completely handled by a hook that retrieves the latest build on its own, so I didn't think I needed to pass anything else in. Let me know if you think I'm mistaken!

File: site/src/pages/WorkspacePage/hooks.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+        if ((error as WorkspaceBuild).status === "canceled") {
+          setLoading(false)
+          return
+        }
+        setBuildError(error)
+        setLoading(false)
+      }
+    },
+  })
+}
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/hooks.ts:66]: Originally, I wanted to use an implementation closer to the following, which react query's [docs](https://tanstack.com/query/v4/docs/react/guides/mutations#promises) suggest is possible:
````
 const requestStopWorkspace = useMutation({ mutationFn: stopWorkspace })
 const requestStartWorkspace = useMutation({ mutationFn: startWorkspace })

  const restartWorkspace = async () => {
    try {
      await requestStopWorkspace.mutateAsync(workspace.id)
      await waitForStop(requestStopWorkspace.data)
      await requestStartWorkspace.mutateAsync({
        workspaceId,
        templateVersionId,
      })
    } catch (error) {
      ...   
    }
  }
````

but `mutateAsync` does not seem to be working and the queries are not treated asynchronously. @BrunoQuaresma is this something you've run into before?

**Comment by ammario** [comment]
Thank you for fixing this so quickly :)

**Comment by ammario** [comment]
(Will let Jon review)

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:135]: Not sure if I understand why a new `isRestarting` is needed since you can do `restartWorkspace.isLoading` 🤔

File: site/src/pages/WorkspacePage/hooks.ts [hunk 3]
```diff
@@ -0,0 +1,66 @@
+import {
+  getWorkspaceBuildByNumber,
+  stopWorkspace,
+  startWorkspace,
+} from "api/api"
+import { delay } from "utils/delay"
+import { ProvisionerJob, WorkspaceBuild } from "api/typesGenerated"
+import { useMutation } from "@tanstack/react-query"
+
+export function waitForBuild(build: WorkspaceBuild) {
```
Comment (BrunoQuaresma) [inline site/src/pages/WorkspacePage/hooks.ts:10]: Why do we need to export this function? Also, this is a really good function to be on `api.ts` very useful for other parts of the code we have.

File: site/src/pages/WorkspacePage/hooks.ts [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+      } catch (error) {
+        if ((error as WorkspaceBuild).status === "canceled") {
+          setLoading(false)
+          return
+        }
+        setBuildError(error)
+        setLoading(false)
+      }
+    },
+  })
```
Comment (BrunoQuaresma) [inline site/src/pages/WorkspacePage/hooks.ts:65]: Why not combine all of this into a single function?

```
const build = await stopWorkspace()
 await waitForBuild(data)
const startBuild = await startWorkspace({
  workspaceId: data.workspace_id,
  templateVersionId: data.template_version_id,
})
await waitForBuild(startBuild)

setLoading(false)
```

File: site/src/pages/WorkspacePage/hooks.ts (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/pages/WorkspacePage/hooks.ts:66]: I put a comment above, I think you don't need to have each API call into a "query". You can have a single function to restart the workspace and wrap this function into a query.

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx (hunk 1 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:135]: @BrunoQuaresma That would be true if we didn't have to watch for build logs and then kick off a call to `API.startWorkspace` as a side effect in the `onSuccess` callback. Unfortunately, `restartWorkspace.isLoading` isn't going to capture the time spend waiting for these requests.

File: site/src/pages/WorkspacePage/hooks.ts (hunk 2 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/hooks.ts:66]: Hmmm that's a good idea. Let me try it!

Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/hooks.ts:8]: @BrunoQuaresma Woo that's a lot better! Thanks!

**Review by BrunoQuaresma — APPROVED** [review]

**Review by bpmct — COMMENTED** [review]
Works as expected with AWS template (stops workspace then starts)
