### PR TITLE
fix: prepend scheme to access url

### LINKED ISSUE #2874: `CODER_ACCESS_URL` shouldn't require protocol
As a user, if the access URL is set to `localhost:6080` instead of `http://localhost:6080`, workspaces will fail to build since "localhost" is assumed to be the protocol. We should either show an error that a protocol is required or add a protocol if none exists.

### PR DESCRIPTION
**Pull request by sreya**
- Problems can arise spawning workspaces if a scheme-less URL is passed
  as the access URL.

  If an access URL is detected to not have an "http" or "https" scheme
  then it is prepended with "https". If the hostname is detected
  to be a loopback device then "http" is preferred.

fixes #2874

### CODE REVIEW

File: cli/server.go [hunk 1]
```diff
@@ -672,6 +673,54 @@ func server() *cobra.Command {
 	return root
 }
 
+// parseURL parses a string into a URL. It works around some technically correct
+// but undesired behavior of url.Parse by prepending a scheme if one does not
+// exist so that the URL does not get parsed improprely.
+func parseURL(ctx context.Context, u string) (*url.URL, error) {
+	var (
+		hasScheme = strings.HasPrefix(u, "http") || strings.HasPrefix(u, "https")
+	)
```
Comment (kylecarbs) [inline cli/server.go:682]: Let's parse for a colon appending these. Otherwise, the weird case of a domain starting with `http` or `https` could conflict here.

**Review by kylecarbs — APPROVED** [review]
