### PR TITLE
fix: re-add original create template context menu

### LINKED ISSUE #14323: New scratch template and upload template are not visible in the UI
Hello,

[I've been told](https://github.com/coder/coder/discussions/14258#discussioncomment-10356083) there should be buttons to:
- create a new template from scratch
- upload a template

But I don't see either.

https://github.com/user-attachments/assets/a947aba9-8396-46e7-af20-29127c2f23cb

CleanShotX - Arc  16 08 2024 at 11-27-39 @2x
CleanShotX - Arc  16 08 2024 at 11-27-58 @2x
CleanShotX - Arc  16 08 2024 at 11-28-26 @2x
CleanShotX - Arc  16 08 2024 at 11-30-48 @2x

```
coder --version
Coder v2.14.1+db94b30 Wed Aug  7 16:56:07 UTC 2024
https://github.com/coder/coder/commit/db94b30b1c418b3ab77a0f5e205a2992288b10e7
```

Coder was installed on a VPS running `Ubuntu 24.04` with:
`curl -L https://coder.com/install.sh | sh`

Browsers tested (macOS):
- Arc 1.56.0 (52658)
Chromium Engine Version 127.0.6533.120
- Safari 17.6

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves #14323

This adds back the original create template button context menu for users that do not have the experiment `multi-organization' enabled.

Screenshot 2024-08-16 at 10 33 19 AM

### CODE REVIEW

File: site/src/pages/TemplatesPage/TemplatesPageView.tsx [hunk 1]
```diff
@@ -190,27 +192,31 @@ export const TemplatesPageView: FC<TemplatesPageViewProps> = ({
 	examples,
 	templates,
 }) => {
+	const { experiments } = useDashboard();
 	const isLoading = !templates;
 	const isEmpty = templates && templates.length === 0;
 	const navigate = useNavigate();
+	const multiOrgExperimentEnabled = experiments.includes("multi-organization");
+	console.log("multiOrgExperimentEnabled", multiOrgExperimentEnabled);
```
Comment (aslilac) [inline site/src/pages/TemplatesPage/TemplatesPageView.tsx:200]: `console.log`

**Review by aslilac — APPROVED** [review]
just remove the log pls
