### PR TITLE
fix: track JetBrains connections

### LINKED ISSUE #9673: API: `/api/v2/deployment/stats` does not return count for JetBrains Gateway sessions
the `/api/v2/deployment/stats` endpoint returns the below connection figures:

```json
"session_count": {
    "vscode": 1,
    "ssh": 0,
    "jetbrains": 0,
    "reconnecting_pty": 0
```

however, the `session_count.jetbrains` figure is not incremented when I open a JetBrains Gateway connection. what is expected to occur for the figure to be `>0`?

# Jetbrains issue

https://youtrack.jetbrains.com/issue/GTW-2288/SSH-Config-SendEnv-not-working-windows

The `SetEnv` and `SendEnv` ssh config fields are **ignored** by Jetbrain's custom ssh implementation. There is no trivial way to fix this. We would have to send the jetbrains information in some other way.

### PR DESCRIPTION
**Pull request by code-asher**
Fixes #9673 

Possibly we will need to find a better string to match on, but this one seems OK to me.

Unit test passes but have not tested an actual deploy yet.

### CODE REVIEW

**Comment by code-asher** [comment]
Ah wait moving back to draft, there seems to be an issue...

File: agent/agent_test.go [hunk 1]
```diff
@@ -191,6 +191,60 @@ func TestAgent_Stats_Magic(t *testing.T) {
 		err = session.Wait()
 		require.NoError(t, err)
 	})
+
+	// This test name must contain the string checked for by the agent, since it
+	// looks for this string in the process name.
+	t.Run("TracksIdea.vendor.name=JetBrains", func(t *testing.T) {
```
Comment (Emyrk) [inline agent/agent_test.go:197]: Lets add some more comments as this is not intuitive. 

```suggestion
	// This test name must contain the string checked for by the agent, since it
	// looks for this string in the process name.
	//
	// This test sets up a port forward that emulates what Jetbrains IDE's do when
	// using gateway. The remote server side of the port forward is spun up using
	// the gotest process, which includes the test name.
	// So this unit test emulates a PID in the workspace with a similar
	// name to the jetbrains IDE. That makes the agent this this SSH port
	// forward is a "jetbrains" session.
	t.Run("TracksIdea.vendor.name=JetBrains", func(t *testing.T) {
```

File: agent/agentssh/jetbrainstrack.go [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+	"strings"
+	"sync"
+
+	"cdr.dev/slog"
+	"github.com/gliderlabs/ssh"
+	"go.uber.org/atomic"
+	gossh "golang.org/x/crypto/ssh"
+)
+
+type localForwardChannelData struct {
```
Comment (Emyrk) [inline agent/agentssh/jetbrainstrack.go:13]:
```suggestion
// localForwardChannelData is copied from the ssh package.
type localForwardChannelData struct {
```

File: agent/agentssh/jetbrainstrack.go [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+	DestAddr string
+	DestPort uint32
+
+	OriginAddr string
+	OriginPort uint32
+}
+
+type ChannelAcceptWatcher struct {
```
Comment (Emyrk) [inline agent/agentssh/jetbrainstrack.go:21]:
```suggestion
// ChannelAcceptWatcher is used to track jetbrains port forwarding (gateway)
// connections. If the port forward is something other than jetbrains, this
// struct is a noop.
type ChannelAcceptWatcher struct {
```

File: agent/agentssh/jetbrainstrack.go [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+	gossh.NewChannel
+	jetbrainsCounter *atomic.Int64
+}
+
+func NewChannelAcceptWatcher(ctx ssh.Context, logger slog.Logger, newChannel gossh.NewChannel, counter *atomic.Int64) gossh.NewChannel {
```
Comment (Emyrk) [inline agent/agentssh/jetbrainstrack.go:26]: Is this a bad name?
```suggestion
func WatchForJetbrains(ctx ssh.Context, logger slog.Logger, newChannel gossh.NewChannel, counter *atomic.Int64) gossh.NewChannel {
```

File: agent/agentssh/jetbrainstrack.go (hunk 3 above)
Comment (Emyrk) [inline agent/agentssh/jetbrainstrack.go:21]: Lets call it something pretty direct?
```suggestion
type JetbrainsNewChannel struct {
```

File: agent/agentssh/jetbrainstrack.go (hunk 4 above)
Comment (code-asher) [reply agent/agentssh/jetbrainstrack.go:30]: Yeah I think you are right, will rename!

**Comment by code-asher** [comment]
The two issues I ran into, just FYI:

- I had the process name check reversed, needed a `!` :facepalm: 
- Netstat only gives the base name, not the full command line, so I need to read `/proc/$pid/cmdline` to get that.

I think it is all sorted now, doing some more testing to be sure.

**Comment by matifali** [comment]
Will this also work for Fleet?

**Comment by code-asher** [comment]
> Will this also work for Fleet?

I am not sure, we will need to test.

**Review by Emyrk — APPROVED** [review]
Looks good, let's get this in and test it a bit.
