### PR TITLE
fix(site): retry and debug passing build parameters options

### LINKED ISSUE #11748: Not possible to easily change ephemeral parameters on failed build
There used to be a dropdown, now it's just "Retry". I don't want to retry without changing ephemeral parameter though.

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Close https://github.com/coder/coder/issues/11748

Screenshot 2024-03-01 at 14 52 39

### CODE REVIEW

File: site/src/testHelpers/handlers.ts [hunk 1]
```diff
@@ -438,4 +444,8 @@ export const handlers = [
   rest.get("/api/v2/workspaceagents/:agent/listening-ports", (_, res, ctx) => {
     return res(ctx.status(200), ctx.json(M.MockListeningPortsResponse));
   }),
+
+  rest.get("/api/v2/integrations/jfrog/xray-scan", (_, res, ctx) => {
+    return res(ctx.status(404));
+  }),
```
Comment (Kira-Pilot) [inline site/src/testHelpers/handlers.ts:450]: Why did we add these?

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx [hunk 2]
```diff
@@ -438,4 +438,102 @@ describe("WorkspacePage", () => {
       });
     });
   });
+
+  it("retry with build parameters", async () => {
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/WorkspacePage.test.tsx:442]: nice!

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx [hunk 3]
```diff
@@ -438,4 +438,102 @@ describe("WorkspacePage", () => {
...
+      latest_build: {
+        ...MockFailedWorkspace.latest_build,
+        transition: "start",
+      },
+    } satisfies Workspace;
+    const parameter = {
+      ...MockTemplateVersionParameter1,
+      display_name: "Parameter 1",
+      ephemeral: true,
+    } satisfies TemplateVersionParameter;
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/WorkspacePage.test.tsx:455]: Why do we have to use `satisifes` here and above?

**Review by Kira-Pilot — APPROVED** [review]
When Storybook is happy I'm happy!

File: site/src/testHelpers/handlers.ts (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/testHelpers/handlers.ts:450]: To avoid getting unhandled request warnings during tests. The warning was introduced many PRs ago but I only noticed it now since it was messing with the output for my tests so I just fixed it.
