### PR TITLE
fix: initialize terminal with correct size

### LINKED ISSUE #9806: Web terminal is unusable with nano/vim etc
version: https://github.com/coder/coder/commit/b742661abde02f1fbceccb773ab5a634ad87e845
client OS: Windows

https://github.com/coder/coder/assets/10648092/f5efa7f6-f39d-47d2-984f-ea2384492c03

This makes using vim/nano almost impossible.
I cannot scroll down to the following content. 

cc: @BrunoQuaresma @bpmct

### PR DESCRIPTION
**Pull request by code-asher**
Currently we spawn the terminal at 80x80 (the default when no initial size is provided) and then resize shortly afterward.

It appears that `screen` sometimes ignores this resize, but at the same time it seems to remember it because trying to resize it again with that size does nothing.

The solution seems to be to start `screen` with the right size from the get-go.  From my testing, this fixes https://github.com/coder/coder/issues/9806.  It can be done by providing the size as query parameters on the web socket URL.

I also tweaked the `fitAddon` calls and fixed an issue with every message causing a resize (more info in the commit messages).

### CODE REVIEW

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 1]
```diff
@@ -134,13 +132,21 @@ const TerminalPage: FC = () => {
...
+    // overflow slightly in some scenarios. Applying a second fit resolves this.
+    fitAddon.fit();
+    fitAddon.fit();
+
+    // This will trigger a resize event on the terminal.
+    const listener = () => fitAddon.fit();
     window.addEventListener("resize", listener);
+
+    // Terminal is correctly sized and is ready to be used.
+    setTerminal(terminal);
```
Comment (Parkreiner) [inline site/src/pages/TerminalPage/TerminalPage.tsx:148]: Is moving the `setTerminal` call just for clarity? Just making sure – because of how/when React flushes state changes, moving the call in this case doesn't actually change anything

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 2]
```diff
@@ -134,13 +132,21 @@ const TerminalPage: FC = () => {
...
     terminal.open(xtermRef.current);
-    const listener = () => {
-      // This will trigger a resize event on the terminal.
-      fitAddon.fit();
-    };
+
+    // We have to fit twice here. It's unknown why, but the first fit will
+    // overflow slightly in some scenarios. Applying a second fit resolves this.
+    fitAddon.fit();
+    fitAddon.fit();
```
Comment (Parkreiner) [inline site/src/pages/TerminalPage/TerminalPage.tsx:141]: I don't know much about xterm, but moving the calls does seem like a good change.

Just making sure for my own understanding – is the terminal expected to resize only when the browser/window viewport does?

**Review by buenos-nachos — APPROVED** [review]
Changes look good. Just had a few questions

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 1 above)
Comment (code-asher) [reply site/src/pages/TerminalPage/TerminalPage.tsx:148]: Yup exactly, I just felt it flowed better but that is probably rather subjective.

Comment (code-asher) [reply site/src/pages/TerminalPage/TerminalPage.tsx:148]: To be honest part of me also wanted to move it just because I do not necessarily trust what React does behind the scenes hahaha, this way I think the intent is clearer at least even if it is functionally identical.
