### PR TITLE
fix: only show error once when failing to update org member roles

### LINKED ISSUE #1030: flake: OrganizationMembersPage error message test - multiple elements found
## CI Failure Details

**CI Run Link:** https://github.com/coder/coder/actions/runs/18009419216/job/51237723285

**Commit Info:** 
- SHA: `fc9bff7107acb7b44e499e93dc89c9a99d0a5b44`
- Failed Job: `test-js` (Job ID: 51237723285)

**Test Location:** `site/src/pages/OrganizationSettingsPage/OrganizationMembersPage.test.tsx:137`

**Test Path:** `OrganizationMembersPage › Update user role › when it fails › shows an error message`

## Error Analysis

**Error Message:**
```
Found multiple elements with the text: Error on updating the user roles.

Here are the matching elements:

<div class="MuiTypography-root MuiTypography-body1 MuiTypography-gutterBottom MuiAlertTitle-root css-1iedavw-MuiTypography-root-MuiAlertTitle-root">
  Error on updating the user roles.
</div>

<span class="css-1c1e297">
  Error on updating the user roles.
</span>
```

**Root Cause:** The test expects to find exactly one element containing "Error on updating the user roles." but the UI now renders this error message in multiple DOM elements (both in a MUI Alert component and a span). The test uses `screen.findByText()` which fails when multiple elements match.

## Assignment Analysis

**Git Blame Results:**
```bash
git blame -L 122,138 site/src/pages/OrganizationSettingsPage/OrganizationMembersPage.test.tsx
```
Shows that the failing test function (lines 122-138) was last modified by:
- **Kayla Washburn-Love** (commit 95a7c0c4f0) on 2024-08-15
- Most test logic authored by Kayla Washburn-Love
- Minor URL template string updated by Bruno Quaresma on line 125

**Assignment Rationale:** Following the primary assignment strategy of git blame on the specific test function, Kayla Washburn-Love (@aslilac) should be assigned as she authored the core test logic including the failing assertion.

## Suggested Fix

The test should be updated to handle multiple elements with the same text. Options:
1. Use `getAllByText()` or `findAllByText()` and assert on array length
2. Use a more specific selector to target the intended element
3. Use `getByRole()` with more specific criteria

## Related Issues

No duplicate issues found in comprehensive search of coder/internal repository.

### PR DESCRIPTION
**Pull request by aslilac**
Closes https://github.com/coder/internal/issues/1030

the flake stems from the fact that we're showing both a toast with the error, and it's being displayed persistently with `ErrorAlert`. sometimes the assert would happen before the toast rendered, allowing the test to pass.

as recently discussed, showing toasts for errors is not a best practice, especially when showing the error persistently with `ErrorAlert` is a good possibility. we're already doing that, so the toast is redundant.

### CODE REVIEW

File: site/src/pages/OrganizationSettingsPage/OrganizationMembersPageView.tsx [hunk 1]
```diff
@@ -152,11 +152,7 @@ export const OrganizationMembersPageView: FC<
 												try {
 													await updateMemberRoles(member, roles);
 													displaySuccess("Roles updated successfully.");
-												} catch (error) {
-													displayError(
-														getErrorMessage(error, "Failed to update roles."),
-													);
-												}
+												} catch {}
```
Comment (BrunoQuaresma) [inline site/src/pages/OrganizationSettingsPage/OrganizationMembersPageView.tsx:157]: Since we’re not catching anything, we can remove the try/catch block entirely to avoid hiding errors.

**Review by BrunoQuaresma — APPROVED** [review]
I just have one observation, but it’s not a blocker.

File: site/src/pages/OrganizationSettingsPage/OrganizationMembersPageView.tsx (hunk 1 above)
Comment (buenos-nachos) [reply site/src/pages/OrganizationSettingsPage/OrganizationMembersPageView.tsx:157]: Yeah, it wouldn't have any bearing on the actual UI, but it feels like if something breaks, it'd be more valuable to have something still get logged to the console instead of having the error get swallowed entirely

Plus, a try/catch with an empty catch block and no comment explaining what we're doing feels weird

Comment (aslilac) [reply site/src/pages/OrganizationSettingsPage/OrganizationMembersPageView.tsx:157]: the test fails without it for some reason. :\ testing-library doesn't like uncaught errors I guess, even if react doesn't care about them
