### PR TITLE
fix: workspace schedule time displays

### LINKED ISSUE #2235: Shutdown section: if Time until shutdown is more than 24h displayed value is confusing
Shutdown section displays time of workspace shutdown, but for case I have TTL more that 24h that value looks confusing as it will be the next day or in a couple of days, but looks like in the nearest future.

coder version:
[Coder v0.0.0-devel+6ea86c8](https://github.com/coder/coder/commit/6ea86c831b5eb1abd549e5450a932acf0ebf9aba)

Steps: 
1. Create a workspace with Time till shutdown 36 hours
2. View Schedule section on workspace page: Shutdown time is displayed only, but it will happen not even on the next day.

***Expected*** 
maybe add date for such cases? or note about that if will happen in n days?
***Actual*** 
only time is displayed

I set time until shutdown this way: 
image

But see it on workspace page as:
image

### PR DESCRIPTION
**Pull request by greyscaled**
Resolves: #2235

Summary:

Various time displays weren't quite right.

Details:

- Display date (not just time) of upcoming workspace stop in workspace
page
- Fix ttlShutdownAt for various cases + tests
  --> manual to non-manual
  --> unchanged/unmodified
  --> isBefore --> isSameOrBefore
  --> use the delta (off by _ error)

### CODE REVIEW

File: site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx [hunk 1]
```diff
@@ -282,19 +283,31 @@ export const WorkspaceScheduleForm: FC<WorkspaceScheduleFormProps> = ({
...
-  if (!isWorkspaceOn(workspace)) {
+export const ttlShutdownAt = (now: dayjs.Dayjs, workspace: Workspace, tz: string, formTTL: number): string => {
+  // a manual shutdown has a deadline of '"0001-01-01T00:00:00Z"'
+  // SEE: #1834
+  const deadline = dayjs(workspace.latest_build.deadline).utc()
+  const hasDeadline = deadline.year() > 1
+  const ttl = workspace.ttl_ms ? workspace.ttl_ms / (1000 * 60 * 60) : 0
+  const delta = formTTL - ttl
+
+  console.info("delta :: ", delta)
```
Comment (vapurrmaid) [inline site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx:294]:
```suggestion
```

File: site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx [hunk 2]
```diff
@@ -282,19 +283,29 @@ export const WorkspaceScheduleForm: FC<WorkspaceScheduleFormProps> = ({
...
-    return `⚠️ ${Language.ttlCausesShutdownHelperText} ${Language.ttlCausesShutdownImmediately} ⚠️`
-  } else if (newDeadline.isBefore(now.add(30, "minute"))) {
-    return `⚠️ ${Language.ttlCausesShutdownHelperText} ${Language.ttlCausesShutdownSoon} ⚠️`
   } else {
-    const newDeadlineString = newDeadline.tz(tz).format("hh:mm A z")
-    return `${Language.ttlCausesShutdownHelperText} ${Language.ttlCausesShutdownAt} ${newDeadlineString}.`
+    const newDeadline = dayjs(hasDeadline ? deadline : now).add(delta, "hour")
+    if (newDeadline.isSameOrBefore(now)) {
+      return `⚠️ ${Language.ttlCausesShutdownHelperText} ${Language.ttlCausesShutdownImmediately} ⚠️`
+    } else if (newDeadline.isSameOrBefore(now.add(30, "minute"))) {
```
Comment (vapurrmaid) [inline site/src/components/WorkspaceScheduleForm/WorkspaceScheduleForm.tsx:302]:
```suggestion
    } else if (newDeadline.isSameOrBefore(now.add(30, "minutes"))) {
```

**Review by johnstcn — APPROVED** [review]

**Review by Kira-Pilot — APPROVED** [review]
