### PR TITLE
fix: update default value handling for dynamic defaults

### LINKED ISSUE #102: Frontend default value handling
Currently it is not possible to have dynamic defaults for parameters because

The existing frontend logic only uses `default_value` for the parameters on initial page load. For any additional responses from the websocket, the `value` is used instead of `default_value`

Goal:

The frontend should only send parameter values for parameters the user has modified since the last page load. 

This means that the last modified parameter value and all previously touched parameters values will be sent in a request.

Since `value` and `default_value` are always the same the frontend will use `value` if it exists and is valid. Otherwise, in case of input, textarea, dropdown and combobox components, the initial form control value will be considered empty string "".

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves coder/preview#102

### CODE REVIEW

File: site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx [hunk 1]
```diff
@@ -195,30 +199,28 @@ const ParameterField: FC<ParameterFieldProps> = ({
...
-				},
-			);
+			const selectedOptions: Option[] = JSON.parse(value).map((val: string) => {
+				const option = parameter.options.find((o) => o.value.value === val);
+				return {
+					value: val,
+					label: option?.name || val,
+					disable: false,
+				};
+			});
```
Comment (aslilac) [inline site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx:215]: this is screaming for some sort of typing issue here. how confident are we that `JSON.parse(value)` will actually always return a `string[]` here?

Comment (jaaydenh) [reply site/src/modules/workspaces/DynamicParameter/DynamicParameter.tsx]: Improved

**Review by aslilac — APPROVED** [review]
