### PR TITLE
fix: allow for alternate usernames on conflict

### LINKED ISSUE #4576: Duplicate key on OpenID connect
Hello, I am working on a cluster setup for devops & developer trainings. A central part of it is coder to give the participants a fancy development environment. For email based self registration I use keycloak and OIDC in coder. I don't now the email domains, so it is not possible to restrict them.

When 2 users with the same name before the @ try to register (e. g. hans@example1.com and hans@example2.com), the second user gets the error:

    {"message":"Failed to process OAuth login.","detail":"in tx: execute transaction: create user: execute transaction: create user: pq: duplicate key value violates unique constraint \"idx_users_username\""}

Is it possible to configure how the names a built? May by converting hans@example2.com to hans-example2-com or similar. Or give the second user a number suffix (hans2).

### PR DESCRIPTION
**Pull request by sreya**
fixes #4576

### CODE REVIEW

File: coderd/coderdtest/coderdtest.go [hunk 1]
```diff
@@ -725,6 +727,79 @@ func NewAWSInstanceIdentity(t *testing.T, instanceID string) (awsidentity.Certif
 		}
 }
 
+type FakeOIDCConfig struct {
+	key    *rsa.PrivateKey
+	issuer string
+}
+
+func NewFakeOIDCConfig(t *testing.T, issuer string) *FakeOIDCConfig {
```
Comment (kylecarbs) [inline coderd/coderdtest/coderdtest.go:735]: I might just call this `OIDCConfig` instead. Not a biggie and totally a nit tho. Since it's in the `coderdtest` pkg it might be explicit

File: coderd/userauth.go [hunk 2]
```diff
@@ -390,6 +391,35 @@ func (api *API) oauthLogin(r *http.Request, params oauthLoginParams) (*http.Cook
...
+			_, err := tx.GetUserByEmailOrUsername(ctx, database.GetUserByEmailOrUsernameParams{
+				Username: params.Username,
+			})
+			if err == nil {
+				var (
+					original      = params.Username
+					validUsername bool
+				)
+				for i := 0; i < 10; i++ {
+					params.Username = fmt.Sprintf("%s_%s", original, namesgenerator.GetRandomName(10))
```
Comment (kylecarbs) [inline coderd/userauth.go:403]: I believe this could result in a really long name, right? Because we aren't checking it against validation again.

File: coderd/coderdtest/coderdtest.go (hunk 1 above)
Comment (sreya) [reply coderd/coderdtest/coderdtest.go:735]: I actually called it that before I renamed it, I'll revert it.

File: coderd/userauth.go (hunk 2 above)
Comment (sreya) [reply coderd/userauth.go:403]: Good point

File: coderd/coderdtest/coderdtest.go [hunk 3]
```diff
@@ -725,6 +727,79 @@ func NewAWSInstanceIdentity(t *testing.T, instanceID string) (awsidentity.Certif
...
+type OIDCConfig struct {
+	key    *rsa.PrivateKey
+	issuer string
+}
+
+func NewOIDCConfig(t *testing.T, issuer string) *OIDCConfig {
+	t.Helper()
+
+	pkey, err := rsa.GenerateKey(rand.Reader, 2048)
+	require.NoError(t, err)
```
Comment (kylecarbs) [inline coderd/coderdtest/coderdtest.go:739]: I _think_ this takes a while to gen. Might wanna just make it a static key

**Review by kylecarbs — APPROVED** [review]
