### PR TITLE
fix: mock Agent querying OS for listening ports in tests

### LINKED ISSUE #1123: flake: TestWorkspaceAgentListeningPorts/LinuxAndWindows/OK_Mainline
Seen while testing locally.

Repeatedly see

```
    workspaceagents_test.go:1108: expected to not find TCP port 33133 in response
```

until the test context expires.

The test itself is funadmentally flaky: it creates a listener on the real OS networking stack, verifies it shows up in the list of listening ports, then closes the listener and verfies the port doesn't show up. However, the OS can immediately reuse the port for something else, so there is no guarantee the agent won't see the port still in use, especially on a busy system that runs multiple tests in parallel.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes https://github.com/coder/internal/issues/1123

We want to tests that ports are not included after they are no longer used, but this isn't safe on the real OS networking stack because there is no way to guarantee a port _won't_ be used. Instead, we introduce an interface and fake implementation for testing.

On order to leave the filtering logic in the test path, this PR also does some refactoring.

Caching logic is left in the real OS querying implementation and a new test case is added for it in this PR.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#20842** <a href="https://app.graphite.com/github/pr/coder/coder/20842?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/coder/20842?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: agent/agent.go [hunk 1]
```diff
@@ -70,16 +71,21 @@ const (
...
+	ReconnectingPTYTimeout time.Duration
+	EnvironmentVariables   map[string]string
+	Logger                 slog.Logger
+	// IgnorePorts tells the api handler which ports to ignore when
+	// listing all listening ports. This is helpful to hide ports that
+	// are used by the agent, that the user does not care about.
+	IgnorePorts map[int]string
+	// ListeningPortsGetter is used to get the list of listening ports. Only
+	// tests should set this. If unset, a default that queries the OS will be used.
+	ListeningPortsGetter         ListeningPortsGetter
```
Comment (mafredri) [inline agent/agent.go:88]: Suggestion: These could be simplified a bit in naming by dropping "Getter". It makes these types somewhat verbose and limits future expansion of the type.

Hypothetical expansion: addition of ClearCache method.

A funny but legit alternative would be: `type ListeningPortser interface { ListeningPorts() ... }`.

**Review by mafredri — APPROVED** [review]
Solid change 👍🏻, some simplification suggestions inline.
