### PR TITLE
fix(coderd): mark sub agent deletion via boolean instead of delete

### LINKED ISSUE #685: Devcontainers: As a side-effect of deleting agents, it's possible for the stats collector to become sad
I did not investigate how this state was achieved, but it happened in my dev environment and it seems plausible that customer could trigger it as well.

```
[API] 2025-06-10 14:27:13.146 [erro]  coderd.workspaceapps.stats_collector: failed to flush workspace app stats ...
[API] error= report workspace app stats from backlog failed:
[API] github.com/coder/coder/v2/coderd/workspaceapps.(*StatsCollector).flush
[API] /home/coder/coder/coderd/workspaceapps/stats.go:263
[API] - insert workspace app stats failed:
[API] github.com/coder/coder/v2/coderd/workspacestats.(*Reporter).ReportAppStats
[API] /home/coder/coder/coderd/workspacestats/reporter.go:116
[API] - execute transaction:
[API] github.com/coder/coder/v2/coderd/database.(*sqlQuerier).runTx
[API] /home/coder/coder/coderd/database/db.go:213
[API] - pq: insert or update on table "workspace_app_stats" violates foreign key constraint "workspace_app_stats_agent_id_fkey"
```

Steps to reproduce (somewhat unknown but potentially some or all of these):

1. Run workspace with devcontainer and sub agents
2. Recreate devcontainer but fail to delete sub agent (inject/stop race)
3. Restart workspace
4. Recreate devcontainer
5. Potentially observe the above in coderd logs

### PR DESCRIPTION
**Pull request by mafredri**
Since deletion of data is uncommon in our database, the introduction of sub agents and their deletion introduced issues with foreign key assumptions in coder/internal#685. We could have only addressed the specific case by allowing cascade deletion of stats as well as handling in the stats collector, but it's unclear how many more such edge-cases we would've run into.

For this reason, we decided to mark the rows as deleted via boolean instead, and filter them out in all queries that seem relevant so that coderd doesn't see the deleted agents.

Testing is covered by updating the relevant `agentapi` tests as well as adding an antagonist deleted agent to `dbgen` which automatically gets applied to all tests.

Fixes coder/internal#685

Note that there are some queries that read `workspace_agents` that were not updated with deletion handling, but each one was analyzed and deemed unnecessary because of how they are used, doing so may introduce more harm than good. On that note, many of these queries can return results for non-latest builds which essentially means, "deleted" agents.

### CODE REVIEW

File: coderd/database/dbgen/dbgen.go [hunk 1]
```diff
@@ -226,6 +226,35 @@ func WorkspaceAgent(t testing.TB, db database.Store, orig database.WorkspaceAgen
 		})
 		require.NoError(t, err, "update workspace agent first connected at")
 	}
+
+	// Add a test antagonist. For every agent we add a deleted sub agent
+	// to discover cases where deletion should be handled.
+	subAgt, err := db.InsertWorkspaceAgent(genCtx, database.InsertWorkspaceAgentParams{
```
Comment (mafredri) [inline coderd/database/dbgen/dbgen.go]: Review: This may be a bit unusual, but it already helped me catch an issue with the `workspace_prebuilds` VIEW.

Ideally this potential cause would somehow be propagated to the user in case of test failure, but not sure how that could be done. I'll add a log entry to help with discovery.

Comment (johnstcn) [reply coderd/database/dbgen/dbgen.go]: I like this a lot! I do agree that it could get confusing to troubleshoot, but the log message in combination with `dbtestutil.DumpOnFailure` should help. You could also potentially set some relevant fields of the sub-agent so that its purpose is clear.

File: coderd/database/queries/workspaceagents.sql [hunk 2]
```diff
@@ -332,7 +348,20 @@ WHERE workspace_builds.id = $1
...
 -- name: DeleteWorkspaceSubAgentByID :exec
-DELETE FROM workspace_agents WHERE id = $1 AND parent_id IS NOT NULL;
+UPDATE
+	workspace_agents
+SET
+	deleted = TRUE
+WHERE
+	id = $1
+	AND parent_id IS NOT NULL
+	AND deleted = FALSE;
```
Comment (johnstcn) [inline coderd/database/queries/workspaceagents.sql:367]: 👍 literally impossible to delete a 'top-level' agent.

File: coderd/database/migrations/000338_use_deleted_boolean_for_subagents.up.sql
Comment (johnstcn) [inline coderd/database/migrations/000338_use_deleted_boolean_for_subagents.up.sql:1]: obligatory reminder to check migration number!

**Review by johnstcn — COMMENTED** [review]
I spot-checked the migrations and the updated views/triggers look OK to me.

Would like a second pair of eyes on this for approval in case there's something I missed.

File: coderd/database/dbgen/dbgen.go (hunk 1 above)
Comment (mafredri) [reply coderd/database/dbgen/dbgen.go]: How about this? 😆 [`bc370a8` (#18411)](https://github.com/coder/coder/pull/18411/commits/bc370a8f0a24395d5c7398775a753ba5f1421293)

Comment (johnstcn) [reply coderd/database/dbgen/dbgen.go]: SATISFACTORY

**Review by DanielleMaywood — APPROVED** [review]
LGTM but awaiting approval from someone on prebuilds

**Review by SasSwart — APPROVED** [review]
