### PR TITLE
fix: stop checking gauges unrelated to TestAgent_Stats_Magic

### LINKED ISSUE #564: flake: TestAgent_Stats_Magic
```
     agent_test.go:191: got stats: ok=true, ConnectionCount=0, RxBytes=0, TxBytes=0, SessionCountVSCode=1, ConnectionMedianLatencyMS=0.381000
    t.go:106: 2025-04-07 07:47:24.914 [debu]  client.net.wgengine: netcheck: [v1] netcheck: measuring HTTP(S) latency of test (1): unexpected status code: 426 (426 Upgrade Required)
    t.go:106: 2025-04-07 07:47:24.914 [debu]  client.net.wgengine: netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=false hair=true portmap= v4a=127.0.0.1:56495 derp=0
    agent_test.go:189: 
        	Error Trace:	/Users/runner/work/coder/coder/agent/agent_test.go:189
        	Error:      	Condition never satisfied
        	Test:       	TestAgent_Stats_Magic/TracksVSCode
        	Messages:   	never saw stats
```

https://github.com/coder/coder/actions/runs/14303616317/job/40082574718

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes https://github.com/coder/internal/issues/564

The test is asserting too much, including stats guages that are not directly related to the thing we are trying to test: ConnectionCount, RxBytes, and TxBytes.  I think the author assumed that these are counts that only go up, but they are guages and eventually zero back out, so there are race condtions where not all of them are non-zero at the same time.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#17290** <a href="https://app.graphite.dev/github/pr/coder/coder/17290?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/17290?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: agent/agent_test.go [hunk 1]
```diff
@@ -190,7 +190,7 @@ func TestAgent_Stats_Magic(t *testing.T) {
 			s, ok := <-stats
 			t.Logf("got stats: ok=%t, ConnectionCount=%d, RxBytes=%d, TxBytes=%d, SessionCountVSCode=%d, ConnectionMedianLatencyMS=%f",
```
Comment (johnstcn) [inline agent/agent_test.go:191]: We should probably also remove these fields (ConnectionCount, RxBytes, TxBytes) from the `t.Logf` as well as they're not relevant to this test. If we need to introspect in more detail, a debugger is probably a better option.

**Review by johnstcn — APPROVED** [review]

File: agent/agent_test.go (hunk 1 above)
Comment (spikecurtis) [reply agent/agent_test.go:191]: I disagree --- although we shouldn't be asserting their values, it can be useful to see them in logs so you can tell the difference between a test that misclassifies the VSCode session from one where we fail to connect at all, or fail to get any meaningful stats.

The debugger is great, but relatively useless for diagnosing rare-ish flakes.
