### PR TITLE
fix: fix race condition in pubsub startup

### LINKED ISSUE #525: Pubsub goroutine leak
Spotted on testing:

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 281873 in state chan send, with github.com/coder/coder/v2/coderd/database/pubsub.(*PGPubsub).startListener.func1 on top of the stack:
github.com/coder/coder/v2/coderd/database/pubsub.(*PGPubsub).startListener.func1(0xc0542f7700?, {0x0, 0x0})
	/home/runner/work/coder/coder/coderd/database/pubsub/pubsub.go:549 +0x3f0
github.com/lib/pq.(*Listener).emitEvent(...)
	/home/runner/go/pkg/mod/github.com/coder/pq@v1.10.5-0.20240813183442-0c420cb5a048/notify.go:825
github.com/lib/pq.(*Listener).listenerConnLoop(0xc0542f7700)
	/home/runner/go/pkg/mod/github.com/coder/pq@v1.10.5-0.20240813183442-0c420cb5a048/notify.go:855 +0xd0
github.com/lib/pq.(*Listener).listenerMain(...)
	/home/runner/go/pkg/mod/github.com/coder/pq@v1.10.5-0.20240813183442-0c420cb5a048/notify.go:884
created by github.com/lib/pq.listener in goroutine 274670
	/home/runner/go/pkg/mod/github.com/coder/pq@v1.10.5-0.20240813183442-0c420cb5a048/notify.go:553 +0x1a7
]
FAIL	github.com/coder/coder/v2/cli	75.434s
```

https://github.com/coder/coder/runs/39360818266

Appears to be a race condition around the errCh if the context is canceled quickly.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes https://github.com/coder/internal/issues/525

If the context is canceled, the goroutine that is supposed to read from the `errCh` could exit prematurely, leading to a goroutine leak. Refactors this code so it cannot block.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#17088** <a href="https://app.graphite.dev/github/pr/coder/coder/17088?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/17088?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: coderd/database/pubsub/pubsub.go [hunk 1]
```diff
@@ -541,18 +544,16 @@ func (p *PGPubsub) startListener(ctx context.Context, connectURL string) error {
...
-			case <-errCh:
+			// Only send the first error.
+			if sentErrCh {
 				return
-			default:
-				errCh <- err
-				close(errCh)
 			}
+			errCh <- err // won't block because we are buffered.
+			sentErrCh = true
```
Comment (mafredri) [inline coderd/database/pubsub/pubsub.go:552]: Do we need to protect this or is sequential execution guaranteed?

**Review by mafredri — APPROVED** [review]
Except for the one question/concern, LGTM 👍🏻

File: coderd/database/pubsub/pubsub.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/database/pubsub/pubsub.go:552]: It executes sequentially, at least by inspection. There is always a chance they could change the implementation and call-back concurrently, but it didn't seem worth while defending for that.

**Comment by spikecurtis** [comment]
### Merge activity

* **Mar 25, 8:45 AM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/17088).
