### PR TITLE
fix: use unique workspace owners over unique users

### LINKED ISSUE #10820: Used by in templates list is innacurate
From dev.coder.com

https://github.com/coder/coder/assets/22407953/3da7993b-8561-41cd-92fd-cebc47f60d08

https://github.com/coder/coder/assets/22407953/3ee06059-4eb9-4727-9b58-790ff44939f5

### PR DESCRIPTION
**Pull request by f0ssel**
Closes https://github.com/coder/coder/issues/10820

Currently the `active_user_count` on each template is not really "active users" but the count of any user that has made a workspace that was healthy based on the template. 

This changes it to use the count of unique workspace owners based off the template, which I believe is what users will expect the number to be based on the issue made for this.

### CODE REVIEW

File: coderd/templates.go [hunk 1]
```diff
@@ -831,7 +831,13 @@ func (api *API) convertTemplate(
 	template database.Template,
 ) codersdk.Template {
 	templateAccessControl := (*(api.Options.AccessControlStore.Load())).GetTemplateAccessControl(template)
-	activeCount, _ := api.metricsCache.TemplateUniqueUsers(template.ID)
+	daus := 0
+	_, resp, ok := api.metricsCache.TemplateDAUs(template.ID, 0)
+	if ok {
+		// this is safe because we currently only support one timezone offset: 0
+		// see metricscache.templateTimezoneOffsets
+		daus = resp.Entries[0].Amount
```
Comment (kylecarbs) [inline coderd/templates.go:839]: Is there 100% of the time an entry here? This would panic if not.

File: coderd/database/queries/workspaces.sql [hunk 2]
```diff
@@ -287,6 +287,12 @@ WHERE
 	AND LOWER("name") = LOWER(@name)
 ORDER BY created_at DESC;
 
+-- name: GetWorkspaceUniqueOwnerCountByTemplateIDs :many
+SELECT template_id, COUNT(DISTINCT owner_id) AS unique_owners_sum
+FROM workspaces
+WHERE template_id = ANY(@template_ids :: uuid[]) AND deleted = false
+GROUP BY template_id;
+
```
Comment (Emyrk) [inline coderd/database/queries/workspaces.sql:295]: Not that it really matters, but most of our sqlc is formatted like:
```sql
-- name: GetWorkspaceUniqueOwnerCountByTemplateIDs :many
SELECT 
	template_id, COUNT(DISTINCT owner_id) AS unique_owners_sum
FROM 
	workspaces
WHERE 
	template_id = ANY(@template_ids :: uuid[]) AND deleted = false
GROUP BY template_id;
```

Comment (Emyrk) [reply coderd/database/queries/workspaces.sql:295]: I'm guessing we do not care the state of the workspace besides deleted? Like stopped vs failed etc?

File: coderd/metricscache/metricscache.go [hunk 3]
```diff
@@ -214,7 +216,9 @@ func (c *Cache) refreshTemplateDAUs(ctx context.Context) error {
 		return xerrors.Errorf("deployment daus: %w", err)
 	}
 
-	for _, template := range templates {
+	ids := make([]uuid.UUID, len(templates))
+	for i, template := range templates {
+		ids[i] = template.ID
```
Comment (Emyrk) [inline coderd/metricscache/metricscache.go:221]: We've been doing this to prevent slices from having nils/empty values. You still get the benefit of pre-allocating. 
```suggestion
	ids := make([]uuid.UUID, 0, len(templates))
	for _, template := range templates {
		ids = append(ids, template.ID)
```

**Review by Emyrk — APPROVED** [review]
:+1: The original value is still there too if you want to pull the total ever. Reading the issue ticket, this all makes sense.

File: coderd/metricscache/metricscache.go (hunk 3 above)
Comment (f0ssel) [reply coderd/metricscache/metricscache.go:221]: ah a good cap v len in the wild, great catch

**Comment by f0ssel** [comment]
Yeah I have a feeling people will want to know the total unique users that have ever used the template _somewhere_ in the UI so I wanted to leave it for now.
