### PR TITLE
fix: add checks for preventing HSL colors from entering React state

### LINKED ISSUE #9888: Can't set service banner background color – background color sometimes changes from hex to HSL format
It is not possible to set the color now as submitted value has incorrect format:

Screenshot 2023-09-27 at 15 17 23

It would be nice to cover it with tests.

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #9888 

## Changes
- Updates the default state for `AppearanceSettingsView` to prevent HSL colors from accidentally entering the component
- Adds some extra runtime checks when performing state transitions that validate color formatting and prevent HSL values from ever being able to enter the `DashboardProvider`'s state
- Adds tests for new functionality

### CODE REVIEW

File: site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx [hunk 1]
```diff
@@ -30,13 +31,17 @@ export type AppearanceSettingsPageViewProps = {
     preview: boolean,
   ) => void;
 };
+
+const fallbackBgColor = hslToHex(colors.blue[7]);
```
Comment (mtojek) [inline site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx:35]: KISS-related question: why do we need other changes in the PR? Did you identify any places where we can face HSL related issue?

**Review by mtojek — COMMENTED** [review]
I didn't expect this to be a relatively large change, so let me challenge it.

File: site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx (hunk 1 above)
Comment (Parkreiner) [reply site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx:35]: Yeah, KISS is definitely something I need to keep in mind more, but at least here, I feel like the defensive changes made sense.

The way I see it, there's three risks right now:
- `DashboardProvider` is already being a general-purpose component that can be imported by anything else
- The component is already being globally available to some degree because it's directly integrated into the `RequireAuth` component
- So many constants in the codebase are set up as HSL strings for readability. We could get rid of these in favor of hex strings, but they're a lot less intuitive to work with

I felt like having the provider be in charge of validating incoming string changes would be the best way to prevent any further mismatches from popping up

Comment (mtojek) [reply site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx:35]: Thanks for the explanation! Sounds good to me 👍

**Review by mtojek — APPROVED** [review]
