### PR TITLE
fix: handle new agent stat format correctly

### LINKED ISSUE #14348: `coderd_agentstats_session_count_*` are not being populated
Screenshot 2024-08-19 at 9 43 47 AM

using dev.coder.com and grafana.dev.coder.com. I did not check if there are other agent metrics that are not being populated

### PR DESCRIPTION
**Pull request by f0ssel**
Closes #14348

### CODE REVIEW

File: coderd/database/queries/workspaceagentstats.sql [hunk 1]
```diff
@@ -246,27 +246,17 @@ minute_buckets AS (
...
-		session_count_reconnecting_pty,
-		session_count_ssh
+		session_count_reconnecting_pty
 	FROM
 		minute_buckets
 	ORDER BY
 		agent_id,
 		minute_bucket DESC
-), latest_agent_stats AS (
-	SELECT
```
Comment (ethanndickson) [inline coderd/database/queries/workspaceagentstats.sql]: This subquery wasn't doing anything, since we've already selected distinct on `agent_id`

File: coderd/database/queries/workspaceagentstats.sql [hunk 2]
```diff
@@ -330,7 +330,9 @@ WITH agent_stats AS (
 		coalesce(SUM(session_count_reconnecting_pty), 0)::bigint AS session_count_reconnecting_pty,
 		coalesce(SUM(connection_count), 0)::bigint AS connection_count
 	FROM workspace_agent_stats
-	WHERE usage = true
+	-- We only want the latest stats, but those stats might be
+	-- spread across multiple rows.
+	WHERE usage = true AND created_at > now() - '1 minute'::interval
```
Comment (ethanndickson) [inline coderd/database/queries/workspaceagentstats.sql:335]: This query, `GetWorkspaceAgentUsageStatsAndLabels` is called with the time the server last started, in `prometheusmetrics.go` (`initialCreateAfter) - but with the experiment enabled, stats from clients are reported at most every minute.

File: coderd/database/queries/workspaceagentstats.sql [hunk 3]
```diff
@@ -341,11 +343,15 @@ WITH agent_stats AS (
...
+	coalesce(session_count_vscode, 0)::bigint AS session_count_vscode,
+	coalesce(session_count_ssh, 0)::bigint AS session_count_ssh,
+	coalesce(session_count_jetbrains, 0)::bigint AS session_count_jetbrains,
+	coalesce(session_count_reconnecting_pty, 0)::bigint AS session_count_reconnecting_pty,
+	coalesce(connection_count, 0)::bigint AS connection_count,
+	connection_median_latency_ms
 FROM
 	agent_stats
-JOIN
+LEFT JOIN
```
Comment (ethanndickson) [inline coderd/database/queries/workspaceagentstats.sql:354]: It's possible for the subquery (`latest_agent_stats`) that selects the rows with session counts from the last minute to be empty, if there are no sessions. This needs to be a left join if we want to update the prometheus metrics (such as going from n sessions to 0), or the rx/tx bytes.

File: coderd/telemetry/telemetry.go [hunk 4]
```diff
@@ -473,13 +474,24 @@ func (r *remoteReporter) createSnapshot() (*Snapshot, error) {
...
 	})
 	eg.Go(func() error {
-		stats, err := r.options.Database.GetWorkspaceAgentStats(ctx, createdAfter)
-		if err != nil {
-			return xerrors.Errorf("get workspace agent stats: %w", err)
-		}
-		snapshot.WorkspaceAgentStats = make([]WorkspaceAgentStat, 0, len(stats))
-		for _, stat := range stats {
-			snapshot.WorkspaceAgentStats = append(snapshot.WorkspaceAgentStats, ConvertWorkspaceAgentStat(stat))
+		if r.options.DeploymentConfig != nil && slices.Contains(r.options.DeploymentConfig.Experiments, string(codersdk.ExperimentWorkspaceUsage)) {
```
Comment (ethanndickson) [inline coderd/telemetry/telemetry.go:477]: Like a few other things in this fix, it's a bit hacky, but this is fine if we clean it out when the experiment is over.

**Review by f0ssel — COMMENTED** [review]
Looks good so far, would like us to ensure summing and filtering is checked a little deeper, but that shouldn't be too bad since the hard part of getting the mocks accurate is done. Have you tried running it in dev with the experiment on? You can try to repro the screenshot in the issue and see if you can data back.

File: coderd/metricscache/metricscache_test.go [hunk 5]
```diff
@@ -150,7 +150,7 @@ func TestCache_BuildTime(t *testing.T) {
 					},
 				},
 				transition: database.WorkspaceTransitionStop,
-			}, want{50 * 1000, true},
```
Comment (f0ssel) [inline coderd/metricscache/metricscache_test.go:153]: What makes this change needed?

**Review by f0ssel — COMMENTED** [review]
Looks great, thanks for double checking on a dev instance as well. I can't approve since it's "my" pr, but feel free to approve yourself and merge when ready.

File: coderd/metricscache/metricscache_test.go (hunk 5 above)
Comment (ethanndickson) [reply coderd/metricscache/metricscache_test.go:153]: The old `dbmem` `tryPercentile` function was implemented slightly differently to how postgres implements `PERCENTILE_CONT` (although this test never gets run with postgres anyway)

**Review by ethanndickson — APPROVED** [review]
