### PR TITLE
fix(agent): check agent metadata every second instead of minute

### LINKED ISSUE #8577: Some metadata disappears from the UI for a long time, repeatedly
I don't know what's the cause, but using the Coder on Coder template on dev.coder.com, I'm seeing metadata appears for a short while, only to disappear again. This happens repeatedly.

Meanwhile, the VSCode extension is showing the values correctly.

Video:

https://github.com/coder/coder/assets/147409/a5eba872-9822-4883-bc2b-84aca59d89e7

Metadata appear at 0:58 and 3:58, so it seems to be on some interval. There might've been a redeploy/reconnect of dev.coder.com too somewhere around the 3-minute mark.

### PR DESCRIPTION
**Pull request by coadler**
I believe this is the fix for https://github.com/coder/coder/issues/8577.

When looking at the websocket, metadata keys go over 2 minutes without updating, even when their interval is much lower. This fixes `reportMetadataLoop` to run every second and properly calculate the interval. A previous refactor set it to tick each minute instead of the previous behavior of each second.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -328,16 +328,45 @@ func (a *agent) reportMetadataLoop(ctx context.Context) {
...
+			default:
+				return
+			}
+		}
+	}
+
 	for {
+		// Ensure all backpressured metadata is posted.
+		if len(metadataResults) > 1 {
+			flushAllMetadata()
```
Comment (mafredri) [inline agent/agent.go:361]: This could perhaps be moved to after the `select` below (i.e. when `baseTicker.C` is triggered). For now it seems to be doing the exact same thing as the select, except when `baseTicker.C` is triggered. (We probably don't need the `len` check either.)

**Review by mafredri — APPROVED** [review]

File: agent/agent.go (hunk 1 above)
Comment (coadler) [reply agent/agent.go]: it doesn't really seem to be necessary, so i've just removed it for now
