### PR TITLE
fix(coderd/healthcheck): ignore deleted wsproxies in wsproxy healthcheck

### LINKED ISSUE #11440: coderd: do not show deleted wsproxies
@johnstcn maybe we should update the backend to only return WS Proxies that are not deleted?

_Originally posted by @BrunoQuaresma in https://github.com/coder/coder/issues/11417#issuecomment-1878600288_

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/11440

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
👍

File: coderd/healthcheck/workspaceproxy.go [hunk 1]
```diff
@@ -76,7 +76,12 @@ func (r *WorkspaceProxyReport) Run(ctx context.Context, opts *WorkspaceProxyRepo
 		return
 	}
 
-	r.WorkspaceProxies = proxies
+	for _, proxy := range proxies.Regions {
+		if proxy.Deleted {
+			continue
+		}
+		r.WorkspaceProxies.Regions = append(r.WorkspaceProxies.Regions, proxy)
```
Comment (johnstcn) [inline coderd/healthcheck/workspaceproxy.go:83]:
```suggestion
		if !proxy.Deleted {
			r.WorkspaceProxies.Regions = append(r.WorkspaceProxies.Regions, proxy)
		}
```
