### PR TITLE
config-ssh: always support agent name in host alias

### LINKED ISSUE #2969: Workspace SSH access button tooltip provides invalid command
Clicking the new "SSH" access button on a workspace in the Coder website shows a tooltip that reads:

> Run the following commands to connect with SSH:
> 
> Configure ssh - only needs to be run once, or after managing workspaces
> 
> `coder config-ssh`
>
> Connect to the agent
>
> `ssh coder.<WORKSPACE_NAME>.dev`

## Expected Behavior

Running `coder config-ssh` and then `ssh coder.<WORKSPACE_NAME>.dev` in a terminal connects you over SSH to the workspace.

## Current Behavior

Running `coder config-ssh` and then `ssh coder.<WORKSPACE_NAME>.dev` in a terminal shows the following error:

```
ssh: Could not resolve hostname coder.<WORKSPACE_NAME>.dev: nodename nor servname provided, or not known
```

However `ssh coder.<WORKSPACE_NAME>` works (without `.dev`). I understand `dev` is the name we gave to the `coder_agent` resource in our workspace template file.

### PR DESCRIPTION
**Pull request by dwahler**
This PR adjusts the behavior of `coder config-ssh` so that it *always* creates aliases of the form `coder.<WORKSPACE_NAME>.<AGENT_NAME>`, and additionally creates an alias of the form `coder.<WORKSPACE_NAME>` if the workspace has exactly one agent. This is more consistent with the behavior of `coder ssh`, and prevents us from incorrectly rejecting commands that are suggested by UI tooltips.

I believe the original logic was subtly incorrect, because it only considered how many agents existed in each workspace resource, not the total number of agents in the workspace. So if a workspace had two resources with one agent each, it would have generated multiple invalid `coder.<WORKSPACE_NAME>` aliases, instead of the correct aliases with the agent name.

Fixes #2969

### CODE REVIEW

File: cli/configssh.go [hunk 1]
```diff
@@ -89,18 +89,23 @@ func sshFetchWorkspaceConfigs(ctx context.Context, client *codersdk.Client) ([]s
...
-						hostname += "." + agent.Name
-					}
-					wc.Hosts = append(wc.Hosts, hostname)
-				}
+				agents = append(agents, resource.Agents...)
+			}
+
+			// handle both WORKSPACE and WORKSPACE.AGENT syntax
+			if len(agents) == 1 {
+				wc.Hosts = append(wc.Hosts, workspace.Name)
```
Comment (deansheather) [inline cli/configssh.go:102]: We should probably invent "default agent" as a flag in the coder_agent resource or something otherwise this may become annoying, could be a good follow up

**Review by deansheather — APPROVED** [review]

File: cli/configssh.go (hunk 1 above)
Comment (mafredri) [reply cli/configssh.go:102]: This sounds like a great idea! I'm guessing we'd have to update the TF provider, update all TF templates (to set default) and ensure that only one resource has the default agent set?

(Might be a bad idea, but we could consider the first one the default, as a fallback.)

File: cli/configssh_test.go [hunk 2]
```diff
@@ -692,3 +694,152 @@ func TestConfigSSH_FileWriteAndOptionsFlow(t *testing.T) {
...
+
+		tokenScanner := bufio.NewScanner(bytes.NewBufferString(line))
+		tokenScanner.Split(bufio.ScanWords)
+		ok := tokenScanner.Scan()
+		if ok && tokenScanner.Text() == "Host" {
+			for tokenScanner.Scan() {
+				result = append(result, tokenScanner.Text())
+			}
+		}
+	}
```
Comment (mafredri) [inline cli/configssh_test.go:842]: Minor (non-blocking): We could consider checking `lineScanner.Err()` after the loop (similarly with `tokenScanner`). I realize it's quite inconsequential for how this function is used, it's more of a best practice.

**Review by mafredri — APPROVED** [review]
Nice solution and tests!

**Comment by kylecarbs** [comment]
@dwahler is this good to merge? We should probably get this out in a patch release.
