### PR TITLE
fix: add link to troubleshooting

### LINKED ISSUE #14933: Docker template doesn't render a troubleshooting link when agent doesn't connect
I'm not sure if this is because we don't render it in the UI or if there isn't a default for our provider, but we should link to our docs here as the default: https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#troubleshooting_url

Screenshot 2024-10-02 at 8 12 14 AM

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/14933

This PR extends the _Unhealthy_ workspace notification with the troubleshooting link (if defined).

Screenshot 2025-02-17 at 13 21 34

### CODE REVIEW

File: site/src/pages/WorkspacePage/WorkspaceNotifications/WorkspaceNotifications.tsx [hunk 1]
```diff
@@ -254,3 +273,18 @@ const styles = {
...
 } satisfies Record<string, Interpolation<Theme>>;
+
+const findTroubleshootingURL = (
+	workspaceBuild: WorkspaceBuild,
+): string | undefined => {
+	for (const resource of workspaceBuild.resources) {
+		if (resource.agents) {
+			for (const agent of resource.agents) {
+				if (agent.troubleshooting_url) {
+					return agent.troubleshooting_url;
```
Comment (johnstcn) [inline site/src/pages/WorkspacePage/WorkspaceNotifications/WorkspaceNotifications.tsx:284]: non-blocking: I can imagine a situation where a multi-agent workspace has a different troubleshooting URL for each agent. We might need some design changes to show multiple troubleshooting URLs though.

**Review by johnstcn — APPROVED** [review]
Proabably no harm to get a quick FE review, but LGTM

File: site/src/pages/WorkspacePage/WorkspaceNotifications/WorkspaceNotifications.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/pages/WorkspacePage/WorkspaceNotifications/WorkspaceNotifications.tsx:284]: I thought about this case! I concluded that having different Troubleshooting guides for various agents is an edge case.
