### PR TITLE
fix(site): show available logs consistently on template creation page

### LINKED ISSUE #19704: bug: Web UI does not surface errors in template creation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When an error occurs when a template is created, the information is not surfaced through the Web UI and can only be accessed by using the Coder CLI. 

Image

Instead, the process hangs indefinitely, which gives the impression that the issue is around provisioner availability and encourages users to wait around instead of debugging the issue by other means. 

Image

Quick fix: On documentation (ex. in the quickstart) guide users towards using the Coder CLI to debug issues. 

Engineering fix: Output errors to the Web UI, potentialy in the form of a terminal window. 

### Relevant Log Output

```shell

```

### Expected Behavior

Web UI should detect that an error has occurred and surface appropriate log output to aid debugging. 

### Steps to Reproduce

1. Create a Coder Docker template (i.e. follow the [quickstart](https://coder.com/docs/tutorials/quickstart)) 
2. Ensure that Docker is not open, which will throw an error
3. Click `Save` - this will redirect you to the page where the process hangs indefinitely. 

### Environment

- Host OS:
- Coder version:

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aslilac**
Closes https://github.com/coder/coder/issues/19704

The condition on this page was subtly wrong in a very annoying way. :^)

### CODE REVIEW

File: site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx [hunk 1]
```diff
@@ -40,12 +40,12 @@ export const BuildLogsDrawer: FC<BuildLogsDrawerProps> = ({
...
 
 	// biome-ignore lint/correctness/useExhaustiveDependencies: consider refactoring
-	useLayoutEffect(() => {
+	useEffect(() => {
 		scrollToBottom();
 	}, [logs]);
 
 	// biome-ignore lint/correctness/useExhaustiveDependencies: consider refactoring
-	useLayoutEffect(() => {
+	useEffect(() => {
```
Comment (buenos-nachos) [inline site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx]: I'm not sure why we're degrading the effect priority to fire after paint, especially when scrolling the UI down  _is_ a layout concern

But beyond that, the current code is still janky because:
1. We're not properly cleaning up timeouts on unmount
2. The effect logic isn't resolving the reactivity properly

If we're keeping the timeout "hacks", this should do the trick, though:
```tsx
const timeoutIdRef = useRef<ReturnType<typeof setTimeout> | undefined>(
	undefined,
);
useEffect(() => {
	return () => {
		clearTimeout(timeoutIdRef.current);
	}
}, []);

const scrollToBottom = useEffectEvent(() => {
	clearTimeout(timeoutIdRef.current);
	timeoutIdRef.current = setTimeout(() => {
		if (logsContainer.current) {
			logsContainer.current.scrollTop = logsContainer.current.scrollHeight;
		}
	}, 0);
});

const logLength = logs?.length ?? 0;
useLayoutEffect(() => {
	if (drawerProps.open || logLength > 0) {
		scrollToBottom();
	}
}, [scrollToBottom, drawerProps.open, logLength]);
```

And then `onFillVariables` would become:
```tsx
onFillVariables={() => {
	variablesSectionRef.current?.scrollIntoView({
		behavior: "smooth",
	});
	const firstVariableInput =
		variablesSectionRef.current?.querySelector("input");
	
	clearTimeout(timeoutIdRef.current);
	timeoutIdRef.current = setTimeout(() => {
		firstVariableInput?.focus();
	}, 0);
	drawerProps.onClose();
}}
```
The two timeouts deal with slightly different concerns, but it should be safe to lump them together into a single state variable

Comment (buenos-nachos) [reply site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx]: But also, do we know what this code is doing? My guess is that the timeouts are being used as a hack to ensure that the logic only fires once React finishes painting to the screen, but normal useEffect calls do that autmatically. I don't know if we need timeouts at all

File: site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx [hunk 2]
```diff
@@ -70,9 +71,7 @@ export const BuildLogsDrawer: FC<BuildLogsDrawerProps> = ({
 					</IconButton>
 				</header>
 
-				{}
```
Comment (buenos-nachos) [inline site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx:73]: Surprised a linter didn't catch this

**Review by buenos-nachos — COMMENTED** [review]
Conditional logic looks right to me, but the effects have me concerned

File: site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx (hunk 1 above)
Comment (aslilac) [reply site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx]: I had convinced myself yesterday that it wasn't a layout effect, but looking into it, it seems like the consensus is that it is. I don't think the timeout is necessary tho, and is just some weird hack to have a useLayoutEffect but not blocking, but the whole point of useLayoutEffect is that it is blocking?

**Comment by aslilac** [comment]
after staring at this for a while, I realized that the effects were weird because they're just in the wrong place. 😅 aaand that every place that uses this component re-implements the autoscrolling behavior itself. it should really just scroll itself, and that makes a bunch of complexity vanish.

File: site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx (hunk 1 above)
Comment (buenos-nachos) [reply site/src/pages/CreateTemplatePage/BuildLogsDrawer.tsx]: Yeah, the whole point of a layout effect is that it fires after the render finishes and the DOM nodes have been created, but before paint. So you get a window of time to sync some state and redo some renders based off what's in the DOM, and then finally flush everything to the screen at once, instead of having it happen in multiple passes (which usually causes screen flickering)

File: site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx [hunk 3]
```diff
@@ -50,38 +56,21 @@ export const WorkspaceBuildLogs: FC<WorkspaceBuildLogsProps> = ({
...
-		}
-
-		return allLogs;
-	}, [logs, build?.job?.logs_overflowed]);
-
 	const groupedLogsByStage = groupLogsByStage(logs);
 
+	const ref = useRef<HTMLDivElement>(null);
+	useLayoutEffect(() => {
+		logs;
```
Comment (buenos-nachos) [inline site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx]: This feels janky to me. I think I'd rather have the Biome warning suppression, because it feels more "honest" about this not being a properly-defined synchronization effect

I think there's a "deeper" fix we can reach for to remove the effect entirely. I just don't know if it makes to do it now. For `BuildLogsDrawer` at least, we could:
1. Update the logs component to accept a forwarded ref, and get rid of the old ref + layout logic
2. Define the ref in `BuildLogsDrawer`
3.  Update `useWatchVersionLogs` to accept an `onMessage` callback that fires each time a new message comes in
4. Have `BuildLogsDrawer` pass the ref down to the logs component, and also pass an `onMessage` callback to the hook that handles the scrolling behavior

Comment (buenos-nachos) [reply site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx]: The big problem right now is that ideally these scrolls would be handled in an event handler, but the state isn't defined in a way that gives you a state setter function that's easy to wrap

Plus, there's five components currently using this

**Review by buenos-nachos — APPROVED** [review]
I think this makes sense for a stopgap. I'm just not a fan of the random `logs` expression used to suppress the Biome warnings

File: site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx (hunk 3 above)
Comment (aslilac) [reply site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx]: one day we'll get signals...

Comment (buenos-nachos) [reply site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx]: I mean, the problem with the React team is that they legitimately think that they don't need signals, and that the compiler is going to solve all of React's problems (which it probably won't). They've turned down a few signal proposals already

Comment (aslilac) [reply site/src/modules/workspaces/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx]: it'll take a while, but I'm pretty sure the web platform will get signals soon, and then the react team will be forced to reckon with them.

also preact even jumped the gun and added signals. angular has signals now. the tide is turning!
