### PR TITLE
fix: Avoid panic in `ServerSentEventSender` by keeping handler alive

### LINKED ISSUE #4807: Unexpected restarts of the coder pod
Hello, I see sporadically this error on a GKE cluster:

(coder 0.11.0, GKE 1.24.6)

```
2022-10-31 07:34:58.861 [INFO]	(coderd.tailnet)	<./tailnet/conn.go:200>	NewConn.func3	wireguard status	{"status": "\u0026{AsOf:2022-10-31 07:34:58.861635364 +0000 UTC m=+1406.588420654 Peers:[{TxBytes:802036 RxBytes:5117168 LastHandshake:2022-10-31 07:33:55.787139294 +0000 UTC NodeKey:nodekey:cd32e74502524f98a828bf4adb7d4d23b0dd8ad0f0ce25006bf49c01f3e89123}] LocalAddrs:[{Addr:xxx.xxx.xxx.xxx:58148 Type:stun} {Addr:10.108.2.51:58148 Type:local}] DERPs:1}", "err": null}
2022-10-31 07:34:58.861 [INFO]	(coderd.tailnet)	<./tailnet/conn.go:456>	(*Conn).sendNode.func1	sending node	{"node": {"id": 5166511059428960592, "as_of": "2022-10-31T07:34:58.861635364Z", "key": "nodekey:33a3060e0d5648c2e31468634fc7811d4abb089049905814aac0eabd4f6d0c40", "disco": "discokey:282dfd24191766d8cc5d93b40231dced685b3227020aed41b18f57cc2eeaaf0e", "preferred_derp": 999, "derp_latency": {"999-v4": 0.008294595}, "addresses": ["fd7a:115c:a1e0:4970:805a:f00a:6f25:63b/128"], "allowed_ips": ["fd7a:115c:a1e0:4970:805a:f00a:6f25:63b/128"], "endpoints": ["xxx.xxx.xxx.xxx:58148", "xxx.xxx.xxx.xxx:58148"]}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x683178]

goroutine 107607 [running]:
bufio.(*Writer).Flush(0x800?)
	/opt/hostedtoolcache/go/1.19.2/x64/src/bufio/bufio.go:623 +0x18
net/http.(*chunkWriter).flush(0xc0150dc840?)
	/opt/hostedtoolcache/go/1.19.2/x64/src/net/http/server.go:402 +0x3f
net/http.(*response).Flush(0xc01bbaa000)
	/opt/hostedtoolcache/go/1.19.2/x64/src/net/http/server.go:1707 +0x48
github.com/coder/coder/coderd/tracing.(*StatusWriter).Flush(0x7f1929df9e78?)
	/home/runner/work/coder/coder/coderd/tracing/status_writer.go:81 +0x35
github.com/coder/coder/coderd/httpapi.ServerSentEventSender.func1()
	/home/runner/work/coder/coder/coderd/httpapi/httpapi.go:206 +0x202
created by github.com/coder/coder/coderd/httpapi.ServerSentEventSender
	/home/runner/work/coder/coder/coderd/httpapi/httpapi.go:191 +0x37d
```

### PR DESCRIPTION
**Pull request by mafredri**
The goroutine launched by `ServerSentEventSender` can perform a write
and flush after the calling http handler has exited, at this point the
resources (e.g. `http.ResponseWriter`) are no longer safe to use.

To work around this issue, heartbeats and sending events are now handled
by the goroutine which signals its closure via a channel. This allows
the calling handler to ensure it is kept alive until it's safe to exit.

Fixes #4807

**NOTE:** This was a relatively quick fix, we may want to consider
rewriting the sender as a service to clean up the implementation.

### CODE REVIEW

File: coderd/httpapi/httpapi.go [hunk 1]
```diff
@@ -187,37 +185,50 @@ func ServerSentEventSender(rw http.ResponseWriter, r *http.Request) (func(ctx co
...
+		// Send a heartbeat every 15 seconds to avoid the connection being killed.
 		ticker := time.NewTicker(time.Second * 15)
 		defer ticker.Stop()
 
 		for {
+			var event sseEvent
+
 			select {
 			case <-r.Context().Done():
 				return
```
Comment (deansheather) [inline coderd/httpapi/httpapi.go:208]: Why doesn't this prevent the write/flush after finish? We're not hijacking the connection so the context should still be cancelled on finish right?

File: coderd/httpapi/httpapi.go [hunk 2]
```diff
@@ -174,8 +173,7 @@ func WebsocketCloseSprintf(format string, vars ...any) string {
 	return msg
 }
 
-func ServerSentEventSender(rw http.ResponseWriter, r *http.Request) (func(ctx context.Context, sse codersdk.ServerSentEvent) error, error) {
-	var mu sync.Mutex
+func ServerSentEventSender(rw http.ResponseWriter, r *http.Request) (sendEvent func(ctx context.Context, sse codersdk.ServerSentEvent) error, closed chan struct{}, err error) {
```
Comment (deansheather) [inline coderd/httpapi/httpapi.go:176]: It seems like we can eliminate the error return from this as it's never set to a non-nil value

File: coderd/httpapi/httpapi.go [hunk 3]
```diff
@@ -232,16 +243,22 @@ func ServerSentEventSender(rw http.ResponseWriter, r *http.Request) (func(ctx co
...
 
-		mu.Lock()
-		defer mu.Unlock()
-		_, err = rw.Write(buf.Bytes())
-		if err != nil {
-			return err
+		event := sseEvent{
+			payload: buf.Bytes(),
+			errC:    make(chan error, 1),
 		}
```
Comment (deansheather) [inline coderd/httpapi/httpapi.go:249]: Did you have to move the writing to the goroutine to fix the bug or is this just a separate change you did? The old flow was simpler to understand as it didn't involve extra write channels and response channels, but if it helps to fix the bug then 👍

File: coderd/httpapi/httpapi.go (hunk 1 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:208]: Because this code had the following race condition:

1. Say `watchWorkspace` encountered an error and exited (this begins the process of all handlers and middleware exiting (`r.Context()` is not yet cancelled)
2. Timer is triggered
3. We write to `rw` which still succeeds as the teardown is still happening
4. Teardown finishes, context is cancelled, but we're currently not listening to this signal
5. We hit `Flush` after teardown so we get a nil pointer deref

File: coderd/httpapi/httpapi.go (hunk 3 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:249]: It's not mandator per-se, but I think we'd want do it if we service-ified this implementation anyway. That said, asynchronous code will always introduce complexity somewhere, this change moves the core logic into one place which IMO simplifies it. It's easier to reason about where and in what order mutations/writes are happening.

This change also has the benefit of allowing us to listen to both `r.Context()` and `ctx` completion which we didn't before, which is more true to the given API (function signature).

File: coderd/httpapi/httpapi.go (hunk 2 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:176]: Not really relevant for this PR, but that's a good point. I'd like to see it kept and remove the panic in favor of an error, though.

File: coderd/httpapi/httpapi.go (hunk 3 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:249]: Oh yeah, forgot to mention that this logic change also stops writes after an error is encountered, allowing the caller (if errors are checked) to stop using the sender. 

Previously we exited the goroutine on write error, meaning keepalives were no longer sent, so it makes sense to disable writes at this point.

File: coderd/httpapi/httpapi.go [hunk 4]
```diff
@@ -232,16 +243,22 @@ func ServerSentEventSender(rw http.ResponseWriter, r *http.Request) (func(ctx co
...
-		return nil
+		select {
+		case <-r.Context().Done():
+			return r.Context().Err()
+		case <-ctx.Done():
+			return ctx.Err()
+		case eventC <- event:
+			return <-event.errC
+		case <-closed:
+			return xerrors.New("server sent event sender closed")
```
Comment (deansheather) [inline coderd/httpapi/httpapi.go:259]: Should be before the write to the events channel

File: coderd/httpapi/httpapi.go (hunk 3 above)
Comment (deansheather) [reply coderd/httpapi/httpapi.go:249]: The asynchronous logic introduces channel reads which can result in the goroutine hanging waiting for data indefinitely. For example, if you wrote an event to the events channel and the sender goroutine got closed before reading that event, you would be permanently stuck waiting for a response from the response channel as far as I can tell.

I think this logic should be kept the way it was to avoid the complexities and extra bugs introduced by having it be asynchronous.

Comment (deansheather) [reply coderd/httpapi/httpapi.go:249]: wait nevermind I forgot it's an unbuffered channel

Comment (mafredri) [reply coderd/httpapi/httpapi.go:249]: I don't see why that's a problem? The previous implementation was already asynchronous and required mutex locking and taking care not to use the resources after close. Here I've fixed those issues and ensured there are no hangs by listening on e.g. `<-closed` which is closed when there no longer is a listener for events. If you're considering a future developer making changes, I'd venture those changes would be "dangerous" in the previous implementation as well?

A motivation to keep this change is that AFAIK we'll be using SSEs more in the future, and we'll want to send different types of events on a single channel (due to browser limitations). At this point we'll need a service (`sendEvent` called from multiple places) and at that point the previous implementation of `sendEvent` becomes unsafe (same bug we're fixing here).

File: coderd/httpapi/httpapi.go (hunk 4 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:259]: Why? Order doesn't matter for `select`.

Comment (deansheather) [reply coderd/httpapi/httpapi.go:259]: Yeah I wrote this comment before I remembered it's an unbuffered channel so it's not relevant

File: coderd/httpapi/httpapi.go (hunk 3 above)
Comment (deansheather) [reply coderd/httpapi/httpapi.go:249]: If we're rewriting this soon like you say then I think this is fine. I still feel like a safe implementation can be achieved in a less complicated way and that we should investigate it in the future, but I won't block your PR for it since this is to fix a panic

**Review by deansheather — APPROVED** [review]

File: coderd/httpapi/httpapi.go (hunk 4 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:259]: Ah, gotcha. Btw, to go runtime intentionally randomizes which channel is picked, so even in the event of a buffered channel, the order wouldn't matter as we can't control which available channel is picked.

File: coderd/httpapi/httpapi.go (hunk 3 above)
Comment (mafredri) [reply coderd/httpapi/httpapi.go:249]: I honestly don't know _when_ we're rewriting/refactoring this, @f0ssel may have some idea. Personally I don't feel channels are any more dangerous than mutexes (you have deadlocks and missing unlocks to think about there), but I guess this is in the eye of the beholder. I'll certainly consider your input if I'm the one rewriting this 👍🏻.

**Review by coadler — APPROVED** [review]

File: coderd/httpapi/httpapi.go (hunk 1 above)
Comment (f0ssel) [reply coderd/httpapi/httpapi.go:208]: Awesome explanation thank you

**Review by f0ssel — APPROVED** [review]
