### PR TITLE
chore: fix proxy 404 page

### LINKED ISSUE #7415: Make 404 page on proxy have a better message
Make it a http `OK` with some message like "Hey you hit a workspace proxy!"

### PR DESCRIPTION
**Pull request by Emyrk**
Screenshot from 2023-05-05 09-37-04

Fixes https://github.com/coder/coder/issues/7415

### CODE REVIEW

File: enterprise/wsproxy/wsproxy.go [hunk 1]
```diff
@@ -235,8 +235,8 @@ func New(ctx context.Context, opts *Options) (*Server, error) {
 	r.Get("/healthz-report", s.healthReport)
 	r.NotFound(func(rw http.ResponseWriter, r *http.Request) {
 		site.RenderStaticErrorPage(rw, r, site.ErrorPageData{
-			Status:       404,
-			Title:        "Route Not Found",
+			Status:       http.StatusBadRequest,
+			Title:        "This is a Workspace Proxy",
```
Comment (kylecarbs) [inline enterprise/wsproxy/wsproxy.go:239]:
```suggestion
			Title:        "Workspace Proxy",
```

File: enterprise/wsproxy/wsproxy.go [hunk 2]
```diff
@@ -235,8 +235,8 @@ func New(ctx context.Context, opts *Options) (*Server, error) {
 	r.Get("/healthz-report", s.healthReport)
 	r.NotFound(func(rw http.ResponseWriter, r *http.Request) {
 		site.RenderStaticErrorPage(rw, r, site.ErrorPageData{
-			Status:       404,
-			Title:        "Route Not Found",
+			Status:       http.StatusBadRequest,
```
Comment (kylecarbs) [inline enterprise/wsproxy/wsproxy.go:238]:
```suggestion
			Status:       http.StatusBadRequest,
```
We shouldn't show this error code in the page, it's not helpful to the user.

File: enterprise/wsproxy/wsproxy.go [hunk 3]
```diff
@@ -235,8 +235,8 @@ func New(ctx context.Context, opts *Options) (*Server, error) {
...
+			Title:        "This is a Workspace Proxy",
 			Description:  "The route you requested does not exist on this workspace proxy. Maybe you intended to make this request to the primary dashboard? Click below to be redirected to the primary site.",
```
Comment (kylecarbs) [inline enterprise/wsproxy/wsproxy.go:240]:
```suggestion
			Description:  "Workspace Proxies route traffic in terminals and apps directly to your workspace. This page must be loaded from the dashboard. Click to be redirected!",
```

**Review by kylecarbs — CHANGES_REQUESTED** [review]

File: enterprise/wsproxy/wsproxy.go (hunk 2 above)
Comment (Emyrk) [reply enterprise/wsproxy/wsproxy.go:238]: I'll mess with the template.

**Comment by Emyrk** [comment]
Fixed

File: enterprise/wsproxy/wsproxy.go [hunk 4]
```diff
@@ -235,9 +235,11 @@ func New(ctx context.Context, opts *Options) (*Server, error) {
 	r.Get("/healthz-report", s.healthReport)
 	r.NotFound(func(rw http.ResponseWriter, r *http.Request) {
 		site.RenderStaticErrorPage(rw, r, site.ErrorPageData{
-			Status:       404,
-			Title:        "Route Not Found",
-			Description:  "The route you requested does not exist on this workspace proxy. Maybe you intended to make this request to the primary dashboard? Click below to be redirected to the primary site.",
+			Title:      "Workspace Proxy",
```
Comment (kylecarbs) [inline enterprise/wsproxy/wsproxy.go:238]: Thoughts on this being "Redirect to Dashboard" or "Head to the Dashboard" instead? Just minor for UX.

**Review by kylecarbs — APPROVED** [review]

File: enterprise/wsproxy/wsproxy.go (hunk 4 above)
Comment (Emyrk) [reply enterprise/wsproxy/wsproxy.go:238]: On the button you mean?

Comment (kylecarbs) [reply enterprise/wsproxy/wsproxy.go:238]: Well, the title doesn't really add to the content at all, so it's just redundant at the moment.

I do think the button should change too though, and say "Back to Dashboard" instead of "Back to Site"

Comment (Emyrk) [reply enterprise/wsproxy/wsproxy.go:238]: Ah. I can make the title that, we can change the button later if it's important.
