### PR TITLE
fix(coderd/provisionerdserver): pass through api ctx to provisionerdserver

### LINKED ISSUE #10257: test flake: TestWorkspace/Health/Mixed_health
Seen here: https://github.com/coder/coder/actions/runs/6509349716/job/17680685598

Error:
```
t.go:93: 2023-10-13 14:16:08.792 [erro]  inmem-provisionerd-friendly_pascal0: workspace notification after agent timeout failed  workspace_build_id=08a7f6ae-f8aa-4029-a1e4-[428](https://github.com/coder/coder/actions/runs/6509349716/job/17680685598#step:5:429)c5d99a78b ...
        error= exec pg_notify:
                   github.com/coder/coder/v2/coderd/database/pubsub.(*pgPubsub).Publish
                       /home/runner/actions-runner/_work/coder/coder/coderd/database/pubsub/pubsub.go:235
                 - context canceled
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
```

Logs: https://gist.github.com/johnstcn/0f7e4e8b21f4d1899cfba2209bfc7443

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/10257

We just happened to be sending a notification when the test completed.

Passes through coderd API ctx to provisionerd server so we can cancel workspace updates when API is shutting down.

### CODE REVIEW

File: coderd/provisionerdserver/provisionerdserver.go [hunk 1]
```diff
@@ -1190,7 +1190,12 @@ func (s *server) CompleteJob(ctx context.Context, completed *proto.CompletedJob)
 						// have a shutdown signal we can listen to.
 						<-wait
 						if err := s.Pubsub.Publish(codersdk.WorkspaceNotifyChannel(workspaceBuild.WorkspaceID), []byte{}); err != nil {
-							s.Logger.Error(ctx, "workspace notification after agent timeout failed",
+							// If the publish failed due to the context being canceled, there's nothing more for us
+							// to do here.
```
Comment (mafredri) [inline coderd/provisionerdserver/provisionerdserver.go:1194]: Does this mean the provisioner is shutting down? Should we mention that?

**Review by mafredri — APPROVED** [review]

File: coderd/provisionerdserver/provisionerdserver.go (hunk 1 above)
Comment (johnstcn) [reply coderd/provisionerdserver/provisionerdserver.go:1194]: From my reading, it means the `coderd` API that talks to provisioners is shutting down, as provisioner daemons have no access to the database pubsub directly.

Comment (spikecurtis) [reply coderd/provisionerdserver/provisionerdserver.go:1194]: This is the error that `Publish` returns, and if it's `context.Canceled`, it must mean the pubsub itself is shutting down (note that `Publish` does not take a context).

This feels very brittle.  Here and now, we know that `context.Canceled` means that the pubsub is shutting down, and here and now, we're pretty sure that means that Coderd itself is shutting down, but there is no contract with `Pubsub` that it will return `context.Canceled` on shutdown, and there is no contract that Pubsub only gets shut down when everything is being shut down.

What I did on #10170 was just ignore errors, but it seems the issue is more widespread, so I was probably wrong to take the easy way out.

What we should really do is pass a context to the provisionerd server, and then 

```
select {
    case <-s.ctx.Done():
        return
    case <-wait:
        // process the timeout
}
```

The context we pass to provisionerdserver should be the Coderd lifetime context.

**Review by spikecurtis — CHANGES_REQUESTED** [review]

File: coderd/provisionerdserver/provisionerdserver.go (hunk 1 above)
Comment (johnstcn) [reply coderd/provisionerdserver/provisionerdserver.go]: @spikecurtis Updated. I think I threaded it through correctly but you know these streets better than I.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 2]
```diff
@@ -125,6 +127,9 @@ func NewServer(
 	options Options,
 ) (proto.DRPCProvisionerDaemonServer, error) {
 	// Panic early if pointers are nil
```
Comment (mtojek) [inline coderd/provisionerdserver/provisionerdserver.go:129]: (not strictly related with this PR)
nit: panic might not be relevant, it is rather fail fast

**Review by mtojek — APPROVED** [review]
LGTM

File: coderd/provisionerdserver/provisionerdserver.go [hunk 3]
```diff
@@ -107,6 +108,7 @@ func (t Tags) Valid() error {
 }
 
 func NewServer(
+	ctx context.Context,
```
Comment (mafredri) [inline coderd/provisionerdserver/provisionerdserver.go:111]: I think we could name this differently, maybe `lifecycleCtx`, or something better. Why? Usually a context is only relevant for the execution of a function. Here I would expect `ctx` not to have any effect after `NewServer` returns, but instead the server keeps it around.

File: coderd/provisionerdserver/provisionerdserver.go (hunk 2 above)
Comment (spikecurtis) [reply coderd/provisionerdserver/provisionerdserver.go]: That comment is left over from an earlier draft of this code where we panic'd instead of returning an error.

**Review by mafredri — APPROVED** [review]
LGTM

File: coderd/provisionerdserver/provisionerdserver.go [hunk 4]
```diff
@@ -1184,16 +1190,25 @@ func (s *server) CompleteJob(ctx context.Context, completed *proto.CompletedJob)
...
-						// can't listen on the context here because we will hang around
-						// after this function has returned. The s also doesn't
-						// have a shutdown signal we can listen to.
-						<-wait
-						if err := s.Pubsub.Publish(codersdk.WorkspaceNotifyChannel(workspaceBuild.WorkspaceID), []byte{}); err != nil {
-							s.Logger.Error(ctx, "workspace notification after agent timeout failed",
+						select {
+						case <-s.ctx.Done():
+							// If the server is shutting down, we don't want to wait around.
+							s.Logger.Warn(context.Background(), "stopping notifications due to server shutdown",
```
Comment (spikecurtis) [inline coderd/provisionerdserver/provisionerdserver.go:1199]: Warn is probably overkill here.  I'd buy as low as Debug.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 5]
```diff
@@ -1184,16 +1193,25 @@ func (s *server) CompleteJob(ctx context.Context, completed *proto.CompletedJob)
...
 								slog.F("workspace_build_id", workspaceBuild.ID),
 								slog.Error(err),
 							)
+							return
+						case <-wait:
+							// Wait for the next potential timeout to occur. Note that we
+							// can't listen on the context here because we will hang around
+							// after this function has returned. The s also doesn't
+							// have a shutdown signal we can listen to.
```
Comment (spikecurtis) [inline coderd/provisionerdserver/provisionerdserver.go:1208]: this comment is outdated --- we DO have a context that acts as a shutdown signal for s.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 6]
```diff
@@ -1184,16 +1193,25 @@ func (s *server) CompleteJob(ctx context.Context, completed *proto.CompletedJob)
...
+							if err := s.Pubsub.Publish(codersdk.WorkspaceNotifyChannel(workspaceBuild.WorkspaceID), []byte{}); err != nil {
+								s.Logger.Error(context.Background(), "workspace notification after agent timeout failed",
```
Comment (spikecurtis) [inline coderd/provisionerdserver/provisionerdserver.go:1210]: it's actually fine to pass an expired context to logging functions.  `slog` only uses the context to find extra fields, never to cancel the logging request.

File: coderd/coderd.go [hunk 7]
```diff
@@ -1108,6 +1108,7 @@ func (api *API) CreateInMemoryProvisionerDaemon(ctx context.Context) (client pro
 	logger := api.Logger.Named(fmt.Sprintf("inmem-provisionerd-%s", name))
 	logger.Info(ctx, "starting in-memory provisioner daemon")
 	srv, err := provisionerdserver.NewServer(
+		ctx,
```
Comment (spikecurtis) [inline coderd/coderd.go:1111]: should be api.ctx

the `ctx` passed in is the "dialer" context

File: coderd/provisionerdserver/provisionerdserver.go (hunk 6 above)
Comment (johnstcn) [reply coderd/provisionerdserver/provisionerdserver.go:1210]: I'll keep the passed-in ctx then in case we add fields on it later.

**Review by spikecurtis — APPROVED** [review]
