### PR TITLE
fix: fix workspace status filter returning more statuses that requested

### LINKED ISSUE #7685: BE Filtering: When filtering for "deleted", the API is returning workspaces with status "failed"
Screen Shot 2023-05-25 at 15 15 59

How to reproduce:
- You need to have on your deployment failed and deleted workspaces
- Try to filter using "status:deleted"
- You will see workspaces with the "failed" badge

Response from the server:
```json
{
  "workspaces": [
    {
      "id": "b31302f5-d62b-4257-8826-8247fab736a3",
      "created_at": "2023-05-15T19:40:54.11607Z",
      "updated_at": "2023-05-15T19:40:54.11607Z",
      "owner_id": "5ccd3128-cbbb-4cfb-8139-5a1edbb60c71",
      "owner_name": "bpmct",
      "organization_id": "703f72a1-76f6-4f89-9de6-8a3989693fe5",
      "template_id": "5ae7e6f0-ca0d-403f-9fe2-3fa2063c4498",
      "template_name": "devcontainer-on-docker",
      "template_display_name": "",
      "template_icon": "",
      "template_allow_user_cancel_workspace_jobs": false,
      "latest_build": {
        "id": "65147d58-63ed-4a41-8281-13d2f73c968a",
        "created_at": "2023-05-16T16:17:57.431116Z",
        "updated_at": "2023-05-16T16:18:04.144033Z",
        "workspace_id": "b31302f5-d62b-4257-8826-8247fab736a3",
        "workspace_name": "coder-test",
        "workspace_owner_id": "5ccd3128-cbbb-4cfb-8139-5a1edbb60c71",
        "workspace_owner_name": "bpmct",
        "template_version_id": "5a4d2091-1787-44fa-bd47-dea13ea14d08",
        "template_version_name": "trusting_brahmagupta3",
        "build_number": 3,
        "transition": "delete",
        "initiator_id": "5ccd3128-cbbb-4cfb-8139-5a1edbb60c71",
        "initiator_name": "bpmct",
        "job": {
          "id": "6e61d8ef-1adf-492e-8a4e-7af2a7d8c8f0",
          "created_at": "2023-05-16T16:17:57.423774Z",
          "started_at": "2023-05-16T16:17:58.306652Z",
          "completed_at": "2023-05-16T16:18:04.140848Z",
          "error": "terraform apply: exit status 1",
          "status": "failed",
          "worker_id": "92805965-0d99-4824-9b99-cd86002c7f06",
          "file_id": "2c902acb-eeaa-461a-9556-2d68a86b7c0e",
          "tags": { "scope": "organization" }
        },
        "reason": "initiator",
        "resources": [],
        "deadline": null,
        "max_deadline": null,
        "status": "failed",
        "daily_cost": 0
      },
      "outdated": true,
      "name": "coder-test",
      "ttl_ms": 86400000,
      "last_used_at": "2023-05-16T14:05:54.475475Z",
      "deleting_at": null
    },
    {
      "id": "9113300e-0f8c-4879-aa89-dcdc312509bf",
      "created_at": "2023-03-11T19:34:52.866948Z",
      "updated_at": "2023-03-11T19:34:52.866948Z",
      "owner_id": "0bac0dfd-b086-4b6d-b8ba-789e0eca7451",
      "owner_name": "kylecarbs",
      "organization_id": "703f72a1-76f6-4f89-9de6-8a3989693fe5",
      "template_id": "0d286645-29aa-4eaf-9b52-cc5d2740c90b",
      "template_name": "coder",
      "template_display_name": "Write Coder on Coder",
      "template_icon": "/emojis/1f3c5.png",
      "template_allow_user_cancel_workspace_jobs": false,
      "latest_build": {
        "id": "88d5a8aa-d2b3-4b04-b67d-097a73beecff",
        "created_at": "2023-03-21T19:12:31.595022Z",
        "updated_at": "2023-03-21T19:12:31.595023Z",
        "workspace_id": "9113300e-0f8c-4879-aa89-dcdc312509bf",
        "workspace_name": "dev2",
        "workspace_owner_id": "0bac0dfd-b086-4b6d-b8ba-789e0eca7451",
        "workspace_owner_name": "kylecarbs",
        "template_version_id": "37bd58b3-c817-4fc3-af3b-dd9c3b83653b",
        "template_version_name": "stupefied_shannon1",
        "build_number": 3,
        "transition": "delete",
        "initiator_id": "0bac0dfd-b086-4b6d-b8ba-789e0eca7451",
        "initiator_name": "kylecarbs",
        "job": {
          "id": "a3801cca-070b-4e2a-9424-fabadae79ce6",
          "created_at": "2023-03-21T19:12:31.594053Z",
          "started_at": "2023-03-21T19:12:32.123527Z",
          "completed_at": "2023-03-21T19:12:37.211205Z",
          "error": "recv workspace provision: plan terraform: terraform plan: exit status 1",
          "status": "failed",
          "worker_id": "5989824e-a8a7-4354-b520-e6ba99b2a183",
          "file_id": "7715ef60-7ad0-4da9-b9c0-ec339f7be71d",
          "tags": { "scope": "organization" }
        },
        "reason": "initiator",
        "resources": [],
        "deadline": null,
        "max_deadline": null,
        "status": "failed",
        "daily_cost": 0
      },
      "outdated": true,
      "name": "dev2",
      "last_used_at": "0001-01-01T00:00:00Z",
      "deleting_at": null
    }
  ],
  "count": 2
}
```

### PR DESCRIPTION
**Pull request by Emyrk**
Fixes the postgres condition to not make failed workspaces show up with the deleted status filter.
Also fixed the dbfake to match the postgres implementation. It was acting a lot differently.

See https://github.com/coder/coder/issues/7685#issuecomment-1568993952
Fixes: https://github.com/coder/coder/issues/7685

# Testing

Made a unit test to test this logic. Doing it on a real DB is slow, so going to skip in CI :cry:. Took a bit of work to get the test setup.

### CODE REVIEW

File: coderd/database/dbgen/generator.go [hunk 1]
```diff
@@ -17,14 +17,25 @@ import (
...
 // All methods take in a 'seed' object. Any provided fields in the seed will be
 // maintained. Any fields omitted will have sensible defaults generated.
 
+// genCtx is to give all generator functions permission if the db is a dbauthz db.
+var genCtx = dbauthz.As(context.Background(), rbac.Subject{
+	ID:     "owner",
+	Roles:  rbac.Roles(must(rbac.RoleNames{rbac.RoleOwner()}.Expand())),
+	Groups: []string{},
+	Scope:  rbac.ExpandableScope(rbac.ScopeAll),
+})
```
Comment (Emyrk) [inline coderd/database/dbgen/generator.go:35]: This is so dbgen can work on dbauthz wrapped databases for unit testing.

File: coderd/database/queries/workspaces.sql [hunk 2]
```diff
@@ -157,10 +157,12 @@ WHERE
...
 					latest_build.completed_at IS NOT NULL AND
 					latest_build.updated_at - INTERVAL '30 seconds' < NOW() AND
-					latest_build.transition = 'delete'::workspace_transition
+					latest_build.transition = 'delete'::workspace_transition AND
+					-- If the error field is null, the status is 'failed'
+					latest_build.error IS NULL
 
 				WHEN @status = 'deleting' THEN
-					latest_build.completed_at IS NOT NULL AND
+					latest_build.completed_at IS NULL AND
```
Comment (Emyrk) [inline coderd/database/queries/workspaces.sql:165]: This was the only fix needed for prod. All other fixes were just for the dbfake

File: coderd/database/queries/workspaces.sql [hunk 3]
```diff
@@ -157,10 +157,12 @@ WHERE
 					latest_build.canceled_at IS NULL AND
 					latest_build.completed_at IS NOT NULL AND
 					latest_build.updated_at - INTERVAL '30 seconds' < NOW() AND
-					latest_build.transition = 'delete'::workspace_transition
+					latest_build.transition = 'delete'::workspace_transition AND
+					-- If the error field is null, the status is 'failed'
```
Comment (spikecurtis) [inline coderd/database/queries/workspaces.sql:161]:
```suggestion
					-- If the error field is not null, the status is 'failed'
```

File: coderd/database/queries/workspaces.sql (hunk 2 above)
Comment (spikecurtis) [inline coderd/database/queries/workspaces.sql:165]: so, it's really difficult to read this query and convince yourself that these WHERE clauses are 

a) non-overlapping
b) match the golang implementation of the status computation

What do you think about the strategy of introducing a stored procedure that computes the status?  Then the filter logic in this query becomes a trivial WHERE clause, and we can use the DB-computed status in prod, rather than computing the status in the API layer.

Annoyingly, we'd still have to keep the golang implementation around for the dbfake, but they could both be written in an imperative style and so it will be much easier to verify the algorithm matches.

File: coderd/workspaces_test.go [hunk 4]
```diff
@@ -555,6 +562,201 @@ func TestWorkspaceByOwnerAndName(t *testing.T) {
...
+		StartedAt: sql.NullTime{Time: time.Now().Add(time.Second * -2), Valid: true},
+	}, database.WorkspaceTransitionDelete)
+
+	// deleted
+	makeWorkspace(database.Workspace{
+		Name: string(database.WorkspaceStatusDeleted),
+	}, database.ProvisionerJob{
+		StartedAt:   sql.NullTime{Time: time.Now().Add(time.Second * -2), Valid: true},
+		CompletedAt: sql.NullTime{Time: time.Now(), Valid: true},
+	}, database.WorkspaceTransitionDelete)
```
Comment (spikecurtis) [inline coderd/workspaces_test.go:725]: these tests are great and all, but they are not combinatorially exhaustive on null vs non-null for all fields.  This is another reason I think a stored procedure for the status is better.

File: coderd/database/queries/workspaces.sql (hunk 2 above)
Comment (Emyrk) [reply coderd/database/queries/workspaces.sql:165]: Oh it was a headache. Are we using stored procedures anywhere else, or would this be the first case? I'm open to anything that makes this easier.

Ideally though, it would be in the next PR so this bug is fixed in main. The major contribution from this PR is the test imo.

File: coderd/workspaces_test.go (hunk 4 above)
Comment (Emyrk) [reply coderd/workspaces_test.go:725]: It is definitely not exhaustive. The annoying thing too is when we prepulate this much data (which isn't even that much), the postgres test gets so slow. So I skipped it in CI, meaning this bug could easily pop up again silently :cry:.

I was debating about putting in a batch insert SQL query outside our typical db interface and see if it is faster. If we go the stored procedure route, might be worth investigating how to make the postgres test run in a reasonable amount of time.

**Comment by Kira-Pilot** [comment]
@Emyrk I tried this out locally and failed workspaces do not show up with the deleted status filter - awesome.
I am a bit confused about the status behavior in general, however. If I have a deleted workspace and I filter by `status:deleted`, nothing shows up. This is confusing to me given the ticket description. Am I missing something?
Screenshot 2023-06-01 at 11 20 03 AM
Screenshot 2023-06-01 at 11 20 23 AM

File: coderd/workspaces_test.go (hunk 4 above)
Comment (spikecurtis) [reply coderd/workspaces_test.go:725]: I wonder if the slowness is related to how we have to create the job, then acquire it, then fail/complete it.  Acquiring in particular might be slow because of the locking we do.

In testing we could have some queries that directly insert the job in the state we want it.  Not exposed on the main `Store` interface, but available if you type assert to a test type.

File: coderd/database/queries/workspaces.sql (hunk 2 above)
Comment (spikecurtis) [reply coderd/database/queries/workspaces.sql:165]: We have triggers for deletion of tokens stored in the DB.  This would be the first computed column, though.

Fine to follow up in another PR.

**Review by spikecurtis — APPROVED** [review]

**Comment by Emyrk** [comment]
@Kira-Pilot could it be "deleting"? 
Can you send the "all workspaces" response?

**Comment by Emyrk** [comment]
> @Emyrk I tried this out locally and failed workspaces do not show up with the deleted status filter - awesome. I am a bit confused about the status behavior in general, however. If I have a deleted workspace and I filter by `status:deleted`, nothing shows up. This is confusing to me given the ticket description. Am I missing something? Screenshot 2023-06-01 at 11 20 03 AM Screenshot 2023-06-01 at 11 20 23 AM

Ah, so that is a different bug actually.

`deleted` is a special case handled in the sql here: https://github.com/coder/coder/blob/cf35412b77756e08f7da343fce9e7d6108edeaaf/coderd/database/queries/workspaces.sql#L108-L109

What I fixed was the list of statuses. So if you search `status:deleted` nothing shows up as we do not show deleted workspaces to users right now.

So that is expected behavior.

**Review by Kira-Pilot — APPROVED** [review]
