### PR TITLE
fix: disable setup page once setup has been completed

### LINKED ISSUE #9157: /setup endpoint available when owner existing
When opening for the first time coder deployed using helm, I'm redirected to https://coder.../setup, to create an account. Without a message to inform me of the success, I looked inside the database, saw a new user with owner permission, and copy the change to my logged user with oidc. 

Moreover, I had set CODER_DISABLE_PASSWORD_AUTH to true.

Now I deleted the local user from the web interface.

My issue is that /setup is still available, asking to create a user. It does not seem to work, so no party can steal ownership but should be disabled fully.

Finally, allowing to set a user from an oidc provider could be a nice feature to remove the need to create the first account manually.

### PR DESCRIPTION
**Pull request by aslilac**
Fixes #9157 

Setup will fail if a first user has been configured, and we already have this state on the client, so we should just use it to navigate you away

### CODE REVIEW

**Comment by aslilac** [comment]
the tests are broken locally right now, and debugging this through CI is rough 💀

File: site/src/pages/SetupPage/SetupPage.tsx [hunk 1]
```diff
@@ -23,12 +24,22 @@ export const SetupPage: FC = () => {
...
     if (authState.matches("signedIn")) {
-      window.location.assign("/workspaces")
+      navigate("/", { state: { isRedirect: true } })
     }
-  }, [authState])
+
+    // If we've already completed setup, navigate to the login page
+    if (
+      !authState.matches("loadingInitialAuthData") &&
+      !authState.matches("configuringTheFirstUser")
```
Comment (BrunoQuaresma) [inline site/src/pages/SetupPage/SetupPage.tsx:38]: Nit: Maybe we could do:
```ts
const isSetupComple = !authState.matches("loadingInitialAuthData") &&  !authState.matches("configuringTheFirstUser")
```

**Review by BrunoQuaresma — APPROVED** [review]
