### PR TITLE
fix: make handleManifest always signal dependents

### LINKED ISSUE #13139: Agent RPC socket failure during handleManifest can lock up the agent
Seen in a test flake: https://github.com/coder/coder/actions/runs/8921350830/job/24501290702?pr=13128

But, the problem is a race condition in our product code.

The agent has a cascade of routines that need to use the RPC connection, and uses a channel called `manifestOK` to communicate that the manifest has been successfully retrieved.

Due to an "idiosyncratic" property of our `WebsocketNetConn`, a failed socket can sometimes manifest as a canceled context in the error.  Our routine management code has special processing to handle `context.Canceled` to preserve some routines that need to keep running even if the main context is canceled, and so it swallows that error and doesn't propagate it to the other routines.

This leaves us in a deadlock if the websocket fails _during_ the `handleManifest` routine.  We won't close the `manifestOK` channel, but we also don't propagate an error to the other routines, so they hang forever, deadlocked until something external kills the agent.

To fix, we need to do at least one of the following:

1) Fix `WebsocketNetConn` so it won't return `context.Canceled` unless the input context really was canceled
2) Fix the `APIConnRoutineManager` so that we don't swallow `context.Canceled` unless the graceful context was actually canceled.
3) Fix the communication between the `handleManifest` routine and its dependents, so that when it completes it always sends success or failure signal(s)

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #13139

Using a bare channel to signal dependent goroutines means that we can only signal success, not failure, which leads to deadlock if we fail in a way that doesn't cause the whole `apiConnRoutineManager` to tear down routines.

Instead, we use a new object called a `checkpoint` that signals success or failure, so that dependent routines get unblocked if the routine they depend on fails.

### CODE REVIEW

**Comment by spikecurtis** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/coder/coder/13141?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#13142** <a href="https://app.graphite.dev/github/pr/coder/coder/13142?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13141** <a href="https://app.graphite.dev/github/pr/coder/coder/13141?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#13140** <a href="https://app.graphite.dev/github/pr/coder/coder/13140?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: agent/agent.go [hunk 1]
```diff
@@ -501,8 +501,8 @@ func (a *agent) reportMetadata(ctx context.Context, conn drpc.Conn) error {
 			// mutex logic and overloading the API.
 			for _, md := range manifest.Metadata {
 				md := md
-				// We send the result to the channel in the goroutine to avoid
-				// sending the same result multiple times. So, we don't care about
+				// We send the complete to the channel in the goroutine to avoid
+				// sending the same complete multiple times. So, we don't care about
```
Comment (mafredri) [inline agent/agent.go:505]: Why the rewording?

File: agent/checkpoint.go [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+	c.err = err
+	close(c.done)
+}
+
+func (c *checkpoint) waitCtx(ctx context.Context) error {
+	select {
+	case <-ctx.Done():
+		return ctx.Err()
+	case <-c.done:
+		return c.err
```
Comment (mafredri) [inline agent/checkpoint.go:25]: Should one of these have higher priority than the other?

File: agent/checkpoint.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+	err  error
+}
+
+// complete the checkpoint.  Pass nil to indicate the checkpoint was ok.
+func (c *checkpoint) complete(err error) {
+	c.err = err
+	close(c.done)
+}
+
+func (c *checkpoint) waitCtx(ctx context.Context) error {
```
Comment (mafredri) [inline agent/checkpoint.go:20]: Nit: ctx feels superfluous here.
```suggestion
func (c *checkpoint) wait(ctx context.Context) error {
```

File: agent/agent.go [hunk 4]
```diff
@@ -807,56 +807,48 @@ func (a *agent) run() (retErr error) {
...
 		})
 
 	connMan.start("fetch service banner loop", gracefulShutdownBehaviorStop, a.fetchServiceBannerLoop)
 
 	connMan.start("stats report loop", gracefulShutdownBehaviorStop, func(ctx context.Context, conn drpc.Conn) error {
-		select {
-		case <-ctx.Done():
-			return nil
-		case <-networkOK:
+		if networkOK.waitCtx(ctx); err != nil {
```
Comment (mafredri) [inline agent/agent.go:850]: Missing err assignment.

File: agent/checkpoint.go [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+// checkpoint allows a goroutine to communicate when it is OK to proceed beyond some async condition
+// to other dependent goroutines.
+type checkpoint struct {
+	done chan struct{}
+	err  error
+}
+
+// complete the checkpoint.  Pass nil to indicate the checkpoint was ok.
+func (c *checkpoint) complete(err error) {
+	c.err = err
```
Comment (mafredri) [inline agent/checkpoint.go:16]: How about using sync once here to simplify usage an allowing multiple calls to complete?

**Review by mafredri — APPROVED** [review]
I like the checkpoint implementation, just some minor stuff but otherwise LGTM (no need to re-review unless you want.)

File: agent/agent.go (hunk 1 above)
Comment (spikecurtis) [reply agent/agent.go:505]: overzealous refactor tooling; fill fix

File: agent/checkpoint.go (hunk 5 above)
Comment (spikecurtis) [reply agent/checkpoint.go:16]: That introduces the possibility of multiple calls racing success vs failure.  Better to ensure that there is only one call to `complete()`.

Comment (mafredri) [reply agent/checkpoint.go:16]: In what way would it be racy? Sync once is atomic AFAIK and first come-first served, the other remains blocked waiting for the first to complete.

Comment (mafredri) [reply agent/checkpoint.go:16]: Perhaps another way to put it: I think it would be preferable for this to be safe to use incorrectly and document how it _should_ be used, vs incorrect use resulting in a runtime panic.

Comment (spikecurtis) [reply agent/checkpoint.go:16]: It's racy in the sense that if you have two callers, one saying "success" and one saying "failure", then they can race each other to determine which gets reported to things waiting on the checkpoint.

Comment (mafredri) [reply agent/checkpoint.go:16]: I think I understand your concern but I have a hard time understanding how it's relevant here. If someone introduces that race right now the program will panic instead. So it needs to be avoided in either case, i.e. a non-issue.

Comment (spikecurtis) [reply agent/checkpoint.go:16]: > I think it would be preferable for this to be safe to use incorrectly and document how it should be used, vs incorrect use (or carelessness) resulting in a runtime panic.

I think that kind of defensive programming is a disservice in this case.  Silently absorbing incorrect/careless use in a non-deterministic way is a source of frustrating and hard to diagnose bugs.

There is a genuine case to be made for a central service like Coderd needing to avoid panicking because of programming bugs, but here in the Agent, I think it's preferable to panic, print a stack trace, and exit.

File: agent/checkpoint.go (hunk 2 above)
Comment (spikecurtis) [reply agent/checkpoint.go:25]: I don't think there is a need, and go doesn't make strong guarantees about how selects get ordered when multiple channels become readable close to the same time.

Comment (mafredri) [reply agent/checkpoint.go:25]: Alright, just thought I'd mention in case it would matter. Prioritization is quite simple, albeit a bit verbose, essentially re-testing like this:

```go
	select {
	case <-ctx.Done():
		select {
		case <-c.done:
			return c.err
		default:
			return ctx.Err()
		}
	case <-c.done:
		return c.err
	}
```

File: agent/checkpoint.go (hunk 5 above)
Comment (mafredri) [reply agent/checkpoint.go:16]: I can definitely see the benefit of that approach as well, but I do feel we should have a high tolerance towards introducing sharp edges that can result in decreased developer flow. If we feel this is important enough to panic, wouldn’t another approach be to detect a second call and log it as an error + stack trace?

We don’t know how well the logs from a panic will be persisted either, the user may attempt to rebuild their workspace and ultimately we caused an inconvenience and are never the wiser.

**Review by mafredri — APPROVED** [review]
Thanks for adding the critical log handling, LGTM!

**Comment by spikecurtis** [comment]
### Merge activity

* **May 6, 6:34 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/coder/coder/13141) rebased this pull request as part of a merge.
