### PR TITLE
fix(cli/sessionstore): don't run Windows keyring tests in parallel

### LINKED ISSUE #1370: flake: TestKeyring "file does not exist"
```
=== Failed
=== FAIL: cli/sessionstore TestWindowsKeyring_WriteReadDelete (0.04s)
    sessionstore_windows_test.go:74: 
        	Error Trace:	C:/actions-runner/coder/coder/cli/sessionstore/sessionstore_windows_test.go:74
        	Error:      	Expected error with "file does not exist" in chain but got nil.
        	Test:       	TestWindowsKeyring_WriteReadDelete

=== FAIL: cli/sessionstore TestKeyring/StorageFormat (0.02s)
    sessionstore_test.go:251: 
        	Error Trace:	C:/actions-runner/coder/coder/cli/sessionstore/sessionstore_test.go:251
        	Error:      	Received unexpected error:
        	            	file does not exist
        	Test:       	TestKeyring/StorageFormat
    --- FAIL: TestKeyring/StorageFormat (0.02s)

=== FAIL: cli/sessionstore TestKeyring/MultipleServers (0.02s)
    sessionstore_test.go:179: 
        	Error Trace:	C:/actions-runner/coder/coder/cli/sessionstore/sessionstore_test.go:179
        	Error:      	Received unexpected error:
        	            	file does not exist
        	Test:       	TestKeyring/MultipleServers
    --- FAIL: TestKeyring/MultipleServers (0.02s)

=== FAIL: cli/sessionstore TestKeyring (0.00s)
```

seen here: https://github.com/coder/coder/runs/65100382395

### PR DESCRIPTION
**Pull request by kylecarbs**
Removes `t.Parallel()` from `TestKeyring` and `TestWindowsKeyring_WriteReadDelete`. The OS keyring is a shared system resource that's flaky under concurrent access, especially Windows Credential Manager in CI.

Fixes coder/internal#1370

### CODE REVIEW

File: cli/sessionstore/sessionstore_test.go [hunk 1]
```diff
@@ -22,7 +22,8 @@ type storedCredentials map[string]struct {
 }
 
 func TestKeyring(t *testing.T) {
-	t.Parallel()
+	// Not parallel: subtests hit the OS keyring which is flaky under
+	// concurrent access (especially Windows Credential Manager in CI).
```
Comment (mafredri) [inline cli/sessionstore/sessionstore_test.go]: This should be:

```
//nolint:tparallel // Subtests hit ...
func TestKeyring(t *testing.T) {
```

Same for the other one.

**Review by mafredri — COMMENTED** [review]
Once nolints are fixed, 👍🏻

File: cli/sessionstore/sessionstore_test.go (hunk 1 above)
Comment (mafredri) [reply cli/sessionstore/sessionstore_test.go]: tparallel or paralleltest, not sure which.

**Review by mafredri — APPROVED** [review]
Oops, thought I approved earlier.
