### PR TITLE
fix: add constraint and runtime check for provisioner logs size limit

### LINKED ISSUE #17992: bug: Workspaces that generates >1MB startup logs result in failure
A template that generates startup logs in excess of 1MB can cause workspace builds to fail even though nothing fatal occurs during the provisioning of the workspace.

The workspace provisioning should still complete but we should emit some message when we hit 1MB that no more logs will be emitted. We should consider making the limit configurable as well.

### PR DESCRIPTION
**Pull request by bcpeinhardt**
This PR sets a constraint of 1MB on the provisioner job logs written to the database. This is consistent with the constraint we place on workspace agent logs: https://github.com/coder/coder/blob/4ac6be6d835dc36c242e35a26b584b784040bf28/coderd/database/dump.sql#L2030

It also adds a message printed to the front end about the provisioner log overflow, and updates the message printed to the front end when workspace startup logs exceed the max, as it was causing some customers to think their startup script had failed to run.

Closes #17992

### CODE REVIEW

File: coderd/provisionerdserver/provisionerdserver.go [hunk 1]
```diff
@@ -927,6 +933,32 @@ func (s *server) UpdateJob(ctx context.Context, request *proto.UpdateJobRequest)
...
+				if err != nil {
+					s.Logger.Error(ctx, "failed to set logs overflowed flag", slog.F("job_id", parsedID), slog.Error(err))
+				}
+				return &proto.UpdateJobResponse{
+					Canceled: job.CanceledAt.Valid,
+				}, nil
+			}
+			s.Logger.Error(ctx, "failed to update logs length", slog.F("job_id", parsedID), slog.Error(err))
+			return nil, xerrors.Errorf("update logs length: %w", err)
+		}
```
Comment (cstyan) [inline coderd/provisionerdserver/provisionerdserver.go]: I think it might be a good idea to store the current logs length and overflow state as variables in this Go code. With that change we would update the length var when an `Insert` call is successful, and we can determine prior to insertion whether the log we want to insert will cause the overflow. That way we can avoid the extra `s.Database.UpdateProvisionerJobLogsLength` call on every log line after an overflow has occurred.

File: coderd/database/queries/provisionerjoblogs.sql [hunk 2]
```diff
@@ -8,6 +8,14 @@ WHERE
 	AND (
 		id > @created_after
 	) ORDER BY id ASC;
+	
+-- name: GetProvisionerJobLogSize :one
```
Comment (bcpeinhardt) [inline coderd/database/queries/provisionerjoblogs.sql]: I can remove this query now I think.

File: site/src/modules/resources/AgentRow.tsx [hunk 3]
```diff
@@ -87,7 +87,8 @@ export const AgentRow: FC<AgentRowProps> = ({
 			logs.push({
 				id: -1,
 				level: "error",
-				output: "Startup logs exceeded the max size of 1MB!",
+				output:
+					"Startup logs exceeded the max size of 1MB, and will not continue to be written to the database! Logs will continue to be written to the /tmp/coder-startup-script.log file in the workspace.",
```
Comment (cstyan) [inline site/src/modules/resources/AgentRow.tsx:91]: should the other places for the logging also contain the more descriptive message, in `WorkspaceBuildLogs.tsx` and `WorkspaceBuildPageView.tsx`?

Comment (bcpeinhardt) [reply site/src/modules/resources/AgentRow.tsx:91]: Yeah I think so :)

File: coderd/provisionerdserver/provisionerdserver.go [hunk 4]
```diff
@@ -902,36 +902,101 @@ func (s *server) UpdateJob(ctx context.Context, request *proto.UpdateJobRequest)
...
-			insertParams.CreatedAt = append(insertParams.CreatedAt, time.UnixMilli(log.CreatedAt))
-			insertParams.Level = append(insertParams.Level, logLevel)
-			insertParams.Stage = append(insertParams.Stage, log.Stage)
-			insertParams.Source = append(insertParams.Source, logSource)
-			insertParams.Output = append(insertParams.Output, log.Output)
+			createdAt = time.UnixMilli(log.CreatedAt)
+			stage = log.Stage
+			output = log.Output
+
+			// Check if we would overflow the job logs (not leaving enough room for the error message)
```
Comment (cstyan) [inline coderd/provisionerdserver/provisionerdserver.go:937]:
```suggestion
// Check if we would overflow the job logs (also leaving enough room for the error message).
```

File: coderd/database/dbauthz/dbauthz.go [hunk 5]
```diff
@@ -4489,6 +4489,22 @@ func (q *querier) UpdateProvisionerJobByID(ctx context.Context, arg database.Upd
 	return q.db.UpdateProvisionerJobByID(ctx, arg)
 }
 
+func (q *querier) UpdateProvisionerJobLogsLength(ctx context.Context, arg database.UpdateProvisionerJobLogsLengthParams) error {
+	// Not sure what the rbac should be here, going with this for now
```
Comment (cstyan) [inline coderd/database/dbauthz/dbauthz.go:4493]: This is the only bit I'm unsure of, maybe include the same comment as the other provisioner related functions have?
```
// TODO: Remove this once we have a proper rbac check for provisioner jobs.
// Details in https://github.com/coder/coder/issues/16160
```
or ask @mafredri since he opened that issue?

**Review by cstyan — APPROVED** [review]
Approving, just one bit I'm unsure about in the rbac stuff.

File: coderd/database/dbauthz/dbauthz.go (hunk 5 above)
Comment (bcpeinhardt) [reply coderd/database/dbauthz/dbauthz.go:4493]: Our manual testing was actually from the admin account, we should look at this again before merging I think.
Edit: I tested with a member account and everything works fine. I could be way off here but I think the action.Update on the ResourceProvisionerJob is coming from the template admin?

Comment (bcpeinhardt) [reply coderd/database/dbauthz/dbauthz.go:4493]: There are several other queries which perform the same rbac check we do to update fields on the ProvisionerJobs table, so I feel comfortable merging this and revisiting the provisioner jobs rbac in the future.
