### PR TITLE
fix(site): Fix template icon field validation

### LINKED ISSUE #7299: `AxoisError` returned when editing template in UI
`0.23.0` - when editing an existing template, I clicked `Submit` and received this error underneath the `Name` field:

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
I noticed two bugs so I made two fixes:
- Validate max char on the icon field
- Do not handle non 4xx errors as validation errors

FIx #7299

### CODE REVIEW

File: site/src/testHelpers/entities.ts [hunk 1]
```diff
@@ -1261,13 +1263,11 @@ type MockAPIOutput = {
   isAxiosError: boolean
 }
 
-type MakeMockApiErrorFunction = (input: MockAPIInput) => MockAPIOutput
-
-export const makeMockApiError: MakeMockApiErrorFunction = ({
+export const makeMockValidationApiError = ({
```
Comment (BrunoQuaresma) [inline site/src/testHelpers/entities.ts:1266]: Renamed it to make the purpose more clear.

**Review by Kira-Pilot — APPROVED** [review]
I looked over the util refactors (nice!) and the machines. Let me know if there's a particular way you'd like me to help test the general refactor; otherwise, looks good to me!
