### PR TITLE
fix: use ANSI colors codes instead of RGB

### LINKED ISSUE #13211: coder cli colors override terminal's theming
We have a user that reports:

> in case we have control over this, yellow might not be the best text color here. seems lots of coder-related things output specific colors and bypass my terminal's theme, leading to text that isn't always easy to read

image_720-1

Is there a way to make these colors more friendly to non-dark background terminals?

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fixes https://github.com/coder/coder/issues/13211

Instead of using RGB color codes, we instead use ANSI color codes. This means that we respect a user's terminal theme. Not all of the new colors match the old ones but this is a limitation with using 4-bit ANSI colors.

This change also allows users to pass `--no-color` to the CLI to completely disable theming. It is worth noting that whilst we do define the `serpent.Option`, we manually check `os.Args` for the flag as there doesn't appear to be a way to have a global middleware with `serpent` (whereas `spf13/cobra` does have this).

This change also removes `> ` from Prompt, and replaces it with `  ` as on `--no-color` there is no difference.

Before:
Screenshot 2024-09-13 at 15 08 26

After:
Screenshot 2024-09-13 at 15 09 15

Before:
Screenshot 2024-09-13 at 15 08 34

After:
Screenshot 2024-09-13 at 15 09 30

Before:
Screenshot 2024-09-13 at 15 08 45

After:
Screenshot 2024-09-13 at 15 09 39

Before:
Screenshot 2024-09-13 at 15 08 54

After:
Screenshot 2024-09-13 at 15 09 50

~~With `--no-color`~~ Now requires `NO_COLOR` environment variable
Screenshot 2024-09-13 at 15 10 09

### CODE REVIEW

File: cli/root.go [hunk 1]
```diff
@@ -461,6 +461,12 @@ func (r *RootCmd) Command(subcommands []*serpent.Command) (*serpent.Command, err
 			Value:       serpent.StringOf(&r.globalConfig),
 			Group:       globalGroup,
 		},
+		{
+			Flag:        cliui.NoColorFlag,
```
Comment (johnstcn) [inline cli/root.go:465]: Wonder if it would make sense to also allow setting it as an env (`CODER_NO_COLOR`)? Not blocking.

File: cli/cliui/cliui.go [hunk 2]
```diff
@@ -37,22 +43,33 @@ var (
...
-	Fuchsia = Color("#EE6FF8")
-	Yellow  = Color("#ECFD65")
-	Blue    = Color("#5000ff")
+	red           = Color("1")
+	green         = Color("2")
+	yellow        = Color("3")
+	magenta       = Color("5")
+	white         = Color("7")
+	brightBlue    = Color("12")
+	brightMagenta = Color("13")
```
Comment (johnstcn) [inline cli/cliui/cliui.go:52]: nit: indicate these are ANSI color codes

File: cli/cliui/cliui.go [hunk 3]
```diff
@@ -109,11 +126,11 @@ func Field(s string) string {
 	return pretty.Sprint(DefaultStyles.Field, s)
 }
 
-func ifTerm(fmt pretty.Formatter) pretty.Formatter {
+func ifTerm(f pretty.Formatter) pretty.Formatter {
 	if !isTerm() {
 		return pretty.Nop
 	}
-	return fmt
+	return f
```
Comment (johnstcn) [inline cli/cliui/cliui.go:133]: 👍

File: cmd/cliui/main.go [hunk 4]
```diff
@@ -37,6 +38,51 @@ func main() {
...
+	root.Options = []serpent.Option{
+		{
+			Default: "false",
+			Flag:    cliui.NoColorFlag,
+			Value:   serpent.BoolOf(&cliui.NoColor),
+		},
+	}
+
+	root.Children = append(root.Children, &serpent.Command{
+		Use: "colors",
```
Comment (johnstcn) [inline cmd/cliui/main.go:50]: 👍 👍

**Review by johnstcn — APPROVED** [review]
Nice work! Just some nits on my end.
Smoke-tested example prompts with and without colour.

File: cli/root.go (hunk 1 above)
Comment (DanielleMaywood) [reply cli/root.go:465]: Yes that should be a good idea. There is a 'standard' around using `NO_COLOR` for this https://no-color.org. We could do both `NO_COLOR` and `CODER_NO_COLOR`?

Comment (johnstcn) [reply cli/root.go:465]: Sounds good to me!

**Review by mafredri — COMMENTED** [review]
I think the global NoColor var could cause a race in our testing since we run things concurrently. E.g. if multiple tests in `cli` package set `--no-color` option, we'd run into it.

Other than that, I think this looks great. Might be worth looking into improving serpent so we can do this in a better way. And perhaps get rid of the package-global state in favor of a "color" instance. That's a much more intrusive change though.

File: cli/cliui/cliui.go [hunk 5]
```diff
@@ -123,42 +140,45 @@ func init() {
 	DefaultStyles = Styles{
 		Code: pretty.Style{
 			ifTerm(pretty.XPad(1, 1)),
-			pretty.FgColor(Red),
-			pretty.BgColor(color.Color("#2c2c2c")),
+			pretty.FgColor(color.Color("#ED567A")),
+			pretty.BgColor(color.Color("#2C2C2C")),
```
[the remark this answers is not in the document]
Comment (DanielleMaywood) [reply cli/cliui/cliui.go:147]: As we set both the foreground and background colour, we have complete control over the contrast so this looks the same regardless of the terminal theme. If we want to use an ANSI code instead we can but there isn't a need to here.

`red` was defined as `#ED567A`, and the new `red` didn't look as good on the background so I kept it as the old one.

**Comment by johnstcn** [comment]
> I think the global NoColor var could cause a race in our testing since we run things concurrently.

@mafredri potentially, yes -- but we already check for `test.v` and skip colours. So I don't think we'd even hit this as long as the check for `test.v` came first.

**Comment by DanielleMaywood** [comment]
> I think the global NoColor var could cause a race in our testing since we run things concurrently. E.g. if multiple tests in `cli` package set `--no-color` option, we'd run into it.

I should probably have documented this but we don't actually use the global var, I needed it to set it in `cmd/cliui` but it appears now removing it from `cmd/coder` doesn't cause the same issue so I should be able to remove this.

We can't make use of it as serpent sets it too late as we can't hook into serpent before it run commands.

**Comment by mafredri** [comment]
> @mafredri potentially, yes -- but we already check for `test.v` and skip colours. So I don't think we'd even hit this as long as the check for `test.v` came first.

Updating the var from multiple locations is still a data race, can be seen in CI here: https://github.com/coder/coder/actions/runs/10851466684/job/30115309148?pr=14665#step:5:5121

**Comment by mafredri** [comment]
> I should probably have documented this but we don't actually use the global var, I needed it to set it in `cmd/cliui` but it appears now removing it from `cmd/coder` doesn't cause the same issue so I should be able to remove this.

Alright, then I think using a local var to the serpent command would be better. 👍🏻

**Comment by DanielleMaywood** [comment]
> I should probably have documented this but we don't actually use the global var, I needed it to set it in `cmd/cliui` but it appears now removing it from `cmd/coder` doesn't cause the same issue so I should be able to remove this.

Turns out serpent behaves differently with `serpent.BoolOf` versus `serpent.Discard`. BoolOf allows just writing `--no-color` but we can't do that with `Discard`.

**Comment by DanielleMaywood** [comment]
> Alright, then I think using a local var to the serpent command would be better. 👍🏻 (+ comment explaining it's purpose)

So define a local var in `root.go` such as `noColorDiscarded`?

File: cli/cliui/cliui.go [hunk 6]
```diff
@@ -37,22 +43,33 @@ var (
...
 			color = termenv.Ascii
 		}
+
+		// Currently it appears there is no way to use the flag from
+		// serpent as it isn't possible to create a root middleware that
+		// runs for every command. For now we just check if `os.Args`
+		// has the flag.
+		if slices.Contains(os.Args, fmt.Sprintf("--%s", NoColorFlag)) {
+			color = termenv.Ascii
+		}
```
[the remark this answers is not in the document]
Comment (DanielleMaywood) [reply cli/cliui/cliui.go:75]: Unfortunately not as `NoColor` is set _after_ our code runs. This is because there is no (apparent) way to have this initialization code ran before _every_ command but after serpent sets up the options.

**Comment by mafredri** [comment]
> So define a local var in `root.go` such as `noColorDiscarded`?

Yep, inside `func (r *RootCmd) Command(subcommands []*serpent.Command) (*serpent.Command, error)` 👍🏻.

File: cli/cliui/cliui.go [hunk 7]
```diff
@@ -37,22 +43,36 @@ var (
...
 			// Use a consistent colorless profile in tests so that results
 			// are deterministic.
 			color = termenv.Ascii
 		}
+
+		// Currently it appears there is no way to use the flag from
+		// serpent as it isn't possible to create a root middleware that
+		// runs for every command. For now we just check if `os.Args`
+		// has the flag.
+		if slices.Contains(os.Args, fmt.Sprintf("--%s", NoColorFlag)) ||
```
[the remark this answers is not in the document]
Comment (DanielleMaywood) [reply cli/cliui/cliui.go:71]: Can do!

> `--no-color=true` and `--no-color=true`

Do my eyes deceive me or are these both the same?

[the remark this answers is not in the document]
Comment (mafredri) [reply cli/cliui/cliui.go:69]: A case of copy-pasta 😂, sorry. Meant `false` for the second.

[the remark this answers is not in the document]
Comment (DanielleMaywood) [reply cli/cliui/cliui.go:69]: Got you, just pushed a change with `--no-color=true` handling. It appears we already handle the `--no-color=false` case!

File: cli/cliui/cliui.go [hunk 8]
```diff
@@ -37,22 +41,37 @@ var (
...
 	colorOnce.Do(func() {
 		color = termenv.NewOutput(os.Stdout).ColorProfile()
+
 		if flag.Lookup("test.v") != nil {
 			// Use a consistent colorless profile in tests so that results
 			// are deterministic.
 			color = termenv.Ascii
 		}
+
+		// Currently it appears there is no way to use the flag from
```
Comment (ammario) [inline cli/cliui/cliui.go:65]: Have you tried setting the option on the root command? It should then evaluate on every command.

File: cli/cliui/cliui.go [hunk 9]
```diff
@@ -37,22 +41,37 @@ var (
...
+		// serpent as it isn't possible to create a root middleware that
+		// runs for every command. For now we just check if `os.Args`
+		// has the flag.
+		if slices.Contains(os.Args, fmt.Sprintf("--%s", NoColorFlag)) ||
```
Comment (ammario) [inline cli/cliui/cliui.go:69]: This is super janky. Relying on os.Args makes it difficult to test. Also, someone could modify the option at the CLI layer and easily forget to update this. Have you considered checking the CLI option higher up in the stack?

Comment (DanielleMaywood) [reply cli/cliui/cliui.go:69]: I absolutely agree with you, however serpent doesn't (from what I can tell) have any way to support this as it lacks the ability to set a middleware that runs before _any_ command.

To demonstrate what I, the code in [this gist](https://gist.github.com/DanielleMaywood/6421e8aa48a160e23d5ddb84093c37c1) has a `Middleware` setup but it only runs on the root cmd and not it's children. If you know of a way to have this run before a commands handler but after options are setup I'd love to do that instead!

Comment (DanielleMaywood) [reply cli/cliui/cliui.go:69]: Scratch that: I think using `rootCmd.Walk` and injecting the middleware to every child should work? Will have a go at doing that.

Comment (DanielleMaywood) [reply cli/cliui/cliui.go]: I've pushed a change that should be less janky, let me know what you think!

**Comment by DanielleMaywood** [comment]
I've ripped out all the logic for `--no-color` as mutating `DefaultStyles` whilst the program is running causes a race condition that is non-trivial to solve due to using `DefaultStyles` around 150 times in the codebase. The behaviour can still be enabled by setting the `NO_COLOR` (https://no-color.org/) environment variable by using termenv's `EnvColorProfile` instead of `ColorProfile`.

File: cmd/cliui/main.go [hunk 10]
```diff
@@ -37,6 +38,43 @@ func main() {
 		},
 	}
 
+	root.Children = append(root.Children, &serpent.Command{
+		Use: "colors",
```
Comment (ammario) [inline cmd/cliui/main.go:42]: This should be hidden

File: cmd/cliui/main.go [hunk 11]
```diff
@@ -37,6 +38,43 @@ func main() {
...
+		Handler: func(inv *serpent.Invocation) error {
+			msg := pretty.Sprint(cliui.DefaultStyles.Code, "This is a code message")
+			_, _ = fmt.Fprintln(inv.Stdout, msg)
```
Comment (ammario) [inline cmd/cliui/main.go:45]: You can simplify this with `pretty.Fprintf`

**Review by ammario — CHANGES_REQUESTED** [review]

File: cli/cliui/cliui.go (hunk 9 above)
Comment (ammario) [reply cli/cliui/cliui.go]: If you do the Walk approach we have the flag duplicated on every help, which is obnoxious. Can't you use an Option on the root command?

File: cmd/cliui/main.go (hunk 10 above)
Comment (DanielleMaywood) [reply cmd/cliui/main.go]: Done!

File: cmd/cliui/main.go (hunk 11 above)
Comment (DanielleMaywood) [reply cmd/cliui/main.go]: Done! I had to separate the newline from the Fprintf call though as otherwise the newline would get themed.

**Review by ammario — APPROVED** [review]
Should prob only merge when one of the core devs approve. I generally don't want to take accountability as a review since my knowledge of the internals has atrophied.

File: cli/cliui/cliui.go [hunk 12]
```diff
@@ -37,17 +37,21 @@ var (
...
+	white         = Color("7")
+	brightBlue    = Color("12")
+	brightMagenta = Color("13")
 )
 
 // Color returns a color for the given string.
 func Color(s string) termenv.Color {
 	colorOnce.Do(func() {
-		color = termenv.NewOutput(os.Stdout).ColorProfile()
+		color = termenv.NewOutput(os.Stdout).EnvColorProfile()
```
Comment (mafredri) [inline cli/cliui/cliui.go:53]: Good solution for disabling colors 👍🏻

**Review by mafredri — APPROVED** [review]
Looks great. I think relying on ansi colors where we don't use a background, and hex colors where we do, is indeed the simplest approach.

Thanks for working through all the iterations of this and glad we could land on a simple solution in the end. 👍🏻
