### PR TITLE
fix: remove error log when notification manager is already closed

### LINKED ISSUE #677: flake: TestRunStopRace
Seems like a shutdown problem seen [here](https://github.com/coder/coder/commit/63adfa57bd6a9c9f3e526fadd90d01a1a052d156/checks)
```

=== RUN   TestRunStopRace
=== PAUSE TestRunStopRace
=== CONT  TestRunStopRace
    t.go:106: 2025-06-03 19:52:21.574 [debu]  pubsub: pubsub dialing postgres  network=tcp  address=127.0.0.1:5432  timeout_ms=0
    t.go:106: 2025-06-03 19:52:21.575 [debu]  pubsub: pubsub postgres TCP connection established  network=tcp  address=127.0.0.1:5432  timeout_ms=0  elapsed_ms=0
    t.go:106: 2025-06-03 19:52:21.580 [debu]  pubsub: pubsub connected to postgres
    t.go:106: 2025-06-03 19:52:21.580 [debu]  pubsub: pubsub has started
    t.go:106: 2025-06-03 19:52:21.581 [debu]  notifications-manager: notification manager started
    t.go:106: 2025-06-03 19:52:21.581 [debu]  notifications-manager: graceful stop requested
    t.go:106: 2025-06-03 19:52:21.581 [debu]  notifications-manager: notification manager stopped
    t.go:115: 2025-06-03 19:52:21.581 [erro]  notifications-manager: notification manager stopped with error ...
        error= manager already closed:
                   github.com/coder/coder/v2/coderd/notifications.(*Manager).loop
                       /home/runner/work/coder/coder/coderd/notifications/manager.go:166
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
    t.go:106: 2025-06-03 19:52:21.581 [debu]  pubsub: pubsub closed
--- FAIL: TestRunStopRace (0.17s)
```

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes https://github.com/coder/internal/issues/677

Resolves flakes such as:

```
$ go test -race -run "TestRunStopRace" github.com/coder/coder/v2/coderd/notifications -count=10000 -parallel $(nproc)
--- FAIL: TestRunStopRace (0.00s)
    t.go:106: 2025-06-06 02:44:39.348 [debu]  notifications-manager: notification manager started
    t.go:106: 2025-06-06 02:44:39.348 [debu]  notifications-manager: graceful stop requested
    t.go:106: 2025-06-06 02:44:39.348 [debu]  notifications-manager: notification manager stopped
    t.go:115: 2025-06-06 02:44:39.348 [erro]  notifications-manager: notification manager stopped with error ...
        error= manager already closed:
                   github.com/coder/coder/v2/coderd/notifications.(*Manager).loop
                       /home/coder/coder/coderd/notifications/manager.go:166
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
--- FAIL: TestRunStopRace (0.00s)
    t.go:106: 2025-06-06 02:44:41.632 [debu]  notifications-manager: notification manager started
    t.go:106: 2025-06-06 02:44:41.632 [debu]  notifications-manager: graceful stop requested
    t.go:106: 2025-06-06 02:44:41.632 [debu]  notifications-manager: notification manager stopped
    t.go:115: 2025-06-06 02:44:41.633 [erro]  notifications-manager: notification manager stopped with error ...
        error= manager already closed:
                   github.com/coder/coder/v2/coderd/notifications.(*Manager).loop
                       /home/coder/coder/coderd/notifications/manager.go:166
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
FAIL
FAIL    github.com/coder/coder/v2/coderd/notifications  6.847s
FAIL
```

These error logs are caused as a result of the `Manager` `Run` start operation being asynchronous. In the flaking test case we immediately call `Stop` after `Run`. It's possible for `Stop` to be scheduled to completion before the goroutine spawned by `Run` calls `loop` and checks `closed`. If this happens, `loop` returns an error and produces the error log.

We'll address this by replacing this specific error log with a warning log.

```
$ go test -run "TestRunStopRace" github.com/coder/coder/v2/coderd/notifications -count=10000 -parallel $(nproc)
ok      github.com/coder/coder/v2/coderd/notifications  1.294s

$ go test -race github.com/coder/coder/v2/coderd/notifications -count=100 -parallel $(nproc)
ok      github.com/coder/coder/v2/coderd/notifications  26.525s
```

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#18264** <a href="https://app.graphite.dev/github/pr/coder/coder/18264?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/18264?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: coderd/notifications/manager.go [hunk 1]
```diff
@@ -161,11 +160,6 @@ func (m *Manager) loop(ctx context.Context) error {
 	}()
 
 	m.mu.Lock()
-	if m.closed {
-		m.mu.Unlock()
-		return xerrors.New("manager already closed")
```
Comment (ethanndickson) [inline coderd/notifications/manager.go:166]: I personally don't think we need to guard against improper API usage, where `Run` is explicitly called after `Stop`, but I'm not completely opposed to the idea of dropping an error log if that happens, if that was the original intention here.

One alternative solution I considered was adding a `started` channel that gets closed by `loop`, then we could modify `Run` to block until the notifier loop has actually started. I opted against this cause I didn't want to add a fourth lifecycle value to the manager.

Comment (mafredri) [reply coderd/notifications/manager.go:166]: This change may cause `Stop` to grab the mutex first, checks `m.notifier = nil` and unlocks. Then this code-path locks, assigns `m.notifier` and executes `m.notifier.run`. The `m.notifier.stop` is never called.

Can't we just enable the slog ignore errors option for the failing test, or change the `m.log.Error` to warning/debug instead?

Comment (ethanndickson) [reply coderd/notifications/manager.go:166]: Ahh 💩, my bad.

I don't like the sound of ignoring all error logs for the test, and I think the manager stopping unexpectedly should produce an error log, so I'll change the specific `manager already closed` error to a warning log.

**Review by mafredri — APPROVED** [review]
