### PR TITLE
fix(site): display correct user_limit on license ui

### LINKED ISSUE #7671: License UI incorrectly show the user count
Version: [`v0.23.5+ef2411e`](https://github.com/coder/coder/commit/ef2411ef1709ca2e9577bc6294c2edbd9b3a0ec1)

An existing license (called 10) has 5 users.

I added a second license (called 11) with 150 users.

The UI shows two licenses with 150 users.

image

Here is trimmed down `coder licenses list` where you see the 5 and 150 user count

```  {
    "id": 10,
    "uploaded_at": "2023-04-07T11:54:33.532829-05:00",
    "claims": {
      "all_features": true,
      "exp": 1712422415,
      "features": {
        "user_limit": 5
      },
      "license_expires": 1712422415
      "version": 3
    }
  },
  {
    "id": 11,
    "uploaded_at": "2023-05-24T16:16:19.725302-05:00",
    "claims": {
      "all_features": true,
      "exp": 1717286400,
      "features": {
        "user_limit": 150
      },
      "license_expires": 1717286400,
      "version": 3
    }
  }
]

### PR DESCRIPTION
**Pull request by rodrimaia**
Fixes #7671 

So, when the license UI was created, we used to have a bug on the backend that would return each license's user_limit as the same as the maximum number of users allowed on all licenses. For that reason we only displayed that max value. The bug was fixed, but we never updated the UI to display the correct value of each license. This PR fixes that.

### CODE REVIEW

File: site/src/components/LicenseCard/LicenseCard.tsx [hunk 1]
```diff
@@ -30,6 +30,9 @@ export const LicenseCard = ({
     number | undefined
   >(undefined)
 
+  const currentUserLimit =
+    license.claims.features["user_limit"] || userLimitLimit
```
Comment (mtojek) [inline site/src/components/LicenseCard/LicenseCard.tsx:34]: This is probably out of scope of this PR, but `userLimitLimit` sounds weird.

File: site/src/components/LicenseCard/LicenseCard.tsx [hunk 2]
```diff
@@ -72,7 +75,7 @@ export const LicenseCard = ({
           <Stack direction="column" spacing={0} alignItems="center">
             <span className={styles.secondaryMaincolor}>Users</span>
             <span className={styles.userLimit}>
-              {userLimitActual} {` / ${userLimitLimit || "Unlimited"}`}
+              {userLimitActual} {` / ${currentUserLimit || "Unlimited"}`}
```
Comment (mtojek) [inline site/src/components/LicenseCard/LicenseCard.tsx:78]: Should we move the condition `|| "Unlimited"` to `currentUserLimit`?

File: site/src/components/LicenseCard/LicenseCard.tsx [hunk 3]
```diff
@@ -82,7 +85,7 @@ export const LicenseCard = ({
             width="134px" // standardize width of date column
           >
             {compareAsc(
-              new Date(license.claims.license_expires * 1000),
+              new Date((license.claims.license_expires as number) * 1000),
```
Comment (mtojek) [inline site/src/components/LicenseCard/LicenseCard.tsx:88]: Can we make the conversion to number in a single place above?

File: site/src/components/LicenseCard/LicenseCard.tsx [hunk 4]
```diff
@@ -30,6 +30,9 @@ export const LicenseCard = ({
     number | undefined
   >(undefined)
 
+  const currentUserLimit =
```
Comment (mtojek) [inline site/src/components/LicenseCard/LicenseCard.tsx:33]: Should we add some unit tests to make sure that we present the correct licensing info?

**Review by mtojek — COMMENTED** [review]
Could you please describe in the issue description what is the root cause of the problem?

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.tsx:78]: I personally would rather not doing it since the user limit is a number and here we are dealing with "presentational" logic

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.tsx:34]: I find it weird as well

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 3 above)
Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.tsx:88]: If the license_expires is not always a number I'm wondering if we should care about the other types it can be 🤔. Do you know what is the case when it is not a number?

**Review by BrunoQuaresma — COMMENTED** [review]
Just small things that @mtojek already mentioned

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 2 above)
Comment (mtojek) [reply site/src/components/LicenseCard/LicenseCard.tsx:78]: Killer argument 👍

**Comment by rodrimaia** [comment]
> Could you please describe in the issue description what is the root cause of the problem?

So, when the license UI was created, we used to have a bug on the backend that would return each license's user_limit as the same as the maximum number of users allowed on all licenses. For that reason we only displayed that max value. The bug was fixed, but we never updated the UI to display the correct value of each license. This PR fixes that.

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 4 above)
Comment (rodrimaia) [reply site/src/components/LicenseCard/LicenseCard.tsx:33]: fixed.

File: site/src/components/LicenseCard/LicenseCard.tsx (hunk 3 above)
Comment (rodrimaia) [reply site/src/components/LicenseCard/LicenseCard.tsx]: type enforced to be a `number`

File: site/src/api/api.ts [hunk 5]
```diff
@@ -1006,7 +1006,7 @@ export const getWorkspaceBuildParameters = async (
   return response.data
 }
 type Claims = {
-  license_expires?: number
+  license_expires: number
```
Comment (BrunoQuaresma) [inline site/src/api/api.ts:1009]: Is this type not returned from the typesGenerated.ts? Usually, the API endpoints and resources have generated types that are more trustable.

**Review by BrunoQuaresma — APPROVED** [review]
Just one minor thing.

File: site/src/components/LicenseCard/LicenseCard.test.tsx [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+        userLimitLimit={10}
+        onRemove={() => null}
+        isRemoving={false}
+      />,
+    )
+
+    // Then
+    await screen.findByText("#1")
+    await screen.findByText("1 / 10")
+    await screen.findByText("Enterprise")
```
Comment (mtojek) [inline site/src/components/LicenseCard/LicenseCard.test.tsx:22]: It doesn't make sense to look at the entire screen for `#1` as I'm sure that you will find something else. Same for Enterprise. Could we limit it only to the rendered element?

**Review by mtojek — CHANGES_REQUESTED** [review]

File: site/src/components/LicenseCard/LicenseCard.test.tsx (hunk 6 above)
Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: I think this is ok and a common practice for JS tests when using react testing library

Comment (mtojek) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: The practice is fine, but we should limit it to the element under tests.

Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: I mean it is safe because if the matcher finds it in multiple elements, it will raise an error.

Comment (mtojek) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: What if it finds a static label placed somewhere else on the page, and our license card didn't render at all?

Comment (BrunoQuaresma) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: The storybook should get that. IMO, integration tests should be used to catch network and "actionable" things. Check if things are rendered correctly should be on Storybook but I get your point.

**Review by mtojek — APPROVED** [review]
I left some comments, but defer the final decision to Bruno as frontend expert.

File: site/src/components/LicenseCard/LicenseCard.test.tsx (hunk 6 above)
Comment (rodrimaia) [reply site/src/components/LicenseCard/LicenseCard.test.tsx:22]: it is usually a recommendation to use `screen`: https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen

And also in this case we are only rendering the component, there isn't anything else in the screen that could be matched. I have printed the result of a `screen.debug()` and this is the result: 

```      
<body>
        <div>
          <div
            class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation2 makeStyles-licenseCard-27 css-19zg6r2-MuiPaper-root"
          >
            <div
              class="makeStyles-stack-39 makeStyles-stack-40  makeStyles-cardContent-28"
            >
              <span
                class="makeStyles-licenseId-29"
              >
                #
                1
              </span>
              <span
                class="makeStyles-accountType-30"
              >
                Enterprise
              </span>
              <div
                class="makeStyles-stack-39 makeStyles-stack-41"
                style="flex: 1;"
              >
                <div
                  class="makeStyles-stack-39 makeStyles-stack-42"
                >
                  <span
                    class="makeStyles-secondaryMaincolor-33"
                  >
                    Users
                  </span>
                  <span
                    class="makeStyles-userLimit-26"
                  >
                    1

                     / Unlimited
                  </span>
                </div>
                <div
                  class="makeStyles-stack-39 makeStyles-stack-43"
                  width="134px"
                >
                  <span
                    class="makeStyles-secondaryMaincolor-33"
                  >
                    Valid Until
                  </span>
                  <span
                    class="makeStyles-licenseExpires-31"
                  >
                    May 20, 2078
                  </span>
                </div>
                <div
                  class="makeStyles-stack-39 makeStyles-stack-44"
                >
                  <button
                    class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textNeutral MuiButton-sizeSmall MuiButton-textSizeSmall MuiButton-root MuiButton-text MuiButton-textNeutral MuiButton-sizeSmall MuiButton-textSizeSmall makeStyles-removeButton-34 css-1sr08q4-MuiButtonBase-root-MuiButton-root"
                    tabindex="0"
                    type="button"
                  >
                    Remove
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
```

as you can see, just the component is being rendered.
