### PR TITLE
fix: handle `getUser` error

### LINKED ISSUE #3088: Fix error messages in authXService
Problem: some error messages supplied by the backend are not displayed on the frontend, and in order to fix that in all XServices, we need a plan.

Definition of done:
- All error messages coming from the authXService show backend error messages if they are present, otherwise a fallback message
- The team is happy with the implementation (naming, placement of function calls) for this PR so that it can be used as a template for future PRs in this epic

### PR DESCRIPTION
**Pull request by AbhineetJain**
Building on #3241, this PR handles the `getUser` error from `authXService`.

Special criteria: The error is only shown when redirecting to the `/login` page from a page other than `/`. It is also not shown when loading the `/login` page directly. 

## Subtasks

- [x] show `getUser` error above the Sign-in form
- [x] restrict showing the error only when redirecting (except redirecting from `/`)
- [x] added stories
- [x] update relevant backend API middleware errors to have the a `You are signed out.` or `An internal error occurred` message and move the details in the error details section.

Fixes #3088 

## Screenshot

Screen Shot 2022-07-28 at 11 14 29 PM

### CODE REVIEW

File: coderd/httpmw/apikey.go [hunk 1]
```diff
@@ -51,6 +51,8 @@ type OAuth2Configs struct {
 	Github OAuth2Config
 }
 
+const loggedOutErrorMessage string = "You are logged out. Please log in to continue."
```
Comment (deansheather) [inline coderd/httpmw/apikey.go]: "You are logged out or your session has expired. Please log in again to continue."

Comment (AbhineetJain) [reply coderd/httpmw/apikey.go]: Much better. Thank you!

**Review by johnstcn — APPROVED** [review]

File: coderd/httpmw/apikey.go [hunk 2]
```diff
@@ -216,7 +225,8 @@ func ExtractAPIKey(db database.Store, oauth *OAuth2Configs, redirectToLogin bool
 				})
 				if err != nil {
 					write(http.StatusInternalServerError, codersdk.Response{
-						Message: fmt.Sprintf("API key couldn't update: %s.", err.Error()),
+						Message: signedOutErrorMessage,
```
Comment (mafredri) [inline coderd/httpmw/apikey.go:228]: I don't think this error message should say logged out; an internal error happened and we don't know what's wrong, it could be a temporary error like database is down/restarting and the problem could go away after a while (not requiring any action from the user). Another issue is that no matter how many times the user tries to login -- it won't work, which would lead to a bad user experience.

Something like: "Try again or contact the system administrator" could work here `¯\_(ツ)_/¯`.

**Review by mafredri — APPROVED** [review]
I'd like to see the 500 error changed, but other than that, backend looks good. 👍🏻

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 3]
```diff
@@ -28,19 +28,25 @@ export const useStyles = makeStyles((theme) => ({
...
+
 export const LoginPage: React.FC = () => {
   const styles = useStyles()
   const location = useLocation()
   const xServices = useContext(XServiceContext)
   const [authState, authSend] = useActor(xServices.authXService)
   const isLoading = authState.hasTag("loading")
   const redirectTo = retrieveRedirect(location.search)
+  const locationState = location.state ? (location.state as LocationState) : null
+  const isRedirected = locationState !== null ? locationState.isRedirect : false
```
Comment (Kira-Pilot) [inline site/src/pages/LoginPage/LoginPage.tsx:43]: Can you simplify like:
```suggestion
  const isRedirected = !locationState ? locationState.isRedirect : false
```
Or are we using `null` for a reason?

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 4]
```diff
@@ -28,19 +28,25 @@ export const useStyles = makeStyles((theme) => ({
...
+}
+
 export const LoginPage: React.FC = () => {
   const styles = useStyles()
   const location = useLocation()
   const xServices = useContext(XServiceContext)
   const [authState, authSend] = useActor(xServices.authXService)
   const isLoading = authState.hasTag("loading")
   const redirectTo = retrieveRedirect(location.search)
+  const locationState = location.state ? (location.state as LocationState) : null
```
Comment (Kira-Pilot) [inline site/src/pages/LoginPage/LoginPage.tsx:42]: Do we need to use a ternary because of types? Or can we:
```suggestion
  const locationState = location.state ??  null
```

**Review by Kira-Pilot — APPROVED** [review]
FE looks great!

File: site/src/pages/LoginPage/LoginPage.tsx (hunk 4 above)
Comment (AbhineetJain) [reply site/src/pages/LoginPage/LoginPage.tsx:42]: `location.state` can be `null`, but since we are typecasting it, the compiler thinks it is never `null`, so we are typecasting it only if it is not null.

File: site/src/pages/LoginPage/LoginPage.tsx (hunk 3 above)
Comment (AbhineetJain) [reply site/src/pages/LoginPage/LoginPage.tsx:43]: Yes, I think I can just use `locationState`.

File: site/src/components/RequireAuth/RequireAuth.tsx [hunk 5]
```diff
@@ -13,9 +13,10 @@ export const RequireAuth: React.FC<RequireAuthProps> = ({ children }) => {
   const xServices = useContext(XServiceContext)
   const [authState] = useActor(xServices.authXService)
   const location = useLocation()
-  const navigateTo = location.pathname === "/" ? "/login" : embedRedirect(location.pathname)
+  const isHomePage = location.pathname === "/"
+  const navigateTo = isHomePage ? "/login" : embedRedirect(location.pathname)
   if (authState.matches("signedOut")) {
-    return <Navigate to={navigateTo} />
+    return <Navigate to={navigateTo} state={{ isRedirect: !isHomePage }} />
```
Comment (presleyp) [inline site/src/components/RequireAuth/RequireAuth.tsx:19]: does `isRedirect` replicate the functionality of `embedRedirect`?

Comment (presleyp) [reply site/src/components/RequireAuth/RequireAuth.tsx:19]: I think we *could* use one both to know whether to show the error and where to go next, but it might be better to keep them separate like this

**Review by presleyp — APPROVED** [review]

File: site/src/components/RequireAuth/RequireAuth.tsx (hunk 5 above)
Comment (AbhineetJain) [reply site/src/components/RequireAuth/RequireAuth.tsx:19]: Yeah, we’d probably have to retrieve the redirect in the component but that didn’t seem like a very solid approach.
