### PR TITLE
fix: use database for user creation to prevent flake

### LINKED ISSUE #10978: flake:  TestPaginatedUsers
```
=== Failed
=== FAIL: coderd TestPaginatedUsers/all_users_5 (50.00s)
    users_test.go:1865: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1865
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=5&offset=20&q=": context deadline exceeded
        	Test:       	TestPaginatedUsers/all_users_5
        	Messages:   	prev page

=== FAIL: coderd TestPaginatedUsers/username_search_3#01 (50.00s)
    users_test.go:1865: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1865
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=3&offset=21&q=specialuser": context deadline exceeded
        	Test:       	TestPaginatedUsers/username_search_3#01
        	Messages:   	prev page

=== FAIL: coderd TestPaginatedUsers/username_search_3 (50.01s)
    users_test.go:1865: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1865
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=3&offset=21&q=specialuser": context deadline exceeded
        	Test:       	TestPaginatedUsers/username_search_3
        	Messages:   	prev page

=== FAIL: coderd TestPaginatedUsers/all_users_3 (50.01s)
    users_test.go:1847: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1847
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=3&offset=21&q=": context deadline exceeded
        	Test:       	TestPaginatedUsers/all_users_3
        	Messages:   	next offset page

=== FAIL: coderd TestPaginatedUsers/gmail_search_3 (50.00s)
    users_test.go:1847: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1847
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=3&offset=24&q=gmail": context deadline exceeded
        	Test:       	TestPaginatedUsers/gmail_search_3
        	Messages:   	next offset page

=== FAIL: coderd TestPaginatedUsers/all_users_10 (50.06s)
    users_test.go:1865: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1865
        	            				/home/runner/actions-runner/_work/coder/coder/coderd/users_test.go:1795
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:38403/api/v2/users?limit=10&offset=40&q=": context deadline exceeded
        	Test:       	TestPaginatedUsers/all_users_10
        	Messages:   	prev page

=== FAIL: coderd TestPaginatedUsers (5.64s)
```

full logs: https://github.com/coder/coder/runs/19210857200

### PR DESCRIPTION
**Pull request by f0ssel**
After speaking with @Emyrk I moved the user creation of these tests to use the database directly to speed things up and do less http requests in order to stay under the 50 second timeout. 

Closes https://github.com/coder/coder/issues/10978

### CODE REVIEW

**Comment by f0ssel** [comment]
Talked with @Emyrk and I'm gonna take a stab at speeding this test up, he had some ideas here.

**Comment by f0ssel** [comment]
I looked at the test data in CI and interestingly this test averages very fast, despite the comments in the code saying otherwise. 
image

That being said, I still think if we are timing out at 50 seconds something on the CI box is running out of resources, and moving this to the database will still reduce the test startup burden for this test.

File: coderd/users_test.go [hunk 1]
```diff
@@ -1817,7 +1813,11 @@ func assertPagination(ctx context.Context, t *testing.T, client *codersdk.Client
 		},
 	}))
 	require.NoError(t, err, "first page")
-	require.Equalf(t, page.Users, allUsers[:limit], "first page, limit=%d", limit)
+	for i := range allUsers[:limit] {
+		require.Equalf(t, page.Users[i].Username, allUsers[i].Username, "first page, limit=%d", limit)
+	}
```
Comment (Emyrk) [inline coderd/users_test.go:1818]: I think the original comparisons are better since the new comparisons fail at the first instance, and do not show the lists and the list lengths in the failure output. Switching to `assert` feels like it might be spammy.

Can we just make a test helper func like:
```golang
func onlyUsernames[U codersdk.User | database.User](users []U) []string {
	var out []string
	for _, u := range users {
		switch u := (any(u)).(type) {
		case codersdk.User:
			out = append(out, u.Username)
		case database.User:
			out = append(out, u.Username)
		}
	}
	return out
}
```

Then we can bring back the old requires.
```golang
require.Equalf(t, onlyUsernames(page.Users), onlyUsernames(allUsers[:limit]), "first page, limit=%d", limit)
```

**Review by Emyrk — COMMENTED** [review]
This is probably a good amount faster :+1:

File: coderd/users_test.go (hunk 1 above)
Comment (Emyrk) [reply coderd/users_test.go]: It's a bit of a hack since I cast to `any` in the function :smile: 

It just gives type safety on the call arguments.

**Review by Emyrk — APPROVED** [review]

**Comment by Emyrk** [comment]
> I looked at the test data in CI and interestingly this test averages very fast, despite the comments in the code saying otherwise.

This is definitely subjective, but I think >100ms is on the slower side for our tests. Is it something to be concerned about? Idk, probably not.
