### PR TITLE
fix: ensure user admins can always see users table

### LINKED ISSUE #15212: User Admin can't view the /deployment/users page
I have a user that has role `User Admin` (and `Template Admin` if that matters).

When I try to view the `/deployment/users` page, it responds

> **Forbidden.**
> Please check the developer console for more details.

In the browser dev tools, I can see that requests to 

* `/api/v2/deployment/config` and
* `/api/v2/deployment/stats`

are both coming back 403 Forbidden.

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #15212

## Changes made
- Updated logic so that proxy config is only requested when appropriate, instead of for all users on all deployment pages
- Split up the main context provider for the `/deployment` and `/organizations` routes, and updated layout logic for `ManagementSettingsLayout` layout component. This ensures the sidebar is always visible, even if request errors happen
- Added additional routing safeguards to make sure that even if a user can view one page in the deployment section, they won't be able to navigate directly to any arbitrary deployment page
- Updated logic for sidebar navigation to ensure that nav items only appear when the user truly has permission
- Centralized a lot of the orgs logic into the `useAuthenticated` hook
- Added additional check cases to the `permissions.tsx` file, to give more granularity, and added missing type-checking
- Extended the API for the `RequirePermissions` component to let it redirect users anywhere
- Updated some of our testing setup files to ensure that types were defined correctly

### CODE REVIEW

File: site/src/contexts/auth/permissions.tsx [hunk 1]
```diff
@@ -116,7 +126,6 @@ export const permissionsToCheck = {
 	[checks.viewAnyGroup]: {
 		object: {
 			resource_type: "group",
-			org_id: "any",
```
Comment (Parkreiner) [inline site/src/contexts/auth/permissions.tsx:119]: Ended up deleting this because the property wasn't compatible. It also didn't seem to be used anywhere

@Emyrk Not sure if we should update the types so that this can be added back

File: site/src/modules/management/ManagementSettingsLayout.tsx [hunk 2]
```diff
@@ -48,61 +47,128 @@ export const canEditOrganization = (
 	);
 };
 
+const isManagementRoutePermitted = (
```
Comment (Parkreiner) [inline site/src/modules/management/ManagementSettingsLayout.tsx:50]: Long function, but I really wanted to make sure that users couldn't access pages that they shouldn't be able to

The previous logic was set up so that if a user could view the deployments page at all, they would be able to update the URL and jump to any page. Felt like we needed something more strict than just hiding navigation options in the sidebar

File: site/src/modules/management/ManagementSettingsLayout.tsx [hunk 3]
```diff
@@ -1,28 +1,27 @@
...
 import { useDashboard } from "modules/dashboard/useDashboard";
 import { type FC, Suspense, createContext, useContext } from "react";
 import { useQuery } from "react-query";
-import { Outlet, useParams } from "react-router-dom";
+import { Outlet, useLocation } from "react-router-dom";
 import { Sidebar } from "./Sidebar";
 
+type ManagementSettingsValue = Readonly<{
+	deploymentValues: DeploymentConfig | undefined;
+}>;
```
Comment (Parkreiner) [inline site/src/modules/management/ManagementSettingsLayout.tsx:19]: Removed most of the properties for two reasons:
1. The `Sidebar` component depended on the context provider. So it was impossible to show the sidebar at all times, because if you moved it outside the provider, it would blow up
2. It's duplicate state that was already accessible via other hooks. Felt better to beef those up, because then other pages would be able to benefit, too

File: site/src/modules/management/SidebarView.tsx [hunk 4]
```diff
@@ -130,10 +126,11 @@ const DeploymentSettingsNavigation: FC<DeploymentSettingsNavigationProps> = ({
 					{permissions.viewDeploymentValues && (
 						<SidebarNavSubItem href="network">Network</SidebarNavSubItem>
 					)}
-					{/* All users can view workspace regions.  */}
```
Comment (Parkreiner) [inline site/src/modules/management/SidebarView.tsx:133]: This actually wasn't true, so Steven and I had to put this behind a condition

File: site/src/router.tsx [hunk 5]
```diff
@@ -426,6 +426,23 @@ export const router = createBrowserRouter(
...
+					 * 2. If the user has access to some deployment pages, but
+					 *    tries accessing one that they shouldn't be able to
+					 *    access, we have to reroute them somewhere. The base
+					 *    deployment route is the only safe option, because not
+					 *    even the general page is accessible by everyone.
+					 *
+					 * Should update the base /deployment page so that there's
+					 * something there, but that will require coordination with
+					 * the design team.
+					 */}
```
Comment (Parkreiner) [inline site/src/router.tsx:445]: I really wish I could've added some content here, but it felt really out of scope. At the very least, better a janky experience over a broken one

**Comment by Parkreiner** [comment]
Will look into the failing E2E tests first thing tomorrow morning

File: site/src/contexts/auth/permissions.tsx (hunk 1 above)
Comment (Emyrk) [reply site/src/contexts/auth/permissions.tsx:119]: Can you delete this unused check then?

Comment (Parkreiner) [reply site/src/contexts/auth/permissions.tsx:119]: Oh, sorry – I meant that the `org_id` property specifically didn't seem to be used anywhere

File: site/src/contexts/auth/RequirePermission.tsx [hunk 6]
```diff
@@ -3,18 +3,20 @@ import { Navigate } from "react-router-dom";
 
 export interface RequirePermissionProps {
 	children?: ReactNode;
-	isFeatureVisible: boolean;
+	permitted: boolean;
+	unpermittedRedirect?: `/${string}`;
```
Comment (BrunoQuaresma) [inline site/src/contexts/auth/RequirePermission.tsx:7]: Nit: Maybe `redirectOnFailure`?

**Review by BrunoQuaresma — APPROVED** [review]
I didn’t find any concerns, so I’m approving it. It would be good to have someone else do a second check and QA.

File: site/src/router.tsx (hunk 5 above)
Comment (BrunoQuaresma) [reply site/src/router.tsx:445]: Maybe something to think together with @chrifro

File: site/src/modules/management/ManagementSettingsLayout.tsx (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/modules/management/ManagementSettingsLayout.tsx:50]: Maybe extract this into an util and add specific tests to it?

Comment (Parkreiner) [reply site/src/modules/management/ManagementSettingsLayout.tsx:50]: Yeah, I can do that really quickly

**Comment by Parkreiner** [comment]
@aslilac Would you be able to do a second glance-over for this PR? Like a third of the total lines of code is just a new unit test file; there weren't huge swashes of changes

**Review by Emyrk — APPROVED** [review]
Permissions LG. @Parkreiner and I did them in discord together :+1:

**Comment by aslilac** [comment]
pls don't merge yet, I'm still reviewing

File: site/jest.setup.ts [hunk 7]
```diff
@@ -48,9 +48,7 @@ global.ResizeObserver = require("resize-observer-polyfill");
 // Polyfill the getRandomValues that is used on utils/random.ts
 Object.defineProperty(global.self, "crypto", {
 	value: {
-		getRandomValues: function (buffer: Buffer) {
-			return crypto.randomFillSync(buffer);
-		},
+		getRandomValues: (b: NodeJS.ArrayBufferView) => crypto.randomFillSync(b),
```
Comment (aslilac) [inline site/jest.setup.ts:51]: you could even take this a step further and just say...

```suggestion
		getRandomValues: crypto.randomFillSync,
```

File: site/src/contexts/auth/permissions.tsx [hunk 8]
```diff
@@ -11,13 +13,17 @@ export const checks = {
...
 	createOrganization: "createOrganization",
 	editAnyOrganization: "editAnyOrganization",
 	viewAnyGroup: "viewAnyGroup",
 	createGroup: "createGroup",
 	viewAllLicenses: "viewAllLicenses",
-} as const;
+	viewNotificationTemplate: "viewNotificationTemplate",
+} as const satisfies Record<string, string>;
+
+type PermissionType = keyof typeof checks;
```
Comment (aslilac) [inline site/src/contexts/auth/permissions.tsx:26]: this is technically incorrect, and only working because all of the key value pairs are symmetrical. what you really want is...

```suggestion
type PermissionType = typeof checks[keyof typeof checks];
```

File: site/src/modules/management/ManagementSettingsLayout.tsx [hunk 9]
```diff
@@ -48,61 +47,134 @@ export const canEditOrganization = (
 	);
 };
 
+export const isManagementRoutePermitted = (
```
Comment (aslilac) [inline site/src/modules/management/ManagementSettingsLayout.tsx:50]: yeah, this feels like total overkill to me, especially for a quick patch this is a _huge_ departure from how we handle this sort of thing everywhere else in the app

**Review by aslilac — CHANGES_REQUESTED** [review]
I'm not a fan of moving state that can be localized up to a global provider where it will never be useful. I agree that the state currently being handled by `ManagementSettingsLayout` needs to be split back into two separate providers, but we shouldn't do it by misusing an existing provider, we should just reintroduce a `DeploymentSettingsProvider`.

File: site/src/contexts/auth/RequirePermission.tsx [hunk 10]
```diff
@@ -3,18 +3,20 @@ import { Navigate } from "react-router-dom";
...
 export const RequirePermission: FC<RequirePermissionProps> = ({
 	children,
-	isFeatureVisible,
+	permitted,
+	unpermittedRedirect = "/workspaces",
 }) => {
-	if (!isFeatureVisible) {
-		return <Navigate to="/workspaces" />;
+	if (!permitted) {
+		return <Navigate to={unpermittedRedirect} replace />;
```
[the remark this answers is not in the document]
Comment (Parkreiner) [reply site/src/contexts/auth/RequirePermission.tsx:19]: No, that's a really fair call. I wouldn't be opposed to ripping this out, since the abstraction is so shallow

**Comment by Parkreiner** [comment]
@aslilac This should be good to go, but I got sloppy. Let me know if you'd rather just reopen your draft PR, just to be on the super-safe side

I'll be looking at GitHub later tonight to try getting either one of the PRs merged in

File: site/src/pages/DeploymentSettingsPage/NotificationsPage/NotificationsPage.tsx [hunk 11]
```diff
@@ -30,10 +29,12 @@ export const NotificationsPage: FC = () => {
...
 	});
-	const ready =
-		templatesByGroup.data && dispatchMethods.data && deploymentValues;
-	const tab = searchParams.get("tab") || "events";
+	const tabState = useSearchParamsKey({
+		key: "tab",
+		defaultValue: "events",
+	});
 
+	const ready = !!(templatesByGroup.data && dispatchMethods.data);
```
Comment (aslilac) [inline site/src/pages/DeploymentSettingsPage/NotificationsPage/NotificationsPage.tsx:37]: nit: prefer `Boolean(…)` over `!!(…)`, it makes it much clearer that you want a boolean cast

File: site/src/pages/ManagementSettingsPage/OrganizationProvisionersPage.tsx [hunk 12]
```diff
@@ -16,13 +16,10 @@ const OrganizationProvisionersPage: FC = () => {
...
 	const { organizations } = useManagementSettings();
 	const { entitlements } = useDashboard();
-
 	const { metadata } = useEmbeddedMetadata();
 	const buildInfoQuery = useQuery(buildInfo(metadata["build-info"]));
 
-	const organization = organizations
-		? getOrganizationByName(organizations, organizationName)
-		: undefined;
+	const organization = organizations?.find((o) => o.name === organizationName);
```
Comment (aslilac) [inline site/src/pages/ManagementSettingsPage/OrganizationProvisionersPage.tsx:22]: oh, this should probably just be using the organization specified by `useManagementSettings`

File: site/src/pages/ManagementSettingsPage/OrganizationSettingsPage.tsx [hunk 13]
```diff
@@ -55,12 +52,17 @@ const OrganizationSettingsPage: FC = () => {
...
-				// JavaScript will happily subtract booleans, but use numbers to keep
-				// the compiler happy.
-				return (b.is_default ? 1 : 0) - (a.is_default ? 1 : 0);
+				if (a.is_default && !b.is_default) {
+					return -1;
+				}
+				if (b.is_default && !a.is_default) {
+					return 1;
+				}
+				return 0;
```
Comment (aslilac) [inline site/src/pages/ManagementSettingsPage/OrganizationSettingsPage.tsx:65]: maybe controversial, but I find the previous version waaaay easier to read. can we revert this? 😅

**Review by aslilac — APPROVED** [review]

File: site/src/pages/DeploymentSettingsPage/NotificationsPage/NotificationsPage.tsx (hunk 11 above)
Comment (Parkreiner) [reply site/src/pages/DeploymentSettingsPage/NotificationsPage/NotificationsPage.tsx:37]: So do I, but for some reason, when I tried to change things, it wasn't doing anything with type narrowing
