### PR TITLE
fix(agent): send metadata in batches

### LINKED ISSUE #9782: batch coder agent metadata
We currently do not batch agent metadata. This causes a fair number of requests and DB load. Our documentation even has a formula for how much DB load a number of metadata would generate. 

> You can expect (10 * 6 * 2) / 4 or 30 writes per second.

There are a couple of ways we could optimize this: 
- Batch metadata on the agent side and only send them when there is new data
- Batch metadata on the coderd side (similar to what we do for agent stats)

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #9782

---

I recommend reviewing with ignore whitespace.

### CODE REVIEW

File: agent/agent_test.go [hunk 1]
```diff
@@ -1066,34 +1066,43 @@ func TestAgent_Metadata(t *testing.T) {
...
+			opts.ReportMetadataInterval = testutil.IntervalFast
 		})
 
 		var gotMd map[string]agentsdk.Metadata
 		require.Eventually(t, func() bool {
 			gotMd = client.GetMetadata()
-			return len(gotMd) == 1
-		}, testutil.WaitShort, testutil.IntervalMedium)
+			return len(gotMd) == 2
+		}, testutil.WaitShort, testutil.IntervalFast/2)
```
Comment (johnstcn) [inline agent/agent_test.go:1092]: Do we need to go this fast? Could this be flake-prone on a slower runner?

File: agent/agent.go [hunk 2]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
+		select {
+		case <-ctx.Done():
+			return
+		case mr := <-metadataResults:
+			// This can overwrite unsent values, but that's fine because
+			// we're only interested about up-to-date values.
+			updatedMetadata[mr.key] = mr.result
+			continue
+		case <-report:
+			if len(updatedMetadata) > 0 {
```
Comment (johnstcn) [inline agent/agent.go:538]: If I'm understanding this correctly - say you have two agent metadata definitions, one which updates every 1 second, the other which updates every 10 seconds.

In the previous request-per-metadata-key approach, this would cause (0.1 + 1) 1.1 requests per second, while in this new approach we would end up with a minimum of 1 requests per second, as the more frequently updated metadatum would cause a batch request.

I'm think we should update the documentation with this change to reflect the new behaviour. I think it would also make sense to recommend users to keep in mind the minimum metadata refresh interval when writing their templates; any metadatum with a refresh interval of 1 second will cause frequent metadata updates from what I understand here.

File: agent/agent_test.go (hunk 1 above)
Comment (mafredri) [reply agent/agent_test.go:1092]: I matched what we have in the `Many` test. AFAICT I've eliminated the potential for race here so it shouldn't flake, since this check is also very simple, I don't think performance wise it will matter.

File: agent/agent.go (hunk 2 above)
Comment (mafredri) [reply agent/agent.go:538]: > In the previous request-per-metadata-key approach, this would cause (0.1 + 1) 1.1 requests per second, while in this new approach we would end up with a minimum of 1 requests per second.

I'm not sure where `0.1` comes from in your example, but for simplicity sake, let's say we have 1s and 2s intervals for the metadata, and each take 0ns to execute. In the previous implementation we would approximately do:

```
14:00:00 POST meta1
14:00:00 POST meta2
14:00:01 POST meta1
14:00:02 POST meta1
14:00:02 POST meta2
14:00:03 POST meta1
```

In the new implementation, we would:

```
14:00:00 POST meta1, meta2
14:00:01 POST meta1
14:00:02 POST meta1, meta2
14:00:03 POST meta1
```

With 2s and 3s metadata, it would look like this:

Old: 

```
14:00:00 POST meta1
14:00:00 POST meta2
14:00:02 POST meta1
14:00:03 POST meta2
14:00:04 POST meta1
14:00:06 POST meta1
14:00:06 POST meta2
```

New:

```
14:00:00 POST meta1, meta2
14:00:02 POST meta1
14:00:03 POST meta2
14:00:04 POST meta1
14:00:06 POST meta1, meta2
```

This is an approximation of ideal conditions, though. And perhaps we should separate `collect` and `send` triggers by, say, 500ms. This would increase the likelyhood of ideal batching.

With regards to RPS the new implementation reduces RPS and doesn't necessarily guarantee 1 RPS, it depends on interval and how long commands take to execute.

> I'm think we should update the documentation with this change to reflect the new behaviour.

Are you referring to this https://coder.com/docs/v2/latest/templates/agent-metadata#db-write-load?

The write load will be about the same, but the writes will be more performant since they're batched. I suppose we could call one batch one write, even though we're updating multiple rows. I'll amend this part.

Comment (johnstcn) [reply agent/agent.go:538]: Wouldn't an agent metadatum with a fresh interval of 10 seconds cause 1 request roughly every 10 seconds (i.e. 0.1 RPS)?

Comment (mafredri) [reply agent/agent.go:538]: Yes, this is the case in both implementations.

**Review by johnstcn — APPROVED** [review]
The change to the docs is the cherry on top here!
> -You can expect `(10 * 6 * 2) / 4` or 30 writes per second.
> +You can expect at most `(10 * 2 / 4) + (10 * 2 / 6)` or ~8 writes per second.

File: agent/agent.go [hunk 3]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
+			lastCollectedAts  = make(map[string]time.Time)
+		)
+		for {
+			select {
+			case <-ctx.Done():
+				return
+			case <-collect:
+			}
 
-		if len(manifest.Metadata) > metadataLimit {
```
Comment (mtojek) [inline agent/agent.go:420]: We don't need this condition anymore? just in case...

File: agent/agent.go [hunk 4]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
-			})
+
+				go func() {
+					ctx, cancel := context.WithTimeout(ctx, reportTimeout)
+					defer func() {
+						cancel()
+						reportSemaphore <- struct{}{}
+					}()
+
+					err := a.client.PostMetadata(ctx, agentsdk.PostMetadataRequest{Metadata: metadata})
```
Comment (mtojek) [inline agent/agent.go:563]: This behavior doesn't change, right: 

If the agent fails to send the metadata, it will be lost. There is no "retry" mechanism in place now?

File: agent/agent.go [hunk 5]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
-						// randomly picked.
-						timeout = 5
-					}
+	// Gather metadata updates and report them once every interval. If a
+	// previous report is in flight, wait for it to complete before
+	// sending a new one. If the network conditions are bad, we won't
+	// benefit from canceling the previous send and starting a new one.
+	var (
+		updatedMetadata = make(map[string]*codersdk.WorkspaceAgentMetadataResult)
+		reportTimeout   = 30 * time.Second
```
Comment (mtojek) [inline agent/agent.go:523]: There are many magic timeouts hidden in this file. I'm wondering if we shouldn't move them to the top of file, and make them more dependent. For instance: instead of `5sec` -> `reportTimeout * 1/6`

File: agent/agent.go [hunk 6]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
 
 	var (
-		baseTicker        = time.NewTicker(a.reportMetadataInterval)
-		lastCollectedAtMu sync.RWMutex
-		lastCollectedAts  = make(map[string]time.Time)
-		metadataResults   = make(chan metadataResultAndKey, metadataLimit)
-		logger            = a.logger.Named("metadata")
+		logger          = a.logger.Named("metadata")
+		report          = make(chan struct{}, 1)
+		collect         = make(chan struct{}, 1)
```
Comment (mtojek) [inline agent/agent.go:377]: Would it change something if we increase buffers here?

File: agent/agent.go [hunk 7]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
+						// If the interval is zero, we assume the user just wants
+						// a single collection at startup, not a spinning loop.
+						if md.Interval == 0 {
+							return
+						}
+						intervalUnit := time.Second
+						// reportMetadataInterval is only less than a second in tests,
+						// so adjust the interval unit for them.
+						if a.reportMetadataInterval < time.Second {
+							intervalUnit = 100 * time.Millisecond
```
Comment (mtojek) [inline agent/agent.go:474]: Another magic.

File: agent/agent.go [hunk 8]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
+							timeout = md.Interval
+						} else if interval := int64(a.reportMetadataInterval.Seconds()); interval != 0 {
+							// Fallback to the report interval
+							timeout = interval * 3
+						} else {
+							// If the interval is still 0 (possible if the interval
+							// is less than a second), default to 5. This was
+							// randomly picked.
+							timeout = 5
+						}
```
Comment (mtojek) [inline agent/agent.go:494]: I had feeling that it would be easier to read this routine if you extract some operations to separate functions.

File: agent/agent.go [hunk 9]
```diff
@@ -362,147 +362,210 @@ func (t *trySingleflight) Do(key string, fn func()) {
...
 					}
-					// The last collected value isn't quite stale yet, so we skip it.
-					if collectedAt.Add(time.Duration(md.Interval) * intervalUnit).After(time.Now()) {
-						return
+					ctxTimeout := time.Duration(timeout) * time.Second
```
Comment (mtojek) [inline agent/agent.go:496]: I might be lost in the flow here... why is this 1sec timeout needed?

**Review by mtojek — COMMENTED** [review]
As you refactored this function a bit, I'm wondering if it is possible to prepare extra unit tests for healthy/unhealthy conditions. I'm thinking about singleflight vs. duplicate backpressure, _coderd is unavailable_, etc.

File: agent/agent.go (hunk 3 above)
Comment (mafredri) [reply agent/agent.go:420]: Previously there was a buffered channel, but that's no longer required so this artificial restriction got lifted. _If_ we want to limit this, it should be in the coder tf provider, saying too many metadata items were added.

File: agent/agent.go (hunk 4 above)
Comment (mafredri) [reply agent/agent.go:563]: Correct, we don't retry since trying to send stale data wouldn't make much sense, we instead wait until the next update is available and try to send it.

Comment (mtojek) [reply agent/agent.go:563]: Ok! I guess we can debate about the lack of source data for insights, but that's a separate issue.

File: agent/agent.go (hunk 5 above)
Comment (mafredri) [reply agent/agent.go:523]: With 5 sec, are you referring to the case where `md.Timeout` is not set (or zero), and we fall back to 5 sec?

I wanted to change as little about the metadata collection as possible, but I can go over this and see what can be consolidated.

This 30 second timeout was randomly picked by me as a crutch for scenarios where the network is super slow or down. It should be enough for at least something to get through, whilst avoiding sending very stale data.

Comment (mtojek) [reply agent/agent.go:523]: I see. I'm afraid that there are too many timeouts depending on each other in the entire implementation, and it might be hard to debug potential queueing problems.

File: agent/agent.go (hunk 6 above)
Comment (mafredri) [reply agent/agent.go:377]: Yes. They are single buffer to be non-blocking and not cause back-pressure. If we increase channel sizes then we may have back-pressure if an operation is taking longer than expected. Say collect was 10, if one iteration of starting collection took 10s then this channel would fill and afterwards 10 collections would start immediately after each other, even if they now finish in 0.1s each, possibly leading to 10 collections (and load) within a second (vs once per second).

File: agent/agent.go (hunk 7 above)
Comment (mafredri) [reply agent/agent.go:474]: This didn't change, it's part of the previous implementation.

File: agent/agent.go (hunk 9 above)
Comment (mafredri) [reply agent/agent.go:496]: This also didn't change in this PR.

The timeout here can be 1s or it can be higher. I suppose the logic is that if you want metadata to update every 1s, collection should run faster than 1s, but this is likely not ideal.

We could change this in the future or if it becomes a problem.

File: agent/agent.go (hunk 4 above)
Comment (mafredri) [reply agent/agent.go:563]: Ah, this is not used for insights, so it will not have an effect on that.

**Review by mtojek — APPROVED** [review]
I have better understanding of the code now. LGTM!

**Comment by mafredri** [comment]
### Merge activity

* **Oct 13, 10:32 AM**: [Graphite](https://app.graphite.dev/github/pr/coder/coder/10225) rebased this pull request after merging its parent, because this pull request is set to merge when ready.
