### PR TITLE
fix: Use command property when launching an application

### LINKED ISSUE #3777: Apps with `command` are not working
It seems that apps that are using a command only are not working like they are suggested at https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app. This is my definition:
````
resource "coder_app" "postgres" {
  agent_id = coder_agent.postgres.id
  name     = "Logs"
  command  = "ls /var/lib/postgresql/data/log/"
}
````

But when I try to open the app it says:
````
{
  "message": "Application Logs does not have a url."
}
````

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #3777.

### CODE REVIEW

File: site/src/xServices/terminal/terminalXService.ts [hunk 1]
```diff
@@ -170,9 +171,11 @@ export const terminalMachine =
               return reject("workspace agent is not set")
             }
             const proto = location.protocol === "https:" ? "wss:" : "ws:"
-            const socket = new WebSocket(
-              `${proto}//${location.host}/api/v2/workspaceagents/${context.workspaceAgent.id}/pty?reconnect=${context.reconnection}`,
-            )
+            let url = `${proto}//${location.host}/api/v2/workspaceagents/${context.workspaceAgent.id}/pty?reconnect=${context.reconnection}`
```
Comment (presleyp) [inline site/src/xServices/terminal/terminalXService.ts:174]: We try to avoid `let`. How about making a const that's either the command query or '', and interpolating it in `url`?

**Review by presleyp — APPROVED** [review]

File: site/src/xServices/terminal/terminalXService.ts (hunk 1 above)
Comment (kylecarbs) [reply site/src/xServices/terminal/terminalXService.ts:174]: Why do we avoid using `let`?

Comment (presleyp) [reply site/src/xServices/terminal/terminalXService.ts:174]: Because it allows mutation.

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 2]
```diff
@@ -38,6 +38,10 @@ const TerminalPage: FC<
     const search = new URLSearchParams(location.search)
     return search.get("reconnect") ?? uuidv4()
   })
+  const [command] = useState(() => {
+    const search = new URLSearchParams(location.search)
+    return search.get("command") || undefined
+  })
```
Comment (BrunoQuaresma) [inline site/src/pages/TerminalPage/TerminalPage.tsx:44]: I don't think this need to be a state since we don't change it.  You could make something like:
```
 const [searchParams] = useSearchParams()
 const command = searchParams.get("command")
```

File: site/src/xServices/terminal/terminalXService.ts (hunk 1 above)
Comment (kylecarbs) [reply site/src/xServices/terminal/terminalXService.ts:174]: I understand, but only inside the function where the variable is defined. Why is the mutation considered bad? In this case, I'd argue it's cleaner code (unless I'm misunderstanding what you're proposing, which is entirely possible ;p).

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 2 above)
Comment (kylecarbs) [reply site/src/pages/TerminalPage/TerminalPage.tsx:44]: Ahh, neato!

Comment (BrunoQuaresma) [reply site/src/pages/TerminalPage/TerminalPage.tsx:44]: Hm... I think react-router-dom does something similar on their back but even in a loop, parsing the search parameters should not be an issue tho

File: site/src/xServices/terminal/terminalXService.ts (hunk 1 above)
Comment (presleyp) [reply site/src/xServices/terminal/terminalXService.ts:174]: I like functional programming, so I try to avoid mutation whenever possible. I find it's often at the root of annoying bugs. Here's a function from v1 where I think reassignment (with `let` but also of the argument) made it hard to read and refactor https://github.com/coder/v1/blob/master/product/coder/site/src/components/Workspaces/CreateEditWorkspaceForm/hooks.ts#L102

It's not a big deal here, but for clarity my proposal is
```
const commandQuery = context.command ? `&command=${encodeURIComponent(context.command)}` : ""
const url = `${proto}//${location.host}/api/v2/workspaceagents/${context.workspaceAgent.id}/pty?reconnect=${context.reconnection}${commandQuery}`
```

But it's probably better to do it this way anyway https://www.valentinog.com/blog/url/#how-to-build-an-url-and-its-search-parameters

Comment (kylecarbs) [reply site/src/xServices/terminal/terminalXService.ts]: Fixed!

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 2 above)
Comment (kylecarbs) [reply site/src/pages/TerminalPage/TerminalPage.tsx:44]: Ohhhh, I missed your sample. I'll update it to do that.

Comment (kylecarbs) [reply site/src/pages/TerminalPage/TerminalPage.tsx]: Fixed!

**Comment by jaulz** [comment]
@kylecarbs would it be feasible to keep the connection open? Right now, the command is executed and immediately afterwards it says `Disconnected`. However, it would be cool to use the command as a starting point so I can continue working in the terminal, e.g.: `cd /logs && ls .` and then I can continue and view a log file from that folder.
