### PR TITLE
fix: Use a select when parameter input has many options

### LINKED ISSUE #3744: Nicer UI for multiple template options
When there are too many options specified with `validation` in a template, it can get a bit annoying. For example:
screenshot

Would be great to have a dropdown for more than, say, 10 items or something.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Before: 
Screen Shot 2022-08-30 at 15 53 31

After:
Screen Shot 2022-08-30 at 15 52 14

Why? 
Radio groups look nice but when it is about 10+ items, it starts to occupy too much vertical space. Fixes #3744

### CODE REVIEW

**Review by jsjoeio — APPROVED** [review]
Looks good to me! This is a great UX improvement too 🔥

File: site/src/components/ParameterInput/ParameterInput.tsx [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import FormControlLabel from "@material-ui/core/FormControlLabel"
+import MenuItem from "@material-ui/core/MenuItem"
 import Radio from "@material-ui/core/Radio"
 import RadioGroup from "@material-ui/core/RadioGroup"
```
Comment (matifali) [inline site/src/components/ParameterInput/ParameterInput.tsx:4]: RadioGroup is not being used anymore. Suggested to remove import.

Comment (BrunoQuaresma) [reply site/src/components/ParameterInput/ParameterInput.tsx:4]: It is for the boolean types
