### PR TITLE
fix: Replace access URL for built-in DERP servers

### LINKED ISSUE #4195: How to stop background tailscale tunneling from occurring
I've been trying to work out how Tailscale networking is used but it's tricky to find documentation around this.

We've got our own Tailscale network which allows the coder workspaces to reach the coder server but find that coder is doing its own tailscale thing in the background when reviewing logs which raises some security concerns and potentially causing connection issues for us.

What options should be specified both at coderd and coder agent to stop any sort of tailscale tunnel and force direct?

Or am I completely missing the point of all the Tailscale action I'm seeing?

I can see coder embedded relay is active but web terminal and web coder server doesn't seem to work and just wondering if this is related. coder CLI port forward and ssh commands work fine.

Screen Shot 2022-09-25 at 8 43 44 pm

Screen Shot 2022-09-25 at 8 53 22 pm

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4195.

### CODE REVIEW

File: codersdk/workspaceagents.go [hunk 1]
```diff
@@ -208,7 +209,42 @@ func (c *Client) WorkspaceAgentMetadata(ctx context.Context) (WorkspaceAgentMeta
...
+	if err != nil {
+		return WorkspaceAgentMetadata{}, err
+	}
+	accessingPort := c.URL.Port()
+	if accessingPort == "" {
+		accessingPort = "80"
+		if c.URL.Scheme == "https" {
+			accessingPort = "443"
+		}
+	}
```
Comment (coadler) [inline codersdk/workspaceagents.go:222]: This is a bit nested, I think it would be simpler as an if + else if

**Review by coadler — APPROVED** [review]

File: codersdk/workspaceagents.go (hunk 1 above)
Comment (kylecarbs) [reply codersdk/workspaceagents.go:222]: It'd be similarly nested tho, right?
