### PR TITLE
fix(cli/ssh): prevent reads/writes to stdin/stdout in stdio mode

### LINKED ISSUE #11530: SSH failed: `kex_exchange_identification: banner line contains invalid characters`
I just tried to `ssh` into my workspace, however, I was greeted by the following:

```console
# ssh -X coder.w     
Your license expires in 25 days.
Workspace was stopped, starting workspace to allow connecting to "w"...
kex_exchange_identification: banner line contains invalid characters
```

So I ran with `ssh -vvv`:

```
Your license expires in 25 days.
Workspace was stopped, starting workspace to allow connecting to "w"...
debug1: kex_exchange_identification: banner line 0: You must authenticate with JFrog Artifactory (https://jfrt.cdr.dev) to create a workspace with this template. Visit:
debug1: kex_exchange_identification: banner line 1: 
debug1: kex_exchange_identification: banner line 2:     https://dev.coder.com/external-auth/jfrog
debug1: kex_exchange_identification: banner line 3: 
kex_exchange_identification: banner line contains invalid characters
banner exchange: Connection to UNKNOWN port 65535: invalid format
```

We need to fix this and be more careful with how/when we output data when establishing SSH connections.

### PR DESCRIPTION
**Pull request by mafredri**
This PR prevents writes to stdout in stdio mode (assuming no developer error that uses `os.Stdout`).

For absolute safety, we also swap stdin with an EOF reader that logs errors on attempts to read. We can't make reads panic (or similar) since there's a high chance that such an issue could slip unnoticed into a release and trigger at runtime.

Fixes #11530

---

The added test, without the fix, would catch the issue at two stages:

```
    ssh_test.go:400: monitorServerOutput: "Planning workspace..." (0x506c616e6e696e6720776f726b73706163652e2e2e)
    ssh_test.go:409:
        	Error Trace:	/home/coder/coder/cli/ssh_test.go:409
        	            				/home/coder/coder/cli/ssh_test.go:1479
        	            				/usr/local/go/src/runtime/asm_amd64.s:1650
        	Error:      	Not equal:
        	            	expected: "SSH-2.0-Go"
        	            	actual  : "Planning workspace..."

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-SSH-2.0-Go
        	            	+Planning workspace...
        	Test:       	TestSSH/Stdio_StartStoppedWorkspace_NoStdinOrStdout
        	Messages:   	invalid header
    ssh_test.go:400: monitorServerOutput: "==> ⧗ Queued" (0x3d3d3e20e2a79720517565756564)

    [...]

    ssh_test.go:463:
        	Error Trace:	/home/coder/coder/cli/ssh_test.go:463
        	Error:      	Received unexpected error:
        	            	ssh: handshake failed: ssh: overflow reading version string
        	Test:       	TestSSH/Stdio_StartStoppedWorkspace_NoStdinOrStdout
```

### CODE REVIEW

File: cli/ssh_test.go [hunk 1]
```diff
@@ -338,6 +339,147 @@ func TestSSH(t *testing.T) {
...
+		// Stop the workspace
+		workspaceBuild := coderdtest.CreateWorkspaceBuild(t, client, workspace, database.WorkspaceTransitionStop)
+		coderdtest.AwaitWorkspaceBuildJobCompleted(t, client, workspaceBuild.ID)
+
+		ctx, cancel := context.WithTimeout(context.Background(), testutil.WaitLong)
+		defer cancel()
+
+		clientOutput, clientInput := io.Pipe()
+		serverOutput, serverInput := io.Pipe()
+		monitorServerOutput, monitorServerInput := io.Pipe()
```
Comment (spikecurtis) [inline cli/ssh_test.go:367]: it's pretty confusing what's happening with these 3 pipes, so I think an ASCII diagram would go a long way.

File: cli/ssh_test.go [hunk 2]
```diff
@@ -338,6 +339,147 @@ func TestSSH(t *testing.T) {
...
+			}
+		}
+		defer closePipes()
+		tGo(t, func() {
+			<-ctx.Done()
+			closePipes()
+		})
+
+		// Here we start a monitor for the input going to the server
+		// (i.e. client stdout) to ensure that the output is clean.
```
Comment (spikecurtis) [inline cli/ssh_test.go:380]: I think this comment is incorrect.  This doesn't monitor data being sent to the server (to monitor that we'd need to be in the tailnet network path and we are not), but rather data being sent to the stdio client.

Underscores a need for a diagram about the pipes.

File: cli/ssh_test.go [hunk 3]
```diff
@@ -338,6 +339,147 @@ func TestSSH(t *testing.T) {
...
+				}
+				if b == '\n' || b == '\r' {
+					out := buf.Bytes()
+					t.Logf("monitorServerOutput: %q (%#x)", out, out)
+					buf.Reset()
+
+					// Ideally we would do further verification, but that would
+					// involve parsing the SSH protocol to look for output that
+					// doesn't belong. This at least ensures that no garbage is
+					// being sent to the server before trying to connect.
```
Comment (spikecurtis) [inline cli/ssh_test.go:405]:
```suggestion
					// being sent to the client before trying to connect.
```

File: cli/ssh_test.go [hunk 4]
```diff
@@ -338,6 +339,147 @@ func TestSSH(t *testing.T) {
...
+
+		tGo(t, func() {
+			// When the agent connects, the workspace was started, and we should
+			// have access to the shell.
+			_ = agenttest.New(t, client.URL, authToken)
+			coderdtest.NewWorkspaceAgentWaiter(t, client, workspace.ID).Wait()
+		})
+
+		conn, channels, requests, err := ssh.NewClientConn(&stdioConn{
+			Reader: serverOutput,
```
Comment (spikecurtis) [inline cli/ssh_test.go:456]: here I think the naming isn't great.  This is the stdout from the proxy command.  The whole problem we are testing for is the output from the proxy command not being faithful to what the server sent over the wire.  Maybe `cmdStdOutR`

**Review by spikecurtis — APPROVED** [review]
I think the commentary and naming could be improved with some inline suggestions, but LGTM.

File: cli/ssh_test.go (hunk 2 above)
Comment (mafredri) [reply cli/ssh_test.go:380]: The stdio client is a representation of a raw network connection, so I don't consider the statement incorrect. Lossy, perhaps.

File: cli/ssh_test.go (hunk 4 above)
Comment (mafredri) [reply cli/ssh_test.go:456]: I followed the naming used in the other tests, I agree it can be improved but perhaps it'd be best to update all of them in that case.

File: cli/ssh_test.go (hunk 1 above)
Comment (mafredri) [reply cli/ssh_test.go]: I neither know mermaid or how to turn it into ascii, so I pasted it in there 😅

```mermaid
flowchart LR
    A[ProxyCommand] --> B[captureProxyCommandStdoutW]
    B --> C[captureProxyCommandStdoutR]
    C --> VA[Validate output]
    C --> D[proxyCommandOutputW]
    D --> E[proxyCommandOutputR]
    E --> F[SSH Client]
```

File: cli/ssh_test.go (hunk 4 above)
Comment (mafredri) [reply cli/ssh_test.go]: Attempted some renaming, looks alright?

Comment (spikecurtis) [reply cli/ssh_test.go]: LGTM

**Review by johnstcn — APPROVED** [review]
