### PR TITLE
fix: use insert and delete instead of upsert for custom roles

### LINKED ISSUE #14245: Frontend integration for custom role endpoint change from upsert to insert + update
depends on #14217

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves #14245

### CODE REVIEW

File: site/src/pages/ManagementSettingsPage/CustomRolesPage/CreateEditRolePage.tsx [hunk 1]
```diff
@@ -47,18 +54,31 @@ export const CreateEditRolePage: FC = () => {
...
           try {
-            await patchOrganizationRoleMutation.mutateAsync(data);
-            navigate(`/organizations/${organizationName}/roles`);
+            if (role) {
+              await updateOrganizationRoleMutation.mutateAsync(data);
+              navigate(`/organizations/${organizationName}/roles`);
+            } else {
+              await createOrganizationRoleMutation.mutateAsync(data);
+              navigate(`/organizations/${organizationName}/roles`);
+            }
```
Comment (aslilac) [inline site/src/pages/ManagementSettingsPage/CustomRolesPage/CreateEditRolePage.tsx:65]:
```suggestion
            if (role) {
              await updateOrganizationRoleMutation.mutateAsync(data);
            } else {
              await createOrganizationRoleMutation.mutateAsync(data);
            }
            navigate(`/organizations/${organizationName}/roles`);
```

**Review by aslilac — APPROVED** [review]
