### PR TITLE
fix: hide app icon if not found

### LINKED ISSUE #14759: handle invalid and nonexistent icon paths in `coder_app`
## Problem
When we set a `coder_app` [icon](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#icon) to a nonexistent path Coder dashboard is not able to render the icon and instead shows something like the image below.

image

This can happen when a coder [module](https://registry.coder.come/modules/cursor) with a `coder_app` using a built in icon is used with an older Coder deployment not having that icon. 

For example the [cursror module](https://registry.coder.come/modules/cursor) icon is [added to `main`](https://github.com/coder/coder/pull/14743) but is not available in any Coder release yet.

## Suggested solution

When the `icon` is set to a non existent icon let us skip rendering and it only show the `display_text`.

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/14759

This PR dynamically hides icon's `` tag if the image can't be loaded (HTTP 404). 

Screenshot 2025-02-24 at 17 08 25

Screenshot 2025-02-25 at 11 20 56

### CODE REVIEW

File: site/src/modules/resources/AppLink/BaseIcon.tsx [hunk 1]
```diff
@@ -4,14 +4,18 @@ import type { FC } from "react";
...
-export const BaseIcon: FC<BaseIconProps> = ({ app }) => {
+export const BaseIcon: FC<BaseIconProps> = ({ app, onError }) => {
 	return app.icon ? (
 		<img
 			alt={`${app.display_name} Icon`}
 			src={app.icon}
 			style={{ pointerEvents: "none" }}
+			onError={() => {
+				onError?.();
+			}}
```
Comment (johnstcn) [inline site/src/modules/resources/AppLink/BaseIcon.tsx:18]: The naming here is kind of confusing IMO. Can we rename the `onError` function variable so it's distinct?

**Review by johnstcn — APPROVED** [review]
LGTM but deferring to the FE expert here!

**Comment by matifali** [comment]
Can we also show a warning somewhere to let the user know that the path used is incorrect? I am not sure what is the best place to show the warning.
1. Toast notification?
2. In logs?
3. Developer Console.?

File: site/src/modules/resources/AppLink/BaseIcon.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/modules/resources/AppLink/BaseIcon.tsx:18]: Good call, renamed to `onIconPathError`

**Review by matifali — APPROVED** [review]
