### PR TITLE
fix: resolve missing users in `<UserCombobox />`

### LINKED ISSUE #21044: Tasks: User search dropdown broken after typing one character
## Description

The user search dropdown/typeahead for Tasks is broken. It doesn't seem to work beyond typing one letter. See https://codercom.slack.com/archives/C09H8LRLG8K/p1764612907541919 for more info.

## Steps to Reproduce

1. Navigate to Tasks
2. Attempt to use the user search dropdown
3. Type more than one character

## Expected Behavior

The user search should filter and display matching users as you type.

## Actual Behavior

The dropdown stops working after typing approximately one character.

### PR DESCRIPTION
**Pull request by jakehwll**
Closes #21044

This pull-request addresses an issue we were seeing where we would attempt to filter the `<UserCombobox />` by the users username or email not their username (which the rendered options would show). 

To highlight this I created three different users. Each with a username that did not contain their `email` or `name` and attempted to filter. Attempting to search for `John` wouldn't actually show the user as his username was `x`, and infact whereas a subset of users might be returned from the backend for having `john` in the `email` it would've been filtered by the frontend for not being in the `name` field.

| Name | Username |
| --- | --- |
| `Jake` | `z` |  
| `Jeff` | `y` |
| `John` | `x` |

| Previously | Now |
| --- | --- |
| OLD_USER_COMBOBOX | NEW_USER_COMBOBOX |

### CODE REVIEW

File: coderd/database/queries/users.sql [hunk 1]
```diff
@@ -247,14 +247,20 @@ WHERE
 		ELSE true
 	END
 	-- Start filters
-	-- Filter by name, email or username
+	-- Filter by email or username
 	AND CASE
 		WHEN @search :: text != '' THEN (
 			email ILIKE concat('%', @search, '%')
 			OR username ILIKE concat('%', @search, '%')
 		)
```
[the remark this answers is not in the document]
Comment (jakehwll) [reply coderd/database/queries/users.sql:255]: This comment was actually misleading. There isn't a regression here as the prior comment where it stated it would search by `name` wasn't actually ever there.

File: coderd/searchquery/search.go [hunk 2]
```diff
@@ -156,6 +156,7 @@ func Users(query string) (database.GetUsersParams, []codersdk.ValidationError) {
 	parser := httpapi.NewQueryParamParser()
 	filter := database.GetUsersParams{
 		Search:          parser.String(values, "", "search"),
+		Name:            parser.String(values, "", "name"),
```
Comment (DanielleMaywood) [inline coderd/searchquery/search.go:159]: Could you add a test/update the existing tests for this?

File: coderd/database/queries/users.sql [hunk 3]
```diff
@@ -247,14 +247,20 @@ WHERE
...
 		ELSE true
 	END
+	-- Filter by name (display name)
+	AND CASE
+		WHEN @name :: text != '' THEN
+			name ILIKE concat('%', @name, '%')
+		ELSE true
+	END
```
Comment (DanielleMaywood) [inline coderd/database/queries/users.sql:263]: Just curious but what's the reason for adding a new filter, query parameter and endpoint parameter instead of updating the original filter to have `or name ILIKE concat('%', @search, '%')`?

Comment (jakehwll) [reply coderd/database/queries/users.sql:263]: I didn't want to effect how `<UserAutocomplete />` worked, I thought it was incorrect that we show the user just the `username` field when we filter on `user` and vice-versa.

**Review by DanielleMaywood — APPROVED** [review]
