### PR TITLE
fix(agent/agentcontainers): respect ignore files

### LINKED ISSUE #19011: bug: dev container project discovery looks in dependencies
When dev container project discovery is enabled and I install a node dependency that has a `.devcontainer.json` file, it will be found and surfaced. 

### Possible solutions

- Introduce a max depth to search (has downsides)
- Respect ignore files

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Closes https://github.com/coder/coder/issues/19011

We now use [go-git](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.16.2/plumbing/format/gitignore)'s `gitignore` plumbing implementation to parse the `.gitignore` files and match against the patterns generated. We use this to ignore any ignored files in the git repository.

Unfortunately I've had to slightly re-implement some of the interface exposed by `go-git` because they use `billy.Filesystem` instead of `afero.Fs`.

### CODE REVIEW

**Comment by DanielleMaywood** [comment]
@coderabbitai review

File: agent/agentcontainers/ignore/dir_test.go [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+		{"/foo//bar///baz", []string{"foo", "bar", "baz"}},
+		{"foo/bar/", []string{"foo", "bar"}},
+		{"/foo/bar/", []string{"foo", "bar"}},
+		{"foo/../bar", []string{"bar"}},
+		{"./foo/../bar", []string{"bar"}},
+		{"/foo/../bar", []string{"bar"}},
+		{"foo/./bar", []string{"foo", "bar"}},
+		{"/foo/./bar", []string{"foo", "bar"}},
+		{"a/b/c/d/e", []string{"a", "b", "c", "d", "e"}},
+		{"/a/b/c/d/e", []string{"a", "b", "c", "d", "e"}},
```
Comment (mtojek) [inline agent/agentcontainers/ignore/dir_test.go]: nit: Aren't some of these cases very similar? I mean, testing the same scenarios?

File: agent/agentcontainers/ignore/dir.go [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+	for segment := range strings.SplitSeq(filepath.Clean(path), string(filepath.Separator)) {
+		if segment != "" {
+			components = append(components, segment)
+		}
+	}
+
+	return components
+}
+
+func readIgnoreFile(fileSystem afero.Fs, path string) ([]gitignore.Pattern, error) {
```
Comment (mtojek) [inline agent/agentcontainers/ignore/dir.go]: TIL: gitignore.Pattern!

File: agent/agentcontainers/ignore/dir.go [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+	var ps []gitignore.Pattern
+
+	data, err := afero.ReadFile(fileSystem, filepath.Join(path, ".gitignore"))
```
Comment (mtojek) [inline agent/agentcontainers/ignore/dir.go]: nit: maybe there is a magic string defined in go-git? or even the entire function

File: agent/agentcontainers/ignore/dir.go [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+	"github.com/go-git/go-git/v5/plumbing/format/gitignore"
+	"github.com/spf13/afero"
+)
+
+func FilePathToParts(path string) []string {
+	components := []string{}
+
+	if path == "" {
+		return []string{}
```
Comment (mtojek) [inline agent/agentcontainers/ignore/dir.go]: nit:` return components`?

File: agent/agentcontainers/api_test.go [hunk 5]
```diff
@@ -3345,6 +3345,46 @@ func TestDevcontainerDiscovery(t *testing.T) {
...
+			fs: map[string]string{
+				"/home/coder/coder/.git/HEAD":              "",
+				"/home/coder/coder/.gitignore":             "y/",
+				"/home/coder/coder/.devcontainer.json":     "",
+				"/home/coder/coder/x/y/.devcontainer.json": "",
+			},
+			expected: []codersdk.WorkspaceAgentDevcontainer{
+				{
+					WorkspaceFolder: "/home/coder/coder",
+					ConfigPath:      "/home/coder/coder/.devcontainer.json",
```
Comment (mtojek) [inline agent/agentcontainers/api_test.go:3364]: oh, isn't it `/home/coder/coder/.devcontainer/devcontainer.json`?

File: agent/agentcontainers/api_test.go [hunk 6]
```diff
@@ -3345,6 +3345,46 @@ func TestDevcontainerDiscovery(t *testing.T) {
 				},
 			},
 		},
+		{
+			name:     "RespectGitIgnore",
```
Comment (mtojek) [inline agent/agentcontainers/api_test.go:3353]: It might be trickier than we thought:

https://docs.github.com/en/get-started/git-basics/ignoring-files#excluding-local-files-without-creating-a-gitignore-file

and

https://git-scm.com/docs/git-config

File: go.mod [hunk 7]
```diff
@@ -122,7 +122,7 @@ require (
 	github.com/fergusstrange/embedded-postgres v1.31.0
 	github.com/fullsailor/pkcs7 v0.0.0-20190404230743-d7302db945fa
 	github.com/gen2brain/beeep v0.11.1
-	github.com/gliderlabs/ssh v0.3.4
+	github.com/gliderlabs/ssh v0.3.8
```
Comment (johnstcn) [inline go.mod:125]: I'm assuming this is a result of adding `go-git` as a dependency.

File: agent/agentcontainers/api_test.go (hunk 5 above)
Comment (johnstcn) [reply agent/agentcontainers/api_test.go:3364]: The "canonical path" is `.devcontainer/devcontainer.json` but it's not a hard requirement AFAIK.

File: agent/agentcontainers/api_test.go (hunk 6 above)
Comment (johnstcn) [reply agent/agentcontainers/api_test.go:3353]: I'm not convinced we should go this far; `.gitignore` is fairly well-known and conventional.

File: agent/agentcontainers/ignore/dir.go (hunk 3 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir.go]: Yep, the entire function is defined in `go-git` but unfortunately they're using a different filesystem abstraction so I've had to re-implement it. If you have any ideas that don't involve pulling in another dependency for this I'm open to suggestions.

https://github.com/go-git/go-git/blob/ed8216c4a2c3fdb7e4e31ce242bf7847356623c9/plumbing/format/gitignore/dir.go#L28-L85

File: agent/agentcontainers/ignore/dir.go [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+		}
+	}
+
+	return ps, nil
+}
+
+func ReadPatterns(fileSystem afero.Fs, path string) ([]gitignore.Pattern, error) {
+	var ps []gitignore.Pattern
+
+	if err := afero.Walk(fileSystem, path, func(path string, info fs.FileInfo, _ error) error {
```
Comment (johnstcn) [inline agent/agentcontainers/ignore/dir.go]: > The err argument reports an error related to path, signaling that Walk will not walk into that directory. The function can decide how to handle that error; as described earlier, returning the error will cause Walk to stop walking the entire tree.

https://pkg.go.dev/path/filepath#WalkFunc

File: agent/agentcontainers/ignore/dir_test.go (hunk 1 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir_test.go]: Yeah, I asked Claude to generate a bunch of test cases for me and they looked fine. If you'd prefer I'll go over and remove a bunch of the ones that are effectively just duplicates.

File: agent/agentcontainers/api_test.go (hunk 5 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api_test.go:3364]: Ah, the dev container spec supports both! You can have either `.devcontainer/devcontainer.json` or `.devcontainer.json`

File: agent/agentcontainers/api_test.go (hunk 6 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api_test.go:3353]: Ah looking again at the implementation they've written, it looks like I forgot to handle the `.git/info/exclude` case, will go ahead and add that.

They've also got a function for loading your git config and respecting the ignores from that. I can try and recreate both of those as well (will require recreating because of the different file system abstraction).

File: go.mod (hunk 7 above)
Comment (DanielleMaywood) [reply go.mod:125]: It happened when I added `go-git`, yeah, unfortunate as it feels unrelated.

File: agent/agentcontainers/ignore/dir_test.go (hunk 1 above)
Comment (mtojek) [reply agent/agentcontainers/ignore/dir_test.go]: Yeah, in favour of shorter tests 👍

File: agent/agentcontainers/api_test.go (hunk 6 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api_test.go:3353]: Added in https://github.com/coder/coder/pull/19016/commits/d787bf6e1d404251afde8c423d30fa7269bbb94d and https://github.com/coder/coder/pull/19016/commits/0a438a87ce7192b68bbd1773090a67a5b42a3ba1

File: agent/agentcontainers/ignore/dir_test.go (hunk 1 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir_test.go]: Addressed in https://github.com/coder/coder/pull/19016/commits/8e6c3f3e431b6aca95e0d51e57d737f22976959d

File: agent/agentcontainers/ignore/dir.go (hunk 4 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir.go]: Addressed in https://github.com/coder/coder/pull/19016/commits/e134b47f7929cf5df59035d8425a87e8c36fff32

File: agent/agentcontainers/api_test.go (hunk 5 above)
Comment (mtojek) [reply agent/agentcontainers/api_test.go:3364]: Should we add some tests to check both cases? and maybe fake ones too:  `devcontainer.json.sample` or `devcontainer.json.bak`?

**Review by mtojek — APPROVED** [review]
Awesome!

File: agent/agentcontainers/ignore/dir.go (hunk 8 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir.go]: Should we handle this error then? I'm happy to fail fast and bubble it all the way up if you'd prefer.

**Review by johnstcn — APPROVED** [review]

File: agent/agentcontainers/ignore/dir.go (hunk 8 above)
Comment (johnstcn) [reply agent/agentcontainers/ignore/dir.go]: I'd honestly just log it and continue (exiting the Walk), but I'd rather not ignore it.

File: agent/agentcontainers/api_test.go (hunk 5 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api_test.go:3364]: Addressed in https://github.com/coder/coder/pull/19016/commits/27a735e75b44f1e755991215004d6b6cb8ecac55

File: agent/agentcontainers/ignore/dir.go (hunk 8 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/ignore/dir.go]: Addressed in https://github.com/coder/coder/pull/19016/commits/7d8a7966153a3d5432e2050f1897b759092c5f83
