### PR TITLE
fix: remove refresh oauth logic on OIDC login

### LINKED ISSUE #8537: "Token not active" error when logging in via OIDC
Hi,

Before 0.25, I could log in to my Keycloak instance via another application and then come to my Coder instance and click on the "Open ID Connect" button and since my OIDC session was already started, I would be logged in immediately. 

Now, when I click the button, I get this:
```
{"message":"Could not refresh expired Oauth token.","detail":"oauth2: \"invalid_grant\" \"Token is not active\""}
```

If I delete all cookies, I get the Keycloak log in screen, and I can log in (again) via Keycloak and then everything works as it should. 

I believe something is (still?) wrong with the OIDC refresh process and I'm uncertain it is now my setup or an actual issue. 

Scott

Coder version: 0.26.1
Environment: k8s

### PR DESCRIPTION
**Pull request by Emyrk**
`apiKeyMiddlewareOptional` was being used to log out users if they convert to OIDC. However this logic was also doing an `OIDC` refresh if the original token expired. This was a mistake. That logic should just pull the `APIKey` for logging out, and do not do anything else.

To fix this I just refactored `ExtractAPIKey` into a helper func to call and not do the refresh logic.

A unit test was added that fails on `main` and is now fixed. It matches the behavior of the reports.

Closes https://github.com/coder/coder/issues/8537

### CODE REVIEW

File: coderd/httpmw/apikey.go [hunk 1]
```diff
@@ -142,6 +142,56 @@ func ExtractAPIKeyMW(cfg ExtractAPIKeyConfig) func(http.Handler) http.Handler {
 	}
 }
 
+func APIKeyFromRequest(ctx context.Context, db database.Store, sessionTokenFunc func(r *http.Request) string, r *http.Request) (*database.APIKey, codersdk.Response, bool) {
```
Comment (deansheather) [inline coderd/httpmw/apikey.go:145]: Instead of this could you have just added a field to the opts struct above "NoRefreshToken" or something?

**Review by deansheather — APPROVED** [review]

File: coderd/httpmw/apikey.go (hunk 1 above)
Comment (Emyrk) [reply coderd/httpmw/apikey.go:145]: I could yea, but I didn't want to keep using that middleware for just the key extraction. It could evolve more features overtime and the use case in this situation doesn't ever change/evovle.
