### PR TITLE
fix(site): fix disappearing preset selector when switching template

### LINKED ISSUE #20465: Coder Tasks presets not set correctly when switching between templates
See https://codercom.slack.com/archives/C094GRQG7UZ/p1761323173375519 for more info

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Closes https://github.com/coder/coder/issues/20465

Ensure we set `selectedPresetId` to `undefined` when we change `selectedTemplateId` to ensure we don't end up breaking the `<Select>` component by giving it an invalid preset id.

### CODE REVIEW

**Review by johnstcn — APPROVED** [review]
LGTM, but will happily defer to other reviewers' feedback.

**Comment by aslilac** [comment]
the `key` was added to intentionally unmount the _state_ of the old selector, so that it would be recomputed with a default from the new set of values.

**Comment by DanielleMaywood** [comment]
@aslilac I've re-added the `key` but added a check on the `onValueChange`. Let me know if you want a different approach

File: site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx [hunk 1]
```diff
@@ -319,7 +319,11 @@ const CreateTaskForm: FC<CreateTaskFormProps> = ({ templates, onSuccess }) => {
 										key={`preset-select-${selectedTemplate.active_version_id}`}
 										name="presetID"
 										value={selectedPresetId}
-										onValueChange={setSelectedPresetId}
+										onValueChange={(value) => {
+											if (value) {
```
Comment (aslilac) [inline site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx]: see, this makes it a little clearer what the problem is. why does this get called with a non-truthy value? is this the right level to catch that issue at, or should `onValueChange` not be called to begin with? is there some invalid value in the list or is this because the list is empty?

just wanna make sure this feels like the appropriate spot for the fix, and that the fix is documented so that whoever comes across this next understands why the check is necessary

**Review by aslilac — APPROVED** [review]
I'm fine with this fix, but left some food for thought and would like to see a comment or something describing the pitfalls that the fix is supposed to smooth over

File: site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx (hunk 1 above)
Comment (DanielleMaywood) [reply site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx]: I took another look and if we instead reset the `selectedPresetId` when we change the `selectedTemplateId` we can avoid this entirely (and I guess it also makes more sense?). Otherwise I'm happy to add a comment to explain this and merge it so we can get it cherry picked in

Comment (aslilac) [reply site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx]: that sounds better to me

Comment (DanielleMaywood) [reply site/src/modules/tasks/TaskPrompt/TaskPrompt.tsx]: Change done in https://github.com/coder/coder/pull/20514/commits/45af3878ee6e7b5be559bbd499513127489e40bf
