### PR TITLE
fix: race conditions in replicasync

### LINKED ISSUE #5286: flaky: enterprise/replicasync race detected during execution of test
Spotted in: https://github.com/coder/coder/actions/runs/3605282480/jobs/6075510642

```
=== Failed
=== FAIL: enterprise/replicasync TestReplica/TwentyConcurrent (1.27s)
    testing.go:1319: race detected during execution of test
    --- FAIL: TestReplica/TwentyConcurrent (1.27s)

=== FAIL: enterprise/replicasync TestReplica (0.00s)

DONE 2515 tests, 11 skipped, 2 failures in 162.177s
make: *** [Makefile:476: test-postgres] Error 1
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by mtojek**
Fixes: https://github.com/coder/coder/issues/5286

While fighting with flakes I noticed possible race conditions in `enterprise` (logs in the issue).

### CODE REVIEW

File: enterprise/replicasync/replicasync.go [hunk 1]
```diff
@@ -276,6 +276,8 @@ func (m *Manager) syncReplicas(ctx context.Context) error {
 		return xerrors.Errorf("ping database: %w", err)
 	}
 
+	m.mutex.Lock()
```
Comment (mtojek) [inline enterprise/replicasync/replicasync.go:279]: https://github.com/coder/coder/issues/5286#issuecomment-1337503222

File: enterprise/replicasync/replicasync_test.go [hunk 2]
```diff
@@ -206,7 +206,12 @@ func TestReplica(t *testing.T) {
 				_ = server.Close()
 			})
 			done := false
+
+			var m sync.Mutex
 			server.SetCallback(func() {
+				m.Lock()
```
Comment (mtojek) [inline enterprise/replicasync/replicasync_test.go:212]: https://github.com/coder/coder/issues/5286#issuecomment-1337583804

**Review by kylecarbs — APPROVED** [review]
