### PR TITLE
fix: handle all auth API errors

### LINKED ISSUE #3088: Fix error messages in authXService
Problem: some error messages supplied by the backend are not displayed on the frontend, and in order to fix that in all XServices, we need a plan.

Definition of done:
- All error messages coming from the authXService show backend error messages if they are present, otherwise a fallback message
- The team is happy with the implementation (naming, placement of function calls) for this PR so that it can be used as a template for future PRs in this epic

### PR DESCRIPTION
**Pull request by AbhineetJain**
Building on #3190, this PR handles all the remaining auth API errors:

- ~getUser~ Will handle in a separate PR
- checkPermissions
- getSSHKey
- regenerateSSHKey

## Subtasks

- [x] display the relevant errors using the `ErrorSummary` component.
- [x] add more stories for Sign in form.
- [x] fix unit tests for SSH Key page.
- [x] add stories for SSH Key page.

Makes more progress towards #3088. Leaves handling `getUserError` now.

### getSSHKey
Screen Shot 2022-07-26 at 6 23 44 PM

### regenerateSSHKey
Screen Shot 2022-07-26 at 6 37 14 PM

### CODE REVIEW

File: site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx [hunk 1]
```diff
@@ -19,12 +20,13 @@ export const Language = {
     "You will need to replace the public SSH key on services you use it with, and you'll need to rebuild existing workspaces.",
   confirmLabel: "Confirm",
   cancelLabel: "Cancel",
+  errorRegenerateSSHKey: "Error on regenerate the SSH Key",
```
Comment (presleyp) [inline site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx:23]: Just taking this opportunity to fix a typo, I know it was like this before.
```suggestion
  errorRegenerateSSHKey: "Error on regenerating the SSH Key",
```

File: site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx [hunk 2]
```diff
@@ -33,27 +35,39 @@ export const SSHKeysPage: React.FC = () => {
   return (
     <>
       <Section title={Language.title} description={Language.description}>
-        {!sshKey && (
+        {authState.matches("signedIn.ssh.gettingSSHKey") && (
           <Box p={4}>
             <CircularProgress size={26} />
           </Box>
         )}
```
Comment (presleyp) [inline site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx:42]: We'll never have the progress spinner AND the code below, right? Let's use if/else here to make that clear.

File: site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx [hunk 3]
```diff
@@ -19,12 +20,13 @@ export const Language = {
     "You will need to replace the public SSH key on services you use it with, and you'll need to rebuild existing workspaces.",
   confirmLabel: "Confirm",
   cancelLabel: "Cancel",
+  errorRegenerateSSHKey: "Error on regenerate the SSH Key",
 }
 
 export const SSHKeysPage: React.FC = () => {
   const xServices = useContext(XServiceContext)
```
Comment (presleyp) [inline site/src/pages/UserSettingsPage/SSHKeysPage/SSHKeysPage.tsx:27]: I think you'll find that Storybook won't work because of the XServices here. My plan for cases like these was actually to break this up into two components, so that the rendering happened in a different one that we can Storybook. It's up to you whether to do that in this PR or write a chore ticket for us to get to it later.

File: site/src/pages/LoginPage/LoginPage.tsx [hunk 4]
```diff
@@ -54,8 +56,12 @@ export const LoginPage: React.FC = () => {
...
               redirectTo={redirectTo}
               isLoading={isLoading}
-              authError={authState.context.authError}
-              methodsError={authState.context.getMethodsError as Error}
+              loginErrors={{
+                authError,
+                getUserError,
+                checkPermissionsError,
+                getMethodsError,
+              }}
```
Comment (presleyp) [inline site/src/pages/LoginPage/LoginPage.tsx:64]: Nice!

File: site/src/components/SignInForm/SignInForm.tsx [hunk 5]
```diff
@@ -65,11 +67,17 @@ const useStyles = makeStyles((theme) => ({
   },
 }))
 
+type LoginErrors = {
```
Comment (presleyp) [inline site/src/components/SignInForm/SignInForm.tsx:70]: We use `interface` instead of `type` when possible

File: site/src/components/SignInForm/SignInForm.tsx [hunk 6]
```diff
@@ -101,18 +108,39 @@ export const SignInForm: FC<SignInFormProps> = ({
...
+            <ErrorSummary
+              error={loginErrors.getUserError}
+              defaultMessage={Language.getUserErrorMessage}
+            />
+          )}
+          {loginErrors.checkPermissionsError && (
+            <ErrorSummary
+              error={loginErrors.checkPermissionsError}
+              defaultMessage={Language.checkPermissionsErrorMessage}
+            />
```
Comment (presleyp) [inline site/src/components/SignInForm/SignInForm.tsx:137]: I would DRY this up by mapping over the keys of `loginErrors`

Comment (AbhineetJain) [reply site/src/components/SignInForm/SignInForm.tsx:137]: Thought about it, but we’ll have to map default messages in a separate object for that. I’ll try that!

**Review by presleyp — APPROVED** [review]
I had some suggestions but this is awesome!

File: site/src/components/SignInForm/SignInForm.tsx (hunk 6 above)
Comment (presleyp) [reply site/src/components/SignInForm/SignInForm.tsx:137]: I was thinking if you map over the keys you could do `defaultMessage={Language[errorKey]` if you name them the same

Comment (AbhineetJain) [reply site/src/components/SignInForm/SignInForm.tsx]: Declared an `enum` with error types, and used a `Record<enum, Error>` for iterating through keys. I was not able iterate through the properties of a `type` or `interface`.

**Comment by AbhineetJain** [comment]
@presleyp Might need some pairing help on this one, but since we are showing `getUserError` in FE now, we see this when loading the home page, as the code tries to fetch the user first before prompting for log in:
Screen Shot 2022-07-28 at 5 08 47 AM

**Comment by presleyp** [comment]
> @presleyp Might need some pairing help on this one, but since we are showing `getUserError` in FE now, we see this when loading the home page, as the code tries to fetch the user first before prompting for log in: Screen Shot 2022-07-28 at 5 08 47 AM

Ah, yes! There was some talk about whether it was correct that an error is thrown at this point, so I suggest checking with the backend team about whether they want it to throw, and if so I guess just don't show that one. But happy to pair.
