### PR TITLE
fix: display explicit 'retry' button(s) when a workspace fails

### LINKED ISSUE #7329: UI shows Stop & Start buttons for workspace in a failed state
version `0.23.0`

the user is shown the `Stop`, `Start`, and `Try again in debug` mode buttons when viewing a workspace in a failed state. this UX is confusing as `Stop` suggests the workspace is running, while `Start` suggests it's in an off state.

Screenshot 2023-04-29 at 9 19 29 PM

this is exacerbated when the template for failed workspace has been updated, adding the "Update" button to the view:

Screenshot 2023-04-29 at 9 20 33 PM

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #7329

Screenshot 2023-11-17 at 9 46 03 AM

## Changes made
- Makes it so that if a workspace fails, the "workspace button tray" will display a Retry button
   - If the user has the ability to see debug logs, an additional "Retry (Debug)" button will also display
   - We already had some logic in place for the retry debug button before, but it was only ever displayed in an error alert. If the user didn't have debug log permissions, no retry button would appear at all, and they wouldn't have a clear action to take. The alert is still there, but now, if the user has no debug permissions, they'll get the lower-level Retry button inside the alert instead
   - Having the buttons in multiple spots introduces a little UI redundancy, but since this logic deals with errors, it felt like it made sense, just to make sure the user was super clear on what to do
- Removes enums in favor of union types for defining workspace errors and workspace button types. The new code is more concise and has fewer imports, with no loss in type-safety
- Adds in tests for Retry functionality (six cases total: three workspace transitions with two debug levels) 
   - Also updates the previous test utilities to parameterize the workspace being used for mocking, rather than assuming it will always be the same default mock workspace

### CODE REVIEW

File: site/src/pages/WorkspacePage/Workspace.tsx [hunk 1]
```diff
@@ -87,55 +90,39 @@ export const Workspace: FC<React.PropsWithChildren<WorkspaceProps>> = ({
...
   onLoadMoreBuilds,
   isLoadingMoreBuilds,
   hasMoreBuilds,
   canAutostart,
 }) => {
   const navigate = useNavigate();
-  const serverVersion = buildInfo?.version || "";
   const { saveLocal, getLocal } = useLocalStorage();
 
-  const buildError = Boolean(workspaceErrors[WorkspaceErrors.BUILD_ERROR]) && (
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/Workspace.tsx:117]: These two booleans were moved into the JSX, to move them closer to where they're actually used

File: site/src/pages/WorkspacePage/Workspace.tsx [hunk 2]
```diff
@@ -87,55 +90,39 @@ export const Workspace: FC<React.PropsWithChildren<WorkspaceProps>> = ({
...
-  if (template !== undefined) {
-    transitionStats = ActiveTransition(template, workspace);
-  }
-
   const [showAlertPendingInQueue, setShowAlertPendingInQueue] = useState(false);
+
+  // 2023-11-15 - MES - This effect will be called every single render because
+  // "now" will always change and invalidate the dependency array. Need to
+  // figure out if this effect really should run every render (possibly meaning
+  // no dependency array at all), or how to get the array stabilized (ideal)
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/Workspace.tsx:125]: Having the effect re-run every single render isn't ideal, but I don't think it's breaking anything

Sometime in December, I'm planning to do an audit for every single `useEffect`/`useLayoutEffect` call we have. I know we have a couple of other wonky calls, too

File: site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx [hunk 3]
```diff
@@ -57,81 +57,72 @@ export const WorkspaceActions: FC<WorkspaceActionsProps> = ({
...
-    [ButtonTypesEnum.updating]: (
-      <UpdateButton loading handleAction={handleUpdate} />
-    ),
-    [ButtonTypesEnum.start]: (
-      <StartButton workspace={workspace} handleAction={handleStart} />
-    ),
-    [ButtonTypesEnum.starting]: (
+  // A mapping of button type to their corresponding React components
+  const buttonMapping: Record<ButtonType, ReactNode> = {
+    update: <UpdateButton handleAction={handleUpdate} />,
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx:74]: Lot of diffs, but only two major things changed:
- Enums got factored out, cleaning up how the properties were defined
- `retry` and `retryDebug` properties got added

File: site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx [hunk 4]
```diff
@@ -57,81 +57,72 @@ export const WorkspaceActions: FC<WorkspaceActionsProps> = ({
...
     <div
       css={{ display: "flex", alignItems: "center", gap: 12 }}
       data-testid="workspace-actions"
     >
-      {canBeUpdated &&
-        (isUpdating
-          ? buttonMapping[ButtonTypesEnum.updating]
-          : buttonMapping[ButtonTypesEnum.update])}
+      {canBeUpdated && (
+        <>{isUpdating ? buttonMapping.updating : buttonMapping.update}</>
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx:115]: Not a huge change, but I wanted to make it super explicit that the logic was accounting for three cases:
1. Render nothing if `canBeUpdated` is false
2. Render updating component
3. Render update component

File: site/src/pages/WorkspacePage/WorkspacePage.test.tsx [hunk 5]
```diff
@@ -34,24 +37,33 @@ const renderWorkspacePage = async () => {
...
- * Requests and responses related to workspace status are unrelated, so we can't test in the usual way.
- * Instead, test that button clicks produce the correct requests and that responses produce the correct UI.
- * We don't need to test the UI exhaustively because Storybook does that; just enough to prove that the
- * workspaceStatus was calculated correctly.
+ * Requests and responses related to workspace status are unrelated, so we can't
+ * test in the usual way. Instead, test that button clicks produce the correct
+ * requests and that responses produce the correct UI.
+ *
+ * We don't need to test the UI exhaustively because Storybook does that; just
+ * enough to prove that the workspaceStatus was calculated correctly.
```
Comment (Parkreiner) [inline site/src/pages/WorkspacePage/WorkspacePage.test.tsx:55]: Just reformatted the comment to properly fit an 80-character width

**Comment by Parkreiner** [comment]
Going to double-check the Storybook tests later this morning – I don't have great internet where I am right now, and the pages are taking ages to load in

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx [hunk 6]
```diff
@@ -242,19 +255,11 @@ export const WorkspaceReadyPage = ({
...
-            case "stop":
-              stopWorkspaceMutation.mutate({ logLevel: "debug" });
-              break;
-            case "delete":
-              deleteWorkspaceMutation.mutate({ logLevel: "debug" });
-              break;
-          }
-        }}
+        handleBuildRetry={() => handleBuildRetry(false)}
+        handleBuildRetryDebug={() => handleBuildRetry(true)}
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:259]: Instead of passing 2 props here, can we just have `handleBuildRetry` and then pass it a boolean in the `Workspace` component?

File: site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx (hunk 3 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx:74]: I think that enum was my complication; thanks for fixing :)

File: site/src/pages/WorkspacePage/WorkspaceActions/constants.ts [hunk 7]
```diff
@@ -1,59 +1,76 @@
...
+  "deleted",
+  "pending",
+] as const;
 
-interface WorkspaceAbilities {
-  actions: ButtonTypesEnum[];
+/**
+ * A button type supported by the workspace actions UI
+ */
+export type ButtonType = (typeof buttonTypes)[number];
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspacePage/WorkspaceActions/constants.ts:35]: I'm not familiar with this syntax...what is going on here?

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx (hunk 6 above)
Comment (Parkreiner) [reply site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:259]: That would work – my main concern with setting up the functions the way I did was insulating the downstream components from changes, or having implementation details leak out

Right now, `handleBuildRetry` and `handleBuildRetryDebug` happen to use the same implementation under the hood, but that's just kind of by coincidence. If `WorkspaceReadyPage` ever gets to the point where the two functions need to look drastically different, we can change things in the one file, and none of the other components have to be any the wiser

I am aware that it does kind of increase the number of props (when we already have a lot), but keeping the other components blind to the implementation details seemed like the lesser of two evils to me

**Review by Kira-Pilot — APPROVED** [review]
This looks great! Nice work.

File: site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx (hunk 6 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx:259]: > If WorkspaceReadyPage ever gets to the point where the two functions need to look drastically different, we can change things in the one file, and none of the other components have to be any the wiser
I think we might be pre-optimizing here, but I'm happy to keep as-is!

File: site/src/pages/WorkspacePage/WorkspaceActions/constants.ts (hunk 7 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspacePage/WorkspaceActions/constants.ts:35]: Appreciate the explanation. It would be nice to use this syntax with `TypesGen.WorkspaceTransitions` but idk how to make that happen on the Go side
