### PR TITLE
fix: update install.sh to remove dead doc link

### LINKED ISSUE #13392: install.sh script contains 404 docs link
When there's a path conflict after installing via the one-liner script, an error throws with a link to a doc that no longer exists.

https://github.com/coder/coder/blob/main/install.sh#L237C1-L248C2

### PR DESCRIPTION
**Pull request by Kira-Pilot**
My friend ran into both this PATH conflict and our dead doc link while trying to use Coder. Looks like we removed the specific install docs in [this PR](https://github.com/coder/coder/pull/11465) so I'm just updating our error message to be a bit more descriptive!

Closes #13392

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -240,9 +240,9 @@ There is another binary in your PATH that conflicts with the binary we've instal
 
   $1
 
-This is likely because of an existing installation of Coder. See our documentation for suggestions on how to resolve this.
-
-  https://coder.com/docs/v2/latest/install/install.sh#path-conflicts
+This is likely because of an existing installation of Coder resulting in multiple Coder binaries in your PATH.
+You can check where all of the versions are located by running \`which -a coder\`.
+Whichever binary comes first in the returned list will be used when running Coder commands.
```
Comment (kylecarbs) [inline install.sh:245]: I trimmed up the language a bit, let me know your thoughts!

Could you manually confirm that `$PATH` is properly escaped here if accepted?

```suggestion
This is likely because of an existing installation of Coder in your \$PATH.

Run `which -a coder` to view all installations.
```

Comment (mafredri) [reply install.sh:245]: Probably not necessary, but:
> Run `which -a coder` to view all installations.
to:
> Run `which -a coder` to view all installations (first come, first served).

Comment (aslilac) [reply install.sh:245]: I like Kyle's version as is personally

**Comment by stirby** [comment]
@Kira-Pilot can we merge?

**Comment by Kira-Pilot** [comment]
> @Kira-Pilot can we merge?

Yup wanna give me the green light @stirby?

**Review by stirby — APPROVED** [review]
🟢 Nice.
