### PR TITLE
fix: stop disconnecting from coderd early and record disconnect correctly

### LINKED ISSUE #1196: flake: coderd TestWorkspaceWatcher
copied from https://github.com/coder/internal/issues/550#issuecomment-3639238220 because it's a separate issue.

CI run: https://github.com/coder/coder/actions/runs/20114690657
- Failing job: test-go-race-pg (run_attempt: 1)
- Job completed at: 2025-12-10T22:32:39Z; Slack alert at 2025-12-10T22:32:58Z (same minute)
- Commit: 8ed1c1d3720b40a5dcc41c8a17debf93b36d3537 (author: Callum Styan)

Failure evidence (excerpt):
```
=== Failed
=== FAIL: coderd TestWorkspaceWatcher (26.09s)
...
Error Trace: /home/runner/work/coder/coder/coderd/workspaces_test.go:3420
             /home/runner/work/coder/coder/coderd/workspaces_test.go:3458
Error:       timed out waiting for event
Test:        TestWorkspaceWatcher
Messages:    agent disconnected
...
DONE 13271 tests, 63 skipped, 1 failure in 431.105s
```

Classification: Flaky test (timeout)
- No data race signatures found (no "WARNING: DATA RACE" or "race detected during execution of test").
- No process crashes or OOM indicators in logs.

Ownership analysis:
- Failing test function: TestWorkspaceWatcher in coderd/workspaces_test.go (approx. lines 3372–3519 on main).
- Attempted to identify last modifier of the function; could not reliably establish function-level blame via API. Recent file contributors include multiple authors across unrelated areas.
- Leaving unassigned for now; tagging area: coderd/workspace events/agent lifecycle.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes https://github.com/coder/internal/issues/1196

The above issue exposes two different bugs in Coder.

In the agent, there is a race where if the agent is closed while starting up networking, it will erroneously disconnect from Coderd, which delays or breaks writing final status and logs.

In Coderd, there is a bug where we don't properly record the latest agent disconnection time if the agent had previously disconnected. This causes us to report the agent status as "Connected" even after it has disconnected up until the inactivity timeout fires.

This PR fixes both issues.

It also slightly reworks when we send workspace updates based on connection and disconnection. Previously we would send two updates when the agent connected in certain circumstances, even though the status would be the same in both (only times changed).  Now we universally only send one on connect, and then another on disconnect.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#21250** <a href="https://app.graphite.com/github/pr/coder/coder/21250?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/coder/21250?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: agent/agent.go [hunk 1]
```diff
@@ -1348,7 +1351,7 @@ func (a *agent) createOrUpdateNetwork(manifestOK, networkOK *checkpoint) func(co
 			a.closeMutex.Unlock()
 			if closing {
 				_ = network.Close()
-				return xerrors.New("agent is closing")
+				return ErrAgentClosing
```
Comment (mafredri) [inline agent/agent.go]: Suggestion: Wrap error for consistency?

File: coderd/workspaceagentsrpc.go [hunk 2]
```diff
@@ -403,6 +396,10 @@ func (m *agentConnectionMonitor) monitor(ctx context.Context) {
 		m.logger.Debug(ctx, "agent connection monitor is closing connection",
 			slog.F("reason", reason))
 		_ = m.conn.Close(websocket.StatusGoingAway, reason)
+		m.disconnectedAt = sql.NullTime{
+			Time:  dbtime.Now(),
+			Valid: true,
+		}
 	}()
```
Comment (mafredri) [inline coderd/workspaceagentsrpc.go]: Perhaps a larger change than you were intending for, but wouldn't it make sense to combine these two defer's? In the current state they muddy the exit path of the routine.

**Review by mafredri — APPROVED** [review]
Nice find!

We should simplify the defer in monitor, but otherwise logic seems sound, approving. 👍🏻

File: coderd/workspaceagentsrpc.go (hunk 2 above)
Comment (spikecurtis) [reply coderd/workspaceagentsrpc.go]: Done

**Comment by spikecurtis** [comment]
### Merge activity

* **Dec 15, 8:04 AM UTC**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.com/github/pr/coder/coder/21250).
