### PR TITLE
fix: fix PG Coordinator to update when heartbeats (re)start

### LINKED ISSUE #8161: flake: TestPGCoordinatorDual_Mainline
I think what's happening is that the node updates all arrive before the first heartbeats.  Right now we trigger updates when heartbeats _remove_ a coordinator, but we should also trigger those updates when heartbeats _add_ a coordinator.

```
=== FAIL: enterprise/tailnet TestPGCoordinatorDual_Mainline (60.11s)
    t.go:85: 2023-06-22 14:38:16.241 [info]  pgcoord: serving connection  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  client_id=5377dccc-d512-4516-a11c-9c7bed72d559
    t.go:85: 2023-06-22 14:38:16.242 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.243 [info]  pgcoord: serving connection  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  name=""  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2
    t.go:85: 2023-06-22 14:38:16.250 [info]  pgcoord: serving connection  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  name=""  agent_id=b33080f4-631c-40d2-bb57-032330b7c073
    t.go:85: 2023-06-22 14:38:16.250 [info]  pgcoord: serving connection  coordinator_id=69af[281](https://github.com/coder/coder/actions/runs/5346881447/jobs/9694534888#step:5:282)e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  client_id=4ee743ab-9507-4940-a8fd-8f8400521663
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord: got node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  client_id=4ee743ab-9507-4940-a8fd-8f8400521663  node={"id":0,"as_of":"0001-01-01T00:00:00Z","key":"nodekey:0000000000000000000000000000000000000000000000000000000000000000","disco":"discokey:0000000000000000000000000000000000000000000000000000000000000000","preferred_derp":11,"derp_latency":null,"derp_forced_websockets":null,"addresses":null,"allowed_ips":null,"endpoints":null}
    t.go:85: 2023-06-22 14:38:16.250 [info]  pgcoord: serving connection  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  client_id=540debbc-7db6-47ab-b268-730923e87db1
    t.go:85: 2023-06-22 14:38:16.250 [info]  pgcoord: serving connection  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  client_id=b53fce9d-26ff-4b01-bfd0-2d885eaa2c16
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=true
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=true
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.250 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.261 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.262 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=true
    t.go:85: 2023-06-22 14:38:16.265 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=true
    t.go:85: 2023-06-22 14:38:16.266 [debu]  pgcoord: sent heartbeat  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9
    t.go:85: 2023-06-22 14:38:16.268 [debu]  pgcoord: sent heartbeat  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e
    t.go:85: 2023-06-22 14:38:16.276 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=b33080f4-631c-40d2-bb57-032330b7c073  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.281 [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:16.[287](https://github.com/coder/coder/actions/runs/5346881447/jobs/9694534888#step:5:288) [debu]  pgcoord.querier: skipping 0 length node update  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  agent_id=65e64e92-0e65-4a10-9204-11da8dc817a2  clients_of_agent=false
    t.go:85: 2023-06-22 14:38:18.268 [debu]  pgcoord: sent heartbeat  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9
    t.go:85: 2023-06-22 14:38:18.268 [debu]  pgcoord: got heartbeat  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e  other_coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9
    t.go:85: 2023-06-22 14:38:18.268 [debu]  pgcoord: set initial heartbeat timeout  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e
    t.go:85: 2023-06-22 14:38:18.268 [debu]  pgcoord: ignoring our own heartbeat  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9
    t.go:85: 2023-06-22 14:38:18.270 [debu]  pgcoord: ignoring our own heartbeat  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e
    t.go:85: 2023-06-22 14:38:18.270 [debu]  pgcoord: sent heartbeat  coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e
    t.go:85: 2023-06-22 14:38:18.270 [debu]  pgcoord: got heartbeat  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9  other_coordinator_id=adba35e0-122d-48ee-bfef-8e47b867872e
    t.go:85: 2023-06-22 14:38:18.270 [debu]  pgcoord: set initial heartbeat timeout  coordinator_id=69af281e-4b91-40cb-b646-b855178d7eb9
   ```

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #8161 

Also fixes a related issue I noticed with the heartbeats, where if there are multiple coordinators and one expires, we don't reschedule the check for others expiring unless a new heartbeat comes in, so if two coordinators stop beating around the same time, we'd only expire one of them.  Test updated to check for both this and the initial bug.

### CODE REVIEW

File: enterprise/tailnet/pgcoord.go [hunk 1]
```diff
@@ -1140,7 +1146,11 @@ func (h *heartbeats) recvBeat(id uuid.UUID) {
 		h.logger.Debug(h.ctx, "set initial heartbeat timeout")
 		return
 	}
+	h.resetExpiryTimer()
+}
 
+func (h *heartbeats) resetExpiryTimer() {
```
Comment (mtojek) [inline enterprise/tailnet/pgcoord.go:1152]: nit: Does `resetExpiryTimer` requires a lock? If so, maybe rename the method to emphasize it (`..WithLock`).

File: enterprise/tailnet/pgcoord.go [hunk 2]
```diff
@@ -1131,7 +1131,13 @@ func (h *heartbeats) recvBeat(id uuid.UUID) {
 	h.logger.Debug(h.ctx, "got heartbeat", slog.F("other_coordinator_id", id))
 	h.lock.Lock()
 	defer h.lock.Unlock()
-	var oldestTime time.Time
+	if _, ok := h.coordinators[id]; !ok {
+		h.logger.Info(h.ctx, "heartbeats (re)started", slog.F("other_coordinator_id", id))
+		// send on a separate goroutine to avoid holding lock.  Triggering update can be async
+		go func() {
```
Comment (mtojek) [inline enterprise/tailnet/pgcoord.go:1137]: 1. Is it necessary to monitor this goroutine in light of concurrency safety?
2. Is it possible that `sendCtx` is called the second time, but the first execution is still in progress?

File: enterprise/tailnet/pgcoord.go [hunk 3]
```diff
@@ -1168,10 +1179,14 @@ func (h *heartbeats) checkExpiry() {
 			h.logger.Info(h.ctx, "coordinator failed heartbeat check", slog.F("other_coordinator_id", id), slog.F("last_heartbeat", lastHB))
 		}
 	}
-	h.lock.Unlock()
 	if expired {
-		_ = sendCtx(h.ctx, h.update, struct{}{})
+		// send on a separate goroutine to avoid holding lock.  Triggering update can be async
+		go func() {
```
Comment (mtojek) [inline enterprise/tailnet/pgcoord.go:1184]: Same questions (1. 2.) as above

File: enterprise/tailnet/pgcoord.go (hunk 2 above)
Comment (spikecurtis) [reply enterprise/tailnet/pgcoord.go:1137]: `sendCtx()` just sends on the given channel, or, if the context expires, returns the context error.  The idea is that if the coordinator is shut down, we don't want any goroutines blocked on sending data across internal channels.  This makes it so we don't have to worry too much about the order in which the different goroutines shut down.  If the channel consumer shuts down first, it's fine because the sender will also close down when the context expires.

So, do directly answer your questions, 

1. No, its not necessary to monitor the goroutine.
2. It is possible that multiple goroutines call `sendCtx()` attempt to write to the channel, but that's explicitly allowed in go.

File: enterprise/tailnet/pgcoord.go (hunk 1 above)
Comment (spikecurtis) [reply enterprise/tailnet/pgcoord.go:1152]: it does require the lock.  I'll rename

File: enterprise/tailnet/pgcoord.go (hunk 2 above)
Comment (mtojek) [reply enterprise/tailnet/pgcoord.go:1137]: > It is possible that multiple goroutines call sendCtx() attempt to write to the channel

Alright, I assumed that it could be feasible to check that the previous `sendCtx` hangs, so there is no need to spawn more goroutines if we know that there is any congestion.

Comment (mtojek) [reply enterprise/tailnet/pgcoord.go:1137]: > No, its not necessary to monitor the goroutine.

> if the context expires, returns the context error

To give more context - it happens relatively often in unit tests that a component is leaking a goroutine. I was curious if the coordinator should implement graceful shutdown.

**Review by mtojek — APPROVED** [review]

File: enterprise/tailnet/pgcoord.go (hunk 2 above)
Comment (spikecurtis) [reply enterprise/tailnet/pgcoord.go:1137]: > it happens relatively often in unit tests that a component is leaking a goroutine. I was curious if the coordinator should implement graceful shutdown.

Yep, that's why I've implemented these context-limited channel writes, to make it easy to ensure that channel writes are never blocked beyond the given context, even if the receiver goes away.
