### PR TITLE
fix: create centralized PaginationContainer component

### LINKED ISSUE #10589: Adding safety nets and better performance to paginated tables
Spurred by #10452 and #10549
Partially addressed already with #10567 and #10561
Overlaps somewhat with #10587

Basically, I think the pagination logic could have some extra "safety nets" and some other UI niceties to help avoid user confusion and keep the UI feeling responsive. This would affect the following tables:
- Users table
- Audits table
- Workspaces table

## Safety nets and bug fixes
1. Make sure that if the user accidentally navigates to an "invalid" table page, there's *something* (automatic or manual) that makes it easy for them to get back to a valid page (right now, the page navigation UI disappears entirely)
2. Make sure that when the user changes pages, the browser will always bring them back to the top of the table (but maybe make it so that this doesn't happen if they start scrolling or doing anything while waiting for the new data to load in? Don't want to hijack their controls if they're in the middle of something)
3. Make sure data for each page is cached properly, so that if you go to a page you've already visited, you see the data immediately

## Niceties
1. After a new page loads in, prefetch the next and previous pages (when it makes sense)

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #10589 (in combination with #10803).

## Changes made
- Creates general-purpose `PaginationContainer` component that:
   - Centralizes a lot of pagination view concerns that were split across several different components throughout the codebase
   - Adds the component to the Users and Audits tables
   - Is set up to for easy interfacing with `usePaginatedQuery`
   - Handles auto-scrolling the user to the top of a table when the page changes (doing it in the least aggressive way possible, with tests in place to help verify that scrolls only happen when they won't be obtrusive to the user)
   - Has updated logic for generating labels for the tops of each table (numbers are now always correct)
- Updates the return type for `usePaginatedQuery` to make generating table labels easier
- Updates the `renderComponent` test utility so that it can safely re-render without any risks of throwing out the previous render state

## Notes
- Pasting this from the other PR: untangling the Workspaces table from its current implementation proved to be a little too much for this sprint; had to defer switching that table over to a later sprint
   - Still tried to bring over as much of the new code as I could
- There's a lot of disparate steps to the scrolling logic for PaginationContainer; it might help to look at the names of each of its test cases first just to get an idea for what it's trying to account for

### CODE REVIEW

File: site/src/testHelpers/renderHelpers.tsx [hunk 1]
```diff
@@ -266,6 +266,8 @@ export const waitForLoaderToBeRemoved = async (): Promise<void> => {
   );
 };
 
-export const renderComponent = (component: React.ReactNode) => {
-  return tlRender(<ThemeProviders>{component}</ThemeProviders>);
+export const renderComponent = (component: React.ReactElement) => {
+  return tlRender(component, {
+    wrapper: ({ children }) => <ThemeProviders>{children}</ThemeProviders>,
```
Comment (Parkreiner) [inline site/src/testHelpers/renderHelpers.tsx:271]: Had to make this change because not using the wrapper causes manual re-renders to break during testing

**Comment by Parkreiner** [comment]
Gonna have to make a couple of changes to the stories, but most of them cleared
Worst example was one of the stories displaying NaN values

**Review by Kira-Pilot — APPROVED** [review]
Nice! I pulled down and took a look - works really well.
One piece of non-blocking feedback that we could look at in another PR: I find it a little cumbersome to scroll through an entire page of records to access the pagination widget. I click, am scrolled up to the top, and then have to scroll down again to find the widget. I wonder if we could just move the widget to the top of the page or duplicate it in a simpler form.

File: site/src/components/PaginationWidget/PaginationContainer.test.tsx [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+  mockInitialRenderResult,
+  mockSuccessResult,
+} from "./PaginationContainer.mocks";
+
+beforeAll(() => {
+  jest.useFakeTimers();
+});
+
+afterAll(() => {
+  jest.clearAllMocks();
```
Comment (BrunoQuaresma) [inline site/src/components/PaginationWidget/PaginationContainer.test.tsx:16]: I think in the jest setup file we already clear all the mocks after each test.

File: site/src/components/PaginationWidget/PaginationContainer.test.tsx [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+            paginationResult={{
+              ...mockSuccessResult,
+              currentPage: 2,
+              isPreviousData: false,
+            }}
+          />,
+        );
+
+        await assertNoScroll(mockScroll);
+        unmount();
```
Comment (BrunoQuaresma) [inline site/src/components/PaginationWidget/PaginationContainer.test.tsx:207]: Why do we have to explicitly unmount?

File: site/src/components/PaginationWidget/PaginationContainer.tsx [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+
+    if (showingPreviousData) {
+      isScrollingQueuedRef.current = true;
+    } else {
+      scrollToTop();
+    }
+  });
+
+  // Would've liked to consolidate these effects into a single useLayoutEffect
+  // call, but they kept messing each other up when grouped together
```
Comment (BrunoQuaresma) [inline site/src/components/PaginationWidget/PaginationContainer.tsx:157]: Do we know the reason?

File: site/src/pages/UsersPage/UsersPageView.tsx [hunk 5]
```diff
@@ -60,54 +54,38 @@ export const UsersPageView: FC<React.PropsWithChildren<UsersPageViewProps>> = ({
...
-
-      {count !== undefined && (
-        <PaginationWidgetBase
-          totalRecords={count}
-          pageSize={limit}
-          onPageChange={onPageChange}
-          currentPage={page}
+      <PaginationContainer
+        paginationResult={usersQuery}
+        paginationUnitLabel="users"
```
Comment (BrunoQuaresma) [inline site/src/pages/UsersPage/UsersPageView.tsx:66]: Nit: Since the component is already a Pagination thing I don't think we should prefix the props with `pagination` because the component name makes it clear enough IMO.

**Review by BrunoQuaresma — APPROVED** [review]
Code looks good but I have mixed feelings. For me, it looks we are adding a lot of complexity to handle scrolling.

**Comment by BrunoQuaresma** [comment]
@Parkreiner if you are interested in design work, the improvement that @Kira-Pilot suggested is a good one. I was planning to refactor the pagination component design but I didn't have time yet. So let me know if you are interested or not, I know you have the Backstage integration stuff on your plate so np.

File: site/src/components/PaginationWidget/PaginationContainer.test.tsx (hunk 3 above)
Comment (Parkreiner) [reply site/src/components/PaginationWidget/PaginationContainer.test.tsx:207]: Because the loop creates a new version of the UI per iteration. But if you don't unmount the previous one, the old UI from the last render sticks around and can cause some issues with test utilities

This happens automatically for most test cases, but it needs to be done manually here because multiple renders are happening before the test case can get garbage-collected

File: site/src/components/PaginationWidget/PaginationContainer.tsx (hunk 4 above)
Comment (Parkreiner) [reply site/src/components/PaginationWidget/PaginationContainer.tsx:157]: It's not because it's an unknown reason – it's more that there are two "sync cues" that the UI needs to account for, and trying to squeeze both of them into one layout effect just got a little unruly. It felt more manageable to set up one effect for the page changes, and one for fetching state, especially since they can change independently

I can rewrite the comment to make that more clear, though

File: site/src/pages/UsersPage/UsersPageView.tsx (hunk 5 above)
Comment (Parkreiner) [reply site/src/pages/UsersPage/UsersPageView.tsx:66]: Yeah, I can agree. I can rename it

**Comment by Parkreiner** [comment]
@BrunoQuaresma Yeah, I agree with you about the complexity, and I wish there were a more straightforward way to side-step it (that's sort of why I put a lot of effort into the tests to at least help document what the logic is supposed to do)

But the pagination is one of the areas where turning on query caching caused the UI to get a little weird. Right now, the scrollbar inconsistently jumps around between page transitions anyway (especially when jumping from/to pages that aren't fully filled out), so I felt like it'd be good to make sure the scrollbar is more consistent for all transitions

I think @Kira-Pilot 's idea about adding mini navigation sounds really good, but I don't know if I'll have time to do it for the rest of the year, especially if Backstage stuff keeps taking priority. At least for the moment, though, I can kind of flip the script – instead of consistently scrolling to the top of the container, it can consistently scroll to the bottom, so that the UI buttons stay within reach

**Comment by Parkreiner** [comment]
@BrunoQuaresma @Kira-Pilot I ended up removing the scroll functionality completely – the more I played with it, the more I realized that there were cases that weren't being handled properly, and I didn't want to increase the complexity more. I [stashed the changes away here](https://gist.github.com/Parkreiner/6e58a0a9668d704633df4d3255cc9f77), so that it's easier to revisit things down the line

Also, scrolling to the bottom started breaking one of the AuditPage tests, which didn't seem great
