### PR TITLE
fix(agent/agentssh): allow remote forwarding a socket multiple times

### LINKED ISSUE #11198: Allow new RemoteForward to override existing RemoteForward in Coder Agent
If a client that is SSH `RemoteForward`ing from their workspace is abruptly disconnected, the SSH server isn't immediately notified because the TCP sessions can be held open for a long time (currently 72h), and we currently block other SSH connections from `RemoteForward` the same target Unix socket path (and TCP port).

This can put the workspace in a state where RemoteForward no longer works unless they restart the workspace or the old TCP session times out.

Since Coder workspaces (unlike a general SSH server) are meant for a single user, we could fix this problem by allowing new connections to override previous `RemoteForward` requests.  The target would begin forwarding to a new connection that requests it and cease forwarding to the old connection.

We have a customer trying to configure remote forwarding to happen by default, and blocking remote forwarding based on a failed, old connection is making this unusable.

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #11198
Fixes https://github.com/coder/customers/issues/407

For this PR, I implemented a new test in `cli/ssh_test.go`, however, in future, we should consider doing more extensive testing for forwarding within the `agent/agentssh` package.

### CODE REVIEW

File: agent/agentssh/forward.go [hunk 1]
```diff
@@ -62,13 +72,17 @@ func (h *forwardedUnixHandler) HandleSSHRequest(ctx ssh.Context, _ *ssh.Server,
...
 		h.Lock()
-		_, ok := h.forwards[addr]
+		_, ok := h.forwards[key]
 		h.Unlock()
 		if ok {
-			log.Warn(ctx, "SSH unix forward request for socket path that is already being forwarded (maybe to another client?)",
-				slog.F("socket_path", addr),
-			)
+			log.Warn(ctx, "SSH unix forward request for socket path that is already being forwarded on this session")
 			return false, nil
```
Comment (mafredri) [inline agent/agentssh/forward.go:86]: Review: Do we want to match OpenSSH even more closely here?

```suggestion
			// Forwarding a socket to the same location twice does not produce
			// an error for OpenSSH, we match that behavior here.
			//
			// Example: ssh -R /tmp/sock:/my/sock -R /tmp/sock:my/other/sock
			//
			// In this case, the second forward will be ignored.
			log.Warn(ctx, "SSH unix forward request for socket path that is already being forwarded on this session, ignoring")
			return true, nil
```

File: agent/agentssh/forward.go [hunk 2]
```diff
@@ -209,3 +233,14 @@ func directStreamLocalHandler(_ *ssh.Server, _ *gossh.ServerConn, newChan gossh.
 
 	Bicopy(ctx, ch, dconn)
 }
+
+// unlink removes files only.
+func unlink(path string) error {
+	// From os/file_posix.go:
```
Comment (spikecurtis) [inline agent/agentssh/forward.go:239]: I read this comment as meaning that `unlink` is implemented in `file_posix.go`, but I think it's just this `EINTR` loop construct --- needs a comment why it's even required, rather than just where it's from.

File: agent/agentssh/forward.go [hunk 3]
```diff
@@ -209,3 +233,14 @@ func directStreamLocalHandler(_ *ssh.Server, _ *gossh.ServerConn, newChan gossh.
...
+	for {
+		err := syscall.Unlink(path)
```
Comment (spikecurtis) [inline agent/agentssh/forward.go:241]: I don't understand why we're using syscall directly instead of the higher level `os` functions.  Is it just because we only want to unlink files and `os.Remove()` removes directories?

If we are using syscalls, do we need to include build flags so we don't try this on Windows and return a sensible error?

File: cli/ssh_test.go [hunk 4]
```diff
@@ -771,6 +773,116 @@ func TestSSH(t *testing.T) {
...
+
+			// Since something was output, it should be safe to write input.
+			// This could show a prompt or "running startup scripts", so it's
+			// not indicative of the SSH connection being ready.
+			_ = pty.Peek(ctx, 1)
+
+			// Ensure the SSH connection is ready by testing the shell
+			// input/output.
+			pty.WriteLine("echo ping' 'pong")
+			pty.ExpectMatchContext(ctx, "ping pong")
```
Comment (spikecurtis) [inline cli/ssh_test.go:846]: using the CLI to test the agent is awkward and this is an example.  This test would be easier to write and easier to understand if were in `agent_test.go` and we could use the go ssh client.

File: agent/agentssh/forward.go (hunk 1 above)
Comment (spikecurtis) [reply agent/agentssh/forward.go:86]: If we get more than one call to start forwarding, would we get more than one call to stop? I there could be all kinds of different behaviors depending on the client code, so sticking close to what OpenSSH does on the server side is a good idea.

Comment (mafredri) [reply agent/agentssh/forward.go:86]: Interestingly, OpenSSH does _not_ seem to send `cancel-streamlocal-forward@openssh.com`. So there's no call to stop, the forwarding simply stops because the session closes. Yet more interestingly, our client does. It does so for both forwarded sockets (i.e. two times), even though they're remote destination is the same. I think both behaviors are fine, and sending `cancel-streamlocal-forward@openssh.com` twice for the same socket also doesn't seem harmful.

One motivation to follow `OpenSSH` here and return `true` is that it will affect the OpenSSH setting of `ExitOnForwardFailure`. If set to `yes`, and we return `false` here, then SSH cannot be established (`Error: remote port forwarding failed for listen path /tmp/echo.sock`).

Why is OpenSSH so lax here? I honestly don't know. It does seem like a potential foot-gun for users, but I'm still in favor of matching OpenSSH.

File: agent/agentssh/forward.go [hunk 5]
```diff
@@ -144,12 +159,11 @@ func (h *forwardedUnixHandler) HandleSSHRequest(ctx ssh.Context, _ *ssh.Server,
 			}
 
 			h.Lock()
-			ln2, ok := h.forwards[addr]
-			if ok && ln2 == ln {
-				delete(h.forwards, addr)
+			if ln2, ok := h.forwards[key]; ok && ln2 == ln {
```
[the remark this answers is not in the document]
Comment (mafredri) [reply agent/agentssh/forward.go:162]: It _should_ be, but I guess it'd be possible for a `cancel-streamlocal-forward@openssh.com` to arrive followed by a `streamlocal-forward@openssh.com` for the same socket. And if that ever happened, there could be a race to close the new listener. I thought it would be good to keep it as a safety guard for this scenario.

File: agent/agentssh/forward.go (hunk 2 above)
Comment (mafredri) [reply agent/agentssh/forward.go:239]: I happened to spot this in stdlib, and added it just-in-case, mainly being cautious. I'll add a comment that `os.Remove` does the same, that should suffice and if someone is interested, they can dive in.

File: agent/agentssh/forward.go (hunk 3 above)
Comment (mafredri) [reply agent/agentssh/forward.go:241]: I wanted to match OpenSSH behavior (we only remove files, not folders). Without doing stat (which also is racy if you think about it), there's no other way to achieve the same (AFAIK).

Since this compiles fine on Windows, I thought it wouldn't be a problem, but I can try to verify. AFAIK this implementation is not supported on Windows, though.

File: cli/ssh_test.go (hunk 4 above)
Comment (mafredri) [reply cli/ssh_test.go:846]: I do somewhat agree, but I'm not sure `agent_test.go` is a much better place since the actual forwarding is implemented here, in `cli/remoteforward.go`. This test should ensure that the behavior we want works with the actual `coder ssh` client.

File: agent/agentssh/forward.go (hunk 3 above)
Comment (spikecurtis) [reply agent/agentssh/forward.go:245]: Fine to match OpenSSH behavior --- maybe a comment to that effect would be helpful.

And, not for this PR, but I know that we _do_ have customers that target Windows workspaces, and we should verify we get some sensible error if you try to remote-forward a Unix socket from one.

Comment (mafredri) [reply agent/agentssh/forward.go:245]: There is a comment to this effect 😄 https://github.com/coder/coder/pull/11631/files#diff-7ac7e219a582bce4b340900ae8681925a65e509602ee869a2863ea2268b64d60R105

> And, not for this PR, but I know that we do have customers that target Windows workspaces, and we should verify we get some sensible error if you try to remote-forward a Unix socket from one.

For sure 👍🏻, I'll make an issue for it.

Comment (mafredri) [reply agent/agentssh/forward.go:247]: https://github.com/coder/coder/issues/11649

**Review by spikecurtis — APPROVED** [review]
One thing to fixup; but I don't need to review again.

File: cli/ssh_test.go (hunk 4 above)
Comment (mafredri) [reply cli/ssh_test.go:846]: https://github.com/coder/coder/issues/11650

File: agent/agentssh/forward.go (hunk 3 above)
Comment (mafredri) [reply agent/agentssh/forward.go:247]: @spikecurtis FYI, just confirmed `syscall.Unlink` works on Windows too, same behavior as Unix.
