### PR TITLE
fix: fixes use of possibly nil RemoteAddr() and LocalAddr() return values

### LINKED ISSUE #1143: flake: cli TestSSH -- nil pointer while recording connections
```
t.go:106: 2025-11-24 09:26:37.343 [info]  agent.ssh-server: stopped serving listener  listen_addr={} ...
        error= tailnet:
                   github.com/coder/coder/v2/tailnet.(*listener).Accept
                       /home/runner/work/coder/coder/tailnet/conn.go:979
                 - use of closed network connection
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent.ssh-server: closing server done
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: set lifecycle state  current={"state":"off","changed_at":"2025-11-24T09:26:37.343441Z"}  last={"state":"shutting_down","changed_at":"2025-11-24T09:26:37.343088Z"}
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent.containers: closing API
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent.containers: closed API
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: sent disconnect
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: reportLoop exiting
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: routine exited  name="stats report loop"  error=<nil>
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: swallowing context canceled  name="fetch service banner loop"
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: swallowing context canceled  name="report metadata"
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: disconnected from derp map RPC
    t.go:106: 2025-11-24 09:26:37.343 [debu]  agent: swallowing context canceled  name="derp map subscriber"
    t.go:106: 2025-11-24 09:26:37.343 [debu]  coderd: GET  host=127.0.0.1:45821  path=/derp  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2025-11-24T09:26:37.171058394Z"  took=172.760004ms  status_code=0  latency_ms=172  request_id=8cbcdeac-9463-4fb8-9f40-070949b98955
    t.go:106: 2025-11-24 09:26:37.343 [debu]  coderd: GET  host=127.0.0.1:45821  path=/api/v2/workspaceagents/42a239b7-6810-4677-82b6-77e303bd533e/coordinate  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2025-11-24T09:26:37.082261759Z"  workspace_name=example  agent_name=dev  workspace_name=myworkspace  requestor_id=251b161f-c368-4179-a1ec-421178dfc176  requestor_name=myuser  requestor_email=funny_khorana2@coder.com  took=261.725929ms  status_code=101  latency_ms=261  params_workspaceagent=42a239b7-6810-4677-82b6-77e303bd533e  params_workspace=4c554967-3020-4b22-a952-96c01b33fbcb  request_id=adcd35c8-c1e4-41c0-a0b6-c1e2e2e99919
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.coord: peerReadLoop got request  peer_id=42a239b7-6810-4677-82b6-77e303bd533e  peer_name=myuser-myworkspace-dev  request_id=997eba72-6a3e-4a88-9fa0-38b938309ee5
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.coord: got tunnel peers  peer_id=42a239b7-6810-4677-82b6-77e303bd533e  tunnel_peers=[]
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.agentrpc: loopResp failed to get response  owner=myuser  workspace_name=myworkspace  agent_name=dev  peer_id={"Name":"myuser-myworkspace-dev","ID":"42a239b7-6810-4677-82b6-77e303bd533e","Auth":{"ID":"42a239b7-6810-4677-82b6-77e303bd533e"}}  name=myuser-myworkspace-dev  request_id=997eba72-6a3e-4a88-9fa0-38b938309ee5  error=EOF
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent.net.tailnet.net.wgengine: magicsock: disco: got disco-looking frame from d:55d257b73896745b via DERP
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent.net.tailnet.net.wgengine: magicsock: disco: ignoring disco-looking frame, don't know endpoint for d:55d257b73896745b
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent: failed to read from protocol  error=EOF
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent: responses closed after disconnect
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent: disconnected from coordination RPC
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.agentrpc: error receiving requests from DRPC stream  owner=myuser  workspace_name=myworkspace  agent_name=dev  peer_id={"Name":"myuser-myworkspace-dev","ID":"42a239b7-6810-4677-82b6-77e303bd533e","Auth":{"ID":"42a239b7-6810-4677-82b6-77e303bd533e"}}  name=myuser-myworkspace-dev  request_id=997eba72-6a3e-4a88-9fa0-38b938309ee5 ...
        error= drpc: stream terminated by sending close
               	storj.io/drpc/drpcstream.init:494
               	runtime.doInit1:7410
               	runtime.doInit:7377
               	runtime.main:254
    t.go:106: 2025-11-24 09:26:37.344 [debu]  agent: routine exited  name=coordination  error=<nil>
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.coord: peerReadLoop context done  peer_id=42a239b7-6810-4677-82b6-77e303bd533e  peer_name=myuser-myworkspace-dev  request_id=997eba72-6a3e-4a88-9fa0-38b938309ee5
    t.go:106: 2025-11-24 09:26:37.344 [debu]  coderd.coord: lostPeer  peer_id=42a239b7-6810-4677-82b6-77e303bd533e
    t.go:106: 2025-11-24 09:26:37.345 [debu]  coderd: GET  host=127.0.0.1:45821  path=/api/v2/workspaces/4c554967-3020-4b22-a952-96c01b33fbcb/watch  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2025-11-24T09:26:37.327427319Z"  requestor_name=System  took=17.976512ms  status_code=401  latency_ms=17  request_id=eabea369-4a9b-48a9-be1a-bdae4200e1db
    t.go:106: 2025-11-24 09:26:37.347 [info]  agent.ssh-server: handling ssh session  remote_addr=[fd7a:115c:a1e0:4cc5:924a:674b:eff1:fe1f]:36917  local_addr=[fd7a:115c:a1e0:4677:82b6:77e3:3bd:533e]:1  id=8aecc6d8-5972-4d4d-80cb-a37019f6aa1e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x21ed358]

goroutine 168518 [running]:
github.com/coder/coder/v2/agent/agentssh.(*Server).sessionHandler(0xc066fae120, {0x650cc30, 0xc081daa1e0})
	/home/runner/work/coder/coder/agent/agentssh/agentssh.go:432 +0x9f8
github.com/gliderlabs/ssh.(*session).handleRequests.func2()
	/home/runner/work/_temp/go-mod-cache/github.com/coder/ssh@v0.0.0-20231128192721-70855dedb788/session.go:351 +0x27
created by github.com/gliderlabs/ssh.(*session).handleRequests in goroutine 168450
	/home/runner/work/_temp/go-mod-cache/github.com/coder/ssh@v0.0.0-20231128192721-70855dedb788/session.go:350 +0x5d1

```

seen here: https://github.com/coder/coder/actions/runs/19629342213/job/56205154064

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes: https://github.com/coder/internal/issues/1143

Both gVisor and the Go standard library implementations of `net.Conn` can under certain circumstances return `nil` for `RemoteAddr()` and `LocalAddr()` calls. If we call their methods, we segfault.

This PR fixes these calls and adds ruleguard rules.

Note that `slog.F("remote_addr", conn.RemoteAddr())` is fine because slog detects the `nil` before attempting to stringify the type.

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#21076** <a href="https://app.graphite.com/github/pr/coder/coder/21076?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/coder/21076?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: agent/agent_internal_test.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+	"github.com/stretchr/testify/require"
+
+	"cdr.dev/slog"
+	"cdr.dev/slog/sloggers/slogtest"
+
+	"github.com/coder/coder/v2/agent/proto"
+	"github.com/coder/coder/v2/testutil"
+)
+
+func TestReportConnectionEmpty(t *testing.T) {
```
Comment (spikecurtis) [inline agent/agent_internal_test.go:18]: Just ensuring that reportConnection itself doesn't barf if we don't give it an IP address.

Comment (dannykopping) [reply agent/agent_internal_test.go:18]: It wasn't immediately apparent what this test was doing before I saw your comment.
Can you add this detail in a comment?

**Review by dannykopping — APPROVED** [review]
LGTM

Nice touch with the linter, although I have a mild concern that it's not specific to the `net.Addr` type so it may result in false-positives.

**Comment by spikecurtis** [comment]
### Merge activity

* **Dec 3, 11:06 AM UTC**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.com/github/pr/coder/coder/21076).
