### PR TITLE
fix: Wrap applications if there are a bunch

### LINKED ISSUE #4672: bug: coder app links css is borked
If you have many coder_app links against a particular coder agent they now run off the screen.

Screen Shot 2022-10-21 at 11 17 52 am

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4672.

### CODE REVIEW

File: site/src/components/Resources/ResourceCard.tsx [hunk 1]
```diff
@@ -149,7 +149,13 @@ export const ResourceCard: FC<ResourceCardProps> = ({
                   </div>
                 </Stack>
 
-                <Stack direction="row" alignItems="center" spacing={0.5}>
+                <Stack
+                  direction="row"
+                  alignItems="center"
+                  spacing={0.5}
+                  wrap="wrap"
+                  maxWidth="750px"
```
Comment (code-asher) [inline site/src/components/Resources/ResourceCard.tsx:157]: Is `maxWidth` to prevent the left column from getting squashed?  If so I wonder if we could do something like put `white-space: nowrap` or similar on the left column instead then the right can take up whatever space is left over.  For example with the current `max-width` setting you can still get some wonkiness depending on your screen size:

width

With no-wrap:

nowrap

**Review by code-asher — APPROVED** [review]
