### PR TITLE
fix: update presentation of beta badges for organizations UI

### LINKED ISSUE #14795: site: beta label cleanup
A couple of cleanup items are necessary to move forward with our new 'Beta' labels before we GA orgs.

**Context:**
image
see related [Slack discussion](https://codercom.slack.com/archives/C070XG9U23G/p1727223602300319)

Note: this label design does not fully align with the existing labels for e.g. "premium" (see screenshot). I'm working on aligning the styles and creating a styleguide explaining when to use which style and which color. So there will be another follow-up issue.

**Requirements**
- [ ]  Replace the small "b" in "beta" with a capital "B" for all "Beta" tags. In case the label is used in another context, the first letter should always be capitalized.

- [ ]  remove the 'Beta' label from organization subpage titles as having the label on every page may be confusing for users since some of those views aren't new, e.g. Members

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #14795 

## Changes made
- Updated `FeatureStageBadge` component to be capitalized
- Removed all instances of the beta `FeatureStageBadge` s from the headers of each organization page
- Updated the headers component to remove the children slot, since it otherwise wouldn't be used

## Screenshots
Before
Screenshot 2024-09-25 at 3 13 45 PM

After
Screenshot 2024-09-25 at 3 13 39 PM

### CODE REVIEW

File: site/src/components/SettingsHeader/SettingsHeader.tsx [hunk 1]
```diff
@@ -19,38 +18,34 @@ export const SettingsHeader: FC<HeaderProps> = ({
...
-									fontWeight: 500,
-								},
-							]}
-						>
-							{title}
-						</h1>
-						{tooltip}
-					</Stack>
-					{badges}
+				<Stack direction="row" spacing={1} alignItems="center">
```
Comment (Parkreiner) [inline site/src/components/SettingsHeader/SettingsHeader.tsx:27]: Only change is that that the outer `Stack` got removed

**Review by aslilac — APPROVED** [review]
yay for reducing visual clutter 😄
