### PR TITLE
fix: update dbgen and dbfake task creation and toolsdk test fixtures

### LINKED ISSUE #1103: flake: TestTools/DeleteTask/NoTaskByWorkspaceIdentifier
CI Run Link: https://github.com/coder/coder/actions/runs/18829562174
Workflow Job: test-go-pg (macos-latest)
Commit: 10ef5933f4a3394c6ead8199bbffd7a57df8a6ae by Max Bretschneider
When: 2025-10-27 04:24:52Z

What failed
- Package: github.com/coder/coder/v2/codersdk/toolsdk
- Test: TestTools/DeleteTask/NoTaskByWorkspaceIdentifier (nested under TestTools/DeleteTask)

Evidence from logs
```
=== FAIL: codersdk/toolsdk TestTools/DeleteTask/NoTaskByWorkspaceIdentifier (0.01s)
    toolsdk_test.go:985:
        Error Trace: /Users/runner/work/coder/coder/codersdk/toolsdk/toolsdk_test.go:985
        Error:        Error "resolve task: list tasks for owner \"me\": GET http://127.0.0.1:59970/api/experimental/tasks?q=owner%3A%22me%22: unexpected status code 500: Internal error converting tasks.
	Error: fetch workspaces: sql: Scan error on column index 34, name \"latest_build_transition\": unsupported scan type for WorkspaceTransition: <nil>" does not contain "Resource not found"
        Test:         TestTools/DeleteTask/NoTaskByWorkspaceIdentifier
```

Classification
- Type: Code change regression (server-side 500) rather than a flaky test
- Not a matrix cancellation artifact (only macOS job failed; windows job was cancelled as a consequence)
- No data race or process crash indicators found

Root cause hypothesis
- The failure originates from the experimental tasks list endpoint used by the SDK helper `TaskByIdentifier` when resolving a non-UUID identifier.
- The endpoint returned HTTP 500 with: "Internal error converting tasks" caused by: `fetch workspaces: sql: Scan error on column index 34, name "latest_build_transition": unsupported scan type for WorkspaceTransition: <nil>`
- This suggests the server’s tasks listing path attempts to scan `latest_build_transition` into a non-nullable WorkspaceTransition field when the value is NULL, leading to a 500 instead of a 404-style "not found" for the requested identifier.

Why now / suspect change
- Recent work migrated the tasks list to the new task data model.
  - Suspect commit: a106d67c07c7dc326ccce5a4eafc2e534412acd9 "feat(coderd): use task data model for list (#20394)" (author: Mathias Fredriksson)
  - Supporting changes in SDK/UI followed on Oct 23–24.
- The failing test itself (DeleteTask/NoTaskByWorkspaceIdentifier) was introduced with the tasks tools work:
  - ebcfae27a2b6cca88a10d37a21f0e1b5b8f90b78 "feat: add task create, list, status, and delete MCP tools (#19901)" (author: Asher)
  - No recent modifications to that specific subtest were found; it previously expected a clean "Resource not found".

Precise assignment analysis
- Test function lines: toolsdk_test.go DeleteTask "NoTaskByWorkspaceIdentifier" block around line ~985.
  - Origin: added in (#19901) by Asher; unchanged recently.
- Server component likely responsible: coderd experimental tasks APIs and their DB/query layer (workspaces.sql includes `latest_build_transition` column). The SDK’s `TaskByIdentifier` uses the tasks list endpoint; failure occurs there.
- Recent owners of the tasks list/data model: Mathias Fredriksson (multiple recent commits including #20394, #20431, etc.). Assigning to the tasks backend area owner vs. the test author fits the code-change nature of this failure.

Proposed next steps
- In coderd experimental tasks list implementation, ensure NULL-safe scan/mapping of workspace-related fields (e.g., latest_build_transition) and return appropriate 404 when identifier does not exist, rather than 500.
- Add coverage for owner-scoped listing when the owner has no tasks to prevent regressions.

Reproduction hints
- From a fresh coderdtest instance with no tasks for the authenticated user, invoke SDK:
  - `NewExperimentalClient(c).Tasks(ctx, &TasksFilter{ Owner: "me" })` → should return 200 with empty list, but currently fails with 500.
- In tests, running `go test ./codersdk/toolsdk -run TestTools/DeleteTask/NoTaskByWorkspaceIdentifier -count=1` should reproduce.

Related searches for duplicates (none found)
- Searched coder/internal for:
  - "latest_build_transition"
  - "Internal error converting tasks"
  - "unsupported scan type for WorkspaceTransition"
  - "DeleteTask toolsdk"

Assignment
- Assigning to tasks backend owner based on recent changes to the experimental tasks model and list endpoint.

Checklist
- Used precise failing test identification and extracted error evidence
- Not a data race; no panic/OOM signatures in logs
- Searched coder/internal for duplicates (open and closed)
- Assignment based on component ownership (coderd experimental tasks), not CI run commit author
- CI run date/time matches Slack ping (same minute)

### PR DESCRIPTION
**Pull request by mafredri**
Depends on #20506
Fixes coder/internal#1103

### CODE REVIEW

File: coderd/database/dbfake/dbfake.go [hunk 1]
```diff
@@ -212,6 +218,37 @@ func (b WorkspaceBuildBuilder) Do() WorkspaceResponse {
...
+				_, err = b.db.UpdateTaskWorkspaceID(ownerCtx, database.UpdateTaskWorkspaceIDParams{
+					ID:          b.taskSeed.ID,
+					WorkspaceID: uuid.NullUUID{UUID: b.ws.ID, Valid: true},
+				})
+				require.NoError(b.t, err, "update task workspace id")
+			} else if task.WorkspaceID.UUID != b.ws.ID {
+				require.Fail(b.t, "task already has a workspace id, mismatch", task.WorkspaceID.UUID, b.ws.ID)
+			}
+		} else if errors.Is(err, sql.ErrNoRows) {
+			task := dbgen.Task(b.t, b.db, b.taskSeed)
```
Comment (DanielleMaywood) [inline coderd/database/dbfake/dbfake.go:243]: I'm curious about this. Do we do this in the real workspace builder? If not, what's the motivation for it here?

Comment (mafredri) [reply coderd/database/dbfake/dbfake.go:243]: Not exactly but also yes. Logically it would make sense to create a TaskBuilder that can take a WorkspaceBuildBuilder and call `.Do` on it.

When we create a task we do so in a transaction which first creates the workspace, then the task, and then the workspace build. But workspace creation by itself never creates a task.

File: coderd/database/dbfake/dbfake.go [hunk 2]
```diff
@@ -115,25 +117,29 @@ func (b WorkspaceBuildBuilder) WithAgent(mutations ...func([]*sdkproto.Agent) []
 	return b
 }
 
-func (b WorkspaceBuildBuilder) WithTask(seed *sdkproto.App) WorkspaceBuildBuilder {
-	if seed == nil {
-		seed = &sdkproto.App{}
+func (b WorkspaceBuildBuilder) WithTask(taskSeed database.TaskTable, appSeed *sdkproto.App) WorkspaceBuildBuilder {
+	//nolint:revive // returns modified struct
+	b.taskSeed = taskSeed
+	b.taskSeed.Prompt = takeFirst(b.taskSeed.Prompt, "list me")
```
Comment (johnstcn) [inline coderd/database/dbfake/dbfake.go]: I'd suggesrt we don't set any default prompt/input here. We do not _enforce_ this at the database layer, so this is a valid default state.

**Review by johnstcn — APPROVED** [review]

**Review by DanielleMaywood — APPROVED** [review]
