### PR TITLE
fix(provisioner): make coder_env and coder_script iteration deterministic

### LINKED ISSUE #21885: Race condition when multiple `coder_env` resources define the same key
### Description

When multiple Terraform modules (or resources) inject a [`coder_env`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/env) with the same `name` for a single `coder_agent`, the final environment variable value is non-deterministic. This creates a race condition in which the workspace environment can vary across builds, even with an identical template configuration.

### Current Behavior

The `ConvertState` function in `provisioner/terraform/resources.go` iterates over a Go map (`tfResourcesByLabel`) to associate `coder_env` resources with agents. Since Go maps have non-deterministic iteration order, when multiple `coder_env` resources define the same key, the order they're appended to `ExtraEnvs` is unpredictable.

Later, in `coderd/provisionerdserver/provisionerdserver.go`, these are merged into a final map where the last one processed "wins" - but that order isn't stable across builds.

### Expected Behavior

The final environment variable state should be deterministic and predictable, with support for intentional merging of path-like variables.

### Reproduction Steps

1. Create a template with multiple modules that each define a `coder_env` with the same `name`
2. Build multiple workspaces from this template
3. Observe that the env var may have different values across builds

### Proposed Solution

Implement a `merge_strategy` attribute on `coder_env` to give template authors explicit control:

```hcl
resource "coder_env" "path_addition" {
  agent_id       = coder_agent.main.id
  name           = "PATH"
  value          = "/my/custom/bin"
  merge_strategy = "append"  # or "prepend", "replace", "error"
}

### PR DESCRIPTION
**Pull request by kacpersaw**
## Description

Fixes https://github.com/coder/coder/issues/21885

When multiple `coder_env` resources define the same key for a single agent, the final environment variable value was non-deterministic because Go maps have random iteration order. The `ConvertState` function iterated over `tfResourcesByLabel` (a map) to associate `coder_env` resources with agents, making the order of `ExtraEnvs` unpredictable across builds.

## Changes

- Added `sortedResourcesByType()` helper in `resources.go` that collects resources of a given type from the label map and sorts them by Terraform address before processing
- Replaced map iteration for `coder_env` and `coder_script` association with sorted iteration, ensuring deterministic ordering
- Added `duplicate-env-keys` test case and fixture verifying that when two `coder_env` resources define the same key, the result is deterministic (sorted by address)

## How it works

When duplicate keys exist, the last one by sorted Terraform address wins. For example, `coder_env.path_a` is processed before `coder_env.path_b`, so `path_b`'s value will be the final one in `ExtraEnvs`. Since `provisionerdserver.go` merges `ExtraEnvs` into a map (last wins), this produces stable, predictable results.

### CODE REVIEW

File: provisioner/terraform/resources.go [hunk 1]
```diff
@@ -1147,6 +1145,24 @@ func PtrInt32(number int) *int32 {
...
+	var result []*tfjson.StateResource
+	for _, resources := range tfResourcesByLabel {
+		for _, resource := range resources {
+			if resource.Type == resourceType {
+				result = append(result, resource)
+			}
+		}
+	}
+	slices.SortFunc(result, func(a, b *tfjson.StateResource) int {
+		return cmp.Compare(a.Address, b.Address)
```
Comment (johnstcn) [inline provisioner/terraform/resources.go:1161]: Is this globally unique?

**Comment by kacpersaw** [comment]
Re: @johnstcn comment on `sortedResourcesByType` — yes, `resource.Address` is globally unique. It is the full Terraform resource address (e.g. `module.foo.coder_env.bar[0]`), which is unique within Terraform state. It is already used as a unique map key at line 251: `tfResourcesByLabel[label][resource.Address] = resource`.

**Review by johnstcn — APPROVED** [review]

**Comment by matifali** [comment]
I think we need docs and example use cases for this. I am still confused about how this will work. Or is it a partial solution?

What about the proposed `merge_strategy` option in the issue? 
Can we reopen the issue if there is still work to do? Thanks
