### PR TITLE
fix: fix null pointer on external provisioner daemons with daily_cost

### LINKED ISSUE #8785: Using external provisionerd with daily_cost won't work
# Description

As the title says we are using an external provisionerd to deploy our workspaces. The provisionerd stops working as soon as I add **daily_cost** to the template. Without setting daily_cost everything works as desired.

When setting daily_cost it gets stuck after planing phase...

image

In the logs of external provionerd raises an error **you don't own this job**

image

# Mitigation

Disable **daily_cost**

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #8785

### CODE REVIEW

**Comment by spikecurtis** [comment]
I did a little refactor on the provisionerdserver so that it's explicit about what arguments are required and what are optional, so that we're less likely to pass null pointers by omission.

File: coderd/provisionerdserver/provisionerdserver.go [hunk 1]
```diff
@@ -71,17 +78,73 @@ type Server struct {
...
+	}
+	if templateScheduleStore == nil {
+		panic("templateScheduleStore is nil")
+	}
+	if userQuietHoursScheduleStore == nil {
+		panic("userQuietHoursScheduleStore is nil")
+	}
+	if deploymentValues == nil {
+		panic("deploymentValues is nil")
+	}
```
Comment (mafredri) [inline coderd/provisionerdserver/provisionerdserver.go:114]: I would rather we return errors here so this can be handled more gracefully at the calling site.

Let's say we introduce a regression where, in a certain configuration, some of these are passed as nil. So our tests don't catch it, but our customer will. By the time these panic, `coderd` could've started some work that will be canceled abruptly (hypothetically, probably not the way todays server starts up, but in the future).

File: coderd/coderd.go [hunk 2]
```diff
@@ -1099,25 +1099,27 @@ func (api *API) CreateInMemoryProvisionerDaemon(ctx context.Context, debounce ti
...
+		api.Database,
+		api.Pubsub,
+		api.Telemetry,
+		tracer,
+		&api.QuotaCommitter,
+		&api.Auditor,
+		api.TemplateScheduleStore,
+		api.UserQuietHoursScheduleStore,
+		api.DeploymentValues,
+		debounce,
```
Comment (mafredri) [inline coderd/coderd.go:1117]: This feels like a lot of args and has it's own risk of mixed up arg order when there are same types (not the case here, now). Typically I'd revert to a struct but I understand why we're making this change. Two structs may be another option. We have a linter that checks that all fields are set (only enabled for certain types atm).

**Review by mafredri — APPROVED** [review]
Tests seem to be failing, but I'm otherwise fine with the change (sans panics). The other suggestion re: args, feel free to consider or disregard.

File: coderd/coderd.go (hunk 2 above)
Comment (spikecurtis) [reply coderd/coderd.go:1117]: The "a lot of args" is it's own code smell, and is a symptom of poor code architecture to have so many required args.

Making it a struct makes it too easy to leave off required arguments.  It doesn't reduce the amount of code, and in fact, increases it.

Comment (mafredri) [reply coderd/coderd.go:1117]: > Making it a struct makes it too easy to leave off required arguments. It doesn't reduce the amount of code, and in fact, increases it.

I think we should value clarity more-so than reducing the number of characters. And it's not like it would increase LOC, just verbosity (but also clarity). But again, feel free to take this as a suggestion, not as an asked change.

PS. I was making a case for a linter that detects missing field. And the struct fields can be further verified in `New` (like some args are now). IMO that levels the playing field.

**Comment by spikecurtis** [comment]
I've disabled "debounce" in external provisioners.  This matches the status quo, but is still a problem, because lots of external provisioners can create a large query burden on the DB.  Tracking that here: #9428
