### PR TITLE
fix!: stop workspace before update

### LINKED ISSUE #17840: bug: template upgrade fails on claimed prebuilt workspace
## Problem

If a prebuilt workspace's template uses [`ignore_changes` as recommended in the docs](https://coder.com/docs/admin/templates/extending-templates/prebuilt-workspaces#preventing-resource-replacement), its agent may not reconnect after a workspace template upgrade.

e.g.

```terraform
resource "docker_container" "workspace" {
  lifecycle {
    ignore_changes = all
  }
  
  count = data.coder_workspace.me.start_count

  entrypoint = ["sh", "-c", coder_agent.main.init_script]
  env = ["CODER_AGENT_TOKEN=${coder_agent.main.token}"]
  ...
}
```

## Details

A template upgrade kicks off a `start` build. `start` builds set `coder_workspace.start_count` to `1`, which is used in the `count` attribute of compute resources (see above example). If the workspace is already started, then any resources which already have `count=1` will attempt to be updated in-place.

A `start` build causes the `coder_agent` to be recreated, which generates a new auth token. Normally, without `ignore_changes`, the `env` attribute above would be modified, since the token value changes. `env` is immutable (i.e. defined as `ForceNew`), therefore Terraform will see any changes to this attribute as drift from the original and force a replacement. This would lead to the `docker_container` being recreated and the agent would start afresh and connect to the control plane.

With `ignore_changes`, however, changes to these attributes are ignored [in order for prebuilds to work](https://coder.com/docs/admin/templates/extending-templates/prebuilt-workspaces#preventing-resource-replacement), which means the template update for the workspace has no real effect at all, but the `coder_agent`'s token is still changed and so the agent can no longer connect to the control plane on behalf of the workspace. The previous agent token would still be used, even though the control plane will only accept the new one.

## Workaround

Manually restarting the workspace will allow the agent to reconnect successfully.

## Proposed Solution

Template updates should not be `start` builds, but rather a logical restart (i.e. successive `stop` and `start` builds) in order to guarantee the behaviour customers expect. This should apply for both claimed prebuilt workspaces AND regular workspaces alike, to guarantee that the compute resource is created anew. I fear the current `start`-only mechanism is working by accident, because of Terraform drift taking care of destroying and recreating the resource like a `stop` + `start` would.

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/17840

NOTE: calling this out as a breaking change so that it is highly visible in the changelog. 

* CLI: Modifies `coder update` to stop the workspace if already running.
* UI: Modifies "update" button to always stop the workspace if already running.

### CODE REVIEW

File: site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx [hunk 1]
```diff
@@ -21,19 +20,39 @@ export interface ActionButtonProps {
 	tooltipText?: string;
 }
 
-export const UpdateButton: FC<ActionButtonProps> = ({
+export const UpdateAndStartButton: FC<ActionButtonProps> = ({
```
Comment (aslilac) [inline site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx]: I would probably keep this as one component that takes a prop like `isRunning` or something to change the text, since that seems to be the main difference

File: site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx [hunk 2]
```diff
@@ -21,19 +20,39 @@ export interface ActionButtonProps {
...
+		</Tooltip>
+	);
+};
+
+export const UpdateAndRestartButton: FC<ActionButtonProps> = ({
+	handleAction,
+	loading,
+}) => {
+	return (
+		<Tooltip title="Stop workspace, if running, and restart it with the latest template version.">
```
Comment (aslilac) [inline site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx]:
```suggestion
		<Tooltip title="Stop workspace and restart it with the latest template version.">
```

more confident wording. unless I'm misunderstanding, that's the point of this change.

Comment (aslilac) [inline site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx:46]:
```suggestion
		<Tooltip title="Stop workspace and restart it with the latest template version.">
```

more confident wording. unless I'm misunderstanding, that's the point of this change.

File: site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx [hunk 3]
```diff
@@ -84,9 +103,9 @@ export const StartButton: FC<ActionButtonPropsWithWorkspace> = ({
 	);
 };
 
-export const UpdateAndStartButton: FC<ActionButtonProps> = ({
-	handleAction,
-}) => {
+export const UpdateAndStartButtonRequireActiveVersion: FC<
```
Comment (aslilac) [inline site/src/pages/WorkspacePage/WorkspaceActions/Buttons.tsx]: similarly, this could also just be an `activeVersionRequired` prop, rather than exponentially increasing the number of `Update(.+)Button(.+?)` components we have

**Review by dannykopping — APPROVED** [review]
No notes, awesome work @johnstcn 💪

File: coderd/coderdtest/coderdtest.go [hunk 4]
```diff
@@ -1245,16 +1245,16 @@ func CreateWorkspace(t testing.TB, client *codersdk.Client, templateID uuid.UUID
 }
 
 // TransitionWorkspace is a convenience method for transitioning a workspace from one state to another.
-func MustTransitionWorkspace(t testing.TB, client *codersdk.Client, workspaceID uuid.UUID, from, to database.WorkspaceTransition, muts ...func(req *codersdk.CreateWorkspaceBuildRequest)) codersdk.Workspace {
+func MustTransitionWorkspace(t testing.TB, client *codersdk.Client, workspaceID uuid.UUID, from, to codersdk.WorkspaceTransition, muts ...func(req *codersdk.CreateWorkspaceBuildRequest)) codersdk.Workspace {
```
Comment (johnstcn) [inline coderd/coderdtest/coderdtest.go:1248]: review: This is annoying to have as a database type, so migrated to use the codersdk type instead. This inflated the diff a bit but removes an unnecessary conversion.

File: site/src/api/api.ts [hunk 5]
```diff
@@ -2274,6 +2275,19 @@ class ApiMethods {
 			throw new MissingBuildParameters(missingParameters, activeVersionId);
 		}
 
+		// Stop the workspace if it is already running.
```
Comment (aslilac) [inline site/src/api/api.ts:2278]: hmm. I'm a bit worried about adding this directly inside the `API` method. most everything in here is 1:1 with a backend endpoint, occasionally with minimal logic to convert from an options object to a query string or whatever. but this is actual application logic leaking in here.

**Review by aslilac — COMMENTED** [review]
The react code looks good

I took a bit of a closer look this time tho, and I'm wondering if this should be handled by the backend rather than the clients? The CLI and the frontend are now both responsible for producing this behavior correctly, and I worry about them getting out of sync or needing to add this in even more places, like the VSCode extension or the JetBrains plugin.

**Comment by johnstcn** [comment]
> I'm wondering if this should be handled by the backend rather than the clients? The CLI and the frontend are now both responsible for producing this behavior correctly, and I worry about them getting out of sync or needing to add this in even more places, like the VSCode extension or the JetBrains plugin.


Yeah, that's a valid concern. The main difficulty there is that there's no 'restart' transition in our current workspace transition model. Ideally we would have something like a 'restart' type provisioner job that would handle both the stop and start stages (or maybe perform a stop and enqueue a start build upon completion). I'd like us to do that eventually as it would greatly simplify the whole implementation here and let us model both restart and update as the same kind of state transition.

Would you be OK with making this a follow-up item in the interest of expediency?

**Comment by dannykopping** [comment]
> > I'm wondering if this should be handled by the backend rather than the clients? The CLI and the frontend are now both responsible for producing this behavior correctly, and I worry about them getting out of sync or needing to add this in even more places, like the VSCode extension or the JetBrains plugin.
> 
> Yeah, that's a valid concern. The main difficulty there is that there's no 'restart' transition in our current workspace transition model. Ideally we would have something like a 'restart' type provisioner job that would handle both the stop and start stages (or maybe perform a stop and enqueue a start build upon completion). I'd like us to do that eventually as it would greatly simplify the whole implementation here and let us model both restart and update as the same kind of state transition.
> 
> Would you be OK with making this a follow-up item in the interest of expediency?

https://github.com/coder/coder/issues/14857

I vote for later, but soon™️

**Comment by aslilac** [comment]
yeah, that sounds like a good follow up solution 👍
