### PR TITLE
fix(cli): port-forward: update workspace last_used_at

### LINKED ISSUE #12431: `coder tunnel` does not update workspace `last_used` with long-lived connections
a customer is connecting to their workspace via `coder tunnel`, and the `last_used` metric is not being updated. this is across Linux and Windows VMs.

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/12431

For the CLI to report workspace usage, we currently depend on the agent sending a stats report with a non-zero connection count. This is sourced from `SetConnStatsCallback` (`tailnet/conn.go:621`).
The problem with this approach is that the tailscale connection tracking only appears to track "connection established" events, and is not equivalent to running e.g. `ss -plunt`. This means:
- Having an open port-forward on its own will not be detected as an 'active connection'
- Having an open port-forward with a single long-lived connection (e.g. websocket conn) will only be counted as one activity datapoint, and subsequent stats collection intervals will ignore that active connection.

This PR updates the `coder port-forward` command to periodically inform coderd that the workspace is being used:
- Adds `workspaceusage.Tracker` which periodically batch-updates workspace LastUsedAt
- Adds coderd endpoint to signal workspace usage
- Updates `coder port-forward` to periodically hit this endpoint
- Modifies `BatchUpdateWorkspacesLastUsedAt` to avoid overwriting with stale data

In later PRs, we can:
- Update `coder ssh` to also use this behaviour,
- Update the workspace activity tracking package to also call `ActivityBumpWorkspace` so that `last_used_at` and `deadline` are handled in the same place,
- Remove the existing behaviour of updating the workspace when stats are received from the agent.

Follow-ups:
- We may need to ensure that multiple port-forwards to the same workspace only result in one `coder` process on a user's workstation updating the workspace at a time. My assumption here is that most users will have at most one or two port-forwards running at a time.

### CODE REVIEW

File: coderd/workspaceusage/tracker.go [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+}
+
+// Close stops Tracker and performs a final flush.
+func (wut *Tracker) Close() {
+	wut.stopOnce.Do(func() {
+		wut.stopCh <- struct{}{}
+		wut.stopTick()
+		<-wut.doneCh
+	})
+}
```
Comment (johnstcn) [inline coderd/workspaceusage/tracker.go:181]: self-review: I originally had a final flush before close, but restarting a large coderd deployment would potentially cause multiple flushes in parallel.

File: coderd/workspaceusage/tracker.go [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+	for k := range wut.m {
+		ids = append(ids, k)
+	}
+	// Reset our internal map
+	wut.m = make(map[uuid.UUID]struct{})
+	// For ease of testing, sort the IDs lexically
+	sort.Slice(ids, func(i, j int) bool {
+		// For some unfathomable reason, byte arrays are not comparable?
+		return strings.Compare(ids[i].String(), ids[j].String()) < 0
+	})
```
Comment (johnstcn) [inline coderd/workspaceusage/tracker.go:138]: self-review: This makes me sad and I would love to know a better way to do this.
The main reason I'm using a `map[uuid.UUID]struct{}` here is to de-duplicate.

File: coderd/workspaceusage/tracker.go [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+				return
+			}
+			wut.mut.Lock()
+			wut.flushLocked(now.UTC())
+			wut.mut.Unlock()
+		}
+	}
+}
+
+// Close stops Tracker and performs a final flush.
```
Comment (johnstcn) [inline coderd/workspaceusage/tracker.go:174]:
```suggestion
// Close stops Tracker and returns once its loop has exited.
```

File: coderd/coderdtest/coderdtest.go [hunk 4]
```diff
@@ -306,6 +308,20 @@ func NewOptions(t testing.TB, options *Options) (func(http.Handler), context.Can
...
+		wutFlush := make(chan int)
+		wutTick := make(chan time.Time)
+		options.WorkspaceUsageTracker = workspaceusage.New(
+			options.Database,
+			workspaceusage.WithLogger(options.Logger.Named("workspace_usage_tracker")),
+			workspaceusage.WithFlushChannel(wutFlush),
+			workspaceusage.WithTickChannel(wutTick),
+		)
+	}
+	t.Cleanup(options.WorkspaceUsageTracker.Close)
```
Comment (johnstcn) [inline coderd/coderdtest/coderdtest.go:323]: self-review: to avoid unintentional flakes, this is disabled by default in `coderdtest`. Any behaviour that depends on last_used_at being updated needs to create and pass in an instance of `workspaceusage.Tracker` and tick/flush manually. See `portforward_test.go` for what this looks like in practice.

File: coderd/workspaceusage/tracker.go [hunk 5]
```diff
@@ -0,0 +1,181 @@
...
+	wut.m[workspaceID] = struct{}{}
+	wut.mut.Unlock()
+}
+
+// flushLocked updates last_used_at of all current workspace IDs.
+// MUST HOLD LOCK BEFORE CALLING
+func (wut *Tracker) flushLocked(now time.Time) {
+	if wut.mut.TryLock() {
+		panic("developer error: must lock before calling flush()")
+	}
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:116]: Oh this is so smart. Always an issue when writing a function like this.

File: coderd/workspaceusage/tracker.go [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+		case <-wut.stopCh:
+			close(wut.doneCh)
+			return
+		case now, ok := <-wut.tickCh:
+			if !ok {
+				return
+			}
+			wut.mut.Lock()
+			wut.flushLocked(now.UTC())
+			wut.mut.Unlock()
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:169]: This can potentially hold the lock for a long time as there is a database action here. Which would block writes. Maybe that is ok since the caller of the api endpoint is an agent, and we run the api call on a go routine.

----

Have you considered the alternative of using a channel? Just placing the `m        map[uuid.UUID]struct{}` as a variable in the `Loop` function and having a channel for incoming workspace writes. Just buffer the `workspaceBump` and taildrop overflow if that ever happens. This would just make sure writers never block.


```golang
	m := make(map[uuid.UUID]struct{})
	for {
		select {
		case wid := <-wut.workspaceBump:
			m[wid] = struct{}{}
		case <-wut.stopCh:
			close(wut.doneCh)
			return
		case now, ok := <-wut.tickCh:
			if !ok {
				return
			}
			wut.flushLocked(now.UTC(), m)
			m = make(map[uuid.UUID]struct{})
		}
	}
```

File: coderd/workspaceusage/tracker.go [hunk 7]
```diff
@@ -0,0 +1,181 @@
...
+		return
+	}
+	wut.log.Info(ctx, "updated workspaces last_used_at", slog.F("count", count), slog.F("now", now))
+}
+
+func (wut *Tracker) Loop() {
+	defer func() {
+		wut.log.Debug(context.Background(), "workspace usage tracker loop exited")
+	}()
+	for {
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:158]: We could protect this from being called on a closed tracker. I think it could be a good protection from the future if someone just assumes they can "reopen" it.

```golang
	select { // Should we check the done channel to?
	case <-wut.stopCh:
		return
	default:
	}
```

File: coderd/workspaceusage/tracker.go [hunk 8]
```diff
@@ -0,0 +1,181 @@
...
+func (wut *Tracker) flushLocked(now time.Time) {
+	if wut.mut.TryLock() {
+		panic("developer error: must lock before calling flush()")
+	}
+	count := len(wut.m)
+	defer func() { // only used for testing
+		if wut.flushCh != nil {
+			wut.flushCh <- count
+		}
+	}()
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:122]: Only run the go routine if flushCh exists
```suggestion
	if wut.flushCh != nil { // only used for testing
		defer func() {
			wut.flushCh <- count
		}()
	}
```

File: coderd/workspaceusage/tracker.go [hunk 9]
```diff
@@ -0,0 +1,181 @@
...
+	// nolint: gocritic // system function
+	authCtx := dbauthz.AsSystemRestricted(ctx)
+	if err := wut.s.BatchUpdateWorkspaceLastUsedAt(authCtx, database.BatchUpdateWorkspaceLastUsedAtParams{
+		LastUsedAt: now,
+		IDs:        ids,
+	}); err != nil {
+		wut.log.Error(ctx, "failed updating workspaces last_used_at", slog.F("count", count), slog.Error(err))
+		return
+	}
+	wut.log.Info(ctx, "updated workspaces last_used_at", slog.F("count", count), slog.F("now", now))
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:151]: If we go the channel method, we can bump this. I think 1s is a bit short for a slow database?

File: coderd/workspaceusage/tracker.go [hunk 10]
```diff
@@ -0,0 +1,181 @@
...
+}
+
+// WithFlushChannel allows passing a channel that receives
+// the number of marked workspaces every time Tracker flushes.
+// For testing only.
+func WithFlushChannel(c chan int) Option {
+	return func(h *Tracker) {
+		h.flushCh = c
+	}
+}
```
Comment (Emyrk) [inline coderd/workspaceusage/tracker.go:92]: Can we really protect this? I say this because if you pass this, you can spawn go routines that infinitely block. 

```suggestion
func WithFlushChannel(c chan int) Option {
	if flag.Lookup("test.v") == nil {
		panic("Developer Error: WithFlushChannel is only for testing, do not use this in production!")
	}
	return func(h *Tracker) {
		h.flushCh = c
	}
}
```

File: coderd/workspaceusage/tracker.go (hunk 1 above)
Comment (Emyrk) [reply coderd/workspaceusage/tracker.go:181]: Yea, the interval is every minute, but our activity trackers use like 15min intervals I think? I think missing a flush is not a big deal.

File: coderd/workspaceusage/tracker.go (hunk 2 above)
Comment (Emyrk) [reply coderd/workspaceusage/tracker.go:138]: The only thing I can think of is to maintain a slice and a map in parallel. In the channel method I mentioned, both would be function scoped variables.

In practice though, sorting a couple thousand IDs once per minute is not a big deal imo.

Comment (Emyrk) [reply coderd/workspaceusage/tracker.go:138]: for the string thing, you could do:
```golang
	sort.Slice(ids, func(i, j int) bool {
		return bytes.Compare(ids[i][:], ids[j][:]) < 0
	})
```

File: coderd/coderdtest/coderdtest.go (hunk 4 above)
Comment (Emyrk) [reply coderd/coderdtest/coderdtest.go:323]: This is fair :+1:. Unfortunately will likely be a debug session for someone in the future. I cannot think of a way to detect if someone will want this in their test.

File: coderd/workspaceusage/tracker.go (hunk 6 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:169]: That's nice! Although writers could still block if enough writes come in at the same time, but that should be fairly unlikely.

File: coderd/workspaceusage/tracker.go (hunk 2 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:138]: 🧠

File: coderd/workspaceusage/tracker.go (hunk 10 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:92]: Yeah good suggestion. I don't want those being used outside of tests.

File: coderd/workspaceusage/tracker.go (hunk 8 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:122]: Good catch!

File: coderd/workspaceusage/tracker.go (hunk 6 above)
Comment (Emyrk) [reply coderd/workspaceusage/tracker.go:169]: I think writers should use a select to just raildrop any overflow. It shouldn't probably happen with a good buffer? 

```golang
func (wut *Tracker) Add(workspaceID uuid.UUID) {
	select {
	case wut.workspaceBump <- workspaceID:
	default:
		wut.log.Warn(context.Background(), "workspace usage tracker is full, dropping workspace", slog.F("workspaceID", workspaceID))
	}
}
```

I do see what you are saying though. If the db call takes say an excessive 5s because of conn pool contention or something, the buffer has to potentially last that full 5s. With workspaces on 1min cadences, missing one isn't ideal.

Maybe make the db call async? So

```golang
	// Set a short-ish timeout for this. We don't want to hang forever.
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	go func() {
		defer cancel()
		// nolint: gocritic // system function
		authCtx := dbauthz.AsSystemRestricted(ctx)
		if err := wut.s.BatchUpdateWorkspaceLastUsedAt(authCtx, database.BatchUpdateWorkspaceLastUsedAtParams{
			LastUsedAt: now,
			IDs:        ids,
		}); err != nil {
			wut.log.Error(ctx, "failed updating workspaces last_used_at", slog.F("count", count), slog.Error(err))
			return
		}
		wut.log.Info(ctx, "updated workspaces last_used_at", slog.F("count", count), slog.F("now", now))
	}()
```

The timeout will ensure it is not run twice across tick intervals. At this point, the mutex is probably comparable. And this does make unit testing more tricky?

Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:169]: We can actually minimize the time we spend locked if we just lock while we copy the ids to a `[]uuid.UUID`.

Comment (Emyrk) [reply coderd/workspaceusage/tracker.go:169]: Yup yup :+1:

File: coderd/workspaceusage/tracker.go (hunk 5 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go]: Not needed now!

File: coderd/workspaceusage/tracker.go (hunk 7 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go]: Gonna be even more strict and panic in this case.

File: coderd/workspaceusage/tracker.go [hunk 11]
```diff
@@ -0,0 +1,221 @@
...
+		s.m = make(map[uuid.UUID]struct{})
+	}
+	l := make([]uuid.UUID, 0)
+	for k := range s.m {
+		l = append(l, k)
+	}
+	// For ease of testing, sort the IDs lexically
+	sort.Slice(l, func(i, j int) bool {
+		// For some unfathomable reason, byte arrays are not comparable?
+		return bytes.Compare(l[i][:], l[j][:]) < 0
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker.go:217]: Glad you found a solution to this!
```suggestion
	sort.Slice(l, func(i, j int) bool {
		// For some unfathomable reason, byte arrays are not comparable?
		// See https://github.com/golang/go/issues/61004
		return bytes.Compare(l[i][:], l[j][:]) < 0
```

File: coderd/workspaceusage/tracker.go [hunk 12]
```diff
@@ -0,0 +1,221 @@
...
+	})
+	s.m = make(map[uuid.UUID]struct{})
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker.go:219]: I believe the idiomatic approach as of Go 1.21 is:

```suggestion
	clear(s.m)
```

https://tip.golang.org/ref/spec#Clear

File: coderd/workspaceusage/tracker.go [hunk 13]
```diff
@@ -0,0 +1,221 @@
...
+	for {
+		select {
+		case <-wut.stopCh:
+			close(wut.doneCh)
+			return
+		case now, ok := <-wut.tickCh:
+			if !ok {
+				return
+			}
+			wut.flush(now.UTC())
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker.go:171]: I would suggest adding a comment either here or in the method comment to explain that `last_used_at` will not be precise; i.e. all workspaces will have their values updates this way every tick, and the _true_ `last_used_at` will not be recorded.

File: coderd/workspaceusage/tracker.go [hunk 14]
```diff
@@ -0,0 +1,221 @@
...
+	s.m[id] = struct{}{}
+}
+
+// UniqueAndClear returns the unique set of entries in s and
+// resets the internal map.
+func (s *uuidSet) UniqueAndClear() []uuid.UUID {
+	s.l.Lock()
+	defer s.l.Unlock()
+	if s.m == nil {
+		s.m = make(map[uuid.UUID]struct{})
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker.go:208]: You can bail out early here.

```suggestion
		s.m = make(map[uuid.UUID]struct{})
		return []uuid.UUID{}
```

or move `l := make([]uuid.UUID, 0)` above this condition and return `l`.

File: coderd/workspaceusage/tracker_test.go [hunk 15]
```diff
@@ -0,0 +1,110 @@
...
+
+	"cdr.dev/slog"
+	"cdr.dev/slog/sloggers/slogtest"
+	"github.com/coder/coder/v2/coderd/database"
+	"github.com/coder/coder/v2/coderd/database/dbmock"
+	"github.com/coder/coder/v2/coderd/database/dbtime"
+	"github.com/coder/coder/v2/coderd/workspaceusage"
+)
+
+func TestTracker(t *testing.T) {
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker_test.go:23]: Nice test 👍

File: codersdk/workspaces.go [hunk 16]
```diff
@@ -314,6 +316,54 @@ func (c *Client) PutExtendWorkspace(ctx context.Context, id uuid.UUID, req PutEx
...
+	return nil
+}
+
+// UpdateWorkspaceUsageContext periodically posts workspace usage for the workspace
+// with the given id in the background.
+// The caller is responsible for calling the returned function to stop the background
+// process.
+func (c *Client) UpdateWorkspaceUsageContext(ctx context.Context, id uuid.UUID) func() {
+	hbCtx, hbCancel := context.WithCancel(ctx)
+	// Perform one initial heartbeat
```
Comment (dannykopping) [inline codersdk/workspaces.go:339]: Supernit™️ 

```suggestion
	// Perform one initial update
```

File: coderd/workspaceusage/tracker.go [hunk 17]
```diff
@@ -0,0 +1,221 @@
...
+	}
+	return func(h *Tracker) {
+		h.tickCh = c
+		h.stopTick = func() {}
+	}
+}
+
+// Add marks the workspace with the given ID as having been used recently.
+// Tracker will periodically flush this to its configured Store.
+func (wut *Tracker) Add(workspaceID uuid.UUID) {
```
Comment (dannykopping) [inline coderd/workspaceusage/tracker.go:112]: We have the opportunity here to be precise by capturing the actual `last_used_at` (or, at least, the time the API was called).
What is the reason for dropping the precision?

I can imagine a scenario where a precision would be useful if not imperative for auditing.

**Review by dannykopping — APPROVED** [review]
Mostly nits & small {que,sugge}stions
Very clean! LGTM

File: coderd/workspaceusage/tracker.go (hunk 17 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:112]: I'm piggy-backing an existing query `BatchUpdateWorkspaceLastUsedAt` (https://github.com/coder/coder/blob/main/coderd/database/queries/workspaces.sql#L430-L436). I was hoping to avoid the need for changes to the database layer here, and I'm honestly not sure how this query could be rewritten to batch update the workspaces table with a different `last_used_at` for every `id`.

File: coderd/workspaceusage/tracker.go (hunk 12 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:219]: Ooh nice, forgot about `clear()`

File: coderd/workspaceusage/tracker.go (hunk 17 above)
Comment (dannykopping) [reply coderd/workspaceusage/tracker.go:112]: Fair enough 👍

File: coderd/workspaceusage/tracker.go (hunk 13 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:177]: big comment added

File: coderd/workspaceusage/tracker.go [hunk 18]
```diff
@@ -0,0 +1,229 @@
...
+var DefaultFlushInterval = 60 * time.Second
+
+// Store is a subset of database.Store
+type Store interface {
+	BatchUpdateWorkspaceLastUsedAt(context.Context, database.BatchUpdateWorkspaceLastUsedAtParams) error
+}
+
+// Tracker tracks and de-bounces updates to workspace usage activity.
+// It keeps an internal map of workspace IDs that have been used and
+// periodically flushes this to its configured Store.
```
Comment (mtojek) [inline coderd/workspaceusage/tracker.go:30]: Are there any risks in the multi-instance coderd deployment?

File: coderd/workspaceusage/tracker.go [hunk 19]
```diff
@@ -0,0 +1,229 @@
...
+}
+
+// Add marks the workspace with the given ID as having been used recently.
+// Tracker will periodically flush this to its configured Store.
+func (wut *Tracker) Add(workspaceID uuid.UUID) {
+	wut.m.Add(workspaceID)
+}
+
+// flush updates last_used_at of all current workspace IDs.
+// If this is held while a previous flush is in progress, it will
```
Comment (mtojek) [inline coderd/workspaceusage/tracker.go:117]: re multi-instance model: this won't overwrite any activity posted on another instance, right?

File: coderd/workspaceusage/tracker.go [hunk 20]
```diff
@@ -0,0 +1,229 @@
...
+	defer cancel()
+	// nolint: gocritic // system function
+	authCtx := dbauthz.AsSystemRestricted(ctx)
+	wut.flushLock.Lock()
+	defer wut.flushLock.Unlock()
+	if err := wut.s.BatchUpdateWorkspaceLastUsedAt(authCtx, database.BatchUpdateWorkspaceLastUsedAtParams{
+		LastUsedAt: now,
+		IDs:        ids,
+	}); err != nil {
+		wut.log.Error(ctx, "failed updating workspaces last_used_at", slog.F("count", count), slog.Error(err))
```
Comment (mtojek) [inline coderd/workspaceusage/tracker.go:144]: Is there any retry mechanism if the batch fails?

**Review by mtojek — COMMENTED** [review]
High-level review first

File: coderd/workspaceusage/tracker.go (hunk 20 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:144]: There is a built-in assumption here that any failure of a single batch can be ignored as it gets retried frequently. I suppose consecutive failures should surface some form of error somewhere. I wonder if the database health page could show a summary of queries that have failed multiple consecutive executions?

File: coderd/workspaceusage/tracker.go (hunk 19 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:117]: It might, but isn't that the point? Any updates to `last_used_at` posted by another instance will be neccessarily older as we use the flush time as `last_used_at`.

Comment (mtojek) [reply coderd/workspaceusage/tracker.go:117]: I'm thinking about the case when old updates queued on another instance were not sent to DB due to a transient network issue, and after some time the network problem is gone, so the instance will flush and overwrite activity. I guess it is a matter of adjusting the DB query.

File: coderd/workspaceusage/tracker.go (hunk 20 above)
Comment (mtojek) [reply coderd/workspaceusage/tracker.go:144]: > There is a built-in assumption here that any failure of a single batch can be ignored as it gets retried frequently. I suppose consecutive failures should surface some form of error somewhere

I might have missed it, but it would be cool to leave a comment stating this.

**Review by mtojek — APPROVED** [review]

File: coderd/workspaceusage/tracker.go (hunk 19 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:117]: Something like adding a `WHERE last_used_at < @new_last_used_at`?

Comment (mtojek) [reply coderd/workspaceusage/tracker.go:117]: Yes, unless it is already there.

File: coderd/workspaceusage/tracker.go (hunk 20 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go]: Done

File: coderd/workspaceusage/tracker.go (hunk 19 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:118]: Query updated

**Review by mtojek — APPROVED** [review]
Nice!

File: coderd/workspaceusage/tracker.go (hunk 19 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:118]: @mtojek @dannykopping also add an 'integration-style' test with multiple coderd instances.

Comment (mtojek) [reply coderd/workspaceusage/tracker.go:118]: Awesome, LGTM 👍

File: cli/portforward_test.go [hunk 21]
```diff
@@ -96,7 +99,15 @@ func TestPortForward(t *testing.T) {
 	// Setup agent once to be shared between test-cases (avoid expensive
 	// non-parallel setup).
 	var (
-		client, db         = coderdtest.NewWithDatabase(t, nil)
+		db, ps  = dbtestutil.NewDB(t)
+		wuTick  = make(chan time.Time)
+		wuFlush = make(chan int, 1)
+		wut     = workspaceusage.New(db, workspaceusage.WithFlushChannel(wuFlush), workspaceusage.WithTickChannel(wuTick))
```
Comment (mafredri) [inline cli/portforward_test.go:105]: jiffy

**Review by dannykopping — APPROVED** [review]
Awesome :+1:

File: cli/portforward_test.go [hunk 22]
```diff
@@ -148,6 +159,12 @@ func TestPortForward(t *testing.T) {
 			cancel()
 			err = <-errC
 			require.ErrorIs(t, err, context.Canceled)
+
+			wuTick <- dbtime.Now()
```
Comment (mafredri) [inline cli/portforward_test.go:163]: Consider also selecting on ctx in case consumer goes away (lets the test exit). (Flush too?)

File: coderd/coderd.go [hunk 23]
```diff
@@ -362,6 +366,14 @@ func New(options *Options) *API {
 		OIDC:   options.OIDCConfig,
 	}
 
+	if options.WorkspaceUsageTracker == nil {
+		options.WorkspaceUsageTracker = workspaceusage.New(options.Database,
+			workspaceusage.WithFlushInterval(workspaceusage.DefaultFlushInterval),
```
Comment (mafredri) [inline coderd/coderd.go:371]: Consider dropping this in favor of setting the default in `New` (only overridden when using WithFlushInterval)?

File: coderd/workspaceusage/tracker.go [hunk 24]
```diff
@@ -0,0 +1,241 @@
...
+		h.tickCh = ticker.C
+		h.stopTick = ticker.Stop
+	}
+}
+
+// WithFlushChannel allows passing a channel that receives
+// the number of marked workspaces every time Tracker flushes.
+// For testing only and will panic if used outside of tests.
+func WithFlushChannel(c chan int) Option {
+	if flag.Lookup("test.v") == nil {
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:91]: Nice strictness check! Feels like this could be a testutil func, even if obvious.

File: coderd/workspaceusage/tracker.go [hunk 25]
```diff
@@ -0,0 +1,241 @@
...
+// Add marks the workspace with the given ID as having been used recently.
+// Tracker will periodically flush this to its configured Store.
+func (wut *Tracker) Add(workspaceID uuid.UUID) {
+	wut.m.Add(workspaceID)
+}
+
+// flush updates last_used_at of all current workspace IDs.
+// If this is held while a previous flush is in progress, it will
+// deadlock until the previous flush has completed.
+func (wut *Tracker) flush(now time.Time) {
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:120]: Nit: Feels like a receiver named `t` would be simpler here.

File: coderd/workspaceusage/tracker.go [hunk 26]
```diff
@@ -0,0 +1,241 @@
...
+		panic("developer error: WithFlushChannel is not to be used outside of tests.")
+	}
+	return func(h *Tracker) {
+		h.flushCh = c
+	}
+}
+
+// WithTickChannel allows passing a channel to replace a ticker.
+// For testing only and will panic if used outside of tests.
+func WithTickChannel(c chan time.Time) Option {
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:101]: Check capacity of `c`? Ensure buffered?

File: coderd/workspaceusage/tracker.go [hunk 27]
```diff
@@ -0,0 +1,241 @@
...
+	wut.log.Info(ctx, "updated workspaces last_used_at", slog.F("count", count), slog.F("now", now))
+}
+
+// Loop periodically flushes every tick.
+// If Loop is called after Close, it will panic. Don't do this.
+func (wut *Tracker) Loop() {
+	// Calling Loop after Close() is an error.
+	select {
+	case <-wut.doneCh:
+		panic("developer error: Loop called after Close")
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:168]: If we need to do this instead of just returning, I'd prefer returning an error here, wouldn't want this to happen for a production instance after some changes to the code.

Feels like this mostly exists for tests (otherwise could be launched from `New`), so more reason not to add a possibility of panic.

File: coderd/workspaceusage/tracker.go [hunk 28]
```diff
@@ -0,0 +1,241 @@
...
+	default:
+	}
+	defer func() {
+		wut.log.Debug(context.Background(), "workspace usage tracker loop exited")
+	}()
+	for {
+		select {
+		case <-wut.stopCh:
+			close(wut.doneCh)
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:177]: This should be moved above to a defer and always run, we also exit if `tickCh` is closed leaving this open.

File: coderd/workspaceusage/tracker.go [hunk 29]
```diff
@@ -0,0 +1,241 @@
...
+	wut.stopOnce.Do(func() {
+		wut.stopCh <- struct{}{}
+		wut.stopTick()
+		<-wut.doneCh
+	})
+}
+
+// uuidSet is a set of UUIDs. Safe for concurrent usage.
+// The zero value can be used.
+type uuidSet struct {
```
Comment (mafredri) [inline coderd/workspaceusage/tracker.go:206]: How about using a `sync.Map` instead?

File: coderd/workspaceusage/tracker_test.go [hunk 30]
```diff
@@ -0,0 +1,223 @@
...
+	t.Parallel()
+
+	ctrl := gomock.NewController(t)
+	mDB := dbmock.NewMockStore(ctrl)
+	log := slogtest.Make(t, nil).Leveled(slog.LevelDebug)
+
+	tickCh := make(chan time.Time)
+	flushCh := make(chan int, 1)
+	wut := workspaceusage.New(mDB, workspaceusage.WithLogger(log), workspaceusage.WithTickChannel(tickCh), workspaceusage.WithFlushChannel(flushCh))
+	t.Cleanup(wut.Close)
```
Comment (mafredri) [inline coderd/workspaceusage/tracker_test.go:38]: Using `defer` would be more natural here, defers and `t.Cleanup` are executed in different order.

File: coderd/coderdtest/coderdtest.go [hunk 31]
```diff
@@ -306,6 +308,36 @@ func NewOptions(t testing.TB, options *Options) (func(http.Handler), context.Can
...
+		//   wuFlush = make(chan int, 1)
+		//   wut     = workspaceusage.New(db, workspaceusage.WithFlushChannel(wuFlush), workspaceusage.WithTickChannel(wuTick))
+		//   client  = coderdtest.New(t, &coderdtest.Options{
+		//     WorkspaceUsageTracker: wut,
+		//     Database:              db,
+		//     Pubsub:                ps,
+		//   })
+		//
+		// See TestPortForward for how this works in practice.
+		wutFlush := make(chan int)
```
Comment (mafredri) [inline coderd/coderdtest/coderdtest.go:330]: Not buffered, this might cause problems with tests that don't consume it.

File: coderd/workspaceusage/tracker.go (hunk 25 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:120]: I kind of dislike naming receivers `t` as I find that can get confused easily with `*testing.T`. Maybe `tr`?

File: coderd/workspaceusage/tracker.go (hunk 29 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:206]: TBH I'm never sure about the correct use case of sync.Map due to:

https://pkg.go.dev/sync#Map

> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

If you feel strongly that this use case matches the above, I'm fine with it.

File: coderd/workspaceusage/tracker.go (hunk 25 above)
Comment (mafredri) [reply coderd/workspaceusage/tracker.go:120]: `tr` is fine, personally I don't feel the context of `testing.T` is relevant in non-testing files, but totally up to you.

File: coderd/coderd.go (hunk 23 above)
Comment (johnstcn) [reply coderd/coderd.go:371]: Fair 👍

File: coderd/workspaceusage/tracker.go (hunk 26 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:101]: I don't think we need to tell people how to write their tests.

File: coderd/workspaceusage/tracker.go (hunk 27 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:168]: If we return an error, then we have two options:
1) Exit with the error, which brings us back to potentially impacting prod, but just in a nicer-looking way.
2) Just log the error and do nothing, which means the error will likely pass unnoticed until folks wonder why their workspace usage isn't being tracked.

I don't think 2) is a valid option. We're not guaranteed to catch it in tests especially because of the possibility of ignoring errors in `slogtest`.

There's an alternative possibility 1a) where we check the error and recreate the tracker if non-nil. WDYT?

File: coderd/coderdtest/coderdtest.go (hunk 31 above)
Comment (johnstcn) [reply coderd/coderdtest/coderdtest.go]: Buffered now.

File: cli/portforward_test.go (hunk 21 above)
Comment (johnstcn) [reply cli/portforward_test.go:105]: wat

File: coderd/workspaceusage/tracker.go (hunk 27 above)
Comment (johnstcn) [reply coderd/workspaceusage/tracker.go:168]: I forgot about option c) - have `New` start the loop and unexport the function.
Now it's un-possible!

File: coderd/workspaceusage/tracker.go (hunk 12 above)
Comment (Emyrk) [reply coderd/workspaceusage/tracker.go]: Oh yeah! `clear` is newer iirc. 

1.21... newish lol

File: coderd/coderdtest/coderdtest.go [hunk 32]
```diff
@@ -306,6 +308,36 @@ func NewOptions(t testing.TB, options *Options) (func(http.Handler), context.Can
...
+		//   wuTick  = make(chan time.Time)
+		//   wuFlush = make(chan int, 1)
+		//   wut     = workspaceusage.New(db, workspaceusage.WithFlushChannel(wuFlush), workspaceusage.WithTickChannel(wuTick))
+		//   client  = coderdtest.New(t, &coderdtest.Options{
+		//     WorkspaceUsageTracker: wut,
+		//     Database:              db,
+		//     Pubsub:                ps,
+		//   })
+		//
+		// See TestPortForward for how this works in practice.
```
Comment (Emyrk) [inline coderd/coderdtest/coderdtest.go:329]: Lol, love the personality in this comment :smile:

**Review by Emyrk — APPROVED** [review]
