### PR TITLE
test: dial socket when testing coder ssh unix socket forwarding

### LINKED ISSUE #942: flake: TestSSH/RemoteForwardUnixSocket
CI failure on main branch in macOS test runner.

**Workflow:** ci
**Committer:** johnstcn
**Commit:** 8083d9d5c87fbb7d7d8f018706a8d0769480378a
**Failure Link:** https://github.com/coder/coder/actions/runs/17247377845/job/48941159145

The test `TestSSH/RemoteForwardUnixSocket` failed on macOS with a timeout waiting for "results: 1" output.

**Error:**
```
--- FAIL: TestSSH/RemoteForwardUnixSocket (28.83s)
    ptytest.go:368: read error
    ssh_test.go:1151: match deadline exceeded: context deadline exceeded (wanted "results: 1"; got output with netstat command)
```

This test was previously fixed in #16103 and #16141 to use `netstat` instead of `ss` on macOS, but appears to be flaking again. The test is trying to verify that a Unix socket remote forward is working by checking if the socket is listening using `netstat -an | grep <socket_path> | wc -l | tr -d ' '`.

The failure suggests the netstat command may not be finding the expected socket or there could be a timing issue with the socket creation.

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes https://github.com/coder/internal/issues/942

The flakey test, `RemoteForwardUnixSocket`, was using `netstat` to check if the unix socket was forwarded properly. In the flake, it looks like netstat was hanging. This PR has `RemoteForwardUnixSocket` be rewritten to match the implementation of `RemoteForwardMultipleUnixSockets`, where we send bytes over the socket in-process instead. More importantly, that test hasn't flaked (yet).

Note: The implementation has been copied directly from the other test, comments and all.

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#19563** <a href="https://app.graphite.dev/github/pr/coder/coder/19563?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/19563?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: cli/ssh_test.go [hunk 1]
```diff
@@ -1332,23 +1329,58 @@ func TestSSH(t *testing.T) {
...
+			for {
+				fd, err := l.Accept()
+				if err != nil {
+					if !errors.Is(err, net.ErrClosed) {
+						assert.NoError(t, err, "listener accept failed")
+					}
+					return
+				}
+
+				testutil.Go(t, func() {
```
Comment (mafredri) [inline cli/ssh_test.go]: I wonder about using `testutil.Go` inside an async function. It assigns a `t.Cleanup` but I don't see it provide any guarantees that the test hasn't finished, in which case the cleanups won't get executed.

Perhaps a wait group and plain `go func` would be preferable inside this handler?

**Review by mafredri — APPROVED** [review]
Unless I'm missing something, this looks like an improvement of the test, thanks! :shipit:

File: cli/ssh_test.go (hunk 1 above)
Comment (ethanndickson) [reply cli/ssh_test.go]: Did you mean something like this?
```go
testutil.Go(t, func() {
	var wg sync.WaitGroup
	for {
		fd, err := l.Accept()
		if err != nil {
			if !errors.Is(err, net.ErrClosed) {
				assert.NoError(t, err, "listener accept failed")
			}
			wg.Wait()
			return
		}

		wg.Add(1)
		go func() {
			defer wg.Done()
			defer fd.Close()
			agentssh.Bicopy(ctx, fd, fd)
		}()
	}
})
```

Comment (mafredri) [reply cli/ssh_test.go]: Yep, that's it 👍🏻

Comment (mafredri) [reply cli/ssh_test.go]: ~~Ah, missing `defer wg.Wait()` at top.~~ Nevermind, now I saw it.

**Comment by ethanndickson** [comment]
### Merge activity

* **Aug 27, 11:30 AM UTC**: @ethanndickson merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/19563).
