### PR TITLE
fix: relax csrf to exclude path based apps

### LINKED ISSUE #11406: CSRF enforcement in v2.6.0 breaks RStudio IDE and other POST requests
Hello,

we have a template running code-server and RStudio as IDEs.
The v2.6.0 release seems to brake the RStudio IDE and all POST requests inside apps running in vscode.

We think we got it down to #11283 enforcing CSRF.
All requests to the Coder API are functional but inside the IDEs POST requests are not.
This is due to the X-CSRF-TOKEN header not being set on the other requests.

Is there some way to fix this on our side or should there maybe another exempt in [coderd/httpmw/csrf.go](https://github.com/coder/coder/blob/ce380580b79ace6b3f955db21b9ccd41c590a044/coderd/httpmw/csrf.go) for the URLs where apps are running, e.g. `/@USER/test.instance/apps/`?
Or maybe a switch to remove the enforcement of CSRF for now?
I'm not really experienced with CSRF so I'm looking forward to your help!

## Expected Behavior

RStudio opens as usual, which it did before upgrading to v2.6.0.

## Actual Behavior
RStudio does not start and throws the following error:
image

This can be backtraced to this POST call failing due to the coder CSRF protection kicking in.
_Note that the rs-csrf-token and csrf-token cookies are from RStudio and the csrf_token cookie is from Coder_
``` bash
curl 'https://coder.example.com/@USER/test.instance/apps/rstudio/rpc/client_init' \
  -H 'authority: coder.example.com' \
  -H 'accept: application/json' \
  -H 'cookie: coder_signed_app_token=<REDACTED>; user-id=<REDACTED>; user-list-id=<REDACTED>; persist-auth=0; rs-csrf-token=853023c5-6fe8-428a-9984-547f927d34a0; csrf-token=853023c5-6fe8-428a-9984-547f927d34a0; csrf_token=jadP8iK3mcFW5T24bfmSPKGbiWEYzKxS8k4gc5HcVbo=; oauth_state=<REDACTED>; oauth_redirect=/; coder_session_token=<REDACTED>' \
  -H 'origin: https://coder.example.com' \
  -H 'referer: https://coder.example.com/@USER/test.instance/apps/rstudio/' \
  -H 'x-rs-csrf-token: 853023c5-6fe8-428a-9984-547f927d34a0' \
  -H 'x-rs-rid: -256097717' \
  --data-raw '{"method":"client_init", "params":["https://coder.example.com/@USER/test.instance/apps/rstudio/","unfj3yhzabbmh01252nbz5tmv6z1fl1k"], "kwparams":{"restore_workspace":2, "run_rprofile":2}, "clientVersion":""}' \
  --compressed
```
Response:
`400 | Something is wrong with your CSRF token. Please refresh the page. If this error persists, try clearing your cookies.`

When I set the X-CSRF-TOKEN header manually and resend the request, it gets through but RStudio still doesn't start...

## Steps to Reproduce the Problem

  1. Setup template like described in documentation [here](https://coder.com/docs/v2/latest/ides/web-ides#rstudio)
  1. Start workspace from template
  1. Start RStudio

## Specifications

  - Version: v2.6.0
  - Platform: Linux
  - Subsystem: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by Emyrk**
Fixes https://github.com/coder/coder/issues/11406

I am working on a unit test to verify and make sure this does not break in future. Our current tests use the header auth method, which bypasses CSRF. My manual testing was just a fileserver which only used GET requests.

### CODE REVIEW

File: coderd/coderd.go [hunk 1]
```diff
@@ -627,6 +626,10 @@ func New(options *Options) *API {
 			// limit must be configurable by the admin.
 			apiRateLimiter,
 			httpmw.ReportCLITelemetry(api.Logger, options.Telemetry),
+			// CSRF only needs to apply to /api routes. It does not apply to GET requests
+			// anyway, which is most other routes. We want to exempt any external auth or
+			// application type routes.
+			httpmw.CSRF(options.SecureAuthCookie),
```
Comment (johnstcn) [inline coderd/coderd.go:632]: There are a bunch of `ExemptRegexp()` calls inside this middleware that may need to be reviewed after this change. It might be nicer to have those passed explicitly as arguments to `httpmw.CSRF` instead of being hidden inside the middleware.

File: coderd/coderd_test.go [hunk 2]
```diff
@@ -315,3 +319,62 @@ func TestSwagger(t *testing.T) {
 		require.Equal(t, "<pre>\n</pre>\n", string(body))
 	})
 }
+
+func TestCSRFExempt(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (Emyrk) [reply coderd/coderd_test.go:323]: Yup. All of our existing unit tests bypass CSRF since the codersdk uses the HEADER method to auth, not the cookie.

File: coderd/coderd.go (hunk 1 above)
Comment (Emyrk) [reply coderd/coderd.go:632]: The thing is, this will pretty quickly fail on someone when they add a new route if it breaks. The error is a CSRF error, which brings you to here. I prefer to have this all in 1 place, and this should never be configurable by a customer except maybe to disable it entirely.

I think the current exempts are overkill. I intentionally went a bit overkill because I was afraid of breaking anything. Some 


The reason there are exempts like this is when I turned this back on, I was trying to error on the side of caution. I think we should have a PR to remove an exempt 1 by 1 when we determine they can never cause an issue.

An example is the `/provisionerdaemons` ones. They are currently only GET requests, and I do not think the actual daemons are using cookies to authenticate. However I error-ed on the side of caution since these routes should never use CSRF anyway.

I can make follow up PRs to drop these with rational for each one

**Review by johnstcn — APPROVED** [review]
LGTM

**Review by deansheather — APPROVED** [review]

**Comment by Emyrk** [comment]
@johnstcn CSRF state is set via go template on page render.

So the CSRF middleware has to be present for page loads.

I just added this instead.
```
if !strings.HasPrefix(r.URL.Path, "/api") {
    return true
}
```

There is only an "exempt" syntax, rather than an "opt in" unfortunately. I think this is the easiest fix.

**Review by johnstcn — APPROVED** [review]
Good catch. LGTM once the linter is happy and once there are some more test cases in TestCSRFExempt

**Comment by Emyrk** [comment]
> ... once the linter is happy ...

It is never happy :smile:
