### PR TITLE
fix: use ephemeral port for postgres, except for TestPubsub_Disconnect

### LINKED ISSUE #7752: TestPubsub_Disconnect flake on port binding
```
=== Failed
=== FAIL: coderd/database TestPubsub_Disconnect (12.09s)
    pubsub_test.go:125: 
        	Error Trace:	/home/runner/work/coder/coder/coderd/database/pubsub_test.go:125
        	Error:      	Received unexpected error:
        	            	could not start resource:
        	            	    github.com/coder/coder/coderd/database/postgres.OpenContainerized
        	            	        /home/runner/work/coder/coder/coderd/database/postgres/postgres.go:118
        	            	  - API error (500): driver failed programming external connectivity on endpoint eager_bouman (bf988aa79d77ab9d95e89f294334975a89e9b70d955c9f8d8d6e96294644d893): Error starting userland proxy: listen tcp4 0.0.0.0:36475: bind: address already in use
        	            	    
        	            	    github.com/ory/dockertest/v3.(*Pool).RunWithOptions
        	            	    	/home/runner/go/pkg/mod/github.com/ory/dockertest/v3@v3.9.1/dockertest.go:457
        	            	    github.com/coder/coder/coderd/database/postgres.OpenContainerized
        	            	    	/home/runner/work/coder/coder/coderd/database/postgres/postgres.go:82
        	            	    github.com/coder/coder/coderd/database_test.TestPubsub_Disconnect
        	            	    	/home/runner/work/coder/coder/coderd/database/pubsub_test.go:124
        	            	    testing.tRunner
        	            	    	/opt/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1576
        	            	    runtime.goexit
        	            	    	/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/asm_amd64.s:1598
        	Test:       	TestPubsub_Disconnect
```

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #7752 

Our implementation of starting postgres on ephemeral ports is racy: it 

1. opens a TCP listener with port 0, which asks the OS to allocate a free port
2. stores the port number
3. starts a Docker container with that port as the host mapping

However, between 2 and 3 another process can come in and snatch the port.

Docker itself accepts 0 as a port mapping, and it asks the OS to allocate a free port.  This closes the race.

A second issue is that we were using an ephemeral port for TestPubsub_Disconnect where we kill the postgres container and then restart it on the same port.  It suffers from a similar race, where another process could snatch the port while postgres is down.  To solve this, we use a hardcoded, arbitrary high port number, but one outside the Linux ephemeral range.

### CODE REVIEW

File: coderd/database/pubsub_test.go [hunk 1]
```diff
@@ -117,11 +115,17 @@ func TestPubsub_ordering(t *testing.T) {
 	}
 }
 
+// disconnectTestPort is the hardcoded port for TestPubsub_Disconnect.  In this test we need to be able to stop Postgres
+// and restart it on the same port.  If we use an ephemeral port, there is a chance the OS will reallocate before we
+// start back up.  The downside is that if the test crashes and leaves the container up, subsequent test runs will fail
+// until we manually kill the container.
+const disconnectTestPort = 26892
```
Comment (mafredri) [inline coderd/database/pubsub_test.go:122]: I hope this, by default, usually falls outside the dynamic port range of `:0`, so we won't collide with other tests/test packages. Are the rules same on Windows?

At least on my NAS, it seems OK:
```
❯ cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```

Assuming these values are set differently, there could still be port collisions.

Something like `port := testutil.Port(26892)`, where that function takes the input as _preferred_, but falls back to seeking the closest free port would help in the case mentioned in the comment. The package can store "used ports", unfortunately I don't think that state won't be shared between test packages (could be wrong though).

**Review by mafredri — APPROVED** [review]

**Review by coadler — APPROVED** [review]

File: coderd/database/pubsub_test.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/database/pubsub_test.go:122]: Regarding Windows, we don't run these tests there.  Presumably because Docker on Windows is more effort/overhead than it's worth.

Comment (spikecurtis) [reply coderd/database/pubsub_test.go:122]: Using `testutil.Port()` is clever, but thinking about it a bit, I don't think we should be that clever in tests.  If the test leaks the container, I'd rather us know about it by failing tests, versus doing something different and rare.
