### PR TITLE
fix(enterprise/cli): correctly set default tags for PSK auth

### LINKED ISSUE #9234: Provisioner using PSK will not be selected if a `scope` tag is absent
Good Evening!

I have been trying to deploy external provisioners using the pre-shared key based authentication. Despite various attempts using different configurations, I was unable to get the provisioner to be selected. However, I was able to select the provisioner when using my personal user token.

Upon further inspection, it seems that an external provisioner that is missing an `scope=organization` tag will never be selected. I am not sure if this is intended behaviour. It would make sense that provisioner deployments have to be explicit about specific the scopes that they would be serving. I only realized this when looking at the `/api/v2/organizations/me/provisionerdaemons` endpoint and noticed that all the inbuilt provisioners have the `scope=organization` tag on them.

The current helm chart does not add this tag which means that jobs will just hang unless the in-built provisioner daemons are enabled.

### LINKED ISSUE #9235: Unable to adjust logging configuration for external provisioner daemon
Good Evening!

When running an external provisioner using `coder provisionerd start`, I am unable to set the log level using flags that I could use for other commands (e.g. `--verbose` `CODER_TRACE_ENABLE`, `CODER_VERBOSE`) etc.

I ran into this when trying to debug provisioner connections for https://github.com/coder/coder/issues/9234. I was looking for the debug message announcing a successful connection but was unable to surface them using the usual config options.

### PR DESCRIPTION
**Pull request by johnstcn**
fixes #9235
fixes #9234

This PR fixes a bug in provisioner daemon authentication where a provisioner daemon run using `--psk=whatever` without explicitly specifying `--tag scope=organization` would fail to pick up any jobs.

Additionally, we were not respecting the global `CODER_VERBOSE` variable such that it was impossible to get debug logs from external provisioner daemons.

I also sprinkled in a few more logging statements that helped me troubleshoot the issue.

### CODE REVIEW

File: enterprise/coderd/provisionerdaemons.go [hunk 1]
```diff
@@ -196,6 +198,12 @@ func (api *API) provisionerDaemonServe(rw http.ResponseWriter, r *http.Request)
 		Tags:         tags,
 	})
 	if err != nil {
+		api.Logger.Error(ctx, "write provisioner daemon",
```
Comment (mafredri) [inline enterprise/coderd/provisionerdaemons.go:201]: Suggestion, consider `logger = api.Logger.With(...)` for the common tags and updating so use of logger. This way the useful context will be available elsewhere too.

**Review by mafredri — APPROVED** [review]

File: coderd/provisionerdserver/provisionertags.go [hunk 2]
```diff
@@ -24,7 +24,9 @@ func MutateTags(userID uuid.UUID, tags map[string]string) map[string]string {
 	}
 	switch tags[TagScope] {
 	case ScopeUser:
-		tags[TagOwner] = userID.String()
+		if userID != uuid.Nil {
+			tags[TagOwner] = userID.String()
+		}
```
Comment (spikecurtis) [inline coderd/provisionerdserver/provisionertags.go:29]: I'd like to see an `else` branch that unsets the owner, or alternatively, don't call this function for PSK logins and just directly set `scope=organization`.

I don't think we want to allow external provisioners with the PSK to claim builds meant for people local workstations or whatever.

File: enterprise/cli/provisionerdaemons.go [hunk 3]
```diff
@@ -83,6 +83,9 @@ func (r *RootCmd) provisionerDaemonStart() *clibase.Cmd {
 			}()
 
 			logger := slog.Make(sloghuman.Sink(inv.Stderr))
+			if ok, _ := inv.ParsedFlags().GetBool("verbose"); ok {
+				logger = logger.Leveled(slog.LevelDebug)
+			}
```
Comment (spikecurtis) [inline enterprise/cli/provisionerdaemons.go:88]: 👍

**Review by spikecurtis — CHANGES_REQUESTED** [review]

File: coderd/provisionerdserver/provisionertags.go (hunk 2 above)
Comment (johnstcn) [reply coderd/provisionerdserver/provisionertags.go:29]: I think the latter makes more sense. Provisioner daemons authenticating with PSKs are implicitly organisation-scoped anyway.

Comment (spikecurtis) [inline coderd/provisionerdserver/provisionertags.go:29]: revert this change since it's no longer needed

File: enterprise/coderd/provisionerdaemons.go [hunk 4]
```diff
@@ -117,6 +117,13 @@ func (p *provisionerDaemonAuth) authorize(r *http.Request, tags map[string]strin
 	if p.psk != "" {
 		psk := r.Header.Get(codersdk.ProvisionerDaemonPSK)
 		if subtle.ConstantTimeCompare([]byte(p.psk), []byte(psk)) == 1 {
+			if len(tags) == 0 {
+				// Directly scope to organization if no tags are provided.
+				// MutateTags is only meant for scoping based on users.
+				tags = map[string]string{
+					provisionerdserver.TagScope: provisionerdserver.ScopeOrganization,
+				}
+			}
```
Comment (spikecurtis) [inline enterprise/coderd/provisionerdaemons.go:126]: instead, I think we should just unconditionally set 

`tags[provisionerdserver.TagScope] = provisionerdserver.ScopeOrganization`

Otherwise you could still use the PSK to grab user local jobs by setting `scope=user, owner=<userid>`

**Review by spikecurtis — APPROVED** [review]

File: enterprise/coderd/provisionerdaemons.go (hunk 4 above)
Comment (johnstcn) [reply enterprise/coderd/provisionerdaemons.go:126]: In this case, it might also be worth doing a check in the CLI provisionerd command to error if you use PSK auth and set `scope=user`.
