### PR TITLE
fix: use quartz clock in task status test

### LINKED ISSUE #1388: flake: Test_TaskStatus (multiple variants)
CI Run: https://github.com/coder/coder/actions/runs/22780868233
Failed Job: test-go-pg (macos-latest)
Commit: b9b3c67c73c551ce9ac0d5c2ee5c703700cc00eb (Kyle Carberry)

Failure:
```
=== FAIL: cli Test_TaskStatus/exists (1.24s)
    task_status_test.go:275: unexpected output diff (-want +got):
         strings.Join({
         	"STATE CHANGED  STATUS  HEALTHY  STATE    MESSAGE\n",
        -	"0",
        +	"1",
         	"s ago         active  true     working  Thinking furiously...",
         }, "")
--- FAIL: Test_TaskStatus/exists (1.24s)

=== FAIL: cli Test_TaskStatus/exists,--watch (1.34s)
    task_status_test.go:275: unexpected output diff (-want +got):
         strings.Join({
         	"STATE CHANGED  STATUS   HEALTHY  STATE  MESSAGE\n",
        -	"5",
        +	"6",
         	"s ago         pending  true\n",
        -	"4",
        +	"5",
         	"s ago         initializing  true\n",
        -	"4",
        +	"5",
         	"s ago         active  true\n",
        -	"3",
        +	"4",
         	"s ago         active  true     working  Reticulating splines...\n",
        -	"2",
        +	"3",
         	"s ago         active  true     complete  Splines reticulated successfully!",
         }, "")
--- FAIL: Test_TaskStatus/exists,--watch (1.34s)

DONE 2509 tests, 37 skipped, 3 failures in 101.792s
```

Error Analysis:
- Output includes relative time strings ("Xs ago") derived from time.Now in the test. macOS runner timing drift causes off-by-one seconds vs expected values.
- Failure only observed on macOS job; Linux/Windows `test-go-pg` jobs passed in same run.

Root Cause Classification: Flaky test (timing-sensitive output assertions)

Assignment Analysis:
- `git blame -L 250,280 cli/task_status_test.go`
  - b255827a5269f767c2dba476c7189ef6157ff574 chore: promote tasks to stable from experimental (#20921) (author: Danielle Maywood, GitHub: DanielleMaywood)
- `git log --oneline -10 --follow cli/task_status_test.go` points to the same commit as the most recent functional change.

Suggested Assignee: DanielleMaywood

Related Issues: none found in coder/internal

Reproduction:
- `go test ./cli -run Test_TaskStatus -count=1`

### PR DESCRIPTION
**Pull request by zedkipp**
Replace time.Since() usage with a quartz.Clock injected via RootCmd to ensure relative time strings ("Xs ago") are deterministic.

Fixes https://github.com/coder/internal/issues/1388

### CODE REVIEW

File: cli/task_status_test.go [hunk 1]
```diff
@@ -252,20 +256,24 @@ func Test_TaskStatus(t *testing.T) {
 
 			var (
 				ctx    = testutil.Context(t, testutil.WaitShort)
-				now    = time.Now().UTC() // TODO: replace with quartz
```
Comment (zedkipp) [inline cli/task_status_test.go:255]: 😄

File: cli/export_test.go [hunk 2]
```diff
@@ -0,0 +1,8 @@
+package cli
+
+import "github.com/coder/quartz"
+
+// NewRootCmdWithClock creates a RootCmd with the given clock for testing.
+func NewRootCmdWithClock(clk quartz.Clock) *RootCmd {
+	return &RootCmd{clock: clk}
+}
```
Comment (johnstcn) [inline cli/export_test.go]: I'd put this in package `clitest` TBH.

File: cli/task_status.go [hunk 3]
```diff
@@ -42,6 +43,10 @@ func (r *RootCmd) taskStatus() *serpent.Command {
 		watchArg         bool
 		watchIntervalArg time.Duration
 	)
+	clk := r.clock
+	if clk == nil {
+		clk = quartz.NewReal()
+	}
```
Comment (johnstcn) [inline cli/task_status.go]: This should be initialized somewhere in `root.go`. Having to check and init in all handlers is going to be a pain.

**Review by johnstcn — COMMENTED** [review]
Thanks for addressing this flake! I have a few comments below.

File: cli/export_test.go (hunk 2 above)
Comment (zedkipp) [reply cli/export_test.go]: Done. I initially put this here to avoid having test code in the `cli` package, but a `SetClock()` method seems reasonable.

File: cli/task_status.go (hunk 3 above)
Comment (zedkipp) [reply cli/task_status.go]: Agreed. I moved this somewhere it should be an easy opt-in for future tests.

File: cli/clitest/clitest.go [hunk 4]
```diff
@@ -40,6 +41,18 @@ func New(t testing.TB, args ...string) (*serpent.Invocation, config.Root) {
...
+// tests that are time-dependent.
+func NewWithClock(t testing.TB, clk quartz.Clock, args ...string) (*serpent.Invocation, config.Root) {
+	var root cli.RootCmd
+	root.SetClock(clk)
+
+	cmd, err := root.Command(root.AGPL())
+	require.NoError(t, err)
+
+	return NewWithCommand(t, cmd, args...)
+}
```
Comment (johnstcn) [inline cli/clitest/clitest.go:54]: (non-blocking): I think we might be reaching the stage now where we want to consolidate these `NewWithThing` functions into something like:

```go
clitest.NewWithOptions(t, WithClock(foo), WithArgs("blah", "zip"), WithConfabulator(contraption))
```

**Review by johnstcn — APPROVED** [review]
Nice, thank you!

File: cli/clitest/clitest.go (hunk 4 above)
Comment (zedkipp) [reply cli/clitest/clitest.go:54]: This is a good callout; I see at least one more function like this. I'll take a stab at refactoring in a follow-up PR.
