### PR TITLE
fix: make prebuild claiming durable and idempotent

### LINKED ISSUE #22359: Make prebuild claiming durable and idempotent
## Problem

The current prebuild claim mechanism is event-driven and ephemeral: when a prebuilt workspace is claimed, a single pubsub event is fired (`PublishWorkspaceClaim`) and forwarded to the agent over an SSE connection. If the agent's SSE connection is interrupted at the moment the claim event is published, the event is permanently lost — pubsub is fire-and-forget with no replay.

This race condition has been observed in production (see [PLAT-42](https://linear.app/codercom/issue/PLAT-42/prebuild-claim-reinit-event-is-lost-if-agent-sse-connection-is)): a network interruption causes the agent to miss the reinit signal, so `coder_script` resources configured to run on claim never execute, and the agent never picks up the new owner's manifest.

The longer a prebuild sits idle waiting to be claimed, the higher the probability of hitting this window.

## Current Architecture

The claim flow today works as follows:

1. **Publisher** (`coderd/provisionerdserver/provisionerdserver.go`): After the claim build completes, `PublishWorkspaceClaim` fires a single pubsub message on a per-workspace channel.
2. **Listener** (`coderd/prebuilds/claim.go`): The coderd SSE endpoint (`/api/v2/workspaceagents/me/reinit`) subscribes to the pubsub channel and forwards events to the agent over the HTTP connection.
3. **Agent** (`codersdk/agentsdk/agentsdk.go`): `WaitForReinitLoop` maintains the SSE connection with retry logic (100ms → 10s backoff). On disconnect, it reconnects — but any events published during the reconnection gap are lost.

This is inherently fragile because:

* The notification is imperative ("reinitialize now!") rather than declarative ("your owner is X")
* There is no persistence, acknowledgment, or replay capability
* A single missed event leaves the workspace in a broken state with no self-healing path

## Proposed Approach

Shift from an imperative event model to a *declarative, idempotent* model:

1. **Persist claim state in the database**: Rather than relying solely on an ephemeral pubsub event, record the claim state (e.g. the new owner) durably. The agent can query this state on (re)connection.
2. **Declarative notifications**: Instead of telling the agent "reinitialize now," tell it "your owner is X." The agent compares this to its current running state and reinitializes if they differ.
3. **Idempotent on reconnect**: When the agent reconnects to the SSE endpoint, the server should check the current claim state and immediately send it if a claim has already occurred. This eliminates the dependency on catching the event in real-time.
4. **Retain pubsub as a trigger optimization**: The pubsub event can still be used to *notify* the agent promptly when a claim happens, but it is no longer the source of truth — just a hint to check the durable state.

This means:

* If the agent is connected when the claim happens → it gets the pubsub notification immediately (fast path)
* If the agent reconnects after missing the event → the server sends the current state on connection setup (recovery path)
* Duplicate notifications are harmless because the agent only reinitializes when state actually changes (idempotent)

## Relevant Code

| Component | Location |
| -- | -- |
| Pubsub publish (fire-and-forget) | `coderd/provisionerdserver/provisionerdserver.go:2490-2500` |
| Pubsub subscribe (no replay) | `coderd/prebuilds/claim.go` |
| SSE reinit endpoint | `coderd/workspaceagents.go` (`workspaceAgentReinit`) |
| Agent SSE retry loop | `codersdk/agentsdk/agentsdk.go` (`WaitForReinitLoop`) |

## Related

* [PLAT-42](https://linear.app/codercom/issue/PLAT-42/prebuild-claim-reinit-event-is-lost-if-agent-sse-connection-is) — Original bug report (claim reinit event lost on SSE interruption)

---

Created on behalf of @dannykopping

### PR DESCRIPTION
**Pull request by SasSwart**
## Problem

When a prebuilt workspace is claimed, the agent reinitializes via a single fire-and-forget pubsub event over SSE. If the agent's SSE connection is interrupted at claim time, the event is permanently lost — the workspace is stuck with no self-healing path.

Additionally, regular (non-prebuild) workspaces had no way to opt out of the `/reinit` polling loop — agents would reconnect indefinitely to an endpoint that would never send them anything useful.

## Root Cause

`workspaceAgentReinit` fetches the workspace (with its current `owner_id`) via `GetWorkspaceByAgentID`, but never checked whether a claim already happened. It only subscribed to pubsub for future events. The database already has durable claim state (`owner_id` changes from `PrebuildsSystemUserID` to the real user), but no layer ever consulted it on reconnection.

### Server-side durable check with first-build-initiator gating

**TOCTOU-safe ordering**: Subscribe to pubsub claim events *before* any durable checks, so a claim that fires during the check is buffered in the channel rather than lost.

**First-build-initiator gating**: When `!workspace.IsPrebuild()` (owner is no longer the system user), look up the first build's `InitiatorID`. The prebuild reconciler always uses `PrebuildsSystemUserID` as the initiator. This distinguishes claimed prebuilds from regular workspaces without any SQL schema changes.

- **Regular workspace** (first build initiator ≠ system user) → **409 Conflict**, agent stops reconnecting
- **Claimed prebuild, build completed** → pre-seed channel with reinit event and close it, transmitter delivers one-shot then exits
- **Claimed prebuild, build in-progress** → fall through to pubsub subscription, agent waits for completion event
- **Unclaimed prebuild** → pubsub subscription (existing happy path)

### Declarative reinit events (defense-in-depth)

- Added `UserID` field to `ReinitializationEvent` with JSON tags
- Switched pubsub serialization from raw string to JSON (with backward-compat fallback for rolling upgrades)
- Populated `UserID` at both the publish site and the durable check

### Agent SDK: 409 handling

`WaitForReinitLoop` detects 409 Conflict from the server and closes the `reinitEvents` channel, cleanly exiting the retry goroutine.

### Agent CLI: fixed two bugs + added reinitCtx

- **Closed channel (`!ok`)**: now blocks on `<-ctx.Done()` instead of `continue`, keeping the current agent running. Previously this would leak agents by skipping `agnt.Close()` and re-entering the loop.
- **Duplicate owner reinit**: cancels `reinitCtx` (stops the reinit goroutine), then blocks on `<-ctx.Done()`. Previously `continue` would skip cleanup and create a new agent on the next loop iteration.
- **`reinitCtx`**: a cancellable child of `ctx` passed to `WaitForReinitLoop`, allowing the agent to stop the reinit HTTP polling after reinit completes.

### Agent-side idempotency

Tracks `lastOwnerID` in the agent reinit loop — duplicate events for the same owner are skipped.

## Testing

- **"unclaimed prebuild receives reinit via pubsub"**: prebuild owned by system user, pubsub event triggers reinit
- **"claimed prebuild receives one-shot reinit on reconnect"**: first build by system user, owner changed, build completed → immediate reinit (no pubsub needed)
- **"claimed prebuild waits during in-progress claim build"**: claimed but build still running → no reinit until build completes
- **"regular workspace gets 409"**: first build by real user → 409 Conflict, agent stops polling
- Updated claim publisher/listener tests: verify `UserID` survives JSON round-trip + backward compat with raw string payloads
- Updated SSE round-trip test: verify `UserID` survives transmit → receive cycle

Fixes #22359

## Rolling upgrade note

During a rolling deploy where old coderd instances coexist with new ones, the pubsub `ReinitializationEvent` has a new `workspace_id` field (JSON key `workspace_id`). Old publishers send a raw reason string instead of JSON; the new listener gracefully falls back by treating the entire payload as the reason and filling in `WorkspaceID` from context. The only visible effect during the upgrade window is that `WorkspaceID` may be the zero UUID in agent-side logs — this is cosmetic and resolves once all instances are updated.

### CODE REVIEW

File: coderd/workspaceagents.go [hunk 1]
```diff
@@ -1476,18 +1477,80 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+		if job.CompletedAt.Valid && !job.Error.Valid {
+			// Claim build succeeded — pre-seed the channel and
+			// close it so the transmitter below delivers exactly
+			// one reinit event then exits cleanly.
+			reinitEvents <- agentsdk.ReinitializationEvent{
+				WorkspaceID: workspace.ID,
+				Reason:      agentsdk.ReinitializeReasonPrebuildClaimed,
+				UserID:      workspace.OwnerID,
+			}
+			close(reinitEvents)
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **P1** The pre-seed send and close on this channel have two related race conditions with the pubsub subscription callback. *(Takumi, Hisoka, Robin, Ryosuke, Luffy)*

The channel is buffer-1 (line 1490) and the pubsub subscription (line 1492) is already active.

**Race A (deadlock):** If the claim build completes during the durable check's DB queries (lines 1506-1536), the pubsub callback at `claim.go:72` fills the buffer. The plain send at line 1542 then blocks forever, nobody is reading yet (the transmitter starts after this block), and the handler goroutine leaks.

**Race B (panic):** If the send succeeds and `close(reinitEvents)` runs here, the pubsub callback can still fire before `defer cancelSub()` on line 1498. Sending on a closed channel panics, and `msgQueue.run()` has no `recover()`, so the process crashes.

The subscribe-before-check pattern exists precisely to cover this window, so these two writers will overlap under load.

Could we cancel the subscription before pre-seeding, or use a non-blocking send? Something like:

```go
cancelSub() // no longer need pubsub
select {
case reinitEvents <- agentsdk.ReinitializationEvent{...}:
default:
    // Pubsub already delivered the event.
}
close(reinitEvents)
```

Alternatively: skip close entirely and let context cancellation terminate the transmitter after the first event.

File: coderd/workspaceagents.go [hunk 2]
```diff
@@ -1476,18 +1477,80 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+	// a prebuild by inspecting the first build's initiator. The
+	// prebuild reconciler always uses PrebuildsSystemUserID as the
+	// initiator for the initial build.
+	if !workspace.IsPrebuild() {
+		firstBuild, err := api.Database.GetWorkspaceBuildByWorkspaceIDAndBuildNumber(ctx,
+			database.GetWorkspaceBuildByWorkspaceIDAndBuildNumberParams{
+				WorkspaceID: workspace.ID,
+				BuildNumber: 1,
+			})
+		if err != nil || firstBuild.InitiatorID != database.PrebuildsSystemUserID {
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **P2** Transient DB error here returns a terminal 409, permanently disabling reinit for the agent. *(Ryosuke, Robin, Komugi, Luffy)*

`if err != nil` covers both `sql.ErrNoRows` (workspace has no builds, shouldn't happen) and transient failures (connection timeout, context deadline). The 409 is treated as terminal by `WaitForReinitLoop` (agentsdk.go:764): it closes the channel and never retries. A brief DB blip would permanently tell a prebuild agent it's a regular workspace.

Could we separate `err != nil` (return 500, the retry loop handles it) from the initiator check (return 409)? Something like:

```go
if err != nil {
    log.Error(ctx, "failed to get first workspace build", slog.Error(err))
    httpapi.InternalServerError(rw, xerrors.New("failed to determine workspace build history"))
    return
}
if firstBuild.InitiatorID != database.PrebuildsSystemUserID {
    httpapi.Write(ctx, rw, http.StatusConflict, codersdk.Response{...})
    return
}
```

File: coderd/workspaceagents.go [hunk 3]
```diff
@@ -1476,18 +1477,80 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+			// one reinit event then exits cleanly.
+			reinitEvents <- agentsdk.ReinitializationEvent{
+				WorkspaceID: workspace.ID,
+				Reason:      agentsdk.ReinitializeReasonPrebuildClaimed,
+				UserID:      workspace.OwnerID,
+			}
+			close(reinitEvents)
+		}
+
+		// Claim build still in progress or failed — fall through
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **P2** Failed claim build leaves the agent hanging in the SSE stream with no event to deliver. The comment here is also misleading for the failure case. *(Hisoka, Bisky, Luffy, Komugi)*

When `job.Error.Valid` is true, neither the one-shot path (line 1538 condition is false) nor the 409 path fires, so the handler falls through to the transmitter. But `PublishWorkspaceClaim` is only called in `completeWorkspaceBuildJob` (provisionerdserver.go:2526), not in `FailJob`. No pubsub event will ever arrive. The agent blocks until request timeout, reconnects, and hangs again in a loop.

The comment says "The pubsub subscription (set up above) will deliver the event when the build completes", but that's only true for in-progress builds, not failed ones.

Worth deciding the intended behavior for this case. Could we either treat failed claim builds the same as completed (the workspace identity already changed), or return an error so the agent doesn't loop?

File: coderd/workspaceagents_test.go [hunk 4]
```diff
@@ -3278,51 +3279,206 @@ func TestAgentConnectionInfo(t *testing.T) {
...
+				agentReinitializedCh <- reinitEvent
+			}
+		}()
+
+		// The agent should NOT receive a reinit event because the
+		// claim build's job is still in progress.
+		select {
+		case ev := <-agentReinitializedCh:
+			t.Fatalf("expected no reinit event, but got one: %+v", ev)
+		case <-time.After(200 * time.Millisecond):
```
Comment (mafredri) [inline coderd/workspaceagents_test.go]: **P3** `time.After(200ms)` for a negative assertion is fragile and can pass vacuously. *(Bisky, Takumi, Luffy, Robin, Komugi)*

The goroutine at line 3434 must: establish an HTTP connection, authenticate, run multiple DB queries, then enter the transmitter. If the handler hasn't reached its blocking state within 200ms on a loaded CI runner, the test passes because nothing happened yet, not because the handler correctly withheld the event.

Also, the goroutine at lines 3436-3437 silently swallows errors (`if err == nil`), so a 500 from a DB issue causes a false pass. The other subtests use `assert.NoError` in the goroutine.

File: codersdk/agentsdk/agentsdk.go [hunk 5]
```diff
@@ -706,8 +707,9 @@ const (
 )
 
 type ReinitializationEvent struct {
-	WorkspaceID uuid.UUID
+	WorkspaceID uuid.UUID              `json:"workspace_id"`
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go]: **[obs]** Adding `json:"workspace_id"` changes the SSE wire key from `"WorkspaceID"` (Go default, no tag) to `"workspace_id"`. *(Ryosuke, Hisoka, Robin, Bisky)*

During a rolling deploy where server is updated before the agent, the old agent's decoder won't match the new key and `WorkspaceID` deserializes as `uuid.Nil`. Currently only cosmetic (the field is logged, not used for logic), and the `UserID` dedup guard (`event.UserID != uuid.Nil`) safely short-circuits for old events. Just worth noting as a wire-format break.

PS. `UserID` and `WorkspaceID` are missing `format:"uuid"` struct tags, causing swagger to show `"type": "string"` without the UUID format annotation. Pre-existing for `WorkspaceID`, new for `UserID`.

File: coderd/prebuilds/claim.go [hunk 6]
```diff
@@ -48,18 +53,23 @@ func (p PubsubWorkspaceClaimListener) ListenForWorkspaceClaims(ctx context.Conte
 	default:
 	}
 
-	cancelSub, err := p.ps.Subscribe(agentsdk.PrebuildClaimedChannel(workspaceID), func(inner context.Context, reason []byte) {
-		claim := agentsdk.ReinitializationEvent{
-			WorkspaceID: workspaceID,
-			Reason:      agentsdk.ReinitializationReason(reason),
+	cancelSub, err := p.ps.Subscribe(agentsdk.PrebuildClaimedChannel(workspaceID), func(inner context.Context, payload []byte) {
+		var event agentsdk.ReinitializationEvent
+		if err := json.Unmarshal(payload, &event); err != nil {
```
Comment (mafredri) [inline coderd/prebuilds/claim.go:63]: **[obs]** The backward-compat fallback silently accepts any non-JSON payload as a reason string. *(Robin, Hisoka)*

This is the right call for the migration. Worth knowing: the inverse direction (new JSON publisher + old raw-string listener, during a rollback) would produce a garbage reason containing the full JSON blob. The reinit still fires because nothing gates on the reason value, so it works by accident. Fine for an internal protocol where both sides deploy together.

**Review by mafredri — CHANGES_REQUESTED** [review]
🤖 Agent on behalf of mafredri

The subscribe-before-check design for TOCTOU prevention is the right approach, the 409 contract for non-prebuilds is clean, and the test structure covers the important state transitions well. The backward-compat fallback in the pubsub listener is thoughtful. Good fix for the missing `return` after `InternalServerError` on line 1480.

Two related P1s in the pre-seed-and-close block, two P2s, and a few minor items across 6 inline comments.

> Seven reviewers, one channel, zero buffer headroom. Hyvää yötä!

File: coderd/workspaceagents_test.go [hunk 7]
```diff
@@ -3278,51 +3279,207 @@ func TestAgentConnectionInfo(t *testing.T) {
...
+			OwnerID:        database.PrebuildsSystemUserID,
+		}).WithAgent().Do()
 	}
-	client := coderdtest.New(t, &coderdtest.Options{
-		Database: db,
-		Pubsub:   &pubsubSpy,
+
+	// Helper to simulate claiming a prebuild: change the workspace
+	// owner to the real user and create a second (claim) build.
+	claimPrebuild := func(t *testing.T, db database.Store, sqlDB *sql.DB, ws database.WorkspaceTable, claimerID uuid.UUID, templateVersionID uuid.UUID, complete bool) dbfake.WorkspaceResponse {
```
Comment (mafredri) [inline coderd/workspaceagents_test.go:3296]: **P1** No test for the "claim build in progress" fall-through path. *(Bisky, Mafu-san, Hisoka, Mafuuu, Meruem, Ryosuke, Kurapika, Takumi)*

This helper accepts `complete bool` and has a `.Starting()` branch, but both call sites pass `true`. The fall-through at `workspaceagents.go:1578` (where `!job.CompletedAt.Valid`) is the only path where the TOCTOU-safe pubsub subscription is load-bearing for a claimed prebuild: the agent reconnects while the claim build is running, the durable check sees the job isn't complete yet, and falls through to wait on the live subscription. If someone accidentally removes that fall-through, the agent hangs indefinitely and no test catches it.

A test using `claimPrebuild(..., false)` followed by a delayed `PublishWorkspaceClaim` would cover this. The plumbing is already here.

File: codersdk/agentsdk/agentsdk.go [hunk 8]
```diff
@@ -706,8 +707,9 @@ const (
 )
 
 type ReinitializationEvent struct {
-	WorkspaceID uuid.UUID
+	WorkspaceID uuid.UUID              `json:"workspace_id" format:"uuid"`
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:710]: **P2** Adding `json:"workspace_id"` changes the SSE wire format during rolling upgrades. *(Bisky, Hisoka, Mafu-san, Mafuuu, Meruem, Ryosuke, Takumi, Robin, Kurapika)*

On main, `WorkspaceID uuid.UUID` has no json tag, so it marshals as `"WorkspaceID"`. Go's case-insensitive matching doesn't bridge the underscore (`workspace_id` vs `workspaceid`), so during a rolling deploy an old agent deserializes `WorkspaceID` as `uuid.Nil`. The field is only logged on the agent side, and the `UserID` dedup guard handles zero values gracefully, so the impact is cosmetic (zero UUID in logs during the upgrade window).

The reverse direction on pubsub is also worth knowing: an old listener receiving JSON from a new publisher will cast the entire JSON blob as the `Reason` string. Functionally harmless since the old agent reinits on any event regardless of reason content.

Worth a sentence in the PR description or release notes so operators aren't confused by zero-UUID log lines during upgrades.

File: codersdk/agentsdk/agentsdk.go [hunk 9]
```diff
@@ -758,6 +760,12 @@ func WaitForReinitLoop(ctx context.Context, logger slog.Logger, client *Client)
 			logger.Debug(ctx, "waiting for agent reinitialization instructions")
 			reinitEvent, err := client.WaitForReinit(ctx)
 			if err != nil {
+				var sdkErr *codersdk.Error
+				if errors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusConflict {
+					logger.Info(ctx, "workspace is not a prebuilt workspace, not waiting for reinit")
+					close(reinitEvents)
+					return
+				}
 				logger.Error(ctx, "failed to wait for agent reinitialization instructions", slog.Error(err))
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:779]: **P2** A permanently failed claim build causes infinite 500 retries with no way to stop. *(Ryosuke)*

Only 409 exits the retry loop (line 764). All other errors, including the 500 returned for a failed claim build, trigger `continue` with backoff up to 10s. If the claim build failed and nobody starts a new build, the agent retries indefinitely, producing server and agent log noise every ~10s for the workspace's lifetime.

This is still better than pre-PR behavior (agent hung forever on the SSE connection). But we could consider returning 409 with a distinct message for permanent failures, or adding 500 to the terminal-error check here. The agent can't usefully do anything with repeated 500s for a failed claim build.

File: codersdk/agentsdk/agentsdk.go [hunk 10]
```diff
@@ -758,6 +760,12 @@ func WaitForReinitLoop(ctx context.Context, logger slog.Logger, client *Client)
 			logger.Debug(ctx, "waiting for agent reinitialization instructions")
 			reinitEvent, err := client.WaitForReinit(ctx)
 			if err != nil {
+				var sdkErr *codersdk.Error
+				if errors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusConflict {
+					logger.Info(ctx, "workspace is not a prebuilt workspace, not waiting for reinit")
+					close(reinitEvents)
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go]: **P3** The goroutine doesn't close the channel when the context is canceled via the retrier loop exiting. *(Killua, Meruem, Ryosuke, Takumi)*

This 409 path and the send-during-cancel path (line 775) both close `reinitEvents`, but when `retrier.Wait(ctx)` returns false (context canceled between iterations), the goroutine exits without closing. Safe today because every caller that cancels also sets `reinitEvents = nil`, but the channel-ownership contract is inconsistent across exit paths.

A `defer close(reinitEvents)` at the top of the goroutine (removing the two explicit closes) would unify all exit paths.

File: coderd/workspaceagents.go [hunk 11]
```diff
@@ -1476,18 +1477,108 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+				Message: "Workspace is not a prebuilt workspace waiting to be claimed.",
+				Detail:  "This endpoint is only for agents running in prebuilt workspaces.",
+			})
+			return
+		}
+
+		// This workspace was a prebuild that got claimed. Check if
+		// the claim build completed successfully before sending
+		// reinit.
+		latestBuild, err := api.Database.GetLatestWorkspaceBuildByWorkspaceID(ctx, workspace.ID)
```
Comment (mafredri) [inline coderd/workspaceagents.go:1544]: **P3** `GetLatestWorkspaceBuildByWorkspaceID` could check the wrong build if a third build exists. *(Mafuuu)*

If a user triggers a restart (build 3) after the claim build (build 2) but before the old agent reconnects, this checks build 3's job status instead of the claim build's. Practical risk is low since the claim-build agent would typically reconnect before subsequent builds are started. But the intent is clearly "check the claim build's status." Could query build number 2 explicitly when first-build is confirmed as a prebuild, or add a comment noting the assumption.

File: coderd/workspaceagents.go [hunk 12]
```diff
@@ -1476,18 +1477,108 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+				slog.F("job_id", job.ID),
+				slog.F("error", job.Error.String))
+			httpapi.Write(ctx, rw, http.StatusInternalServerError, codersdk.Response{
+				Message: "Claim build failed.",
+				Detail:  job.Error.String,
+			})
+			return
+		}
+
+		// Claim build still in progress — fall through to the
```
Comment (mafredri) [inline coderd/workspaceagents.go:1585]: **[obs]** If a claim build fails while the agent is already connected (in-progress path), no pubsub event arrives and the SSE blocks until the connection drops. *(Killua, Kurapika, Hisoka, Takumi)*

`PublishWorkspaceClaim` is only called from `completeWorkspaceBuildJob` (success path). `FailJob` does not publish to this channel. So a build failure during an active SSE session leaves the agent hanging until the connection is severed, at which point reconnect hits the `job.Error.Valid` branch and gets the 500. Pre-existing behavior that the PR doesn't worsen. A follow-up could subscribe to the workspace build status channel and emit a synthetic error event on failure.

File: codersdk/agentsdk/agentsdk.go [hunk 13]
```diff
@@ -706,8 +707,9 @@ const (
 )
 
 type ReinitializationEvent struct {
-	WorkspaceID uuid.UUID
+	WorkspaceID uuid.UUID              `json:"workspace_id" format:"uuid"`
 	Reason      ReinitializationReason `json:"reason"`
+	UserID      uuid.UUID              `json:"user_id,omitempty" format:"uuid"`
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go]: **Nit** `UserID` is vague and inconsistent with how other layers name this value. *(Gon, Leorio)*

The struct field is `UserID`, the log key in `cli/agent.go:365` is `owner_id`, and the tracking variable is `lastOwnerID`. Three names for the same concept. Since the workspace table calls it `OwnerID` and this represents the new owner after claiming, `OwnerID` (with `json:"owner_id"`) would align all three sites.

Also, none of the three fields on this struct have doc comments. A one-liner like `// UserID is the new owner when the prebuild has been claimed; zero for unclaimed prebuilds.` would save a reader from tracing through callers to understand when it's populated.

File: coderd/prebuilds/claim.go [hunk 14]
```diff
@@ -48,18 +53,23 @@ func (p PubsubWorkspaceClaimListener) ListenForWorkspaceClaims(ctx context.Conte
...
+			// Backward compatibility: treat payload as raw reason
```
Comment (mafredri) [inline coderd/prebuilds/claim.go]: **Nit** Comment says "publishers that predate JSON encoding" but this PR is what introduces JSON encoding. *(Gon, Meruem)*

The fallback protects against a rolling-upgrade window where a new listener receives a message from an old publisher. Something like "Rolling upgrade: old publishers send the raw reason string instead of JSON" would be more precise about what this is guarding against.

File: coderd/workspaceagents.go [hunk 15]
```diff
@@ -1476,18 +1477,108 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
 	if err != nil {
 		log.Error(ctx, "failed to retrieve workspace from agent token", slog.Error(err))
 		httpapi.InternalServerError(rw, xerrors.New("failed to determine workspace from agent token"))
+		return
 	}
```
Comment (mafredri) [inline coderd/workspaceagents.go:1488]: **Nit** `workspace.ID` not added to the structured logger after this fetch. *(Leorio)*

All the downstream log and error paths in the `!workspace.IsPrebuild()` block (first-build lookup, latest-build lookup, job lookup, claim-failed warning) lack a `workspace_id` field. Adding `log = log.With(slog.F("workspace_id", workspace.ID))` here would make every downstream message greppable by workspace.

**Review by mafredri — CHANGES_REQUESTED** [review]
> 🤖 Generated by [Coder](https://coder.com/) deep-review. 10 Tier 1 + 3 Tier 2 reviewers.

The architecture is sound. The subscribe-before-check ordering eliminates the TOCTOU window correctly, the durable state check covers the agent-reconnect scenario that motivated this PR, and the backward-compat JSON/raw-string fallback in the pubsub listener is clean. Fixing the pre-existing missing `return` after `GetWorkspaceByAgentID` failure is a good catch.

The main gap: the "claim build in progress" fall-through is the only path where the TOCTOU-safe subscription is actually load-bearing for claimed prebuilds, and it has no test. The helper infrastructure is already in place (`claimPrebuild(..., false)`). One P1, two P2s, two P3s, one observation, and four nits across 9 inline comments.

> 🤖 Reviewers: Bisky, Hisoka, Mafu-san, Mafuuu, Killua, Kurapika, Meruem, Ryosuke, Takumi, Robin, Ging (Go), Gon, Leorio

File: coderd/workspaceagents.go (hunk 1 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: Resolved in e89d110. We now call `cancelSub()` before the pre-seed send, use a non-blocking `select` send (handles the case where pubsub already filled the buffer), and no longer `close(reinitEvents)`. The transmitter will send the one buffered event and then exit via `ctx.Done()` or `sseSenderClosed` when the handler returns.

File: coderd/workspaceagents.go (hunk 2 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: Resolved in e89d110. Split into two separate checks: `err != nil` now returns 500 (agent retries with backoff), and the initiator check returns 409 (terminal). Matches the pattern already used for `GetLatestWorkspaceBuildByWorkspaceID` and `GetProvisionerJobByID` below.

File: coderd/workspaceagents.go (hunk 3 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: Resolved in e89d110. Added an explicit `else if job.CompletedAt.Valid && job.Error.Valid` branch that calls `cancelSub()`, logs a warning, and returns 500. The agent retries with backoff instead of hanging forever. Also updated the fall-through comment to clarify it only applies to in-progress builds.

File: coderd/workspaceagents_test.go (hunk 4 above)
Comment (SasSwart) [reply coderd/workspaceagents_test.go]: Resolved in e89d110. The original test was vacuously passing — during an in-progress claim build, the agent from build 1 gets 401 from the auth middleware (build 1 is no longer the latest and build 2 agent rows do not exist yet), and the error was silently swallowed. Replaced the subtest with "failed claim build returns 500" which covers the new Fix 3 code path with positive assertions (no fragile timeout).

File: codersdk/agentsdk/agentsdk.go (hunk 5 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go]: Added `format:"uuid"` tags to both `WorkspaceID` and `UserID` in e89d110. Wire-format break acknowledged as acceptable per your analysis.

File: coderd/prebuilds/claim.go (hunk 6 above)
Comment (SasSwart) [reply coderd/prebuilds/claim.go:63]: Acknowledged — no code change needed per your analysis. The fallback works correctly for both directions during rolling upgrades.

File: coderd/workspaceagents_test.go (hunk 7 above)
Comment (SasSwart) [reply coderd/workspaceagents_test.go:3296]: Good point. The original test using `claimPrebuild(..., false)` was vacuously passing — the agent from build 1 gets 401 from the auth middleware during an in-progress claim build (build 1 is no longer the latest, and build 2 agent rows do not exist yet because `.Starting()` does not run `ProvisionerJobResources().Do()`), so the request never reaches the reinit handler at all. The error was silently swallowed by the `if err == nil` guard.

We replaced that subtest with "failed claim build returns 500" to cover the new error-handling code path. The in-progress fall-through + pubsub delivery path is tricky to test at this level because of the auth middleware constraint. The "unclaimed prebuild receives reinit via pubsub" test already exercises the pubsub→transmitter path. Would a test that bypasses auth (e.g. directly calling the handler) be worth adding here?

File: codersdk/agentsdk/agentsdk.go (hunk 8 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:710]: Acknowledged — good suggestion about the PR description note. The impact is cosmetic (zero UUID in agent logs during upgrade window) and the `UserID` dedup guard handles zero values safely.

File: codersdk/agentsdk/agentsdk.go (hunk 9 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:779]: Good observation. The 500 retry loop is strictly better than the pre-PR behavior (hung forever on SSE), but agreed it produces unnecessary log noise for a permanent failure. Returning 409 with a distinct message (e.g. "Claim build failed permanently") would let `WaitForReinitLoop` exit cleanly. Happy to make that change if you think it belongs in this PR rather than a follow-up.

File: codersdk/agentsdk/agentsdk.go (hunk 10 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go]: Not addressed in this commit — this is in `WaitForReinitLoop` (agentsdk.go) which is pre-existing code. Agree that `defer close(reinitEvents)` at the top of the goroutine would unify all exit paths cleanly. Worth a follow-up.

File: coderd/workspaceagents.go (hunk 11 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1544]: Not addressed in this commit. Agree the risk is low (claim agent reconnects before build 3 starts), but the intent is clearly "check the claim build." A comment noting the assumption would be the minimal fix. Happy to add one.

File: coderd/workspaceagents.go (hunk 12 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1585]: Acknowledged — pre-existing behavior that this PR does not worsen. On reconnect after the connection drops, the agent now hits the `job.Error.Valid` branch and gets 500 instead of hanging. A follow-up subscribing to the workspace build status channel for synthetic error events would close this gap fully.

File: codersdk/agentsdk/agentsdk.go (hunk 13 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go]: Not addressed in this commit. Agree that `OwnerID` with `json:"owner_id"` would align all three sites (struct field, log key, tracking variable). This is a wire-format change though, so it might make sense to batch it with the json tag change already in this PR. Happy to rename if you want it here.

File: coderd/prebuilds/claim.go (hunk 14 above)
Comment (SasSwart) [reply coderd/prebuilds/claim.go]: Not addressed in this commit. Agree the wording should be more precise — "Rolling upgrade: old publishers send the raw reason string instead of JSON" is clearer. Happy to update.

File: coderd/workspaceagents.go (hunk 15 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1488]: Not addressed in this commit. Agree — adding `log = log.With(slog.F("workspace_id", workspace.ID))` at the top of the `!workspace.IsPrebuild()` block would make all downstream messages greppable. Happy to add.

File: coderd/workspaceagents.go [hunk 16]
```diff
@@ -1476,18 +1477,109 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
 		return
 	}
-	defer cancel()
+	defer cancelSub()
+
+	// If the workspace has already been claimed (i.e. the owner is no
+	// longer the prebuilds system user), check whether it was originally
+	// a prebuild by inspecting the first build's initiator. The
+	// prebuild reconciler always uses PrebuildsSystemUserID as the
+	// initiator for the initial build.
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **P1** Durable check creates an infinite reinit loop for old agents during rolling upgrades. *(Meruem P1)*

> The new server handler's durable check sends a reinit event on every connection from an agent whose workspace was claimed. The new agent code deduplicates via `lastOwnerID`. But old agents on `origin/main` have none of this: no `reinitCtx`/`reinitCancel`, no `lastOwnerID` tracking, no `!ok` channel-closed handling. During rolling upgrade (new server, old agent, claimed prebuild): old agent's goroutine calls `WaitForReinit(ctx)` → server seeds channel with reinit event → old agent reinitializes → goroutine loops → server sends reinit again. Each cycle drops SSH sessions and port forwards; cycle time is ~3-5 seconds. The loop persists until the agent binary is replaced.

I verified: old `cli/agent.go` assigns `reinitEvents` once before the for loop, with no dedup. The goroutine survives reinit cycles and calls `WaitForReinit` again immediately. This is user-visible disruption during upgrades.

Meruem's suggested fix: gate the durable check on an opt-in signal from the agent (e.g. a query parameter `?durable-reinit=1`). Old agents without the signal get the old behavior (pubsub-only). This eliminates the hazard without version negotiation.

File: coderd/workspaceagents.go [hunk 17]
```diff
@@ -1476,18 +1477,109 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+			httpapi.InternalServerError(rw, xerrors.New("failed to get latest workspace build"))
+			return
+		}
+		job, err := api.Database.GetProvisionerJobByID(ctx, latestBuild.JobID)
+		if err != nil {
+			log.Error(ctx, "failed to get provisioner job", slog.Error(err))
+			httpapi.InternalServerError(rw, xerrors.New("failed to get provisioner job"))
+			return
+		}
+
```
Comment (mafredri) [inline coderd/workspaceagents.go:1556]: **P2** Cancelled pending claim build is misclassified as successful. *(Mafuuu P2)*

> When a pending job is cancelled via `patchCancelWorkspaceBuild`, `UpdateProvisionerJobWithCancelByID` sets `canceled_at` and `completed_at` but does NOT set `error`. The resulting job state (`CompletedAt.Valid == true`, `Error.Valid == false`, `CanceledAt.Valid == true`) matches this success branch. The handler pre-seeds a reinit event and the agent reinitializes into a workspace whose claim build never actually ran.

I verified the SQL: `UpdateProvisionerJobWithCancelByID` sets `canceled_at = $2, completed_at = $3` with no error column. Scenario: operator claims a prebuild, claim build is queued but no provisioner is available, operator cancels, agent reconnects and gets told to reinitialize against an un-provisioned workspace.

Fix: `if job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid`.

File: coderd/workspaceagents_test.go [hunk 18]
```diff
@@ -3278,51 +3279,205 @@ func TestAgentConnectionInfo(t *testing.T) {
...
```
Comment (mafredri) [inline coderd/workspaceagents_test.go:3296]: **P2** No test for the "claim build in progress" fall-through path. *(Ryosuke P2, Bisky P2, Hisoka P2, Mafu-san P3)*

> The PR description lists "claimed prebuild waits during in-progress claim build" as a tested scenario. No such test exists. The `claimPrebuild` helper accepts a `complete bool` parameter and has a `Starting()` branch, but it is never called with `complete=false`. This leaves the fallthrough-to-transmitter code path at lines 1578-1581 untested, which is exactly the path where the pubsub subscription is load-bearing for claimed prebuilds.

*Ryosuke adds:* This is the core recovery scenario the PR solves (agent reconnects during a claim build), and it's the only path where the subscribe-before-check ordering actually matters for a claimed workspace.

A test using `claimPrebuild(..., false)` followed by a delayed `PublishWorkspaceClaim` would cover this.

File: coderd/workspaceagents.go [hunk 19]
```diff
@@ -1476,18 +1477,109 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+			log.Warn(ctx, "claim build failed",
+				slog.F("job_id", job.ID),
+				slog.F("error", job.Error.String))
+			httpapi.Write(ctx, rw, http.StatusConflict, codersdk.Response{
+				Message: "Claim build failed permanently.",
+				Detail:  job.Error.String,
+			})
+			return
+		}
+
```
Comment (mafredri) [inline coderd/workspaceagents.go:1584]: **P2** Comment says "will deliver the event when the build completes" but `FailJob` doesn't publish to this channel. *(Hisoka P1, Killua P2, Takumi P2)*

> `PublishWorkspaceClaim` is only called from `completeWorkspaceBuildJob` (provisionerdserver.go:2526), which executes on the `CompletedJob` RPC path. When a build fails, `FailJob` (provisionerdserver.go:1177) is called instead — it sets `CompletedAt` + `Error` but never publishes a claim event. The SSE connection stays alive via heartbeats, so the agent blocks in the transmitter until the transport-level connection breaks.

Hisoka rated this P1 for the unbounded hang + resource leak per workspace. Killua and Takumi rated P2 noting it self-heals on reconnect and the PR is a net improvement over pre-PR behavior. I agree with P2: the comment is inaccurate (in-scope), and the hang is pre-existing. The comment should say "when the build completes successfully" and ideally note that failure is unhandled until reconnect.

PS. Takumi suggests adding a `TODO` comment here about publishing from `FailJob` for claim builds.

File: codersdk/agentsdk/agentsdk.go (hunk 8 above)
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:710]: **P3** `WorkspaceID` JSON tag rename changes the SSE wire format during rolling upgrades. *(Bisky P2, Mafu-san P2, Mafuuu P3, Killua P3)*

Bisky and Mafu-san rated this P2; Mafuuu and Killua rated P3. The field is log-only on the agent side and the dedup guard handles zero values, so the consequence is zero-UUID log lines during the upgrade window. Not blocking, but worth a note in the PR description. Subsummed in severity by the P1 rolling-upgrade finding (which causes actual behavioral disruption, not just log cosmetics).

File: codersdk/agentsdk/agentsdk.go [hunk 20]
```diff
@@ -754,17 +756,22 @@ func WaitForReinitLoop(ctx context.Context, logger slog.Logger, client *Client)
 	reinitEvents := make(chan ReinitializationEvent)
 
 	go func() {
+		defer close(reinitEvents)
 		for retrier := retry.New(100*time.Millisecond, 10*time.Second); retrier.Wait(ctx); {
 			logger.Debug(ctx, "waiting for agent reinitialization instructions")
 			reinitEvent, err := client.WaitForReinit(ctx)
 			if err != nil {
+				var sdkErr *codersdk.Error
+				if errors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusConflict {
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:774]: **P3** Log message "workspace is not a prebuilt workspace" is misleading for failed claim builds. *(Ryosuke P3)*

> `WaitForReinitLoop` logs `"workspace is not a prebuilt workspace, not waiting for reinit"` for every 409 Conflict. But the server now returns 409 for two semantically different conditions: regular workspace, and failed claim build. For the failed-claim case, the workspace IS a prebuild — the claim just failed. An operator debugging a failed claim would be misled.

Suggestion: `"received terminal 409, stopping reinit polling"` covers both cases without asserting a specific cause.

File: codersdk/agentsdk/agentsdk.go (hunk 13 above)
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go]: **Nit** `UserID` should be `OwnerID`, and `omitempty` is a no-op on `uuid.UUID`. *(Gon, Ging-Go, Leorio)*

> Every usage site names this value as the owner: `cli/agent.go` tracks it in `lastOwnerID`, logs `"owner unchanged"`. `workspaceagents.go` and `provisionerdserver.go` populate it from `workspace.OwnerID`. A reader seeing `event.UserID` doesn't know which user. *(Gon)*

> `encoding/json` does not consider array zero values "empty," so `omitempty` never omits `uuid.Nil`. The module declares `go 1.25`; `omitzero` (since 1.24) correctly omits zero-value types including `[16]byte`. *(Ging-Go)*

File: codersdk/agentsdk/agentsdk.go [hunk 21]
```diff
@@ -754,17 +756,22 @@ func WaitForReinitLoop(ctx context.Context, logger slog.Logger, client *Client)
 	reinitEvents := make(chan ReinitializationEvent)
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:765]: **Nit** `WaitForReinitLoop` is exported but has no doc comment, and the channel-close contract changed. *(Gon, Leorio)*

> The returned channel now closes on two paths: context cancellation and 409 from the server. The caller in `cli/agent.go` depends on distinguishing open-with-event from closed. A one-line comment like `// WaitForReinitLoop polls for reinit events. The returned channel closes when ctx is done or the server returns 409.` would save the next reader from tracing through the goroutine. *(Gon)*

File: cli/agent.go [hunk 22]
```diff
@@ -343,9 +347,31 @@ func workspaceAgent() *serpent.Command {
 				case <-ctx.Done():
 					logger.Info(ctx, "agent shutting down", slog.Error(context.Cause(ctx)))
 					mustExit = true
-				case event := <-reinitEvents:
-					logger.Info(ctx, "agent received instruction to reinitialize",
-						slog.F("workspace_id", event.WorkspaceID), slog.F("reason", event.Reason))
+				case event, ok := <-reinitEvents:
+					switch {
+					case !ok:
+						// Channel closed — 409 from server means this
```
Comment (mafredri) [inline cli/agent.go]: **Nit** Comment overstates 409 as the only reason for channel close. *(Gon, Leorio)*

> The channel also closes when the loop's context expires (the `defer close` fires on every exit path). Since `reinitCtx` is a child of `ctx`, a `ctx` cancellation can race between the `<-ctx.Done()` arm and the channel-close arm. The comment claims a single cause when channel close is a general "loop exited" signal. *(Gon)*

Suggestion: "Channel closed — reinit loop exited (not a prebuild, or context expired)."

**Review by mafredri — CHANGES_REQUESTED** [review]
> 🤖 Generated by [Coder](https://coder.com/) deep-review v2. 10 Tier 1 + 3 Tier 2 reviewers.

Good progress since v1. The `defer close`, the 409 for failed claim builds, the structured logger fix, and the rolling-upgrade comment rewording all address previous findings cleanly.

New panel caught two issues the first round missed: a rolling-upgrade infinite reinit loop (old agent + new server), and a cancelled claim build that passes the success condition. 1 P1, 3 P2s, 2 P3s, and 4 nits across 9 inline comments.

> 🤖 Reviewers: Bisky, Hisoka, Mafu-san, Mafuuu, Killua, Kurapika, Meruem, Ryosuke, Takumi, Robin, Ging (Go), Gon, Leorio

File: coderd/workspaceagents.go (hunk 1 above)
Comment (mafredri) [reply coderd/workspaceagents.go]: Verified, looks correct.

File: coderd/workspaceagents.go (hunk 2 above)
Comment (mafredri) [reply coderd/workspaceagents.go]: Verified, the split looks right.

File: coderd/workspaceagents.go (hunk 3 above)
Comment (mafredri) [reply coderd/workspaceagents.go]: Verified, the 409 for failed builds is clean.

File: coderd/workspaceagents_test.go (hunk 4 above)
Comment (mafredri) [reply coderd/workspaceagents_test.go]: Good catch on the vacuous pass.

File: codersdk/agentsdk/agentsdk.go (hunk 5 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go]: OK, agreed.

File: coderd/prebuilds/claim.go (hunk 6 above)
Comment (mafredri) [reply coderd/prebuilds/claim.go:63]: Agreed, no action needed.

File: coderd/workspaceagents_test.go (hunk 7 above)
Comment (mafredri) [reply coderd/workspaceagents_test.go:3296]: You're right about the auth constraint. I verified: `GetAuthenticatedWorkspaceAgentAndBuildByAuthToken` joins agent token → resources → latest build, so build 1's token gets 401 when build 2 exists but has no agent rows yet (`.Starting()` does not create resources).

A handler-level test bypassing auth would cover it, but that couples the test to handler internals. Given the "unclaimed prebuild" test already exercises the pubsub→transmitter path, and the gating logic is the only untested part, I think the current coverage is acceptable. Sorry for re-raising this without engaging with your explanation.

File: coderd/workspaceagents.go (hunk 11 above)
Comment (mafredri) [reply coderd/workspaceagents.go:1544]: OK, a comment noting the assumption is fine.

File: coderd/workspaceagents.go (hunk 12 above)
Comment (mafredri) [reply coderd/workspaceagents.go:1585]: Agreed, no action needed in this PR.

File: codersdk/agentsdk/agentsdk.go (hunk 13 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go]: Up to you whether to batch it with this PR or follow up.

File: coderd/prebuilds/claim.go (hunk 14 above)
Comment (mafredri) [reply coderd/prebuilds/claim.go]: Looks good, the "Rolling upgrade" wording is clearer.

File: coderd/workspaceagents.go (hunk 15 above)
Comment (mafredri) [reply coderd/workspaceagents.go:1488]: Verified, looks good.

File: codersdk/agentsdk/agentsdk.go (hunk 8 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go:710]: Apologies, this was already acknowledged in the previous round. Should not have been re-raised.

File: codersdk/agentsdk/agentsdk.go (hunk 13 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go]: Apologies, you already agreed to this above. Should not have been re-raised.

File: coderd/workspaceagents_test.go (hunk 18 above)
Comment (mafredri) [reply coderd/workspaceagents_test.go:3296]: Apologies for re-raising without engaging with your auth constraint explanation. Replied above — I agree the current coverage is acceptable given the middleware limitation.

File: codersdk/agentsdk/agentsdk.go (hunk 8 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go:710]: OK, acknowledged. No further action needed.

File: codersdk/agentsdk/agentsdk.go (hunk 9 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go:779]: Verified, the 409 with distinct message is in the current diff. Looks good.

File: codersdk/agentsdk/agentsdk.go (hunk 10 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go]: Verified, defer close is in the current diff. Looks good.

File: coderd/workspaceagents.go (hunk 16 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: Addressed in 53f58d946. `WaitForReinit` now sends `?wait=true` as a query parameter. The server only performs the durable claim check (the pre-seed into the channel) when this parameter is present. Old agents that lack the `lastOwnerID` dedup guard do not send `?wait=true`, so they fall through directly to the SSE transmitter and only receive events via pubsub — the original pre-this-PR behavior. This eliminates the infinite reinit loop during rolling upgrades.

File: coderd/workspaceagents.go (hunk 17 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1556]: Addressed in 53f58d946. The success condition now includes `!job.CanceledAt.Valid`, so cancelled builds are no longer misclassified as successful:

```go
if job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid {
```

A cancelled build falls through to the "claim build still in progress" path, which at worst leaves the agent blocking on SSE until reconnect (at which point the durable check handles it).

File: coderd/workspaceagents.go (hunk 19 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1584]: Addressed in 53f58d946. The comment now explicitly notes that `FailJob` does not publish a claim event, so a failed in-progress build will leave the agent blocking until it disconnects and reconnects (at which point the durable check handles it).

File: coderd/workspaceagents.go (hunk 11 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1544]: Addressed in 53f58d946. Added a comment above the `GetLatestWorkspaceBuildByWorkspaceID` call documenting the assumption that the latest build is the claim build (build 2), and noting the extremely small race window if a third build (e.g. restart) starts between the claim and agent reconnection.

File: codersdk/agentsdk/agentsdk.go (hunk 20 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:774]: Addressed in 53f58d946. Log message changed from `"workspace is not a prebuilt workspace, not waiting for reinit"` to `"received terminal 409, stopping reinit polling"`, which correctly covers both 409 reasons (regular workspace and failed claim build).

File: codersdk/agentsdk/agentsdk.go (hunk 21 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:765]: Addressed in 53f58d946. Added a doc comment to `WaitForReinitLoop` explaining the retry loop behavior and documenting that the channel closes on either context cancellation or a terminal 409 Conflict. The caller should select on both the channel and `ctx.Done()`.

File: cli/agent.go (hunk 22 above)
Comment (SasSwart) [reply cli/agent.go]: Addressed in 53f58d946. Comment in `cli/agent.go` updated from `"Channel closed — 409 from server means this is not a prebuild"` to `"Channel closed — the reinit loop exited (terminal 409 or context expired)"`, which correctly covers both close paths.

**Review by mafredri — COMMENTED** [review]
The subscribe-before-check TOCTOU pattern is well-designed, the `?wait` rolling-upgrade gating is a clean solution to the old-agent infinite-reinit problem, and the channel lifecycle (`defer close`, `!ok` handling, nil-channel-in-select) is textbook correct Go concurrency. The test suite is genuine: four real subtests exercising distinct server-side paths with proper DB state setup.

One state machine gap to look at (P2), one minor API contract issue (P3), and three nits across 6 inline comments.

> *Meruem:* "A completed build with no error is successful regardless of cancellation status. Change the success condition to eliminate the class of bug."

> *Ryosuke:* "The handler inlines ~60 lines of claim status business logic. A `ClaimStatus` method on a prebuilds service would make the gap visible as a missing enum case."

> 🤖 Generated by [Coder](https://coder.com/) deep-review v3. 9 Tier 1 + 3 Tier 2 reviewers.

File: coderd/workspaceagents.go [hunk 23]
```diff
@@ -1476,18 +1478,125 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+		}
+		job, err := api.Database.GetProvisionerJobByID(ctx, latestBuild.JobID)
+		if err != nil {
+			log.Error(ctx, "failed to get provisioner job", slog.Error(err))
+			httpapi.InternalServerError(rw, xerrors.New("failed to get provisioner job"))
+			return
+		}
+
+		if job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid {
+			// Claim build succeeded — cancel the subscription
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **P2** Canceled-but-completed claim build falls through the state machine and hangs the agent permanently. *(Meruem P2, Takumi P2, Hisoka P3, Ryosuke P3, Mafuuu P3, Mafu-san P3, Kurapika P3, Bisky P3)*

> The success condition `job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid` does not handle a build that completed successfully despite a concurrent cancel request. In this state (`CompletedAt=true, Error=false, CanceledAt=true`), neither the success branch (rejects CanceledAt) nor the failure branch (requires Error) matches. The code falls through to "claim build still in progress," but the build IS complete and no pubsub event will ever arrive. The agent blocks on the SSE transmitter, disconnects, reconnects, and hits the same dead end every cycle.

> *Meruem adds:* Verified via `provisionerd/runner/runner.go`: when `Canceled=true` is received, the runner calls `Cancel()` for graceful shutdown. If terraform finishes before the force-cancel timeout, `CompleteJob` is called (no error) while `CanceledAt` was already set by the cancel request.

> *Hisoka adds:* The `!job.CanceledAt.Valid` guard was added for R3-P2 to prevent misclassifying pending-canceled builds, but pending-canceled builds are already unreachable: build 2 has no agent rows (`.Starting()` never created resources), so the auth middleware returns 401. The guard protects against a phantom while creating a real gap.

The fix is a one-line change to the success condition:
```go
if job.CompletedAt.Valid && !job.Error.Valid {
```
This eliminates the class of bug: any completed-without-error build is treated as successful, which is correct by definition. Pending-canceled builds remain unreachable via auth.

> 🤖

File: coderd/workspaceagents.go [hunk 24]
```diff
@@ -1476,18 +1478,125 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+	// an infinite reinit loop if we pre-seeded the channel on every
+	// connection.
+	//
+	// If the workspace has already been claimed (i.e. the owner is
+	// no longer the prebuilds system user), check whether it was
+	// originally a prebuild by inspecting the first build's
+	// initiator. The prebuild reconciler always uses
+	// PrebuildsSystemUserID as the initiator for the initial build.
+	if r.URL.Query().Has("wait") && !workspace.IsPrebuild() {
+		firstBuild, err := api.Database.GetWorkspaceBuildByWorkspaceIDAndBuildNumber(ctx,
```
Comment (mafredri) [inline coderd/workspaceagents.go:1515]: **P3** Swagger annotation says `bool`, code checks presence. *(Ryosuke P3, Mafuuu P3, Kurapika Obs, Gon Nit)*

> The swagger declares `@Param wait query bool false`, but `r.URL.Query().Has("wait")` is a presence check. `?wait=false` triggers the durable path, contradicting the documented boolean semantics.

No runtime impact today since the only caller sends `?wait=true`. But a third-party agent reading the API docs could send `?wait=false` expecting opt-out. Either parse the value (`r.URL.Query().Get("wait") == "true"`) or change the swagger type to match the presence-check behavior.

PS. Kurapika notes this is consistent with other query params in this file (`follow`, `no_compression`), so presence-check may be the intended convention.

> 🤖

File: cli/agent.go [hunk 25]
```diff
@@ -343,9 +347,32 @@ func workspaceAgent() *serpent.Command {
...
+						// Channel closed — the reinit loop exited
+						// (terminal 409 or context expired). Keep
+						// running the current agent until the parent
+						// context is canceled.
+						logger.Info(ctx, "reinit channel closed, running without reinit capability")
+						reinitEvents = nil
+						<-ctx.Done()
+						mustExit = true
+					case event.UserID != uuid.Nil && event.UserID == lastOwnerID:
+						// Duplicate reinit for same owner — already
```
Comment (mafredri) [inline cli/agent.go:362]: **Obs** Rolling upgrade produces two reinit cycles before dedup engages. *(Meruem P3, Hisoka P3, Takumi Obs, Killua Obs)*

> During a rolling upgrade, an old publisher sends a raw reason string (not JSON). The backward-compat fallback creates an event with `UserID: uuid.Nil`. The dedup guard (`event.UserID != uuid.Nil && event.UserID == lastOwnerID`) skips nil-UserID events, so the agent reinits. On reconnect, the durable check delivers an event with the real `UserID`. Since `uuid.Nil != real_owner_id`, the agent reinits a second time. After the second reinit, dedup catches it.

Two reinit cycles instead of one during the upgrade window. Self-correcting, reinit is idempotent, and the window is transient. Not worth a code change, but worth knowing about for operators who might see double SSH interruptions during upgrades.

> 🤖

File: codersdk/agentsdk/agentsdk.go [hunk 26]
```diff
@@ -706,8 +707,9 @@ const (
 )
 
 type ReinitializationEvent struct {
-	WorkspaceID uuid.UUID
+	WorkspaceID uuid.UUID              `json:"workspace_id" format:"uuid"`
 	Reason      ReinitializationReason `json:"reason"`
+	UserID      uuid.UUID              `json:"user_id,omitempty" format:"uuid"`
 }
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:713]: **Nit** `omitempty` is a no-op on `uuid.UUID`; use `omitzero`. *(Ging, Gon)*

> `encoding/json` checks array *length* for emptiness, not content. `[16]byte` always has length 16, so `omitempty` never omits `uuid.Nil`. The go.mod declares `go 1.25`; `omitzero` (since 1.24) uses `reflect.Value.IsZero()` which correctly detects an all-zero `[16]byte`.

If omission of nil UUIDs is intended: `json:"user_id,omitzero"`. If it's not: drop `omitempty` to avoid implying the field can be absent.

PS. The `UserID` vs `OwnerID` naming is deferred from prior rounds. Every producer sets this from `workspace.OwnerID` and every consumer calls it `lastOwnerID` / logs `"owner_id"`. A rename would align all three sites.

> 🤖

File: coderd/workspaceagents.go [hunk 27]
```diff
@@ -1476,18 +1478,125 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
 		log.Error(ctx, "subscribe to prebuild claimed channel", slog.Error(err))
 		httpapi.InternalServerError(rw, xerrors.New("failed to subscribe to prebuild claimed channel"))
 		return
 	}
-	defer cancel()
+	defer cancelSub()
+
+	// Only perform the durable claim check when the agent opts in via
+	// the "wait" query parameter. Old agents (pre-v2.X) don't send
+	// this and lack the duplicate-reinit guard, so they would enter
```
Comment (mafredri) [inline coderd/workspaceagents.go]: **Nit** `pre-v2.X` is a placeholder that will never be filled in. *(Gon, Leorio)*

> Once merged, nobody will come back to replace `X` with the actual version number. A reader six months from now won't know what `v2.X` means.

Suggestion: drop the version reference and describe the behavior:
```go
// Old agents that predate the wait parameter don't send
// this and lack the duplicate-reinit guard, so they would
// enter an infinite reinit loop if we pre-seeded the
// channel on every connection.
```

> 🤖

File: codersdk/agentsdk/agentsdk.go [hunk 28]
```diff
@@ -750,21 +755,32 @@ func (c *Client) WaitForReinit(ctx context.Context) (*ReinitializationEvent, err
...
 	go func() {
+		defer close(reinitEvents)
 		for retrier := retry.New(100*time.Millisecond, 10*time.Second); retrier.Wait(ctx); {
 			logger.Debug(ctx, "waiting for agent reinitialization instructions")
 			reinitEvent, err := client.WaitForReinit(ctx)
 			if err != nil {
+				var sdkErr *codersdk.Error
+				if errors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusConflict {
+					logger.Info(ctx, "received terminal 409, stopping reinit polling")
+					return
```
Comment (mafredri) [inline codersdk/agentsdk/agentsdk.go:777]: **Nit** 409 log message discards the server's reason. *(Leorio)*

> The log says `"received terminal 409, stopping reinit polling"` but does not include `sdkErr.Message`, which carries the diagnosis: either "Workspace is not a prebuilt workspace waiting to be claimed" or "Claim build failed permanently." An operator seeing this log line at 2 AM knows the symptom but not the cause.

Suggestion:
```go
logger.Info(ctx, "received terminal 409, stopping reinit polling",
    slog.F("message", sdkErr.Message))
```

> 🤖

File: coderd/workspaceagents.go (hunk 16 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: Resolved in 53f58d94. The durable claim check is now gated on `r.URL.Query().Has("wait")` (line 1513). New agents send `?wait=true` (agentsdk.go line 728); old agents don't include the parameter and get the old pubsub-only behavior. This eliminates the infinite reinit loop during rolling upgrades without version negotiation.

File: codersdk/agentsdk/agentsdk.go (hunk 13 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go]: Resolved in 1195c77. Renamed `UserID` → `OwnerID` with JSON tag `owner_id` and replaced `omitempty` with `omitzero` (agentsdk.go line 712):

```go
OwnerID     uuid.UUID              `json:"owner_id,omitzero" format:"uuid"`
```

Updated all 8 usage sites across `workspaceagents.go`, `provisionerdserver.go`, `cli/agent.go`, and tests.

File: codersdk/agentsdk/agentsdk.go (hunk 21 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:765]: Resolved in 53f58d94. `WaitForReinitLoop` now has a doc comment (agentsdk.go lines 758-763):

```go
// WaitForReinitLoop polls the /reinit SSE endpoint in a retry loop and
// forwards received reinitialization events to the returned channel. The
// channel is closed when ctx is canceled or the server returns 409
// Conflict (indicating the workspace is not a prebuilt workspace or the
// claim build failed permanently). The caller should select on both the
// channel and ctx.Done().
```

File: codersdk/agentsdk/agentsdk.go (hunk 8 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:710]: Acknowledged. The rolling-upgrade note in the PR description covers this — the only visible effect during the upgrade window is zero-UUID log lines, which resolve once all instances are updated. Subsumed by the P1 rolling-upgrade fix (the `?wait` query parameter gate).

File: coderd/workspaceagents.go (hunk 17 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1556]: Resolved in 53f58d94. The success condition now includes `!job.CanceledAt.Valid` (line 1556):

```go
if job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid {
```

A cancelled-but-completed job no longer matches the success branch.

File: cli/agent.go (hunk 22 above)
Comment (SasSwart) [reply cli/agent.go]: Resolved in 53f58d94. The comment now reads (cli/agent.go lines 353-356):

```go
// Channel closed — the reinit loop exited
// (terminal 409 or context expired). Keep
// running the current agent until the parent
// context is canceled.
```

This covers both exit paths without overstating a single cause.

File: coderd/workspaceagents_test.go (hunk 18 above)
Comment (SasSwart) [reply coderd/workspaceagents_test.go:3296]: Accepted per mafredri's follow-up — the auth middleware prevents a clean end-to-end test at this level (build 1's agent token gets 401 when build 2 exists but has no agent rows yet via `.Starting()`). The "unclaimed prebuild receives reinit via pubsub" test already exercises the pubsub→transmitter path, and the gating logic is covered by the other subtests.

File: codersdk/agentsdk/agentsdk.go (hunk 20 above)
Comment (SasSwart) [reply codersdk/agentsdk/agentsdk.go:774]: Resolved in 53f58d94. The log message now reads `"received terminal 409, stopping reinit polling"` (agentsdk.go line 775), covering both the regular-workspace and failed-claim-build cases without asserting a specific cause.

File: coderd/workspaceagents.go (hunk 19 above)
Comment (SasSwart) [reply coderd/workspaceagents.go:1584]: Resolved in 53f58d94. The fall-through comment (lines 1591-1598) now explicitly says "when the build completes successfully" and notes the `FailJob` gap:

```
// Note: FailJob does not publish a claim event, so a failed
// in-progress build will leave the agent blocking here until
// it disconnects and reconnects (at which point the durable
// check above handles it).
```

This is pre-existing behavior that the PR does not worsen — on reconnect, the `job.Error.Valid` branch now returns 409 instead of hanging.

File: coderd/prebuilds/claim.go [hunk 29]
```diff
@@ -48,18 +53,23 @@ func (p PubsubWorkspaceClaimListener) ListenForWorkspaceClaims(ctx context.Conte
...
+			}
 		}
 
 		select {
 		case <-ctx.Done():
 			return
 		case <-inner.Done():
 			return
-		case reinitEvents <- claim:
+		case reinitEvents <- event:
```
Comment (mafredri) [inline coderd/prebuilds/claim.go:75]: 🏂🏻 I didn't trace the code, but:

Since this is a subscription and Go picks select branch on random. If `reinitEvents` is _ever closed_, this subscription may race to send on a closed channel which will panic. Subscription must be fully unsubscribed (and the unsubscribe function must give guarantees that all pending subscription callbacks have returned) before closing the channel.

**Design note:** The existing design of `ListenForWorkspaceClaims` is somewhat dangerous and easy to use in the wrong way. Both send and close are write operations on a channel and these should be orchestrated from the same place so that safety can be guaranteed. For example, this function could have created `reinitEvents` and returned it, allowing it to be the sole manager of write operations.

File: cli/agent.go (hunk 25 above)
Comment (mafredri) [reply cli/agent.go:362]: Not a required change. 🏂🏻

File: coderd/workspaceagents.go (hunk 23 above)
Comment (mafredri) [reply coderd/workspaceagents.go]: This sounds worth fixing if valid. 🏂🏻

File: coderd/workspaceagents.go [hunk 30]
```diff
@@ -1481,18 +1478,125 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+		if job.CompletedAt.Valid && !job.Error.Valid && !job.CanceledAt.Valid {
+			// Claim build succeeded — cancel the subscription
+			// (we no longer need pubsub) and pre-seed the
+			// channel so the transmitter delivers exactly one
+			// reinit event. Use a non-blocking send in case
+			// pubsub already delivered the event before we
+			// canceled.
+			cancelSub()
+			select {
+			case reinitEvents <- agentsdk.ReinitializationEvent{
```
Comment (mafredri) [inline coderd/workspaceagents.go]: We may end up sending a second event if we don't know whether or not the pubs did. Expected behavior? 🏂🏻

File: coderd/workspaceagents.go [hunk 31]
```diff
@@ -1481,18 +1478,125 @@ func (api *API) workspaceAgentReinit(rw http.ResponseWriter, r *http.Request) {
...
+				WorkspaceID: workspace.ID,
+				Reason:      agentsdk.ReinitializeReasonPrebuildClaimed,
+				OwnerID:     workspace.OwnerID,
+			}:
+			default:
+				// Pubsub already delivered the event.
+			}
+			// Don't close the channel — the transmitter will
```
Comment (mafredri) [inline coderd/workspaceagents.go]:
```suggestion
			// Don't close the channel. The transmitter will
```
Nit: Please avoid committing emdashes to the codebase. They are rarely appropriate and AI's overuse them. I saw a few others instances too. The more occurrences the code base has, the more they will propagate. Even into parts the user directly interacts with (CLI, UI). 🏂🏻

File: codersdk/agentsdk/agentsdk.go (hunk 28 above)
Comment (mafredri) [reply codersdk/agentsdk/agentsdk.go:777]: Seems like a nice addition. 🏂🏻

**Review by mafredri — APPROVED** [review]
Except for the question regarding `reinitEvents` safety (I'd like to see human confirmation on it), all my remaining requests are simple enough to address, so pre-approving! 🏂🏻

File: coderd/prebuilds/claim.go (hunk 29 above)
Comment (SasSwart) [reply coderd/prebuilds/claim.go:75]: It took a while to figure out a simple way to solve this, but I found one. Thanks for the feedback.

File: coderd/workspaceagents.go (hunk 30 above)
Comment (SasSwart) [reply coderd/workspaceagents.go]: This has been solved by my fix to your first comment. The db check takes priority. If it detects an event, it sends it and ignores the pubsub events that may or may not have arrived.

File: coderd/prebuilds/claim.go (hunk 29 above)
Comment (SasSwart) [reply coderd/prebuilds/claim.go:75]: We now use two different channels. One for the pubsub, and one for the db check. The check takes precedence. So if it succeeds, we pass it for transmission instead of the pubsub channel. I have also refactored `ListenForWorkspaceClaims` to own its channel outright.
