### PR TITLE
fix: exclude prebuilt workspaces from lifecycle executor

### LINKED ISSUE #18740: Prebuilds trigger autostart/autostop/dormancy before claiming
## Description 

The Workspace schedule (Autostart/Autostop) and dormancy features can be configured at 2 levels:
* Template-level
* Workspace-level

Prebuilt workspaces inherit these lifecycle configurations from their associated template or workspace. However, prebuilds should not actively follow these settings until they are claimed by a user (i.e., when the `owner_id` transitions from the prebuilds user to a regular user). Applying lifecycle logic prematurely **conflicts with prebuild-specific behaviors**, such as the `expiration_policy` and prebuild `scheduling` mechanisms, which are designed to manage prebuilds independently of user-driven workspace lifecycle features.

## Actual Behavior

* Prebuilds start behaving as if they are regular workspaces (autostarting, stopping, or becoming dormant) before they are claimed. 
* Specifically, the lifecycle executor (which manages these features) may stop prebuilds based on the inherited configuration. 
* However, stopped prebuilds are not counted as running by the reconciliation loop, which monitors and ensures that the number of running prebuild instances matches the desired number. 
* As a result, the reconciliation loop will see fewer running prebuilds than desired and will attempt to start new prebuild instances, leading to churn, inefficiency, and instability in the prebuild system.

## Expected Behavior

* Prebuilds can inherit lifecycle settings from the template or workspace.
* These settings should not be enforced or acted upon while the workspace is in the prebuild phase (owned by the prebuilds user).
* Once a prebuild is claimed (ownership changes to a regular user), the lifecycle settings should take effect.

## Proposed Fix

Introduce logic to skip enforcement of Autostart, Autostop, and Dormancy in the `lifecycle_executor` for workspaces owned by the prebuilds user. Enforcement should only begin once ownership is transferred to a real user.

Related with: https://github.com/coder/coder/issues/18658

### PR DESCRIPTION
**Pull request by ssncferreira**
## Description

This PR updates the lifecycle executor to explicitly exclude prebuilt workspaces from being considered for lifecycle operations such as `autostart`, `autostop`, `dormancy`, `default TTL` and `failure TTL`.

Prebuilt workspaces (i.e., those owned by the prebuild system user) are handled separately by the prebuild reconciliation loop. Including them in the lifecycle executor could lead to unintended behavior such as incorrect scheduling or state transitions.

## Changes

* Updated the lifecycle executor query `GetWorkspacesEligibleForTransition` to exclude workspaces with `owner_id = 'c42fdf75-3097-471c-8c33-fb52454d81c0'` (prebuilds).
* Added tests to verify prebuilt workspaces are not considered in:
  * Autostop
  * Autostart
  * Default TTL
  * Dormancy
  * Failure TTL

Fixes: https://github.com/coder/coder/issues/18740
Related to: https://github.com/coder/coder/issues/18658

### CODE REVIEW

File: enterprise/coderd/workspaces_test.go [hunk 1]
```diff
@@ -1713,6 +1720,793 @@ func TestTemplateDoesNotAllowUserAutostop(t *testing.T) {
...
+	})
+
+	// Prebuild workspaces should not follow the autostart schedule.
+	// This test verifies that AutostartRequirement (autostart schedule) is ignored while the workspace is a prebuild.
+	t.Run("AutostartScheduleOnlyTriggersAfterClaim", func(t *testing.T) {
+		t.Parallel()
+
+		// Set the clock to dbtime.Now() to match the workspace build's CreatedAt
+		clock := quartz.NewMock(t)
+		clock.Set(dbtime.Now())
```
Comment (ssncferreira) [inline enterprise/coderd/workspaces_test.go:2097]: `WorkspaceBuild.CreatedAt` is set using `dbtime.Now()`https://github.com/coder/coder/blob/main/coderd/wsbuilder/wsbuilder.go#L424, which is not mockable. Since the next autostart schedule is computed based on the workspace's `LatestBuild.CreatedAt` https://github.com/coder/coder/blob/main/coderd/autobuild/lifecycle_executor.go#L523 it's not possible to control the autostart behavior precisely in tests.

This limitation is not addressed in this PR, but to improve test reliability and determinism, we should consider injecting a clock into the workspace builder (wsbuilder) in the future, so tests can simulate specific timestamps consistently.

File: coderd/autobuild/lifecycle_executor_test.go [hunk 2]
```diff
@@ -1183,6 +1190,348 @@ func TestNotifications(t *testing.T) {
...
+		OrganizationID:    orgID,
+		OwnerID:           database.PrebuildsSystemUserID,
+		Deleted:           false,
+		CreatedAt:         time.Now().Add(-time.Hour * 2),
+		AutostartSchedule: options.AutostartSchedule,
+	})
+	setupTestDBWorkspaceBuild(ctx, t, clock, db, ps, orgID, workspace.ID, templateVersionID, presetID, buildTransition)
+
+	return workspace
+}
```
Comment (johnstcn) [inline coderd/autobuild/lifecycle_executor_test.go:1533]: Suggestion: It would be useful to have this in `dbgen`; I think we have this in a couple of other places.

File: enterprise/coderd/workspaces_test.go [hunk 3]
```diff
@@ -1713,6 +1720,793 @@ func TestTemplateDoesNotAllowUserAutostop(t *testing.T) {
...
+	getRunningPrebuilds := func(
+		t *testing.T,
+		ctx context.Context,
+		db database.Store,
+		prebuildInstances int,
+	) []database.GetRunningPrebuiltWorkspacesRow {
+		t.Helper()
+
+		var runningPrebuilds []database.GetRunningPrebuiltWorkspacesRow
+		require.Eventually(t, func() bool {
```
Comment (johnstcn) [inline enterprise/coderd/workspaces_test.go]: Suggestion: Use `testutil.Eventually` instead as it's context-aware.

File: enterprise/coderd/workspaces_test.go [hunk 4]
```diff
@@ -1713,6 +1720,793 @@ func TestTemplateDoesNotAllowUserAutostop(t *testing.T) {
...
+				name:                    "ClaimedBeforeDeadline_UsesSameDeadline",
+				isClaimedBeforeDeadline: true,
+			},
+			// If the prebuild is claimed after the scheduled deadline,
+			// the workspace should not stop immediately, but instead respect the next
+			// valid scheduled deadline (the next day).
+			{
+				name:                    "ClaimedAfterDeadline_SchedulesForNextDay",
+				isClaimedBeforeDeadline: false,
+			},
```
Comment (johnstcn) [inline enterprise/coderd/workspaces_test.go:1957]: This is a _really_ good test to have. 👍

File: site/src/api/typesGenerated.ts [hunk 5]
```diff
@@ -275,11 +275,12 @@ export interface BuildInfoResponse {
 }
 
 // From codersdk/workspacebuilds.go
-export type BuildReason = "autostart" | "autostop" | "initiator";
+export type BuildReason = "autostart" | "autostop" | "dormancy" | "initiator";
```
Comment (johnstcn) [inline site/src/api/typesGenerated.ts:278]: 👀 Nice catch, didn't know this was always missing.

File: site/src/utils/workspace.tsx [hunk 6]
```diff
@@ -75,14 +75,15 @@ export const getDisplayWorkspaceBuildStatus = (
...
-): string => {
+): string | undefined => {
 	switch (build.reason) {
 		case "initiator":
 			return build.initiator_name;
 		case "autostart":
 		case "autostop":
 			return "Coder";
 	}
+	return undefined;
```
Comment (johnstcn) [inline site/src/utils/workspace.tsx:87]: Shouldn't we handle the `dormancy` reason here and return `Coder`?

File: docs/admin/templates/extending-templates/prebuilt-workspaces.md
[the remark this answers is not in the document]
Comment (ssncferreira) [reply docs/admin/templates/extending-templates/prebuilt-workspaces.md:1]: Addressed in https://github.com/coder/coder/pull/18762/commits/fd12369932b12a55f47a7968ce23ba60b5777768

File: coderd/autobuild/lifecycle_executor_test.go (hunk 2 above)
Comment (ssncferreira) [reply coderd/autobuild/lifecycle_executor_test.go:1533]: We definitely should 😞 I have been copy-pasting this across tests, and just tweaking the parameters that I need for the specific test, but we should move it to `dbgen` and make it generic. I will try addressing this in a separate PR. 

The `templateWithAgentAndPresetsWithPrebuilds` function is also a good candidate to be moved somewhere for being reused. Not sure where 🤔

File: enterprise/coderd/workspaces_test.go (hunk 3 above)
Comment (ssncferreira) [reply enterprise/coderd/workspaces_test.go]: Addressed in https://github.com/coder/coder/pull/18762/commits/2bb2102fcc3bfb4bc8bd2556eff7de740aec98b1

File: enterprise/coderd/workspaces_test.go (hunk 4 above)
Comment (ssncferreira) [reply enterprise/coderd/workspaces_test.go:1957]: I also wanted to do the same for the Autostart test, but couldn't because of the workspace build's `createdAt` using `dbtime.Now()` (see comment https://github.com/coder/coder/pull/18762#discussion_r2189709800)

File: site/src/utils/workspace.tsx (hunk 6 above)
Comment (ssncferreira) [reply site/src/utils/workspace.tsx:87]: Good catch! This was failing in the linter, and I assumed it was because the `dormancy` case was added, but apparently not. Addressed in:  https://github.com/coder/coder/pull/18762/commits/d1a9c6494515b67ab23ed5b82fc637fd0a686abd

**Review by DanielleMaywood — APPROVED** [review]
The lifecycle executor change looks good to me 👍 I've tried my best to understand the prebuild tests but I'm not sure I'd be able to spot if there were any issues there 😄

**Review by johnstcn — APPROVED** [review]
