### PR TITLE
fix: use pre-built binary instead of `go run` in e2e tests

### LINKED ISSUE #204: flake: e2e-premium test app
```
/home/runner/work/coder/coder/site/e2e/helpers.ts:430:
   at helpers.ts:430

  428 | 	await page
  429 | 		.getByTestId("agent-status-ready")
> 430 | 		.waitFor({ state: "visible", timeout: 45_000 });
      | 		 ^
  431 | 	return cp;
  432 | };
  433 |
TimeoutError: locator.waitFor: Timeout 4[500](https://github.com/coder/coder/runs/32607981335#step:11:501)0ms exceeded.
Call log:
  - waiting for getByTestId('agent-status-ready') to be visible
```

Seen here: https://github.com/coder/coder/runs/32607981335

### LINKED ISSUE #279: flake: `app.spec.ts` E2E test
Seen here: https://github.com/coder/coder/actions/runs/12827736403/job/35770358361?pr=16169

```
/home/runner/work/coder/coder/site/e2e/tests/app.spec.ts:66:
  64 |
  65 | 	// Wait for the web terminal to open in a new tab
> 66 | 	const pagePromise = context.waitForEvent("page");
     | 	                            ^
  67 | 	await page.getByText(appName).click({ timeout: 60_000 });
  68 | 	const app = await pagePromise;
  69 | 	await app.waitForLoadState("domcontentloaded");
TimeoutError: browserContext.waitForEvent: Timeout 5000ms exceeded while waiting for event "page"
```

### PR DESCRIPTION
**Pull request by aslilac**
Closes coder/internal#204
Closes coder/internal#279

Using `go run` inside of a test is fragile, because it means we have to wait for `go` to compile the binary while also constrained on resources by the fact that Playwright and coderd are already running. We should instead compile a coder binary for the current platform before the tests and use it directly.

### CODE REVIEW

**Comment by spikecurtis** [comment]
I think maybe the PR description is out of date

File: site/e2e/helpers.ts [hunk 1]
```diff
@@ -479,27 +476,21 @@ export const startAgentWithCommand = async (
 		},
 	});
 	cp.stdout.on("data", (data: Buffer) => {
-		console.info(
-			`[agent] [stdout] [onData] ${data.toString().replace(/\n$/g, "")}`,
-		);
+		console.info(`[agent][stdout] ${data.toString().replace(/\n$/g, "")}`);
```
Comment (Parkreiner) [inline site/e2e/helpers.ts:479]: Big fan of the cleaner logs

File: site/e2e/tests/app.spec.ts [hunk 2]
```diff
@@ -18,8 +18,6 @@ test.beforeEach(async ({ page }) => {
 });
 
 test("app", async ({ context, page }) => {
-	test.setTimeout(75_000);
```
Comment (Parkreiner) [inline site/e2e/tests/app.spec.ts:21]: Big, big fan

**Review by buenos-nachos — APPROVED** [review]
Changes look good, but yeah, agree with Spike – definitely need a new description, especially if we're going to be using it for the squashed message

**Comment by aslilac** [comment]
> Either there's some crazy contention bug, the agent randomly takes 45 seconds to compile and run,

I love that you can see exactly where I realized what the problem was 😂

But yeah, I'll update the description.

File: site/e2e/setup/preflight.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
+import { execSync } from "node:child_process";
+import * as path from "node:path";
+
+export default function () {
```
[the remark this answers is not in the document]
Comment (aslilac) [reply site/e2e/setup/preflight.ts:4]: yeah, if you look in playwright.config.ts we specify a `globalSetup` option and with a path to this file as the value. playwright will then load this file and execute the default export exactly once per test run.

it's not safe to do any of this in the playwright.config.ts file directly because that gets executed once per worker (ie. potentially dozens of times per run)
