### PR TITLE
fix: hide "Create Workspace" button for deleted templates

### LINKED ISSUE #17417: bug: hide *Create Workspace* button for deleted workspaces
On the <https://dev.coder.com/templates?filter=deleted%3Atrue|Templates> page, we show the *Create Workspace* button when `deleted:true,` which actually does not work and shows an always spinning window and developer console log saying `Failed to load resource: the server responded with a status of 404 ()`. We should hide that button similar to what we do with `deprecated:true`

Image

Image

[Slack Message](https://codercom.slack.com/archives/C015YDF37AT/p1744802791425059)

### PR DESCRIPTION
**Pull request by jeremyruppel**
**Background**

Reported in #17417, there is a `deleted` query parameter supported by /api/v2/templates, but we do not respect this field on the client, showing the "Create Workspace" button for deleted templates.

**Expected Behavior**

Don't show the "Create Workspace" button for deleted templates.

**Notes**

This PR adds a new `deleted` field to the templates API response.

### CODE REVIEW

**Comment by jeremyruppel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by DanielleMaywood — COMMENTED** [review]
Could you make sure we have a storybook story for the case where `deleted` is `true`?

File: coderd/templates_test.go [hunk 1]
```diff
@@ -1801,6 +1801,22 @@ func TestDeleteTemplate(t *testing.T) {
...
+		template := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID)
+		coderdtest.AwaitTemplateVersionJobCompleted(t, client, version.ID)
+
+		ctx := testutil.Context(t, testutil.WaitLong)
+
+		// Verify the deleted field is exposed in the SDK and set to false for active templates
+		got, err := client.Template(ctx, template.ID)
+		require.NoError(t, err)
+		require.False(t, got.Deleted)
+	})
```
Comment (DanielleMaywood) [inline coderd/templates_test.go:1819]: Could we have another test to verify `require.True(t, got.Deleted)` after you call `user.DeleteTemplate`?

File: site/src/pages/TemplatesPage/TemplatesPageView.tsx [hunk 2]
```diff
@@ -85,6 +85,47 @@ const TemplateHelpTooltip: FC = () => {
...
+					e.stopPropagation();
+				}}
+			>
+				<RouterLink to={`${templatePageLink}/workspace`}>
+					<ArrowRightIcon />
+					Create Workspace
+				</RouterLink>
+			</Button>
+		);
+	}
```
Comment (DanielleMaywood) [inline site/src/pages/TemplatesPage/TemplatesPageView.tsx:111]:
```suggestion
	if (!workspacePermissions?.[template.organization_id]?.createWorkspaceForUserID) {
		return null;
	}
	
	return (
		<Button
			asChild
			variant="outline"
			size="sm"
			title={`Create a workspace using the ${template.display_name} template`}
			onClick={(e) => {
				e.stopPropagation();
			}}
		>
			<RouterLink to={`${templatePageLink}/workspace`}>
				<ArrowRightIcon />
				Create Workspace
			</RouterLink>
		</Button>
	);
```

**Review by DanielleMaywood — COMMENTED** [review]
Sorry but got two more minor comments:

- We could do with a test to verify `got.Deleted` can also be true
- Just a minor nit with the frontend component, we can make use of an early return to reduce the indentation by a level

File: coderd/templates_test.go (hunk 1 above)
Comment (jeremyruppel) [reply coderd/templates_test.go:1819]: This was a little harder than I expected! There's a test now for deleted templates showing up in the template list, but it turns out I can't fetch the template itself (it'll 404).

File: site/src/pages/TemplatesPage/TemplatesPageView.tsx [hunk 3]
```diff
@@ -85,6 +85,49 @@ const TemplateHelpTooltip: FC = () => {
...
+
+	if (
+		!workspacePermissions?.[template.organization_id]?.createWorkspaceForUserID
+	) {
+		return null;
+	}
+
+	if (template.deprecated) {
+		return <DeprecatedBadge />;
+	}
```
Comment (DanielleMaywood) [inline site/src/pages/TemplatesPage/TemplatesPageView.tsx]: We've _slightly_ changed the behaviour here. Previously if `createWorkspaceForUserID` was `false`, we would still see `DeprecatedBadge`.


```suggestion
	if (template.deprecated) {
		return <DeprecatedBadge />;
	}
	
	if (
		!workspacePermissions?.[template.organization_id]?.createWorkspaceForUserID
	) {
		return null;
	}
```

**Review by DanielleMaywood — COMMENTED** [review]
The Go tests look good to me! Final little nit and then we're good to go!

File: site/src/pages/TemplatesPage/TemplatesPageView.tsx (hunk 3 above)
Comment (jeremyruppel) [reply site/src/pages/TemplatesPage/TemplatesPageView.tsx]: Great catch, thanks! 🙏

**Review by DanielleMaywood — APPROVED** [review]
