### PR TITLE
fix: handle paths with spaces in Match exec clause of SSH config

### LINKED ISSUE #18199: bug: config-ssh writes bad Match exec clause on Windows
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

`coder config-ssh` writes a config stanza like

```
# ------------START-CODER-----------
# This section is managed by coder. DO NOT EDIT.
#
# You should not hand-edit this section unless you are removing it, all
# changes will be lost when running "coder config-ssh".
#
Host coder.*
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand "C:\Program Files\Coder\bin\coder.exe" --global-config C:\Users\micha\AppData\Roaming\coderv2 ssh --stdio --ssh-host-prefix coder. %h

Host *.coder
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR

Match host *.coder !exec ""C:\Program Files\Coder\bin\coder.exe" connect exists %h"
        ProxyCommand "C:\Program Files\Coder\bin\coder.exe" --global-config C:\Users\micha\AppData\Roaming\coderv2 ssh --stdio --hostname-suffix coder %h
# ------------END-CODER------------
```

This results in a failed ssh invocation

```
C:\Users\micha\Downloads> ssh net-integration.coder
Missing Match criteria for exec
C:\\Users\\micha/.ssh/config line 66: Bad Match condition
C:\\Users\\micha/.ssh/config: terminating, 1 bad configuration options
```

### Relevant Log Output

```shell

```

### Expected Behavior

`ssh` should connect

### Steps to Reproduce

1. Install Coder on Windows to a path with a space in it like `C:\Program Files\Coder\`
2. run `coder config-ssh`
3. run `ssh <workspace>`

### Environment

- Host OS: Windows 11
- Coder version: 2.22.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #18199 

Corrects handling of paths with spaces in the `Match !exec` clause we use to determine whether Coder Connect is running. This is handled differently than the ProxyCommand, so we have a different escape routine, which also varies by OS.

On Windows, we resort to a pretty gnarly hack, but it does work and I feel the only other option would be to reduce functionality such that we could not detect the Coder Connect state.

### CODE REVIEW

File: cli/configssh_windows.go [hunk 1]
```diff
@@ -2,5 +2,58 @@
...
+// to do it, but powershell.exe can convert ASCII to characters like this: `[char]34` (where 34 is the code point for ").
+//
+// Other notes:
+//   - @ in `@cmd.exe` suppresses echoing it, so you don't get this command printed
+//   - we need another invocation of cmd.exe (e.g. `do @cmd.exe /c %%aC:\Program Files\Coder\bin\coder.exe%%a`). Without
+//     it the double-quote gets interpreted as part of the path, and you get: '"C:\Program' is not recognized.
+//     Constructing the string and then passing it to another instance of cmd.exe does this trick here.
+//   - OpenSSH passes the `Match exec` command to cmd.exe regardless of whether the user has a unix-like shell like
+//     git bash, so we don't have a `forceUnixPath` option like for the ProxyCommand which does respect the user's
+//     configured shell on Windows.
```
Comment (mafredri) [inline cli/configssh_windows.go:42]: Thanks for the great write-up! ❤️

QQ: Is there a chance the "default shell" that OpenSSH uses can be configured to be powershell instead of cmd.exe? And if yes, would the for loop break?

File: cli/configssh_windows.go [hunk 2]
```diff
@@ -2,5 +2,58 @@
...
+		return "", xerrors.Errorf("invalid path: %s", path)
+	}
+	// Windows does not allow double-quotes or tabs in paths. If we get one it is an error.
+	if strings.ContainsAny(path, "\"\t") {
+		return "", xerrors.Errorf("path must not contain quotes or tabs: %q", path)
+	}
+
+	if strings.ContainsAny(path, " ") {
+		// c.f. function comment for how this works.
+		path = fmt.Sprintf("for /f %%%%a in ('powershell.exe -Command [char]34') do @cmd.exe /c %%%%a%s%%%%a", path) //nolint:gocritic // We don't want %q here.
```
Comment (mafredri) [inline cli/configssh_windows.go:56]: 💫😵💫 %%%%%%%%%%%%%%%%%%%%%%%% 💫😵💫

**Review by mafredri — APPROVED** [review]
Thanks for the research and docs here. Although this is indisputably gnarly, I much prefer it to the alternative of reducing functionality. Kudos on finding this hack 👍🏻

Please note QQ in inline comment, but other than that, approved!

File: cli/configssh_windows.go (hunk 1 above)
Comment (spikecurtis) [reply cli/configssh_windows.go:42]: I've looked into this, and OpenSSH on Windows calls `system`, which seems to always be `cmd.exe`.

https://github.com/PowerShell/openssh-portable/blob/bdacf9868fe9e8024a5312861b7aaa6faba1821f/readconf.c#L544

https://learn.microsoft.com/en-us/cpp/c-language/system-function?view=msvc-170
