### PR TITLE
fix(site): ensure empty string error shows default message

### LINKED ISSUE #9042: bug: When Coder is upgraded workspace page shows an empty banner
When Coder is upgraded, the Workspace page shows an empty banner with no error message. It goes away with a  page refresh
image
cc: @BrunoQuaresma

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #9042

If we get a 404 or similar, Axios still creates a response body (with a missing message). We were not checking for this.

With this fix, we will still see an error banner because the API has stopped responding; however, now it is populated with our default message:
Screenshot 2023-10-11 at 12 07 47 PM

### CODE REVIEW

**Comment by matifali** [comment]
Testing this now.

**Review by BrunoQuaresma — APPROVED** [review]

**Comment by matifali** [comment]
There is no backend. This happens when the coder is down. So network logs have either 503 or 403 errors.

File: site/src/api/errors.ts [hunk 1]
```diff
@@ -62,10 +62,13 @@ export const getErrorMessage = (
...
 ): string => {
-  if (isApiError(error)) {
+  // if error is API error
+  // 404s result in the default message being returned
+  if (isApiError(error) && error.response.data.message) {
     return error.response.data.message;
   }
-  if (typeof error === "string") {
+  // if error is a non-empty string
+  if (error && typeof error === "string") {
```
Comment (Kira-Pilot) [inline site/src/api/errors.ts:71]: even though this wasn't the fix for this bug, I'm keeping it because we should guard against empty strings anyway

**Review by BrunoQuaresma — APPROVED** [review]

**Comment by matifali** [comment]
We have verified that it is resolved. Thanks @Kira-Pilot

**Comment by Kira-Pilot** [comment]
> We have verified that it is resolved.
Thanks so much for your help @matifali!
