### PR TITLE
fix(coderd): fix memory leak in `watchWorkspaceAgentMetadata`

### LINKED ISSUE #10550: Potential Memory Leak in 2.3
After upgrading the coder helm chart from v2.2 to v2.3 on 10/20, we started seeing significant memory (tens of gigabytes), CPU (multiple cores), and constant container restarts.

CPU Usage:
image

Memory Usage:
image

Container Restarts: 
image

### PR DESCRIPTION
**Pull request by mafredri**
A change to agent metadata processing was introduced in https://github.com/coder/coder/releases/tag/v2.3.1 which introduced a logic bug leading to a memory leak. However, it's not entirely clear how this can be triggered. I managed to trigger it twice, but the exact steps elude me. One time `coderd` was left with a permanent memory consumption of 1.7 GB and the other time, it was OOM killed (ironically, after I had given up reproducing the issue).

To trigger the memory leak that was fixed here, the `coderd` watch metadata handler has to 1) subscribe to metadata updates via pubsub and 2) somewhere along the way, begin teardown of the handler or exit the consumer running in a goroutine _without_ getting so far as to unsubscribing from the pubsub.

Potential triggers for the bug:
1. Slow/hung database read
2. Slow/hung write on the HTTP connection (SSE)
3. Unsubscribe from pubsub failing -- seems unlikely

~~This is not guaranteed to fix #10550, but it's a good candidate.~~

Fixes #10550
Closes https://github.com/coder/customers/issues/334

### CODE REVIEW

File: coderd/workspaceagents.go [hunk 1]
```diff
@@ -1859,17 +1865,16 @@ func (api *API) watchWorkspaceAgentMetadata(rw http.ResponseWriter, r *http.Requ
...
-					keys = append(keys, key)
+				prevKeysSet[key] = struct{}{}
+			}
+			for _, key := range payload.Keys {
+				if _, ok := prevKeysSet[key]; !ok {
+					prev.Keys = append(prev.Keys, key)
 				}
 			}
-			payload.Keys = keys
+			payload.Keys = prev.Keys
```
Comment (mafredri) [inline coderd/workspaceagents.go:1877]: This is the actual memory leak (logic bug).

File: coderd/workspaceagents.go [hunk 2]
```diff
@@ -1891,12 +1896,22 @@ func (api *API) watchWorkspaceAgentMetadata(rw http.ResponseWriter, r *http.Requ
...
 	}()
+	// Synchronize cancellation from SSE -> context, this lets us simplify the
+	// cancellation logic.
+	go func() {
+		select {
+		case <-ctx.Done():
+		case <-sseSenderClosed:
+			cancel()
+		}
+	}()
```
Comment (mafredri) [inline coderd/workspaceagents.go:1910]: These changes were added so that we can be sure we're not blocking on `<-sseSenderClosed`.

File: codersdk/workspaceagents.go [hunk 3]
```diff
@@ -492,6 +492,11 @@ func (c *Client) WatchWorkspaceAgentMetadata(ctx context.Context, id uuid.UUID)
 				firstEvent = false
 			}
 
+			// Ignore pings.
+			if sse.Type == ServerSentEventTypePing {
+				continue
+			}
```
Comment (mafredri) [inline codersdk/workspaceagents.go:498]: This was a bug in `WatchWorkspaceAgentMetadata`, leading to hitting an error below (nil data) and breaking the watcher. This could be a/the cause that the agent metadata tests have been flakey in the past.

**Comment by spikecurtis** [comment]
FWIW, I think we'd hit this bug on an ordinary DB fetch error, not just a slow or hung fetch.

That's because we had

```
	sseSendEvent, sseSenderClosed, err := httpapi.ServerSentEventSender(rw, r)
	if err != nil {
		httpapi.Write(ctx, rw, http.StatusInternalServerError, codersdk.Response{
			Message: "Internal error setting up server-sent events.",
			Detail:  err.Error(),
		})
		return
	}
	// Prevent handler from returning until the sender is closed.
	defer func() {
		<-sseSenderClosed
	}()
```

and once you call this, the only things that allow `sseSenderClosed` to close is r.Context() expiring or a write error sending an event.

So, when we do

```
	md, err := api.Database.GetWorkspaceAgentMetadata(ctx, database.GetWorkspaceAgentMetadataParams{
		WorkspaceAgentID: workspaceAgent.ID,
		Keys:             nil,
	})
	if err != nil {
		// If we can't successfully pull the initial metadata, pubsub
		// updates will be no-op so we may as well terminate the
		// connection early.
		httpapi.InternalServerError(rw, err)
		return
	}
```

`httpapi.InternalServerError(rw, err)` doesn't actually shut down the SSE, and in fact, probably just corrupts the SSE stream, if anything.  At that point it sort of depends on what the client does.  If they cleanly hang up then maybe `r.Context()` gets closed, but if they just ignore the malformed data and keep reading then we just block, since the server will send no more events.

**Comment by mafredri** [comment]
> FWIW, I think we'd hit this bug on an ordinary DB fetch error, not just a slow or hung fetch.

Yeah, I agree. I know that wasn't the cause in my repro though since my logs were missing the line indicating a DB error happened.

Good catch on the `httpapi.InternalServerError`, we should make sure these invocations fail/are not permitted on SSE connections. Or automatically translated to SSE error payload (but that's too much magic perhaps).

> I like what you've done with squirreling away a cancelable context on the Request, but perhaps it makes sense to just accept a context in `httpapi.ServerSentEventSender()` instead of the Request. That might make it a little more obvious how to cancel.

Big agree, I wasn't super happy with the squirreling, so I was thinking I'll take a look at refactoring the SSE sender in a separate PR. I do think it should at minimum be closeable, not just "hoping" for a close. If we can find an alternative to using contexts that outlive their function call, I think that'd be good too.

---

I managed to reproduce the leak by issuing the following cURL command (the agent is v2.2.1 which is more efficient at triggering the ballooning, due to old metadata implementation):

```bash
curl \
  -H 'Coder-Session-Token: ...' \
  -H 'Accept: text/event-stream' \
  --limit-rate 1 \
  'http://my-coder:7080/api/v2/workspaceagents/025226f8-a637-4ea4-8fea-620ddbf81272/watch-metadata'
```

And then going AFK so my computer went a sleep, when I came back and woke my computer, I saw how Coder memory usage started ballooning and was able to stop it in its tracks by pressing Ctrl+C on the cURL command. Not sure whether limit-rate helped in reproduction, or if it was mainly due to what happens to the connection when the other client sleeps.

**Comment by mafredri** [comment]
@spikecurtis I added a test in https://github.com/coder/coder/pull/10685/commits/ab3cea2500ee2520609b8d323f1cc2120d9b37a2 that reproduces the leak. Using the DB error exit path is not the same mechanism that triggers it in the wild, but I didn't manage to reproduce it in any other way.

File: testutil/go.go [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+		cancel()
+		<-done
+	})
+	go func() {
+		fn(ctx)
+		close(doneC)
+	}()
+
+	return doneC, cancel
+}
```
Comment (johnstcn) [inline testutil/go.go:45]: Would it not make more sense to allow the caller to pass in the context here?
Also, seems unused at present?

File: coderd/workspaceagents_test.go [hunk 5]
```diff
@@ -1107,6 +1110,162 @@ func TestWorkspaceAgent_Metadata(t *testing.T) {
...
+
+func (s *testWAMErrorStore) GetWorkspaceAgentMetadata(ctx context.Context, arg database.GetWorkspaceAgentMetadataParams) ([]database.WorkspaceAgentMetadatum, error) {
+	err := s.err.Load()
+	if err != nil {
+		return nil, *err
+	}
+	return s.Store.GetWorkspaceAgentMetadata(ctx, arg)
+}
+
+func TestWorkspaceAgent_Metadata_CatchMemoryLeak(t *testing.T) {
```
Comment (johnstcn) [inline coderd/workspaceagents_test.go:1126]: Should this instead be a benchmark?

File: coderd/workspaceagents.go [hunk 6]
```diff
@@ -1908,15 +1900,45 @@ func (api *API) watchWorkspaceAgentMetadata(rw http.ResponseWriter, r *http.Requ
...
-	metadataMap := make(map[string]database.WorkspaceAgentMetadatum)
-	for _, datum := range md {
+	log.Debug(ctx, "got initial metadata", "num", len(initialMD))
+
+	metadataMap := make(map[string]database.WorkspaceAgentMetadatum, len(initialMD))
+	for _, datum := range initialMD {
 		metadataMap[datum.Key] = datum
 	}
+	//nolint:ineffassign // Release memory.
+	initialMD = nil
```
Comment (johnstcn) [inline coderd/workspaceagents.go:1910]: My understanding here is that we only need the initial slice of metadata from the DB once in order to massage it into a map.
Without this, I assume the initial slice would stay around for the duration of the SSE request?

File: coderd/workspaceagents.go [hunk 7]
```diff
@@ -1835,22 +1835,28 @@ func (api *API) workspaceAgentUpdateMetadata(ctx context.Context, workspaceAgent
...
+
+	workspaceAgent := httpmw.WorkspaceAgentParam(r)
+	log := api.Logger.Named("workspace_metadata_watcher").With(
+		slog.F("workspace_agent_id", workspaceAgent.ID),
 	)
 
 	// Send metadata on updates, we must ensure subscription before sending
 	// initial metadata to guarantee that events in-between are not missed.
 	update := make(chan workspaceAgentMetadataChannelPayload, 1)
 	cancelSub, err := api.Pubsub.Subscribe(watchWorkspaceAgentMetadataChannel(workspaceAgent.ID), func(_ context.Context, byt []byte) {
```
Comment (johnstcn) [inline coderd/workspaceagents.go:1851]: Is the `func(context.Context, []byte)` we pass to `api.Pubsub.Suscribe` getting ripe for extraction?

File: testutil/go.go (hunk 4 above)
Comment (mafredri) [reply testutil/go.go:45]: I'll remove it, I simply moved the two methods as-is, they have existed for a long time (as `tGoContext` and `tGo`).

File: coderd/workspaceagents_test.go (hunk 5 above)
Comment (mafredri) [reply coderd/workspaceagents_test.go:1126]: I wanted to keep this as a test to verify the endpoint behaves as it should. A benchmark wouldn't help in catching a memory leak either since it requires being run manually and checking output (assuming it doesn't get OOM killed).

File: coderd/workspaceagents.go (hunk 7 above)
Comment (mafredri) [reply coderd/workspaceagents.go:1851]: Could you clarify? I'm not sure I understand the question.

Comment (johnstcn) [reply coderd/workspaceagents.go:1851]: I mean, should we refactor the second argument of this function into its own function as opposed to leaving it anonymous? Not in this PR of course.

Comment (mafredri) [reply coderd/workspaceagents.go:1851]: Ah, I don't think that's necessary, it's very short and the only logic in it is the slice merger. We could break that out into its own function, though.

**Review by johnstcn — APPROVED** [review]

**Review by mtojek — APPROVED** [review]
