### PR TITLE
fix: Improve friendly validation error messages

### LINKED ISSUE #1673: CLI: getting "Validation failed name: username" error in cli in case workspace or template name does not follow allowed pattern
## OS Information

- OS: Windows 10
- `coder --version`:
Coder v0.5.10+ba818b3 Wed May 18 00:07:20 UTC 2022
https://github.com/coder/coder/commit/ba818b3a10aa364073c90a217631dd1d17c32393

## Steps to Reproduce

1. Init any template
2. Run "coder template create **wrong-name_** -d "[path to template]"
3. Set service account key
4. Confirm create? (yes/no) yes

## Expected

Any error message that template name has a wrong format is displayed

## Actual

status code 400: Validation failed
        name: username

The same  for a new worskpace created with CLI.

## What is your suggestion?

Currently if Workspace Name or Template Name does not match names rules: "Name must start with a-Z or 0-9 and can contain a-Z, 0-9 or -."
in CLI the resulting error is:

status code 400: Validation failed
        **name: username**

That is confusing since this is not username that causes the error, but template name or workspace name in case workspace was created. 

## Screenshot
Template error

image

Workspace error

image

### PR DESCRIPTION
**Pull request by mafredri**
This PR adds the validation errors to the friendly error message.

I found it confusing when working on #3000 and all I got was `Validation failed.`.

Before:

```
❯ go run ./cmd/coder rename testy user/tester
Validation failed.
Run 'coder rename --help' for usage.
```

After:

```
❯ go run ./cmd/coder rename testy user/tester
Validation failed.
- name: Validation failed for tag "workspace_name" with value: "user/tester"
Run 'coder rename --help' for usage.
```

The original `Validation failed for tag "username"` was also confusing, so new validators were registered.

- fix: Add validations to `(*codersdk.Error).Friendly`
- fix: Add named validators for template and workspace name

---

Fixes #1673

### CODE REVIEW

File: coderd/httpapi/httpapi.go [hunk 1]
```diff
@@ -31,16 +29,19 @@ func init() {
...
 		return name
 	})
-	err := validate.RegisterValidation("username", func(fl validator.FieldLevel) bool {
+	nameValidator := func(fl validator.FieldLevel) bool {
 		f := fl.Field().Interface()
 		str, ok := f.(string)
 		if !ok {
 			return false
 		}
 		return UsernameValid(str)
```
Comment (johnstcn) [inline coderd/httpapi/httpapi.go:38]: The semantics for username validation may be different to those of workspace and template names.
We should register different validators for each of these.

Comment (mafredri) [reply coderd/httpapi/httpapi.go:38]: Previously these fields used the `username` validation tag, so behavior hasn't changed and I wasn't looking to change the behavior in this PR. If the validation is incorrect then we should definitely fix that.

**Review by johnstcn — APPROVED** [review]

**Comment by AbhineetJain** [comment]
This PR seems related to #1943 and should be impacting the error messages that we show on frontend, so a verification of the frontend behavior and a review from @presleyp should be helpful.

**Comment by mafredri** [comment]
@AbhineetJain thanks for keeping an eye out. I don't think this affects the frontend though, except for the validation error message when creating a workspace, if the workspace name is invalid. Then the error message will say that the validator that failed is `workspace_name` instead of `username`.

**Review by bpmct — COMMENTED** [review]
Are we able to surface the regex and/or what characters violated it? From looking at the code, it is clear you cannot use spaces and/or underscores but this may not be immediately clear to the user.

File: coderd/httpapi/httpapi.go (hunk 1 above)
Comment (bpmct) [reply coderd/httpapi/httpapi.go:38]: Related #3321

**Comment by mafredri** [comment]
> Are we able to surface the regex and/or what characters violated it? From looking at the code, it is clear you cannot use spaces and/or underscores but this may not be immediately clear to the user.

AFAICT, not very straight-forward with the [validator](https://github.com/go-playground/validator) library we use. I looked a bit through the API and validators are mostly booleans, so we'd need to utilize multiple validators for one field to be able to narrow down the error case? Perhaps we should look into replacing the library, or just implement custom types with their own JSON marshal/unmarshal where we can control the behavior.

**Comment by bpmct** [comment]
> AFAICT, not very straight-forward with the [validator](https://github.com/go-playground/validator) library we use. I looked a bit through the API and validators are mostly booleans, so we'd need to utilize multiple validators for one field to be able to narrow down the error case? Perhaps we should look into replacing the library, or just implement custom types with their own JSON marshal/unmarshal where we can control the behavior.

Oh, that makes sense. Perhaps something we can look into later if it comes up again.

**Comment by Emyrk** [comment]
> > Are we able to surface the regex and/or what characters violated it? From looking at the code, it is clear you cannot use spaces and/or underscores but this may not be immediately clear to the user.
> 
> AFAICT, not very straight-forward with the [validator](https://github.com/go-playground/validator) library we use. I looked a bit through the API and validators are mostly booleans, so we'd need to utilize multiple validators for one field to be able to narrow down the error case? Perhaps we should look into replacing the library, or just implement custom types with their own JSON marshal/unmarshal where we can control the behavior.

I noticed this too with the validator lib before. There is something you can do with their "translator" api,but it seems kinda jank. I wish the validator custom functions could return custom errors.

**Comment by mafredri** [comment]
> I noticed this too with the validator lib before. There is something you can do with their "translator" api,but it seems kinda jank. I wish the validator custom functions could return custom errors.

Agreed, using the translations API seems very jank. I found one project utilizing it, but that's a lot of code for working around the fact that the validator API has shortcomings: https://github.com/Aptomi/k8s-app-engine/blob/11b495fc520680093a990fee0eaaf598507596b5/pkg/lang/validation.go

There are a few other libs that seem to have a better API:
- https://github.com/guiferpa/gody
- https://github.com/dealancer/validate
- (More at https://awesome-go.com/validation/)

But I have no experience with these.
