### PR TITLE
fix: Trigger workspace event after agent timeout seconds

### LINKED ISSUE #5116: I have to refresh to see that agent is disconnected
https://user-images.githubusercontent.com/22407953/202440336-15a864f7-22eb-439b-bdfd-c40bc10595ab.mov

This is on a template where the agent intentionally never connects but has a timeout of 10 seconds

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #5116

### CODE REVIEW

File: coderd/provisionerdserver/provisionerdserver.go [hunk 1]
```diff
@@ -631,14 +633,59 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
 				}
 			}
 
+			// On start, we want to ensure that workspace agents timeout statuses
+			// are propagated. This method is simple and does not protect against
+			// notifying in edge cases like when a workspace is stopped soon
+			// after being started.
+			//
+			// Agent timeouts could be minutes apart, resulting in an unresponsive
+			// experience, so we'll notify after every unique timeout seconds.
```
Comment (BrunoQuaresma) [inline coderd/provisionerdserver/provisionerdserver.go:656]: What "eveery unique timeout seconds" means?

Comment (mafredri) [reply coderd/provisionerdserver/provisionerdserver.go:656]: Let's say there are two agents with 120s timeout, then there will only be one unique timeout, 120s and we'll notify once.

Then in another scenario, we add a third agent with 240s timeout, there are now two unique timeouts `[120s, 240s]` and we will notify once at 120s, and another time at 240s.

Comment (BrunoQuaresma) [reply coderd/provisionerdserver/provisionerdserver.go:656]: Ahh I see. Thanks for the explanation!

**Review by BrunoQuaresma — APPROVED** [review]
The code makes sense to me. I'm not a BE expert but since you added tests it is safe to merge IMO 👍

File: coderd/provisionerdserver/provisionerdserver.go [hunk 2]
```diff
@@ -631,14 +633,59 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
 			if err != nil {
 				return xerrors.Errorf("update workspace build: %w", err)
 			}
+
+			agentTimeouts := make(map[time.Duration]bool) // A set of agent timeouts.
 			// This could be a bulk insert to improve performance.
 			for _, protoResource := range jobType.WorkspaceBuild.Resources {
+				for _, protoAgent := range protoResource.Agents {
+					dur := time.Duration(protoAgent.GetConnectionTimeoutSeconds()) * time.Second
```
Comment (johnstcn) [inline coderd/provisionerdserver/provisionerdserver.go:641]: review: should we truncate these to `time.Second`?

File: coderd/provisionerdserver/provisionerdserver.go [hunk 3]
```diff
@@ -631,14 +633,59 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
+				}
+				go func() {
+					for _, wait := range updates {
+						// Wait for the next potential timeout to occur. Note that we
+						// can't listen on the context here because we will hang around
+						// after this function has returned. The server also doesn't
+						// have a shutdown signal we can listen to.
+						<-wait
+						err := server.Pubsub.Publish(codersdk.WorkspaceNotifyChannel(workspaceBuild.WorkspaceID), []byte{})
+						if err != nil {
```
Comment (johnstcn) [inline coderd/provisionerdserver/provisionerdserver.go:679]: how about combining the assignment and conditional to keep the scope of `err` small?

File: coderd/provisionerdserver/provisionerdserver.go (hunk 2 above)
Comment (mafredri) [reply coderd/provisionerdserver/provisionerdserver.go:641]: I don't think that's necessary since the input is in seconds?

File: coderd/workspaces_test.go [hunk 4]
```diff
@@ -1372,58 +1373,64 @@ func TestWorkspaceWatcher(t *testing.T) {
 
 	wc, err := client.WatchWorkspace(ctx, workspace.ID)
 	require.NoError(t, err)
-	wait := func() {
+
+	// Wait events are easier to debug with timestamped logs.
+	logger := slogtest.Make(t, nil).Named(t.Name()).Leveled(slog.LevelDebug)
+	wait := func(event string) {
```
Comment (johnstcn) [inline coderd/workspaces_test.go:1379]: nice!

File: coderd/provisionerdserver/provisionerdserver.go [hunk 5]
```diff
@@ -631,14 +633,59 @@ func (server *Server) CompleteJob(ctx context.Context, completed *proto.Complete
...
+
+				var updates []<-chan time.Time
+				for _, d := range timeouts {
+					server.Logger.Debug(ctx, "triggering workspace notification after agent timeout",
+						slog.F("workspace_build_id", workspaceBuild.ID),
+						slog.F("timeout", d),
+					)
+					// Agents are inserted with `database.Now()`, this triggers a
+					// workspace event approximately after created + timeout seconds.
+					updates = append(updates, time.After(d))
```
[the remark this answers is not in the document]
Comment (mafredri) [reply coderd/provisionerdserver/provisionerdserver.go:669]: This is non-cancelable, so the "leakage" is intentional as per the comment above `<-wait`.

**Review by johnstcn — APPROVED** [review]
