### PR TITLE
fix: audit log workspace build URL should form with the correct workspace owner

### LINKED ISSUE #5673: Audit Log: Build URL is incorrect when admin starts workspace for which they are not an owner
Kapture 2023-01-11 at 12 27 22

Steps to repo:

1. As an admin, create a workspace on behalf of another user (so that the user is the owner of the workspace)
2. Go to the Audit Log and find the line item that says "admin started build {#n} for workspace {usersWorkspaceName}"
3. Click on the link and be redirected to a page that never loads
4. Note the URL specifies the incorrect owner, e.g. `/@admin/{usersWorkspaceName}/builds/{n}`

Expected outcome:
Url should be `/@{userName}/{usersWorkspaceName}/builds/{n}`

### PR DESCRIPTION
**Pull request by Kira-Pilot**
Resolves #5673 
Build URL was incorrect when admin started a workspace for which they were not an owner.

Before:
Kapture 2023-01-11 at 12 27 22

After: 
Kapture 2023-01-11 at 12 38 29

### CODE REVIEW

File: coderd/audit.go [hunk 1]
```diff
@@ -352,18 +350,34 @@ func auditLogResourceLink(alog database.GetAuditLogsOffsetRow, additionalFields
...
+			return ""
+		}
+		workspace, getWorkspaceErr := api.Database.GetWorkspaceByID(ctx, workspaceBuild.WorkspaceID)
+		if getWorkspaceErr != nil {
+			return ""
+		}
+		workspaceOwner, getWorkspaceOwnerErr := api.Database.GetUserByID(ctx, workspace.OwnerID)
+		if getWorkspaceOwnerErr != nil {
+			return ""
+		}
```
Comment (Kira-Pilot) [inline coderd/audit.go:378]: I don't love it, but idk how else to get workspace owner. I don't want to pass everything through `additionalFields` because that will not fix old records.

**Review by kylecarbs — APPROVED** [review]
Looks good to me! I might change the hyperlink to be on the build # instead.

Having it on the workspace name makes me think it'll link me to the workspace.

**Comment by Kira-Pilot** [comment]
@kylecarbs I can look at that in a follow-up PR!

**Comment by kylecarbs** [comment]
@Kira-Pilot awesome! And thanks for putting up with my slow review!
