### PR TITLE
fix pubsub/poll race on provisioner job logs

### LINKED ISSUE #2603: streaming job logs race condition means not all logs are returned / TestDelete flake
Relates to #2347 

HTTP endpoint `/api/v2/workspacebuilds/<build>/logs` will sometimes end without returning all logs.

This causes our `TestDelete` cli tests to be flaky because they wait for the final "Cleaning Up" log which sometimes never comes,

e.g.

```
    ptytest.go:92: match exceeded deadline: wanted "Cleaning Up"; got "\x1b[1A\r✔ Queued [-18ms]\r\n⧗  \x1b[;mRunning\x1b[0m \r\n⧗  \x1b[;mRunning\x1b[0m \r\n\x1b[1A\r✔ Running [345ms]\r\n⧗  \x1b[;mSetting up\x1b[0m \r\n\x1b[1A\r✔ Setting up [73ms]\r\n⧗  \x1b[;mDestroying workspace\x1b[0m \r\n\x1b[1A\r✔ Destroying workspace [204ms]\r\n"
    ptytest.go:97: 
        	Error Trace:	ptytest.go:97
        	            				delete_test.go:75
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestDelete/DifferentUser
    t.go:81: 2022-06-23 04:01:14.391 [DEBUG]	(provisionerd)	<github.com/coder/coder/provisionerd/provisionerd.go:1078>	(*Server).closeWithError	closing server with error	{"error": null}
    --- FAIL: TestDelete/DifferentUser (18.15s)
```

The fundamental problem is that this endpoint receives logs from the PubSub stream for the job, and asynchronously checks for the job being marked as complete in the database every 250ms.  When the trigger to check for job completion fires, there is no guarantee that all logs have been received or processed, and so we can miss some.

Exacerbating the problem is the fact that the provisionerd calls `CompleteJob` _before_ the final `UpdateJob` that logs successful cleanup, due to the later being in a `defer`.  But, even if these calls were made in the correct order, there is still a race between receiving and processing the logs and detecting that the job is done.

Some fix options:

1. Introduce an "end of record" log that gets inserted into the database and pubsub for each job when it is completed, canceled or failed.  This allows us to avoid polling the database for job completion, and so we don't have the associated race between the poll and the log subscription.
2. Keep track of the most recently processed log ID, and when we detect the job is complete, query the database for any remaining logs after the one we have processed.

Note that both above options depend on fixing the problem where provisionerd sends logs after `CompleteJob`.

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #2603

### CODE REVIEW

File: coderd/provisionerjobs.go [hunk 1]
```diff
@@ -38,6 +38,37 @@ func (api *API) provisionerJobLogs(rw http.ResponseWriter, r *http.Request, job
...
+		// completes between the prior query and the start of following the pubsub.  A more substantial refactor could
+		// avoid this, but not worth it for one fewer query at this point.
+		job, err = api.Database.GetProvisionerJobByID(r.Context(), job.ID)
+		if err != nil {
+			httpapi.Write(rw, http.StatusInternalServerError, httpapi.Response{
+				Message: "Internal error querying job.",
+				Detail:  err.Error(),
+			})
+			return
+		}
```
Comment (Emyrk) [inline coderd/provisionerjobs.go:69]: Understandable :'(

File: coderd/provisionerjobs.go [hunk 2]
```diff
@@ -343,3 +338,46 @@ func convertProvisionerJob(provisionerJob database.ProvisionerJob) codersdk.Prov
...
 	return fmt.Sprintf("provisioner-log-logs:%s", jobID)
 }
+
+// provisionerJobLogsMessage is the message type published on the provisionerJobLogsChannel() channel
+type provisionerJobLogsMessage struct {
+	EndOfLogs bool                         `json:"end_of_logs,omitempty"`
+	Logs      []database.ProvisionerJobLog `json:"logs,omitempty"`
+}
+
+func (api *API) followLogs(jobID uuid.UUID) (chan database.ProvisionerJobLog, func(), error) {
```
Comment (Emyrk) [inline coderd/provisionerjobs.go:348]: Might as well limit what the caller can do with the channel
```suggestion
func (api *API) followLogs(jobID uuid.UUID) (<-chan database.ProvisionerJobLog, func(), error) {
```

File: coderd/provisionerjobs.go [hunk 3]
```diff
@@ -343,3 +338,46 @@ func convertProvisionerJob(provisionerJob database.ProvisionerJob) codersdk.Prov
...
+	bufferedLogs := make(chan database.ProvisionerJobLog, 128)
+	closeSubscribe, err := api.Pubsub.Subscribe(provisionerJobLogsChannel(jobID),
+		func(ctx context.Context, message []byte) {
+			jlMsg := provisionerJobLogsMessage{}
+			err := json.Unmarshal(message, &jlMsg)
+			if err != nil {
+				api.Logger.Warn(ctx,
+					fmt.Sprintf("invalid provisioner job log on channel %q: %s",
+						provisionerJobLogsChannel(jobID),
+						err.Error()))
```
Comment (Emyrk) [inline coderd/provisionerjobs.go:358]: Is there a reason we aren't using the structured fields?
We probably should have a metter method to ensure things like `job_id` are consistent everywhere we use it.

```suggestion
				api.Logger.Warn(ctx, "invalid provisioner job log on channel",
					slog.Error(err),
					slog.F("job_id", jobID),
				)
```

File: coderd/provisionerjobs.go [hunk 4]
```diff
@@ -343,3 +338,46 @@ func convertProvisionerJob(provisionerJob database.ProvisionerJob) codersdk.Prov
...
+			for _, log := range jlMsg.Logs {
+				select {
+				case bufferedLogs <- log:
+					api.Logger.Debug(ctx, "subscribe buffered log",
+						slog.F("job_id", jobID),
+						slog.F("stage", log.Stage))
+				default:
+					// If this overflows users could miss logs streaming. This can happen
+					// if a database request takes a long amount of time, and we get a lot of logs.
+					api.Logger.Warn(ctx, "provisioner job log overflowing channel")
```
Comment (Emyrk) [inline coderd/provisionerjobs.go:371]: I don't totally get this comment. Doesn't the messages from from the database? So doesn't this overflow if the caller (websocket) is slower than the logs coming in over the database? 


Just looking for clarity of the comment, I know we should not block the database side of this. I wonder if we should record the number of skipped logs and try to insert something like "... X logs lines skipped ...".

File: go.mod [hunk 5]
```diff
@@ -138,7 +138,10 @@ require (
 	tailscale.com v1.26.1
 )
 
-require github.com/googleapis/enterprise-certificate-proxy v0.1.0 // indirect
+require (
+	github.com/googleapis/enterprise-certificate-proxy v0.1.0 // indirect
+	github.com/stretchr/objx v0.4.0 // indirect
+)
```
Comment (Emyrk) [inline go.mod:144]: `go mod tidy` removes the `objx` dep

File: coderd/provisionerjobs.go [hunk 6]
```diff
@@ -343,3 +338,46 @@ func convertProvisionerJob(provisionerJob database.ProvisionerJob) codersdk.Prov
...
 }
+
+// provisionerJobLogsMessage is the message type published on the provisionerJobLogsChannel() channel
+type provisionerJobLogsMessage struct {
+	EndOfLogs bool                         `json:"end_of_logs,omitempty"`
+	Logs      []database.ProvisionerJobLog `json:"logs,omitempty"`
+}
+
+func (api *API) followLogs(jobID uuid.UUID) (chan database.ProvisionerJobLog, func(), error) {
+	bufferedLogs := make(chan database.ProvisionerJobLog, 128)
```
Comment (Emyrk) [inline coderd/provisionerjobs.go:349]: One little thing to help logger fields maybe.

```golang
logger := api.Logger.With(slog.F("job_id", jobID))
```

Then just `logger.Warn()` and `logger.Debug()` later. The field is always present.

**Review by Emyrk — APPROVED** [review]
I like this EOF type thing :+1:

File: coderd/provisionerjobs.go (hunk 4 above)
Comment (dwahler) [reply coderd/provisionerjobs.go:371]: Yeah, the channel could overflow if the client is slow to read from the websocket, but it could also overflow if more than 128 messages are added between the time we set up the pubsub subscription and the time we start reading from the channel, which doesn't happen until `GetProvisionerLogsByIDBetween` completes.

**Review by dwahler — APPROVED** [review]
Nice fix!

File: coderd/provisionerjobs.go (hunk 3 above)
Comment (spikecurtis) [reply coderd/provisionerjobs.go:358]: That's a good point.  This code was just moved, so I didn't really look at it very critically.  Happy to fix up.

File: coderd/provisionerjobs.go (hunk 1 above)
Comment (dwahler) [reply coderd/provisionerjobs.go:69]: I guess technically we could do this query asynchronously and check its result later, since we already know we're going to query logs from the DB regardless of whether the job is already complete. But it's such a lightweight query that it doesn't seem worth the extra complexity.

File: coderd/provisionerjobs.go (hunk 4 above)
Comment (spikecurtis) [reply coderd/provisionerjobs.go:371]: Yep, yep.

The problem with trying to insert a  "... X logs lines skipped ..." message is that the buffer is already full, so we don't have anywhere to put it.  We'd have to roll our own ring buffer or something messy to be able to coalesce logs already buffered.  I don't want to do that in this PR --- this is just a refactor matching existing behavior.

File: go.mod (hunk 5 above)
Comment (spikecurtis) [reply go.mod:144]: 🤷‍♂️

File: coderd/provisionerjobs.go (hunk 1 above)
Comment (spikecurtis) [reply coderd/provisionerjobs.go:69]: >  But it's such a lightweight query that it doesn't seem worth the extra complexity.
Agree
