### PR TITLE
fix(site): preserve file path when building template version

### LINKED ISSUE #14130: [Bug] When hit build in the template editor UI it will redirect to another file
When opening a diff file than main.tf and hitting the build button, the main.tf file will be opened when the editor should keep the current file.

### PR DESCRIPTION
**Pull request by breadface**
Fixes issue where clicking Build in the template editor would always redirect to main.tf instead of keeping the currently open file.

Closes #14130

### CODE REVIEW

**Comment by breadface** [comment]
I have read the CLA Document and I hereby sign the CLA

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx [hunk 1]
```diff
@@ -104,10 +104,14 @@ const TemplateVersionEditorPage: FC = () => {
...
+			version.name
+		}/edit`;
+		// Preserve the current path query parameter
+		const newSearchParams = new URLSearchParams(searchParams);
+		const queryString = newSearchParams.toString();
 		return navigate(
-			`${getLink(linkToTemplate(organizationName, templateName))}/versions/${
-				version.name
-			}/edit`,
+			queryString ? `${url}?${queryString}` : url,
```
Comment (BrunoQuaresma) [inline site/src/pages/TemplateVersionEditorPage/TemplateVersionEditorPage.tsx]: - `searchParams` is already a `URLSearchParams` object so you don't need to instantiate that
- There is no issue if the `?` gets added to the url without any query string
- I think you could simplify the code to be:
  ```ts
  const navigateToVersion = (version: TemplateVersion) => {
	const url = `${getLink(linkToTemplate(organizationName, templateName))}/versions/${
		version.name
	}/edit?${searchParams.toString()}`;
	return navigate(url, { replace: true });
  };
  ```
- It would be nice to have tests for this fix 🙏

**Review by BrunoQuaresma — APPROVED** [review]
Thank you!
