### PR TITLE
fix(site): fix infinity loading when template has no previous version

### LINKED ISSUE #12053: template 'source code' tab never shows source code if only one version exists
The template source code tab shows a diff between the previous and current version of the template source code.  If there aren't two versions to compare, it never shows the code

image

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Close https://github.com/coder/coder/issues/12053

### CODE REVIEW

File: site/src/api/queries/templates.ts [hunk 1]
```diff
@@ -266,12 +266,15 @@ export const previousTemplateVersion = (
...
-      API.getPreviousTemplateVersionByName(
+    queryFn: async () => {
+      const result = await API.getPreviousTemplateVersionByName(
         organizationId,
         templateName,
         versionName,
-      ),
+      );
+
+      return result ?? null;
```
Comment (BrunoQuaresma) [inline site/src/api/queries/templates.ts:276]: I need to do this because react-query does not allow queries to return `undefined` 😟

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot I'm merging it now but let me know if you have any considerations.
