### PR TITLE
fix(agent/agentcontainers): fix `TestDevcontainerDiscovery/AutoStart` flake

### LINKED ISSUE #864: [flake] TestDevcontainerDiscovery/AutoStart/MultipleEnabled
```
=== FAIL: agent/agentcontainers TestDevcontainerDiscovery/AutoStart/MultipleEnabled (0.04s)
    t.go:106: 2025-08-04 19:32:45.999 [debu]  updater loop started
    t.go:106: 2025-08-04 19:32:45.999 [debu]  cleaning up subagents
    t.go:106: 2025-08-04 19:32:45.999 [debu]  cleanup subagents complete
    t.go:106: 2025-08-04 19:32:45.999 [debu]  performing initial containers update
    t.go:106: 2025-08-04 19:32:45.999 [debu]  containers updated successfully  container_count=0  warning_count=0  devcontainer_count=0
    t.go:106: 2025-08-04 19:32:45.999 [debu]  initial containers update complete
    mock.go:202: Mock Clock - TickerFunc(<ctx>, 10s, <fn>, [agentcontainers updaterLoop]) call, matched 0 traps
    t.go:106: 2025-08-04 19:32:45.999 [debu]  project discovery started
    t.go:106: 2025-08-04 19:32:45.999 [debu]  watcher loop started
    t.go:106: 2025-08-04 19:32:46.022 [debu]  project-discovery: discovered dev container project  project_path=/home/coder  workspace_folder=/home/coder
    t.go:106: 2025-08-04 19:32:46.022 [debu]  project-discovery: adding dev container project  project_path=/home/coder  workspace_folder=/home/coder
    t.go:106: 2025-08-04 19:32:46.022 [debu]  project-discovery: discovered dev container project  project_path=/home/coder  workspace_folder=/home/coder/project
    t.go:106: 2025-08-04 19:32:46.022 [debu]  project-discovery: adding dev container project  project_path=/home/coder  workspace_folder=/home/coder/project
    t.go:106: 2025-08-04 19:32:46.023 [debu]  containers updated successfully  container_count=0  warning_count=0  devcontainer_count=2
    t.go:106: 2025-08-04 19:32:46.038 [debu]  project discovery finished
    t.go:106: 2025-08-04 19:32:46.038 [debu]  closing API
    t.go:106: 2025-08-04 19:32:46.038 [debu]  api context canceled
    t.go:106: 2025-08-04 19:32:46.038 [debu]  watcher loop stopped
    mock.go:202: Mock Clock - TickerFunc.Wait([agentcontainers updaterLoop]) call, matched 0 traps
    t.go:106: 2025-08-04 19:32:46.038 [debu]  updater loop stopped
    t.go:106: 2025-08-04 19:32:46.038 [debu]  closed API
    controller.go:97: missing call(s) to *acmock.MockDevcontainerCLI.Up(is anything, is equal to /home/coder (string), is equal to /home/coder/.devcontainer/devcontainer.json (string), is anything) /Users/runner/work/coder/coder/agent/agentcontainers/api_test.go:3736
    controller.go:97: missing call(s) to *acmock.MockDevcontainerCLI.Up(is anything, is equal to /home/coder/project (string), is equal to /home/coder/project/.devcontainer.json (string), is anything) /Users/runner/work/coder/coder/agent/agentcontainers/api_test.go:3760
    controller.go:97: aborting test due to missing call(s)
    mock.go:477: Mock Clock - test cleanup; will no longer log clock events
        --- FAIL: TestDevcontainerDiscovery/AutoStart/MultipleEnabled (0.04s)
```

seen here: https://github.com/coder/coder/actions/runs/16732257205/job/47363223942

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fixes https://github.com/coder/internal/issues/864

### CODE REVIEW

**Comment by DanielleMaywood** [comment]
@coderabbitai review

**Review by mafredri — APPROVED** [review]
LGTM 👍🏻

File: agent/agentcontainers/api_test.go [hunk 1]
```diff
@@ -3775,43 +3705,73 @@ func TestDevcontainerDiscovery(t *testing.T) {
...
+
+				// And: We expect `up` to have been called the expected amount of times.
+				assert.Len(t, upCalledFor, tt.expectUpCalledCount)
+
+				// And: `up` was called on the correct containers
+				for configPath, config := range tt.configMap {
+					autoStart := config.Configuration.Customizations.Coder.AutoStart
+					wasUpCalled := upCalledFor[configPath]
+
+					require.Equal(t, autoStart, wasUpCalled)
```
Comment (johnstcn) [inline agent/agentcontainers/api_test.go:3773]: Suggest `assert` here instead.

File: agent/agentcontainers/api_test.go [hunk 2]
```diff
@@ -3775,43 +3705,73 @@ func TestDevcontainerDiscovery(t *testing.T) {
...
+				// Then: We expect to find the expected devcontainers
+				assert.Len(t, got.Devcontainers, tt.expectDevcontainerCount)
+
+				// And: We expect `up` to have been called the expected amount of times.
+				assert.Len(t, upCalledFor, tt.expectUpCalledCount)
+
+				// And: `up` was called on the correct containers
+				for configPath, config := range tt.configMap {
+					autoStart := config.Configuration.Customizations.Coder.AutoStart
+					wasUpCalled := upCalledFor[configPath]
```
Comment (johnstcn) [inline agent/agentcontainers/api_test.go:3771]: Will this handle the case where we call `up` for something not in `config.Configuration.Customizations.Coder.AutoStart`?

**Review by johnstcn — COMMENTED** [review]
Some (belated) comments below, but nothing blocking.
