### PR TITLE
fix: introduce ResourceAiSeat for fine-grained AI seat RBAC

### LINKED ISSUE #1444: AI seat state upsert fails with RBAC forbidden error on per-user first connection to AI Bridge
## Description:

When a user connects to AI Bridge for the first time, the following warning is logged:
```
2026-04-01 11:56:03.959 [info]  api: 2026-04-01 11:56:03.959 [warn]  coderd.aiseats: upsert AI seat state  error="unauthorized: rbac: forbidden"  user_id=45f9b709-4f51-4da5-a0b3-5e4d29fc26af  event_type=aibridge
```

This only occurs on the first connection per user, subsequent connections from the same user do not produce the warning. AI Bridge functionality is not affected (tested with Claude and Copilot), but the user may not be recorded as consuming an AI seat.

Observed in a local development setup using the internal premium license. 

Related to internal Slack thread: https://codercom.slack.com/archives/C0AEHQGLW22/p1775045737042489

### PR DESCRIPTION
**Pull request by mtojek**
## Problem

When a user connects to AI Bridge for the first time, `UpsertAISeatState` fails with `unauthorized: rbac: forbidden` because the `subjectAibridged` RBAC subject lacks the required permission. The deprecated `ResourceSystem` catch-all was used for the authorization check, so any fix using `ResourceSystem` would grant overly broad access to 22 other unrelated operations.

Additionally, the two read queries (`GetActiveAISeatCount`, `GetUserAISeatStates`) were gated on `ResourceLicense` and `ResourceUser` respectively, which is semantically incorrect.

## Fix

Introduce a dedicated `ResourceAiSeat` RBAC resource with `ActionCreate` (for upserts) and `ActionRead` (for queries), following the same pattern as `ResourceBoundaryUsage`.

All three AI seat DB operations now use `ResourceAiSeat`:

| Query | Was | Now |
|-------|-----|-----|
| `UpsertAISeatState` | `ResourceSystem, ActionCreate` | `ResourceAiSeat, ActionCreate` |
| `GetActiveAISeatCount` | `ResourceLicense, ActionRead` | `ResourceAiSeat, ActionRead` |
| `GetUserAISeatStates` | `ResourceUser, ActionRead` | `ResourceAiSeat, ActionRead` |

Subjects updated:
- `subjectAibridged`: `ResourceAiSeat.ActionCreate`
- `subjectProvisionerd`: `ResourceAiSeat.ActionCreate`
- `subjectUsagePublisher`: `ResourceAiSeat.ActionRead`
- `AsSystemRestricted` already covers read via `ResourceWildcard`

Existing tests in `tracker_test.go` and `cron_test.go` now use real dbauthz-wrapped databases with `rbac.NewStrictAuthorizer`, exercising production RBAC paths (AsAIBridged, AsProvisionerd, AsUsagePublisher) instead of bypassing authorization.

Fixes coder/internal#1444

> 🤖 Generated with [Coder Agents](https://coder.com/agents)

## Manual testing

0. Prepare local deployment:
* Install Premium license
* `CODER_AIBRIDGE_ENABLED=true CODER_AIBRIDGE_ANTHROPIC_KEY=sk-ant... ./scripts/develop.sh`
1. Log in as member@coder.com
2. Start AI task -> workspace is created -> Seats: 1/50
3. Create a session token for member@.
4. Run:
```
curl -s -X POST http://localhost:3000/api/v2/aibridge/anthropic/v1/messages \
  -H "x-api-key: $CODER_SESSION_TOKEN" \
  -H "Content-Type: application/json" \
  -H "anthropic-version: 2023-06-01" \
  -d '{
    "model": "claude-sonnet-4-20250514",
    "max_tokens": 32,
    "messages": [{"role": "user", "content": "say hi"}]
  }'
```
-> Seats still at: 1/50
5. Log in as admin@coder.com
6. Create a session token for admin@.
7. Run:
```
curl -s -X POST http://localhost:3000/api/v2/aibridge/anthropic/v1/messages \
  -H "x-api-key: $CODER_SESSION_TOKEN" \
  -H "Content-Type: application/json" \
  -H "anthropic-version: 2023-06-01" \
  -d '{
    "model": "claude-sonnet-4-20250514",
    "max_tokens": 32,
    "messages": [{"role": "user", "content": "say hi"}]
  }'
```
-> Seats: 2/50

### CODE REVIEW

File: enterprise/coderd/usage/cron_test.go [hunk 1]
```diff
@@ -77,22 +85,39 @@ func TestCron(t *testing.T) {
...
 	t.Parallel()
 
 	ctx := testutil.Context(t, testutil.WaitLong)
-	ctrl := gomock.NewController(t)
-	db := dbmock.NewMockStore(ctrl)
-
-	db.EXPECT().GetActiveAISeatCount(gomock.Any()).Return(int64(42), nil)
-
-	fn := usage.AISeatsHeartbeat(db)
+	rawDB, _ := dbtestutil.NewDB(t)
```
Comment (spikecurtis) [inline enterprise/coderd/usage/cron_test.go]: You can wrap dbauthz around the mocked database. We'd still get the auth checks, but won't have to pay the cost of creating a real PG database.

File: coderd/database/dbauthz/dbauthz.go [hunk 2]
```diff
@@ -226,6 +226,7 @@ var (
 					rbac.ResourceProvisionerJobs.Type: {policy.ActionRead, policy.ActionUpdate, policy.ActionCreate},
 					rbac.ResourceFile.Type:            {policy.ActionCreate, policy.ActionRead},
 					rbac.ResourceSystem.Type:          {policy.WildcardSymbol},
+					rbac.ResourceAiSeat.Type:          {policy.ActionCreate}, // Required for UpsertAISeatState via SeatTracker.
```
Comment (ssncferreira) [inline coderd/database/dbauthz/dbauthz.go:229]: Why does provisioner role need create on AI seat?

File: coderd/database/dbauthz/dbauthz_test.go [hunk 3]
```diff
@@ -1851,11 +1851,11 @@ func (s *MethodTestSuite) TestProvisionerJob() {
 func (s *MethodTestSuite) TestLicense() {
```
Comment (ssncferreira) [inline coderd/database/dbauthz/dbauthz_test.go]: nit: we should probably change this to be TestAISeat or something like that, right? 🤔

File: enterprise/aibridgedserver/aibridgedserver_test.go [hunk 4]
```diff
@@ -791,6 +797,46 @@ func TestRecordInterception(t *testing.T) {
 	)
 }
 
+// TestRecordInterceptionRBAC verifies that RecordInterception succeeds
+// through real RBAC (AsAIBridged) and records an AI seat via the real
+// SeatTracker, matching the production call path.
+func TestRecordInterceptionRBAC(t *testing.T) {
```
Comment (ssncferreira) [inline enterprise/aibridgedserver/aibridgedserver_test.go]: Is this test needed? Seems redundant with the dbauthz coverage for `UpsertAISeatState`, which already verifies the `ActionCreate` on `ResourceAiSeat`.

File: enterprise/aiseats/tracker_test.go [hunk 5]
```diff
@@ -77,65 +87,98 @@ func TestSeatTrackerDB(t *testing.T) {
...
 		require.NoError(t, err)
 		require.EqualValues(t, 1, count)
 
 		require.Len(t, a.AuditLogs(), 1)
 		require.Equal(t, database.ResourceTypeAiSeat, a.AuditLogs()[0].ResourceType)
 	})
+
+	// Provisionerd also calls RecordUsage via SeatTracker for
+	// task workspace builds.
+	t.Run("AsProvisionerd", func(t *testing.T) {
```
Comment (ssncferreira) [inline enterprise/aiseats/tracker_test.go:154]: Is this the reason why provisioner role needs create on AI seat? I thought task workspaces were no longer used 🤔

**Review by ssncferreira — APPROVED** [review]
LGTM 👍 thank you for handling this 🙏 just a couple of notes, but nothing blocking from my side

File: coderd/database/dbauthz/dbauthz.go (hunk 2 above)
Comment (mtojek) [reply coderd/database/dbauthz/dbauthz.go:229]: `provisionerdserver.go` still calls `RecordUsage` for task workspace builds (`workspace.TaskID.Valid`). The code isn't deprecated or removed, so I kept the permission.

File: enterprise/aiseats/tracker_test.go (hunk 5 above)
Comment (mtojek) [reply enterprise/aiseats/tracker_test.go:154]: see above

File: coderd/database/dbauthz/dbauthz_test.go (hunk 3 above)
Comment (mtojek) [reply coderd/database/dbauthz/dbauthz_test.go]: I missed it, fixed. Thanks!

File: enterprise/aibridgedserver/aibridgedserver_test.go (hunk 4 above)
Comment (mtojek) [reply enterprise/aibridgedserver/aibridgedserver_test.go]: Hm.. I think you're right. Deleted.
