### PR TITLE
fix(agent): start devcontainers through agentcontainers package

### LINKED ISSUE #706: Devcontainers: Decrease log spam from running @devcontainers/cli
Currently we output the entire log stream from `@devcontainers/cli` to the parent agent log. We should filter on `level: 3` as well as only output the `text` part instead of the whole JSON payload.

An example of the full payload is available at the bottom.

Result from applying `level: 3` filter and extracting `text`:

```console
@devcontainers/cli 0.76.0. Node.js v20.16.0. linux 6.8.0-60-generic x64.
Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-in-docker:2'...
Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
Files to omit: ''
Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-coder/container-features/0.76.0-1750239153793 --build-arg _DEV_CONTAINERS_BASE_IMAGE=codercom/oss-dogfood:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=coder --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-coder/container-features/0.76.0-1750239153793/Dockerfile.extended -t vsc-coder-16501171b99410a3c45670c2393882c63fca0ca319d89a5c3f48672fec889697-features /tmp/devcontainercli-coder/empty-folder
#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from Dockerfile.extended\n#1 transferring dockerfile: 2.83kB done\n#1 DONE 0.0s\n\n#2 resolve image config for docker-image://docker.io/docker/dockerfile:1.4\n
#2 DONE 0.7s\n
\n#3 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc\n#3 resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc done\n#3 sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 2.00kB / 2.00kB done\n#3 sha256:ad87fb03593d1b71f9a1cfc1406c4aafcb253b1dabebf569768d6e6166836f34 528B / 528B done\n#3 sha256:1e8a16826fd1c80a63fa6817a9c7284c94e40cded14a9b0d0d3722356efa47bd 2.37kB / 2.37kB done\n#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0B / 9.94MB 0.1s\n
#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 6.29MB / 9.94MB 0.3s\n
#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB 0.3s done\n#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.1s\n
#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.3s done\n#3 DONE 0.6s\n
\n#4 [internal] load .dockerignore\n#4 transferring context: 2B done\n#4 DONE 0.0s\n\n#5 [context dev_containers_feature_content_source] load .dockerignore\n#5 transferring dev_containers_feature_content_source: 2B done\n#5 DONE 0.0s\n\n#6 [internal] load metadata for docker.io/codercom/oss-dogfood:latest\n
#6 DONE 2.7s\n
\n#7 [context dev_containers_feature_content_source] load from client\n#7 transferring dev_containers_feature_content_source: 81.48kB done\n#7 DONE 0.0s\n\n#8 [dev_containers_feature_content_normalize 1/3] FROM docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443\n#8 resolve docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 done\n#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0B / 29.54MB 0.1s\n#8 sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8 6.61kB / 6.61kB done\n#8 sha256:cd1b9e8c46de633ff92e03f4e3db60883520295ffce0379da05587a5c7a3b211 25.72kB / 25.72kB done\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 0B / 20.04kB 0.1s\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 0B / 56.27MB 0.1s\n#8 sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 856B / 856B done\n
#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 13.63MB / 29.54MB 0.3s\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 20.04kB / 20.04kB 0.2s done\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 0B / 202B 0.3s\n
#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s\n
#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s done\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 5.24MB / 56.27MB 0.5s\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 202B / 202B 0.5s done\n#8 extracting sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0.1s\n#8 sha256:5c6c08bf17935d799bde53457781042a7593bcfa2c2b8bacd05b875748426ca8 0B / 1.43GB 0.5s\n
#8 sha256:14511a7be93f6649f6b2541d355a1d2009cce93fd348d69743f4f0a017e8c2ed 0B / 29.64MB 0.5s\n
#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 16.78MB / 56.27MB 0.6s\n
```

The JSON looks as follows, and as can be seen, there exists two types: `text` and `raw`. We could consider doing some treatment to the raw output as well.

```json
{"type":"text","level":3,"timestamp":1750239151324,"text":"@devcontainers/cli 0.76.0. Node.js v20.16.0. linux 6.8.0-60-generic x64."}
{"type":"text","level":3,"timestamp":1750239153796,"text":"Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-in-docker:2'..."}
{"type":"text","level":3,"timestamp":1750239154383,"text":"Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order..."}
{"type":"text","level":3,"timestamp":1750239155097,"text":"Files to omit: ''"}
{"type":"start","level":3,"timestamp":1750239155118,"text":"Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-coder/container-features/0.76.0-1750239153793 --build-arg _DEV_CONTAINERS_BASE_IMAGE=codercom/oss-dogfood:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=coder --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-coder/container-features/0.76.0-1750239153793/Dockerfile.extended -t vsc-coder-16501171b99410a3c45670c2393882c63fca0ca319d89a5c3f48672fec889697-features /tmp/devcontainercli-coder/empty-folder"}
{"type":"raw","level":3,"timestamp":1750239155413,"text":"#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from Dockerfile.extended\n#1 transferring dockerfile: 2.83kB done\n#1 DONE 0.0s\n\n#2 resolve image config for docker-image://docker.io/docker/dockerfile:1.4\n"}
{"type":"raw","level":3,"timestamp":1750239155917,"text":"#2 DONE 0.7s\n"}
{"type":"raw","level":3,"timestamp":1750239156022,"text":"\n#3 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc\n#3 resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc done\n#3 sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 2.00kB / 2.00kB done\n#3 sha256:ad87fb03593d1b71f9a1cfc1406c4aafcb253b1dabebf569768d6e6166836f34 528B / 528B done\n#3 sha256:1e8a16826fd1c80a63fa6817a9c7284c94e40cded14a9b0d0d3722356efa47bd 2.37kB / 2.37kB done\n#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0B / 9.94MB 0.1s\n"}
{"type":"raw","level":3,"timestamp":1750239156222,"text":"#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 6.29MB / 9.94MB 0.3s\n"}
{"type":"raw","level":3,"timestamp":1750239156366,"text":"#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB 0.3s done\n#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.1s\n"}
{"type":"raw","level":3,"timestamp":1750239156676,"text":"#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.3s done\n#3 DONE 0.6s\n"}
{"type":"raw","level":3,"timestamp":1750239156839,"text":"\n#4 [internal] load .dockerignore\n#4 transferring context: 2B done\n#4 DONE 0.0s\n\n#5 [context dev_containers_feature_content_source] load .dockerignore\n#5 transferring dev_containers_feature_content_source: 2B done\n#5 DONE 0.0s\n\n#6 [internal] load metadata for docker.io/codercom/oss-dogfood:latest\n"}
{"type":"raw","level":3,"timestamp":1750239159359,"text":"#6 DONE 2.7s\n"}
{"type":"raw","level":3,"timestamp":1750239159511,"text":"\n#7 [context dev_containers_feature_content_source] load from client\n#7 transferring dev_containers_feature_content_source: 81.48kB done\n#7 DONE 0.0s\n\n#8 [dev_containers_feature_content_normalize 1/3] FROM docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443\n#8 resolve docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 done\n#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0B / 29.54MB 0.1s\n#8 sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8 6.61kB / 6.61kB done\n#8 sha256:cd1b9e8c46de633ff92e03f4e3db60883520295ffce0379da05587a5c7a3b211 25.72kB / 25.72kB done\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 0B / 20.04kB 0.1s\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 0B / 56.27MB 0.1s\n#8 sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 856B / 856B done\n"}
{"type":"raw","level":3,"timestamp":1750239159710,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 13.63MB / 29.54MB 0.3s\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 20.04kB / 20.04kB 0.2s done\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 0B / 202B 0.3s\n"}
{"type":"raw","level":3,"timestamp":1750239159812,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s\n"}
{"type":"raw","level":3,"timestamp":1750239159998,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s done\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 5.24MB / 56.27MB 0.5s\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 202B / 202B 0.5s done\n#8 extracting sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0.1s\n#8 sha256:5c6c08bf17935d799bde53457781042a7593bcfa2c2b8bacd05b875748426ca8 0B / 1.43GB 0.5s\n"}
{"type":"raw","level":3,"timestamp":1750239159999,"text":"#8 sha256:14511a7be93f6649f6b2541d355a1d2009cce93fd348d69743f4f0a017e8c2ed 0B / 29.64MB 0.5s\n"}
{"type":"raw","level":3,"timestamp":1750239160102,"text":"#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 16.78MB / 56.27MB 0.6s\n"}
```

Full output:

```json
{"type":"text","level":3,"timestamp":1750239151324,"text":"@devcontainers/cli 0.76.0. Node.js v20.16.0. linux 6.8.0-60-generic x64."}
{"type":"start","level":2,"timestamp":1750239151324,"text":"Run: docker buildx version"}
{"type":"stop","level":2,"timestamp":1750239151373,"text":"Run: docker buildx version","startTimestamp":1750239151324}
{"type":"text","level":2,"timestamp":1750239151373,"text":"github.com/docker/buildx v0.24.0 d0e5e86c8b88ae4865040bc96917c338f4dd673c\r\n"}
{"type":"text","level":2,"timestamp":1750239151373,"text":"\u001b[1m\u001b[31m\u001b[39m\u001b[22m\r\n"}
{"type":"start","level":2,"timestamp":1750239151373,"text":"Run: docker -v"}
{"type":"stop","level":2,"timestamp":1750239151387,"text":"Run: docker -v","startTimestamp":1750239151373}
{"type":"start","level":2,"timestamp":1750239151387,"text":"Resolving Remote"}
{"type":"start","level":2,"timestamp":1750239151389,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder --filter label=devcontainer.config_file=/home/coder/coder/.devcontainer/devcontainer.json"}
{"type":"stop","level":2,"timestamp":1750239151404,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder --filter label=devcontainer.config_file=/home/coder/coder/.devcontainer/devcontainer.json","startTimestamp":1750239151389}
{"type":"start","level":2,"timestamp":1750239151404,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder"}
{"type":"stop","level":2,"timestamp":1750239151418,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder","startTimestamp":1750239151404}
{"type":"start","level":2,"timestamp":1750239151544,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder --filter label=devcontainer.config_file=/home/coder/coder/.devcontainer/devcontainer.json"}
{"type":"stop","level":2,"timestamp":1750239151560,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/coder/coder --filter label=devcontainer.config_file=/home/coder/coder/.devcontainer/devcontainer.json","startTimestamp":1750239151544}
{"type":"start","level":2,"timestamp":1750239151561,"text":"Run: docker inspect --type image codercom/oss-dogfood:latest"}
{"type":"stop","level":2,"timestamp":1750239151577,"text":"Run: docker inspect --type image codercom/oss-dogfood:latest","startTimestamp":1750239151561}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> input: docker.io/codercom/oss-dogfood:latest"}
{"type":"text","level":1,"timestamp":1750239151577,"text":">"}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> resource: docker.io/codercom/oss-dogfood"}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> id: oss-dogfood"}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> owner: codercom"}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> namespace: codercom"}
{"type":"text","level":1,"timestamp":1750239151577,"text":"> registry: docker.io"}
{"type":"text","level":1,"timestamp":1750239151578,"text":"> path: codercom/oss-dogfood"}
{"type":"text","level":1,"timestamp":1750239151578,"text":">"}
{"type":"text","level":1,"timestamp":1750239151578,"text":"> version: latest"}
{"type":"text","level":1,"timestamp":1750239151578,"text":"> tag?: latest"}
{"type":"text","level":1,"timestamp":1750239151578,"text":"> digest?: undefined"}
{"type":"text","level":1,"timestamp":1750239151578,"text":"manifest url: https://registry-1.docker.io/v2/codercom/oss-dogfood/manifests/latest"}
{"type":"text","level":1,"timestamp":1750239151894,"text":"[httpOci] Attempting to authenticate via 'Bearer' auth."}
{"type":"text","level":1,"timestamp":1750239151896,"text":"[httpOci] Invoking platform default credential helper 'secret'"}
{"type":"start","level":2,"timestamp":1750239151896,"text":"Run: docker-credential-secret get"}
{"type":"stop","level":2,"timestamp":1750239151898,"text":"Run: docker-credential-secret get","startTimestamp":1750239151896}
{"type":"text","level":1,"timestamp":1750239151899,"text":"[httpOci] Failed to query for 'docker.io' credential from 'docker-credential-secret': Error: write EPIPE"}
{"type":"text","level":1,"timestamp":1750239151899,"text":"[httpOci] No authentication credentials found for registry 'docker.io' via docker config or credential helper."}
{"type":"text","level":1,"timestamp":1750239151899,"text":"[httpOci] No authentication credentials found for registry 'docker.io'. Accessing anonymously."}
{"type":"text","level":1,"timestamp":1750239151899,"text":"[httpOci] Attempting to fetch bearer token from:  https://auth.docker.io/token?service=registry.docker.io&scope=repository:codercom/oss-dogfood:pull"}
{"type":"stop","level":2,"timestamp":1750239151900,"text":"Run: docker-credential-secret get","startTimestamp":1750239151896}
{"type":"text","level":1,"timestamp":1750239152625,"text":"[httpOci] 200 on reattempt after auth: https://registry-1.docker.io/v2/codercom/oss-dogfood/manifests/latest"}
{"type":"text","level":1,"timestamp":1750239152626,"text":"[httpOci] Applying cachedAuthHeader for registry docker.io..."}
{"type":"text","level":1,"timestamp":1750239152984,"text":"[httpOci] 200 (Cached): https://registry-1.docker.io/v2/codercom/oss-dogfood/manifests/latest"}
{"type":"text","level":1,"timestamp":1750239152985,"text":"Fetched: {\n    \"schemaVersion\": 2,\n    \"mediaType\": \"application/vnd.oci.image.index.v1+json\",\n    \"manifests\": [\n        {\n            \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\",\n            \"digest\": \"sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8\",\n            \"size\": 6608,\n            \"platform\": {\n                \"architecture\": \"amd64\",\n                \"os\": \"linux\"\n            }\n        },\n        {\n            \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\",\n            \"digest\": \"sha256:d4e89fcdb375e5b11e2bedbc3061663716e7a36b8486f69c7603517bfcbeebf1\",\n            \"size\": 568,\n            \"annotations\": {\n                \"vnd.docker.reference.digest\": \"sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8\",\n                \"vnd.docker.reference.type\": \"attestation-manifest\"\n            },\n            \"platform\": {\n                \"architecture\": \"unknown\",\n                \"os\": \"unknown\"\n            }\n        }\n    ]\n}"}
{"type":"text","level":1,"timestamp":1750239152985,"text":"[httpOci] Applying cachedAuthHeader for registry docker.io..."}
{"type":"text","level":1,"timestamp":1750239153414,"text":"[httpOci] 200 (Cached): https://registry-1.docker.io/v2/codercom/oss-dogfood/manifests/sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8"}
{"type":"text","level":1,"timestamp":1750239153414,"text":"blob url: https://registry-1.docker.io/v2/codercom/oss-dogfood/blobs/sha256:cd1b9e8c46de633ff92e03f4e3db60883520295ffce0379da05587a5c7a3b211"}
{"type":"text","level":1,"timestamp":1750239153414,"text":"[httpOci] Applying cachedAuthHeader for registry docker.io..."}
{"type":"text","level":1,"timestamp":1750239153792,"text":"[httpOci] 200 (Cached): https://registry-1.docker.io/v2/codercom/oss-dogfood/blobs/sha256:cd1b9e8c46de633ff92e03f4e3db60883520295ffce0379da05587a5c7a3b211"}
{"type":"text","level":1,"timestamp":1750239153794,"text":"workspace root: /home/coder/coder"}
{"type":"text","level":1,"timestamp":1750239153794,"text":"configPath: /home/coder/coder/.devcontainer/devcontainer.json"}
{"type":"text","level":1,"timestamp":1750239153795,"text":"--- Processing User Features ----"}
{"type":"text","level":1,"timestamp":1750239153795,"text":"[* user-provided] ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":3,"timestamp":1750239153796,"text":"Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-in-docker:2'..."}
{"type":"text","level":2,"timestamp":1750239153796,"text":"* Processing feature: ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> input: ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239153796,"text":">"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> resource: ghcr.io/devcontainers/features/docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> id: docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> owner: devcontainers"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> namespace: devcontainers/features"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> registry: ghcr.io"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> path: devcontainers/features/docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239153796,"text":">"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> version: 2"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> tag?: 2"}
{"type":"text","level":1,"timestamp":1750239153796,"text":"> digest?: undefined"}
{"type":"text","level":1,"timestamp":1750239153797,"text":"manifest url: https://ghcr.io/v2/devcontainers/features/docker-in-docker/manifests/2"}
{"type":"text","level":1,"timestamp":1750239153909,"text":"[httpOci] Attempting to authenticate via 'Bearer' auth."}
{"type":"text","level":1,"timestamp":1750239153910,"text":"[httpOci] Invoking platform default credential helper 'secret'"}
{"type":"start","level":2,"timestamp":1750239153911,"text":"Run: docker-credential-secret get"}
{"type":"stop","level":2,"timestamp":1750239153914,"text":"Run: docker-credential-secret get","startTimestamp":1750239153911}
{"type":"text","level":1,"timestamp":1750239153914,"text":"[httpOci] Failed to query for 'ghcr.io' credential from 'docker-credential-secret': Error: write EPIPE"}
{"type":"text","level":1,"timestamp":1750239153914,"text":"[httpOci] No authentication credentials found for registry 'ghcr.io' via docker config or credential helper."}
{"type":"text","level":1,"timestamp":1750239153914,"text":"[httpOci] No authentication credentials found for registry 'ghcr.io'. Accessing anonymously."}
{"type":"text","level":1,"timestamp":1750239153914,"text":"[httpOci] Attempting to fetch bearer token from:  https://ghcr.io/token?service=ghcr.io&scope=repository:devcontainers/features/docker-in-docker:pull"}
{"type":"stop","level":2,"timestamp":1750239153915,"text":"Run: docker-credential-secret get","startTimestamp":1750239153911}
{"type":"text","level":1,"timestamp":1750239154225,"text":"[httpOci] 200 on reattempt after auth: https://ghcr.io/v2/devcontainers/features/docker-in-docker/manifests/2"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> input: ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239154225,"text":">"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> resource: ghcr.io/devcontainers/features/docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> id: docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> owner: devcontainers"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> namespace: devcontainers/features"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> registry: ghcr.io"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> path: devcontainers/features/docker-in-docker"}
{"type":"text","level":1,"timestamp":1750239154225,"text":">"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> version: 2"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> tag?: 2"}
{"type":"text","level":1,"timestamp":1750239154225,"text":"> digest?: undefined"}
{"type":"text","level":2,"timestamp":1750239154226,"text":"* Processing feature: ghcr.io/devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> input: ghcr.io/devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154226,"text":">"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> resource: ghcr.io/devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> id: common-utils"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> owner: devcontainers"}                                                                         {"type":"text","level":1,"timestamp":1750239154226,"text":"> namespace: devcontainers/features"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> registry: ghcr.io"}                                                                            {"type":"text","level":1,"timestamp":1750239154226,"text":"> path: devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154226,"text":">"}                                                                                              {"type":"text","level":1,"timestamp":1750239154226,"text":"> version: latest"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> tag?: latest"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"> digest?: undefined"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"manifest url: https://ghcr.io/v2/devcontainers/features/common-utils/manifests/latest"}
{"type":"text","level":1,"timestamp":1750239154226,"text":"[httpOci] Applying cachedAuthHeader for registry ghcr.io..."}
{"type":"text","level":1,"timestamp":1750239154382,"text":"[httpOci] 200 (Cached): https://ghcr.io/v2/devcontainers/features/common-utils/manifests/latest"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> input: ghcr.io/devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154382,"text":">"}                                                                                              {"type":"text","level":1,"timestamp":1750239154382,"text":"> resource: ghcr.io/devcontainers/features/common-utils"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> id: common-utils"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> owner: devcontainers"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> namespace: devcontainers/features"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> registry: ghcr.io"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> path: devcontainers/features/common-utils"}                                                    {"type":"text","level":1,"timestamp":1750239154382,"text":">"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> version: latest"}                                                                              {"type":"text","level":1,"timestamp":1750239154382,"text":"> tag?: latest"}
{"type":"text","level":1,"timestamp":1750239154382,"text":"> digest?: undefined"}                                                                           {"type":"text","level":1,"timestamp":1750239154383,"text":"[* resolved worklist] ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239154383,"text":"[\n  {\n    \"type\": \"user-provided\",\n    \"userFeatureId\": \"ghcr.io/devcontainers/features/docker-in-docker:2\",\n    \"options\": {\n      \"moby\": \"false\"\n    },\n    \"dependsOn\": [],\n    \"installsAfter\": [\n      {\n        \"type\": \"resolved\",\n        \"userFeatureId\": \"ghcr.io/devcontainers/features/common-utils\",\n        \"options\": {},\n        \"featureSet\": {\n          \"sourceInformation\": {\n            \"type\": \"oci\",\n            \"manifest\": {\n              \"schemaVersion\": 2,\n              \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\",\n              \"config\": {\n                \"mediaType\": \"application/vnd.devcontainers\",\n                \"digest\": \"sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a\",\n                \"size\": 2\n              },\n              \"layers\": [\n                {\n                  \"mediaType\": \"application/vnd.devcontainers.layer.v1+tar\",\n                  \"digest\": \"sha256:1ea70afedad2279cd746a4c0b7ac0e0fb481599303a1cbe1e57c9cb87dbe5de5\",\n                  \"size\": 50176,\n                  \"annotations\": {\n                    \"org.opencontainers.image.title\": \"devcontainer-feature-common-utils.tgz\"\n                  }\n                }\n              ],\n              \"annotations\": {\n                \"dev.containers.metadata\": \"{\\\"id\\\":\\\"common-utils\\\",\\\"version\\\":\\\"2.5.3\\\",\\\"name\\\":\\\"Common Utilities\\\",\\\"documentationURL\\\":\\\"https://github.com/devcontainers/features/tree/main/src/common-utils\\\",\\\"description\\\":\\\"Installs a set of common command line utilities, Oh My Zsh!, and sets up a non-root user.\\\",\\\"options\\\":{\\\"installZsh\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Install ZSH?\\\"},\\\"configureZshAsDefaultShell\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":false,\\\"description\\\":\\\"Change default shell to ZSH?\\\"},\\\"installOhMyZsh\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Install Oh My Zsh!?\\\"},\\\"installOhMyZshConfig\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Allow installing the default dev container .zshrc templates?\\\"},\\\"upgradePackages\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Upgrade OS packages?\\\"},\\\"username\\\":{\\\"type\\\":\\\"string\\\",\\\"proposals\\\":[\\\"devcontainer\\\",\\\"vscode\\\",\\\"codespace\\\",\\\"none\\\",\\\"automatic\\\"],\\\"default\\\":\\\"automatic\\\",\\\"description\\\":\\\"Enter name of a non-root user to configure or none to skip\\\"},\\\"userUid\\\":{\\\"type\\\":\\\"string\\\",\\\"proposals\\\":[\\\"1001\\\",\\\"automatic\\\"],\\\"default\\\":\\\"automatic\\\",\\\"description\\\":\\\"Enter UID for non-root user\\\"},\\\"userGid\\\":{\\\"type\\\":\\\"string\\\",\\\"proposals\\\":[\\\"1001\\\",\\\"automatic\\\"],\\\"default\\\":\\\"automatic\\\",\\\"description\\\":\\\"Enter GID for non-root user\\\"},\\\"nonFreePackages\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":false,\\\"description\\\":\\\"Add packages from non-free Debian repository? (Debian only)\\\"}}}\",\n                \"com.github.package.type\": \"devcontainer_feature\"\n              }\n            },\n            \"manifestDigest\": \"sha256:3cf7ca93154faf9bdb128f3009cf1d1a91750ec97cc52082cf5d4edef5451f85\",\n            \"featureRef\": {\n              \"id\": \"common-utils\",\n              \"owner\": \"devcontainers\",\n              \"namespace\": \"devcontainers/features\",\n              \"registry\": \"ghcr.io\",\n              \"resource\": \"ghcr.io/devcontainers/features/common-utils\",\n              \"path\": \"devcontainers/features/common-utils\",\n              \"version\": \"latest\",\n              \"tag\": \"latest\"\n            },\n            \"userFeatureId\": \"ghcr.io/devcontainers/features/common-utils\",\n            \"userFeatureIdWithoutVersion\": \"ghcr.io/devcontainers/features/common-utils\"\n          },\n          \"features\": [\n            {\n              \"id\": \"common-utils\",\n              \"included\": true,\n              \"value\": {}\n            }\n          ]\n        },\n        \"dependsOn\": [],\n        \"installsAfter\": [],\n        \"roundPriority\": 0,\n        \"featureIdAliases\": [\n          \"common-utils\"\n        ]\n      }\n    ],\n    \"roundPriority\": 0,\n    \"featureSet\": {\n      \"sourceInformation\": {\n        \"type\": \"oci\",\n        \"manifest\": {\n          \"schemaVersion\": 2,\n          \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\",\n          \"config\": {\n            \"mediaType\": \"application/vnd.devcontainers\",\n            \"digest\": \"sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a\",\n            \"size\": 2\n          },\n          \"layers\": [\n            {\n              \"mediaType\": \"application/vnd.devcontainers.layer.v1+tar\",\n              \"digest\": \"sha256:52d59106dd0809d78a560aa2f71061a7228258364080ac745d68072064ec5a72\",\n              \"size\": 40448,\n              \"annotations\": {\n                \"org.opencontainers.image.title\": \"devcontainer-feature-docker-in-docker.tgz\"\n              }\n            }\n          ],\n          \"annotations\": {\n            \"dev.containers.metadata\": \"{\\\"id\\\":\\\"docker-in-docker\\\",\\\"version\\\":\\\"2.12.2\\\",\\\"name\\\":\\\"Docker (Docker-in-Docker)\\\",\\\"documentationURL\\\":\\\"https://github.com/devcontainers/features/tree/main/src/docker-in-docker\\\",\\\"description\\\":\\\"Create child containers *inside* a container, independent from the host's docker instance. Installs Docker extension in the container along with needed CLIs.\\\",\\\"options\\\":{\\\"version\\\":{\\\"type\\\":\\\"string\\\",\\\"proposals\\\":[\\\"latest\\\",\\\"none\\\",\\\"20.10\\\"],\\\"default\\\":\\\"latest\\\",\\\"description\\\":\\\"Select or enter a Docker/Moby Engine version. (Availability can vary by OS version.)\\\"},\\\"moby\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Install OSS Moby build instead of Docker CE\\\"},\\\"mobyBuildxVersion\\\":{\\\"type\\\":\\\"string\\\",\\\"default\\\":\\\"latest\\\",\\\"description\\\":\\\"Install a specific version of moby-buildx when using Moby\\\"},\\\"dockerDashComposeVersion\\\":{\\\"type\\\":\\\"string\\\",\\\"enum\\\":[\\\"none\\\",\\\"v1\\\",\\\"v2\\\"],\\\"default\\\":\\\"v2\\\",\\\"description\\\":\\\"Default version of Docker Compose (v1, v2 or none)\\\"},\\\"azureDnsAutoDetection\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Allow automatically setting the dockerd DNS server when the installation script detects it is running in Azure\\\"},\\\"dockerDefaultAddressPool\\\":{\\\"type\\\":\\\"string\\\",\\\"default\\\":\\\"\\\",\\\"proposals\\\":[],\\\"description\\\":\\\"Define default address pools for Docker networks. e.g. base=192.168.0.0/16,size=24\\\"},\\\"installDockerBuildx\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Install Docker Buildx\\\"},\\\"installDockerComposeSwitch\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":true,\\\"description\\\":\\\"Install Compose Switch (provided docker compose is available) which is a replacement to the Compose V1 docker-compose (python) executable. It translates the command line into Compose V2 docker compose then runs the latter.\\\"},\\\"disableIp6tables\\\":{\\\"type\\\":\\\"boolean\\\",\\\"default\\\":false,\\\"description\\\":\\\"Disable ip6tables (this option is only applicable for Docker versions 27 and greater)\\\"}},\\\"entrypoint\\\":\\\"/usr/local/share/docker-init.sh\\\",\\\"privileged\\\":true,\\\"containerEnv\\\":{\\\"DOCKER_BUILDKIT\\\":\\\"1\\\"},\\\"customizations\\\":{\\\"vscode\\\":{\\\"extensions\\\":[\\\"ms-azuretools.vscode-docker\\\"],\\\"settings\\\":{\\\"github.copilot.chat.codeGeneration.instructions\\\":[{\\\"text\\\":\\\"This dev container includes the Docker CLI (`docker`) pre-installed and available on the `PATH` for running and managing containers using a dedicated Docker daemon running inside the dev container.\\\"}]}}},\\\"mounts\\\":[{\\\"source\\\":\\\"dind-var-lib-docker-${devcontainerId}\\\",\\\"target\\\":\\\"/var/lib/docker\\\",\\\"type\\\":\\\"volume\\\"}],\\\"installsAfter\\\":[\\\"ghcr.io/devcontainers/features/common-utils\\\"]}\",\n            \"com.github.package.type\": \"devcontainer_feature\"\n          }\n        },\n        \"manifestDigest\": \"sha256:842d2ed40827dc91b95ef727771e170b0e52272404f00dba063cee94eafac4bb\",\n        \"featureRef\": {\n          \"id\": \"docker-in-docker\",\n          \"owner\": \"devcontainers\",\n          \"namespace\": \"devcontainers/features\",\n          \"registry\": \"ghcr.io\",\n          \"resource\": \"ghcr.io/devcontainers/features/docker-in-docker\",\n          \"path\": \"devcontainers/features/docker-in-docker\",\n          \"version\": \"2\",\n          \"tag\": \"2\"\n        },\n        \"userFeatureId\": \"ghcr.io/devcontainers/features/docker-in-docker:2\",\n        \"userFeatureIdWithoutVersion\": \"ghcr.io/devcontainers/features/docker-in-docker\"\n      },\n      \"features\": [\n        {\n          \"id\": \"docker-in-docker\",\n          \"included\": true,\n          \"value\": {\n            \"moby\": \"false\"\n          },\n          \"version\": \"2.12.2\",\n          \"name\": \"Docker (Docker-in-Docker)\",\n          \"documentationURL\": \"https://github.com/devcontainers/features/tree/main/src/docker-in-docker\",\n          \"description\": \"Create child containers *inside* a container, independent from the host's docker instance. Installs Docker extension in the container along with needed CLIs.\",\n          \"options\": {\n            \"version\": {\n              \"type\": \"string\",\n              \"proposals\": [\n                \"latest\",\n                \"none\",\n                \"20.10\"\n              ],\n              \"default\": \"latest\",\n              \"description\": \"Select or enter a Docker/Moby Engine version. (Availability can vary by OS version.)\"\n            },\n            \"moby\": {\n              \"type\": \"boolean\",\n              \"default\": true,\n              \"description\": \"Install OSS Moby build instead of Docker CE\"\n            },\n            \"mobyBuildxVersion\": {\n              \"type\": \"string\",\n              \"default\": \"latest\",\n              \"description\": \"Install a specific version of moby-buildx when using Moby\"\n            },\n            \"dockerDashComposeVersion\": {\n              \"type\": \"string\",\n              \"enum\": [\n                \"none\",\n                \"v1\",\n                \"v2\"\n              ],\n              \"default\": \"v2\",\n              \"description\": \"Default version of Docker Compose (v1, v2 or none)\"\n            },\n            \"azureDnsAutoDetection\": {\n              \"type\": \"boolean\",\n              \"default\": true,\n              \"description\": \"Allow automatically setting the dockerd DNS server when the installation script detects it is running in Azure\"\n            },\n            \"dockerDefaultAddressPool\": {\n              \"type\": \"string\",\n              \"default\": \"\",\n              \"proposals\": [],\n              \"description\": \"Define default address pools for Docker networks. e.g. base=192.168.0.0/16,size=24\"\n            },\n            \"installDockerBuildx\": {\n              \"type\": \"boolean\",\n              \"default\": true,\n              \"description\": \"Install Docker Buildx\"\n            },\n            \"installDockerComposeSwitch\": {\n              \"type\": \"boolean\",\n              \"default\": true,\n              \"description\": \"Install Compose Switch (provided docker compose is available) which is a replacement to the Compose V1 docker-compose (python) executable. It translates the command line into Compose V2 docker compose then runs the latter.\"\n            },\n            \"disableIp6tables\": {\n              \"type\": \"boolean\",\n              \"default\": false,\n              \"description\": \"Disable ip6tables (this option is only applicable for Docker versions 27 and greater)\"\n            }\n          },\n          \"entrypoint\": \"/usr/local/share/docker-init.sh\",\n          \"privileged\": true,\n          \"containerEnv\": {\n            \"DOCKER_BUILDKIT\": \"1\"\n          },\n          \"customizations\": {\n            \"vscode\": {\n              \"extensions\": [\n                \"ms-azuretools.vscode-docker\"\n              ],\n              \"settings\": {\n                \"github.copilot.chat.codeGeneration.instructions\": [\n                  {\n                    \"text\": \"This dev container includes the Docker CLI (`docker`) pre-installed and available on the `PATH` for running and managing containers using a dedicated Docker daemon running inside the dev container.\"\n                  }\n                ]\n              }\n            }\n          },\n          \"mounts\": [\n            {\n              \"source\": \"dind-var-lib-docker-${devcontainerId}\",\n              \"target\": \"/var/lib/docker\",\n              \"type\": \"volume\"\n            }\n          ],\n          \"installsAfter\": [\n            \"ghcr.io/devcontainers/features/common-utils\"\n          ]\n        }\n      ]\n    },\n    \"featureIdAliases\": [\n      \"docker-in-docker\"\n    ]\n  }\n]"}
{"type":"text","level":1,"timestamp":1750239154383,"text":"[raw worklist]: ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":3,"timestamp":1750239154383,"text":"Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order..."}
{"type":"text","level":1,"timestamp":1750239154383,"text":"[worklist-without-dangling-soft-deps]: ghcr.io/devcontainers/features/docker-in-docker:2"}       {"type":"text","level":1,"timestamp":1750239154383,"text":"Starting round-based Feature install order calculation from worklist..."}
{"type":"text","level":1,"timestamp":1750239154383,"text":"\n[round] ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239154384,"text":"[round-candidates] ghcr.io/devcontainers/features/docker-in-docker:2 (0)"}
{"type":"text","level":1,"timestamp":1750239154384,"text":"[round-after-filter-priority] (maxPriority=0) ghcr.io/devcontainers/features/docker-in-docker:2 (0)"}
{"type":"text","level":1,"timestamp":1750239154397,"text":"[round-after-comparesTo] ghcr.io/devcontainers/features/docker-in-docker:2"}
{"type":"text","level":1,"timestamp":1750239154397,"text":"--- Fetching User Features ----"}
{"type":"text","level":2,"timestamp":1750239154398,"text":"* Fetching feature: docker-in-docker_0_oci"}
{"type":"text","level":1,"timestamp":1750239154398,"text":"Fetching from OCI"}
{"type":"text","level":1,"timestamp":1750239154399,"text":"blob url: https://ghcr.io/v2/devcontainers/features/docker-in-docker/blobs/sha256:52d59106dd0809d78a560aa2f71061a7228258364080ac745d68072064ec5a72"}
{"type":"text","level":1,"timestamp":1750239154399,"text":"[httpOci] Applying cachedAuthHeader for registry ghcr.io..."}
{"type":"text","level":1,"timestamp":1750239155094,"text":"[httpOci] 200 (Cached): https://ghcr.io/v2/devcontainers/features/docker-in-docker/blobs/sha256:52d59106dd0809d78a560aa2f71061a7228258364080ac745d68072064ec5a72"}
{"type":"text","level":1,"timestamp":1750239155097,"text":"omitDuringExtraction: '"}
{"type":"text","level":3,"timestamp":1750239155097,"text":"Files to omit: ''"}
{"type":"text","level":1,"timestamp":1750239155102,"text":"Testing './'(Directory)"}
{"type":"text","level":1,"timestamp":1750239155104,"text":"Testing './NOTES.md'(File)"}
{"type":"text","level":1,"timestamp":1750239155105,"text":"Testing './README.md'(File)"}
{"type":"text","level":1,"timestamp":1750239155105,"text":"Testing './devcontainer-feature.json'(File)"}
{"type":"text","level":1,"timestamp":1750239155105,"text":"Testing './install.sh'(File)"}
{"type":"text","level":1,"timestamp":1750239155110,"text":"Files extracted from blob: ./NOTES.md, ./README.md, ./devcontainer-feature.json, ./install.sh"}
{"type":"text","level":2,"timestamp":1750239155111,"text":"* Fetched feature: docker-in-docker_0_oci version 2.12.2"}
{"type":"start","level":3,"timestamp":1750239155118,"text":"Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-coder/container-features/0.76.0-1750239153793 --build-arg _DEV_CONTAINERS_BASE_IMAGE=codercom/oss-dogfood:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=coder --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-coder/container-features/0.76.0-1750239153793/Dockerfile.extended -t vsc-coder-16501171b99410a3c45670c2393882c63fca0ca319d89a5c3f48672fec889697-features /tmp/devcontainercli-coder/empty-folder"}
{"type":"raw","level":3,"timestamp":1750239155413,"text":"#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from Dockerfile.extended\n#1 transferring dockerfile: 2.83kB done\n#1 DONE 0.0s\n\n#2 resolve image config for docker-image://docker.io/docker/dockerfile:1.4\n"}
{"type":"raw","level":3,"timestamp":1750239155917,"text":"#2 DONE 0.7s\n"}
{"type":"raw","level":3,"timestamp":1750239156022,"text":"\n#3 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc\n#3 resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc done\n#3 sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 2.00kB / 2.00kB done\n#3 sha256:ad87fb03593d1b71f9a1cfc1406c4aafcb253b1dabebf569768d6e6166836f34 528B / 528B done\n#3 sha256:1e8a16826fd1c80a63fa6817a9c7284c94e40cded14a9b0d0d3722356efa47bd 2.37kB / 2.37kB done\n#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0B / 9.94MB 0.1s\n"}
{"type":"raw","level":3,"timestamp":1750239156222,"text":"#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 6.29MB / 9.94MB 0.3s\n"}
{"type":"raw","level":3,"timestamp":1750239156366,"text":"#3 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB 0.3s done\n#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.1s\n"}
{"type":"raw","level":3,"timestamp":1750239156676,"text":"#3 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.3s done\n#3 DONE 0.6s\n"}
{"type":"raw","level":3,"timestamp":1750239156839,"text":"\n#4 [internal] load .dockerignore\n#4 transferring context: 2B done\n#4 DONE 0.0s\n\n#5 [context dev_containers_feature_content_source] load .dockerignore\n#5 transferring dev_containers_feature_content_source: 2B done\n#5 DONE 0.0s\n\n#6 [internal] load metadata for docker.io/codercom/oss-dogfood:latest\n"}
{"type":"raw","level":3,"timestamp":1750239159359,"text":"#6 DONE 2.7s\n"}
{"type":"raw","level":3,"timestamp":1750239159511,"text":"\n#7 [context dev_containers_feature_content_source] load from client\n#7 transferring dev_containers_feature_content_source: 81.48kB done\n#7 DONE 0.0s\n\n#8 [dev_containers_feature_content_normalize 1/3] FROM docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443\n#8 resolve docker.io/codercom/oss-dogfood:latest@sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 done\n#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0B / 29.54MB 0.1s\n#8 sha256:6089f3cf114a835e3a41f47a867da30584ca7d4b582326b85cd52c6c172010e8 6.61kB / 6.61kB done\n#8 sha256:cd1b9e8c46de633ff92e03f4e3db60883520295ffce0379da05587a5c7a3b211 25.72kB / 25.72kB done\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 0B / 20.04kB 0.1s\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 0B / 56.27MB 0.1s\n#8 sha256:599c74e4bbbc5b60b724edcadfb842087202ad951ebd80d76b45609a5752a443 856B / 856B done\n"}
{"type":"raw","level":3,"timestamp":1750239159710,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 13.63MB / 29.54MB 0.3s\n#8 sha256:0aa4c37993f3fdd9f993b6a6f91a40546614977d8401bc73f820aedede2c1e19 20.04kB / 20.04kB 0.2s done\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 0B / 202B 0.3s\n"}
{"type":"raw","level":3,"timestamp":1750239159812,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s\n"}
{"type":"raw","level":3,"timestamp":1750239159998,"text":"#8 sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 29.54MB / 29.54MB 0.4s done\n#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 5.24MB / 56.27MB 0.5s\n#8 sha256:39ee86e3f1d5f75a02c66cb7ea1625cb313ac2b6933bf6da3ee26453f89a5453 202B / 202B 0.5s done\n#8 extracting sha256:6414378b647780fee8fd903ddb9541d134a1947ce092d08bdeb23a54cb3684ac 0.1s\n#8 sha256:5c6c08bf17935d799bde53457781042a7593bcfa2c2b8bacd05b875748426ca8 0B / 1.43GB 0.5s\n"}
{"type":"raw","level":3,"timestamp":1750239159999,"text":"#8 sha256:14511a7be93f6649f6b2541d355a1d2009cce93fd348d69743f4f0a017e8c2ed 0B / 29.64MB 0.5s\n"}
{"type":"raw","level":3,"timestamp":1750239160102,"text":"#8 sha256:38191baf86b8c70a1ba0fa327100642ccb5718028e68f0c25a2d5ff3c0d96a1b 16.78MB / 56.27MB 0.6s\n"}
```

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fixes https://github.com/coder/internal/issues/706

Context for the implementation here
https://github.com/coder/internal/issues/706#issuecomment-2990490282

Synchronously starts dev containers defined in terraform with our `DevcontainerCLI` abstraction, instead of piggybacking off of our `agentscripts` package. This gives us more control over logs, instead of being reliant on packages which may or may not exist in the user-provided image.

Screenshot 2025-06-24 at 15 54 47

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -1169,7 +1162,13 @@ func (a *agent) handleManifest(manifestOK *checkpoint) func(ctx context.Context,
 				// finished (both start and post start). For instance, an
 				// autostarted devcontainer will be included in this time.
 				err := a.scriptRunner.Execute(a.gracefulCtx, agentscripts.ExecuteStartScripts)
-				err = errors.Join(err, a.scriptRunner.Execute(a.gracefulCtx, agentscripts.ExecutePostStartScripts))
+
+				if cAPI := a.containerAPI.Load(); cAPI != nil {
+					for _, dc := range manifest.Devcontainers {
+						err = errors.Join(err, cAPI.CreateDevcontainer(dc))
```
Comment (mafredri) [inline agent/agent.go]: I think it's a good idea to do these sync so we avoid potential Docker concurrency races, it'd be nice if it was asynchronous but let's go with this!

File: agent/agentcontainers/api.go [hunk 2]
```diff
@@ -794,14 +796,25 @@ func (api *API) handleDevcontainerRecreate(w http.ResponseWriter, r *http.Reques
...
 
+func (api *API) CreateDevcontainer(dc codersdk.WorkspaceAgentDevcontainer) error {
+	api.mu.Lock()
+	dc.Status = codersdk.WorkspaceAgentDevcontainerStatusStarting
+	dc.Container = nil
+	api.knownDevcontainers[dc.WorkspaceFolder] = dc
+	api.asyncWg.Add(1)
+	api.mu.Unlock()
+
+	return api.recreateDevcontainer(dc, dc.ConfigPath)
```
Comment (mafredri) [inline agent/agentcontainers/api.go]: How about we rename this `createDevcontainer` and make `recreate` an argument? I'm thinking that _iff_ users use a docker volume for Docker, it might be nice if we didn't delete/recreate the existing container that was persisted across workspace restart. 🤔

File: agent/agentcontainers/devcontainer.go [hunk 3]
```diff
@@ -22,61 +20,6 @@ const (
...
-	}
-	cmd := fmt.Sprintf(devcontainerUpScriptTemplate, strings.Join(args, " "))
-	// Force the script to run in /bin/sh, since some shells (e.g. fish)
-	// don't support the script.
-	script.Script = fmt.Sprintf("/bin/sh -c '%s'", cmd)
-	// Disable RunOnStart, scripts have this set so that when devcontainers
-	// have not been enabled, a warning will be surfaced in the agent logs.
-	script.RunOnStart = false
-	return script
-}
```
Comment (mafredri) [inline agent/agentcontainers/devcontainer.go:78]: Yay!!!

File: agent/agentscripts/agentscripts.go [hunk 4]
```diff
@@ -138,19 +123,6 @@ func (r *Runner) RegisterMetrics(reg prometheus.Registerer) {
...
-func WithPostStartScripts(scripts ...codersdk.WorkspaceAgentScript) InitOption {
-	return func(r *Runner) {
-		for _, s := range scripts {
-			r.scripts = append(r.scripts, runnerScript{
-				runOnPostStart:       true,
-				WorkspaceAgentScript: s,
-			})
-		}
-	}
-}
```
Comment (mafredri) [inline agent/agentscripts/agentscripts.go:152]: Good bye my beautiful hack! 👋🏻

File: agent/agentcontainers/devcontainercli_test.go [hunk 5]
```diff
@@ -363,7 +363,7 @@ func TestDevcontainerCLI_WithOutput(t *testing.T) {
 		require.NotEmpty(t, containerID, "expected non-empty container ID")
 
 		// Read expected log content.
-		expLog, err := os.ReadFile(filepath.Join("testdata", "devcontainercli", "parse", "up.log"))
+		expLog, err := os.ReadFile(filepath.Join("testdata", "devcontainercli", "parse", "up.expected"))
```
Comment (mafredri) [inline agent/agentcontainers/devcontainercli_test.go]: Suggestion: `.golden` is a typical extension used for verifying output. (Won't push for a change though.)

File: agent/agentcontainers/api.go [hunk 6]
```diff
@@ -857,7 +870,7 @@ func (api *API) recreateDevcontainer(dc codersdk.WorkspaceAgentDevcontainer, con
 		api.knownDevcontainers[dc.WorkspaceFolder] = dc
 		api.recreateErrorTimes[dc.WorkspaceFolder] = api.clock.Now("agentcontainers", "recreate", "errorTimes")
 		api.mu.Unlock()
-		return
+		return err
```
Comment (mafredri) [inline agent/agentcontainers/api.go]: I suggest wrapping the errors here to provide more context.

**Review by mafredri — COMMENTED** [review]
Cursory glance looks good! 👍🏻

Couple of notes (in addition to inline comments):
- Testing, this could be done in `agent_test.go` for e.g. autostart integration test
- A `api_test.go` to test `CreateDevcontainer` behavior
- (Re-introduce agent script timing for autostart of devcontainer, not critical for GA, but perhaps track via ticket or if simple a follow-up PR.)

File: agent/agent.go [hunk 7]
```diff
@@ -1204,6 +1228,36 @@ func (a *agent) handleManifest(manifestOK *checkpoint) func(ctx context.Context,
...
+	}
+	endTime := a.clock.Now()
+
+	if _, scriptErr := aAPI.ScriptCompleted(ctx, &proto.WorkspaceAgentScriptCompletedRequest{
+		Timing: &proto.Timing{
+			ScriptId: script.ID[:],
+			Start:    timestamppb.New(startTime),
+			End:      timestamppb.New(endTime),
+			ExitCode: exitCode,
+			Stage:    proto.Timing_START,
```
Comment (mafredri) [inline agent/agent.go:1249]: Do we need to set `Status` as well (ok/exit failure)?

File: agent/api.go [hunk 8]
```diff
@@ -41,34 +37,9 @@ func (a *agent) apiHandler(aAPI proto.DRPCAgentClient26) (http.Handler, func() e
...
-				agentcontainers.WithManifestInfo(manifest.OwnerName, manifest.WorkspaceName),
-			)
-
-			if len(manifest.Devcontainers) > 0 {
-				containerAPIOpts = append(
-					containerAPIOpts,
-					agentcontainers.WithDevcontainers(manifest.Devcontainers, manifest.Scripts),
-				)
-			}
+		if cAPI := a.containerAPI.Load(); cAPI != nil {
```
Comment (mafredri) [inline agent/api.go]: I imagine there could be a race here? And since this method will only be called once, we would then never correctly set the routes if that happens. Just considering since we saw the race the other way today, but this seems to have worked as intended before.

It would also be good to verify that `cAPI.UpdateSubAgentClient` still gets called in an appropriate location/order considering the refactor.

File: agent/agentcontainers/api.go (hunk 2 above)
Comment (mafredri) [reply agent/agentcontainers/api.go]: I'd like to bump this idea, not critical to get this merged though.

**Review by mafredri — COMMENTED** [review]
Largely looks good, but I still have some concerns with initialization order of the containers API (see comment). Ideally it would be initialized early, like e.g. SSH server, then the race could be avoided.

File: agent/agent.go (hunk 7 above)
Comment (DanielleMaywood) [reply agent/agent.go:1249]: Oops, must've accidentally deleted that field and then forgot to fill it out.

File: agent/agentcontainers/api.go (hunk 2 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api.go]: I'm not entirely sure I understand what the difference would be? What would the `recreate` argument make it do differently?

File: agent/api.go (hunk 8 above)
Comment (DanielleMaywood) [reply agent/api.go]: Quite possibly. I'll need to address updating the `WithManifestInfo` call as we won't have the manifest information yet.

Comment (DanielleMaywood) [reply agent/api.go]: I've given it a go, let me know if I've done anything obviously wrong.

File: agent/agentcontainers/api.go (hunk 2 above)
Comment (mafredri) [reply agent/agentcontainers/api.go]: It would decide whether or not to pass `WithRemoveExistingContainer` to the up command. If not given and the container exists but is stopped, it would simply be started rather than removed and a new created in its place. May allow users to persist fs changes in their devcontainer across workspace restarts.

File: agent/agentcontainers/api.go [hunk 9]
```diff
@@ -315,12 +317,26 @@ func NewAPI(logger slog.Logger, options ...Option) *API {
...
+		case <-api.initialized:
+			go api.watcherLoop()
+			go api.updaterLoop()
+		}
+	}()
 
 	return api
 }
 
+func (api *API) Init(opts ...Option) {
```
Comment (mafredri) [inline agent/agentcontainers/api.go:326]: Suggestion: Document purpose and also special behavior (like must only be called once).

~~An option is also to move watcher/updater start here, which would remove the need for the waiting goroutine in `NewAPI`, but either works.~~ Perhaps better if kept as-is, but just amend the channel closing.

File: agent/agentcontainers/api.go [hunk 10]
```diff
@@ -315,12 +317,26 @@ func NewAPI(logger slog.Logger, options ...Option) *API {
...
 
-	go api.watcherLoop()
-	go api.updaterLoop()
+	go func() {
+		select {
+		case <-api.ctx.Done():
+			break
+		case <-api.initialized:
+			go api.watcherLoop()
+			go api.updaterLoop()
```
Comment (mafredri) [inline agent/agentcontainers/api.go]: An important consideration here is that `Close` is dependent on these functions closing their channels.

File: agent/api.go (hunk 8 above)
Comment (mafredri) [reply agent/api.go]: I think it can work! It's a bit different than what I had in mind but yours is probably better tbh 😄

File: agent/agentcontainers/api.go (hunk 9 above)
Comment (DanielleMaywood) [reply agent/agentcontainers/api.go:326]: Oops I already listened to what you said before crossing it out 😅 I think it does actually simplify things a little but yeah the shutdown scenario might be an issue.

File: agent/agentcontainers/api.go [hunk 11]
```diff
@@ -315,10 +313,22 @@ func NewAPI(logger slog.Logger, options ...Option) *API {
...
 	}
 
+	return api
+}
+
+// Init applies a final set of options to the API and then
+// begins the watcherLoop and updaterLoop. This function
+// must only be called once.
+func (api *API) Init(opts ...Option) {
+	for _, opt := range opts {
```
Comment (mafredri) [inline agent/agentcontainers/api.go:333]: We should grab a mutex lock for this func and check `if api.closed` and return early. Otherwise there's a little assignment/read race between this and Close.

File: agent/agentcontainers/api.go [hunk 12]
```diff
@@ -920,16 +932,32 @@ func (api *API) handleDevcontainerRecreate(w http.ResponseWriter, r *http.Reques
 	})
 }
 
-// recreateDevcontainer should run in its own goroutine and is responsible for
+type CreateBehavior bool
+
+const (
+	CreateBehaviorStart   CreateBehavior = false
+	CreateBehaviorRestart CreateBehavior = true
```
Comment (mafredri) [inline agent/agentcontainers/api.go]: If we want an enum, I'd suggest either int or string. But perhaps an even simpler option would be to just pass the `Up` option(s) directly.

Suggestion if kept: s/Restart/Recreate/ as the former could suggest it does a docker restart on the container rather than remove it.

File: agent/agentcontainers/api.go [hunk 13]
```diff
@@ -920,16 +932,32 @@ func (api *API) handleDevcontainerRecreate(w http.ResponseWriter, r *http.Reques
...
 // incremented before calling this function.
-func (api *API) recreateDevcontainer(dc codersdk.WorkspaceAgentDevcontainer, configPath string) {
+func (api *API) CreateDevcontainer(dc codersdk.WorkspaceAgentDevcontainer, configPath string, behavior CreateBehavior) error {
 	defer api.asyncWg.Done()
 
+	if behavior == CreateBehaviorStart {
+		api.mu.Lock()
+		dc.Status = codersdk.WorkspaceAgentDevcontainerStatusStarting
+		dc.Container = nil
+		api.knownDevcontainers[dc.WorkspaceFolder] = dc
```
Comment (mafredri) [inline agent/agentcontainers/api.go]: I'd suggest two changes:

1. Rather than take `dc` here and assign to `knownContainers` (overwriting `WithDevcontainers`), simply take `workspaceFolder` and `configPath`, if found in knownContainers we take `dc`. If `dc` is not found, we can return an error for now since logging depends on it
2. Moving the `dc.Status` assignment to `WithDevcontainers`, this way all devcontainers will immediately be in the starting phase and reflected as loading in the UI. This is somewhat truthful without introducing a new state like "start queued".

Change 1. would allow this to also be used to start any runtime-detected devcontainer config which we might support in the future (aka. hey we found this, do you want to start it?).

Change 2. simplifies this as we only need to add to asyncWg. Maybe we could add a comment why we only do it for start as well.

**Review by mafredri — COMMENTED** [review]
A few more suggestions but we're real close now, nice work!

File: agent/agentcontainers/api.go [hunk 14]
```diff
@@ -920,16 +941,22 @@ func (api *API) handleDevcontainerRecreate(w http.ResponseWriter, r *http.Reques
...
 // incremented before calling this function.
-func (api *API) recreateDevcontainer(dc codersdk.WorkspaceAgentDevcontainer, configPath string) {
+func (api *API) CreateDevcontainer(workspaceFolder, configPath string, opts ...DevcontainerCLIUpOptions) error {
+	api.asyncWg.Add(1)
 	defer api.asyncWg.Done()
 
+	dc, found := api.knownDevcontainers[workspaceFolder]
+	if !found {
+		return xerrors.Errorf("no devcontainer found")
+	}
```
Comment (mafredri) [inline agent/agentcontainers/api.go:962]: Reading this map and calling `asyncWg.Add` must only be done when the `api.mu` lock is held. This change can work, but right now we can't guarantee that `recreate` increments `asyncWg` _before_ API is closed and thus won't be waited upon.

So we have to:

1. Lock
2. Check if api is closed, if yes, return without incrementing asyncwg
3. Check if dc exists
4. Unlock

**Review by mafredri — APPROVED** [review]
Awesome! Let's try this out in dogfood and if everything seems OK, cherry-pick it in 💪🏻

File: agent/agentcontainers/api.go [hunk 15]
```diff
@@ -920,15 +941,29 @@ func (api *API) handleDevcontainerRecreate(w http.ResponseWriter, r *http.Reques
...
+	api.mu.Lock()
+	if api.closed {
+		api.mu.Unlock()
+		return nil
+	}
+
+	dc, found := api.knownDevcontainers[workspaceFolder]
+	if !found {
+		api.mu.Unlock()
+		return xerrors.Errorf("no devcontainer found")
```
Comment (mafredri) [inline agent/agentcontainers/api.go]:
```suggestion
		return xerrors.Errorf("devcontainer not found")
```
Minor: Just a slightly different signal to not suggest there isn't a single devcontainer.

**Review by mafredri — APPROVED** [review]
