### PR TITLE
fix: never send local endpoints if disabled

### LINKED ISSUE #10791: test flake: scaletest: Test_Runner/NoCleanup: peer is connected directly
Apparently if both peers are on the same net with no endpoints they can still just end up connecting directly.

Seen here: https://github.com/coder/coder/actions/runs/6931328284/job/18852836455?pr=10790

Error:

```
    run_test.go:436: 
        	Error Trace:	/Users/runner/work/coder/coder/scaletest/createworkspaces/run_test.go:436
        	Error:      	Received unexpected error:
        	            	run workspace connections in parallel:
        	            	    github.com/coder/coder/v2/scaletest/createworkspaces.(*Runner).Run
        	            	        /Users/runner/work/coder/coder/scaletest/createworkspaces/run.go:172
        	            	  - run agent connection:
        	            	    github.com/coder/coder/v2/scaletest/createworkspaces.(*Runner).Run.func2
        	            	        /Users/runner/work/coder/coder/scaletest/createworkspaces/run.go:163
        	            	  - check connection mode: peer is connected directly, not via DERP:
        	            	    github.com/coder/coder/v2/scaletest/agentconn.(*Runner).Run
        	            	        /Users/runner/work/coder/coder/scaletest/agentconn/run.go:96
        	Test:       	Test_Runner/NoCleanup
```

https://github.com/coder/coder/blob/main/scaletest/agentconn/run.go#L96
```
	// Ensure DERP for completeness.
	if r.cfg.ConnectionMode == ConnectionModeDerp {
		status := conn.Status()
		if len(status.Peers()) != 1 {
			return xerrors.Errorf("check connection mode: expected 1 peer, got %d", len(status.Peers()))
		}
		peer := status.Peer[status.Peers()[0]]
		if peer.Relay == "" || peer.CurAddr != "" {
			return xerrors.Errorf("check connection mode: peer is connected directly, not via DERP")
		}
	}

```

### PR DESCRIPTION
**Pull request by deansheather**
Endpoints gathered by scanning interfaces on the local computer (i.e. local addresses like `192.168.1.x`) would get sent to peers via Tailscale Disco protocol, even if the server or client forbade sending endpoints with the server/client flags. This prevents sending any endpoints when blocked by the user or admin.

Previously, we only blocked sending endpoints in the coordination protocol and we blocked STUN servers from functioning, but these local IPs could still get sent via Disco.

Closes #10791

### CODE REVIEW

**Review by kylecarbs — COMMENTED** [review]
Is it possible for us to write a test for this?

**Comment by deansheather** [comment]
I can write a test but I don't think it will reliably catch issues. There's no way to force endpoints to update without calling private tailscale methods, so the only way is to sleep and make sure they never appear.

I added multiple thorough tests for the underlying `(*magicsock.Conn).SetBlockEndpoints()` method when I implemented it, which use hidden APIs to settle things quicker.

File: tailnet/conn_test.go [hunk 1]
```diff
@@ -412,9 +413,78 @@ parentLoop:
...
+	// Watch for 10 seconds to ensure that neither peer has any endpoints.
+	// There's no good way to force endpoint updates, so we just wait.
+parentLoop:
+	for {
+		select {
+		case node := <-nodes1:
+			require.Empty(t, node.Endpoints, "conn1 got endpoints")
+		case node := <-nodes2:
+			require.Empty(t, node.Endpoints, "conn2 got endpoints")
+		case <-time.After(testutil.WaitShort):
```
Comment (spikecurtis) [inline tailnet/conn_test.go:466]: timer gets reset each time we go around the loop, so we could wait for much longer than 10 sec.

But, I don't think we add much value by waiting for 10s.  There are unit tests for `tailnet.Conn` blocking endpoints on node updates.  

What wasn't covered prior to this is endpoints discovered via disco.  The status tests you have below cover that.

Comment (deansheather) [reply tailnet/conn_test.go:466]: Oops, yeah I guess I can just remove this section then. I do still think we should wait because we can't force it to gather local endpoints, unless you know a way to test this reliably?

Comment (spikecurtis) [reply tailnet/conn_test.go:466]: we have tests that demonstrate that `tailnet.Conn` won't send endpoint in a Node update callback when blockendpoints is set.

E.g. `TestNodeUpdater_setBlockEndpoints_different`

Where we got the endpoints from (local, STUN, etc) is immaterial.

Comment (deansheather) [reply tailnet/conn_test.go:466]: I removed the node endpoint check but I still think the delay is required unless you know of another way to force disco endpoints to be gathered and sent immediately

**Review by spikecurtis — APPROVED** [review]
