### PR TITLE
fix: clean template destination path for `pull`

### LINKED ISSUE #10281: The coder template pull command fails with a relative path starting with `.`
This works:

```shell
coder template pull mytemplate foo/bar
```

This doesn't, it only creates an empty directory:

```shell
coder template pull mytemplate ./foo/bar
```

Both are valid ways to represent the same path.

### PR DESCRIPTION
**Pull request by dannykopping**
Fixes https://github.com/coder/coder/issues/10281

Cleaning the path and making it absolute causes the path to not be seen as [unsafe by the underlying library](https://github.com/coder/coder/issues/10281#issuecomment-1988553588).

**Note to reviewer:** this PR obviates the need for `TestTemplatePull_ToImplicit`.
It made sense to me to merge them together, but you may want to keep them separate; I'm easy either way.

Side-note: I was testing to see if I could inject problematic template names like `--help` and ended up finding a CLI bug: https://github.com/coder/coder/issues/12575

### CODE REVIEW

File: cli/templatepull.go [hunk 1]
```diff
@@ -130,6 +131,17 @@ func (r *RootCmd) templatePull() *clibase.Cmd {
...
 			}
 
+			clean, err := filepath.Abs(filepath.Clean(dest))
+			if err != nil {
+				cliui.Error(inv.Stderr, fmt.Sprintf("cleaning destination path %s failed: %q", dest, err))
+				return err
+			}
+
+			if dest != clean {
+				cliui.Warn(inv.Stderr, fmt.Sprintf("cleaning destination path from %s to %s", dest, clean))
```
Comment (mtojek) [inline cli/templatepull.go:141]: nit: I wouldn't warn users here, it the tool can fix the path then we don't need to them

File: cli/templatepull_test.go [hunk 2]
```diff
@@ -230,118 +230,93 @@ func TestTemplatePull_LatestStdout(t *testing.T) {
...
+		name      string
+		givenPath string
+	}{
+		{
+			name:      "absolute path works",
+			givenPath: filepath.Join(tmp, "actual"),
+		},
+		{
+			name:      "relative path is cleaned up",
+			givenPath: "./pulltmp",
```
Comment (mtojek) [inline cli/templatepull_test.go:249]: Do we need an extra case for `"."`?

File: cli/templatepull_test.go [hunk 3]
```diff
@@ -230,118 +230,93 @@ func TestTemplatePull_LatestStdout(t *testing.T) {
...
-	ctx := context.Background()
-
-	err = extract.Tar(ctx, bytes.NewReader(expected), expectedDest, nil)
-	require.NoError(t, err)
-
-	inv, root := clitest.New(t, "templates", "pull", template.Name, actualDest)
-	clitest.SetupConfig(t, templateAdmin, root)
-
-	ptytest.New(t).Attach(inv)
+	// Prevents the tests from running in parallel.
```
Comment (mtojek) [inline cli/templatepull_test.go:235]: nit: you may want to add more context here, for instance ... _as the test changes the work dir._

**Review by mtojek — APPROVED** [review]
LGTM, but please wait for review from Mathias 👍

File: cli/templatepull.go [hunk 4]
```diff
@@ -130,6 +131,17 @@ func (r *RootCmd) templatePull() *clibase.Cmd {
 				dest = templateName
 			}
 
+			clean, err := filepath.Abs(filepath.Clean(dest))
+			if err != nil {
+				cliui.Error(inv.Stderr, fmt.Sprintf("cleaning destination path %s failed: %q", dest, err))
+				return err
```
Comment (mafredri) [inline cli/templatepull.go:137]: Could this be an `xerrors.Errorf("lookup of absolute path failed ...: %w")` instead of the manual cliui error call? I'd expect the error to be printed twice this way.

File: cli/templatepull_test.go (hunk 3 above)
Comment (mafredri) [reply cli/templatepull_test.go:235]: Question: Why can't this (parent) test run in parallel with other tests? I saw that the `os.Chdir` is removed, which is why I ask. I understand the subtests may conflict with each other, so at least there it's fine to not have parallel.

Also, whenever you add a nolint, it's good practice to include the why attached to it in the following format (unrelated example):

```
//nolint: paralleltest // Changes the environment.
```

File: cli/templatepull_test.go [hunk 5]
```diff
@@ -230,118 +230,93 @@ func TestTemplatePull_LatestStdout(t *testing.T) {
...
+			// are being sorted correctly.
+			updatedVersion := coderdtest.UpdateTemplateVersion(t, client, owner.OrganizationID, source2, template.ID)
+			_ = coderdtest.AwaitTemplateVersionJobCompleted(t, client, updatedVersion.ID)
+			coderdtest.UpdateActiveTemplateVersion(t, client, template.ID, updatedVersion.ID)
 
-	// create a tempdir and change the working directory to it for the duration of the test (cannot run in parallel)
-	dir := t.TempDir()
-	wd, err := os.Getwd()
-	require.NoError(t, err)
-	err = os.Chdir(dir)
```
Comment (mafredri) [inline cli/templatepull_test.go:319]: How do these tests actually work with chdir removed? The files will be created inside the repo since we're not in the tmpdir, right?

File: cli/templatepull.go (hunk 1 above)
Comment (dannykopping) [reply cli/templatepull.go]: I was thinking this process of cleaning the dir might cause unexpected results, but on reflection I think you're right; I've removed it.

File: cli/templatepull_test.go (hunk 3 above)
Comment (dannykopping) [reply cli/templatepull_test.go:236]: Good points, thanks.

File: cli/templatepull_test.go (hunk 5 above)
Comment (dannykopping) [reply cli/templatepull_test.go:319]: It pulls into the `givenPath`:

```go
inv, root := clitest.New(t, "templates", "pull", template.Name, tc.givenPath)
```

AFAICS it's functionally equivalent

**Review by dannykopping — COMMENTED** [review]
@mafredri @mtojek responded, thank you for your reviews!

File: cli/templatepull_test.go (hunk 5 above)
Comment (mafredri) [reply cli/templatepull_test.go:319]: If the given path is relative, won't it be relative to the Go process, i.e. the test which is running in `coder/cli` directory. Thus it'll store files in there instead of tmp.

Comment (dannykopping) [reply cli/templatepull_test.go:319]: You're correct! I added these two lines to account for that in the last commit:

```go
			newWD := t.TempDir()
			require.NoError(t, os.Chdir(newWD))
```

Comment (mafredri) [reply cli/templatepull_test.go:319]: You also need to restore the wd after the test has ended, otherwise it could break other tests.

Comment (dannykopping) [reply cli/templatepull_test.go:319]: Oooh good point!

File: cli/templatepull_test.go [hunk 6]
```diff
@@ -230,118 +230,111 @@ func TestTemplatePull_LatestStdout(t *testing.T) {
...
-// nolint: paralleltest
-func TestTemplatePull_ToImplicit(t *testing.T) {
-	client := coderdtest.New(t, &coderdtest.Options{
-		IncludeProvisionerDaemon: true,
-	})
-	owner := coderdtest.CreateFirstUser(t, client)
-	templateAdmin, _ := coderdtest.CreateAnotherUser(t, client, owner.OrganizationID, rbac.RoleTemplateAdmin())
+			t.Cleanup(func() {
+				_ = os.RemoveAll(tc.givenPath)
+				_ = os.RemoveAll(expectedDest)
```
Comment (mafredri) [inline cli/templatepull_test.go:285]: We could perhaps combine these and chdir into a single cleanup? Or perhaps even better would be to implement `testutil.Chdir` since it's something we do every now and a then.

**Review by mafredri — COMMENTED** [review]
A few more things but once those are fixed I think this is good to go. Thanks for tackling this issue!

File: cli/templatepull_test.go [hunk 7]
```diff
@@ -230,118 +230,111 @@ func TestTemplatePull_LatestStdout(t *testing.T) {
 
 // ToDir tests that 'templates pull' pulls down the active template
 // and writes it to the correct directory.
+//
+// nolint: tparallel // The subtests cannot be run in parallel; see the inner loop.
 func TestTemplatePull_ToDir(t *testing.T) {
 	t.Parallel()
```
[the remark this answers is not in the document]
Comment (dannykopping) [reply cli/templatepull_test.go:236]: Note that this is [`tparallel`](https://golangci-lint.run/usage/linters/#:~:text=Tparallel%20detects%20inappropriate%20usage%20of%20t.Parallel()%20method%20in%20your%20Go%20test%20codes.) not `paralleltest`.

**Comment by dannykopping** [comment]
@mafredri I took a slightly different approach in https://github.com/coder/coder/pull/12559/commits/a5bb71795a2aebd0fb7f7b9e721bd62886789b3d which is a bit cleaner. Please let me know what you think.

File: cli/templatepull_test.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (mafredri) [reply cli/templatepull_test.go:236]: I wasn't referring to linting. A test that modified the environment of the process (e.g. setenv or chdir) can't be parallel or have parallel ancestors.

[the remark this answers is not in the document]
Comment (dannykopping) [reply cli/templatepull_test.go]: OH you're completely right!

**Review by mafredri — APPROVED** [review]
Found one last simplification, but otherwise LGTM! 😄
