### PR TITLE
fix: stop reporting future licenses as errors

### LINKED ISSUE #14476: Admins have to stay up until midnight to apply a new license
Licenses include a start date, which has to be when a contract begins

To make life easier for Coder admins, can we make it so:

- Licenses can be applied prematurely, but activated during the start date 

OR

- 72 hour period to allow licenses to be applied early

Open to other ideas. Let's collaborate with @ericpaulsen and @ssncoder on this solution

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #14476

Fixes the entitlements processing code so that we don't report existence of "future" licenses as an error, which might alarm admins needlessly.  Downstack PR fixes our API to allow such licenses to be added to the database.

### CODE REVIEW

**Comment by spikecurtis** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/coder/coder/14492?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14492** <a href="https://app.graphite.dev/github/pr/coder/coder/14492?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14491** <a href="https://app.graphite.dev/github/pr/coder/coder/14491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: enterprise/coderd/coderdenttest/coderdenttest.go [hunk 1]
```diff
@@ -199,6 +199,13 @@ func (opts *LicenseOptions) Valid(now time.Time) *LicenseOptions {
 	return opts
 }
 
+func (opts *LicenseOptions) FutureTerm(now time.Time) *LicenseOptions {
+	opts.NotBefore = now.Add(time.Hour * 24)
+	opts.ExpiresAt = now.Add(time.Hour * 24 * 60)
+	opts.GraceAt = now.Add(time.Hour * 24 * 53)
```
Comment (johnstcn) [inline enterprise/coderd/coderdenttest/coderdenttest.go:205]: Would it make sense to use `AddDate()` here?

**Review by johnstcn — APPROVED** [review]

File: enterprise/coderd/license/license.go [hunk 2]
```diff
@@ -100,6 +100,13 @@ func LicensesEntitlements(
 	//   'Entitlements' group as a whole.
 	for _, license := range licenses {
 		claims, err := ParseClaims(license.JWT, keys)
+		var vErr *jwt.ValidationError
+		if xerrors.As(err, &vErr) && vErr.Is(jwt.ErrTokenNotValidYet) {
+			// The license isn't valid yet.  We don't consider any entitlements contained in it, but
+			// it's also not an error.  Just skip it silently.  This can happen if an administrator
+			// uploads a license for a new term that hasn't started yet.
+			continue
+		}
```
Comment (Emyrk) [inline enterprise/coderd/license/license.go:109]: Why not just use `ParseClaimsIgnoreNbf(license.JWT, keys)` instead of `ParseClaims`

Comment (spikecurtis) [reply enterprise/coderd/license/license.go:109]: Because in this context, the license is still invalid: we don't want to process entitlements for terms that haven't started yet. So, I want the Go `error`, but I don't want to log it. `ParseClaimsIngoreNbf` doesn't return an error if `nbf` is violated.

Comment (Emyrk) [reply enterprise/coderd/license/license.go:109]: Ah, makes sense. Feel like we should try to reuse this logic somehow.

**Review by Emyrk — APPROVED** [review]

File: enterprise/coderd/coderdenttest/coderdenttest.go (hunk 1 above)
Comment (spikecurtis) [reply enterprise/coderd/coderdenttest/coderdenttest.go:205]: `AddDate()` is tied to timezones and could be ambiguous around daylight savings switches. Adding hours is not ambiguous.

**Comment by spikecurtis** [comment]
### Merge activity

* **Sep 3, 1:22 AM EDT**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/14492).
