### PR TITLE
fix(site): fix and improve pending state on template editor UI

### LINKED ISSUE #12676: Improve template editor UI when template version build is pending
While a template version is pending the build button is disabled and there is no clue to the user why. Possible solutions:
- Display a build badge close to the build button
- Display a helpful message sharing with the user why the template at that moment can't be built

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Closes https://github.com/coder/coder/issues/12676

https://github.com/coder/coder/assets/3165839/5be6ec59-d3ec-4f7c-a234-4247a452965f

### CODE REVIEW

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx [hunk 1]
```diff
@@ -575,62 +573,58 @@ export const TemplateVersionEditor: FC<TemplateVersionEditorProps> = ({
...
+                    />
+                  ) : (
+                    <Loader css={{ height: "100%" }} />
+                  )}
+                </div>
+              )}
+
+              {selectedTab === "resources" && (
+                <div
+                  css={[{ height: selectedTab ? 280 : 0 }, styles.resources]}
```
Comment (Parkreiner) [inline site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx:617]: Just in case, could the order of the array elements be flipped?

My first thought when I saw this was that I'd have to go through the rest of the code to see if the height was being overridden by `styles.resources`. With the order flipped, it's clear that the height object will always win out

**Review by buenos-nachos — APPROVED** [review]
Looks good! Had one tiny nit for code clarity

File: site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx:617]: Good catch, I can easily refactor this 🙏
