### PR TITLE
fix: skip autostart for suspended/dormant users

### LINKED ISSUE #10597: Workspaces for suspended users are still autostarted
When users are offboarded via SCIM, they enter a "suspended" state.

However, Coder will still honour the configured autostart schedule for these users.

I would expect Coder to not continue autostarting these instances, as they're unlikely to be accessed again.

---

Issue observed on: v2.3.2+1372bf8

### PR DESCRIPTION
**Pull request by coadler**
Fixes #10597

### CODE REVIEW

**Comment by coadler** [comment]
Current dependencies on/for this PR:
* main
  * **PR #10771** <a href="https://app.graphite.dev/github/pr/coder/coder/10771?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/10771?utm_source=stack-comment).

File: coderd/autobuild/lifecycle_executor_test.go [hunk 1]
```diff
@@ -265,6 +265,50 @@ func TestExecutorAutostartNotEnabled(t *testing.T) {
...
+	require.NoError(t, err, "update user status")
+
+	// When: the autobuild executor ticks after the scheduled time
+	go func() {
+		tickCh <- sched.Next(workspace.LatestBuild.CreatedAt)
+		close(tickCh)
+	}()
+
+	// Then: nothing should happen
+	stats := <-statsCh
```
Comment (sreya) [inline coderd/autobuild/lifecycle_executor_test.go:307]: i think spike recently merged a helper in `testutil` so that you can select on this + a ctx with a timeout so we don't have to wait 10 mins if this ever messes up for whatever reason.

File: coderd/autobuild/lifecycle_executor_test.go [hunk 2]
```diff
@@ -265,6 +265,50 @@ func TestExecutorAutostartNotEnabled(t *testing.T) {
 	require.Len(t, stats.Transitions, 0)
 }
 
+func TestExecutorAutostartUserSuspended(t *testing.T) {
+	t.Parallel()
+
+	var (
+		ctx     = context.Background()
```
Comment (sreya) [inline coderd/autobuild/lifecycle_executor_test.go:272]: `testutil.Context`

**Review by sreya — APPROVED** [review]
