### PR TITLE
fix: fix --header flag in CLI

### LINKED ISSUE #8021: `--header` format changed in recent version, must be colon delimited now
https://github.com/coder/coder/commit/43eee35ae8c974be02ea06da6707270623acb871 introduces https://github.com/gobwas/httphead for HTTP header parsing.

However, `httphead` uses colon-delimited key-value pairs, rather than `=`: https://github.com/gobwas/httphead/blob/935b70b38dcb69f249f00f338774bf75822c090a/head.go#L185

This is a breaking change and not reflected in the CLI options:
```
      --header string-array, $CODER_HEADER
          Additional HTTP headers added to all requests. Provide as key=value. Can be specified multiple times.
```

Earlier versions of the Coder CLI supported `--header=key=value`. Now it must be `--header=key:value`.

```
➜  coder login --header=foo=bar
invalid header: foo=bar
➜  coder login --header=foo:bar
Open the following in your browser:

        https://coder.foobar.com/cli-auth

> Paste your token here: 
```

### PR DESCRIPTION
**Pull request by deansheather**
The `--header` flag was changed from `key=value` to `key:value` in https://github.com/coder/coder/commit/43eee35ae8c974be02ea06da6707270623acb871 which is a breaking change.

This PR reverts the behavior to `key=value` as there doesn't seem to be a good reason for the breaking change.

The `ExtraHeaders` field is removed from `codersdk.Client` to match the prior behavior and to reduce the amount of ways headers can be set in the SDK to avoid confusion.

This regression would've been caught by an existing test, but the test was faulty and didn't catch the issue. The test has been fixed and improved, and a test has been added to make sure headers are sent to the DERP server to avoid breaking https://github.com/coder/coder/pull/6572.

Fixes #8021
Fixes https://github.com/coder/v2-customers/issues/203

### CODE REVIEW

File: cli/root.go [hunk 1]
```diff
@@ -430,6 +427,15 @@ type RootCmd struct {
 }
 
 func addTelemetryHeader(client *codersdk.Client, inv *clibase.Invocation) {
+	transport, ok := client.HTTPClient.Transport.(*headerTransport)
+	if !ok {
+		transport = &headerTransport{
```
Comment (mafredri) [inline cli/root.go:432]: I'm a bit worried about losing headers in a situation where we think it's safe to wrap the transport and we end up with a type that's `headerTransport(otherTransport(headerTransport))`. Not sure what the best approach to guard against this would be, though.

**Review by mafredri — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]
