### PR TITLE
fix(cli): fix flakes related to context cancellation when establishing pg connections

### LINKED ISSUE #672: flake: TestServer/Logging fails with `no rows returned for version select`
Seen here: https://github.com/coder/coder/actions/runs/15461129890/job/43522552318

```
=== FAIL: cli TestServer/Logging/CreatesFile (2.82s)
    clitest.go:75: invoking command: coder --global-config /var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/TestServerLoggingCreatesFile2486680519/002 server --log-filter=.* --postgres-url=***127.0.0.1:5432/test_2025_06_05_07_35_16_jxjvtgijva?sslmode=disable --http-address :0 --access-url http://example.com/ --provisioner-daemons=3 --provisioner-types=echo --log-human /var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/TestServerLoggingCreatesFile2486680519/001/coder-logging-test-1008095851
    t.go:106: 2025-06-05 07:35:16.826 [debu]  cli: started debug logging
    t.go:106: 2025-06-05 07:35:16.826 [info]  cli: stdout: Started HTTP listener at http://[::]:51869
    t.go:106: 2025-06-05 07:35:16.826 [info]  cli: ...
        msg= stdout: ╔════════════════════════╗
             ║    View the Web UI:    ║
             ║   http://example.com/   ║
             ╚════════════════════════╝
    t.go:106: 2025-06-05 07:35:16.826 [debu]  cli: connecting to postgresql
    t.go:106: 2025-06-05 07:35:16.904 [debu]  cli: closing tracing
    t.go:106: 2025-06-05 07:35:16.904 [debu]  cli: tracing closed  error=<nil>
    clitest.go:261: command "coder server" exited with error: running command "coder server": connect to postgres:
            github.com/coder/coder/v2/cli.(*RootCmd).Server.func2
                /Users/runner/work/coder/coder/cli/server.go:754
          - connect to postgres:
            github.com/coder/coder/v2/cli.getAndMigratePostgresDB
                /Users/runner/work/coder/coder/cli/server.go:2882
          - no rows returned for version select:
            github.com/coder/coder/v2/cli.ConnectToPostgres
                /Users/runner/work/coder/coder/cli/server.go:2363
    clitest.go:172: 
        	Error Trace:	/Users/runner/work/coder/coder/cli/clitest/clitest.go:172
        	            				/Users/runner/work/_tool/go/1.24.2/arm64/src/runtime/asm_arm64.s:1223
        	Error:      	Received unexpected error:
        	            	running command "coder server": connect to postgres:
        	            	    github.com/coder/coder/v2/cli.(*RootCmd).Server.func2
        	            	        /Users/runner/work/coder/coder/cli/server.go:754
        	            	  - connect to postgres:
        	            	    github.com/coder/coder/v2/cli.getAndMigratePostgresDB
        	            	        /Users/runner/work/coder/coder/cli/server.go:2882
        	            	  - no rows returned for version select:
        	            	    github.com/coder/coder/v2/cli.ConnectToPostgres
        	            	        /Users/runner/work/coder/coder/cli/server.go:2363
        	Test:       	TestServer/Logging/CreatesFile
        --- FAIL: TestServer/Logging/CreatesFile (2.82s)
```

### PR DESCRIPTION
**Pull request by hugodutka**
Since https://github.com/coder/coder/pull/18195 was merged, we started running CLI tests with postgres instead of just dbmem. This surfaced errors related to context cancellation while establishing postgres connections.

This PR should fix https://github.com/coder/internal/issues/672. Related to https://github.com/coder/coder/issues/15109.

### CODE REVIEW

File: cli/clitest/clitest.go [hunk 1]
```diff
@@ -168,6 +168,11 @@ func StartWithAssert(t *testing.T, inv *serpent.Invocation, assertCallback func(
 		switch {
 		case errors.Is(err, context.Canceled):
 			return
+		case err != nil && strings.Contains(err.Error(), "driver: bad connection"):
+			// When a test exits it cancels the context. If a transaction is open
+			// and a query is being executed, instead of a context.Canceled error
+			// we get a "driver: bad connection" error.
+			return
```
Comment (johnstcn) [inline cli/clitest/clitest.go]: Wouldn't exiting with an open transaction be bugged behaviour? Could this mask someone forgetting to close a connection?

Comment (hugodutka) [reply cli/clitest/clitest.go]: Hmm, I should probably make the comment clearer. It should be

> When we cancel the context on a query that's being executed within a transaction, sometimes, instead of a context.Canceled error we get a "driver: bad connection" error.

I don't think this could mask someone forgetting to close a connection. I suppose it might mask someone closing a connection while a transaction is being executed? I'm not sure how the database would handle this scenario.

Comment (hugodutka) [reply cli/clitest/clitest.go]: seems to also be reported here: https://github.com/lib/pq/issues/1137

**Review by johnstcn — APPROVED** [review]
