### PR TITLE
fix: fix loss of buffered input on cliui.Prompt

### LINKED ISSUE #203: cliui.Prompt can drop input on validation errors
`cliui.Prompt()` uses a _buffered_ reader to read until the first newline to capture one "line" of input from terminal user.

However, if the input fails validation, it re-entrantly calls `Prompt()` to ask the user for more input.  If the original buffered reader has read and buffered some input after the newline, this input is lost and inaccessible to the new `Prompt()` call.

I believe this is the root cause of errors like this in our validation test: https://github.com/coder/coder/actions/runs/11681622439/job/32527173007

This is a legit bug in our product, but it is unlikely to come up in normal human use of the CLI, since the missing input would have to be available immediately after the newline. That's why I've raised this in coder/internal instead of coder/coder. It could still plausibly come up if someone is interacting with our CLI via an `expect`-style library, but I would hope our flag options generally make that unnecessary.

We should still fix it for the sake of test flakes.

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes https://github.com/coder/internal/issues/203

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#15421** <a href="https://app.graphite.dev/github/pr/coder/coder/15421?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spikecurtis and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: cli/cliui/prompt.go [hunk 1]
```diff
@@ -179,3 +178,29 @@ func promptJSON(reader *bufio.Reader, line string) (string, error) {
...
+// before the error and the error itself (often io.EOF). readUntil returns err != nil if and only if
+// the returned data does not end in delim.
+func readUntil(r io.Reader, delim byte) (string, error) {
+	var (
+		have []byte
+		b    = make([]byte, 1)
+	)
+	for {
+		n, err := r.Read(b)
+		if n > 0 {
```
Comment (mtojek) [inline cli/cliui/prompt.go:194]: Minor note: since `r.Read` blocks until it receives content or encounters an error, could this be restructured perhaps as follows?

```
	for {
		_, err := r.Read(b)
		if err != nil {
			return string(have), err
		}
		have = append(have, b[0])
		if b[0] == delim {
			return string(have), nil
		}
	}
```

**Review by mtojek — APPROVED** [review]

File: cli/cliui/prompt.go (hunk 1 above)
Comment (spikecurtis) [reply cli/cliui/prompt.go:194]: from the docs for `io.Reader.Read`

> When Read encounters an error or end-of-file condition after successfully reading n > 0 bytes, it returns the number of bytes read. It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call. An instance of this general case is that a Reader returning a non-zero number of bytes at the end of the input stream may return either err == EOF or err == nil. The next Read should return 0, EOF.
>
> **Callers should always process the n > 0 bytes returned before considering the error err.** Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.

(emphasis mine)
