### PR TITLE
fix: properly convert max port share level for oss

### LINKED ISSUE #13259: public port sharing not available on OSS deployment
From https://github.com/coder/coder/issues/11486#issuecomment-2101178378

> @kylecarbs the feature allows admins to restrict the maximum sharing level of ports in the template settings. If you're on our dev template the maximum sharing level is Authenticated.
> 
> We could add a tooltip if this is unclear.
> 
> @stirby What do you mean by "If you're on our dev template"?
> 
> I'm on an OSS deployment, upgraded from v2.10.2 to v2.11.0 today, and am seeing the same thing as @kylecarbs: "public" option is greyed out.
> 
> In the workspace settings, the "Public" option is pre-selected and unmodifiable, as expected.
> 
> The [documentation on port forwarding](https://coder.com/docs/v2/latest/networking/port-forwarding) says:
> 
> OSS deployments allow all workspaces to share ports at both the authenticated and public levels.
> 
> I can't seem to find a way to enable public port sharing via the port helper.

I've started a OSS deployment and I see the issue described:
image

### PR DESCRIPTION
**Pull request by f0ssel**
Closes https://github.com/coder/coder/issues/13259

In the database we default to `owner` for the max port sharing level for existing and new templates. In OSS, the only valid option is `public` because changing max port share level is an enterprise feature. This change ensures we always return `public` for OSS and return the db value for Enterprise.

### CODE REVIEW

File: coderd/portsharing/portsharing.go [hunk 1]
```diff
@@ -10,6 +10,7 @@ import (
 type PortSharer interface {
```
Comment (kylecarbs) [inline coderd/portsharing/portsharing.go:10]: We should remove PortSharing from all of these interface function names.

**Review by kylecarbs — APPROVED** [review]

File: coderd/portsharing/portsharing.go (hunk 1 above)
Comment (f0ssel) [reply coderd/portsharing/portsharing.go:10]: Sure thing
