### PR TITLE
fix: Enable `goleak` for `cli` tests

### LINKED ISSUE #3221: Fix issues reported by `goleak` in `cli` package tests and then enable `goleak`
As per the title, we have not had `goleak` enabled for CLI tests. We should turn it on and work through each test that is causing leaks to be reported with the final goal of permanently enabling `goleak`.

### PR DESCRIPTION
**Pull request by mafredri**
This PR enables `goleak` checking for `cli` commands. This should be worhwile to detect potential leaks caused by long-running commands like `coder server`, maybe others.

Merging is currently blocked until these PRs are merged (or we switch to forks):

- [ ] https://github.com/hashicorp/hc-install/pull/68
- [ ] https://github.com/pion/udp/pull/73

Closes #3221

### CODE REVIEW

File: cli/root_internal_test.go [hunk 1]
```diff
@@ -67,7 +67,11 @@ func Test_formatExamples(t *testing.T) {
 }
 
 func TestMain(m *testing.M) {
-	// Replace with goleak.VerifyTestMain(m) when we enable goleak.
-	os.Exit(m.Run())
-	// goleak.VerifyTestMain(m)
+	goleak.VerifyTestMain(m,
+		// The lumberjack library is used by by agent and seems to leave
+		// goroutines after Close(), fails TestGitSSH tests.
+		// https://github.com/natefinch/lumberjack/pull/100
```
Comment (kylecarbs) [inline cli/root_internal_test.go:73]: Should we do a go mod replace instead?

**Review by kylecarbs — APPROVED** [review]

File: cli/root_internal_test.go (hunk 1 above)
Comment (mafredri) [reply cli/root_internal_test.go:73]: TBH I haven't done a proper review of that PR, and I'm not confident in using it in a production environment without doing so. My judgement was that this is a non-issue in a production environment since the agent only runs once and thus won't be leaking memory, so I think the goleak ignore is acceptable here.

Comment (kylecarbs) [reply cli/root_internal_test.go:73]: Makes sense! TY sir
