### PR TITLE
fix(site): fix react state violation in filetree create/update utils

### LINKED ISSUE #20482: Unable to create new file in template editor in react development mode
In the `CreateFileDialog` component, we appear to have mutation happening on the `setFileTree` setter.

https://github.com/coder/coder/blob/b89093031e0fb3c78c598ddabec767a0660dded8/site/src/pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx#L390

We can see the mutation happening in the `createFile` function with `set` from lodash.

https://github.com/coder/coder/blob/b89093031e0fb3c78c598ddabec767a0660dded8/site/src/utils/filetree.ts#L23

My understanding is that you aren't supposed to perform mutation on a React state value, so in Strict mode it'll call this function twice to see if you're violating this contract. As we're violating this contract, it gets called twice, and on that second invocation `fileTree` will contain the new file, and throw an error because the file already exists.

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Closes https://github.com/coder/coder/issues/20482

Ensure file tree utils don't modify their parameters so we don't violate Reacts rules

### CODE REVIEW

**Review by BrunoQuaresma — COMMENTED** [review]
That is interesting. Could we create a test for that? To make sure we don't have any regressions in the future?

File: site/src/utils/filetree.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const createFile = (
 		throw new Error(pathError);
 	}
 
-	return set(fileTree, path.split("/"), value);
+	return set(path.split("/"), value)(fileTree);
```
Comment (buenos-nachos) [inline site/src/utils/filetree.ts]: I get the benefits of opting for the FP version, especially since it handles immutability out of the box, but I'm worried about bringing new conventions into the codebase without having any conversations about them first

The rest of the codebase leans into a lot more vanilla JS-based patterns, and while currying like this works just fine, I'm worried about consistency

Comment (buenos-nachos) [reply site/src/utils/filetree.ts]: I'd be leaning towards making a copy of the value using traditional JS methods, and then using the vanilla Lodash `set` method on that

**Review by buenos-nachos — COMMENTED** [review]
The change itself is right – I'm just worried about what the style of change means for the larger codebase

File: site/src/utils/filetree.ts (hunk 1 above)
Comment (DanielleMaywood) [reply site/src/utils/filetree.ts]: Yeah I'm more than happy to do that 👍

**Comment by DanielleMaywood** [comment]
@BrunoQuaresma I've added a test to verify the `createFile`, `updateFile`, and `removeFile` functions to not modify the incoming `FileTree`.

@Parkreiner I've replaced the usage of `lodash/fp/set` with `lodash/cloneDeep` and `lodash/set`. Plus fixed a flawed shallow clone in the `removeFile` function.

File: site/src/utils/filetree.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
+import cloneDeep from "lodash/cloneDeep";
```
Comment (aslilac) [inline site/src/utils/filetree.ts]: instead of `cloneDeep` we should use [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone)

Comment (DanielleMaywood) [reply site/src/utils/filetree.ts]: Addressed in https://github.com/coder/coder/pull/20483/commits/416b55c78f5b48f679fe8d11a408b08c0d0da15a

**Review by aslilac — APPROVED** [review]
