### PR TITLE
fix: use dynamic parameter resolution in the cli

### LINKED ISSUE #19879: FR: CLI parameter resolver fails for dynamic parameters while API works fine
## Environment

**Component**: Coder CLI  
**Version**: v2.25.2  
**File**: [`cli/parameterresolver.go#L233`](https://github.com/coder/coder/blob/main/cli/parameterresolver.go#L233)  

## Summary

The CLI's parameter resolver rejects **dynamic parameters** (using `count` conditions) when creating workspaces, even though the same parameters work perfectly via API calls.  
This breaks CLI/pipeline workflows for templates with dynamic parameters.
Coder Docs may indicate that creating Workspaces with the CLI should work.
This primarily affects users who want to automate the 'coder create' command, i.e. CI/CD etc.

## Expected Behavior

```bash
coder create --template test test-ws --rich-parameter-file param.yml
```

A simple alternative would be to generate an error message explaining the disparity or Beta status when Dynamic Parameters are detected and cause errors.

## Workaround

- Use the API
- Create Workspaces in the UI

``` bash
# Get template ID
TEMPLATE_ID=$(coder templates list --output json | jq -r ".[] | select(.name == \"$TEMPLATE\") | .id")

# Convert YAML to JSON
PARAMS=$(yq eval '. | to_entries | map({"name": .key, "value": .value | tostring})' param.yml -o json)

# Create via API
curl -X POST "$CODER_URL/api/v2/users/me/workspaces" \
  -H "Coder-Session-Token: $CODER_SESSION_TOKEN" \
  -H "Content-Type: application/json" \
  --data "{\"name\":\"$WORKSPACE\",\"rich_parameter_values\":$PARAMS,\"template_id\":\"$TEMPLATE_ID\"}"
```

## Expected Resolution

The CLI should successfully create and start a Workspace, where it can evaluate dynamic parameters using provided parameter values, matching the behaviour of the API and UI.

## Related Issues

#19754 – Dynamic Parameters: local module path cannot be resolved
#19789 – Template parsing error when using count with module outputs

### PR DESCRIPTION
**Pull request by Emyrk**
Closes https://github.com/coder/coder/issues/19879

# What this does

Uses dynamic parameters `EvaluateTemplateVersion` vs `TemplateVersionRichParameters` to determine initial parameter state.

This is still not perfect, as dynamic templates are reactive. So if the cli prompts the user for a value, that value can change another parameter. So to fix this holistically, we need fundamentally redesign the parameter logic in the cli to be in a loop. The ux for that is not obvious though, as you might have to re-prompt the user for things they already decided?

For now, this is a stop gap. This handles if the initial parameters are dynamic based on initial inputs (initial args & user context)

### Core Logic (`cli/create.go`)
- Added `Owner` field to `prepWorkspaceBuildArgs` to support dynamic parameter evaluation
- Modified `prepWorkspaceBuild` to check `template.UseClassicParameterFlow` and conditionally use either:
  - **Classic flow**: `client.TemplateVersionRichParameters()` (existing behavior)
  - **Dynamic flow**: `client.EvaluateTemplateVersion()` with initial parameter values from CLI inputs

### Parameter Resolution (`cli/parameterresolver.go`)
- Added `InitialValues()` method to gather CLI-provided parameter values (from flags, files, presets, last build, etc.) **without** validating against template parameters. This is required to initialize any dynamic elements of a template off the original input.

### CODE REVIEW

**Comment by Emyrk** [comment]
* **#21734** <a href="https://app.graphite.com/github/pr/coder/coder/21734?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/coder/21734?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#21732** <a href="https://app.graphite.com/github/pr/coder/coder/21732?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#21733** <a href="https://app.graphite.com/github/pr/coder/coder/21733?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: cli/create_test.go [hunk 1]
```diff
@@ -24,6 +24,317 @@ import (
...
+		  type         = "string"
+		  # No default - this makes it required when it appears
+		}
+	`
+
+	// Test conditional parameters: a parameter that only appears when another
+	// parameter has a certain value.
+	t.Run("ConditionalParam", func(t *testing.T) {
+		t.Parallel()
+		owner := coderdtest.New(t, &coderdtest.Options{IncludeProvisionerDaemon: true})
```
Comment (johnstcn) [inline cli/create_test.go]: Could we share a single `coderdtest` instance between these sub-tests?

File: cli/create_test.go [hunk 2]
```diff
@@ -24,6 +24,317 @@ import (
...
+		pty = ptytest.New(t).Attach(inv)
+
+		doneChan = make(chan error)
+		go func() {
+			doneChan <- inv.Run()
+		}()
+
+		pty.ExpectMatch("has been created")
+
+		err = <-doneChan
```
Comment (johnstcn) [inline cli/create_test.go]: suggest testutil.RequireReceive

File: cli/create_test.go [hunk 3]
```diff
@@ -24,6 +24,317 @@ import (
...
+		inv, root := clitest.New(t, args...)
+		clitest.SetupConfig(t, member, root)
+		pty := ptytest.New(t).Attach(inv)
+
+		doneChan := make(chan error)
+		go func() {
+			doneChan <- inv.Run()
+		}()
+
+		pty.ExpectMatch("has been created")
```
Comment (johnstcn) [inline cli/create_test.go]: suggest: ExpectMatchContext

File: cli/create.go [hunk 4]
```diff
@@ -574,6 +582,46 @@ func prepWorkspaceBuild(inv *serpent.Invocation, client *codersdk.Client, args p
...
+
+		eval, err := client.EvaluateTemplateVersion(ctx, templateVersion.ID, ownerID, initial)
+		if err != nil {
+			return nil, xerrors.Errorf("evaluate template version dynamic parameters: %w", err)
+		}
+
+		for _, param := range eval.Parameters {
+			templateVersionParameters = append(templateVersionParameters, param.TemplateVersionParameter())
+		}
+	}
```
Comment (johnstcn) [inline cli/create.go:622]: This might be worth extracting into its own method.

File: cli/create_test.go (hunk 1 above)
Comment (Emyrk) [reply cli/create_test.go]: Yea, I'll do that :+1:

File: cli/create.go (hunk 4 above)
Comment (Emyrk) [reply cli/create.go:622]: There is just so many local variables being used :cry:

File: cli/parameterresolver.go [hunk 5]
```diff
@@ -180,7 +192,26 @@ nextEphemeralParameter:
 	return resolved
 }
 
-func (pr *ParameterResolver) resolveWithLastBuildParameters(resolved []codersdk.WorkspaceBuildParameter, templateVersionParameters []codersdk.TemplateVersionParameter) []codersdk.WorkspaceBuildParameter {
+func (pr *ParameterResolver) resolveWithLastBuildParameters(resolved []codersdk.WorkspaceBuildParameter) []codersdk.WorkspaceBuildParameter {
+	if pr.promptRichParameters {
```
Comment (johnstcn) [inline cli/parameterresolver.go:196]: Calling `resolveWithLastBuildParameters` in this case feels like a logic error? Nevertheless I'm OK with short-circuiting here.

File: provisioner/terraform/testdata/resources/devcontainer/converted_state.state.golden [hunk 6]
```diff
@@ -24,15 +24,13 @@
             {
               "workspace_folder": "/workspace1",
               "name": "dev1",
-              "id": "eb9b7f18-c277-48af-af7c-2a8e5fb42bab",
-              "subagent_id": "72d17819-ea3b-450a-a502-175886583ecf"
```
Comment (johnstcn) [inline provisioner/terraform/testdata/resources/devcontainer/converted_state.state.golden:28]: I don't think this change is relevant, see also L35 below.

File: cli/create.go [hunk 7]
```diff
@@ -574,6 +582,46 @@ func prepWorkspaceBuild(inv *serpent.Invocation, client *codersdk.Client, args p
...
+	} else {
+		var ownerID uuid.UUID
+		{ // Putting in its own block to limit scope of owningMember, as it might be nil
+			owningMember, err := client.OrganizationMember(ctx, templateVersion.OrganizationID.String(), args.Owner)
+			if err != nil {
+				// This is unfortunate, but if we are an org owner, then we can create workspaces
+				// for users that are not part of the organization.
+				owningUser, uerr := client.User(ctx, args.Owner)
+				if uerr != nil {
+					// Return the original member
```
Comment (johnstcn) [inline cli/create.go]: nit: that's not what we do though?

**Review by johnstcn — APPROVED** [review]

File: cli/create.go (hunk 7 above)
Comment (Emyrk) [reply cli/create.go]: Whoops.

File: cli/parameterresolver.go (hunk 5 above)
Comment (Emyrk) [reply cli/parameterresolver.go:196]: I don't follow what you are saying :thinking:

File: provisioner/terraform/testdata/resources/devcontainer/converted_state.state.golden (hunk 6 above)
Comment (Emyrk) [reply provisioner/terraform/testdata/resources/devcontainer/converted_state.state.golden:28]: This is strange. I just rebased it, and make gen did this. I assumed I missed something on `main`. Looking into it

File: cli/parameterresolver.go (hunk 5 above)
Comment (johnstcn) [reply cli/parameterresolver.go:196]: Why call this function at all if we know ahead of time that we don't want to fetch parameters from the last build?

Comment (Emyrk) [reply cli/parameterresolver.go:196]: Ah, I see. Do you mean instead to write it as:
```golang
	if !pr.promptRichParameters {
		staged = pr.resolveWithLastBuildParameters(staged)
	}
```

instead? 

If so, I'm not changing to code pattern, I just moved some existing code around

Comment (johnstcn) [reply cli/parameterresolver.go:196]: Perhaps; the flow just seemed weird to me. Not a blocker in any case.

Comment (Emyrk) [reply cli/parameterresolver.go:196]: The parameter resolution code is a bit tangled imo. I wanted to avoid trying to untangle it, and just update it to use the dynamic param resolver instead of the static.
