### PR TITLE
fix(coderd): Ensure agent disconnect happens after timeout

### LINKED ISSUE #6598: skip tests: scaletest/reconnectingpty Test_Runner
I can't make 5 consecutive PR runs without this failure, so disabling the runner.

```
run_test.go:128: Runner logs:
        
        Opening reconnecting PTY connection to agent via coderd...
        	ID:      cdc30c01-34ec-41c6-93a3-a3a967b5930f
        	Width:   80
        	Height:  24
        	Command: "sleep 120"
        
        
    run_test.go:130: 
        	Error Trace:	/Users/runner/work/coder/coder/scaletest/reconnectingpty/run_test.go:130
        	Error:      	Target error should be in err chain:
        	            	expected: "context deadline exceeded"
        	            	in chain: "open reconnecting PTY: GET http://localhost:61013/api/v2/workspaceagents/99e51b2f-f932-4174-95f5-e79c836935a6/pty?command=sleep+120&height=80&reconnect=cdc30c01-34ec-41c6-93a3-a3a967b5930f&width=24: unexpected status code 400: Agent state is \"disconnected\", it must be in the \"connected\" state."
        	            		"GET http://localhost:61013/api/v2/workspaceagents/99e51b2f-f932-4174-95f5-e79c836935a6/pty?command=sleep+120&height=80&reconnect=cdc30c01-34ec-41c6-93a3-a3a967b5930f&width=24: unexpected status code 400: Agent state is \"disconnected\", it must be in the \"connected\" state."
        	Test:       	Test_Runner/Timeout/Timeout
```

Job: https://github.com/coder/coder/actions/runs/4414473932/jobs/7737086635

### PR DESCRIPTION
**Pull request by mafredri**
Fixes #6598

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

File: coderd/coderd.go [hunk 1]
```diff
@@ -175,6 +175,10 @@ func New(options *Options) *API {
 	if options.AgentInactiveDisconnectTimeout == 0 {
 		// Multiply the update by two to allow for some lag-time.
 		options.AgentInactiveDisconnectTimeout = options.AgentConnectionUpdateFrequency * 2
+		// Set a minimum timeout to avoid disconnecting too soon.
+		if options.AgentInactiveDisconnectTimeout < 2*time.Second {
```
Comment (mtojek) [inline coderd/coderd.go:179]: > 2*time.Second

Interesting, doesn't `make fmt` complain about it?

**Review by mtojek — APPROVED** [review]

File: coderd/coderd.go (hunk 1 above)
Comment (mafredri) [reply coderd/coderd.go:179]: This is actually fmt's handiwork. It groups operands when there are multiple operators.

Comment (mtojek) [reply coderd/coderd.go:179]: TIL!
