### PR TITLE
fix(site): fix terminal size when displaying alerts

### LINKED ISSUE #7914: Web terminal notification for "Startup script failed" does not account for terminal size
image

It seems the notification banner is throwing off the terminal size and showing content outside the window (depending on window size).

The terminal status bar at the bottom also seems to disappear with this notification, but not with the "startup script is still running" one.

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Before - The terminal size does not fit the available space so the bottom is hidden.

https://github.com/coder/coder/assets/3165839/d08470b9-9fc6-476c-a551-8a3e13fc25bf

After - The terminal adjusts when there are alert changes.

https://github.com/coder/coder/assets/3165839/8cc32bfb-056f-47cb-97f2-3bb18c5fe906

Unfortunately, I don't think there is a sane way to automate tests for this but open to suggestions.

Close https://github.com/coder/coder/issues/7914

### CODE REVIEW

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 1]
```diff
@@ -328,6 +328,73 @@ const TerminalPage: FC = () => {
...
+    if (!wrapperRef.current) {
+      return;
+    }
+    const observer = new MutationObserver(onAlertChange);
+    observer.observe(wrapperRef.current, { childList: true });
+
+    return () => {
+      observer.disconnect();
+    };
+  }, [onAlertChange]);
```
Comment (code-asher) [inline site/src/pages/TerminalPage/TerminalPage.tsx:369]: Would it be possible to just always call `fit()` when this component re-renders instead of using an observer?  Since ideally the component only renders again when the alert changes.

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 2]
```diff
@@ -328,6 +328,73 @@ const TerminalPage: FC = () => {
...
+    prevLifecycleState.current = lifecycleState;
+  }, [lifecycleState]);
+
+  // Mock state
+  const [displayAlert, setDisplayAlert] = useState(false);
+  useEffect(() => {
+    setTimeout(() => {
+      setDisplayAlert(true);
+    }, 1_000);
+  }, []);
```
Comment (code-asher) [inline site/src/pages/TerminalPage/TerminalPage.tsx:354]: Left over from testing?

File: site/src/pages/TerminalPage/TerminalPage.tsx [hunk 3]
```diff
@@ -328,6 +328,73 @@ const TerminalPage: FC = () => {
...
+        <div css={{ height: 500, backgroundColor: "red" }}>
+          Some big element here
+          <button
+            onClick={() => {
+              setDisplayAlert(false);
+            }}
+          >
+            Close
+          </button>
+        </div>
```
Comment (code-asher) [inline site/src/pages/TerminalPage/TerminalPage.tsx:383]: Left over from testing?

**Comment by code-asher** [comment]
A comment about testing, since we have the story now, maybe we can just output more than a screen's worth of text, since with the bug it would render differently than without it, so it should catch this issue.

**Comment by code-asher** [comment]
Or we output some ANSI sequence that writes text to the bottom of the screen.

**Comment by mafredri** [comment]
@BrunoQuaresma for testing, maybe you can write an escape sequence to the terminal that will write something at the bottom?

For example, the following escape sequence would write to the bottom left and right corners of the terminal: `\33[1000BLEFT\33[1000C\33[4DRIGHT`

image

Then you can test if the output is visible?

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/TerminalPage/TerminalPage.tsx:369]: This is a good question and the why this does not work is that the `.fit()` needs to run after the render so in this case, I just think the mutation observer is more reliable. I could use some hacky `setTimeout` inside of `useEffect` to do that, I guess, but I don't think it would be any better. Wdyt?

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 2 above)
Comment (BrunoQuaresma) [reply site/src/pages/TerminalPage/TerminalPage.tsx:354]: Lol, yes

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/TerminalPage/TerminalPage.tsx:369]: PS: I'm going to add this as a comment so we remember the "why" of this decision.

**Comment by BrunoQuaresma** [comment]
@mafredri @code-asher good suggestion, I didn't know there was a way to do that. I was just copying and pasting the websocket messages from the terminal. 

@mafredri how do you know how to do that? I would add it to my LinkedIn like "Languages: English, ANSI"

**Comment by BrunoQuaresma** [comment]
@code-asher @mafredri just confirming your suggestion worked! 🙏

**Comment by mafredri** [comment]
> @mafredri how do you know how to do that? I would add it to my LinkedIn like "Languages: English, ANSI"

Haha, I will consider it 😉. TBH it was trial and error, I remembered that it was ~ `ESC[#X`, then I just tried the letters ABCD and saw what happened (I could've just looked it up lol.) Essentially we're moving 1000 blocks in each direction which means we'll hit a wall and stay at the edge, when we do the right one we also go 1000 blocks and then backtrack a few so we have space to output the text. 😄

This looks like a pretty solid intro if you're interested: https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#cursor-controls

File: site/src/pages/TerminalPage/TerminalPage.tsx (hunk 1 above)
Comment (code-asher) [reply site/src/pages/TerminalPage/TerminalPage.tsx]: Ohhh right that makes sense!  Yeah you are right, this is better.

File: site/src/pages/TerminalPage/TerminalPage.stories.tsx [hunk 4]
```diff
@@ -142,3 +142,27 @@ export const ConnectionError: Story = {
...
+  parameters: {
+    ...meta.parameters,
+    // Forcing smaller viewport to make it easier to identify the issue
+    viewport: {
+      defaultViewport: "terminal",
+    },
+    webSocket: [
+      {
+        event: "message",
+        // Copied and pasted this from browser
```
Comment (code-asher) [inline site/src/pages/TerminalPage/TerminalPage.stories.tsx:159]:
```suggestion
        // This outputs text in the bottom left and right corners of the terminal.
```

**Review by code-asher — APPROVED** [review]
Perfect!

**Comment by BrunoQuaresma** [comment]
### Merge activity

* **Mar 8, 5:38 AM EST**: @BrunoQuaresma merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/12444).
