### PR TITLE
fix: improve wsproxy error when proxyurl is set to a primary

### LINKED ISSUE #11116: workspace proxies: unique health check error if being treated as a subdomain app
## Background

A customer may mistakenly put a proxy in the same DNS path as wildcard apps, where the wildcard app somehow takes priority.

e.g. `*.demo.coder.com` vs `proxy.demo.coder.com`

image
image
image

## Proposal

Show a unique error in the health check to explain the conflict and resolution

### PR DESCRIPTION
**Pull request by Emyrk**
fixes: https://github.com/coder/coder/issues/11116

Screenshot from 2024-01-11 16-51-38

Check header for proxy instance, and check content-type for non json. If it's not a json payload, the json error is almost completely useless.

I think this could be formatted better, but it has the helpful information, which is enough for now imo.

### CODE REVIEW

**Comment by Emyrk** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/coder/coder/11586?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

<b>In this stack:</b> <code>🔧 Improve error handling in wsproxy for primary proxyurl</code>
* `main`
  * **#11584** <a href="https://app.graphite.dev/github/pr/coder/coder/11584?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **#11586** <a href="https://app.graphite.dev/github/pr/coder/coder/11586?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Emyrk and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: enterprise/coderd/proxyhealth/proxyhealth.go [hunk 1]
```diff
@@ -275,8 +276,34 @@ func (p *ProxyHealth) runOnce(ctx context.Context, now time.Time) (map[uuid.UUID
...
+
 					// If we cannot read the report, mark the proxy as unhealthy.
-					status.Report.Errors = []string{fmt.Sprintf("failed to decode health report: %s", err.Error())}
+					status.Report.Errors = []string{
+						errors.Join(
+							isCoderErr,
+							fmt.Errorf("received a status code 200, but failed to decode health report body: %w", err.Error()),
+						).Error(),
+					}
 					status.Status = Unhealthy
```
Comment (Emyrk) [inline enterprise/coderd/proxyhealth/proxyhealth.go:307]: The json decode error is usually absolute garbage. So this should improve it.

It also does a header check to instantly tell the user if they are not even pointed at a coder instance at all (proxy or otherwise)

**Review by sreya — APPROVED** [review]
