### PR TITLE
fix: clarify we download templates on template select

### LINKED ISSUE #1815: UX: warn users coder templates init modifies current directory
## Problem

When I run `coder templates init`, I am not informed that this command will create a new directory with a template in my current directory.

## Suggestion

Warn user before this happens and ask to confirm after selecting a template, default to yes.

### PR DESCRIPTION
**Pull request by f0ssel**
Fixes https://github.com/coder/coder/issues/1815

### CODE REVIEW

File: cli/templateinit.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ func templateInit() *cobra.Command {
 
 			_, _ = fmt.Fprintln(cmd.OutOrStdout(), cliui.Styles.Wrap.Render(
 				"A template defines infrastructure as code to be provisioned "+
-					"for individual developer workspaces. Select an example to get started:\n"))
+					"for individual developer workspaces. Select an example to download:\n"))
```
Comment (kylecarbs) [inline cli/templateinit.go:39]: The templates are embedded, not downloaded from an external source. I might be misunderstanding though.

Comment (Emyrk) [reply cli/templateinit.go:39]: They download to your local disk from coderd

Comment (kylecarbs) [reply cli/templateinit.go:39]: They actually are embedded in the CLI, not from coderd!

Comment (Emyrk) [reply cli/templateinit.go:39]: Oh yea. Good point. Maybe download is the wrong name, but I see what the confusion might be since it creates a directory.

`Select an example to be copied to the active directory`? Unsure exactly what language

**Comment by Emyrk** [comment]
@f0ssel when you get back, if you want to get this in

File: cli/templateinit.go (hunk 1 above)
Comment (jsjoeio) [reply cli/templateinit.go:39]: I like @Emyrk's suggestion:
```suggestion
					"for individual developer workspaces. Select an example to be copied to the active directory:\n"))
```

**Comment by jsjoeio** [comment]
@f0ssel anything i can do to help move this forward?

**Review by bpmct — APPROVED** [review]

**Review by Emyrk — APPROVED** [review]
