### PR TITLE
fix: don't navigate away from editor after publishing

### LINKED ISSUE #7153: Let template author change values while playing with the Editor
After publishing a new template version the user is redirected to the template page. We may want to add an option "Keep on editor" to keep the user on the current editor page so they can keep playing with the template.

### PR DESCRIPTION
**Pull request by aslilac**
Fixes #7153 

- Removes the `onPublish` action that was only used to navigate away from the editor after publishing
- Instead, the template name is now clickable, and will navigate you to the template summary (which is where you were sent after publishing previously)
- Renamed a state with a name that was slightly misleading
- Reorganized the state chart to make it a little friendlier

### CODE REVIEW

File: site/src/components/TemplateVersionEditor/TemplateVersionEditor.tsx [hunk 1]
```diff
@@ -217,13 +225,6 @@ export const TemplateVersionEditor: FC<TemplateVersionEditorProps> = ({
 
             <Button
               variant="contained"
-              title={
-                dirty
-                  ? "You have edited files! Run another build before updating."
-                  : templateVersion.job.status !== "succeeded"
-                  ? "Something"
-                  : ""
-              }
```
Comment (aslilac) [inline site/src/components/TemplateVersionEditor/TemplateVersionEditor.tsx:226]: I removed this because browsers disable `title` whenever the element they apply to is `disabled`. The only text that ever had a chance of being seen by a user was the `"Something"` placeholder text. 😅

**Review by BrunoQuaresma — APPROVED** [review]
🚢 it
