### PR TITLE
fix: preserve workspace resource metadata order

### LINKED ISSUE #4511: feat: specify ordering coder_metadata resource items in workspace dashboard
Version: [`v0.9.9+abf14d9`](https://github.com/coder/coder/commit/abf14d976a66e1869128410b7170b443c83abf05)

As a DevOps lead, I would like workspace metadata specified in a `coder_metadata` resource to be sorted in a specific way, which is not alphabetical. e.g., CPU, memory, disk should be logically grouped together.

Currently, Coder displays them in alphabetical order, which is not how the lead wants to group them.

Expected behavior is the order in the `coder_metadata` resource is how the metadata will be shown.

image

### PR DESCRIPTION
**Pull request by kylecarbs**
Fixes #4511.

### CODE REVIEW

File: coderd/database/queries/workspaceresources.sql [hunk 1]
```diff
@@ -47,11 +47,14 @@ FROM
 WHERE
 	workspace_resource_id = ANY(@ids :: uuid [ ]);
 
--- name: InsertWorkspaceResourceMetadata :one
+-- name: InsertWorkspaceResourceMetadata :many
```
Comment (coadler) [inline coderd/database/queries/workspaceresources.sql:50]: I think the selects above should have explicit `id ASC`s. I think that'd be the default, but changing the primary key again could alter that.

File: coderd/workspacebuilds.go [hunk 2]
```diff
@@ -948,33 +948,17 @@ func (api *API) convertWorkspaceBuild(
...
-		Sensitive: false,
-	}
-	// explicit metadata fields come afterward, and can override implicit ones
-	for _, field := range metadata {
-		metadataMap[field.Key] = field
-	}
-
+	slices.SortFunc(metadata, func(a, b database.WorkspaceResourceMetadatum) bool {
+		return a.ID < b.ID
+	})
```
Comment (coadler) [inline coderd/workspacebuilds.go:953]: Why sort in Go when we get them back from Postgres already sorted?

**Review by coadler — APPROVED** [review]

File: coderd/workspacebuilds.go (hunk 2 above)
Comment (kylecarbs) [reply coderd/workspacebuilds.go:953]: I wasn't sure if we would, but if we do then I'll rm this.
