### PR TITLE
fix: update template with noop returned undefined template

### LINKED ISSUE #11186: `Owner` role can't update a template, if template's `Everyone` role removed
Version: [`v2.5.0+cab8ffa`](https://github.com/coder/coder/commit/cab8ffa54ad88b34b965b0aeb859f35c335c5fcb)

I've been updating a new template in the Settings UI, and now get this when clicking `Submit`

image

`Resource not found or you do not have access to this resource`

It seems to happen if I remove the `Everyone` role. It didn't do that in previous releases.

### PR DESCRIPTION
**Pull request by Emyrk**
Fixes https://github.com/coder/coder/issues/11186

When the UI submits an update to a template, and there has been no change, the response is a 304 (Not modified) with an empty payload. The UI expected a response, and returned `/undefined` as the template name.

The unit test added was just testing the reported case, which turned out not to be an issue.

### CODE REVIEW

File: enterprise/coderd/templates_test.go [hunk 1]
```diff
@@ -687,6 +687,44 @@ func TestTemplates(t *testing.T) {
 		require.Empty(t, template.DeprecationMessage)
 		require.False(t, template.Deprecated)
 	})
+
+	// Create a template, remove the group, see if an owner can
+	// still fetch the template.
+	t.Run("GetOnEveryoneRemove", func(t *testing.T) {
```
Comment (Emyrk) [inline enterprise/coderd/templates_test.go:693]: Probably worth keeping, it was the original report.

File: site/src/pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPage.tsx [hunk 2]
```diff
@@ -29,6 +29,13 @@ export const TemplateSettingsPage: FC = () => {
     (data: UpdateTemplateMeta) => updateTemplateMeta(template.id, data),
     {
       onSuccess: async (data) => {
+        // This update has a chance to return a 304 which means nothing was updated.
+        // In this case, the return payload will be empty and we should use the
+        // original template data.
+        if (!data) {
+          data = template;
+        }
```
Comment (Parkreiner) [inline site/src/pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPage.tsx:37]: I think this change works for our purposes here. I guess there's just two other things that come to mind:

1. At the end of the day, we do need an `undefined` check, but right now, there's nothing surfacing that the data could be undefined at the type level.

   My worry is that someone will see that we're doing a check for something that appears non-nullable, and not be sure whether the comment still applies. Could you also add an `undefined` union for `updateTemplateMeta`?
   
   I know that we're using this API call in two other files, though, so there might be some edge cases with changing it everywhere. `onSuccess`'s `data` argument could be changed to include `undefined` as a bandaid solution by broadening the type
```ts
export const updateTemplateMeta = async (
  templateId: string,
  data: TypesGen.UpdateTemplateMeta,
): Promise<TypesGen.Template | undefined> => {
  const response = await axios.patch<TypesGen.Template | undefined>(
    `/api/v2/templates/${templateId}`,
    data,
  );
  return response.data;
};
```

2. I haven't dived too deeply into our settings stuff, but my gut feeling is that we don't necessarily need to invalidate the queries and go through a refetch if no data has changed. I wonder if something like this might be good:
```ts
onSuccess: async (data) => {
  if (!data) {
    data = template;
  } else {
    await queryClient.invalidateQueries(
      templateByNameKey(orgId, data.name),
    );
  }
}
```

**Review by buenos-nachos — COMMENTED** [review]
I think the client-side fix makes sense – just had one suggestion for a possible improvement.

I don't think I should be trusted with the Go stuff, though. I hate to delegate that part, but I'm still getting up to speed on the language, and am a little worried that some nuances might be lost on me

**Comment by Emyrk** [comment]
I did attempt to solve this in the backend, but I could not.

Golang does not allow writing a body for some status codes:

https://github.com/golang/go/blob/master/src/net/http/server.go#L1569-L1574

File: site/src/api/api.ts [hunk 3]
```diff
@@ -411,11 +411,13 @@ export const unarchiveTemplateVersion = async (templateVersionId: string) => {
...
 
+// updateTemplateMeta will return "undefined" if there is no change to the template.
+// A noop returns a "Not Modified" (304) response.
 export const updateTemplateMeta = async (
   templateId: string,
   data: TypesGen.UpdateTemplateMeta,
-): Promise<TypesGen.Template> => {
-  const response = await axios.patch<TypesGen.Template>(
+): Promise<TypesGen.Template | undefined> => {
+  const response = await axios.patch<TypesGen.Template | undefined>(
```
Comment (Parkreiner) [inline site/src/api/api.ts:420]: Oh wait, I just realized something – I'm worried the logic isn't quite right. `undefined` isn't a valid JSON-serializable value (though `null` is), so it shouldn't be able to make it across the API boundary in the first place

Is the condition we should actually be checking for whether `data.name` is the string literal `"undefined"`? Even in the bug issue, the previous code wasn't breaking when it was trying to access the `name` property during the navigation – it was just being fed an incorrect value. That's making me think that technically, `data` and its properties would always be defined – it's just that `name` is `"undefined"` in certain situations

This is definitely out of scope for the PR, and I haven't explored our type generation logic, so I don't know how complicated this would be, but there is a trick we can use to add the literal `"undefined"` to autocomplete without narrowing the overall type unnecessarily:
```ts
interface Template {
  readonly name: "undefined" | (string | {}); // (string | NonNullable<unknown>) also works
}
```
With that, "undefined" would show up during autocomplete, but the overall type would still be `string`

Comment (Emyrk) [reply site/src/api/api.ts:420]: The response is a completely empty payload, 0 bytes.

You are saying that is `null` and not `undefined`?

**Review by buenos-nachos — APPROVED** [review]
👍
