### PR TITLE
fix: clear workspace name validation on field dirty

### LINKED ISSUE #10637: bug: After correcting a duplicate workspace name, the validation errors remain
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

Coder correctly checks if a duplicate workspace name is chosen at workspace creation.

However, if I change the name, the red errors still appear, but if I press create, the workspace creates fine.

image

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #10637

### CODE REVIEW

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePage.tsx [hunk 1]
```diff
@@ -127,6 +127,7 @@ const CreateWorkspacePage: FC = () => {
           defaultOwner={me}
           defaultBuildParameters={defaultBuildParameters}
           error={createWorkspaceMutation.error}
+          resetMutation={createWorkspaceMutation.reset}
```
Comment (BrunoQuaresma) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePage.tsx:130]: For me, resetMutation does not say too much about its intention. Maybe `resetError` could be a better name?

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx [hunk 2]
```diff
@@ -157,7 +159,8 @@ export const CreateWorkspacePageView: FC<CreateWorkspacePageViewProps> = ({
             <TextField
               {...getFieldHelpers("name")}
               disabled={creatingWorkspace}
-              onChange={onChangeTrimmed(form)}
+              // resetMutation facilitates the clearing of validation errors
+              onChange={onChangeTrimmed(form, resetMutation)}
```
Comment (BrunoQuaresma) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageView.tsx:163]: We should not have to reset the mutation to clear the form error. But I think it is probably out of scope since it looks to be an issue with how we use the getFormHelpers gets the errors.

**Review by BrunoQuaresma — APPROVED** [review]
Just minor comments.
