### PR TITLE
fix(site): add defensive access to entitlement features

### LINKED ISSUE #14784: License without `user_limit` crashes license UI page
Screenshot from 2024-09-24 13-51-13

### PR DESCRIPTION
**Pull request by mtojek**
Fixes #14784

## Summary

This PR fixes a runtime crash on the License Settings page when the entitlements response doesn't contain the `user_limit` feature, and removes unused code from TemplateInsightsPage.

### 1. Fix: Defensive access to entitlement features (LicensesSettingsPage.tsx)

When the entitlements response doesn't contain certain feature keys (like `user_limit`), the License Settings page crashes with a runtime error because the code assumes `features.user_limit` always exists.

**Solution:** Use optional chaining (`?.`) to safely access feature properties:

```diff
- userLimitActual={entitlementsQuery.data?.features.user_limit.actual}
- userLimitLimit={entitlementsQuery.data?.features.user_limit.limit}
+ userLimitActual={entitlementsQuery.data?.features.user_limit?.actual}
+ userLimitLimit={entitlementsQuery.data?.features.user_limit?.limit}
```

The View component already handles `undefined` values gracefully through its optional prop types.

### 2. Test: Storybook story for the fix

Added `LicensesSettingsPage.stories.tsx` with `WithoutUserLimitFeature` story that tests the page renders correctly when entitlements don't include `user_limit`.

### 3. Refactor: Remove unused code from TemplateInsightsPage

The `userLimit` prop in `ActiveUsersPanel` was passed through but never actually used in the render. This removes:
- `entitlements` query from `TemplateInsightsPage`
- `entitlements` prop from `TemplateInsightsPageView`  
- `userLimit` prop from `ActiveUsersPanel`
- Associated unused imports (`entitlements`, `Entitlements`, `useEmbeddedMetadata`)

### CODE REVIEW

**Comment by DanielleMaywood** [comment]
Is there a reason for using jest over storybook?

**Comment by mtojek** [comment]
Yes, there is. The culprit is [LicensesSettingsPage.tsx](https://github.com/coder/coder/pull/21381/files#diff-7665bb514b3e2bb6013771ab0d85f0babcb05789a561a152e4dc32e93244a766), which is before going into PageView. Storybooks operate on PageView components.

**Comment by DanielleMaywood** [comment]
We have a couple of options then:
- Create a new storybook that operates on the `LicensesSettingsPage`.
- Write the test using Vitest instead of Jest (We're in the process of moving away from Jest https://github.com/coder/coder/pull/20568)

File: site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx [hunk 1]
```diff
@@ -77,8 +77,8 @@ const LicensesSettingsPage: FC = () => {
 				showConfetti={confettiOn}
 				isLoading={isLoading}
 				isRefreshing={refreshEntitlementsMutation.isPending}
-				userLimitActual={entitlementsQuery.data?.features.user_limit.actual}
-				userLimitLimit={entitlementsQuery.data?.features.user_limit.limit}
+				userLimitActual={entitlementsQuery.data?.features.user_limit?.actual}
+				userLimitLimit={entitlementsQuery.data?.features.user_limit?.limit}
```
Comment (EhabY) [inline site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: `features: Record<FeatureName, Feature>;`, technically any index access should use the `?.` notation (no guarantees on the existence). There's even a `tsconfig.json` config for this: https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess

This issue is that if this is enabled it might require a humongous amount of changes

Comment (mtojek) [reply site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: TIL!

I understand that it is something we definitely don't want to enable without wider refactor 😅 ?

**Review by mtojek — COMMENTED** [review]
@DanielleMaywood Thanks for challenging. I switched to Storybook and actually discovered unused code in template insights (we don't draw the limit line anymore).

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx [hunk 2]
```diff
@@ -251,11 +240,6 @@ export const TemplateInsightsPageView: FC<TemplateInsightsPageViewProps> = ({
 				<ActiveUsersPanel
 					css={{ gridColumn: "span 2" }}
 					interval={interval}
-					userLimit={
-						entitlements?.features.user_limit.enabled
-							? entitlements?.features.user_limit.limit
-							: undefined
-					}
```
Comment (EhabY) [inline site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx:258]: Was this just passed to **nothing**?

File: site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx (hunk 1 above)
Comment (EhabY) [reply site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: So I do not have a working `site` rn but if you add the option:

```json
"compilerOptions": {
    "noUncheckedIndexedAccess": true
  }
```

How many failures are there when compiling? This is def beyond the scope of this PR though :sweat:

**Review by EhabY — APPROVED** [review]
LGTM, I'm not too familiar with Storybook though :sweat_smile:

File: site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx (hunk 2 above)
Comment (mtojek) [reply site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx:258]: Passed and [unused](https://github.com/coder/coder/blob/11275330a6d346d1316e8836da55281bb57ac175/site/src/pages/TemplatePage/TemplateInsightsPage/TemplateInsightsPage.tsx#L289-L317) 👍

File: site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: I involved Claude & mux in this exercise. Here are the results:

Total: 257 errors, 89 files

TS2532 | 86 | Object is possibly 'undefined'
-- | -- | --
TS2345 | 62 | Argument of type 'X \| undefined' is not assignable to...
TS2322 | 56 | Type 'X \| undefined' is not assignable to type...
TS18048 | 46 | 'X' is possibly 'undefined'
Others | 7 | (TS2538, TS2339, TS2769, TS2488)

I asked to create a draft for better picture (clauding now), but we would need more eyes on this anyway 😅

**Review by DanielleMaywood — APPROVED** [review]

File: site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx (hunk 1 above)
Comment (mtojek) [reply site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: Here is the first draft: https://github.com/coder/coder/pull/21383

Comment (EhabY) [reply site/src/pages/DeploymentSettingsPage/LicensesSettingsPage/LicensesSettingsPage.tsx:81]: Hahahaha I love how the way it solves this is by asserting (and thus breaking at run time anyway). 145 lines is not bad though, I'm guessing in some cases we can assert and in others we just "handle" the undefined
