### PR TITLE
fix: handle NaN in build time estimate

### LINKED ISSUE #5437: build time shows `NaN seconds remaining`
prospect shared this feedback, saying it should display something like "working..." if the build time is not able to be calculated.

image

### PR DESCRIPTION
**Pull request by presleyp**
Fixes #5437 

If the estimated time left is 0, we divide by 0 and get NaN, and the max of 0 and NaN is NaN, so it takes an extra step to avoid passing NaN on.

### CODE REVIEW

File: site/src/components/WorkspaceBuildProgress/WorkspaceBuildProgress.tsx [hunk 1]
```diff
@@ -34,11 +34,13 @@ const estimateFinish = (
...
 ): [number | undefined, string] => {
   const sinceStart = dayjs().diff(startedAt)
-  const secondsLeft = (est: number) =>
-    Math.max(
+  const secondsLeft = (est: number) => {
+    const max = Math.max(
       Math.ceil(dayjs.duration((1 - sinceStart / est) * est).asSeconds()),
       0,
     )
+    return isNaN(max) ? 0 : max
```
Comment (Kira-Pilot) [inline site/src/components/WorkspaceBuildProgress/WorkspaceBuildProgress.tsx:42]: Hmm, looking at the ticket, it seems like this will result in a string saying "Up to 0 seconds remaining" which seems a little off to me. What do you think about adjusting the text for this case so it says something like "Finishing up..." or similar instead?

Comment (presleyp) [reply site/src/components/WorkspaceBuildProgress/WorkspaceBuildProgress.tsx:42]: It actually hits the case that says "Anytime now..." I added a story called StartingZeroEstimate that should show that.

Comment (Kira-Pilot) [reply site/src/components/WorkspaceBuildProgress/WorkspaceBuildProgress.tsx:42]: Sweet!

**Review by Kira-Pilot — APPROVED** [review]
