### PR TITLE
fix(coderd/wsbuilder): correctly evaluate dynamic workspace tag values

### LINKED ISSUE #15894: bug: creating a workspace build with `workspace_tags` variable fails with error: 'There is no variable named "var"'
While working on #15800 I neglected to add the discovered variables into the correct format expected by `wsbuilder`. This causes workspace build creation to fail if using a template that has a Terraform variable for a tag value in the `coder_workspace_tags` data source.

### PR DESCRIPTION
**Pull request by johnstcn**
Relates to https://github.com/coder/coder/issues/15894:

- Adds `coderdenttest.NewExternalProvisionerDaemonTerraform`
- Adds integration-style test coverage for creating a workspace with `coder_workspace_tags` specified in `main.tf`
- Modifies `coderd/wsbuilder` to fetch template version variables and include them in eval context for evaluating `coder_workspace_tags`

### CODE REVIEW

File: enterprise/coderd/coderdenttest/coderdenttest.go [hunk 1]
```diff
@@ -304,57 +306,94 @@ func CreateOrganization(t *testing.T, client *codersdk.Client, opts CreateOrgani
...
+	var serveFunc func()
+	switch ty {
+	case codersdk.ProvisionerTypeTerraform:
+		serveFunc = func() {
+			defer close(serveDone)
+			assert.NoError(t, terraform.Serve(ctx, &terraform.ServeOptions{
+				ServeOptions: &provisionersdk.ServeOptions{
+					Listener:      provisionerSrv,
+					WorkDirectory: t.TempDir(),
+				},
```
Comment (mafredri) [inline enterprise/coderd/coderdenttest/coderdenttest.go:365]: It'd be nice if we could at least for tests using this provisioner, ensure that the binary is only downloaded once (if needed). Otherwise we'll populate /tmp with a bunch of terraform downloads and it might increase flake risk too.

So something like this:
```go
// Lookup or install...
binPath, err := terraform.Install(ctx, logger, t.TempDir(), terraform.TerraformVersion)
if err != nil {
	return xerrors.Errorf("install terraform: %w", err)
}

// ...
BinaryPath: binPath,
```

We could optionally export some functions from `terraform` package to make this more convenient.

Do we need to set CachePath too to avoid potential racy access to the data? Referring to this:

```
// CachePath must not be used by multiple processes at once.
```

**Review by mafredri — APPROVED** [review]
Awesome, thanks for adding this functionality!

**Review by mtojek — APPROVED** [review]
LGTM!

File: coderd/wsbuilder/wsbuilder.go [hunk 2]
```diff
@@ -617,6 +618,22 @@ func (b *Builder) getTemplateVersionParameters() ([]database.TemplateVersionPara
 	return tvp, nil
 }
 
+func (b *Builder) getTemplateVersionVariables() ([]database.TemplateVersionVariable, error) {
+	if b.templateVersionVariables != nil {
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply coderd/wsbuilder/wsbuilder.go:622]: I don't think the builder is meant to be safe for concurrent use.
Maybe good for a follow-up though, as it could trip someone else up in future.

File: enterprise/coderd/coderdenttest/coderdenttest.go [hunk 3]
```diff
@@ -304,57 +306,94 @@ func CreateOrganization(t *testing.T, client *codersdk.Client, opts CreateOrgani
 	return org
 }
 
+// NewExternalProvisionerDaemon runs an external provisioner daemon in a
+// goroutine and returns a closer to stop it. The echo provisioner is used
+// here. This is the default provisioner for tests and should be fine for
+// most use cases. If you need to test terraform-specific behaviors, use
+// NewExternalProvisionerDaemonTerraform instead.
 func NewExternalProvisionerDaemon(t testing.TB, client *codersdk.Client, org uuid.UUID, tags map[string]string) io.Closer {
```
[the remark this answers is not in the document]
Comment (johnstcn) [reply enterprise/coderd/coderdenttest/coderdenttest.go:314]: I can rename in a follow-up! It would be a big diff :D

File: enterprise/coderd/coderdenttest/coderdenttest.go (hunk 1 above)
Comment (johnstcn) [reply enterprise/coderd/coderdenttest/coderdenttest.go:365]: I'd even go further to suggest that the terraform binary must already be present if you're running these tests!

File: coderd/wsbuilder/wsbuilder.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Emyrk) [reply coderd/wsbuilder/wsbuilder.go:622]: Yea, we do this pattern everywhere. It's all single threaded

File: enterprise/coderd/coderdenttest/coderdenttest.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Emyrk) [reply enterprise/coderd/coderdenttest/coderdenttest.go:315]: Yea, I think I wrote the original name. I don't think I even considered expected non-echo type in tests :smile:

File: enterprise/coderd/coderdenttest/coderdenttest.go [hunk 4]
```diff
@@ -304,57 +307,99 @@ func CreateOrganization(t *testing.T, client *codersdk.Client, opts CreateOrgani
...
+
+		go func() {
+			defer close(serveDone)
+			assert.NoError(t, terraform.Serve(ctx, &terraform.ServeOptions{
+				BinaryPath: terraformPath,
+				CachePath:  t.TempDir(),
+				ServeOptions: &provisionersdk.ServeOptions{
+					Listener:      provisionerSrv,
+					WorkDirectory: t.TempDir(),
+				},
```
Comment (Emyrk) [inline enterprise/coderd/coderdenttest/coderdenttest.go:373]: So this runs real terraform? Does this mean tests can accidentally provision resources?

File: enterprise/coderd/workspaces_test.go [hunk 5]
```diff
@@ -1420,6 +1422,182 @@ func TestTemplateDoesNotAllowUserAutostop(t *testing.T) {
 	})
 }
 
+// TestWorkspaceTagsTerraform tests that a workspace can be created with tags.
+// This is an end-to-end-style test, meaning that we actually run the
+// real Terraform provisioner and validate that the workspace is created
+// successfully. The workspace itself does not specify any resources, and
+// this is fine.
+func TestWorkspaceTagsTerraform(t *testing.T) {
```
Comment (Emyrk) [inline enterprise/coderd/workspaces_test.go:1430]: Woah, he did it :exploding_head: 

This is a super nice test. Slightly concerned with terraform being executed in tests, would be nice if we could lock it down somehow to prevent it allocating any resources.

**Review by Emyrk — APPROVED** [review]

File: enterprise/coderd/coderdenttest/coderdenttest.go (hunk 4 above)
Comment (johnstcn) [reply enterprise/coderd/coderdenttest/coderdenttest.go:373]: Yeah, that's the tricky thing if you're not careful. There's no other real way to test this apart from spinning up a Docker container or manual testing, and we _really need_ some kind of integration test here.

File: enterprise/coderd/workspaces_test.go (hunk 5 above)
Comment (johnstcn) [reply enterprise/coderd/workspaces_test.go:1430]: I could add a hacky check for the pattern `resource "[^"]+" "[^"]+"` and fail. That would at least make folks think twice before hacking it to allow certain resources.

Comment (Emyrk) [reply enterprise/coderd/workspaces_test.go:1430]: I don't think ruleguard would be sufficient. I wonder if we can do something to the executable. Run it another userspace with no perms? Configure a `HTTP_PROXY` that is broken so any external requests fail? I'm not sure :man_shrugging: 

I'm ok if we let this slide for now, since I don't know a good way. Just an unfortunate consequence.

Comment (johnstcn) [reply enterprise/coderd/workspaces_test.go:1430]: Yeah I think we may need to think about the best way to prevent misuse of this.
