### PR TITLE
test: fix flaky boundary test

### LINKED ISSUE #1297: flake: TestBoundarySubcommand
CI Run Link: https://github.com/coder/coder/actions/runs/21296461116
Failing Job: ci / test-go-pg-17
Completed: 2026-01-23T18:23:55Z (within minutes of Slack alert)
Run attempt: 1

Commit Info:
- SHA: 338b952d71dd7600579615b42fb2ad954fc0a3d0
- Author: DevCats (christofer@coder.com)
- Message: chore: skip doc-check when secrets are not available (#21637)
- Link: https://github.com/coder/coder/commit/338b952d71dd7600579615b42fb2ad954fc0a3d0

What failed
- Go tests failed with a single failing test:
  - package: enterprise/cli
  - test: TestBoundarySubcommand

Failure evidence
```
=== FAIL: enterprise/cli TestBoundarySubcommand (0.00s)
    boundary_test.go:36:
        Error:      Received unexpected error:
                    write /dev/pts/0: input/output error
        Test:       TestBoundarySubcommand
```

Why this looks flaky / likely root cause
- TestBoundarySubcommand starts `inv.Run()` in a goroutine and immediately proceeds to `pty.ExpectMatch(...)`.
- The match happens early (the short description appears near the top of `--help` output), while the command continues printing additional help text.
- The test does not wait for the goroutine to finish. When the test returns, cleanup closes the PTY; if the command is still writing help output, the write can fail with EIO (`write /dev/pts/0: input/output error`) and bubble up as `inv.Run()` returning an error.

Suggested fix
- Wait for `inv.Run()` to complete before letting the test return, e.g.:
  - `errCh := make(chan error, 1); go func(){ errCh <- inv.WithContext(ctx).Run() }()`
  - `pty.ExpectMatch(...)`
  - `require.NoError(t, <-errCh)`

Assignment analysis (code ownership)
- This test was introduced/moved as part of the Boundary feature work:
  - `git log -1 -- enterprise/cli/boundary_test.go` => 9b14fd3adc96c0cc9056b4be60a27cecb353cdf1 ("feat: add boundary premium feature (#21589)")
- Assigning to the most recent meaningful modifier of the test.

Duplicate detection
- Searched coder/internal for: "TestBoundarySubcommand", "write /dev/pts", "boundary_test.go flake", "ptytest input/output error" (no matches).
- Related (similar PTY closure symptom, different test): https://github.com/coder/internal/issues/713

Reproduction ideas
- `go test ./enterprise/cli -run TestBoundarySubcommand -count=100` (may reproduce depending on timing)

Notes
- This appears unrelated to the commit under test (which touched doc-check workflow) and instead is timing-sensitive behavior in the test/PTY harness.

### PR DESCRIPTION
**Pull request by evgeniy-scherbina**
Closes https://github.com/coder/internal/issues/1297

Rewrite `TestBoundarySubcommand` in a way similar to `TestPrebuildsCommand`.

### CODE REVIEW

**Review by zedkipp — APPROVED** [review]

File: enterprise/cli/boundary_test.go [hunk 1]
```diff
@@ -17,31 +18,28 @@ import (
...
+	err := inv.Run()
+	require.NoError(t, err)
 
-	// Expect the --help output to include the short description.
+	// Verify help output contains expected information.
 	// We're simply confirming that `coder boundary --help` ran without a runtime error as
 	// a good chunk of serpents self validation logic happens at runtime.
-	pty.ExpectMatch(boundarycli.BaseCommand("dev").Short)
+	output := buf.String()
+	assert.Contains(t, output, boundarycli.BaseCommand("dev").Short)
```
Comment (zedkipp) [inline enterprise/cli/boundary_test.go:42]: Not `assert.Equal()`?

Comment (evgeniy-scherbina) [reply enterprise/cli/boundary_test.go:42]: yeah, it should be `contains` to be in line with previous logic
