### PR TITLE
fix: redirect to new url after template name update

### LINKED ISSUE #10634: bug: renaming a template does not refresh the UI with the new name, causing additional edits to fail
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

I renamed a template in the Coder dashboard.

Then I changed the icon/emoji for the template as well as the description.

Saving gives the following error, which I think is because the Coder deployment's full URL still has the old template name in there which is no longer correct.

image

Refreshing the dashboard shows the changes were saved.

image

Proposed solution: If you change the template name, refresh the dashboard immediately so the new full URL is there.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #10634

### CODE REVIEW

File: site/e2e/helpers.ts [hunk 1]
```diff
@@ -709,6 +713,30 @@ export const updateTemplate = async (
...
+    UpdateTemplateMeta,
+    "name" | "display_name" | "description"
+  >,
+) => {
+  await page.goto(`/templates/${templateName}/settings`, {
+    waitUntil: "domcontentloaded",
+  });
+  await expect(page).toHaveURL(`/templates/${templateName}/settings`);
+
+  for (const [key, value] of Object.entries(templateSettingValues)) {
```
Comment (Parkreiner) [inline site/e2e/helpers.ts:729]: There's nothing wrong with the code right now, but there is a risk in the future from runtime/compile-time mismatches:

This will not throw a type error:
```ts
const myObj = {
  name: "whoops",
  obviouslyWrongValue: true
};

updateTemplateSettings(page, templateName, myObj);
```
You only get the error if you pass the object in as a literal, but there's not a great way to enforce people call the function that way:
```ts
updateTemplateSettings(page, templateName, {
  name: "whoops",
  
  // Error: Object literal may only specify known properties, and 'obviouslyWrongValue' does not exist in...
  obviouslyWrongValue: true
});
```
And because the loop is iterating over everything (regardless of what the type info says), you will get both properties logged, not just `name`

Just to be on the safe side, and because this is a general test helper, I'm wondering if there should be a runtime check on the key to make sure that you're only processing name/display_name/description

**Review by buenos-nachos — CHANGES_REQUESTED** [review]
Looks really good!
All the code was straightforward and easy to follow, but I did notice one edge case with the test helper that could cause flakes/weird behavior if we're not careful

File: site/e2e/helpers.ts (hunk 1 above)
Comment (Parkreiner) [reply site/e2e/helpers.ts:729]: Edited the message because I didn't like the way my tone sounded. Sorry about that

**Review by buenos-nachos — APPROVED** [review]
Kira and I talked about the issue – changes were kind of overkill, since we will still get errors if the runtime looping causes problems

Switching this to approved
