### PR TITLE
fix: use TSMP for pings and checking reachability

### LINKED ISSUE #11294: flake: TestPortForward/UDP_OnePort - EOF
```
    portforward_test.go:150: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/cli/portforward_test.go:351
        	            				/home/runner/actions-runner/_work/coder/coder/cli/portforward_test.go:336
        	            				/home/runner/actions-runner/_work/coder/coder/cli/portforward_test.go:150
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestPortForward/UDP_OnePort
        	Messages:   	read payload
```

seen here: https://github.com/coder/coder/actions/runs/7226765867/job/19693041460#step:5:320

### PR DESCRIPTION
**Pull request by spikecurtis**
We're seeing some flaky tests related to agent connectivity - https://github.com/coder/coder/actions/runs/7286675441/job/19856270998

I'm pretty sure what happened in this one is that the client opened a connection while the wgengine was in the process of reconfiguring the wireguard device, so the fact that the peer became "active" as a result of traffic being sent was not noticed.

The test calls `AwaitReachable()` but this only tests the disco layer, so it doesn't wait for wireguard to come up.

I think we should be using TSMP for pinging and reachability, since this operates at the IP layer, and therefore requires that wireguard comes up before being successful.

This should also help with the problems we have seen where a TCP connection starts before wireguard is up and the initial round trip has to wait for the 5 second wireguard handshake retry.

fixes: #11294

### CODE REVIEW

**Comment by spikecurtis** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #11306** <a href="https://app.graphite.dev/github/pr/coder/coder/11306?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/coder/coder/11306?utm_source=stack-comment).

**Review by coadler — APPROVED** [review]

**Review by deansheather — APPROVED** [review]

File: agent/agent_test.go [hunk 1]
```diff
@@ -186,7 +186,7 @@ func TestAgent_Stats_Magic(t *testing.T) {
 				// If it isn't, it's set to -1.
 				s.ConnectionMedianLatencyMS >= 0
 		}, testutil.WaitLong, testutil.IntervalFast,
-			"never saw stats: %+v", s,
+			"never saw stats",
```
Comment (spikecurtis) [inline agent/agent_test.go:189]: This gives misleading information since the pointer is passed on the initial call to `Eventually`.  It is not updated since `<-stats` returns a new pointer, rather than updating the data at the old pointer.  Changed in favor of logging the relevant info as we get it.

File: agent/agent_test.go [hunk 2]
```diff
@@ -256,12 +256,13 @@ func TestAgent_Stats_Magic(t *testing.T) {
 		_ = tunneledConn.Close()
 
 		require.Eventuallyf(t, func() bool {
-			var ok bool
-			s, ok = <-stats
-			return ok && s.ConnectionCount == 0 &&
+			s, ok := <-stats
+			t.Logf("got stats after disconnect %t, %d",
+				ok, s.SessionCountJetBrains)
+			return ok &&
```
Comment (spikecurtis) [inline agent/agent_test.go:262]: TSMP ping counts as a "connection" in the agent stats so it never goes to zero.  I'm not sure why we were testing it going to zero in the first place @code-asher

**Comment by spikecurtis** [comment]
### Merge activity

* **Jan 2, 6:53 AM**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/11306).

File: agent/agent_test.go (hunk 2 above)
Comment (code-asher) [reply agent/agent_test.go:262]: I think we wanted to make sure `ConnectionCount` was also updating correctly, but did not realize there would be other connections going on.
