### PR TITLE
fix: ensure signing out cannot cause any runtime render errors

### LINKED ISSUE #13130: site: Logging out of the dashboard immediately throws an "unexpected application error" when using the Go backend (including production)
Turning this into an issue for documentation purposes. I'm dropping everything and working on this now, and gunning to have this done by end of day

## Updates
- I think I got this figured out – when we started trying to embed more and more data into the HTML to speed up queries, we didn't update all the query logic to account for the fact that even when we log out, there's still going to be user data in the HTML
   - None of the unit tests caught this because the metadata doesn't exist in the JS runtime – it only exists when we're actually serving files through the Go backend

## Steps to reproduce
1. Log into Coder via Google OAuth (I'm using Coder Dogfood)
2. Click the user icon in the top-right corner
3. Click "Sign out"
4. Immediate "Unexpected application error" based on permissions being unavailable

## Video
https://github.com/coder/coder/assets/28937484/e1a70cc6-8aa4-44da-82e7-3c80dc59a354

## Notes
- As far as I can tell, this is strictly an issue on the UI side. The log out request is correctly going through, but the UI isn't syncing correctly afterwards

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #13130

## Changes made
- Created an entire fully-type-safe state management system for exposing all the metadata in a render-safe way for the UI
   - We've had a couple of bugs specifically around bringing this metadata in already. If we're going to keep bringing in more and more data, we need a way to centralize it, and make sure it can pipe into React/React Query well
   - Critically, this system allows you to delete metadata (the bug fix for this issue involves deleting the user metadata in the HTML, and making sure the stale data isn't persisted in any variables)
- Updates how we're placing error boundaries to greatly decrease our odds of more uncaught runtime errors slipping through the UI
   - I want to update our error boundary component a bit, but that'll be done in a later PR
- Updates how we're integrating the React Query dev tools to make sure nothing breaks there either

## Notes
- I would eventually like to make a `useMetadataQuery` hook to improve the ergonomics of wiring up our metadata to React Query, but this is a decent first step towards that
- Going to make a separate PR for making an E2E test to make sure we catch any possible logout bugs

### CODE REVIEW

File: site/src/App.tsx [hunk 1]
```diff
@@ -60,10 +74,10 @@ export const AppProviders: FC<AppProvidersProps> = ({
...
   return (
-    <AppProviders>
-      <ErrorBoundary>
+    <ErrorBoundary>
+      <AppProviders>
         <RouterProvider router={router} />
-      </ErrorBoundary>
-    </AppProviders>
+      </AppProviders>
+    </ErrorBoundary>
```
Comment (Parkreiner) [inline site/src/App.tsx:81]: Important – before, if any of the sub-components in `AppProviders` threw an error, we had nothing to catch it. Moved `ErrorBoundary` to be the top-most component

File: site/src/api/queries/appearance.ts [hunk 2]
```diff
@@ -1,16 +1,14 @@
...
-import { getMetadataAsJSON } from "utils/metadata";
+import type { MetadataState } from "hooks/useEmbeddedMetadata";
 import { cachedQuery } from "./util";
 
-const initialAppearanceData = getMetadataAsJSON<AppearanceConfig>("appearance");
 const appearanceConfigKey = ["appearance"] as const;
 
-export const appearance = (): UseQueryOptions<AppearanceConfig> => {
-  // We either have our initial data or should immediately fetch and never again!
+export const appearance = (metadata: MetadataState<AppearanceConfig>) => {
```
Comment (Parkreiner) [inline site/src/api/queries/appearance.ts:9]: I want to go back and add the explicit return types in, but right now, these functions rely on inference

File: site/src/api/queries/users.ts [hunk 3]
```diff
@@ -193,6 +190,22 @@ export const logout = (queryClient: QueryClient) => {
...
+       * completely uncaught runtime rendering error. Worse yet, the error only
+       * exists when serving the site from the Go backend (the JS environment
+       * has zero issues because it doesn't have access to the metadata). These
+       * errors can only be caught with E2E tests.
+       *
+       * Deleting the user data will mean that all future requests have to take
+       * a full roundtrip, but better that than having the logout button blow
+       * the entire app up.
+       */
+      defaultMetadataManager.clearMetadataByKey("user");
```
Comment (Parkreiner) [inline site/src/api/queries/users.ts:208]: This is the main part of the fix.

File: site/src/api/queries/util.ts
Comment (Parkreiner) [inline site/src/api/queries/util.ts:1]: The function is largely the same, but I went ahead and redefined all the types to ensure 100% compatibility with React Query

File: site/src/contexts/ProxyContext.tsx [hunk 4]
```diff
@@ -94,37 +95,8 @@ export const ProxyProvider: FC<PropsWithChildren> = ({ children }) => {
...
-    // Build info is injected by the Coder server into the HTML document.
-    const regions = document.querySelector("meta[property=regions]");
-    if (regions) {
-      const rawContent = regions.getAttribute("content");
-      try {
-        const obj = JSON.parse(rawContent as string);
-        if ("regions" in obj) {
-          return obj.regions as Region[];
-        }
-        return obj as Region[];
```
Comment (Parkreiner) [inline site/src/contexts/ProxyContext.tsx:113]: @Emyrk I wasn't completely sure why we had a check for whether the data getting parsed was either an array or an object with the array inside it, but just to be on the safe side, I ripped this out and centralized it in the metadata manager file

File: site/src/contexts/ProxyContext.tsx [hunk 5]
```diff
@@ -133,9 +105,15 @@ export const ProxyProvider: FC<PropsWithChildren> = ({ children }) => {
...
-      queryFn: query,
+      metadata: metadata.regions,
+      queryKey: ["get-proxies"],
+      queryFn: async (): Promise<readonly Region[]> => {
+        const endpoint = permissions.editWorkspaceProxies
+          ? getWorkspaceProxies
+          : getWorkspaceProxyRegions;
+        const resp = await endpoint();
+        return resp.regions;
+      },
```
Comment (Parkreiner) [inline site/src/contexts/ProxyContext.tsx:116]: Just inlined a bunch of the values, since they're only used here

File: site/src/api/queries/users.ts [hunk 6]
```diff
@@ -193,6 +190,22 @@ export const logout = (queryClient: QueryClient) => {
...
+       * completely uncaught runtime rendering error. Worse yet, the error only
+       * exists when serving the site from the Go backend (the JS environment
+       * has zero issues because it doesn't have access to the metadata). These
+       * errors can only be caught with E2E tests.
+       *
+       * Deleting the user data will mean that all future requests have to take
+       * a full roundtrip, but this still felt like the best way to ensure that
+       * manually logging out doesn't blow the entire app up.
+       */
+      defaultMetadataManager.clearMetadataByKey("user");
```
Comment (Parkreiner) [inline site/src/api/queries/users.ts:208]: This is the main part of the fix

File: site/src/contexts/auth/RequireAuth.tsx [hunk 7]
```diff
@@ -48,6 +44,11 @@ export const RequireAuth: FC = () => {
   }
 
   if (isSignedOut) {
+    const isHomePage = location.pathname === "/";
+    const navigateTo = isHomePage
+      ? "/login"
+      : embedRedirect(`${location.pathname}${location.search}`);
+
```
Comment (Parkreiner) [inline site/src/contexts/auth/RequireAuth.tsx:51]: Moved the variables here because they're only relevant for this block

File: site/src/api/queries/experiments.ts [hunk 8]
```diff
@@ -1,15 +1,13 @@
...
 import type { Experiments } from "api/typesGenerated";
-import { getMetadataAsJSON } from "utils/metadata";
+import type { MetadataState } from "hooks/useEmbeddedMetadata";
 import { cachedQuery } from "./util";
 
-const initialExperimentsData = getMetadataAsJSON<Experiments>("experiments");
 const experimentsKey = ["experiments"] as const;
 
-export const experiments = (): UseQueryOptions<Experiments> => {
+export const experiments = (metadata: MetadataState<Experiments>) => {
```
Comment (Parkreiner) [inline site/src/api/queries/experiments.ts:8]: I do want to go back and add explicit return types, but I was on a tight deadline, and didn't have time.

These functions are still type-safe and will let you know if you wire things wrong. They're just not "add explicit type parameter"-safe, because of TypeScript generic shenanigans

**Comment by BrunoQuaresma** [comment]
I found this fix quite complex but comprehensible 👍 good job. I also tested it locally.

**Review by BrunoQuaresma — APPROVED** [review]

File: site/src/contexts/ProxyContext.tsx (hunk 4 above)
Comment (Emyrk) [reply site/src/contexts/ProxyContext.tsx:113]: Great question. The type safety we have on these fields is terrible, and should be resolved imo to make things like this more clear. We just inject strings that are json. Very weak imo.

I think it should always have `regions` as a field, but would have to do some digging to really confirm.
