### PR TITLE
coderd: treat email case insensitively

### LINKED ISSUE #4213: Login email should not be case sensitive
[Bug] At login, the email address should not be case sensitive.

E.g.
My registered email is: _Test@example.com_

When I try to login with _test@example.com_ (all lower case), coder shows the message _Incorrect email or password_.

### PR DESCRIPTION
**Pull request by ammario**
Resolves https://github.com/coder/coder/issues/4213

### CODE REVIEW

**Comment by coadler** [comment]
The index should be changed to be case insensitive too like this https://github.com/coder/v1/blob/master/product/coder/pkg/lifecycle/migrations/1647279660_case_insensitive_usernames.go#L56

**Comment by ammario** [comment]
check again @coadler

File: coderd/database/queries/users.sql [hunk 1]
```diff
@@ -17,7 +17,7 @@ SELECT
 FROM
 	users
 WHERE
-	(LOWER(username) = LOWER(@username) OR email = @email)
+	(LOWER(username) = LOWER(@username) OR LOWER(email) = (@email))
```
Comment (coadler) [inline coderd/database/queries/users.sql:20]: I think you need a LOWER(@email) here too

**Review by coadler — APPROVED** [review]
