### PR TITLE
fix: template permissions page never loads

### LINKED ISSUE #4953: navigating to `/templates/<name>/permissions` keeps spinning
Steps to reproduce: https://dev.coder.com/templates/coder/permissions

### PR DESCRIPTION
**Pull request by Kira-Pilot**
(hopefully) resolves #4953 

Previously, on the Template Permissions page, we always showed a loader if a user did not have permissions to update the template. 
We don't anymore; we just disable the dropdowns on the page:

Screen Shot 2022-11-10 at 4 13 31 PM

In addition, I made an effort to clean up loading on this page overall. @BrunoQuaresma could you please review carefully? I think you were the last person to touch this code.

### CODE REVIEW

File: site/src/components/TemplateLayout/TemplateLayout.tsx [hunk 1]
```diff
@@ -152,65 +140,59 @@ export const TemplateLayout: FC<PropsWithChildren> = ({ children }) => {
           }
         >
           <Stack direction="row" spacing={3} className={styles.pageTitle}>
-            {!isLoading && (
```
Comment (Kira-Pilot) [inline site/src/components/TemplateLayout/TemplateLayout.tsx:155]: I'm not sure why we were wrapping all these blocks in `isLoading` - seems like we just need to make sure the template is there (and we do on line 114).

File: site/src/pages/TemplatePage/TemplatePermissionsPage/TemplatePermissionsPage.tsx [hunk 2]
```diff
@@ -26,14 +25,11 @@ export const TemplatePermissionsPage: FC<
     context: { templateId: template?.id },
   })
   const { templateACL, userToBeUpdated, groupToBeUpdated } = state.context
-  if (!template || !permissions) {
-    return <Loader />
-  }
```
Comment (Kira-Pilot) [inline site/src/pages/TemplatePage/TemplatePermissionsPage/TemplatePermissionsPage.tsx:31]: We shouldn't need another loader here, right? We already have the `Suspense` in the parent component with a fallback loader. Also, at this point, we can be certain template is loaded.

**Review by BrunoQuaresma — APPROVED** [review]
