### PR TITLE
fix(coderd): fix isContextLimitKey false positive on max_context_version

### LINKED ISSUE #23332: bug(coderd/chatd/chatloop): isContextLimitKey false positive on max_context_version
> 🤖 Found during coverage testing in #23313. Filing for follow-up as suggested by @johnstcn.

## Problem

`isContextLimitKey` in `coderd/chatd/chatloop/contextlimit.go` has a fallback heuristic that matches any key starting with `"max"` that also contains `"context"`. This incorrectly matches keys like `"max_context_version"` which are not context limit keys.

The heuristic at the end of the function:

```go
// Fallback: starts with "max" and contains "context".
if strings.HasPrefix(norm, "max") && strings.Contains(norm, "context") {
    return true
}
```

## Impact

A provider returning metadata with a key like `"max_context_version"` would have that value parsed as a context limit, potentially overriding the real limit or causing errors in `numericContextLimitValue` if the value is not numeric.

## Test

A skipped test case exists in `coderd/chatd/chatloop/contextlimit_internal_test.go`:

```go
{name: "max_context_version false positive", key: "max_context_version", want: false, skip: true},
```

Remove the `skip: true` after fixing the heuristic.

## Suggested fix

The heuristic could require that the key also contains a limit-related suffix like `"limit"`, `"tokens"`, `"length"`, or `"window"` instead of just `"context"`.

> 🤖 Heuristics: the gift that keeps on giving (false positives).

### PR DESCRIPTION
**Pull request by dylanhuff-at-coder**
`isContextLimitKey` had a fallback heuristic that matched any key starting with `"max"` containing `"context"`, causing false positives on keys like `"max_context_version"`. A provider returning such metadata would have the
  value parsed as a context limit.

  Replace substring matching on the separator-stripped key with word-level matching. A new `metadataKeyWords` function tokenizes keys by splitting on separators and camelCase boundaries, then the fallback requires `"context"`
  paired with a limit-related word (`"limit"`, `"window"` + qualifier, `"length"` + qualifier, or `"tokens"` + qualifier). Known exact forms like `"context_window"` remain in the fast-path switch.

  Closes https://github.com/coder/coder/issues/23332

### CODE REVIEW

**Comment by dylanhuff-at-coder** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dylanhuff-at-coder** [comment]
recheck

File: coderd/x/chatd/chatloop/chatloop.go [hunk 1]
```diff
@@ -1342,6 +1357,40 @@ func normalizeMetadataKey(key string) string {
 	return b.String()
 }
 
+func metadataKeyWords(key string) []string {
+	words := make([]string, 0, 4)
```
Comment (zedkipp) [inline coderd/x/chatd/chatloop/chatloop.go:1361]: Why initialize this with a capacity of 4?

Comment (zedkipp) [reply coderd/x/chatd/chatloop/chatloop.go:1361]: I see this a typical key length. Seems fine to keep but not sure a tiny pre-alloc is necessary

**Review by zedkipp — APPROVED** [review]

File: coderd/x/chatd/chatloop/chatloop.go (hunk 1 above)
Comment (dylanhuff-at-coder) [reply coderd/x/chatd/chatloop/chatloop.go:1361]: Yeah set based on expected key length, I'll leave it as is and keep in mind that such a small pre-allocation isn't really in future similar scenarios
