### PR TITLE
fix: open coder_app links in new tab when open_in is tab

### LINKED ISSUE #18573: bug: coder_app 'open_in = "tab"' opens link in same tab
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Given this app:

```
resource "coder_app" "api" {
  agent_id  = coder_agent.main.id
  slug      = "api"
  icon      = "https://upload.wikimedia.org/wikipedia/commons/a/a6/Api_logo.jpg"
  url       = "my-url"
  external = true
  open_in = "tab"
}
```

Link opens in same tab, tested in vivaldi and edge.

### Relevant Log Output

```shell

```

### Expected Behavior

Link opens in a new tab.

### Steps to Reproduce

Set open_in = "tab" in a coder_app.
Open link.

### Environment

- Host OS: Ubuntu 22.04
- Coder version: 2.23.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by angrycub**
Fixes #18573

## Changes

When a `coder_app` resource sets `open_in = "tab"`, clicking the app link now opens in a new browser tab instead of navigating in the same tab.

`target="_blank"` and `rel="noopener noreferrer"` are set inline on the `<a>` elements in `AppLink.tsx`, gated on `app.open_in === "tab"`. This follows the codebase convention of co-locating `target` and `rel` at the render site.

`noopener` prevents tabnabbing — without it, the opened page can redirect the Coder dashboard tab via `window.opener`. This is especially relevant for same-origin path-based apps, which would otherwise have full DOM access to the dashboard. `noreferrer` suppresses the Referer header to avoid leaking workspace IDs to destination servers.

> **Future enhancement**: template admins could opt into sending the referrer via a `coder_app` setting, enabling feedback pages built around workspace context.

## Tests

A vitest case is added in `AppLink.test.tsx` (rather than a Storybook story, since the assertions are purely behavioral with no visual component):

- **`sets target=_blank and rel=noopener noreferrer when open_in is tab`** — renders the app link with `open_in: "tab"` and asserts `target="_blank"` and `rel="noopener noreferrer"` are present on the anchor.

## Slim-window behavior

The `slim-window` test case and the `openAppInNewWindow()` comment in `apps.ts` have been split out into a follow-up PR for separate review, since the `window.open()` / `noopener` tradeoffs there deserve dedicated discussion.

### CODE REVIEW

File: site/src/modules/resources/AppLink/AppLink.tsx [hunk 1]
```diff
@@ -135,15 +135,25 @@ export const AppLink: FC<AppLinkProps> = ({
 
 	const button = grouped ? (
 		<DropdownMenuItem asChild>
-			<a href={canClick ? link.href : undefined} onClick={link.onClick}>
+			<a
+				href={canClick ? link.href : undefined}
+				onClick={link.onClick}
+				target={app.open_in === "tab" ? "_blank" : undefined}
+				rel={app.open_in === "tab" ? "noopener noreferrer" : undefined}
```
Comment (aslilac) [inline site/src/modules/resources/AppLink/AppLink.tsx]:
```suggestion
				rel={app.open_in === "tab" ? "noreferrer" : undefined}
```
just do `noreferrer`, it is a superset of the `noopener` behavior

File: site/src/modules/resources/AppLink/AppLink.tsx [hunk 2]
```diff
@@ -135,15 +135,25 @@ export const AppLink: FC<AppLinkProps> = ({
...
 			</a>
 		</DropdownMenuItem>
 	) : (
 		<AgentButton asChild>
-			<a href={canClick ? link.href : undefined} onClick={link.onClick}>
+			<a
+				href={canClick ? link.href : undefined}
+				onClick={link.onClick}
+				target={app.open_in === "tab" ? "_blank" : undefined}
+				rel={app.open_in === "tab" ? "noopener noreferrer" : undefined}
```
Comment (aslilac) [inline site/src/modules/resources/AppLink/AppLink.tsx]:
```suggestion
				rel={app.open_in === "tab" ? "noreferrer" : undefined}
```

File: site/src/modules/resources/AppLink/AppLink.test.tsx [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+const renderAppLink = (app: typeof MockWorkspaceApp) => {
+	return renderWithAuth(
+		<AppLink app={app} workspace={MockWorkspace} agent={MockWorkspaceAgent} />,
+	);
+};
+
+// Regression test for https://github.com/coder/coder/issues/18573:
+// open_in="tab" was not opening links in a new tab.
+describe("AppLink", () => {
+	it("sets target=_blank and rel=noopener noreferrer when open_in is tab", async () => {
```
Comment (aslilac) [inline site/src/modules/resources/AppLink/AppLink.test.tsx]:
```suggestion
	it("sets target=_blank and rel=noreferrer when open_in is tab", async () => {
```

noreferrer is more strict than noopener. I don't know if they're meant to be specified together like, but I do know that at the very least it's redundant. at worst it might lead to inconsistent parsing/interpretation.

File: site/src/modules/resources/AppLink/AppLink.test.tsx [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+		renderAppLink({ ...MockWorkspaceApp, open_in: "tab" });
+		const link = await screen.findByRole("link");
+		expect(link).toHaveAttribute("target", "_blank");
+		expect(link).toHaveAttribute("rel", "noopener noreferrer");
```
Comment (aslilac) [inline site/src/modules/resources/AppLink/AppLink.test.tsx]:
```suggestion
		expect(link).toHaveAttribute("rel", "noreferrer");
```

**Review by aslilac — COMMENTED** [review]
sorry, I just realized I didn't actually submit this review on friday 🤦‍♀️

**Review by aslilac — APPROVED** [review]
