### PR TITLE
fix(cli): retry transient connection failures during SSH setup

### LINKED ISSUE #24005: coder ssh: add retry loop for transient connection failures
`coder ssh --stdio` exits immediately on transient errors (DNS failure, connection timeout, API unreachable). When used as an SSH ProxyCommand, this causes VS Code's Remote SSH extension to throw a permanent `SshResolverError.Create()` error, which kills the reconnection loop on the first attempt. The user sees "Reload Window" even though the error would resolve itself in seconds.

## Confirmed failure mode

Captured from `remote.SSH.logLevel: "trace"` during a real sleep/wake cycle on Linux with `systemd-resolved`:

1. Wake from sleep, VS Code detects disconnect (\~20s), starts reconnection
2. Remote SSH extension spawns new SSH with ProxyCommand: `coder ssh --stdio`
3. `coder ssh` immediately queries the workspace API
4. **DNS lookup fails**: `dial tcp: lookup dev.coder.com: server misbehaving` (`systemd-resolved` not ready after wake)
5. `coder ssh` exits immediately with error
6. Remote SSH sees unparsable bash script output
7. `SshResolverError.Create()` (permanent) -> "Reload Window"

DNS recovers within seconds, but `coder ssh` has already exited. VS Code does not retry because the error is classified as permanent.

This affects any configuration where `coder ssh` errors produce terminal output that the Remote SSH extension tries to parse as bash script output (i.e. when `useLocalServer` is `false`). With `useLocalServer: true`, the local server manages SSH with its own retry logic and doesn't depend on script parsing, making it more resilient to transient ProxyCommand failures.

A separate but related issue exists with the Coder Connect code path, where a broken tunnel causes a \~55 minute hang before `coder ssh` exits. The retry loop proposed here would eventually recover from that too, but a dial timeout and tailnet fallback are needed to avoid the long wait. See [ENG-2346](https://linear.app/codercom/issue/ENG-2346/coder-ssh-coder-connect-path-has-no-dial-timeout-no-health-check-no).

## Proposed change

Wrap the connection establishment logic in [`cli/ssh.go`](<https://github.com/coder/coder/blob/main/cli/ssh.go>) (handler function, lines \~280-474) in a retry loop with backoff. This covers workspace resolution, API calls, agent readiness checks, and the dial to the workspace.

```go
retryDelays := []time.Duration{0, 2 * time.Second, 5 * time.Second, 10 * time.Second, 10 * time.Second}

for attempt := range retryDelays {
    err := connectAndServe(ctx, ...)
    if err == nil {
        return nil
    }
    if !isRetryable(err) || attempt == len(retryDelays)-1 {
        return err
    }
    logger.Warn(ctx, "connection failed, retrying",
        slog.Error(err), slog.F("attempt", attempt+1))
    select {
    case <-ctx.Done():
        return ctx.Err()
    case <-time.After(retryDelays[attempt]):
    }
}
```

**Error classification:**

| Error | Retryable? | Rationale |
| -- | -- | -- |
| DNS lookup failure | Yes | Resolvers recover within seconds after wake |
| Connection refused / reset | Yes | Network interface may still be coming up |
| Connection timeout | Yes | Transient network issue |
| `DialAgent` failure | Yes | Tailnet coordinator may be temporarily unreachable |
| HTTP 401/403 (auth) | No | Credentials are wrong, retrying won't help |
| HTTP 404 (workspace not found) | No | Workspace doesn't exist |
| Context canceled (SIGINT/SIGHUP) | No | User or SSH parent requested exit |

## Current workaround

A vscode-coder extension PR ([https://github.com/coder/vscode-coder/pull/872](<https://github.com/coder/vscode-coder/pull/872>)) wraps the ProxyCommand with a shell-level retry as a stopgap. This works but is fragile (platform-specific shell behavior, can't classify errors) and only helps VS Code/Cursor users.

## Why the CLI is the right layer

* Covers all editors (VS Code, Cursor, JetBrains, plain SSH)
* Can accurately distinguish transient vs permanent errors
* Avoids platform-specific shell wrapper issues
* Logs retries to the `coder ssh` log file for debugging
* Removes the need for an extension-side ProxyCommand retry wrapper

### PR DESCRIPTION
**Pull request by EhabY**
When `coder ssh` connects to a workspace after laptop wake, DNS or the control plane may be briefly unavailable. Previously this caused an immediate failure, which VS Code Remote SSH classified as permanent ("Reload Window").

Wrap each network step (workspace resolution, template version fetch, agent connection info, Coder Connect dial, tailnet dial) with `retryWithInterval` so transient errors (DNS, connection refused, 5xx) are retried individually. Non-retryable errors (auth, 404) and context cancellation stop immediately. Data transfer is never retried.

Fixes https://github.com/coder/coder/issues/24005

### CODE REVIEW

File: cli/ssh.go [hunk 1]
```diff
@@ -790,6 +422,477 @@ func (r *RootCmd) ssh() *serpent.Command {
...
+	if usageAppName != "" {
+		closeUsage := client.UpdateWorkspaceUsageWithBodyContext(ctx, workspace.ID, codersdk.PostWorkspaceUsageRequest{
+			AgentID: workspaceAgent.ID,
+			AppName: usageAppName,
+		})
+		defer closeUsage()
+	}
+
+	if args.stdio {
+		rawSSH, err := conn.SSH(ctx)
```
Comment (spikecurtis) [inline cli/ssh.go]: This doesn't respect the layering between SSH and the underlying tunnel.

It may make sense to retry tunnel establishment if we are confident the error could be transient, but as soon as the tunnel comes up successfully and we start moving data at the SSH layer, we cannot retry! If we did the server would see data coming in at an arbitrary point in the SSH protocol for a new connection and not have any idea what to do with it.

**Review by spikecurtis — CHANGES_REQUESTED** [review]

File: cli/ssh.go (hunk 1 above)
Comment (EhabY) [reply cli/ssh.go]: Fair, the retry wrapping the entire function doesn't respect the tunnel/SSH layering. It's safe today only because `copier.copy()` swallows errors and returns `nil`. If the data transfer path ever returned a `net.OpError`, `isRetryableError` would match it and the loop would establish a fresh tunnel while OpenSSH keeps sending mid-session data into it.

What do you think about splitting the stdio path into two phases?

1. **Establishment** (`sshEstablishStdioConn`): resolve workspace, wait for agent, dial tunnel. Only this part sits inside the retry loop.
2. **Data transfer** (`sshHandleStdio`): `copier.copy()` / `Bicopy` runs after the loop exits, physically outside it, so retrying once data flows is structurally impossible.

The non-stdio path stays untouched since it was never retried.

**Comment by spikecurtis** [comment]
This still feels half-baked.

1. Just wrapping the whole thing in a retry is a hack. If step 3 fails in some way that is retryable, why do we need to go back to step 1?
2. Why are we only retrying on `--stdio` and not other SSH use cases? Having different logic in those two paths adds a lot of maintenance burden.

**Comment by EhabY** [comment]
The issue is this code here is very monolithic and sequential which makes the maintenance here harder than it should be.

> Just wrapping the whole thing in a retry is a hack. If step 3 fails in some way that is retryable, why do we need to go back to step 1?

True, if the dial fails there's no reason to re-resolve the workspace. The resolve result could be cached and only the dial retried. Right now the establishment function bundles resolve + dial together, so the retry re-does both. I can split it so the resolve happens once and only the dial is retried. Is this worth doing?

> Why are we only retrying on `--stdio` and not other SSH use cases? Having different logic in those two paths adds a lot of maintenance burden.

In interactive mode the user sees the error and can retry manually. In stdio mode, `coder ssh --stdio` runs as a `ProxyCommand` (usually spawned by VS Code), so the user doesn't see the error directly and just gets "connection failed." Transparent retry makes the `ProxyCommand` more resilient on flaky networks. Happy to add retry for interactive mode too if you think it's useful.

**Comment by spikecurtis** [comment]
I agree that the code is not well structured and difficult to maintain. Let's not make the problem worse.

I'm in the process of rearchitecting this code right now, to use a state machine and a new watch on the workspace to replace the workspace and agent resolution code. https://www.notion.so/coderhq/coder-ssh-watch-and-FSM-329d579be59280e3979bfae59051a54e?d=309d579be59283609af183ec14f89244

Still, there will be some initial API requests that get server settings and the like. If we need to include retries, I would much rather wrap individual steps in retries, with an overall context timeout so we don't retry forever. That way you can decide on a step-by-step basis what is transient/retryable, and you don't have to restart the whole process if you hit an error part way through.

**Comment by EhabY** [comment]
~~Oh fair enough, I wasn't aware of this. Should've discussed this with someone beforehand. Should I close this for now and we can handle it after the restructure? Or maybe add a very minimal solution like retrying ONLY Coder Connect TCP dial (`dialer.DialContext`) AND Tailnet dial (separately for stdio only)~~

How about I add per-step retry, can be cancelled by the user (Ctrl + C or killing the parent process etc), and it retries up to X times for each step? I can add a total timeout but I'm not sure about this value because what if this process used to take 60s? 100s? Maybe even more (it had no timeout before).

A follow up here is, do we want to retry only in `stdio` mode or both?

**Comment by spikecurtis** [comment]
> How about I add per-step retry, can be cancelled by the user (Ctrl + C or killing the parent process etc), and it retries up to X times for each step? I can add a total timeout but I'm not sure about this value because what if this process used to take 60s? 100s? Maybe even more (it had no timeout before).

Per step retry sounds fine. Total timeout might get tricky since we wait for the build, so a per-step retry count is probably fine.

> A follow up here is, do we want to retry only in `stdio` mode or both?

I'd prefer to keep things going down the same code paths as we bring up the tunnel. `stdio` is an application-layer concern, so really don't want different behavior down at the tailnet and TCP layer because of it.

File: cli/ssh.go [hunk 2]
```diff
@@ -52,6 +52,10 @@ import (
 
 const (
 	disableUsageApp = "disable"
+
+	// Retry transient errors during SSH connection establishment.
+	sshRetryInterval = 2 * time.Second
+	sshMaxAttempts   = 10 // initial + retries per step
```
Comment (EhabY) [inline cli/ssh.go:58]: `sshMaxAttempts = 5` might be sufficient, this is being a bit generous (or possibly 1s interval with 10 tries)

**Review by spikecurtis — APPROVED** [review]
