### PR TITLE
fix: deprecate codersdk.AITaskPromptParameterName and reduce usage

### LINKED ISSUE #979: chore: tasks: replace exising usage of hard-coded "AI Prompt" parameter with `tasks.prompt`
Blocked by https://github.com/coder/internal/issues/948

Tasks currently have a hard-coded dependency on a parameter named `AI Prompt` (defined as `TaskPromptParameterName` in `coder/terraform-provider-coder`.
This is to be replaced with `tasks.prompt`.

- Deprecate both `codersdk.TaskPromptParameterName` and `provider.TaskPromptParameterName`
- Replace all existing references to this parameter name with `tasks.prompt WHERE tasks.id = ?`

### PR DESCRIPTION
**Pull request by mafredri**
Depends on coder/sqlc#1
Fixes coder/internal#979
Updates coder/internal#973

**Notes:**

- The updated query here requires a patch `sqlc`, without the patch it incorrectly identifies ambigious columns.
  - `queries/workspaces.sql:401:13: column reference "owner_id" is ambiguous` (false positive)

### CODE REVIEW

File: coderd/database/queries/workspaces.sql [hunk 1]
```diff
@@ -351,25 +350,19 @@ WHERE
...
+		THEN sqlc.narg('has_ai_task')::boolean = EXISTS (
+			SELECT
+				1
+			FROM
+				tasks
+			WHERE
+				-- Consider all tasks, deleting a task does not turn the
+				-- workspace into a non-task workspace.
+				tasks.workspace_id = workspaces.id
+		)
```
Comment (mafredri) [inline coderd/database/queries/workspaces.sql:365]: Review: This here breaks with un-patched sqlc because it puts tasks.owner_id in global scope even though it's not selected.

Should we fork sqlc for now?

Comment (johnstcn) [reply coderd/database/queries/workspaces.sql:365]: I'm fine with forking sqlc temporarily while an upstream bug is filed. I wonder if there's also the possibility of selecting `id, workspace_id` from tasks in a CTE and doing the join on that?

**Review by DanielleMaywood — APPROVED** [review]

File: cli/exp_task_list_test.go [hunk 2]
```diff
@@ -43,76 +39,22 @@ func makeAITask(t *testing.T, db database.Store, orgID, adminID, ownerID uuid.UU
...
-
-	return task
+		}).
+		WithAgent().
+		WithTask(database.TaskTable{
+			Prompt: prompt,
+		}, nil).
+		Do()
+
+	return build.Task
```
Comment (johnstcn) [inline cli/exp_task_list_test.go:57]: ❤️

File: coderd/coderd.go [hunk 3]
```diff
@@ -1021,10 +1021,7 @@ func New(options *Options) *API {
 			apiRateLimiter,
 			httpmw.ReportCLITelemetry(api.Logger, options.Telemetry),
 		)
-		r.Route("/aitasks", func(r chi.Router) {
-			r.Use(apiKeyMiddleware)
-			r.Get("/prompts", api.aiTasksPrompts)
-		})
```
Comment (johnstcn) [inline coderd/coderd.go:1027]: I'm potentially concerned about this given our "one minor release" backward compat guarantee. Maybe mark this endpoint deprecated instead?

Comment (mafredri) [reply coderd/coderd.go:1027]: Was this ever used by anything other than the frontend? Considering the route is experimental and you can't run an old coderd with a newer frontend, I imagined this should be fine.

Comment (johnstcn) [reply coderd/coderd.go:1027]: Not that I'm aware, no. I guess we can remove it with the provisio that this was always under `/api/experimental`.

File: coderd/database/queries/workspaces.sql (hunk 1 above)
Comment (Emyrk) [reply coderd/database/queries/workspaces.sql:365]: Can you drop the original bugged sql query? I'm curious to see what the failing/bugged query looked like.

Comment (mafredri) [reply coderd/database/queries/workspaces.sql:365]: @Emyrk This edit IS the bugged query, but check the added testdata in coder/sqlc#1 to see more.

**Review by johnstcn — APPROVED** [review]
