### PR TITLE
test: fix TestCache_DeploymentStats flake

### LINKED ISSUE #961: flake: TestCache_DeploymentStats
**CI Run Link:** https://github.com/coder/coder/actions/runs/17423933022/job/49467317166

**Commit Info:** ee35ad3a572de87ca04760a1438116906149578b by spikecurtis

**Error Analysis:**
```
metricscache_test.go:332: 
    Error Trace:	/home/runner/work/coder/coder/coderd/metricscache/metricscache_test.go:332
    Error:      	Not equal: 
                	expected: 1
                	actual  : 0
    Test:       	TestCache_DeploymentStats
```

**Root Cause:** 
The test expects the deployment stats count to be 1 but receives 0. This appears to be a timing-related flake where the metrics cache hasn't been updated by the time the assertion runs. The test uses a mock clock and fast intervals, but there may be a race condition between the cache refresh and the assertion.

**Related Issues:** 
This may be related to the broader test reliability epic #871.

### PR DESCRIPTION
**Pull request by ethanndickson**
Closes https://github.com/coder/internal/issues/961
Likely the same deal as in #19599, the body of `require.Eventually` now fires immediately, when it used to fire after 250ms (the interval). Presumably, the deployment stats become ready before the vs code session count gets incremented. This was never an issue with the 250ms delay, as this flake has only cropped up after the testify version bump.

We'll fix the issue by making it possible to wait for a full metrics cache refresh, i.e. removing `require.Eventually` in this test altogether.

### CODE REVIEW

**Comment by ethanndickson** [comment]
* **#19683** <a href="https://app.graphite.dev/github/pr/coder/coder/19683?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/19683?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by spikecurtis** [comment]
Can we stop using `Eventually` entirely? Like, make this test actually deterministic?

**Comment by ethanndickson** [comment]
> Can we stop using `Eventually` entirely? Like, make this test actually deterministic?

@spikecurtis I've gone with an approach similar to that used by `dbpurge_test`, though I had to change the way the ticking works slightly. This seems preferable to modifying the API of the metrics cache.

If this approach looks good to you, I'll update the other tests to also no longer use `require.Eventually`.

EDIT: An unrelated test is failing because it calls `clock.Set` with a time after the next `metricscache` tick time (which quartz does not allow).
If we want to go with this solution, we may need to stop piping the clock from `coderdtest.Options` through to `metricscache`, and just always give it a real clock when created as part of a `coderdtest`.
Alternatively, those tests that need to set the clock to a time in the future could just choose really long tick intervals.
WDYT?

File: coderd/metricscache/metricscache.go [hunk 1]
```diff
@@ -198,12 +198,18 @@ func (c *Cache) run(ctx context.Context, name string, interval time.Duration, re
...
+	}
 
+	doRefresh(ctx, c.clock.Now())
+
+	for {
 		select {
-		case <-ticker.C:
+		case tick := <-ticker.C:
+			ticker.Stop()
+			doRefresh(ctx, tick)
```
Comment (spikecurtis) [inline coderd/metricscache/metricscache.go]: the `case <-c.done:` arm of this select is unhittable because a waitgroup on `run()` prevents closing the channel until this function exits.  Without that case, this Ticker/select is now the standard form covered by `c.clock.TickerFunc`. This allows you to force a tick just by advancing the clock, without the need for traps on `Reset`.

However, you still need to set a trap on the call to `TickerFunc` itself, lest advancing the clock race with starting the ticker and leading to a flaky test.

File: coderd/metricscache/metricscache_test.go [hunk 2]
```diff
@@ -47,6 +47,27 @@ func newMetricsCache(t *testing.T, log slog.Logger, clock quartz.Clock, interval
 	return cache, db
 }
 
+func awaitCacheRefresh(ctx context.Context, t *testing.T, clock *quartz.Mock) chan struct{} {
+	t.Helper()
+	ch := make(chan struct{})
+	trapNow := clock.Trap().Now()
```
Comment (spikecurtis) [inline coderd/metricscache/metricscache_test.go]: Setting of the traps races with the function you are trying to test. You need to set your traps _before_ you call the function under test.

**Comment by spikecurtis** [comment]
In general, `clock.Set` is discouraged other than start of test _before_ you pass it to anything.

Also, Quartz mocks are not really designed for integration tests where you have a whole lot of things calling into the clock with different intervals.

File: coderd/metricscache/metricscache.go [hunk 3]
```diff
@@ -181,40 +171,45 @@ func (c *Cache) refreshDeploymentStats(ctx context.Context) error {
...
+		return nil
 	}
+
+	// Call once immediately before starting ticker
+	_ = tickerFunc()
+
+	tkr := c.clock.TickerFunc(ctx, interval, tickerFunc, "metricscache", name)
+	c.tickersMu.Lock()
+	c.tickers = append(c.tickers, tkr)
+	c.tickersMu.Unlock()
```
Comment (spikecurtis) [inline coderd/metricscache/metricscache.go]: This introduces a race where the `Close()` could come before we execute this code, which would complete even though a refresh is still running. The race might not be that hard to hit because you call `tickerFunc()` prior.

File: coderd/coderd.go [hunk 4]
```diff
@@ -459,7 +459,7 @@ func New(options *Options) *API {
 	metricsCache := metricscache.New(
 		options.Database,
 		options.Logger.Named("metrics_cache"),
-		options.Clock,
+		quartz.NewReal(),
```
Comment (spikecurtis) [inline coderd/coderd.go:462]: 🤔

Comment (ethanndickson) [reply coderd/coderd.go:462]: We discussed this and are 'happy' to keep it

File: coderd/metricscache/metricscache_test.go [hunk 5]
```diff
@@ -67,38 +72,47 @@ func TestCache_TemplateWorkspaceOwners(t *testing.T) {
...
-	)
+
+	// Wait for both ticker functions to be created (template build times and deployment stats)
+	trapTickerFunc.MustWait(ctx).MustRelease(ctx)
+	trapTickerFunc.MustWait(ctx).MustRelease(ctx)
+
+	_, wait := clock.AdvanceNext()
+	wait.MustWait(ctx)
+	_, wait = clock.AdvanceNext()
+	wait.MustWait(ctx)
```
Comment (spikecurtis) [inline coderd/metricscache/metricscache_test.go]: You only need to trigger one tick in each of these. Both the template build times and deployment stats have the same interval, so both get triggered on each tick.

Also, I think it's more understandable and concise to write:

```
clock.Advance(time.Minute).MustWait(ctx)
```

**Review by spikecurtis — APPROVED** [review]
Suggestion inline about only triggering a single tick and using Advance rather than AdvanceNext, but I don't need to review again. Nice work.

**Comment by ethanndickson** [comment]
```
~/coder [main] » go test github.com/coder/coder/v2/coderd/metricscache -count=1
ok      github.com/coder/coder/v2/coderd/metricscache   5.099s

~/coder [ethan/deployment-stats-flake] » go test github.com/coder/coder/v2/coderd/metricscache -count=1
ok      github.com/coder/coder/v2/coderd/metricscache   0.118s
```
:tada:
