### PR TITLE
fix: add support for spaces in search & enable searching by display name in templates

### LINKED ISSUE #14384: cannot search template name with spaces
https://github.com/user-attachments/assets/526e4b74-6160-46f9-bd02-07490b72c438

### PR DESCRIPTION
**Pull request by rafrdz**
## Summary

In this pull request we're updating search to support queries with spaces in addition to the `field:value` pattern that is currently supported.

Additionally templates search now defaults to `display_name` (since `display_name` is optional the search will fallback to `name`) when searching without the `field:value` pattern

Closes: https://github.com/coder/coder/issues/14384

### Downsides with searching on `name` and `display_name`

Because the `name` field cannot include spaces, we end up in a situation where including a space in the query will result in no results since the query searches on both `name` AND `display_name`. In the following example, we can see the results of searching by both `name` and `display_name` on these templates:

| Name | Display Name |
| ------ | ------------- |
| docker | Docker Template |
| faketemplate | A Fake Template |
| azure | Fake Azure Template |
| anotherfake | Another Fake Template |
| azurefake | Another Fake Fake Azure Template |

https://github.com/user-attachments/assets/b0e0793e-e77d-46bc-9a42-d7cf4f8bd910

### Proposal: Search on `display_name` by default and allow for `name` using the `field:value` pattern

If we remove `name` from the default template search, we're now able to search with spaces on template `display_names`. Since `display_names` are what users see in the templates list they might expect the search to work this way.

Below is an example of `name` being removed from the default template search.

https://github.com/user-attachments/assets/9aba5911-4960-4384-befb-08ea1acaa3ab

With this approach users would still be able to search on template names by specifying `exact_name:foo`.

### Testing

Added additional test cases to ensure spaces were handled as expected in combination with `field:value` patterns.

### CODE REVIEW

File: coderd/searchquery/search.go [hunk 1]
```diff
@@ -268,8 +268,9 @@ func Templates(ctx context.Context, db database.Store, actorID uuid.UUID, query
 	// Always lowercase for all searches.
 	query = strings.ToLower(query)
 	values, errors := searchTerms(query, func(term string, values url.Values) error {
-		// Default to the template name
+		// Default to the template name and display name
 		values.Add("name", term)
```
Comment (rafrdz) [inline coderd/searchquery/search.go]: See PR description for proposal on removing defaulting to `name` from the default search

**Comment by matifali** [comment]
Can we fallback to the `name` for Templates, when `display_name` is empty?

**Comment by rafrdz** [comment]
> Can we fallback to the name for Templates `display_name` is empty, as it's optional?

To make sure I'm following would you like to search on `display_name` by default and fallback to `name` if `display_name` is empty?

That can be done. Since we would now support spaces in the search queries we'd probably need to update the `name` query to filter out any spaces since `name` cannot have any spaces 🤔

**Comment by matifali** [comment]
> To make sure I'm following would you like to search on display_name by default and fallback to name if display_name is empty?

Yes

File: coderd/searchquery/search.go (hunk 1 above)
Comment (rafrdz) [reply coderd/searchquery/search.go]: Commit https://github.com/coder/coder/pull/19552/commits/8c780dc5c7172e44b6239bc66723f110688bed43 now defaults search to `display_name` and will fallback to `name` if `display_name` is empty as requested in https://github.com/coder/coder/pull/19552#issuecomment-3225245715

**Comment by rafrdz** [comment]
> > To make sure I'm following would you like to search on display_name by default and fallback to name if display_name is empty?
> 
> Yes

Sounds good! Defaulting to `display_name` and falling back to `name` (with spaces removed from query) in https://github.com/coder/coder/pull/19552/commits/8c780dc5c7172e44b6239bc66723f110688bed43

**Comment by matifali** [comment]
Nor directly related but is it possible to stop showing `deprecated:false` in the search nar?

Can it be a hidden default filter that's always true. If someone wants deprecated templates they can set it to `deprecated:true`

**Comment by rafrdz** [comment]
> Nor directly related but is it possible to stop showing `deprecated:false` in the search nar?
> 
> Can it be a hidden default filter that's always true. If someone wants deprecated templates they can set it to `deprecated:true`

We could remove that from the frontend as the default query and update the query to always return `deprecated:false` unless a user specifically asked for `deprecated:true`. The frontend already has a "Deprecated templates" filter that sets `deprecated:true`.

Should we make a new issue for this work?

**Comment by matifali** [comment]
Yes let's create a new issue. Thanks

File: coderd/searchquery/search.go [hunk 2]
```diff
@@ -385,3 +388,21 @@ func splitQueryParameterByDelimiter(query string, delimiter rune, maintainQuotes
 
 	return parts
 }
+
+// processTokens takes the split tokens and groups them based on a delimiter. Tokens
+// without a delimiter present are joined to support searching with spaces.
+func processTokens(tokens []string) []string {
```
Comment (brettkolodny) [inline coderd/searchquery/search.go]: nit: It took me a beat to fully understand what this function was doing even with the comment. Maybe we could add an example or two of input -> output?

**Review by brettkolodny — APPROVED** [review]
Personally I think the UX of our workspace search needs a bit of an improvement, but I think this is a good solution given what we've got!

File: coderd/searchquery/search.go (hunk 2 above)
Comment (rafrdz) [reply coderd/searchquery/search.go]: Good idea! Added an example in https://github.com/coder/coder/pull/19552/commits/d4c1392da1e31b55fccbea9ffcbf18922993cff8

**Review by brettkolodny — APPROVED** [review]
Thank you!
