### PR TITLE
fix: template: enforce bounds of template max_ttl

### LINKED ISSUE #3640: bug: template settings
[Screencast from 08-23-2022 02:37:39 PM.webm](https://user-images.githubusercontent.com/10648092/186152279-ba1e5055-64c5-4692-999f-ee47fa02e89a.webm)
There are multiple issues.

1. Does not allow saving if,

    - Description is longer than some characters. (Show a limit on the length of maximum characters) or show a message if the user exceeds that limit
    - if `MAX_TTL` time is 1 year = 31536000000 milliseconds.

2. Make `MAX_TTL` in hours

3. Allow setting `MAX_TTL` to `inf` or turning off the auto-shutdown for the template.

### PR DESCRIPTION
**Pull request by johnstcn**
This PR makes the following changes:

- enforces lower and upper limits on template `max_ttl_ms`
- adds a migration to enforce 7-day cap on `max_ttl`
- allows setting template `max_ttl` to 0
- updates template edit CLI help to be clearer

Partially fixes https://github.com/coder/coder/issues/3640

### CODE REVIEW

File: coderd/workspaces.go [hunk 1]
```diff
@@ -312,10 +310,10 @@ func (api *API) postWorkspacesByOrganization(rw http.ResponseWriter, r *http.Req
...
 	}
 
-	if !dbTTL.Valid {
-		// Default to min(12 hours, template maximum). Just defaulting to template maximum can be surprising.
-		dbTTL = sql.NullInt64{Valid: true, Int64: min(template.MaxTtl, int64(workspaceDefaultTTL))}
-	}
+	// if !dbTTL.Valid {
+	// Default to min(12 hours, template maximum). Just defaulting to template maximum can be surprising.
+	// dbTTL = sql.NullInt64{Valid: true, Int64: min(template.MaxTtl, int64(workspaceDefaultTTL))}
+	// }
```
Comment (johnstcn) [inline coderd/workspaces.go:316]:
```suggestion
```

**Review by deansheather — APPROVED** [review]

**Review by Emyrk — APPROVED** [review]
LGTM

File: coderd/workspaces.go (hunk 1 above)
Comment (johnstcn) [reply coderd/workspaces.go]: They're gone now!

**Review by Kira-Pilot — APPROVED** [review]
Yay!

**Comment by matifali** [comment]
What does setting `max_ttl` to 0 mean? Turning off auto stop?

**Comment by johnstcn** [comment]
> What does setting `max_ttl` to 0 mean? Turning off auto stop?

Autostop can be enabled on a per-workspace basis. `max_ttl` controls the maximum workspace lifetime.
