### PR TITLE
fix: add some missing workspace updates

### LINKED ISSUE #7186: Server/API is not sending event to workspace/watch when it is failed
Reproduce:
- Create a template where the build will fail like a template with the wrong credentials
- Create a workspace with this template
- You will notice the starting or pending status will remain but if you refresh the page, the status will display failed

Probably cause:
- The API/server is not sending the event on failure as we do for the other statuses

### PR DESCRIPTION
**Pull request by code-asher**
Fixes https://github.com/coder/coder/issues/7186.  Probably.  I was not able to reproduce with a template that had invalid credentials (I used the Heroku template) but I was able to reproduce with the Docker template by deleting my volumes (well I restarted my dev workspace which killed the volumes).

There were two issues:

1. Sometimes a failed job does not have the workspace build type so no workspace update was published.  Fix is to add that type to all workspace build failures (or at least all the ones I found).
2. Sometimes a failed job does not have any state so again no workspace update was published as that is skipped when there is no state.  Fix is to publish an update even when there is no state.

### CODE REVIEW

File: coderd/provisionerdserver/provisionerdserver.go [hunk 1]
```diff
@@ -757,9 +757,6 @@ func (server *Server) FailJob(ctx context.Context, failJob *proto.FailedJob) (*p
 
 	switch jobType := failJob.Type.(type) {
 	case *proto.FailedJob_WorkspaceBuild_:
-		if jobType.WorkspaceBuild.State == nil {
-			break
-		}
```
Comment (code-asher) [inline coderd/provisionerdserver/provisionerdserver.go:762]: I am not sure what this was guarding against so maybe removing it has some unintended consequences...

File: provisionerd/runner/runner.go [hunk 2]
```diff
@@ -1116,6 +1116,7 @@ func (r *Runner) failedJobf(format string, args ...interface{}) *proto.FailedJob
 		JobId:     r.job.JobId,
 		Error:     message,
 		ErrorCode: code,
+		Type:      &proto.FailedJob_WorkspaceBuild_{},
```
Comment (code-asher) [inline provisionerd/runner/runner.go:1119]: I was able to trigger this by using the Docker template, creating a workspace, deleting my Docker volumes, then trying to start the workspace again.

It does not trigger through the unit test.  Not sure how to make it take this code path.

File: coderd/workspaces_test.go [hunk 3]
```diff
@@ -1733,13 +1733,37 @@ func TestWorkspaceWatcher(t *testing.T) {
...
 	err = client.UpdateActiveTemplateVersion(ctx, template.ID, codersdk.UpdateActiveTemplateVersion{
-		ID: template.ActiveVersionID,
+		ID: updatedVersion.ID,
 	})
 	require.NoError(t, err)
 	wait("update active template version", nil)
 
-	cancel()
+	// Build with the new template; should end up with a failure state.
+	_ = coderdtest.CreateWorkspaceBuild(t, client, workspace, database.WorkspaceTransitionStart, func(req *codersdk.CreateWorkspaceBuildRequest) {
```
Comment (code-asher) [inline coderd/workspaces_test.go:1758]: For some reason creating this build fails the test, somewhere I think there is an assertion that the provisioner has no errors or something.

Comment (code-asher) [reply coderd/workspaces_test.go:1761]: Turns out it was the logger failing the test due to an error log when testing the failure state.

This implies to me that the logger's opinion is either that testing failures is an anti-pattern (which seems wrong) or that a provisioner job failing does not qualify to be logged as an error (could maybe change it to a warning).

For now I added a bool to disable this behavior rather than globally disable it or change the log level.

File: coderd/provisionerdserver/provisionerdserver.go (hunk 1 above)
Comment (code-asher) [reply coderd/provisionerdserver/provisionerdserver.go:762]: I added it back but only gated the update behind it since that appears specifically for updating the state and I suppose we might not want to do that when no state was included but we still want the publish.

File: provisionerd/runner/runner.go [hunk 4]
```diff
@@ -1102,6 +1102,12 @@ func (r *Runner) runWorkspaceBuild(ctx context.Context) (*proto.CompletedJob, *p
 	}, nil
 }
 
+func (r *Runner) failedWorkspaceBuildf(format string, args ...interface{}) *proto.FailedJob {
```
Comment (code-asher) [inline provisionerd/runner/runner.go:1105]: I feel like there must be a better way to do this...maybe `failedJobf().withWorkspaceBuildType()` or something but `proto.FailedJob` is generated so not sure how to add that.

File: coderd/coderdtest/coderdtest.go [hunk 5]
```diff
@@ -134,6 +134,10 @@ type Options struct {
 	ConfigSSH codersdk.SSHConfigResponse
 
 	SwaggerEndpoint bool
+
+	// LoggerIgnoreErrors causes the test logger to not fatal the test on Fatal
+	// and not error the test on Error or Critical.
+	LoggerIgnoreErrors bool
```
Comment (kylecarbs) [inline coderd/coderdtest/coderdtest.go:140]: I'm not sure we should make this an option... if an error isn't a failure, we should change the log.

If I'm misunderstanding, please link the log in question so I can take a closer look 🕵️🕵️🕵️

File: provisionerd/runner/runner.go (hunk 4 above)
Comment (kylecarbs) [reply provisionerd/runner/runner.go:1105]: Meh, I think this is fine

**Review by kylecarbs — APPROVED** [review]

File: coderd/coderdtest/coderdtest.go (hunk 5 above)
Comment (code-asher) [reply coderd/coderdtest/coderdtest.go:140]: Yeah I was quite conflicted about this.  It implies to me that the logger's opinion is either that testing failures is an anti-pattern or that a workspace build job failing does not qualify to be logged as an error.

I believe it was this log here: https://github.com/coder/coder/blob/467b0a10046337570b9a7d21f6e4609c79ecf809/provisionerd/runner/runner.go#L929-L932

Maybe this should only be warning level?

Comment (kylecarbs) [reply coderd/coderdtest/coderdtest.go:140]: Ahh, yes. I'd say warning level is fine!
