### PR TITLE
fix: improve checkbox text in template schedule settings dialog

### LINKED ISSUE #13344: Weird confirmation for dormancy warning in template schedule settings
If you set the dormancy threshold to a value that stages existing workspaces for deletion, you get this warning:

Screenshot 2024-05-22 at 9 27 51 AM

The "Reset" button feels ambiguous. It should read "Reset workspace inactivity timers".

### PR DESCRIPTION
**Pull request by jaaydenh**
Fixes #13344 

- Update ScheduleDialog text
- Add storybook story for ScheduleDialog

### CODE REVIEW

**Comment by jaaydenh** [comment]
I have read the CLA Document and I hereby sign the CLA

File: site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx [hunk 1]
```diff
@@ -68,11 +67,12 @@ export const ScheduleDialog: FC<ScheduleDialogProps> = ({
             <>
               <h4>Dormancy Threshold</h4>
               <p css={styles.dialogDescription}>
-                This change will result in {inactiveWorkspacesToGoDormant}{" "}
-                workspaces being immediately transitioned to the dormant state
-                and {inactiveWorkspacesToGoDormantInWeek} over the next seven
-                days. To prevent this, do you want to reset the inactivity
-                period for all template workspaces?
+                This change will result in{" "}
+                <strong>{inactiveWorkspacesToGoDormant}</strong> workspace(s)
```
Comment (aslilac) [inline site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx:71]:
```suggestion
                <strong>{inactiveWorkspacesToGoDormant}</strong> {inactiveWorkspacesToGoDormant === 1 ? "workspace" : "workspaces"}
```

we tend to avoid the parenthesized (s) in our language

File: site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx [hunk 2]
```diff
@@ -68,11 +67,12 @@ export const ScheduleDialog: FC<ScheduleDialogProps> = ({
...
+                being immediately transitioned to the dormant state and{" "}
+                <strong>{inactiveWorkspacesToGoDormantInWeek}</strong> over the
```
Comment (aslilac) [inline site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx:73]: can we have it say "workspace"/"workspaces" here as well?

```suggestion
                <strong>{inactiveWorkspacesToGoDormantInWeek}</strong> {inactiveWorkspacesToGoDormantInWeek === 1 ? "workspace" : "workspaces"} over the
```

File: site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx [hunk 3]
```diff
@@ -84,35 +84,34 @@ export const ScheduleDialog: FC<ScheduleDialogProps> = ({
...
-                        updateDormantWorkspaces(e.target.checked);
-                      }}
-                    />
-                  }
-                  label="Reset"
-                />
-              </Stack>
+              <p css={styles.dialogDescription}>
+                This change will result in{" "}
+                <strong>{dormantWorkspacesToBeDeleted}</strong> workspace(s)
```
Comment (aslilac) [inline site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx:97]: same here

File: site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx [hunk 4]
```diff
@@ -84,35 +84,34 @@ export const ScheduleDialog: FC<ScheduleDialogProps> = ({
...
+                being immediately deleted and{" "}
+                <strong>{dormantWorkspacesToBeDeletedInWeek}</strong> over the
```
Comment (aslilac) [inline site/src/pages/TemplateSettingsPage/TemplateSchedulePage/ScheduleDialog.tsx:99]: same here

**Review by aslilac — APPROVED** [review]
this looks great! just a couple small language changes that would be nice, but the code looks good
