### PR TITLE
fix: add cache for terraform installer files

### LINKED ISSUE #1126: flake: TestInstall (provisioner/terraform) on macOS arm64
CI Run: https://github.com/coder/coder/actions/runs/19353959038
Commit: fe3b825b86c0875898a716d2c03b087aa88af0f9 (Steven Masley)

Summary
- Job: test-go-pg (macos-latest)
- Package: github.com/coder/coder/v2/provisioner/terraform
- Failing test: TestInstall
- Root cause classification: Code change in test (platform-specific setup)

Error evidence (from logs)
```
=== FAIL: provisioner/terraform TestInstall (0.73s)
install_test.go:223: 
    Error:      Received unexpected error:
                install:
                    github.com/coder/coder/v2/provisioner/terraform.Install
                        /Users/runner/work/coder/coder/provisioner/terraform/install.go:109
                  - no ZIP archive found for terraform 1.13.4 darwin/arm64
Test:       TestInstall
```

Why this is happening
- Recent change edf056babc3932cbfeebec29765b8531b0a529fd (test: add mocked terraform installation files) updated TestInstall to use a fake HTTP server that serves only linux/amd64 artifacts.
- On macOS runners (darwin/arm64), hc-install queries for darwin/arm64, which is not present in the mocked index, causing the error above.

Precise assignment analysis
- Test function and mock data introduced/modified by: edf056babc3932cbfeebec29765b8531b0a529fd by Paweł Banaszewski.
  - install_test.go defines createFakeTerraformInstallationFiles and versionedJSON to only include linux_amd64 builds, e.g.:
    - zipFilename: `terraform_%s_linux_amd64.zip`
    - Builds: `{ OS: "linux", Arch: "amd64" }`
  - TestInstall passes the fake server base URL to Install, so platform-specific selection happens against this mocked catalog.

Related issues
- Closed as fixed (different root cause): https://github.com/coder/internal/issues/72 (TestInstall reached out to the internet). This is a new platform-specific catalog issue.

Proposed fix
- Extend the mocked product catalog and files to include the current runner’s GOOS/GOARCH (at minimum darwin/arm64 alongside linux/amd64), or adjust the test to force linux/amd64 selection irrespective of host platform.
- Optionally add a CI-only skip or guard for unsupported platforms if mocking multiple platforms is non-trivial.

Reproduction
- Run TestInstall on macOS arm64 (macos-latest). The fake server lacks darwin/arm64, leading to the error above.

### PR DESCRIPTION
**Pull request by pawbana**
Replaces mocks by simple proxy that caches terraform files using test cache https://github.com/coder/coder/blob/16b8e6072fd84f45404e3f84bb2b6fea2424b090/testutil/cache.go#L13
Fixes: https://github.com/coder/internal/issues/1126

### CODE REVIEW

File: provisioner/terraform/install_test.go [hunk 1]
```diff
@@ -101,8 +136,42 @@ func mainJSON(versions ...*version.Version) product {
 	return mj
 }
 
-func exeContent(v *version.Version) []byte {
-	return []byte(strings.ReplaceAll(terraformExecutableTemplate, "${ver}", v.String()))
+func mustCreateZips(t *testing.T, tmpDir string, v *version.Version) {
+	for _, oa := range allArchs {
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: oa?

File: provisioner/terraform/install_test.go [hunk 2]
```diff
@@ -101,8 +136,42 @@ func mainJSON(versions ...*version.Version) product {
 	return mj
 }
 
-func exeContent(v *version.Version) []byte {
-	return []byte(strings.ReplaceAll(terraformExecutableTemplate, "${ver}", v.String()))
+func mustCreateZips(t *testing.T, tmpDir string, v *version.Version) {
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: nit: should we mark v non-nullable?

File: provisioner/terraform/install_test.go [hunk 3]
```diff
@@ -101,8 +136,42 @@ func mainJSON(versions ...*version.Version) product {
...
+	for _, oa := range allArchs {
+		rep := strings.NewReplacer("${ver}", v.String(), "${os}", oa.os, "${arch}", oa.arch)
+		exeContent := rep.Replace(bashExecutableTemplate)
+		if oa.os == "windows" {
+			exeContent = rep.Replace(windowsExecutableTemplate)
+		}
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: don't need to run replace twice (if-else)

File: provisioner/terraform/install_test.go [hunk 4]
```diff
@@ -101,8 +136,42 @@ func mainJSON(versions ...*version.Version) product {
...
+
+		// `${version}/${os}_${arch}.zip`
+		zip1, err := os.Create(filepath.Join(tmpDir, version1.String(), zipFilename(v, oa.os, oa.arch)))
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: shouldn't you `Close()` zip1, zip1writer, exe, etc. (resource leak)?

File: provisioner/terraform/install_test.go [hunk 5]
```diff
@@ -28,24 +29,53 @@ import (
...
 {
   "terraform_version": "${ver}",
-  "platform": "linux_amd64",
+  "platform": "${os}_${arch}",
   "provider_selections": {},
   "terraform_outdated": true
 }
 EOF
+`
+	windowsExecutableTemplate = `echo {^
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: confidence check: did you manually check this on Windows?

File: provisioner/terraform/install_test.go (hunk 2 above)
Comment (mtojek) [inline provisioner/terraform/install_test.go]: I think you can split this function into multiple shorter ones for readability purposes:

`createZipForPlatform`, `generateExecutableContent`, `writeExecutableToZip`, `writeLicenseToZip`, etc. I think you know what I mean :)

File: provisioner/terraform/install_test.go (hunk 5 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go]: Kind of manually. I'm checking it by manually triggering nightly-gauntlet https://github.com/coder/coder/actions/runs/19363858133/job/55402011876#step:11:1006

It doesn't work in this form : (

Comment (mtojek) [reply provisioner/terraform/install_test.go]: This might be a wild guess:

```
    t.go:106: 2025-11-14 12:09:44.378 [debu]  stdlib: unpacking terraform to C:\Users\ADMINI~1\AppData\Local\Temp\TestInstall200751571\001
    t.go:106: 2025-11-14 12:09:44.378 [debu]  stdlib: unpacking LICENSE.txt to C:\Users\ADMINI~1\AppData\Local\Temp\TestInstall200751571\001
    t.go:106: 2025-11-14 12:09:44.379 [debu]  stdlib: deleted unpacked archive at C:\Users\ADMINI~1\AppData\Local\Temp\terraform_1.13.4_windows_amd64.zip664676320
    t.go:106: 2025-11-14 12:09:44.379 [debu]  stdlib: changing perms of C:\Users\ADMINI~1\AppData\Local\Temp\TestInstall200751571\001\terraform.exe
    install_test.go:244: 
        	Error Trace:	C:/actions-runner/coder/coder/provisioner/terraform/install_test.go:244
        	            				C:/Users/Administrator/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.10.windows-amd64/src/runtime/asm_amd64.s:1700
        	Error:      	Received unexpected error:
        	            	install:
        	            	    github.com/coder/coder/v2/provisioner/terraform.Install
        	            	        C:/actions-runner/coder/coder/provisioner/terraform/install.go:109
        	            	  - chmod C:\Users\ADMINI~1\AppData\Local\Temp\TestInstall200751571\001\terraform.exe: The system cannot find the file specified.
        	Test:       	TestInstall
```

It chmods `terraform.exe`, but unpacks `terraform` instead of `terraform.exe` (see: `stdlib: unpacking terraform to`).

Comment (pawbana) [reply provisioner/terraform/install_test.go]: This is a run from first commit (https://github.com/coder/coder/pull/20776/commits/9eb35d5cb463994eceb92fd96a160e4711570f44) where windows specific logic was missing (exe / filename).

Hoping this one will be fine: https://github.com/coder/coder/actions/runs/19370758043 (it uses last commit:  https://github.com/coder/coder/commit/6bee8db2c9ab30206c7b8831b5c5100a2f99738d)

**Comment by pawbana** [comment]
I think https://github.com/coder/coder/pull/20776/commits/69021e733779491c3c45edf7d198d7debda0cf84 works although it is quite ugly: https://github.com/coder/coder/actions/runs/19376939370/job/55446613426 (some other test fails)
```
ok  	github.com/coder/coder/v2/provisioner/terraform	4.310s

...

=== FAIL: enterprise/coderd  (0.00s)
FAIL	github.com/coder/coder/v2/enterprise/coderd [build failed]

=== Errors
Error: enterprise\coderd\workspaces_test.go:3403:28: undefined: testutil.CacheTFProviders
```

File: provisioner/terraform/install_test.go [hunk 6]
```diff
@@ -101,8 +145,82 @@ func mainJSON(versions ...*version.Version) product {
...
+}
+
+// for windows it seems some progmram complication is required
+func windowsExeContent(t *testing.T, tmpDir string, v *version.Version, platform osArch) []byte {
+	code := fmt.Sprintf(windowsExecutableGoSourceCodeTemplate, v, platform.arch)
+	require.NoError(t, os.WriteFile(filepath.Join(tmpDir, "fake-terraform.go"), []byte(code), 0o600))
+
+	var errbuf strings.Builder
+	if _, err := os.Stat(filepath.Join(tmpDir, "go.mod")); errors.Is(err, os.ErrNotExist) {
+		cmd := exec.Command("go", "mod", "init", "fake-terraform")
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: Thinking loud -

Since you have logic to dynamically create a fake terraform binary, can we use it for all cases, I mean mac/linux/windows? 
Also, if the binary runs on the same platform as testing code, can it dynamically figure out the os and arch?

I'm curious if we can get rid of those if-windows clauses in favor of generic code for all platforms.

File: provisioner/terraform/install_test.go [hunk 7]
```diff
@@ -101,8 +145,82 @@ func mainJSON(versions ...*version.Version) product {
...
+// for linux/mac simple script works
+func unixExeContent(t *testing.T, v *version.Version, platform osArch) []byte {
+	rep := strings.NewReplacer("${ver}", v.String(), "${os}", platform.os, "${arch}", platform.arch)
+	return []byte(rep.Replace(bashExecutableTemplate))
+}
+
+// for windows it seems some progmram complication is required
+func windowsExeContent(t *testing.T, tmpDir string, v *version.Version, platform osArch) []byte {
+	code := fmt.Sprintf(windowsExecutableGoSourceCodeTemplate, v, platform.arch)
+	require.NoError(t, os.WriteFile(filepath.Join(tmpDir, "fake-terraform.go"), []byte(code), 0o600))
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: Re `fake-terraform.go`: does it have to be dynamically created file? Can we add a special package under testdata with .go sources?

File: provisioner/terraform/install_test.go [hunk 8]
```diff
@@ -101,8 +145,82 @@ func mainJSON(versions ...*version.Version) product {
...
 
-func exeContent(v *version.Version) []byte {
-	return []byte(strings.ReplaceAll(terraformExecutableTemplate, "${ver}", v.String()))
+// for linux/mac simple script works
+func unixExeContent(t *testing.T, v *version.Version, platform osArch) []byte {
+	rep := strings.NewReplacer("${ver}", v.String(), "${os}", platform.os, "${arch}", platform.arch)
+	return []byte(rep.Replace(bashExecutableTemplate))
+}
+
+// for windows it seems some progmram complication is required
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: typo: progmram complication

File: provisioner/terraform/install_test.go [hunk 9]
```diff
@@ -101,8 +145,82 @@ func mainJSON(versions ...*version.Version) product {
...
+	}
+	exeContent, err := os.ReadFile(exePath)
+	require.NoError(t, err)
+	return exeContent
+}
+
+func mustCreateZips(t *testing.T, tmpDir string, v *version.Version) {
+	for _, platform := range allPlatforms {
+		if platform.os != runtime.GOOS || platform.arch != runtime.GOARCH {
+			// only zip for platform on which test is being run is needed
```
Comment (mtojek) [inline provisioner/terraform/install_test.go]: makes sense, but do we need to keep `allPlatforms` or can we dynamically determine `runtime.GOOS` and `runtime.GOARCH`

**Review by mtojek — COMMENTED** [review]
I think you skipped some of comments from past iterations.

**Comment by mtojek** [comment]
> I think https://github.com/coder/coder/commit/69021e733779491c3c45edf7d198d7debda0cf84 works although it is quite ugly: https://github.com/coder/coder/actions/runs/19376939370/job/55446613426 (some other test fails)

@pawbana Hmm.. I admit I can't figure out the fix from the commit history. What was the root cause?

File: provisioner/terraform/install_test.go (hunk 9 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go]: Setting it dynamically should work.

**Comment by pawbana** [comment]
> > I think [69021e7](https://github.com/coder/coder/commit/69021e733779491c3c45edf7d198d7debda0cf84) works although it is quite ugly: https://github.com/coder/coder/actions/runs/19376939370/job/55446613426 (some other test fails)
> 
> @pawbana Hmm.. I admit I can't figure out the fix from the commit history. What was the root cause?

Root cause is my first attempt to mock terraform installation files and not being aware I should also prepare mac/windows versions: https://github.com/coder/coder/commit/edf056babc3932cbfeebec29765b8531b0a529fd (I've asked if I should revert it but was told it is fine to leave it failing for short time).

File: provisioner/terraform/install_test.go (hunk 6 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go]: We could do that, although I'd rather avoid compiling if possible. I'd like to check if there is no other way for windows.
If compilation was windows is required then still I think it may be better to avoid it for linux/mac.

File: provisioner/terraform/install_test.go (hunk 7 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go]: Yes is compilation would be required I plan to do so.

File: provisioner/terraform/install_test.go (hunk 6 above)
Comment (pawbana) [reply provisioner/terraform/install_test.go]: Talked with @hugodutka a bit and decided to go with cached proxy approach. Installers are cached in test cache and only downloaded on cache miss.

**Comment by pawbana** [comment]
nightly-gauntlet fails due to unrelated reason but test passes: https://github.com/coder/coder/actions/runs/19435271482/job/55604365354#step:11:325

```
=== Failed
=== FAIL: enterprise/coderd  (0.00s)
FAIL	github.com/coder/coder/v2/enterprise/coderd [build failed]

=== Errors
Error: enterprise\coderd\workspaces_test.go:3403:28: undefined: testutil.CacheTFProviders


DONE 12046 tests, 131 skipped, 1 failure, 1 error in 426.864s
```

File: provisioner/terraform/install_test.go [hunk 10]
```diff
@@ -205,8 +127,11 @@ func TestInstall(t *testing.T) {
 	dir := t.TempDir()
 	log := testutil.Logger(t)
 
-	tmpDir := createFakeTerraformInstallationFiles(t)
-	addr := startFakeTerraformServer(t, tmpDir)
+	proxy := persistentlyCachedProxy(t)
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go:129]:
```suggestion
    // lets us cache terraform binaries between test runs to improve CI flakiness
	proxy := persistentlyCachedProxy(t)
```

**Review by hugodutka — APPROVED** [review]
LGTM

File: provisioner/terraform/install_test.go [hunk 11]
```diff
@@ -6,12 +6,13 @@
 package terraform_test
 
 import (
-	"archive/zip"
 	"context"
-	"encoding/json"
-	"fmt"
+	_ "embed"
```
Comment (hugodutka) [inline provisioner/terraform/install_test.go]: do we need `embed`?

**Comment by mtojek** [comment]
I see you have already merged the PR. Next time please give reviewers more time to  gain more 👍, unless it is emergency.

I can’t review it the regular way as Github fails with “Issue is locked”, so here is my review:

1. Why do we need WriteTimeout and ReadTimeout? Why 30 sec?
2. You can use RWMutex instead, and just lock the server when actually modifying the cache directory.
3. Can we determine terraform version and download the terraform binary before running the test? No need to fiddle with mutexes. 

BTW, these can be improved in follow-ups.
