### PR TITLE
fix: correct connection_median_latency_ms in query

### LINKED ISSUE #14805: Some users reporting 0ms latency on template insights
May be related to recent usage query changes, or may have been there before those changes, not 100% sure. Most likely the issue is we are selecting a latest stat somewhere with a 0ms instead of correctly selecting max from the period. Most likely related to a specific type of session since it only seems to affect some users. 

Screenshot 2024-09-25 at 2 22 24 PM

### PR DESCRIPTION
**Pull request by f0ssel**
Closes https://github.com/coder/coder/issues/14805

### CODE REVIEW

File: coderd/database/queries/insights.sql [hunk 1]
```diff
@@ -661,7 +661,7 @@ WITH
 			AND date_trunc('minute', was.created_at) = mb.minute_bucket
 			AND was.template_id = mb.template_id
 			AND was.user_id = mb.user_id
-			AND was.connection_median_latency_ms >= 0
```
Comment (f0ssel) [inline coderd/database/queries/insights.sql:664]: This is the bug fix, in other queries that use `connection_median_latency_ms` we always filter our the 0 values to rule out any usage stats.

File: coderd/database/queries/workspaceagentstats.sql [hunk 2]
```diff
@@ -332,9 +333,11 @@ WITH agent_stats AS (
 		agent_id,
 		workspace_id,
 		coalesce(SUM(rx_bytes), 0)::bigint AS rx_bytes,
-		coalesce(SUM(tx_bytes), 0)::bigint AS tx_bytes
+		coalesce(SUM(tx_bytes), 0)::bigint AS tx_bytes,
+		coalesce(MAX(connection_median_latency_ms), 0)::float AS connection_median_latency_ms
 	FROM workspace_agent_stats
-	WHERE workspace_agent_stats.created_at > $1
+	-- The greater than 0 is to support legacy agents that don't report connection_median_latency_ms.
+	WHERE workspace_agent_stats.created_at > $1 AND connection_median_latency_ms > 0
```
Comment (f0ssel) [inline coderd/database/queries/workspaceagentstats.sql:340]: This is another fix I found along the way where we weren't filtering out the stats with 0 or selecting only recent stats.

**Review by ethanndickson — APPROVED** [review]
Nice catches!
