### PR TITLE
fix(cli): speed up CLI over SSH

### LINKED ISSUE #7884: All commands take a long time to complete
E.g., `coder --help` takes 750ms for me.

### PR DESCRIPTION
**Pull request by ammario**
By caching the terminal's color profile, we avoid myriad
round trips during command execution.

Resolves #7884

### CODE REVIEW

File: cli/portforward.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ import (
 
 	"github.com/coder/coder/agent/agentssh"
 	"github.com/coder/coder/cli/clibase"
+
```
Comment (coadler) [inline cli/portforward.go:20]: bunch of these for some reason

**Review by coadler — APPROVED** [review]

File: cli/portforward.go (hunk 1 above)
Comment (ammario) [reply cli/portforward.go]: A careful eye on this one. Impressive.

Comment (coadler) [reply cli/portforward.go]: I love my proper import formatting
