### PR TITLE
fix(site): fix parameters' request upon template variables update

### LINKED ISSUE #11870: constantly prompted for missing variables when entering template editor
Steps to reproduce: 

1. Use a template with variables (e.g. Kubernetes)
2. Enter the template editor

https://github.com/coder/coder/assets/22407953/f626c34d-073b-4bf6-87ac-3891d494aec2

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Fix https://github.com/coder/coder/issues/11870

### CODE REVIEW

File: site/src/pages/TemplateVersionEditorPage/ProvisionerTagsPopover.tsx [hunk 1]
```diff
@@ -111,18 +111,13 @@ export const ProvisionerTagsPopover: FC<ProvisionerTagsPopoverProps> = ({
...
-                        <ProvisionerTag
-                          key={k}
-                          k={k}
-                          v={tags[k]}
-                          onDelete={onDelete}
-                        />
+                        <ProvisionerTag k={k} v={tags[k]} onDelete={onDelete} />
                       )}
-                    </>
+                    </Fragment>
```
Comment (aslilac) [inline site/src/pages/TemplateVersionEditorPage/ProvisionerTagsPopover.tsx:120]: this doesn't even need to be a fragment, both branches only return one element. I guess it's nice to only specify the key in one place tho.

**Review by aslilac — APPROVED** [review]

File: site/src/pages/TemplateVersionEditorPage/ProvisionerTagsPopover.tsx (hunk 1 above)
Comment (BrunoQuaresma) [reply site/src/pages/TemplateVersionEditorPage/ProvisionerTagsPopover.tsx:120]: Yes!
