### PR TITLE
fix: user status change chart accommodates DST

### LINKED ISSUE #464: flake: `TestGetUserStatusCounts`
Looks like this test has broken with the US moving to daylight savings, it only runs with postgres and it's failed on all postgres-using CI jobs.
https://github.com/coder/coder/actions/runs/13752449408
https://github.com/coder/coder/actions/runs/13756567387

e.g.
```
=== FAIL: coderd/database TestGetUserStatusCounts/America/New_York/User_deleted_during_query_range (0.53s)
    t.go:106: 2025-03-09 21:04:28.690 [debu]  pubsub: pubsub dialing postgres  network=tcp  address=127.0.0.1:5432  timeout_ms=0
    t.go:106: 2025-03-09 21:04:28.690 [debu]  pubsub: pubsub postgres TCP connection established  network=tcp  address=127.0.0.1:5432  timeout_ms=0  elapsed_ms=0
    t.go:106: 2025-03-09 21:04:28.716 [debu]  pubsub: pubsub connected to postgres
    t.go:106: 2025-03-09 21:04:28.716 [debu]  pubsub: pubsub has started
    querier_test.go:3334: 
        	Error Trace:	/home/runner/work/coder/coder/coderd/database/querier_test.go:3334
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestGetUserStatusCounts/America/New_York/User_deleted_during_query_range
    t.go:106: 2025-03-09 21:04:29.077 [info]  pubsub: pubsub is closing
    t.go:106: 2025-03-09 21:04:29.077 [info]  pubsub: pubsub listen stopped receiving notify
    t.go:106: 2025-03-09 21:04:29.077 [debu]  pubsub: pubsub closed
```

### PR DESCRIPTION
**Pull request by SasSwart**
closes https://github.com/coder/internal/issues/464

# Summary

This PR resolves a flaky test that was sensitive to DST transitions in various time zones. The root of the flake was:
* a bug; the query and its tests assume 24 hours per day
* the tests used local system time, which resulted in failures for dates proximal to DST transitions

# Changes

Query:

The original query assumed 24 hour intervals between each day, which is not a valid assumption. It now increments `1 day` at a time.

Database tests:

Database level tests for the query all assumed 24 hour days. They now increment in DST-aware days instead. Instead of using time.Now() as a base for testing, the test uses a series of dates over the course of an entire year, to ensure that DST transition dates are present in every test run.

# API Endpoint

The endpoint that delivers the user status chart now accepts an IANA timezone name as a parameter and passes it, keeping the existing offset as a fallback, to the database query.

API level tests were added to ensure the correct response form and error behaviour. Correctness of content is tested at the database level.

### CODE REVIEW

File: coderd/database/queries/insights.sql [hunk 1]
```diff
@@ -805,36 +805,26 @@ GROUP BY utp.num, utp.template_ids, utp.name, utp.type, utp.display_name, utp.de
...
+	-- latest_status_before_range selects the last status of each user before the start_time.
+	-- This represents the status of all users at the start of the time range.
 latest_status_before_range AS (
     SELECT
         DISTINCT usc.user_id,
         usc.new_status,
         usc.changed_at,
         ud.deleted
     FROM user_status_changes usc
+	INNER JOIN users u ON u.id = usc.user_id AND NOT u.is_system
```
Comment (mafredri) [inline coderd/database/queries/insights.sql]: **Tip:** `INNER` is implicit in plain `JOIN`, so it can be omitted. It's not wrong, but I'd recommend staying consistent at minimum per query (I did not check the query beyond diff).


In the past we checked against magic UUID, have we eradicated all such use or would it be beneficial here to avoid the join?

I'm also not familiar with why system users have user status changes, is it valid or an oversight?

File: coderd/database/queries/insights.sql [hunk 2]
```diff
@@ -879,16 +865,15 @@ relevant_status_changes AS (
         new_status,
         changed_at
     FROM status_changes_during_range
-    WHERE NOT deleted
+    WHERE NOT deleted -- TODO(sasswart): move this clause to the CTE above.
```
Comment (DanielleMaywood) [inline coderd/database/queries/insights.sql]: Are these two TODOs meant to be actioned in the future or in this change?

File: coderd/database/queries/insights.sql [hunk 3]
```diff
@@ -862,15 +850,13 @@ status_changes_during_range AS (
...
-	-- relevant_status_changes defines the status of each user at any point in time.
-	-- It includes the status of each user before the start_time, and the status of each user during the start_time and end_time.
 relevant_status_changes AS (
     SELECT
         user_id,
         new_status,
         changed_at
     FROM latest_status_before_range
-    WHERE NOT deleted
+    WHERE NOT deleted -- TODO(sasswart): move this clause to the CTE above.
```
Comment (mafredri) [inline coderd/database/queries/insights.sql]: I guess it depends. Is deleted a part of the statistics? If yes, perhaps it can't be moved? If not, you could just do it here instead of adding a TODO?

File: coderd/database/queries/insights.sql (hunk 2 above)
Comment (SasSwart) [reply coderd/database/queries/insights.sql]: I'd like to get to them in the future, but there's no blocking influence or anything that allows me to specify when in the comment as I would have liked. Its simply that: 
* I've spent way too much time on this ticket already
* There's no obvious value to doing this, it would just be more readable and less surprising
* The cost to measure and verify the change thoroughly right now outweighs its value.

If you don't like todo comments without clear actionable triggers, I can remove them?

File: coderd/insights.go [hunk 4]
```diff
@@ -306,8 +307,8 @@ func (api *API) insightsUserStatusCounts(rw http.ResponseWriter, r *http.Request
 
 	p := httpapi.NewQueryParamParser()
 	vals := r.URL.Query()
+	timezone := p.String(vals, "", "timezone")
 	tzOffset := p.Int(vals, 0, "tz_offset")
-	interval := p.Int(vals, int((24 * time.Hour).Seconds()), "interval")
```
Comment (mafredri) [inline coderd/insights.go:310]: What's the repercussion of removing this? It's not part of our public API?

File: coderd/insights.go [hunk 5]
```diff
@@ -318,16 +319,34 @@ func (api *API) insightsUserStatusCounts(rw http.ResponseWriter, r *http.Request
...
+		if tzOffset > 0 {
+			timezone = fmt.Sprintf("Etc/GMT-%d", tzOffset)
+		} else if tzOffset < 0 {
+			timezone = fmt.Sprintf("Etc/GMT+%d", -tzOffset)
+		}
+	}
+
+	loc, err := time.LoadLocation(timezone)
+	if err != nil {
+		httpapi.Write(ctx, rw, http.StatusBadRequest, codersdk.Response{
```
Comment (mafredri) [inline coderd/insights.go:342]: I guess this could also be an internal server error, but I guess this will be right most of the time.

File: coderd/insights.go [hunk 6]
```diff
@@ -318,16 +319,34 @@ func (api *API) insightsUserStatusCounts(rw http.ResponseWriter, r *http.Request
...
 	sixtyDaysAgo := dbtime.StartOfDay(nextHourInLoc).AddDate(0, 0, -60)
 
-	rows, err := api.Database.GetUserStatusCounts(ctx, database.GetUserStatusCountsParams{
+	queryParams := database.GetUserStatusCountsParams{
 		StartTime: sixtyDaysAgo,
 		EndTime:   nextHourInLoc,
-		// #nosec G115 - Interval value is small and fits in int32 (typically days or hours)
-		Interval: int32(interval),
-	})
+		Tz:        loc.String(),
```
Comment (mafredri) [inline coderd/insights.go]: Verify: Go timezones map 1-to-1 to PostgreSQL timezones.

File: site/src/api/api.ts [hunk 7]
```diff
@@ -2468,9 +2468,11 @@ class ApiMethods {
 	};
 
 	getInsightsUserStatusCounts = async (
+		timezone = Intl.DateTimeFormat().resolvedOptions().timeZone,
```
Comment (mafredri) [inline site/src/api/api.ts:2474]: Verify: JS timezones map 1-to-1 to Go timezones.

File: coderd/database/queries/insights.sql (hunk 2 above)
Comment (DanielleMaywood) [reply coderd/database/queries/insights.sql]: I'm fine with them as-is just wanted to make sure I knew the intention when reviewing 👍

File: coderd/database/queries/insights.sql [hunk 8]
```diff
@@ -843,17 +833,15 @@ latest_status_before_range AS (
...
-	-- need to ensure that this is enforced, so that a change in business logic later does not break this graph.
+	-- status_changes_during_range selects the statuses of each user during the start_time and end_time.
 status_changes_during_range AS (
     SELECT
         usc.user_id,
         usc.new_status,
         usc.changed_at,
         ud.deleted
     FROM user_status_changes usc
+	INNER JOIN users u ON u.id = usc.user_id AND NOT u.is_system
```
Comment (mafredri) [inline coderd/database/queries/insights.sql]: Suggestion: Since we're selecting users twice, how about `WITH system_users AS (SELECT id FROM users WHERE is_system = TRUE` and `usc.id NOT IN (SELECT id FROM system_users)`.

File: coderd/insights.go (hunk 4 above)
Comment (DanielleMaywood) [inline coderd/insights.go:310]: It doesn't look like this was previously documented but removing this is a backwards incompatible change. Are we okay with that?

File: codersdk/insights.go [hunk 9]
```diff
@@ -294,14 +294,14 @@ type UserStatusChangeCount struct {
 }
 
 type GetUserStatusCountsRequest struct {
-	// Timezone offset in hours. Use 0 for UTC, and TimezoneOffsetHour(time.Local)
-	// for the local timezone.
-	Offset int `json:"offset"`
+	Timezone string `json:"timezone" example:"America/St_Johns"`
+	Offset   int    `json:"offset" example:"-2"`
```
Comment (mafredri) [inline codersdk/insights.go]: Mark deprecated?

File: coderd/insights.go [hunk 10]
```diff
@@ -318,16 +319,34 @@ func (api *API) insightsUserStatusCounts(rw http.ResponseWriter, r *http.Request
 		return
 	}
 
-	loc := time.FixedZone("", tzOffset*3600)
+	var loc *time.Location
+	if timezone == "" {
```
Comment (mafredri) [inline coderd/insights.go:331]: Error if both timezone and offset provided? Motivation, avoid user confusion (passes a tz offset, but it does not get applied, does not see/think about timezone param present.)

File: coderd/insights.go [hunk 11]
```diff
@@ -298,6 +298,7 @@ func (api *API) insightsUserLatency(rw http.ResponseWriter, r *http.Request) {
 // @Security CoderSessionToken
 // @Produce json
 // @Tags Insights
+// @Param timezone query string true "IANA timezone name (e.g. America/St_Johns)"
```
Comment (DanielleMaywood) [inline coderd/insights.go]: We're specifying here that the timezone is a required parameter, but later on we treat it as optional.

We should either:
- Make this `false` to represent the implementation
- Bail out when `timezone` is not present


```suggestion
// @Param timezone query string false "IANA timezone name (e.g. America/St_Johns)"
```

**Review by mafredri — COMMENTED** [review]
Looks good, no major concerns. Pointed out a few things we could improve and a few cases where we should do some additional verification.

File: coderd/database/queries/insights.sql (hunk 1 above)
Comment (SasSwart) [reply coderd/database/queries/insights.sql]: > against magic UUID, have we eradicated all such use or would it be beneficial here to avoid the join?

Good question. We have a magic uuid for the prebuilds user, but it might not be the only system user. Others might be added. So we filter by all system users for future-proofing.

System users should only have one status change, which is when they change from not-existing to existing (active).

File: coderd/database/queries/insights.sql (hunk 3 above)
Comment (SasSwart) [reply coderd/database/queries/insights.sql]: I'll test it out quickly and see.
Not sure what you mean by the "statistics".
We do remove deleted users from the chart as soon as they are deleted.

File: coderd/insights.go (hunk 4 above)
Comment (SasSwart) [reply coderd/insights.go:310]: Official clients never used it AFAICT, but because its been part of the public interface for more than a year, I actually don't think we can remove it now without deprecating it first. I have added it back with a deprecation warning.

File: coderd/insights.go (hunk 6 above)
Comment (SasSwart) [reply coderd/insights.go]: Both use the IANA tzdata database. Go does have a special value for `UTC/local` but there is no way for it to get into this codepath.

File: site/src/api/api.ts (hunk 7 above)
Comment (SasSwart) [reply site/src/api/api.ts:2474]: Both use the IANA tzdata database.

File: coderd/database/queries/insights.sql (hunk 8 above)
Comment (SasSwart) [reply coderd/database/queries/insights.sql]: done

File: coderd/insights.go (hunk 10 above)
Comment (SasSwart) [reply coderd/insights.go:331]: done

File: coderd/insights.go (hunk 4 above)
Comment (SasSwart) [reply coderd/insights.go:310]: I've added it back with a deprecation message.

File: coderd/insights.go (hunk 11 above)
Comment (SasSwart) [reply coderd/insights.go]: both timezone and offset are now optional. If you provide both, we give the appropriate error. If neither are provided we default to UTC

File: coderd/database/queries/insights.sql (hunk 3 above)
Comment (SasSwart) [reply coderd/database/queries/insights.sql]: I've tried this and it works. So I got rid of those todos.

File: coderd/database/queries/insights.sql [hunk 12]
```diff
@@ -805,90 +805,70 @@ GROUP BY utp.num, utp.template_ids, utp.name, utp.type, utp.display_name, utp.de
...
+    SELECT id FROM users WHERE is_system = TRUE
+),
+	-- dates_of_interest generates the dates that will represent the horizontal axis of the chart.
 dates_of_interest AS (
-	SELECT date FROM generate_series(
-		@start_time::timestamptz,
-		@end_time::timestamptz,
-		(CASE WHEN @interval::int <= 0 THEN 3600 * 24 ELSE @interval::int END || ' seconds')::interval
-	) AS date
+  SELECT timezone(@tz::text, gs_local) AS date
```
Comment (mafredri) [inline coderd/database/queries/insights.sql:814]: Suggestion: For future readers, we could mention what this ceremony is about. I.e. Remove timezone -> generate series -> add timezone back and why that's done.

**This suggestion is optional, don't want to increase churn on this PR.**

**Review by mafredri — APPROVED** [review]
