### PR TITLE
fix(scaletest): fix flake in Test_Runner/Cleanup

### LINKED ISSUE #10240: test flake: scaletest/createworkspaces Test_Runner/CleanupPendingBuild
Seen here: https://github.com/coder/coder/actions/runs/6496433258/job/17643357736

Logs: https://gist.github.com/johnstcn/b43a9f8d34fbcfe5c7718a353f87ae73

### PR DESCRIPTION
**Pull request by johnstcn**
Fixes https://github.com/coder/coder/issues/10240

From the linked issue:

- We get to the `require.Eventually` that asserts that the build was canceled
- This times out after 10 seconds
- It appears that the build job never got canceled after 10 seconds
- It also appears that a second build never got created
- We unfortunately appear to be missing cleanup logs in the output, so hard to troubleshoot further.

Based on the above, it looks like a race between `runner.Cleanup` doing its thing and the `require.Eventually` asserting that cleanup happened. I don't see a simple way to synchronize between these two actions, so to reduce the likelihood of this happening in future and hoepfully aid future troubleshooting:

- Added a check that the build is running before we cancel it
- Added cleanup output to logs (TODO done)
- Added some checks to the test cleanup logs

I wasn't able to recrate the original failure after running the test 100 times with `DB=ci` and `-race`, so while not 100% confident this completely fixes the flake, I'm hopeful at least.

### CODE REVIEW

File: scaletest/createworkspaces/run.go [hunk 1]
```diff
@@ -176,13 +176,14 @@ resourceLoop:
 }
 
 // Cleanup implements Cleanable.
-func (r *Runner) Cleanup(ctx context.Context, id string) error {
+func (r *Runner) Cleanup(ctx context.Context, id string, w io.Writer) error {
```
Comment (spikecurtis) [inline scaletest/createworkspaces/run.go:179]: I like the name `logs` as clearer intention than `w`

File: scaletest/workspacebuild/run.go [hunk 2]
```diff
@@ -119,12 +121,18 @@ func (r *CleanupRunner) Run(ctx context.Context, _ string, logs io.Writer) error
 
 	ws, err := r.client.Workspace(ctx, r.workspaceID)
 	if err != nil {
+		var sdkErr *codersdk.Error
+		if xerrors.As(err, &sdkErr) && sdkErr.StatusCode() == http.StatusNotFound {
+			_, _ = fmt.Fprintf(logs, "Workspace %s not found, skipping delete.\n", r.workspaceID)
```
Comment (spikecurtis) [inline scaletest/workspacebuild/run.go:126]: why not use the `logger` here?

File: scaletest/createworkspaces/run_test.go [hunk 3]
```diff
@@ -257,24 +262,35 @@ func Test_Runner(t *testing.T) {
...
+				return false
+			}
 
-			return len(workspaces.Workspaces) > 0
-		}, testutil.WaitShort, testutil.IntervalFast)
+			ws := workspaces.Workspaces[0]
+			t.Logf("checking build: %s | %s", ws.LatestBuild.Transition, ws.LatestBuild.Job.Status)
+			// There should be only one build at present.
+			if ws.LatestBuild.Transition != codersdk.WorkspaceTransitionStart {
+				t.Fatalf("expected build transition %s, got %s", codersdk.WorkspaceTransitionStart, ws.LatestBuild.Transition)
```
Comment (spikecurtis) [inline scaletest/createworkspaces/run_test.go:279]: can't call `t.Fatalf` in an Eventually condition, because it is run on a separate go routine and `t.Fatalf` is only allowed on the main test goroutine.

**Review by spikecurtis — APPROVED** [review]
Some nits to take care of, but I don't need to re-review

File: scaletest/createworkspaces/run_test.go (hunk 3 above)
Comment (johnstcn) [reply scaletest/createworkspaces/run_test.go:279]: oops

File: scaletest/workspacebuild/run.go (hunk 2 above)
Comment (johnstcn) [reply scaletest/workspacebuild/run.go]: Fixed

File: scaletest/createworkspaces/run.go (hunk 1 above)
Comment (johnstcn) [reply scaletest/createworkspaces/run.go]: Renamed
