### PR TITLE
fix: VSCode desktop connection

### LINKED ISSUE #80: bug: folder URI parameter with relative path fails to open silently
Trying to open a VSCode URI of the following format will fail _silently_ unless you bust open the VSCode DevTools and watch the error log:

```
vscode://coder.coder-remote/open?owner=john&workspace=joes-workspace&url=https%3A%2F%2Fdev.coder.com&token=supersecret&agent=smith&folder=relative%2Fpath
```

The error is:

```
Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at T (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23616)
	at new C (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:24703)
	at new E (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:26084)
	at C.from (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:25501)
	at t.Commands.<anonymous> (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:154887)
	at Generator.next (<anonymous>)
	at c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:149762
	at new Promise (<anonymous>)
	at i (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:149507)
	at t.Commands.open (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:153240)
	at m.h (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125797)
	at m.g (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124687)
	at m.executeCommand (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124587)
	at Object.executeCommand (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:23801)
	at c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:157816
	at Generator.next (<anonymous>)
	at i (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:156251)
```

Correct behaviour would probably be one of:
1) Complain loudly e.g. show an error dialog
2) Attempt to resolve the folder relative to `$HOME`

### PR DESCRIPTION
**Pull request by matifali**
This PR fixes an issue with VS Code Desktop connection when the URI becomes invalid if the `dir` in `coder_agent` resource is not an absolute path or does not start with `~`.

Fixes https://github.com/coder/vscode-coder/issues/80

### CODE REVIEW

**Review by johnstcn — COMMENTED** [review]
Nice find! We should probably add a unit test for this change though.

See here: https://github.com/coder/coder/blob/17f692a89a83142e6939e1b5e839f2348c921167/agent/agent_test.go#L1361

We should probably also document this in `docs/template/open-in-coder.md`.

**Review by kylecarbs — APPROVED** [review]

File: agent/agent.go [hunk 1]
```diff
@@ -1407,5 +1407,12 @@ func expandDirectory(dir string) (string, error) {
 		}
 		dir = filepath.Join(home, dir[1:])
 	}
+	if !filepath.IsAbs(dir) {
```
Comment (mafredri) [inline agent/agent.go:1410]: Since this is done before `os.ExpandEnv`, it will incorrectly think the path isn’t absolute when the value is e.g. `$HOME`. Moving this too after that should fix the test that’s failing.

Comment (matifali) [reply agent/agent.go]: Thanks for the suggestion but $HOME not being used as an absolute path

File: agent/agent.go [hunk 2]
```diff
@@ -1407,5 +1407,13 @@ func expandDirectory(dir string) (string, error) {
 		}
 		dir = filepath.Join(home, dir[1:])
 	}
-	return os.ExpandEnv(dir), nil
+
+	if !filepath.IsAbs(dir) && dir[0] != '$' {
```
Comment (mafredri) [inline agent/agent.go:1411]: Let's say `dir = $USER/src` which would be a relative path (e.g. `mafredri/src`), it would not be turned into an absolute path in this case.

I still think it'd be simplest to expand dir before the abs check.

Comment (matifali) [reply agent/agent.go:1411]: let me try this. Thank you.

**Review by mafredri — APPROVED** [review]
LGTM, nice work!

**Review by johnstcn — APPROVED** [review]
