### PR TITLE
fix: don't create autostart workspace builds with no available provisioners

### LINKED ISSUE #17941: Automatic builds should not be created if there are no provisioners with matching tags
Automatic builds created due to autostart, autostop, or dormancy should not be created if there are no provisioners available with matching tags.

Otherwise we get into a fight with the new job reaper code and we will keep churning out new jobs (especially for dormancy, which will cause new jobs every 30 minutes).

Image

Example on dogfood: https://dev.coder.com/@cian/crimson-cobra-21?sidebar=history

### PR DESCRIPTION
**Pull request by cstyan**
This should fix https://github.com/coder/coder/issues/17941

With just the test addition the test will fail since the workspace build is triggered, we attempt to move the workspace into the `start` state: `require.Equal(t, codersdk.WorkspaceTransitionStop, workspace.LatestBuild.Transition)`
```
    lifecycle_executor_test.go:1718: 
                Error Trace:    /home/coder/coder/coderd/autobuild/lifecycle_executor_test.go:1718
                Error:          Not equal: 
                                expected: "stop"
                                actual  : "start"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -(codersdk.WorkspaceTransition) (len=4) "stop"
                                +(codersdk.WorkspaceTransition) (len=5) "start"
                                 
                Test:           TestExecutorAutostartSkipsWhenNoProvisionersAvailable
```

With the 2nd commit we skip the calls to `wsbuilder.New` and `builder.Build` and so the transition is never scheduled.
```
coder@automatic-builds-test:~/coder/coderd/autobuild$ go test -run TestExecutorAutostartSkipsWhenNoProvisionersAvailable
PASS
ok      github.com/coder/coder/v2/coderd/autobuild      1.134s
coder@automatic-builds-test:~/coder/coderd/autobuild$ go test -run TestExecutorAutostartSkipsWhenNoProvisionersAvailable -v | grep autostart
    t.go:106: 2025-07-28 22:11:09.405 [warn]  coderd.autobuild: skipping autostart - no available provisioners  workspace_id=219f4901-dfd0-4cdc-8cf2-258861adfd18  workspace_name=dazzling-jemison3-89l
```

However, many tests don't fully setup provisioner or wait for the provisioner + DB to be fully available, so the third commit adds a somewhat smelly way to skip the provisioner check in tests that don't need to test that functionality.

### CODE REVIEW

File: coderd/autobuild/lifecycle_executor.go [hunk 1]
```diff
@@ -131,6 +138,39 @@ func (e *Executor) Run() {
...
+	provisionerDaemons, err := tx.GetProvisionerDaemonsByOrganization(ctx, database.GetProvisionerDaemonsByOrganizationParams{
+		OrganizationID: ws.OrganizationID,
+		WantTags:       templateVersionJob.Tags,
+	})
+	if err != nil {
+		return false, xerrors.Errorf("get provisioner daemons: %w", err)
+	}
+
+	// Check if any provisioners are active (not stale)
+	now := dbtime.Now()
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go]: This should be using the passed in time from `runOnce` rather than getting it's own time

File: coderd/autobuild/lifecycle_executor.go [hunk 2]
```diff
@@ -131,6 +138,39 @@ func (e *Executor) Run() {
...
+func (e *Executor) hasAvailableProvisioners(ctx context.Context, tx database.Store, ws database.Workspace, templateVersionJob database.ProvisionerJob) (bool, error) {
+	if e.SkipProvisionerCheck {
+		return true, nil
+	}
+
+	// Use a shorter stale interval for tests
+	staleInterval := provisionerdserver.StaleInterval
+	if testing.Testing() {
+		staleInterval = TestingStaleInterval
+	}
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go]: If you use the passed in time from `runOnce` I don't think changing the interval would be necessary, you could write the test in a way that the default interval works fine

File: coderd/autobuild/lifecycle_executor.go [hunk 3]
```diff
@@ -52,6 +56,9 @@ type Executor struct {
 	experiments           codersdk.Experiments
 
 	metrics executorMetrics
+
+	// Skip provisioner availability check (should only be true for *some* tests)
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go]: It says it should only be true for some tests, but it seems it's true for almost every test using `coderdtest`. How many tests are actually broken by this change? If it's only a few, I'd rather we just fix those tests (e.g. by adding provisioners) rather than add a skip flag.

**Comment by cstyan** [comment]
Okay @deansheather thanks for your patience, I think this is finally ready for another review. Took quite a bit of digging with the help of Blink to find all the bits and pieces that had to be updated to get the tests working without the `skipProvisionerCheck` flag. I've done my own run through of the changes twice now but I may have still missed some small stuff, nit pick away 👍 

The TL; DR of the changes is that we in tests which deal with autobuilds we need:
- to create the test in a way where we also return the handle to the database instance
- ensure the test creates a provisioner with the relevant tags for the workspace that will be used within that test case (in most cases this is just the default `owner: "", scope: organization` but there is a mechanism for using specific tags in at least one of the tests)
- based on whether the autobuild should happen or not, we need to ensure we can retrieve the relevant provisioner and sest the scheduled tick time for the autobuild appropriately (should the provisioner be valid, or should it be stale)

File: coderd/autobuild/lifecycle_executor.go [hunk 4]
```diff
@@ -131,6 +134,36 @@ func (e *Executor) Run() {
 	}()
 }
 
+func (e *Executor) hasAvailableProvisioners(ctx context.Context, tx database.Store, t time.Time, ws database.Workspace, templateVersionJob database.ProvisionerJob) (bool, error) {
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go]: Maybe `Online` is a better name here, since we're just checking that there _are_ provisioners, not that they're necessarily available right now for a new build.

File: coderd/autobuild/lifecycle_executor.go [hunk 5]
```diff
@@ -131,6 +134,36 @@ func (e *Executor) Run() {
...
+	queryParams := database.GetProvisionerDaemonsByOrganizationParams{
+		OrganizationID: ws.OrganizationID,
+		WantTags:       templateVersionJob.Tags,
+	}
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go:142]: Maybe you should put something up here like `logger := e.log.With(slog.F("tags", templateVersionJob.Tags))` for those log statements below

File: coderd/autobuild/lifecycle_executor.go [hunk 6]
```diff
@@ -28,11 +28,14 @@ import (
...
 	"github.com/coder/coder/v2/coderd/database/pubsub"
 	"github.com/coder/coder/v2/coderd/notifications"
+	"github.com/coder/coder/v2/coderd/provisionerdserver"
 	"github.com/coder/coder/v2/coderd/schedule"
 	"github.com/coder/coder/v2/coderd/wsbuilder"
 	"github.com/coder/coder/v2/codersdk"
 )
 
+const TestingStaleInterval = time.Second * 5
+
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor.go]: This seems to be only used in tests and not in this file. We should try to avoid test-only constants like this anyways, in favor of letting it be configured as a new argument to `NewExecutor`

File: coderd/autobuild/lifecycle_executor_test.go [hunk 7]
```diff
@@ -1583,3 +1665,177 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+	coderdtest.MustWaitForProvisionersAvailable(t, db, workspace, autobuild.TestingStaleInterval)
+
+	// Now shut down the provisioner daemon
+	ctx := testutil.Context(t, testutil.WaitShort)
+	err := provisionerCloser.Close()
+	require.NoError(t, err)
+
+	// Wait for the provisioner to become stale (heartbeat stops)
+	// The stale interval is 5 seconds, so we need to wait a bit longer
+	time.Sleep(6 * time.Second)
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: We typically avoid sleeps wherever possible in tests. You could try:
- Manipulating the database to set the provisioners to have a last_seen_at property six seconds in the past
- Manipulating the tick time you pass into the executor to use a time six seconds in the past

File: coderd/autobuild/lifecycle_executor_test.go [hunk 8]
```diff
@@ -1583,3 +1665,177 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+
+	// Debug: check what's in the database
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: I don't mind a few debug log statements typically, but this test has a lot which impacts readability, and I personally don't think most of them are that useful

File: coderd/autobuild/lifecycle_executor_test.go [hunk 9]
```diff
@@ -1583,3 +1665,177 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+	daemons, err := db.GetProvisionerDaemons(ctx)
+	require.NoError(t, err)
+	t.Logf("After close: found %d daemons", len(daemons))
+	for i, daemon := range daemons {
+		t.Logf("Daemon %d: ID=%s, Name=%s, LastSeen=%v", i, daemon.ID, daemon.Name, daemon.LastSeenAt)
+	}
+
+	// Since we commented out the close call, the provisioner should NOT become stale
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: I'm confused about this comment, it looks like the close call isn't commented out

File: coderd/autobuild/lifecycle_executor_test.go (hunk 8 above)
Comment (deansheather) [reply coderd/autobuild/lifecycle_executor_test.go]: I also think if the test avoids using sleeps and switches to manipulation of the db/ticks it'll be more reliable and won't need all of these debugs, since you won't have to worry about a real provisioner daemon sending updates

File: coderd/autobuild/lifecycle_executor_test.go (hunk 7 above)
Comment (deansheather) [reply coderd/autobuild/lifecycle_executor_test.go]: I think you'd also be able to avoid the 5s test timeout constant if you did this instead

File: coderd/autobuild/lifecycle_executor_test.go [hunk 10]
```diff
@@ -1583,3 +1665,177 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+	}, nil)
+	require.NoError(t, err)
+
+	// Test 2: Timing issue - query right before and after hasAvailableProvisioners
+	t.Logf("=== Testing timing issue ===")
+
+	// Query right before the autostart trigger
+	beforeDaemons, err := db.GetProvisionerDaemonsByOrganization(context.Background(), queryParams)
+	require.NoError(t, err)
+	t.Logf("Right before autostart: %d daemons", len(beforeDaemons))
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: You run the same query 4 times in a row here. If you'd like to assert the value before you trigger the run, just query once and check the result (e.g. the `Query right before the autostart trigger` query you have).

Testing different combinations of contexts/transactions is out of the realm of the lifecycle executor test, and would be better for the database package (that being said, I don't think it'd be a high-value test in the database package anyway).

File: coderd/autobuild/lifecycle_executor_test.go [hunk 11]
```diff
@@ -1583,3 +1665,177 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+	// Query with context.Background() (what we used above)
+	matchingDaemons1, err := db.GetProvisionerDaemonsByOrganization(context.Background(), queryParams)
+	require.NoError(t, err)
+	t.Logf("With context.Background(): %d daemons", len(matchingDaemons1))
+
+	// Query with a fresh context
+	ctx2 := context.Background()
+	matchingDaemons2, err2 := db.GetProvisionerDaemonsByOrganization(ctx2, queryParams)
+	require.NoError(t, err2)
+	t.Logf("With fresh context: %d daemons", len(matchingDaemons2))
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: These are identical since they both use a background context and the same parameters.

File: enterprise/coderd/workspaces_test.go [hunk 12]
```diff
@@ -644,7 +644,12 @@ func TestWorkspaceAutobuild(t *testing.T) {
 		ws := coderdtest.CreateWorkspace(t, client, template.ID)
 		build := coderdtest.AwaitWorkspaceBuildJobCompleted(t, client, ws.LatestBuild.ID)
 		require.Equal(t, codersdk.WorkspaceStatusFailed, build.Status)
-		ticker <- build.Job.CompletedAt.Add(failureTTL * 2)
+		tickTime := build.Job.CompletedAt.Add(failureTTL * 2)
+
+		p, err := coderdtest.GetProvisionerForWorkspace(t, db, time.Now(), ws.OrganizationID, database.ProvisionerJob{})
```
Comment (deansheather) [inline enterprise/coderd/workspaces_test.go]: `provisionerdserver.StaleInterval` is 90s, so is this necessary? Most tests have a timeout of <30s.

File: coderd/coderdtest/coderdtest.go [hunk 13]
```diff
@@ -1590,3 +1592,117 @@ func DeploymentValues(t testing.TB, mut ...func(*codersdk.DeploymentValues)) *co
 	}
 	return cfg
 }
+
+// GetProvisionerForWorkspace returns the first valid provisioner for a workspace + template tags.
+func GetProvisionerForWorkspace(t *testing.T, tx database.Store, curTime time.Time, orgID uuid.UUID, templateVersionJob database.ProvisionerJob) (database.ProvisionerDaemon, error) {
```
Comment (deansheather) [inline coderd/coderdtest/coderdtest.go]: The function name says it's for a workspace but takes a template version. Maybe you should change the signature to:
```go
func GetProvisionerForTags(t *testing.T, tx database.Store, curTime time.Time, orgID uuid.UUID, tags []string) (database.ProvisionerDaemon, error) {
```

File: enterprise/coderd/workspaces_test.go (hunk 12 above)
Comment (cstyan) [reply enterprise/coderd/workspaces_test.go]: I'm not sure what this comment was referring to honestly.

Comment (deansheather) [reply enterprise/coderd/workspaces_test.go]: In a lot of the autobuild tests, you query the provisionerd and force update it to be current with `coderdtest.UpdateProvisionerLastSeenAt(t, db, p.ID, tickTime)` right before it ticks, even if the test isn't doing anything funky with the timings. Since the stale interval is 90s, I don't think most tests need this change to be made to them no? Unless there's another reason, like our fake provisioner daemons not setting times correctly?

File: coderd/autobuild/lifecycle_executor_test.go [hunk 14]
```diff
@@ -55,10 +56,13 @@ func TestExecutorAutostartOK(t *testing.T) {
...
 	workspace = coderdtest.MustTransitionWorkspace(t, client, workspace.ID, codersdk.WorkspaceTransitionStart, codersdk.WorkspaceTransitionStop)
-
+	p, err := coderdtest.GetProvisionerForTags(db, time.Now(), workspace.OrganizationID, map[string]string{})
+	require.NoError(t, err)
 	// When: the autobuild executor ticks after the scheduled time
 	go func() {
-		tickCh <- sched.Next(workspace.LatestBuild.CreatedAt)
+		tickTime := sched.Next(workspace.LatestBuild.CreatedAt)
+		coderdtest.UpdateProvisionerLastSeenAt(t, db, p.ID, tickTime)
+		tickCh <- tickTime
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go:69]: W.R.T the last comment from the previous review, this is what I'm referring to. Is this change (and other similar changes) necessary?

File: coderd/autobuild/lifecycle_executor_test.go [hunk 15]
```diff
@@ -1583,3 +1666,63 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
 func TestMain(m *testing.M) {
 	goleak.VerifyTestMain(m, testutil.GoleakOptions...)
 }
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go]: I know this wasn't your doing but could you please move TestMain to the top of the file? It feels wrong nestled in with real tests

File: coderd/autobuild/lifecycle_executor_test.go [hunk 16]
```diff
@@ -1583,3 +1666,63 @@ func mustWorkspaceParameters(t *testing.T, client *codersdk.Client, workspaceID
...
+	coderdtest.MustWaitForProvisionersAvailable(t, db, workspace)
+	p, err := coderdtest.GetProvisionerForTags(db, time.Now(), workspace.OrganizationID, provisionerDaemonTags)
+	require.NoError(t, err, "Error getting provisioner for workspace")
+
+	// Ensure the provisioner is stale
+	staleTime := sched.Next(workspace.LatestBuild.CreatedAt).Add((-1 * provisionerdserver.StaleInterval) + -10*time.Second)
+	coderdtest.UpdateProvisionerLastSeenAt(t, db, p.ID, staleTime)
+
+	// Trigger autobuild
+	tickCh <- sched.Next(workspace.LatestBuild.CreatedAt)
```
Comment (deansheather) [inline coderd/autobuild/lifecycle_executor_test.go:1735]: This is racey since the provisioner daemon is still running and can update it's stats. It'd be less prone to racing if the provisioner daemon was closed.

```go
db, pubsub := dbtestutil.New(t)
client, _, api := coderdtest.NewWithAPI(t, &coderdtest.Options{
  Database: db,
  Pubsub: pubsub,
  IncludeProvisionerDaemon: false,
})

daemon1Closer := coderdtest.NewTaggedProvisionerDaemon(t, api, "name", tags)
t.Cleanup(func() {
  _ = daemon1Closer.Close()
})

// create the workspace

daemon1Closer.Close() // <-- this is the important line, prevents the race I described

next := sched.Next(workspace.LatestBuild.CreatedAt)
staleTime := next.Add(-1 * provisionerdserver.StaleInterval - 10 *time.Second)
coderdtest.UpdateProvisionerLastSeenAt(t, db, p.ID, staleTime)
tickCh <- next

// Assertions...

// Create a new provisioner daemon with the same tags like you just did before, then ensure it works
```

File: coderd/coderdtest/coderdtest.go [hunk 17]
```diff
@@ -1590,3 +1592,121 @@ func DeploymentValues(t testing.TB, mut ...func(*codersdk.DeploymentValues)) *co
...
+}
+
+func MustWaitForAnyProvisioner(t *testing.T, db database.Store) {
+	t.Helper()
+	ctx := ctxWithProvisionerPermissions(testutil.Context(t, testutil.WaitShort))
+	require.Eventually(t, func() bool {
+		daemons, err := db.GetProvisionerDaemons(ctx)
+		return err == nil && len(daemons) > 0
+	}, testutil.WaitShort, testutil.IntervalFast)
+}
```
Comment (deansheather) [inline coderd/coderdtest/coderdtest.go:1653]: Is this function necessary? In all of your tests there is an admin client there also, so you could just use the WithClient variant of this function instead.

File: coderd/coderdtest/coderdtest.go [hunk 18]
```diff
@@ -1590,3 +1592,121 @@ func DeploymentValues(t testing.TB, mut ...func(*codersdk.DeploymentValues)) *co
...
+			if pd.LastSeenAt.Valid {
+				age := now.Sub(pd.LastSeenAt.Time)
+				if age <= provisionerdserver.StaleInterval {
+					id = pd.ID
+					return true // Found an active provisioner
+				}
+			}
+		}
+		return false // No active provisioners found
+	}, testutil.WaitShort, testutil.IntervalFast)
```
Comment (deansheather) [inline coderd/coderdtest/coderdtest.go]:
```suggestion
	}, testutil.WaitLong, testutil.IntervalFast)
```

File: enterprise/coderd/workspaces_test.go [hunk 19]
```diff
@@ -644,7 +644,12 @@ func TestWorkspaceAutobuild(t *testing.T) {
 		ws := coderdtest.CreateWorkspace(t, client, template.ID)
 		build := coderdtest.AwaitWorkspaceBuildJobCompleted(t, client, ws.LatestBuild.ID)
 		require.Equal(t, codersdk.WorkspaceStatusFailed, build.Status)
-		ticker <- build.Job.CompletedAt.Add(failureTTL * 2)
+		tickTime := build.Job.CompletedAt.Add(failureTTL * 2)
+
+		p, err := coderdtest.GetProvisionerForTags(db, time.Now(), ws.OrganizationID, nil)
+		require.NoError(t, err)
+		coderdtest.UpdateProvisionerLastSeenAt(t, db, p.ID, tickTime)
+		ticker <- tickTime
```
Comment (deansheather) [inline enterprise/coderd/workspaces_test.go:650]: Also related to the comment from my previous review, is this necessary?

File: coderd/autobuild/lifecycle_executor_test.go (hunk 14 above)
Comment (cstyan) [reply coderd/autobuild/lifecycle_executor_test.go:69]: Yes, AFAICT it is. Otherwise the test is flakey, it would only pass if you run the test within `StaleInterval` seconds of the top of any hour.

When one of these tests starts, the provisioner has a `LastSeenAt` time of `time.Now()` (sometimes + 1 second or so), but `sched.Next(workspace.LatestBuild.CreatedAt)` will return a value that is the top of the hour.

For example: right now if I comment out the `UpdateProvisionerLastSeenAt` line here, in `hasValidProvisioner` the `pd.LastSeenAt` time is `2025-08-12 16:34:02.908042 +0000 UTC` but `t` from the `tickCh` is `2025-08-12 17:00:00 +0000 UTC`. So in a real running deployment of Coder that provisioner would be considered stale.

This is the exact thing we were trying to solve for with the addition of `hasValidProvisioner`. So any test case which utilized the autobuild functionality but needed to continue passing needed to update the `LastSeenAt` value. In the test I have added, which should see the provisioner as stale and then assert that there were no autobuild transitions initiated, we ensure the `LastSeenAt` time is far enough in the past that the provisioner is stale.

File: coderd/coderdtest/coderdtest.go (hunk 17 above)
Comment (cstyan) [reply coderd/coderdtest/coderdtest.go:1653]: I don't have much insight into _why_, but yes the tests which are currently using `MustWaitForAnyProvisioner` fail if they're changed to `MustWaitForAnyProvisionerWithClient`. I can do a bit more digging on that today.

File: enterprise/coderd/workspaces_test.go (hunk 19 above)
Comment (cstyan) [reply enterprise/coderd/workspaces_test.go:650]: Yes, for the same reason as above.

File: coderd/autobuild/lifecycle_executor_test.go (hunk 16 above)
Comment (cstyan) [reply coderd/autobuild/lifecycle_executor_test.go:1735]: made these changes, lmk if this test still looks off to you

File: coderd/coderdtest/coderdtest.go (hunk 17 above)
Comment (cstyan) [reply coderd/coderdtest/coderdtest.go:1653]: I decided to change things so that we just have `MustWaitForAnyProvisioner`, but we could have gone either way. 

The test which was using `MustWaitForAnyProvisioner` was calling `CreateFirstUser` after the `MustWaitForAnyProvisioner` call, so the client did not have an admin session token yet and would 401. The test which was calling `MustWaitForAnyProvisionerWithClient` was just calling `corderdtest.New` instead of `coderdtest.NewWithDatabase`.

File: coderd/autobuild/lifecycle_executor_test.go (hunk 14 above)
Comment (deansheather) [reply coderd/autobuild/lifecycle_executor_test.go:69]: Ahhh I get it, because the autostart time is way in the future.

Perhaps a better option for these autostarty tests to set a value on the lifecycle executor like `TestIgnoreNoDaemons: true`, and then just set it to true for these tests. Avoids having to get the provisioners and update them right before ticking, which feels like it could be racey

File: coderd/autobuild/lifecycle_executor_test.go (hunk 16 above)
Comment (deansheather) [reply coderd/autobuild/lifecycle_executor_test.go:1735]: Looks good now!

File: coderd/autobuild/lifecycle_executor_test.go (hunk 14 above)
Comment (cstyan) [reply coderd/autobuild/lifecycle_executor_test.go:69]: Isn't that essentially just going back to what I had originally? https://github.com/coder/coder/pull/19067#discussion_r2244231449

I guess we're doing the configuration in a cleaner way, but we'd still be setting that value to true for essentially all of these tests, which is what we wanted to change.

Comment (deansheather) [reply coderd/autobuild/lifecycle_executor_test.go:69]: Yeah I think I may have looped... sorry. I think what you have now is good then 👍

**Review by deansheather — APPROVED** [review]
