### PR TITLE
fix: allow regular users to push files

### LINKED ISSUE #4415: template permissions: user with `admin` access cannot push or pull a template
The Jane user is an admin for a template, but a "user" deployment-wide. I confirmed Jane can edit settings and delete the template, however, Jane cannot push to the template with `coder templates push` or pull with `coder templates pull`.

Screen Shot 2022-10-07 at 8 21 43 AM

```sh
➜  coder templates push 
> Upload "~/coder/examples/templates/docker"? (yes/no) yes
Forbidden.                                  
Run 'coder templates push --help' for usage.
```

> This is for an enterprise feature that isn't live yet (we'll be ironing out some of the bugs before we kick off trials) #4235

### PR DESCRIPTION
**Pull request by sreya**
- As part of merging support for Template RBAC
  and user groups a permission check on reading files
  was relaxed.

  With the addition of admin roles on individual templates, regular
  users are now able to push template versions if they have
  inherited the 'admin' role for a template. In order to do so
  they need to be able to create and read their own files. Since
  collisions on hash in the past were ignored, this means that a regular user
  who pushes a template version with a file hash that collides with
  an existing hash will not be able to read the file (since it belongs to
  another user).

  This commit fixes the underlying problem which was that
  the files table had a primary key on the 'hash' column.
  This was not a problem at the time because only template
  admins and other users with similar elevated roles were
  able to read all files regardless of ownership. To fix this
  a new column and primary key 'id' has been introduced to the files
  table. The unique constraint has been updated to be hash+created_by.
  Tables (provisioner_jobs) that referenced files.hash have been updated
  to reference files.id. Relevant API endpoints have also been updated.

fixes #4415

### CODE REVIEW

File: coderd/coderd.go [hunk 1]
```diff
@@ -280,7 +280,7 @@ func New(options *Options) *API {
 				// file content is expensive so it should be small.
 				httpmw.RateLimitPerMinute(12),
 			)
-			r.Get("/{hash}", api.fileByHash)
+			r.Get("/{hashID}", api.fileByID)
```
Comment (Emyrk) [inline coderd/coderd.go:283]: Remove the word hash?
```suggestion
			r.Get("/{fileID}", api.fileByID)
```

File: coderd/database/migrations/000059_file_id.up.sql [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+	file_id = files.id
+FROM
+	files
+WHERE
+	provisioner_jobs.storage_source = files.hash;
+
+-- Enforce NOT NULL on file_id now.
+ALTER TABLE provisioner_jobs ALTER COLUMN file_id SET NOT NULL;
+-- Drop storage_source since it is no longer useful for anything.
+ALTER TABLE provisioner_jobs DROP COLUMN storage_source;
```
Comment (Emyrk) [inline coderd/database/migrations/000059_file_id.up.sql:40]: `file_id` is more descriptive than `storage_source` :+1:

**Review by Emyrk — APPROVED** [review]
LG. PR comment is great.
