### PR TITLE
fix: use tailscale that avoids small MTU paths

### LINKED ISSUE #15523: Is it possible to configure the tailnet subnet?
Hello!

Is it possible to configure the tailnet subnet?
My company uses tailscale and the coder's default tailscale config conflicts with the company one.
So the coder can't instantiate a direct connection because of that and I use depr as a proxy now.
In the company config we have rules for `10.8/13`and the coder uses `10.10.10.0/24`.

It is unclear for me how it chooses this subnet 10.10.10.0/24.

### PR DESCRIPTION
**Pull request by spikecurtis**
Fixes #15523

Uses latest https://github.com/coder/tailscale which includes https://github.com/coder/tailscale/pull/85 to stop selecting paths with small MTU for direct connections.

Also updates the tailnet integration test to reproduce the issue. The previous version had the 2 peers connected by a single veth, but this allows the OS to fragment the packet. In the new version, the 2 peers (and server) are all connected by a central router. The link between peer 1 and the router has an adjustable MTU. IPv6 does not allow packets to be fragmented by intermediate routers, so sending a too-large packet in this scenario forces the router to drop packets and reproduce the issue (without the tailscale changes).

### CODE REVIEW

**Comment by spikecurtis** [comment]
* **#18323** <a href="https://app.graphite.dev/github/pr/coder/coder/18323?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/coder/coder/18323?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: tailnet/test/integration/network.go [hunk 1]
```diff
@@ -390,33 +390,38 @@ func createFakeInternet(t *testing.T) fakeInternet {
...
+// .   │  Client 1    ├───────────────────────────────┤  Router     │
+// .   │              │fdac:38fa:ffff:1::1            │             │
+// .   └──────────────┘                               └─────┬───────┘
+// .   ┌──────────────┐                                     │ fdac:38fa:ffff:2::2
+// .   │              │                                     │
+// .   │  Client 2    ├─────────────────────────────────────┘
+// .   │              │fdac:38fa:ffff:2::1
+// .   └──────────────┘
+// The veth link between Client 1 and the router has a configurable MTU via Client1MTU.
 func (n TriangleNetwork) SetupNetworking(t *testing.T, l slog.Logger) TestNetworking {
```
Comment (deansheather) [inline tailnet/test/integration/network.go:425]: It's not really a triangle anymore unfortunately, more of a pitchfork 🤣

File: tailnet/test/integration/network.go [hunk 2]
```diff
@@ -390,33 +390,38 @@ func createFakeInternet(t *testing.T) fakeInternet {
...
+// .   ┌──────────────┐                               ┌─────┴───────┐
+// .   │              │            fdac:38fa:ffff:1::2│             │
+// .   │  Client 1    ├───────────────────────────────┤  Router     │
+// .   │              │fdac:38fa:ffff:1::1            │             │
+// .   └──────────────┘                               └─────┬───────┘
+// .   ┌──────────────┐                                     │ fdac:38fa:ffff:2::2
+// .   │              │                                     │
+// .   │  Client 2    ├─────────────────────────────────────┘
+// .   │              │fdac:38fa:ffff:2::1
+// .   └──────────────┘
```
Comment (deansheather) [inline tailnet/test/integration/network.go]: Can we change the `::1` addresses to belong to the router instead of the leaf nodes? I get that this doesn't affect the behavior of the test, but in most router setups (especially IPv4) the router typically uses `.1` for itself. Since we're kinda treating these IPv6 addresses like they are IPv4 addresses with sequential numbering, it seems more intuitive to give `::1` to the router.

Comment (deansheather) [reply tailnet/test/integration/network.go]: This was something I noticed previously (between clients and server) but decided not to bring up since there wasn't a router.

**Review by deansheather — APPROVED** [review]

File: tailnet/test/integration/network.go (hunk 1 above)
Comment (deansheather) [reply tailnet/test/integration/network.go:425]: You should redo the diagram to be triforce 🤣

Comment (spikecurtis) [reply tailnet/test/integration/network.go:425]: Not sure unicode has the correct (60°) diagonals

**Review by ethanndickson — APPROVED** [review]

**Comment by spikecurtis** [comment]
### Merge activity

* **Jun 11, 10:16 AM UTC**: @spikecurtis merged this pull request with [Graphite](https://app.graphite.dev/github/pr/coder/coder/18323).
