### PR TITLE
fix(coderd/x/chatd): stabilize auto-promotion flake

### LINKED ISSUE #1406: flake: TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease
CI Run: https://github.com/coder/coder/actions/runs/23172387510
Failed Job: test-go-pg (ubuntu-latest)
Commit: 1031da9738a22cc7158f7b3e02e31933e7771243 (author: Michael Suchacz)

Failure:
```
=== FAIL: coderd/chatd TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease (0.52s)
    chatd_test.go:884:
        Error Trace: /home/runner/work/coder/coder/coderd/chatd/chatd_test.go:884
        Error:       Should be true
```

Observed context (from logs):
- The failure occurs right after `SendMessage` with content "later queued"; the test expects `laterQueuedResult.Queued` to be true.
- Logs show chat processing and pubsub events, then the assertion failure (no panic/OOM/race output).

Suspected root cause: *Flaky test* (timing-sensitive). The test assumes the chat remains busy/interrupting when the second `SendMessage` is called; if the chat finishes processing earlier, `laterQueuedResult.Queued` can be false, causing the assertion failure.

Assignment analysis:
- `git log --oneline -10 --follow coderd/chatd/chatd_test.go` (approximated via API list commits for the file) shows recent changes touching this test file, including:
  - 5d0eb772 "fix(cored): fix flaky TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease" by Michael Suchacz
- This commit is directly related to the test and prior flake fix; assigning to @ibetitsmike.

Related issues search (coder/internal):
- "TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease"
- "chatd_test.go" "coderd/chatd"
- "chat interrupted" pubsub
- "AutoPromotion" OR "usage limit" chatd
No existing issues found.

Reproduction (if needed):
```
go test ./coderd/chatd -run TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease -count=1
```

Notes:
- No data race warnings, panic traces, or OOM indicators found in the job logs.

### PR DESCRIPTION
**Pull request by ibetitsmike**
TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease still relied on wall-clock polling after the acquire loop moved to a mock clock, so it could assert before chatd finished its asynchronous cleanup and auto-promotion work.

Wait on explicit request-start signals and on the server's in-flight chat work before asserting the intermediate and final database state. This keeps the test synchronized with the actual processor lifecycle instead of scheduler timing.

Closes https://github.com/coder/internal/issues/1406

### CODE REVIEW

File: coderd/chatd/chatd_test.go [hunk 1]
```diff
@@ -902,15 +902,41 @@ func TestInterruptAutoPromotionIgnoresLaterUsageLimitIncrease(t *testing.T) {
...
 	defer acquireTrap.Close()
 
+	waitForSignal := func(name string, ch <-chan struct{}) {
+		t.Helper()
+		select {
+		case <-ch:
+		case <-ctx.Done():
+			t.Fatalf("timed out waiting for %s: %v", name, ctx.Err())
+		}
+	}
```
Comment (johnstcn) [inline coderd/chatd/chatd_test.go]: `testutil.TryReceive`

File: coderd/x/chatd/export_test.go [hunk 2]
```diff
@@ -0,0 +1,8 @@
+package chatd
+
+// WaitUntilIdleForTest waits for background chat work tracked by the server to
+// finish. Tests use this to assert final database state only after asynchronous
+// chat processing has completed.
+func WaitUntilIdleForTest(server *Server) {
+	server.inflight.Wait()
```
Comment (johnstcn) [inline coderd/x/chatd/export_test.go:8]: If there isn't a `Close()` method on `chatd.Server` this seems like a good thing to put in there.

File: coderd/chatd/chatd_test.go (hunk 1 above)
Comment (ibetitsmike) [reply coderd/chatd/chatd_test.go]: Good call. I replaced the local helper with `testutil.TryReceive` for the signal waits in this test.

File: coderd/x/chatd/export_test.go (hunk 2 above)
Comment (ibetitsmike) [reply coderd/x/chatd/export_test.go:8]: `chatd.Server` already has a `Close()` method and it waits on the same tracked work. I clarified the test helper comment to call out that this is the non-shutdown equivalent for tests that need to keep using the server.

Comment (ibetitsmike) [reply coderd/x/chatd/export_test.go:8]: @johnstcn does it make sense or should we adjust?

**Review by johnstcn — APPROVED** [review]
