### PR TITLE
test(cli): fix flaky TestProvisioners_Golden

### LINKED ISSUE #449: flake: `TestProvisioners_Golden/list`
https://github.com/coder/coder/actions/runs/13633936629/job/38108542481#step:7:812

```
=== FAIL: cli TestProvisioners_Golden/list (0.16s)
    clitest.go:75: invoking command: coder --global-config C:\Users\RUNNER~1\AppData\Local\Temp\TestProvisioners_Goldenlist1494230179\001 provisioners list --column id,created at,last seen at,name,version,tags,key name,status,current job id,current job status,previous job id,previous job status,organization
    golden.go:119: 
        	Error Trace:	C:/a/coder/coder/cli/clitest/golden.go:119
        	Error:      	Not equal: 
        	            	expected: "ID                                    CREATED AT            LAST SEEN AT          NAME                 VERSION       TAGS                                    KEY NAME  STATUS   CURRENT JOB ID                        CURRENT JOB STATUS  PREVIOUS JOB ID                       PREVIOUS JOB STATUS  ORGANIZATION  \n00000000-0000-0000-aaaa-000000000000  ====[timestamp]=====  ====[timestamp]=====  default-provisioner  v0.0.0-devel  map[owner: scope:organization]          built-in  idle     <nil>                                 <nil>               00000000-0000-0000-bbbb-000000000001  succeeded            Coder         \n00000000-0000-0000-aaaa-000000000001  ====[timestamp]=====  ====[timestamp]=====  provisioner-1        v0.0.0        map[foo:bar owner: scope:organization]  built-in  busy     00000000-0000-0000-bbbb-000000000002  running             <nil>                                 <nil>                Coder         \n00000000-0000-0000-aaaa-000000000002  ====[timestamp]=====  ====[timestamp]=====  provisioner-2        v0.0.0        map[owner: scope:organization]          built-in  offline  <nil>                                 <nil>               00000000-0000-0000-bbbb-000000000003  succeeded            Coder         \n00000000-0000-0000-aaaa-000000000003  ====[timestamp]=====  ====[timestamp]=====  provisioner-3        v0.0.0        map[owner: scope:organization]          built-in  idle     <nil>                                 <nil>               <nil>                                 <nil>                Coder         \n"
        	            	actual  : "ID                                    CREATED AT            LAST SEEN AT          NAME                 VERSION       TAGS                                    KEY NAME  STATUS   CURRENT JOB ID                        CURRENT JOB STATUS  PREVIOUS JOB ID                       PREVIOUS JOB STATUS  ORGANIZATION  \n00000000-0000-0000-aaaa-000000000000  ====[timestamp]=====  ====[timestamp]=====  default-provisioner  v0.0.0-devel  map[owner: scope:organization]          built-in  idle     <nil>                                 <nil>               00000000-0000-0000-bbbb-000000000001  failed               Coder         \n00000000-0000-0000-aaaa-000000000001  ====[timestamp]=====  ====[timestamp]=====  provisioner-1        v0.0.0        map[foo:bar owner: scope:organization]  built-in  busy     00000000-0000-0000-bbbb-000000000002  running             <nil>                                 <nil>                Coder         \n00000000-0000-0000-aaaa-000000000002  ====[timestamp]=====  ====[timestamp]=====  provisioner-2        v0.0.0        map[owner: scope:organization]          built-in  offline  <nil>                                 <nil>               00000000-0000-0000-bbbb-000000000003  succeeded            Coder         \n00000000-0000-0000-aaaa-000000000003  ====[timestamp]=====  ====[timestamp]=====  provisioner-3        v0.0.0        map[owner: scope:organization]          built-in  idle     <nil>                                 <nil>               <nil>                                 <nil>                Coder         \n"
```

### PR DESCRIPTION
**Pull request by mafredri**
Use a single base time with consistent offsets and ensure CreatedAt
is set on all dbgen-created resources.

Fixes coder/internal#449

### CODE REVIEW

File: cli/provisioners_test.go [hunk 1]
```diff
@@ -89,23 +89,26 @@ func TestProvisioners_Golden(t *testing.T) {
 	replace[version.ID.String()] = "00000000-0000-0000-cccc-000000000000"
 	replace[workspace.LatestBuild.ID.String()] = "00000000-0000-0000-dddd-000000000000"
 
+	now := dbtime.Now()
+
 	// Create a provisioner that's working on a job.
 	pd1 := dbgen.ProvisionerDaemon(t, coderdAPI.Database, database.ProvisionerDaemon{
 		Name:       "provisioner-1",
-		CreatedAt:  dbtime.Now().Add(1 * time.Second),
+		CreatedAt:  dbtime.Now().Add(time.Second),
```
Comment (DanielleMaywood) [inline cli/provisioners_test.go]:
```suggestion
		CreatedAt:  now.Add(time.Second),
```

**Review by DanielleMaywood — APPROVED** [review]
