### PR TITLE
fix: Add `SIGHUP` and `SIGTERM` handling to `coder server`

### LINKED ISSUE #1529: Coder server does not exit gracefully after single `SIGHUP` or `SIGTERM`
Currently only `SIGINT` (Ctrl+C) triggers a graceful shutdown, however, it would make sense for `SIGHUP` and `SIGTERM` to have this behavior as well. Maybe others.

For example, using the provided `docker-compose.yaml` with `docker-compose up` and later `docker-compose down` will leave the system in a dirty state and all workspaces will be left running.

We can probably just extend the `SIGINT` behavior to listen to these two signals. After any one of them is received, either deregister HUP and TERM or add an exit handler.

### PR DESCRIPTION
**Pull request by mafredri**
To prevent additional signals from aborting program execution, signal
handling was moved to the beginning of the main function, this ensures
that signals stays registered for the entire shutdown procedure.

Fixes #1529

### CODE REVIEW

**Review by johnstcn — APPROVED** [review]

File: cli/server.go [hunk 1]
```diff
@@ -127,6 +127,19 @@ func server() *cobra.Command {
...
+			// be interrupted by additional signals. Note that we avoid
+			// shadowing cancel() (from above) here because notifyStop()
+			// restores default behavior for the signals. This protects
+			// the shutdown sequence from abrubtly terminating things
+			// like: database migrations, provisioner work, workspace
+			// cleanup in dev-mode, etc.
+			//
+			// To get out of a graceful shutdown, the user can send
+			// SIGQUIT with ctrl+\ or SIGKILL with `kill -9`.
+			notifyCtx, notifyStop := signal.NotifyContext(ctx, interruptSignals...)
```
Comment (mafredri) [inline cli/server.go:140]: Note: Naming this `notifyCtx` here means that during startup, and interrupt signal won't abort the process up until we start listening `<-notifyCtx.Done()`.

The reason for this is that we have certain services that begin their shutdown procedure on context cancellation, but we want to control the order in which things are shut down.

I think it's acceptable that after starting, ctrl+c won't close `coder server` until the initial startup sequence is complete. But it's possible to work around this by monitoring the `notifyCtx` separately for parts of the startup where we want an early exit.

**Review by johnstcn — APPROVED** [review]

**Review by kylecarbs — APPROVED** [review]
