### PR TITLE
fix: add service banner to workspace page

### LINKED ISSUE #12379: UI: Service Banner is not shown on when selecting a workspace
When you navigate to a specific workspace eg: `https://coder.example.com/@michaelbrewer/myworkspace` the service banner is not visible.

Expected outcome would be that the service banner is always visible

Coder docs on service banner:
https://coder.com/docs/v2/latest/admin/appearance#service-banner

Looks like `site/src/pages/WorkspacePage/WorkspacePage.tsx` does not include a `<ServiceBanner />` see 

https://github.com/coder/coder/blob/7fbca62e087acd47c214f12b4735f40837ddbf47/site/src/pages/WorkspacePage/WorkspacePage.tsx#L107

### PR DESCRIPTION
**Pull request by michaelbrewer**
closes #12379

### CODE REVIEW

File: site/src/pages/WorkspacePage/WorkspacePage.tsx [hunk 1]
```diff
@@ -104,25 +105,28 @@ export const WorkspacePage: FC = () => {
...
   return (
-    <div css={{ height: "100%", display: "flex", flexDirection: "column" }}>
-      <Navbar />
-      {pageError ? (
-        <Margins>
-          <ErrorAlert
-            error={pageError}
-            css={{ marginTop: 16, marginBottom: 16 }}
+    <>
+      <ServiceBanner />
```
Comment (BrunoQuaresma) [inline site/src/pages/WorkspacePage/WorkspacePage.tsx:109]: I think the service banner should be included right before the `<Navbar />`

Comment (michaelbrewer) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:109]: Sure I can try that. I was emulating what the main layout was doing. But I can test both ways.

Comment (michaelbrewer) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:109]: Visually both ways works, so i go ahead the changes anyway. 

Here is how the service banner html looks like on all the pages using the `DashboardLayout.tsx`

Screenshot 2024-03-01 at 8 48 52 AM

This current PR with changes to `WorkspacePage.tsx`

Screenshot 2024-03-01 at 8 48 32 AM

What it would look like with the proposed changes, as you can see the banner dev would be in a new location

Screenshot 2024-03-01 at 8 53 08 AM

Comment (BrunoQuaresma) [reply site/src/pages/WorkspacePage/WorkspacePage.tsx:109]: Ahh I see, so we can leave it as it is. Thx for the changes.

**Review by BrunoQuaresma — APPROVED** [review]

**Review by aslilac — APPROVED** [review]
seems reasonable!
