### PR TITLE
fix: list templates returns non-deprecated templates by default

### LINKED ISSUE #17565: bug: Coder recommends deprecated templates to users
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

https://github.com/user-attachments/assets/3d629ff2-55b4-47e3-8fcf-0d8837163cc6

### Relevant Log Output

```shell

```

### Expected Behavior

Deprecated templates are not in "New Workspace" dropdown or the empty state of workspaces

### Steps to Reproduce

- Deprecate some templates
- Log in as a user with no templates

### Environment

- Host OS:
- Coder version: `main`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ssncferreira**
## Description

Modifies the behaviour of the "list templates" API endpoints to return non-deprecated templates by default. Users can still query for deprecated templates by specifying the `deprecated=true` query parameter.

**Note:** The deprecation feature is an enterprise-level feature

## Affected Endpoints
* /api/v2/organizations/{organization}/templates
* /api/v2/templates

Fixes #17565

### CODE REVIEW

**Comment by ssncferreira** [comment]
I have read the CLA Document and I hereby sign the CLA

File: coderd/database/dbmem/dbmem.go [hunk 1]
```diff
@@ -13021,7 +13021,7 @@ func (q *FakeQuerier) GetAuthorizedTemplates(ctx context.Context, arg database.G
 		if arg.ExactName != "" && !strings.EqualFold(template.Name, arg.ExactName) {
 			continue
 		}
-		if arg.Deprecated.Valid && arg.Deprecated.Bool == (template.Deprecated != "") {
+		if arg.Deprecated.Valid && arg.Deprecated.Bool != (template.Deprecated != "") {
```
Comment (cstyan) [inline coderd/database/dbmem/dbmem.go:13024]: I think a comment here might be useful as well. Initially I wanted to suggest renaming `arg.Deprecated` but I imagine that's a bigger change to roll out here. It's just not very nice to read this as something like 
```
if arg.Deprecated.Valid && arg.IgnoreDeprecated && template.IsDeprecated
```

potentially the template struct could be refactored to have `IsDeprecated` and `DeprecatedMessage` as opposed to just having `Deprecated` message whose value being `"some string"` means the template is deprecated. Alternatively, the template could have a function `IsDeprecated`?

File: enterprise/coderd/templates_test.go [hunk 2]
```diff
@@ -873,6 +873,241 @@ func TestTemplates(t *testing.T) {
 			require.Equal(t, tmpl.OrganizationName, org2.Name, "organization name on template")
 		}
 	})
+
+	t.Run("ListEmpty", func(t *testing.T) {
```
Comment (cstyan) [inline enterprise/coderd/templates_test.go:877]: can this new set of tests be table driven?

**Review by cstyan — COMMENTED** [review]
Some style/organization comments, but I'm not sure about all the details of the preferred style for Go and tests here so curious what others have to say.

File: coderd/database/dbmem/dbmem.go (hunk 1 above)
Comment (ssncferreira) [reply coderd/database/dbmem/dbmem.go:13024]: I agree that the current expression with `arg.Deprecated.Valid && arg.IgnoreDeprecated && template.Deprecated.Valid` isn't the most readable. 

Just for context: this method filters templates based on the `arg` param in the in-memory database used for testing. This logic ensures that only templates matching the requested deprecated state are returned.

The `Deprecated` field is of type `sql.NullBool`, which is represented as:
```
type NullBool struct {
	Bool  bool
	Valid bool // Valid is true if Bool is not NULL
}
```
So we need to check `Valid` to avoid misinterpreting a NULL as false.

The `template` is of type [`database.Template`](https://github.com/coder/coder/blob/main/coderd/database/models.go#L3030), generated by `sqlc`. 
I could add a method `IsDeprecated` to the `Template` struct to clean this up, but since that type is generated by `sqlc`, don't think it would be a good idea to add this type of custom logic directly at the DB layer. An alternative might be to define a wrapper around the generated type or introduce a view model in the service layer that handles this logic more cleanly but that may add more complexity than it solves, especially for a test-specific filter.

File: enterprise/coderd/templates_test.go (hunk 2 above)
Comment (ssncferreira) [reply enterprise/coderd/templates_test.go:877]: We could refactor this into a table-driven test, but I followed the existing style used in this file for consistency.

File: coderd/database/dbmem/dbmem.go (hunk 1 above)
Comment (johnstcn) [reply coderd/database/dbmem/dbmem.go:13024]: For readability I'd suggest a comment at most, or some light variable extraction. `dbmem` is only used for testing and it is planned to retire it at some point.

File: enterprise/coderd/templates_test.go (hunk 2 above)
Comment (johnstcn) [reply enterprise/coderd/templates_test.go:877]: I'd suggest also adding some equivalent tests for the AGPL templates list endpoint (see: `coderd/templates_test.go:444`).

File: enterprise/coderd/templates_test.go [hunk 3]
```diff
@@ -873,6 +873,241 @@ func TestTemplates(t *testing.T) {
...
+		bar := coderdtest.CreateTemplate(t, client, user.OrganizationID, version2.ID, func(request *codersdk.CreateTemplateRequest) {
+			request.Name = "bar"
+		})
+
+		ctx := testutil.Context(t, testutil.WaitLong)
+
+		// Should return only the deprecated templates
+		templates, err := client.Templates(ctx, codersdk.TemplateFilter{
+			SearchQuery: "deprecated:false",
+		})
```
Comment (johnstcn) [inline enterprise/coderd/templates_test.go:1022]: Potential copy-pasta comment here. This should only return **non-deprecated** templates.

Comment (ssncferreira) [reply enterprise/coderd/templates_test.go:1022]: Great catch! 👀  Updating...
```suggestion
		// Should return only the non-deprecated templates
		templates, err := client.Templates(ctx, codersdk.TemplateFilter{
			SearchQuery: "deprecated:false",
		})
```

File: enterprise/coderd/templates_test.go (hunk 2 above)
Comment (ssncferreira) [reply enterprise/coderd/templates_test.go:877]: Initially, I added the tests in `coderd/templates_test.go:444`. However, the deprecation feature is an enterprise-level feature, and the Deprecated field is part of the access control-related configuration which is handled by the `AccessControlStore` interface:
* AGPL template access control:
https://github.com/coder/coder/blob/af2941bb92306f00c2e7576ec9a0a36a298e603f/coderd/database/dbauthz/accesscontrol.go#L46-L69
* Enterprise template access control: https://github.com/coder/coder/blob/af2941bb92306f00c2e7576ec9a0a36a298e603f/enterprise/coderd/dbauthz/accesscontrol.go#L22-L32

One possible workaround would be to extend [`coderdtest.Option`](https://github.com/coder/coder/blob/main/coderd/coderdtest/coderdtest.go#L99) with a field to choose between the AGPL or enterprise `AccessControlStore`: https://github.com/coder/coder/blob/af2941bb92306f00c2e7576ec9a0a36a298e603f/coderd/coderdtest/coderdtest.go#L268-L270

However, since the enterprise tests already cover this logic, I opted to place the tests only in the enterprise folder. 
@johnstcn Does this make sense or am I missing something?

Comment (ssncferreira) [reply enterprise/coderd/templates_test.go]: As discussed moved the tests from `enterprise/coderd/templates_test.go` to `coderd/templates_test.go`: https://github.com/coder/coder/pull/17747/commits/b344266b675648b5ba1297901d097acfb95cf564

File: coderd/database/dbmem/dbmem.go (hunk 1 above)
Comment (johnstcn) [reply coderd/database/dbmem/dbmem.go:13025]: Reading this change a little more closely, doesn't this invert the query logic?

Comparing with the SQL:

```sql
	-- Filter by deprecated
	AND CASE
		WHEN sqlc.narg('deprecated') :: boolean IS NOT NULL THEN
			CASE
				WHEN sqlc.narg('deprecated') :: boolean THEN
					deprecated != ''
				ELSE
					deprecated = ''
			END
		ELSE true
	END
```

Aside: I've found it useful to comment the Go code in dbmem with the relevant parts of the corresponding SQL query.

File: enterprise/coderd/templates_test.go (hunk 2 above)
Comment (cstyan) [reply enterprise/coderd/templates_test.go]: > upon further inspection, the actual logic for checking whether a template should be shown or not based on its deprecated status is located in coderd/templates.go so the tests should go in the same place.

Just want to make sure I understand this comment, this is because in `templates.go` we're calling `GetAuthorizedTemplates` which in `modelqueries.go` passes `arg.Deprecated`?

Comment (johnstcn) [reply enterprise/coderd/templates_test.go]: Correct, look for the implementations of `AccessControlStore` and compare the differences between them. Essentially if you're changing either `EnterpriseTemplateAccessControlStore` or `AGPLTemplateAccessControlStore` then you'd want corresponding tests for that in `enterprise/coderd` or `coderd` respectively. All of the changes here were outside of `enterprise/`.

File: coderd/database/dbmem/dbmem.go (hunk 1 above)
Comment (ssncferreira) [reply coderd/database/dbmem/dbmem.go:13025]: I think the logic here aligns with the SQL query.
In the SQL, we filter as follows:
* If `deprecated` is set to `true`, we only include templates where `deprecated != ''`, i.e., there is a deprecation message.
* If `deprecated` is set to `false`, we only include templates where `deprecated = ''`, i.e., there is no deprecation message.
* If `deprecated` is not set (`NULL`), we include all templates (`ELSE true` clause).

In the in-memory logic we are doing an inverse filtering, the `continue` is used to exclude non-matching templates:
```
if arg.Deprecated.Valid && arg.Deprecated.Bool != (template.Deprecated != "") {
  continue
}
```
We skip templates when the `Deprecated` filter is set and the template's deprecation status **does not match** the `Deprecated` value. This mirrors the behavior of the SQL CASE logic, so I don’t believe the condition is inverted.

I think what’s confusing here is the double negation. I’ll improve the comment and maybe add a simple `isDeprecated` function for readability.

**Review by johnstcn — APPROVED** [review]

File: coderd/database/dbmem/dbmem.go (hunk 1 above)
Comment (cstyan) [reply coderd/database/dbmem/dbmem.go]: :+1: I like it
