### PR TITLE
fix: use signal-based sync instead of time.Sleep in sync test

### LINKED ISSUE #1376: flake: TestSyncCommands_Golden/start_with_dependencies
CI Run: https://github.com/coder/coder/actions/runs/22639933232
Failing job: https://github.com/coder/coder/actions/runs/22639933232/job/65613285949
Commit: 6acdd6ca7d3cd935a3c23c424a47acffafb50388 (Danielle Maywood) — fix: wire agents-tab-visible metadata to experiments flag (#22553)

Summary
`TestSyncCommands_Golden/start_with_dependencies` failed on Windows with a golden file mismatch. The output sometimes skips the expected “Waiting for dependencies…” line and only prints “Success”, indicating a timing-dependent flaky test.

Failure evidence
```
=== FAIL: cli TestSyncCommands_Golden/start_with_dependencies (0.28s)
    clitest.go:86: invoking command: coder --global-config C:\Users\ADMINI~1\AppData\Local\Temp\TestSyncCommands_Goldenstart_with_dependencies2007397451\001 exp sync start test-unit --socket-path \\.\pipe\com.coder.agentsocket_test.TestSyncCommands_Golden/start_with_dependencies.EB5P5CXMZFVKOTNIWWZ2JHK2RW
    golden.go:192:
        Error:       Should be empty, but was  string(
            -   "Waiting for dependencies of unit 'test-unit' to be satisfied...\nSuccess\n",
            +   "Success\n",
          )
        Messages:   golden file mismatch (-want +got): testdata\TestSyncCommands_Golden\start_with_dependencies.golden
```

Root cause classification
- Flaky test (timing): the test relies on `time.Sleep(100 * time.Millisecond)` to ensure the “Waiting…” line appears. On Windows, the dependency completes quickly enough that the waiting message is skipped, causing the golden mismatch.
- No data race / panic / OOM indicators found.

Assignment analysis
- Function-level blame (git blame -L) isn’t available via current tooling.
- Used `git log --oneline -10 --follow cli/sync_test.go` to find recent meaningful changes.
- Most recent relevant change: 1069ce6e “feat: add support for agentsock on Windows (#22171)” by Spike Curtis, which introduced/updated Windows sync behavior and touches this test file.
- Assigning to @spikecurtis for triage.

Related issues searched (none found)
- “TestSyncCommands_Golden”
- “start_with_dependencies”
- “exp sync”
- Closed issues updated in last 30 days with “TestSyncCommands”

Reproduction (best effort)
- Windows: `go test ./cli -run TestSyncCommands_Golden/start_with_dependencies -count=1`

Suggested next steps
- Make the test output deterministic (e.g., explicit synchronization/ready signal instead of fixed sleep) or relax golden expectations for the optional waiting line on fast paths.

### PR DESCRIPTION
**Pull request by mafredri**
The `start_with_dependencies` golden test was flaky on Windows CI. It used `time.Sleep(100ms)` in a goroutine hoping the `sync start` command would have time to call `SyncReady`, find the dependency unsatisfied, and print the "Waiting..." message before the goroutine completed the dependency.

On slower Windows runners, the sleep could finish and complete the dependency before the command's first `SyncReady` call, so `ready` was already `true` and the "Waiting..." message was never printed, causing the golden file mismatch.

This replaces the `time.Sleep` with a `syncWriter` that wraps `bytes.Buffer` with a mutex and a channel. The channel closes when the written output contains the expected signal string ("Waiting"). The goroutine blocks on this channel instead of sleeping, so it only completes the dependency after the command has confirmed it is in the waiting state.

Fixes https://github.com/coder/internal/issues/1376

Flake:
```
=== FAIL: cli TestSyncCommands_Golden/start_with_dependencies (0.28s)
    golden.go:192:
            Error: Should be empty, but was   string(
                   - "Waiting for dependencies of unit 'test-unit' to be satisfied...\nSuccess\n",
                   + "Success\n",
                   )
```

---

🤖 This PR was created with the help of Coder Agents, and reviewed by a human 🏂🏻.

### CODE REVIEW

**Review by kylecarbs — APPROVED** [review]

File: cli/sync_test.go [hunk 1]
```diff
@@ -330,3 +339,36 @@ func TestSyncCommands_Golden(t *testing.T) {
...
+	if w.signal != "" && strings.Contains(w.buf.String(), w.signal) {
+		w.closeOnce.Do(func() { close(w.matched) })
+	}
+	return n, err
+}
+
+func (w *syncWriter) Bytes() []byte {
+	w.mu.Lock()
+	defer w.mu.Unlock()
+	return w.buf.Bytes()
```
Comment (sreya) [inline cli/sync_test.go:373]: I feel like we've written this a thousand times, would be good to put it in some utility package

**Review by sreya — APPROVED** [review]

File: cli/sync_test.go (hunk 1 above)
Comment (mafredri) [reply cli/sync_test.go:373]: True, I'll put an agent on identifying the patterns and breaking it out. 👍🏻

Comment (sreya) [reply cli/sync_test.go:373]: Might also be better to call this SyncBuffer since you would assume a SyncWriter would accept an io.Writer

Comment (mafredri) [reply cli/sync_test.go:373]: Fair. Could go either way tbh, IMO syncWriter also works when it implements `io.Writer`. I'll merge this as-is and try to refactor into something better.
