### PR TITLE
fix: stop reading closed channel for `/watch` devcontainers endpoint

### LINKED ISSUE #19372: bug: devcontainers `/watch` endpoint reads from empty channel when message over 32KiB is received
## Problem

In the devcontainer `/watch` endpoint, we only allow a maximum message payload of 32KiB. If you have many devcontainers, or a devcontainer with many apps, this limit is easily reached. Once this happens, we fail to detect that the websocket has been closed and then send an empty message over the websocket to the site forever on loop.

## Solution

- Increase websocket payload limit
- Detect when the websocket channel is closed and close the websocket.

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Fixes https://github.com/coder/coder/issues/19372

We increase the read limit to 4MiB (we use this limit elsewhere). We also make sure to stop sending messages of `containersCh` becomes closed.

### CODE REVIEW

**Review by johnstcn — COMMENTED** [review]
If possible, I'd like to see a unit test or similar that reproduces the condition and validates the fix.

File: codersdk/workspacesdk/agentconn.go [hunk 1]
```diff
@@ -399,7 +399,8 @@ func (c *AgentConn) WatchContainers(ctx context.Context, logger slog.Logger) (<-
 	url := fmt.Sprintf("http://%s%s", host, "/api/v0/containers/watch")
 
 	conn, res, err := websocket.Dial(ctx, url, &websocket.DialOptions{
-		HTTPClient: c.apiClient(),
+		HTTPClient:      c.apiClient(),
+		CompressionMode: websocket.CompressionNoContextTakeover,
```
Comment (mafredri) [inline codersdk/workspacesdk/agentconn.go:406]: Should we add this to the containerapi side accept as well?

**Comment by DanielleMaywood** [comment]
> If possible, I'd like to see a unit test or similar that reproduces the condition and validates the fix.

I've added a test in https://github.com/coder/coder/pull/19373/commits/0ca20dc5bd7e1ddfc50fc87f5197fcdaaf62801b

If you remove the fix in `coderd/workspaceagents.go` you'll be able to test it fails before the fix and passes afterwards.

**Review by johnstcn — APPROVED** [review]
This looks OK to me, but I also wonder if there's a way for us to detect us reaching the payload limit and log an error somewhere?

**Comment by DanielleMaywood** [comment]
> This looks OK to me, but I also wonder if there's a way for us to detect us reaching the payload limit and log an error somewhere?

We already do but as a `debug` log

https://github.com/coder/coder/blob/0ca20dc5bd7e1ddfc50fc87f5197fcdaaf62801b/codersdk/wsjson/decoder.go#L41

**Comment by johnstcn** [comment]
> > This looks OK to me, but I also wonder if there's a way for us to detect us reaching the payload limit and log an error somewhere?
> 
> We already do but as a `debug` log
> 
> https://github.com/coder/coder/blob/0ca20dc5bd7e1ddfc50fc87f5197fcdaaf62801b/codersdk/wsjson/decoder.go#L41

Ah nice, so we can check for `StatusMessageTooBig` there and scream louder then. 👍 Might be a good separate PR

File: codersdk/workspacesdk/agentconn.go (hunk 1 above)
Comment (DanielleMaywood) [reply codersdk/workspacesdk/agentconn.go:406]: Sorry, I'm unsure what you mean

Comment (DanielleMaywood) [reply codersdk/workspacesdk/agentconn.go:406]: Oh nevermind, found it

File: codersdk/workspacesdk/agentconn.go [hunk 2]
```diff
@@ -411,6 +412,8 @@ func (c *AgentConn) WatchContainers(ctx context.Context, logger slog.Logger) (<-
 		defer res.Body.Close()
 	}
 
+	conn.SetReadLimit(1 << 22) // 4MiB
```
Comment (mafredri) [inline codersdk/workspacesdk/agentconn.go:422]: Nit: let's add a comment for this, as well as the compression, for posterity.

Re: compression, we might say that we chose nocontexttakeover to improve bandwidth cost/latency with minimal cpu/memory overhead even if contexttakeover  has better compression.

**Review by mafredri — APPROVED** [review]
Minor nit, but LGTM, nice work!
