### PR TITLE
fix: duplicate workspace update entries

### LINKED ISSUE #4317: audit: Two entries created for adding a auto-stop time of 1 hour
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

I added an auto-off setting to a workspace of 1 hour.

In the audit logs, it created 2 entries. The first entry does let me open it, to see the change.

Unfortunately it is in raw millisecond detail and not 1 hour like in the UI.

The unknown second audit log entry for this same event, cannot be opened.

image

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves #4317 

This was happening because we sent down two requests when we updated the workspace schedule form: 1) to `/autostart`, with an empty payload and 2) to `/ttl` with our updated auto-off. This was creating two audit logs, one without a diff.

This PR fixes the following

 - cleans up that errant, empty API call on the FE
 - makes sure the BE only creates log entries if there are actually diffs
 - filters out audit logs with 0 diffs on the FE so that users don't see these old, nonsense records

Before
Screen Shot 2022-10-12 at 9 37 32 AM

After:
Screen Shot 2022-10-12 at 9 37 11 AM

### CODE REVIEW

**Comment by Kira-Pilot** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Kira-Pilot** [comment]
recheck

File: coderd/audit/audit.go [hunk 1]
```diff
@@ -36,4 +38,6 @@ func (a *MockAuditor) Export(_ context.Context, alog database.AuditLog) error {
 	return nil
 }
 
-func (*MockAuditor) diff(any, any) Map { return Map{} }
+func (*MockAuditor) diff(any, any) Map {
+	return Map{"ttl": {"3600000000000", "7200000000000", false}}
```
Comment (Kira-Pilot) [inline coderd/audit/audit.go:42]: @coadler I'm attempting to mock out some diffs here so that our tests continue to pass. Is this kosher or no?

File: site/src/xServices/audit/auditXService.ts [hunk 2]
```diff
@@ -131,8 +131,12 @@ export const auditMachine = createMachine(
           }).then((data) => data.count),
         ])
 
+        // Filter out any logs that don't have an actual diff to present to the user
+        const filteredLogs = auditLogs.filter(
+          (log) => Object.entries(log.diff).length > 0,
+        )
```
Comment (Kira-Pilot) [inline site/src/xServices/audit/auditXService.ts:137]: @coadler I'm filtering out any logs with an empty diff on the FE to hide duplicate records. Is there a better way to clean these up? Will filtering these out have any unintended side effects, i.e. is it valid to have an audit log without diff content in any use case?

**Review by BrunoQuaresma — APPROVED** [review]
LGTM

File: site/src/xServices/audit/auditXService.ts (hunk 2 above)
Comment (coadler) [reply site/src/xServices/audit/auditXService.ts:137]: It's fairly likely that we'll have audit logs in the future that shouldn't have diffs, do I don't think we should try to hide them.

File: coderd/audit/audit.go (hunk 1 above)
Comment (coadler) [reply coderd/audit/audit.go:42]: I think it'd be confusing if all mock audit logs had a hardcoded ttl diff
