### PR TITLE
test: remove classic params from ephemeral params test

### LINKED ISSUE #19065: Dynamic parameters to allow default ephemeral parameters
Unit tests relying on default ephemeral parameter values are failing with dynamic parameter validation.

https://github.com/coder/coder/blob/0501cff814fdb9ea1e07dfc4f1993e2765647685/coderd/workspaces_test.go#L3846-L3846

### PR DESCRIPTION
**Pull request by Emyrk**
Dynamic parameters supports ephemeral parameters. Updated the test to use dynamic parameters.

Ephemeral params **require** a default value.
Closes https://github.com/coder/coder/issues/19065

### CODE REVIEW

File: provisioner/echo/serve.go [hunk 1]
```diff
@@ -650,6 +650,12 @@ func ParameterTerraform(param *proto.RichParameter) (string, error) {
 			s, _ := proto.ProviderFormType(v.FormType)
 			return string(s)
 		},
+		"hasDefault": func(v *proto.RichParameter) bool {
+			// Emit default when the value is explicitly non-empty,
+			// or when the parameter is ephemeral (ephemeral params
+			// always need a default, even if it's an empty string).
+			return v.DefaultValue != "" || v.Ephemeral
+		},
```
Comment (Emyrk) [inline provisioner/echo/serve.go:658]: Empty string is a valid default value. This used to work for classic params because no terraform validation was applied. And we used the echo provisioner. So the empty string was passed all the way through.

Dynamic params validate the terraform. And `default` is now a required field when `ephemeral` is true. So this change allows accepting the explicit empty string for these unit tests.

File: coderd/workspaces_test.go [hunk 2]
```diff
@@ -4372,9 +4372,7 @@ func TestWorkspaceWithEphemeralRichParameters(t *testing.T) {
 		}},
 	})
 	coderdtest.AwaitTemplateVersionJobCompleted(t, client, version.ID)
-	template := coderdtest.CreateTemplate(t, client, user.OrganizationID, version.ID, func(request *codersdk.CreateTemplateRequest) {
-		request.UseClassicParameterFlow = ptr.Ref(true) // TODO: Remove this when dynamic parameters handles this case
```
Comment (Emyrk) [inline coderd/workspaces_test.go:4376]: Dynamic params do handle this case

**Review by jaaydenh — APPROVED** [review]
