### PR TITLE
fix: add websocket close handling

### LINKED ISSUE #17508: Parameter: Broken websocket fails silently
When a parameter form is open, and the websocket fails/terminates. The form does not indicate this, and continues to be intractable, but fails to function.

The form state should be tied to the state of the websocket.

### PR DESCRIPTION
**Pull request by jaaydenh**
resolves #17508 

Display an error in the UI that the websocket closed if the user is still interacting with the dynamic parameters form

Screenshot 2025-04-23 at 17 57 25

### CODE REVIEW

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageExperimental.tsx [hunk 1]
```diff
@@ -107,6 +108,15 @@ const CreateWorkspacePageExperimental: FC = () => {
 				onError: (error) => {
 					setWsError(error);
 				},
+				onClose: () => {
```
Comment (jaaydenh) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageExperimental.tsx:111]: The assumption is that if the websocket closes while the component is mounted, that this is unexpected and we should inform the user with an error in the UI

File: site/src/pages/CreateWorkspacePage/CreateWorkspacePageExperimental.tsx [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import type { ApiErrorResponse } from "api/errors";
+import { DetailedError } from "api/errors";
```
Comment (aslilac) [inline site/src/pages/CreateWorkspacePage/CreateWorkspacePageExperimental.tsx:2]: merge these imports pls

**Review by aslilac — APPROVED** [review]
