### PR TITLE
fix(site): disable autostart and autostop according to template settings

### LINKED ISSUE #10930: disabling auto-start & stop fields at the template level does not update workspace fields
#10022 disables the input fields, but does not turn off the auto-start or auto-stop once it is disabled at the template level. here is an example, where i have a workspace with both auto-start and stop enabled, but disabled at the template level:

Screenshot 2023-11-28 at 16 04 14

### LINKED ISSUE #10931: autostart weekends are disabled at template level, but still selectable at workspace level
related #10930 

at the template level, i disabled workspace auto-start on the weekends here:

Screenshot 2023-11-28 at 16 07 01

but at the workspace level, i am still able to select weekends for auto-start:

Screenshot 2023-11-28 at 16 10 52

clicking the `Submit` button does not display any message, but I do receive a `204` API response in the browser console. in addition, the changes to the autostart selections are not persisted when navigating to another template tab, such as `Parameters`, even after clicking `Submit`.

### PR DESCRIPTION
**Pull request by Kira-Pilot**
resolves [#10930](https://github.com/coder/coder/issues/10930)
resolves [#10931](https://github.com/coder/coder/issues/10931)
Deployed a PR below

Disabling these fields on a template level:
Screenshot 2024-01-24 at 2 02 33 PM

will disable them on a workspace level (but will not reset any workspace values set before disablement):
Screenshot 2024-01-24 at 2 02 44 PM

Similarly, when specific days of the week are allowed to be configured per the template:
Screenshot 2024-01-24 at 2 04 48 PM

only those days of the week are enabled in the workspace settings:
Screenshot 2024-01-24 at 2 05 02 PM

### CODE REVIEW

File: site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx [hunk 1]
```diff
@@ -311,14 +315,14 @@ export const WorkspaceScheduleForm: FC<
           <Stack direction="row">
             <TextField
               {...formHelpers("startTime")}
-              disabled={isLoading || !form.values.autostartEnabled}
```
Comment (Kira-Pilot) [inline site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx:314]: I am not sure why we were looking at the form values here...I assume this was a typo.

Comment (BrunoQuaresma) [reply site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx:314]: I think it's because that's where the state of the form is. So if someone turns on autostart, this is the place to check its value.

**Review by BrunoQuaresma — APPROVED** [review]
LGTM +1 for tests!

**Comment by ericpaulsen** [comment]
thank you for this @Kira-Pilot - wanted to check whether this PR also addresses the below:

> in addition, the changes to the autostart selections are not persisted when navigating to another template tab, such as Parameters, even after clicking Submit.

File: site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx (hunk 1 above)
Comment (Kira-Pilot) [reply site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx:314]: Thanks for catching me here - I've fixed the attribute and added some test cases.
Down the road, we might want to reconsider the prop architecture of the form as it accepts `initialValues`, and one could try to disable `autostart` or  `autostop` using this prop, e.g. :
```
initialValues={{
  autoStartEnabled: false
  autoStopEnabled: false
}}
```
But this wouldn't affect the top toggle of each feature; only the secondary fields associated with them. So it's a bit of a bizarre API, but I'd rather not touch it in this PR.

**Comment by matifali** [comment]
That's great Kira. I noticed the week start day is different on Template and Workspace settings. It starts with Sunday vs Monday. Could you also align the week start day here?

**Comment by Kira-Pilot** [comment]
@matifali fixed!
@ericpaulsen thanks for pointing this out; I overlooked this part of the ticket. Fixed!
