### PR TITLE
fix: coderdtest: increase ForceCancelInterval

### LINKED ISSUE #3083: test bug: coderd/TestPatchCancelTemplateVersion/Success
In this unit test we check that the template verison job status is canceled but we do not assert that the error is nil when in fact we timed out cancelling the job. Seems related to the low value (25ms) of `ForceCancelInterval` in `coderdtest.NewProvisionerDaemon`.
This tripped us up when in #3061, so filing a follow-up issue for this.

image

EDIT: see also `coderd/TestPatchCancelWorkspaceBuild`

### PR DESCRIPTION
**Pull request by johnstcn**
Two `coderd` unit tests (`TestPatchCancelTemplateVersion/Success` and `TestPatchCancelWorkspaceBuild`) implied erroneously that the job was canceled successfully.

This is not the case, as these unit tests do not include a Provision_Complete response in the input to the
echo provisioner. Now explicitly checking the job error and bumping the force cancel interval to be longer.

I'm not sure if this is the "correct" fix here; I'm mainly unblocking https://github.com/coder/coder/pull/3061.
It seems that the "right" way would be to allow some way of modifying the contents of the test provisioner's job in-flight. 
For example in this use-case, we want to have the job initially returning only logs (implying in progress), and then also returning a complete after we cancel. 
There's another use case where we want the status quo, e.g. to test the force cancelation logic.

Fixes https://github.com/coder/coder/issues/3083.

### CODE REVIEW

File: coderd/templateversions_test.go [hunk 1]
```diff
@@ -150,8 +150,11 @@ func TestPatchCancelTemplateVersion(t *testing.T) {
 		require.Eventually(t, func() bool {
 			var err error
 			version, err = client.TemplateVersion(context.Background(), version.ID)
-			require.NoError(t, err)
-			return version.Job.Status == codersdk.ProvisionerJobCanceled
+			return assert.NoError(t, err) &&
```
Comment (mafredri) [inline coderd/templateversions_test.go:153]: Oh nice, TIL these could be used as booleans.

**Review by mafredri — APPROVED** [review]
As far as workarounds go, this looks OK to me. I'd like to defer to @spikecurtis for a correctness check though.

**Review by Kira-Pilot — APPROVED** [review]
Thanks for looking at this!

**Review by spikecurtis — APPROVED** [review]
