### PR TITLE
fix: fix coder template pull on Windows

### LINKED ISSUE #9291: `coder templates pull` does not work as expected on Windows
https://github.com/coder/coder/assets/22407953/08e57ccb-6c24-430c-8155-8f7e50a33443

It creates a folder, but no files

### PR DESCRIPTION
**Pull request by spikecurtis**
fixes #9291 and adds a unit test

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
👍  as along as CI is happy

File: cli/templatepull_test.go [hunk 1]
```diff
@@ -40,165 +40,218 @@ func dirSum(t *testing.T, dir string) string {
...
-		expected, err := echo.Tar(source2)
+	// create a tempdir and change the working directory to it for the duration of the test (cannot run in parallel)
+	dir := t.TempDir()
+	wd, err := os.Getwd()
+	require.NoError(t, err)
+	err = os.Chdir(dir)
+	require.NoError(t, err)
+	defer func() {
+		err := os.Chdir(wd)
 		require.NoError(t, err)
```
Comment (mafredri) [inline cli/templatepull_test.go:170]: An additional explanation to the required might be good here since this may break other tests if it fails for whatever reason.

**Review by mafredri — APPROVED** [review]

**Comment by mafredri** [comment]
> Unfortunately, extracting the tests out of a `t.Run()` subtest structure breaks the diff on GitHub. But, the new test can't be run in parallel, so it can't be a subtest...

Using the hide whitespace feature made it quite alright 👌

**Review by johnstcn — APPROVED** [review]

**Comment by matifali** [comment]
Tested here seems to resolve the issue.
```pwsh
PS C:\Users\matif\Downloads> .\coder_test.exe login https://pr9327.test.cdr.dev/
Your browser has been opened to visit:

        https://pr9327.test.cdr.dev/cli-auth

> Paste your token here:
> Welcome to Coder, coder! You're authenticated.
PS C:\Users\matif\Downloads> .\coder_test.exe templates ls
NAME        LAST UPDATED     USED BY
kubernetes  August 25, 2023  - active developers
PS C:\Users\matif\Downloads> .\coder_test.exe templates pull kubernetes
Extracting template to "kubernetes"
PS C:\Users\matif\Downloads> ls .\kubernetes\

    Directory: C:\Users\matif\Downloads\kubernetes

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          25/08/2023 12:16 pm           2489 .terraform.lock.hcl
-a---          25/08/2023 12:16 pm           8147 main.tf
```

**Review by matifali — APPROVED** [review]
tested in a PR deployment and seems to resolve the issue.
