### PR TITLE
fix: prevent workspace search bar text from getting garbled

### LINKED ISSUE #9547: Filter input flickers when typing fast
typing fast into the filter field will usually get garbled as i think the xhr returns the search and updates the field again. not sure if its workspace quantity related, but we're only at 74 workspaces right now.

### PR DESCRIPTION
**Pull request by buenos-nachos**
Closes #9547 
Addresses main issue where the text in the workspaces search bar would periodically get garbled, especially if you kept typing very fast.

## Changes made
- Replaced `debounce-it` usage for the page with a home-spun `useDebouncedFunction`
   - The library's debounce utility assumes it's called in regular JavaScript, so it kept creating a brand new stateful function on every single render. That was splitting up all the debounced calls, instead of having them go to one centralized place
   - There are still other parts of the codebase that need to have this swap made; will open a new issue shortly about getting those areas updated (changes were out of scope for this PR)
   - Hook has tests in place, too, just to give us more confidence when we use it in the future.
- Reorganized some of the code and also added a few extra checks to minimize risks of accidental state desyncs between the search bar state and the global query state that it's based off of

## Other notes
- Accidentally got confused when I was learning the codebase (lowercase `filter.tsx` vs uppercase `Filter.tsx`), and refactored a file that didn't really need changes. Functionality is the same; it was a pure refactor.
  - Will be more dutiful about making sure PRs don't touch any unnecessary files in the future

### CODE REVIEW

**Comment by Parkreiner** [comment]
I have read the CLA Document and I hereby sign the CLA

File: site/src/components/Filter/filter.tsx [hunk 1]
```diff
@@ -150,20 +141,42 @@ export const Filter = ({
...
+  learnMoreLink,
+  learnMoreLabel2,
+  learnMoreLink2,
+  presets,
+}: FilterProps) => {
+  // Storing local copy of the filter query so that it can be updated more
+  // aggressively without re-renders rippling out to the rest of the app every
+  // single time. Exists for performance reasons - not really a good way to
+  // remove this; render keys would cause the component to remount too often
+  const [queryCopy, setQueryCopy] = useState(filter.query);
```
Comment (BrunoQuaresma) [inline site/src/components/Filter/filter.tsx:161]: Maybe we could use `useRef`?

**Review by BrunoQuaresma — APPROVED** [review]
Really good one, just one minor comment.
